### ISSUE TITLE
Please add "sign in with google" feature

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1010]

**Comment by shayek** [comment]
Here is a comprehensive tutorials https://developers.google.com/identity/

**Comment by roundhill** [comment]
Good idea! You can sort of do this via `Sign in with WordPress.com`, because it supports `Sign in with Google`. But then you also get a WordPress account ;)

**Comment by Donboscow** [comment]
Boss any estimated time of arrival for this feature? @mirka

**Comment by Donboscow** [comment]
Alright, that is nice to hear from you. Thank you! @mirka

**Comment by Donboscow** [comment]
Any ETA? @bummytime

**Comment by Donboscow** [comment]
Any possible ETA? @mirka @bummytime @belcherj

**Comment by bummytime** [comment]
@Donboscow I am happy to say this **is** part our upcoming roadmap for Simplenote. However, I can't provide an exact ETA at this time...the best I could do is say sometime between Q4 2019 and Q2 2020. 😄

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
