### ISSUE TITLE
Feature Request  : Add Folder Support

### ISSUE THREAD

**Issue by baraa272** [Automattic/simplenote-electron#1019]
Windows Store Version Here 
Hi and glad to use the program 
Anyway 
It would really be efficient to add folders support For more effecient sort of the notes 
Because Actually having tags only will lead to huge amount of tags and it would be difficult to organise them all 
So folders will be actually better I think 
Thanks for reading

**Comment by mirka** [comment]
Thank you for the feature request! I'm afraid we are not considering folder support at this time (see also #288 #432). However, we are looking into ways to make tags better (sorting, searching, etc.) so it can cover more organizational needs without adding a layer of complexity that a folder structure would bring.
