### ISSUE TITLE
Keep tag panel open

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/simplenote-electron#1027]
We had a request (1576723-zen) that in Linux, the tag panel would be able to stay open, rather than automatically slide closed.

I don't have Linux myself so I can't test/take screenshots, but I noticed a screencast in a comment on the P2 testing call from Oct 9th which clearly showed the tag panel automatically sliding shut.

I believe it would be appreciated if there was an option to hold the panel open :)

**Comment by mirka** [comment]
Closing in favor of #433
