### ISSUE TITLE
Move CoreImporter.importNotes (plural) into SimplenoteImporter

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#1034]
It would probably be better to have SimplenoteImporter take care of adapting the Simplenote export data to the core import format. Then we can keep CoreImporter focused on being the core importer. 

Also by calling `CoreImporter.importNote()` directly in SimplenoteImporter, we would be able to keep track of the per-note progress better.

**Comment by belcherj** [comment]
Closing as we will not tackle this work soon.
