### ISSUE TITLE
Large naming inconsistencies (and a typo) in denotation of architecture in builds

### ISSUE THREAD

**Issue by justinkterry** [Automattic/simplenote-electron#1038]
While PR #809 standardized the names across releases by making the builds automating the builds in the CI, the names used (at least in 1.2.1) still have problems:

You call the 32 bit builds 'i386' for the appimage and deb builds, 'ia32' for the windows build and linux tar.gz build, and concerningly 'i**6**86' in your rpm builds.

You call the 64 bit build 'amd64' for the deb, 'x64' for the linux tar.gz build, 'x86_64' for the appimage and rpm builds.

For the windows builds, you label the appx build as 'ia32', and don't label the .exe at all, which also needs to be fixed (are you only releasing 32 bit builds for windows or something?)

Please change the CI to stick to a consistent naming convention (the most common one being i386 and amd64), and fix whatever's going on with the windows build labeling.

**Comment by lehasb** [comment]
I'd like second this, and add that the 'amd64' name in particular is very confusing. x86_64 is more commonly understood.

**Comment by justinkterry** [comment]
@mirka 

This is still tagged as "needs review"?

**Comment by justinkterry** [comment]
Any updates here?

@mirka

**Comment by belcherj** [comment]
These are the architecture names that come from Electron Builder. To make this change we would want the change to come from upstream. 

https://github.com/electron-userland/electron-builder/blob/cd28eb093f0bf5969ad87c64773cc0714dc8d8ea/packages/builder-util/src/arch.ts#L7
