### ISSUE TITLE
Preview icon disappears when switching to Trash with Markdown enabled in the Windows app

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-electron#1040]
This is a user report - 1594008-zen

#### Steps to reproduce

1. Enable Markdown in the app
2. Switch to **Trash**
3. Switch back to the editor

#### What I expected

The Preview icon should persist despite changing views from the note editor to Trash, and back again.

#### What happened instead

The Preview icon disappeared. It only returned when selecting another note.

#### Simplenote version

Version 1.2.1

#### OS version

Windows 7

#### Screenshot / Video

Requested from the user.

**Comment by Piyopiyo-Kitsune** [comment]
More notes and screen shots from the user:
**Markdown enabled** - you can see the Preview icon on the right-hand side.
**Tag icon** - clicking on the Tag icon slides the panel open. The Preview icon is still visible (far right) at this point.
**Select Tag** - If you select a tag (I just clicked on All Notes for ease of explanation), the Preview icon disappears.
**Select Note** - The preview icon reappears.

![image](https://user-images.githubusercontent.com/17694715/48982045-24e9e580-f092-11e8-98ed-6d2160a729dc.jpeg)
![image 1](https://user-images.githubusercontent.com/17694715/48982046-24e9e580-f092-11e8-832b-50f49bb2f19e.jpeg)

**Comment by mirka** [comment]
I confirmed this as occuring in v1.2.1, but was fixed by #884. So this should be fixed in v1.3.0 and higher 👍

**Comment by Piyopiyo-Kitsune** [comment]
Thanks @mirka! Sent a follow up to the user in 1629283-zen
