### ISSUE TITLE
View more than one tag at the same time via the UI?

### ISSUE THREAD

**Issue by sprite-1** [Automattic/simplenote-electron#1043]
I would like to request for a way to list down multiple tags at the same time via the UI. I understand that this can be achieved by doing `tag:note1 tag:note2` etc on the search but it would make it easier to find the notes we're looking for if we can click it directly on the UI, for example by holding down Ctrl to select multiple tags at the same time.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
