### ISSUE TITLE
Handle inline styles in ENML to Markdown conversion

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#1044]
It would be nice if the [ENML to Markdown converter](https://github.com/Automattic/simplenote-electron/blob/master/lib/utils/import/evernote/enml-to-markdown.js) could handle inline styles for bold and italics.

So something like this

```
<span style="font-weight: bold;">Bold text</span>
```

would be converted to `**Bold text**`.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
