### ISSUE TITLE
Option to hide the menu bar?

### ISSUE THREAD

**Issue by sprite-1** [Automattic/simplenote-electron#1047]
When using the dark theme, it's a bit jarring to see the light menu bar on top (in Windows 10). I get that this may be a system limitation that prevents the menu bar color from being changed too along with the rest of the UI so I propose to instead add an option to hide the menu bar. Pressing `Alt` should show it again for quick access and hide again afterwards.

(Firefox has this kind of behavior where if you press `Alt`, the hidden menu bar shows up and if you do anything like click on the UI or go to any menu, it closes again.)

**Comment by mirka** [comment]
Thanks for the request! Closing in favor of #293
