### ISSUE TITLE
Re-order Accented Characters Alphabetically

### ISSUE THREAD

**Issue by sdixon194** [Automattic/simplenote-electron#1050]
Presently, accented characters are listed after Z when you sort alphabetically, and when you search for keywords with accented characters, the app doesn't find the notes that contain those keywords written with non-accented characters (and vice versa).

Would be great to have better search functionality for accented characters. 

1598900-zen

**Comment by mirka** [comment]
Thanks! I posted the "search" part as a separate issue (#1143), since this is handled differently from the "sort" part.
