### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by lucamosca1** [Automattic/simplenote-electron#1051]
Not sure if this is the right place to raise this issue but I try anyway. I just installed simplenote as a snap on Fedora 29 but with the standard wayland session the application doesn't start.

https://github.com/snapcrafters/simplenote/issues/17
https://forum.snapcraft.io/t/simplenote-snap-doesnt-start-on-fedora-29/8683

**Comment by mirka** [comment]
Hi there! I don't think there's anything we can do about it on our side (it's either a compatibility issue involving Electron or Snapcrafters). Feel free to reopen if you find out otherwise.

**Comment by goduck777** [comment]
I hope you can reopen this issue. Electron 12 now has native wayland support. I have tried to change package.json to use electron 12, and simplenote can successfully run in wayland.

However, with the development build I cannot use my own account. I hope you can have electron 12 in your next release, or just relax this limitation so I can build a production version myself.
