### ISSUE TITLE
Spell Check on Windows 10

### ISSUE THREAD

**Issue by geezzeer** [Automattic/simplenote-electron#1056]
#### Steps to reproduce
1.
2.
3.
4.

**Comment by mirka** [comment]
Thanks for the report. Could you see if the new v1.3.0 is working for you?

**Comment by geezzeer** [comment]
Miriam,

Thanks for the reply and for the advice. I thought I was on the latest version, but ...

Now that I'm on v1.3.0, I'm getting spellcheck on Windows 10.

Thanks again!

**Comment by mirka** [comment]
No worries, v1.3.0 was released just around the time you posted this issue 🙂
