### ISSUE TITLE
Simplenote 1.3 is very slow on my end

### ISSUE THREAD

**Issue by henriiquecampos** [Automattic/simplenote-electron#1057]
#### Steps to reproduce
1. Download and install Simplenote 1.3
2. Try to do any task at all

#### What I expected
I'd expect to have an user experience equal to or better than with 1.2.1

#### What happened instead
Every single interaction takes at least 4seg to actually process. Super duper slow.

#### Simplenote version

Simplenote-linux-1.3.0-x86_64.AppImage and also Simplenote-win-1.3.0.exe

#### OS version
Both Windows 10 x64 and Solus Gnome x64 current

#### Screenshot / Video

![simplenote](https://user-images.githubusercontent.com/10171059/49248022-e6408c00-f3ff-11e8-80de-0dab3517641b.gif)

**Comment by sprite-1** [comment]
Oh, I thought it was just my laptop being stupid but yeah, I did feel that performance hit and remember the previous versions to be a lot faster and more responsive.

**Comment by djordjeandrejevic** [comment]
Happens to me too. I've immediately noticed slight delay even when switching notes. It wasn't as snappy as the last version. The thing that completely blocked application is the search functionality - I had to manually kill Simplenote process. Downgraded to 1.2.1.

**Comment by sprite-1** [comment]
@henriiquecampos do you know how to disable the update prompt? I rolled back to 1.2.1  too but it keeps asking me to update which gets kinda annoying.

**Comment by roundhill** [comment]
Hmm it ran ok during our internal testing... do y'all see anything interesting in the console? You can access it at Help -> Advanced -> Debugging Console and then click on the Console tab.

**Comment by henriiquecampos** [comment]
@roundhill this is what I get on windows 10

![image](https://user-images.githubusercontent.com/10171059/49318630-6d653100-f4e0-11e8-961d-f08df0033a5b.png)

**Comment by roundhill** [comment]
Thanks @henriiquecampos, that's some serious lag there! I'm wondering if it is something in your notes, do you have any notes that are really large? I'm also curious if it helps if you disable the spell checker in the Edit menu?

**Comment by henriiquecampos** [comment]
> I'm wondering if it is something in your notes, do you have any notes that are really large

I don't think so...the bigger one is about 3k words, with 2 images. But everything was smooth in 1.2.1

>I'm also curious if it helps if you disable the spell checker in the Edit menu?

Just checked it off, still lagging 😢

**Comment by ddwagner** [comment]
Chiming in to say same problem. Happened on both linux (Mint, trusty I think) and Windows 10 updated to 1.3.2. Similar console output as above (i.e., mousedown handler took 1349ms). Going to downgrade to 1.2.1.

**Comment by roundhill** [comment]
Would one of you mind creating another Simplenote account and see if it has the same lag issue? Just trying to isolate if it is something with your notes or if it is something else.

**Comment by ddwagner** [comment]
I just did that. New account was back to being snappy and first. Logged out and reloaded my original account and it's molasses down to being unresponsive (I'm currently stuck in a tag and can't get out of it). I don't feel like I have a tremendous amount of notes. Maybe 20 tages. Each with 4-5 notes. Just text, maybe one image embedded somewhere in there). 

I am finding one oddity, which is that certain tags are way slower than others. (one only has 4 notes, simple text). The other tags are reasonably snappy, possibly as good as 1.2.1. But I've found 3 tags that are slow as hell. Can't find much in the notes that would make them any different than the others. Maybe there's a note or two in there that are slightly longer. All notes view is incredibly slow. I think I ruled out long notes as I just moved two of the notes from the slow tag to a new tag and that tag is also slow even though these two notes are tiny. Just a few words. Hope that helps.

**Comment by roundhill** [comment]
I think I'm on to something here. Do y'all have a lot of Markdown notes?

**Comment by roundhill** [comment]
Would one of you mind testing this Windows build?

https://ci.appveyor.com/api/buildjobs/ptjvuhvjwo7wrr73/artifacts/release%2FSimplenote-win-1.3.3.exe

It should fix the issue. Looks like a module we used to strip Markdown caused the lag.

**Comment by henriiquecampos** [comment]
@roundhill YES! 

It is working with no (noticeable) lag now! 🎉 

Thanks for the support! 📝 ❤️

**Comment by roundhill** [comment]
😎 We'll get this fix out in the 1.3.4 update, probably Monday or Tuesday.

**Comment by ddwagner** [comment]
My notes are exclusively in markdown (it's why I switched to simplenote!). The new build works much better. Thanks for fixing the issue!

**Comment by sprite-1** [comment]
I don't quite understand how the profiler works for this but I gave it a go and this was the result after clicking around my notes (on 1.3.3)

![image](https://user-images.githubusercontent.com/33685433/49643694-55962b80-fa51-11e8-9bfd-6db2bceb470a.png)

**Comment by roundhill** [comment]
@henriiquecampos we think we found a nice workaround for the bug that still allows the markdown to be stripped from the notes list, could you test one more build to be sure that it works well for you?

https://ci.appveyor.com/api/buildjobs/yrpuw3qsi7c8wbq0/artifacts/release%2FSimplenote-win-1.3.3.exe

**Comment by henriiquecampos** [comment]
@roundhill sorry for the lag, I don't use windows very often :P 

Seems to be working smoother! I think this is the, noticeable, performance we had with 1.2 ❤️

**Comment by mirka** [comment]
Thanks for testing! We'll be releasing this soon.
