### ISSUE TITLE
Note display preview but (if note contains '*/*')

### ISSUE THREAD

**Issue by habi** [Automattic/simplenote-electron#1060]
#### Steps to reproduce
Write a note containing a title and `*/*.log` (actually some more, but this is the minimal example)

#### What I expected
Preview on the left shows what I typed.

#### What happened instead
Preview on the left shows Title and '/.log' below (also compare attached screenshots)

#### Simplenote version
Version 1.3.0

#### OS version
OS X 10.12.6 (16G1618)

#### Screenshot / Video
![redacted screenshot showing the issue](https://user-images.githubusercontent.com/1651235/49297260-a7bbd780-f4ba-11e8-92a3-8f1dfb2c2d1a.png)
![redacted screenshot showing how it should look](https://user-images.githubusercontent.com/1651235/49297261-a7bbd780-f4ba-11e8-83f4-7a4132fcddf5.png)

**Comment by habi** [comment]
Funnily, also GitHub munges '*/*'.log

**Comment by mirka** [comment]
Thanks for the report!

I think this is expected behavior, because we are stripping Markdown tags in the note list excerpts for better readability. The sequence `*/*` is going to be interpreted as `<em>/</em>`, not as a literal `*/*`. You can either turn off Markdown for that note, or use backticks like you did for this textarea 🙂

**Comment by habi** [comment]
BTW: The problem is *not* seen in the Linux version of Simplenote...

**Comment by mirka** [comment]
> The problem is _not_ seen in the Linux version of Simplenote

Hmm, that's strange. v1.3.0 on Linux is giving me the exact same behavior.

**Comment by habi** [comment]
Simplenote 1.2.0 did *not* show the problem, version 1.3.0 *does* show it :)

**Comment by mirka** [comment]
Yes, that sounds correct. We added the Markdown-stripping (#996) in v1.3.0.
