### ISSUE TITLE
Entering tags with Chinese characters failing

### ISSUE THREAD

**Issue by JohnAD** [Automattic/simplenote-electron#1061]
This is addition to the problems fixed in Issue #696

A user reported problems with the Windows electron app; specifically either the tag input being ignored; or in the case of using Microsoft Pinyin IME, multiple characters appearing rather than one. The user was able to repeat the problems after upgrading to v1.3.0.

However, this specific ticket is for the Linux version, which is also having problems for Chinese tag input. I do not have access to a Windows PC but am happy to help with this from the context of the Linux problem.

#### Steps to reproduce
1. Started simplenote and edited a note.
2. Pressed key (shift-ctrl-space for me) to switch to Chinese keyboard input (`fctix` using `google-pinyin`)
3. clicked in tag field and typed `ni hao` which is pinyin for 你好 
4. pressed space to get to the next word. Also tried pressing enter instead.

#### What I expected
The 你好 characters appear in the tag field.

#### What happened instead
Saw a series of other characters. I don't know Chinese so I can't identify them; see the animated GIF.

#### Simplenote version
v1.3.0

#### OS version
Linux Mint 18.3

#### Screenshot / Video

The following animated GIF shows the main note body receiving "ni hao" correctly, then two attempts to enter the same information into the tag field.

![peek 2018-11-30 14-31](https://user-images.githubusercontent.com/5799303/49313895-54438c80-f4ae-11e8-9594-377387f164c4.gif)

**Comment by roundhill** [comment]
This is already fixed in the next release (1.3.2)

See #999
