### ISSUE TITLE
Notes disappear at strtup in 1.3.0

### ISSUE THREAD

**Issue by igorkulman** [Automattic/simplenote-electron#1063]
#### Steps to reproduce
1. Open the app

#### What I expected

List of my notes

#### What happened instead

The list disappears after a split second and is empty.

#### Simplenote version

1.3.0

#### OS version

Windows 10

#### Screenshot / Video

![sn](https://user-images.githubusercontent.com/4746070/49328376-de075e80-f56f-11e8-978c-1ec7f143c77d.gif)

**Comment by roundhill** [comment]
Hi @igorkulman, a build server misconfiguration caused an issue with the app we submitted to the Windows Store. We've submitted an update to Microsoft for certification, but it isn't approved yet.

You can download a working update from here in the meantime: https://github.com/Automattic/simplenote-electron/releases/tag/v1.3.0

Our apologies!
