### ISSUE TITLE
Note Listing and Tags dissapear after opening Windows UWP and Electron version

### ISSUE THREAD

**Issue by Ymetro** [Automattic/simplenote-electron#1066]
#### Steps to reproduce
1. Open the app. 

#### What I expected
The app showing my notes, ready to be edited. 

#### What happened instead
Note title list disappears right before my eyes. Then none of the 144 are showing. See added GIF video in the Screenshot / Video section. 
Tags disappeared as well. 
Emptiness everywhere! 
The same happens every time when opening the app. First, it showed in the UWP app and now the Electron app does this as well, so I am guessing it has to do with the installation on my computer. 

#### Simplenote version
Windows Electron 1.3.0 from GitHub

#### OS version
Windows 10 version 1809 build 17758.1
Why is the UWP app taken down from Microsoft Store? I cannot find it in the Dutch store.

#### Screenshot / Video
![simplenote hides all notes 360](https://user-images.githubusercontent.com/30724400/49443094-bf9d9f00-f7cb-11e8-993b-ca9db0825ec5.gif)
Plus an error in the console:
![schermopname 38](https://user-images.githubusercontent.com/30724400/49443162-fecbf000-f7cb-11e8-8146-0ea81a40bd98.jpg)

**Comment by Ymetro** [comment]
O dear: I did not expect the GIF run so slow in a browser! I made a full HD MP4 capture, masked private info and converted it in GIMP with GAP and exported it to 360p, but still at 60 fps. When downloaded the full speed is shown in Irfanview at least.

**Comment by roundhill** [comment]
Hi @Ymetro we released a 1.3.1 update that should fix this issue. Can you check for it in the Windows Store?

**Comment by Ymetro** [comment]
Installed it from the Microsoft Store and its version number says 1.3.1, but the note list is still disappearing after a second, exactly as shown above. Console still gives the same error:
![folded out console error](https://user-images.githubusercontent.com/30724400/49476949-a1f82600-f81b-11e8-8677-5700114ecb26.jpg)

**Comment by Ymetro** [comment]
That seems to have fixed it! Great!
One other thing: Had sync problems with the iPhone app as well (not showing contents, only tags and the white theme, instead of my chosen dark theme). Did what you mentioned and it now works like a charm again. Thank you.
