### ISSUE TITLE
Add note templates

### ISSUE THREAD

**Issue by JustMaier** [Automattic/simplenote-electron#1072]
I'm a big fan of the simplicity of Simplenote. Previously I'd use text documents to keep notes, but the portability/cross-platform nature of Simplenote is just so much better.

One thing I've started doing recently requires a common format for a particular set of notes. Rather than having to keep the template and copy and paste whenever I want to use it, it'd be really neat if notes tagged with `template` could be selected as a starting point when creating a new note.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by samtuke** [comment]
I'm also missing this. Several times every day for the last 2 years or so I've started the title of each note with the current date, eg `2021-04-28 ...` so all my note titles are like `2021-04-28 Investor meeting`. That makes it easier to copy titles to filenames when I save them separately, and also just to understand notes chrolologically when listed in SN following search etc. (and also as a namespace for notes with the same title, actually, eg `2021-04-28 standup` vs `2021-04-29 standup`).
