### ISSUE TITLE
Update over old version installed another separately

### ISSUE THREAD

**Issue by abhijithvijayan** [Automattic/simplenote-electron#1074]
#### What I expected
Update to new version

#### What happened instead
- Repeated Prompt to update when opened Simple Note app.
- Left 2 versions of simple note

#### Simplenote version
v1.1.7
v.1.3.2

#### OS version
Windows 10 1803

#### Screenshot / Video
![](https://i.imgur.com/C29pEH1.png)

**Comment by mirka** [comment]
There has been some recent changes in how we handle updates.

Could you try:

1. Uninstall v1.1.7
2. Uninstall v1.3.2
3. Install the [latest release](https://github.com/Automattic/simplenote-electron/releases/download/v1.3.3/Simplenote-win-1.3.3.exe)

and see if the problem persists?

**Comment by KshDi13** [comment]
I have  the same issue. Updated PC version when prompted and now it's left both a 1.1.x version that i cannot log into (incorrect login credentials it says) and the new updated 1.3.x version (which works but slow).

**Comment by abhijithvijayan** [comment]
[Fixed] for now.

**Comment by mirka** [comment]
@KshDi13 

> the new updated 1.3.x version (which works but slow).

You might be experiencing #1057. This will be fixed by #1073 (will be released soon as v1.3.4).
