### ISSUE TITLE
simplenote stays at a disconnected screen Windows 10

### ISSUE THREAD

**Issue by Atm0n** [Automattic/simplenote-electron#1077]
#### Steps to reproduce
1. Buy a secondary screen
2. connect the screen
3. open simplenote and move it to the second screen
4. Disconnect your sescond screen
5. MAGIC you now can't acces to simplenote because it thinks that a secondary screen is avaiable

#### What I expected
I expected the program to move to the active screen when no second screen avaiable

#### What happened instead
ghost screen resulting on not beeing able to use simplenote

#### OS version
Windows 10

#### Screenshot / Video
Not necessary

**Comment by mirka** [comment]
I tried this with my Windows 10 machine and couldn't reproduce. I'm inclined to think this is a display setup problem, or maybe a bug in [Electron itself](https://github.com/electron/electron).

To isolate the cause, you could try to see what happens with [other Electron apps](https://electronjs.org/#apps). Let us know if it only happens with Simplenote.
