### ISSUE TITLE
Clicking in note editor causes two render() calls in notes list

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#1079]
From: https://github.com/Automattic/simplenote-electron/pull/1078#issue-236655410

We should audit the app to see what is causing multiple render() calls to happen when clicking within the note editor.

- [ ] Test 1
- [ ] Test 2

**Comment by dmsnell** [comment]
Closing as not relevant anymore. Probably resolved by #2148 if it was still an issue previously.
