### ISSUE TITLE
Pointer moving randomly 

### ISSUE THREAD

**Issue by WolfyLPDC** [Automattic/simplenote-electron#1080]
I have a very strange bug in Linux since the last updates that makes pointer to go crazy. I have not read all the Issues so perhaps it is something common, but it's really frustrating. 

#### Steps to reproduce
1. Open Simplenote
2. Open/Create a Note
3. Write a bit

#### What I expected
A simple tipping as it is mean to be done.

#### What happened instead
Since the 1.32 update (or before), a lot of times (I'm talking of more than 5 times per minute) the pointer gets crazy and I start to write in another line or at the end of the file or things like that. It is very strange and frustrating. 

It happens only on one of my Linux PCs. I use KDE in all of them. 

#### Simplenote version
Currently 1.33

#### OS version
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

#### Screenshot / Video
I do not have any. Sorry.

**Comment by mirka** [comment]
Thanks for the report! There seems to be some issues with cursor positioning. Closing in favor of #36
