### ISSUE TITLE
Windows 7 app not synching 

### ISSUE THREAD

**Issue by eurello** [Automattic/simplenote-electron#1086]
A customer reports that notes aren't synching from his Windows 7 device. He is using version 1.3.2 of the app, and the changes do not appear in the web app. 

He also uses Simplenote on a Windows 10 and an iOS device, and has no trouble with sync from those. 

I'm not sure what additional questions to ask to further dig into what could be causing this. 

#1619717-zen

**Comment by mirka** [comment]
@eurello Can they try this on their Windows 7 device?

1. Export their notes, just to make sure they aren't lost.
1. Uninstall Simplenote and reinstall.
1. Log in again.

**Comment by eurello** [comment]
I've asked them to try that -- thank you!
