### ISSUE TITLE
Confirm Delete

### ISSUE THREAD

**Issue by jlarne** [Automattic/simplenote-electron#1087]
A handy still 'simple' feature sould be the inclusion of an option to be able to 'confirm before delete'.  I have had some moments where, with a bit of network delay, two notes were delete that were in order in my list.  This would be a good option, or options both for initially sending to the trash as well as for permanent deletion.

**Comment by mirka** [comment]
Related: #571

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
