### ISSUE TITLE
simplenote Simplenote-linux-1.3.3-i386.deb and Simplenote-linux-1.3.2-i386.deb doesn't start

### ISSUE THREAD

**Issue by YKastell** [Automattic/simplenote-electron#1092]
#### Steps to reproduce (exactly the same for 1.3.2 and 1.3.3
1. install Simplenote-linux-1.3.2-i386.deb on Ubuntu Mate 18.04 LTS with GDebi 0.9.5.4
2. no install error message
3. try to launch : hourglass appears for a while
4. nothing happens Simplenote does not start
5. remove simplenote 3.2 with GDebi
5. reinstall 3.0

#### Simplenote version
las version Working : 1.3.0 (never seen a 1.3.1 ?)

#### OS version
Ubuntu Mate 18.04 LTS on a Lenovo Yoga 2

#### Screenshot / Video
N/A

**Comment by hieutle2011** [comment]
Same problem with Ubuntu 16.04 LTS. After installing Simplenote-linux-1.3.2-i386.deb, simplenote doesn't start. I have installed the newer version Simplenote-linux-1.3.3-i386.deb but nothing appears.

**Comment by mirka** [comment]
Does the [64-bit version](https://github.com/Automattic/simplenote-electron/releases/download/v1.3.3/Simplenote-linux-1.3.3-amd64.deb) work?

I believe Lenovo Yoga 2 is 64-bit, and it might take [extra configuration](https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit) for 32-bit apps to run on it.

**Comment by YKastell** [comment]
Hi, 
didn't try 1.3.3 64-bit but 1.3.4 64-bit works fine 
Thanks
