### ISSUE TITLE
AutoUpdater: `autoInstallOnAppQuit` is ignored on Mac

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#1094]
On Mac, a downloaded app update will be installed after quit even if the user clicked `Cancel` in the update prompt.

This option isn't working:

https://github.com/Automattic/simplenote-electron/blob/c9b8d4a606a508a35758e120cf135cbfb5fef394/desktop/updater/auto-updater/index.js#L22

https://www.electron.build/auto-update#api

**Comment by belcherj** [comment]
Closing as macOS is unsupported and the App Store native app should be used.
