### ISSUE TITLE
Two notes are missing

### ISSUE THREAD

**Issue by JonnyTheWise** [Automattic/simplenote-electron#1097]
#### Steps to reproduce
1. I was typing a note during a lecture. I finished one note and created a new one and later a third one.
2. After finishing the lecture I closed Simplenote and turned off my laptop.
3. I didn't need the notes for a couple of weeks, using Simplenote in the meantime for other work.
4. About 3 weeks after the lecture in question, I needed to go through the notes and found out that only the first one is there, the two other missing.

I searched all my other notes, I searched the trash (which I don't use at all, I never delete any notes), I searched the note history of all the notes, the text is nowhere to be found. There are no empty notes either, so not only the text but the entire notes did not save. The first note of that lecture is there and is complete, the last edit is made about one third into the lecture which fits the time I created the next note. Another note saved after the first one is about a week later - that also fits, I didn't use Simplenote in the meantime.
I used Simplenote on my Windows laptop for writing the notes and later for searching for them. After finding them missing, I checked both Android and web versions of Simplenote to find out if anything is different there, with no success. 

#### What I expected
I expected that the notes I took would save :(

#### What happened instead
Two notes disappeared (or more likely didn't save at all).

#### Simplenote version
1.3.3 (probably 1.3.0 at the time of taking the notes in question)

#### OS version
Windows 10

**Comment by mirka** [comment]
Hi there! Our support team may be able to assist you with this.
https://simplenote.com/contact-us/

**Comment by bikingTarzan** [comment]
The same problem, lost a note written on the windows side, but the label of the note still exists。
