### ISSUE TITLE
Open Source Self-hosted Backend

### ISSUE THREAD

**Issue by infosisio** [Automattic/simplenote-electron#1099]
Many thanks for this great project. 

I am however not very happy with not being able to self-host the backend.

Any plans for that? 

The biggest issue for me is what happens if you shut down.

Thanks!

**Comment by infosisio** [comment]
Hello

**Comment by timypcr** [comment]
I agree that the back end should be opened source as well, from what I have read the code base for the server is "complex" and will take awhile to release but Automattic has stated it will be available one day.

 In the meantime have you looked into nextcloud? Among file storage and a ton of other features it also allows you to take notes directly from the webUI and their also exists many clients for nextcloud as well.

[nextcloud notes](https://apps.nextcloud.com/apps/notes)

[NextCloud Gitrepo](https://github.com/nextcloud)

**Comment by en3r0** [comment]
Agreed, would love to see the backend available here as well.

**Comment by famouzkk** [comment]
Still waiting. Why just not open source backend?
