### ISSUE TITLE
Search Can be Slow with Large Note Open

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#1107]
Search can lag by a few seconds if you have a large note open in the editor:

**Repro steps:**
1. Create a really large note, over 2k lines.
2. Leave the note open in the editor, and search for something.
3. The search will lag.

**Comment by mirka** [comment]
Related: #747

**Comment by mgalbritton** [comment]
Adding another report of this in #1672373-zen.

**Comment by laoyuan** [comment]
This problem may be solved whth #624 and #983
