### ISSUE TITLE
Feature Request: Typewriter Mode

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/simplenote-electron#1112]
A user is requesting a "Typewriter Mode" when composing content, as illustrated here:

![Typewriter Mode](https://cdn-std.dprcdn.net/files/acc_685266/FrKaTt)

Typewriter Mode, where the text you're typing is roughly in the middle of the editing window as you work, as opposed to the bottom of the screen.

Ref: 1657818-zen

**Comment by mirka** [comment]
Related: #959

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
