### ISSUE TITLE
Feature Request: Markdown keyboard shortcuts while editing

### ISSUE THREAD

**Issue by mattwright324** [Automattic/simplenote-electron#1113]
Similar to how we can use shortcuts in the [markdown content on GitHub](https://help.github.com/articles/using-keyboard-shortcuts/#comments) (such as when writing this issue), it would be really nice to have the following shortcuts available while creating/editing notes while markdown is enabled:

* `Ctrl + B` surrounds the cursor position or selected text with `**` for quick bolded text.
* `Ctrl + I` surrounds the cursor position or selected text with `*` for quick italicized text.
* `Ctrl + K` surrounds the cursor position or selected text with `[` and `](url)` and moves cursor and selecting the url part to quickly paste if link is in clipboard.
* Pressing `Tab` while selecting a block of text will push every line in the selection forward by adding a tab character the front of the line to quickly create markdown quote/code block. This would be very useful when pasting in a multline block of text/code. Currently this just replaces the entire selected portion with a tab character. Edit: to add, `Shift + Tab` to do the opposite, shifting the selection backward by removign a tab character from the front of the line(s).

**Comment by sandymcfadden** [comment]
I've moved this to our internal feature request tracker for future consideration and am closing this for now.
