### ISSUE TITLE
Windows: Failure to sync all notes on version 1.3.4 (Windows 10)

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-electron#1117]
This is a user report in 1653877-zen.

### Steps to reproduce
1. User noticed that notes older than the most recent 22 notes weren't synching between Windows devices
2. User then imported notes, and found that only the most recent 22 notes were duplicated
3. User updated to version 1.3.4, but this update didn't resolve the issue.
4. After updating Windows computers to 1.3.4, none of them sync (aside from some tags)

### What I expected

All notes should sync between devices.

### What happened instead

According to the user:

>1. I imported the notes because it wasn't syncing anything but the latest 22, but since it's syncing those 22, they are duplicated. This is the case.
>
>2. When I export my notes, I'm running Windows 10 (1803) on a Dell laptop (Inspiroon 15 7000) , the Simplenote version is 1.2.1 (Win store version). This is my main device.
>When I import my notes on another device, I'm running Windows 10 (1607) on an Acer PC. The Simplenote version is 1.3.3 (both the Win store and desktop version were tested and they behave similarly). The exported and imported file is "notes.json". The imported notes and the synced notes are not combined but duplicated. However, at the same time, I noticed that even the notes and tags are duplicated, my notes on mobile devices (Android 7.0/Huawei and iOS 12/iPhone 6s) were not affected and functioned well.
>
>3. The web app shows the latest 41 notes (after a long wait since I opened the web app page) while I have 143 notes in total. Maybe this was caused by my network status? I'm in China.

After we asked the user to update to version 1.3.4, the user followed up with this feedback:

>Thank you for your new version. I downloaded and installed the latest version 1.3.4 but the issue is still there. I tried to create a new note on my old device ( Windows 10 1803, laptop, v1.2.1) and it was successfully synced to my mobile device (iPhone 6s, iOS 12). However, the software on the new device (Windows 10 1607, PC, v1.3.4) did not sync the new note.
>
>Then, in order to test whether it is caused by the different devices, I uninstalled all my simplenote windows installations (both on the old and new device), cleared the registry and reinstalled the latest version to the two devices. However, the newly installed apps never started to sync this time. I even tried reinstalling previous versions (v1.0.8 and v1.2.1) and these newly installed Windows apps all show a blank list and never sync notes. But the tags are shown correctly. I tried some newly created notes and they are not synced to my mobile devices any more, either. It seems there is some mysterious power preventing them from syncing. I checked the Windows firewall and network connection but did not find anything wrong. Maybe this is caused by my Internet environment.

### Simplenote version

1.3.4

### OS version

Windows 10

### Screenshot / Video

None.

**Comment by mgalbritton** [comment]
Another case 1678805-zen

**Comment by jenlynnemc** [comment]
Another case 1784277-zen

**Comment by codebykat** [comment]
Closing as stale - if we have newer reports of syncing issues we'll need to follow up there.
