### ISSUE TITLE
Import can unexpectedly overwrite an existing tag

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#1119]
#### Steps to reproduce
1. Starting with an empty account, create a note with title `Original note` and tag it `original`.
1. Export the note.
1. In the tag drawer, rename the `original` tag to `edited`.
1. Import the file exported in step 2.

#### What I expected
My account to have two tags: `original` and `edited`.

#### What happened instead
My account has only one tag: `original`.

#### Simplenote version
1.3.4

**Comment by mirka** [comment]
Importers should probably use the Redux action `createTag` instead of calling `tagBucket.update()` directly. `createTag` should be fixed to protect against collisions (#1124).

**Comment by dmsnell** [comment]
Resolved in #2148
