### ISSUE TITLE
Add Evernote notebook as a tag

### ISSUE THREAD

**Issue by ianchanning** [Automattic/simplenote-electron#1122]
#### Steps to reproduce
1. Export all notes from Evernote across notebooks via Windows desktop app
2. Import Evernote.enex file into Simplenote

#### What I expected
Notes would be tagged with the Evernote notebook that they were in

#### What happened instead
No notebook tag was applied

Looking in the `.enex` files this might be an issue with the Evernote export that it doesn't include the notebook. If there is nothing that can be done, it might be worth noting in your help that you should pre-tag everything with the notebook name in Evernote before exporting (which is quite easy to do) as it's a big hassle to delete and re-import 1000s of notes in Simplenote

#### Simplenote version

v1.3.4

#### OS version
Windows 10

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
