### ISSUE TITLE
Tag IDs can collide

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#1124]
#### Steps to reproduce
1. Start with an empty account.
1. Create a new tag named `tag1` by adding it to a note.
1. In the tag drawer, rename it to `tag2`. At this point, you should have a single tag named `tag2` in your account.
1. Create another tag named `tag1` by adding it to another note.

#### What I expected
Two tags in my account: `tag1` and `tag2`.

#### What happened instead
One tag in my account: `tag1`. (The tag named `tag2` was overwritten with a new name because its ID collided with the new `tag1` tag)

#### Simplenote version
1.3.4

**Comment by dmsnell** [comment]
Resolved in #2148
