### ISSUE TITLE
Windows: new note keyboard shortcut doesn't change focus to the new note

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/simplenote-electron#1125]
Looks similar to #179 .

#### Steps to reproduce
1. Start a new note
2. Type for a bit on it, then create a new note with the `ctrl` + `N` shortcut

#### What I expected
To change the focus to the new note.

#### What happened instead

You might need to try one or two times to reproduce the issue.

The new note is created but the focus remains on the current note instead of moving the context to the new one. You see the new note in the left sidebar, but the actual note panel still shows the old one.

#### Simplenote version
1.3.4

#### Screenshot / Video

https://cloudup.com/c_xnZk60WTw

---
User report: 1669336-zen

**Comment by msilbers** [comment]
I was able to reproduce this repeatedly and consistently
Simplenote Mac Electron version, 1.3.4
Mac OS 10.14.2 Mojave
