### ISSUE TITLE
Tags can be renamed to a duplicate name

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#1128]
#### Steps to reproduce
1. Add a new tag named `first` to a note.
2. Add another tag named `second`.
3. In the tag drawer, rename `first` to `second`.

#### What I expected
A warning, or a dialog asking if I want to merge the two tags.

#### What happened instead
Nothing, and now I have duplicate tags.

#### Simplenote version
1.3.4

**Comment by mirka** [comment]
Once this is fixed, see #1119

**Comment by rachelmcr** [comment]
I noticed this is still happening while testing 1.15.0-beta.2.

**Comment by belcherj** [comment]
It was never fixed.

**Comment by indeec05** [comment]
Version 1.15.0. The mistake is still here

**Comment by dmsnell** [comment]
Resolved in #2148
