### ISSUE TITLE
[Windows] Copying notes from Simplenote 1.3.4 to Blogger will show wide line spacing

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-electron#1129]
#### Steps to reproduce
1. Create a note in Simplenote 1.3.4
2. Paste it in a Blogger post and Preview it.
3. It will show something like this: https://monosnap.com/file/qdYSJMXnpmJ8On5StQONkWqKIpwynd

#### What I expected
To have it like this:
https://monosnap.com/file/AFWIes5psuU5tc28RnwJlYmA8w2kRG

#### What happened instead
The third point above.

**Note: This doesn't happen with Simplenote 1.3.3**

#### Simplenote version
1.3.4

#### OS version
Windows 10

Ref: #1668013-zen

**Comment by mgalbritton** [comment]
Another report of the same issue in #1679936-zen.

**Comment by mgalbritton** [comment]
Another report of this in #1679936-zen. I was also able to replicate it using the Electron version 1.3.4 on macOS Mojave 10.14.2. Here is a short gif:

![screen capture on 2019-01-08 at 08-27-00](https://user-images.githubusercontent.com/19782997/50836766-a2567600-131f-11e9-8bf0-bca9a53cc26b.gif)
