### ISSUE TITLE
Opening 'Preferences' leads to strange cursor behaviour, unwanted and strange duplicating of typed text 

### ISSUE THREAD

**Issue by johann-ka** [Automattic/simplenote-electron#1134]
#### Steps to reproduce
1. Create a new note, activate Markdown for this note
2. Create a # headline further down a ## headline
3. Put in three (or fewer or more) bullet points 
4. Go with the cursor to the end of the line of your last bullet point
5. Open File > Preferences, click on 'Display' and then click back on 'Account', close the preferences dialogue
6. When closing Preferences, the cursor is automatically being placed at the top at the very left in the active note
7. Now simply write something, the text being typed appears in the first line, where the cursor was placed automatically as well as at the beginning in the line where the cursor was before the Preferences tab was opened. Typing is being duplicated but Backspace only affects the line where the cursor actually is (Line 1 in this example)
8. When switching to another programme, e.g. FireFox, and then back to Simplenote, the false behavouir rewinds to normal functionality but first one must place the cursor somewhere else in the note.

#### What I expected
Normal behaviour, alterting the text where the cursor is

#### What happened instead
Copying the text of the active line somewhere else in the note and duplicating it as it is being typed

#### Simplenote version

Simplenote 
![simplenote bug](https://user-images.githubusercontent.com/15203094/50574814-adb11b00-0dce-11e9-8a89-a0cb8fc7f811.PNG)
1.3.4 

#### OS version
Windows 10, all updates installed

**Comment by codebykat** [comment]
Looks like our old friend the text duplication bug, we think we've fixed it so closing this for now. Let's re-open if it comes back.
