### ISSUE TITLE
Pin owner's email to top of collaborators list

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#115]
Pin the owner to the top of the collaborator list (cannot be removed from list):
![screen shot 2015-12-08 at 5 34 18 pm](https://cloud.githubusercontent.com/assets/618551/11671993/02e815a8-9dd2-11e5-9c5a-6bd6da687ff2.png)

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
