### ISSUE TITLE
PWA for the Windows 10 Store?

### ISSUE THREAD

**Issue by sprite-1** [Automattic/simplenote-electron#1151]
Hi there! Have you guys considered releasing a PWA (Progressive Web Apps) version of Simplenote on the Microsoft Store? Twitter is doing the same thing and Twitter is very light on system resource usage since it's just relying on the system's rendering engine.

This is something that could bee done with Simplenote too right? Since even the new website version is pretty much the same as the desktop one but without the Chrome overhead of Electron.

**Comment by mirka** [comment]
AFAIK it hasn't been considered yet. But I feel like we should probably be [headed in that direction](https://developers.google.com/web/progressive-web-apps/checklist), regardless of whether we actually abandon Electron — especially now that this is going to be our official web app as well. Once we get to a point where the app acts like a PWA, we may start to consider moving away from Electron.

Related: https://medium.com/dailyjs/goodbye-electron-hello-desktop-pwas-f316b8f39882

**Comment by sprite-1** [comment]
Yes please, I tested using it as a PWA on Linux and it starts up way faster than the Electron app. I just have the issue where it keeps kicking me out of the session whenever I close it and I have to log in again each time but navigation is way faster.

**Comment by kevgo** [comment]
This would also make SimpleNote work natively on ChromeOS. ChromeOS has 21% market share now.

**Comment by belcherj** [comment]
I plan on doing this in the term near future.

**Comment by sandymcfadden** [comment]
I'm going to move this issue to our internal feature request tracker for something to look at again in the future.
