### ISSUE TITLE
Quick capture/global keyboard shortcut

### ISSUE THREAD

**Issue by cweagans** [Automattic/simplenote-electron#1160]
I'd love it if Simplenote could give me a global keyboard shortcut that I can use no matter what application I have in focus that would a) focus the main Simplenote window b) create a note and c) put the cursor in the note body area.

A similar keyboard shortcut that would a) focus the main Simplenote window and b) put the cursor in the search field would also be extremely helpful.

**Comment by mirka** [comment]
Thanks for the request! Let's consolidate this to #324.
