### ISSUE TITLE
Checkboxes in the Note List can be squashed

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#1161]
In the Note List, if the title of the note has a checklist item, checklist items underneath appear a bit horizontally squashed:

![squashed checkbox in note list](https://user-images.githubusercontent.com/789137/51294863-b22e2400-19c9-11e9-8676-8c01b497f6cf.png)

Originally reported here: https://github.com/Automattic/simplenote-electron/pull/1159#pullrequestreview-193452271

**Comment by qualitymanifest** [comment]
Looks like this might be OS-specific. I tried this (title checkbox and a body checkbox right below it) and it appears just fine for me on linux mint.

**Comment by qualitymanifest** [comment]
What OS? I looked into this and it displays properly in linux mint.

**Comment by mirka** [comment]
> What OS? I looked into this and it displays properly in linux mint.

Strange, I can't get it to reproduce either (Mac Electron).

<img width="554" alt="untitled" src="https://user-images.githubusercontent.com/555336/51679879-775c6980-2023-11e9-902b-0e3997279691.png">

@roundhill Did this go away or is it only in a certain OS/browser?

**Comment by roundhill** [comment]
Ahhh, it is only happening on Chrome on macOS for me. Good to see that it's ok in Electron.

**Comment by mirka** [comment]
I don't see it in current Mac Chrome (71.0.3578.98) either, so I'm wondering if there are other repro conditions.

**Comment by roundhill** [comment]
I can't reproduce this now on Chrome `72.0.3626.81`. Will reopen if I see it again.
