### ISSUE TITLE
Can't open again after quick close in non-English OS

### ISSUE THREAD

**Issue by lizardll** [Automattic/simplenote-electron#1177]
#### Steps to reproduce
It's simple to reproduce on win10:
1. Open simplenote (logged in)
2. Close the simplenote window by clicking the cross sign at the top right corner, **as fast as you can**
3. Open simplenote again, this time it won't open unless you manually close the process

I can reproduce it on another win10 1803 PC

But if I use File->Exit to close the window, then this issue won't happen

#### What I expected
the simplenote main window show up again

#### What happened instead
the main window didn't show up again

#### Simplenote version

1.3.4
#### OS version
win10 pro 1803

**Comment by mirka** [comment]
Thanks for the report!

I'm having trouble reproducing it though. Maybe I'm not doing it fast enough.

Does this happen with Simplenote 1.5.0 (we updated the Electron version we're using in it)? Also, do you know if this happens with other Electron-based apps?

**Comment by lizardll** [comment]
First, Simplenote 1.5.0 has the same issue as 1.4.x on my PCs. Second, other Electron-based apps like vscode doesn't have similar problems.

BUT I HAVE AN IMPORTANT DISCOVERY TODAY:
If I change my system language from Chinese to English, then this issue disappears! And if I change it back to Chinese, it happens again. So I think it's an issue about multi-language supporting?

**Comment by lizardll** [comment]
> Thanks for the report!
> 
> I'm having trouble reproducing it though. Maybe I'm not doing it fast enough.
> 
> Does this happen with Simplenote 1.5.0 (we updated the Electron version we're using in it)? Also, do you know if this happens with other Electron-based apps?

First, this also happens with Simplenote 1.5.0. Second, Electron-based vscode doesn't have similar problems.
**HOWEVER, I have an important discovery:**
If I change my system language from Chinese to English, than it won't happen anymore. And after I change it back to Chinese, this issue reappears. So maybe there are some problems with multi-language supporting.

**Comment by mirka** [comment]
@lizardll Great, thank you. I was able to confirm this in Japanese and Polish as well.

My first guess is that it has something to do with [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker).

**Comment by mirka** [comment]
This doesn't reproduce for me anymore with 1.21.1 on Win 10 Home 1903. Let us know if you still see issues. (cc @belcherj)
