### ISSUE TITLE
PPA for Ubuntu and Linux Mint

### ISSUE THREAD

**Issue by reaganch** [Automattic/simplenote-electron#1179]
This is more of a feature request rather than a bug report.

It would be helpful if Simplenote installers for Ubuntu (Linux Mint) were made available via a PPA, so that updates could be delivered in a streamlined fashion via the distribution's package manager, rather than having to download individual *.deb files and install them each time a new version is released, which seems to be rather frequently.

**Comment by tribukhouski** [comment]
ppa is incomparably better than monstrous snap

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
