### ISSUE TITLE
Simplenote 1.4.0 - new lines by "enter" not respected anymore in markdown

### ISSUE THREAD

**Issue by DanyGee** [Automattic/simplenote-electron#1183]
#### Steps to reproduce
1. Type something
2. Go to next line with enter
3. Type another thing

#### What I expected
2 lines of notes

#### What happened instead
1 line of notes

#### Simplenote version
1.4.0

#### OS version
Windows10
Linux (Deepin & elementaryOS)

#### Screenshot / Video
raw
![screenshot from 2019-02-01 08 27 47 2x](https://user-images.githubusercontent.com/26818551/52108851-b67a5400-25fb-11e9-9def-676785c37beb.png)
markdown
![screenshot from 2019-02-01 08 27 58 2x](https://user-images.githubusercontent.com/26818551/52108857-ba0ddb00-25fb-11e9-8e43-cb66ef5d4169.png)

**Comment by roundhill** [comment]
This was actually intentional to match up with the correct Markdown syntax and to be compatible with the other Simplenote apps. To enforce a new line, add two spaces at the end of the line. 

See #1169
