### ISSUE TITLE
[Feature request] Option to create Nested tags

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1186]
Please implement nested tags feature. In the bottom of every note, there is a "**Add a tag...**" signed input bar. We can easily make another input bar (below parent tag or right side of the parent tag or vice versa)  for nested tags.

- Nested tag will help us to manage lots of unstructured notes.
- It will make easy to manage and find notes.
- Then all notes will be well structured

**Comment by Donboscow** [comment]
Please think about this most wanted and most needed feature @mirka @roundhill @drw158

**Comment by mirka** [comment]
Thanks, this is indeed a popular feature request, and is something we're considering in the coming months. Closing in favor of #750.
