### ISSUE TITLE
Notes missing after update 1.4.0 (Windows 10)

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#1187]
#### Steps to reproduce
Update to 1.4.0 (Windows 10) as suggested on startup at previous version

#### What I expected
Search for a note using a keyword

#### What happened instead
The note is no longer there / not dispalyed

The note is in the database as a cross-check proves with:
- https://app.simplenote.com/new
- Android

#### Simplenote version
1.4.0

#### OS version
Windows 10

**Comment by justinkterry** [comment]
This happened with a note to me too, on Ubuntu 18.04.

**Comment by detlefholtz** [comment]
Had a very similar report of a user updating to 1.4.1 and experiencing this issue
1789062-zen

**Comment by jonnyruzek** [comment]
Similar report in 1812305-zen

**Comment by kriskorn** [comment]
Another report in #1781373-zen

**Comment by codebykat** [comment]
Closing as stale, it may have been the product of a bug that failed to load certain notes. Please open a new issue if anyone is still having problems.
