### ISSUE TITLE
New version popup in Snap application

### ISSUE THREAD

**Issue by yaronf** [Automattic/simplenote-electron#1188]
#### Steps to reproduce
1. Install Simplenote from Snap store (in my case Linux Ubuntu)
2. Start the application when a newer version is available for download 
3. A new version popup is displayed

#### What I expected

No new version popup. Snap installs the new version automatically when it is available in the Snap store.

#### What happened instead

Popup calling for manual download of the new version.

#### Simplenote version

1.3.4
#### OS version

Ubuntu 18.10

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
