### ISSUE TITLE
Import Markdown Files

### ISSUE THREAD

**Issue by milkdromeda** [Automattic/simplenote-electron#1189]
#### Feature Request
I believe the adding the ability to **import files in the Markdown format** is critical. Rather than importing .txt files where the formatting is omitted, .md files keeps the formatting.

As a Markdown-focused notes app, I am surprised that this feature is missing. This presents a barrier for new users like me who are trying to import their old notes, only to discover that there is no direct and perfect way to achieve this in bulk.

##### Did NOT Work
For example, in my case, I wanted to import my notes from Apple Notes to Simplenote (I use MacOS). So I tried to use [Notes Exporter](http://writeapp.net/notesexporter/) to convert Apple Notes to .txt before importing it to Simplenote. But the Apple Notes formatting turned into HTML and strange symbols (Notes Exporter issue).

Next, I tried using [Exporter](https://itunes.apple.com/app/exporter/id1099120373?l=en%26mt%3D12) to export Apple Notes to .md. Then, I extracted the files from folders and converted it to .txt using [Cloud Convert](https://cloudconvert.com/md-to-txt) before importing. While Exporter transformed the Apple Notes formatting to .md perfectly, the latter converted the .md files to .txt in a non-user friendly markdown syntax (Cloud Convert issue).

##### Somewhat Work
From the method above, instead of using Cloud Convert, I did the following
1. Used the following Terminal command to convert markdown to text (have to do it individually for each file)
> util -convert txt [Markdown File Path]
2. Filtered and extracted Markdown files to trash can using Finder, leaving only text files
3. Imported converted text file to Simplenote

The markdown renders nicely with the exception that the titles are displayed twice (which is a Simplenote issue as the text file itself does not have the title repeated)

If there's a simpler way to import to Simplenote that I've missed, feel free to tell me. Otherwise, I think we can agree that the feature to add markdown files is indispensable. Thank you!

**Comment by mirka** [comment]
I agree that it would be a good idea to accept files with extension `.md` in addition to `.txt` in our plain text importer. Maybe we could also check the "Enable Markdown on all notes" option by default when there is a `.md` file in the batch.

In the meantime, note that there is nothing inherently special about `.md` files — it's just a plain text file, that may or may not contain Markdown syntax. If you have a bunch of `.md` files, you can bulk rename them to have a `.txt` extension and import it with the "Enable Markdown on all notes" option checked.

**Comment by mirka** [comment]
> I am just interested in one thing: how can one bulk rename files (on the Mac or other platforms)?

In recent versions of macOS, there is a handy [bulk renaming feature](https://www.imore.com/how-rename-multiple-files-once-mac) in the context menu. Before that, I used to use bulk renaming apps like [Name Mangler](https://manytricks.com/namemangler/) (which are probably still better if you have more advanced needs).

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by eallion** [comment]
yes, i want this feature too. thx

**Comment by philtrade** [comment]
> Hi @mirka,
> I like your suggestion to check "Enable Markdown on all notes" by default for `.md` files.
> I am just interested in one thing: how can one bulk rename files (on the Mac or other platforms)?

A perl one-liner will do the trick of bulk renaming of files using regex substitution.  MacOS comes with perl installed.

In a terminal window:

`cd /directory/of/some-4000-mdfiles/`

`ls *.md | perl -MFile::Copy -ne 'chomp; next unless -e; $o = $_; s/\.md$/.txt/; next if -e; move($o, $_)'`
You might wanna test a few files first:

`ls file1.md file2.md file3.md | perl .....`

Once you verify this is doing what you need, wiggle the magic wand on the 4000+ files with `ls *.md | perl .....`

If you prefer to be cautious and copy the files instead of renaming them, change the`move(...)` to `copy(...)`

One question though, the Exporter app is not available in the app store (USA) now.. do you know where else I may get it?

**Comment by dmsnell** [comment]
@philtrade note that `bash` can do this natively too

```bash
for FILE in *.md; do mv "$FILE" "${FILE%.md}.txt"; done
```

**Comment by philtrade** [comment]
Nice! Glad to learn this "%"  op in bash, thank you for pointing that out Dennis!

**Comment by codebykat** [comment]
Done in #2351
