### ISSUE TITLE
Please upstream snap build by snapcrafters

### ISSUE THREAD

**Issue by justinkterry** [Automattic/simplenote-electron#1190]
There are 3 self contained Linux package formats: appimage, flatpack, and snap. 

Snap is by far the most widely used, and is the only one most programs support. It's also best integrated into Ubuntu. 

You currently only support appimage. That's fine, however the fine people over at snap crafters repackaged the tar you distributed to snap for people who want it, and distribute it to the snap universe. The entire snap universe is shown in the ubuntu store, and so their build of simple note shows there for you. As per bug #1188 , small tweaks for proper snap support are required. 

This creates the following problems:

1) You have an official seeming release of simple note the Ubuntu store (where ton's of people can see it, and many people look on the store distribution page) that you aren't technically the one's supporting
2) You have an official seeming version of simple note that lots of people use that has small bugs because snap isn't natively supported (like in #1188 )

Snapcrafters entire goal is to make snap more used, so I strongly assume they'd be willing to help you upstream their snap package, so you could take control and work out the handful of tweaks needed.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
