### ISSUE TITLE
CTRL+SHIFT+P - Cursor still not returning

### ISSUE THREAD

**Issue by SonGokussj4** [Automattic/simplenote-electron#1194]
#### Steps to reproduce
1. Multiline note, click on line X (for example third)
2. Press shortcut CTRL+SHIFT+P - Switch to Preview Mode
3. Press shortcut CTRL+SHIFT+P - Switch to Modification Mode

#### What I expected
The cursor would be on the same place I had it before switching to Preview Mode.
OR - at least on the first? line of the text.

#### What happened instead
The cursor is nowhere...
At least be somewhere :-D Please

#### Simplenote version

1.4.0 - Beta

#### OS version
Linux - Centos 7

#### Screenshot / Video
/

#### Additional informations.
I found similar issue #737 but this was redirected to #42 which is already close.
Because of this, I'm reopening this issue.

**Comment by mirka** [comment]
Agreed! Thanks for the report. Closing in favor of #331.
