### ISSUE TITLE
Every so often, my cursor teleports to the end of the text field, in the middle of writing a word.

### ISSUE THREAD

**Issue by Pand9** [Automattic/simplenote-electron#1196]
I noticed today in several notes, short and long.
- happens for both markdown enabled and disabled
- I think it only happens after writing a big letter (e.g. shift+p).

Loving your app btw.

#### Simplenote version

1.4.0 Linux/Electron

#### OS version

Ubuntu 18.04 / Gnome 3

**Comment by qualitymanifest** [comment]
Hey, give [1.4.1](https://github.com/Automattic/simplenote-electron/releases/tag/v1.4.1) a try, this issue should be resolved there.

**Comment by mirka** [comment]
Closing for now, but let us know if you still encounter this in 1.4.1 🙂
