### ISSUE TITLE
Allow changing checklist item's order

### ISSUE THREAD

**Issue by evandrojr** [Automattic/simplenote-electron#1198]
#### What I expected

Be able to rearrange the order of the items of a checklist. It would be nice to drag and drop up or down a item.

#### What happened instead

Not able to drag and drop items.

#### Simplenote version

1.4.1

#### OS version

Linux

**Comment by evandrojr** [comment]
Maybe this lib can be useful for the task:

https://github.com/SortableJS/Sortable

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by gsirvine** [comment]
Re-ordering would be so nice.  Trying to transition from evernote and that is really hindering the switch.  I often think of things out of order and it is nice to help myself work through things better by chunking tasks together in a sequential order.  Explaining my usecase.  I hope the feature request makes it to a final build.

Was this feature removed from the feature request list?
