### ISSUE TITLE
Conflict between Polish character “ć” and checklist keyboard shortcut

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/simplenote-electron#1203]
#### Steps to reproduce
1. Set up Windows with the `"Polish (Programmers)"` keyboard layout 
2. Use alt + c combination for polish character “ć” inside a note

#### What I expected
To see the character “ć” inside a note

#### What happened instead

It started a list item with the "ć" character

#### Simplenote version

v1.4.1

#### OS version
Windows 10

#### Screenshot / Video

![screen capture on 2019-02-14 at 15-39-59](https://user-images.githubusercontent.com/3696121/52817442-de44cf80-3071-11e9-9364-fa9a64578cfc.gif)

#### First report (for internal reference)

1783137-zen

**Comment by edequalsawesome** [comment]
Also reported in #1801149-zen

**Comment by msilbers** [comment]
This was reported again by another Polish user who is trying to add the ć character, in #1807844-zen

**Comment by mirka** [comment]
Sorry for the lack of awareness about this! I [read up on it](https://en.wikipedia.org/wiki/AltGr_key) and it seems like we should be steering clear of <kbd>Ctrl+Alt</kbd> shortcuts in general.

We'll change this one to <kbd>Ctrl+Shift+C</kbd>.

**Comment by mikeicode** [comment]
Also reported #1785056-zen

They provided this video example: https://www.youtube.com/watch?v=mvkqml_e74I

**Comment by mikeicode** [comment]
Also reported #1785056-zen
