### ISSUE TITLE
Korean input: tabbing causes word duplication

### ISSUE THREAD

**Issue by eurello** [Automattic/simplenote-electron#1204]
When typing a list in Korean with multiple tabs, words are duplicated: 

1. Type a list in Korean, add tabs at the beginning of each line
2. Korean words duplicate themselves

![simplenote_kor_issue](https://user-images.githubusercontent.com/8698879/52881483-4b1ba080-312a-11e9-9fe7-ba4671a25d71.gif)

A customer reports this happening with version 1.4.1 of the app in Windows 7 and Windows 10. 

Reported in #1759739-zen

**Comment by mirka** [comment]
Bug confirmed in 1.4.1, and also confirmed fixed in #1172. We'll be releasing this fix in the next few weeks.

Related: #1171
