### ISSUE TITLE
How to build a non-development version on Linux?

### ISSUE THREAD

**Issue by andreas-R17** [Automattic/simplenote-electron#1208]
I do:

`> wget https://github.com/Automattic/simplenote-electron/archive/v1.4.1.tar.gz`

`> tar -xvf v1.4.1.tar.gz`

`> cd simplenote-electron-1.4.1`

`> make linux`

But I get the development version.

Then I edited the config.json file. Replaced "development": true with "development": false and run again:

`> make linux`

The signature "dev" is gone. But the program does not work((.
Login and password are correct.

#### Simplenote version

1.4.1

#### OS version

Linux

#### Screenshot / Video

https://i.imgur.com/TJdJwSS.jpg
https://i.imgur.com/L7AkK4F.png

**Comment by mirka** [comment]
Good question! We have separate databases for development and production, and we allow use of the production database only in official production builds.
