### ISSUE TITLE
[Windows] Word duplication if a Japanese character is written after a <tab>

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#1221]
This was reported on 1816847-zen , seems to happen only in Windows and the same user is unable to see this problem on the web app.

Words in Japanese are being duplicated if the word is written in a new line after a tabulation.

#### Steps to reproduce
1. Write something using Japanese characters (Seems to affect at least Kanji and Hiragana)
2. Go to new line, see there's no problems.
3. Press <tab> and write again
4. See how the character is duplicated after moving to a new line

<img width="1279" alt="screen shot 2019-02-23 at 16 10 13" src="https://user-images.githubusercontent.com/3812076/53284348-8e5abc80-3785-11e9-8c27-351c45840d2a.png">

#### What I expected

Default behavior of no word duplication.

#### What happened instead

Word duplication.

#### OS version
- Windows

#### Screenshot / Video

- Video: https://cld.wthms.co/G77WRD

**Comment by mirka** [comment]
This is fixed in 1.5.0 👍 

Related: #1204
