### ISSUE TITLE
Shortcuts for switching mode

### ISSUE THREAD

**Issue by ouwenkg** [Automattic/simplenote-electron#1222]
#### What I expected

It should have shortcuts to switch between edit and preview mode.

#### Simplenote version

version 1.4.0

#### OS version

Ubuntu 18.04

**Comment by mirka** [comment]
We actually do have a shortcut for this: <kbd>Ctrl+Shift+P</kbd>

However, this isn't documented anywhere yet and is kind of impossible to discover (related: #700). We have a tooltip enhancement in the pipeline that should make it more discoverable #1214.
