### ISSUE TITLE
Keyword search highlight

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#1223]
While keyword highlight exists on iOS and Android, seems to not be the case for the web app, or OSX (cannot test Windows)

#### Steps to reproduce
1. Search for any word in the search bar
2. See how the notes are filtered, but no words are highlighted within the note

#### What I expected

Consistency between apps.

Reported initially on 1830712-zen
Reported for OSX as well on https://github.com/Automattic/simplenote-macos/issues/18

**Comment by mirka** [comment]
This feature is implemented in the Electron app and the new web app (https://app.simplenote.com/new). The old web app will be retired soon.
