### ISSUE TITLE
Web app: parity with other platform releases

### ISSUE THREAD

**Issue by ekadas** [Automattic/simplenote-electron#1225]
This is more a question around the plans for the web app [app.simplenote.com](app.simplenote.com).

It seems (based on the assumption the web app tracks the [webapp branch](https://github.com/Automattic/simplenote-electron/tree/webapp)) that the web app is at around version 1.3.0 and that it requires manual deployment (as there isn't a job for deploying the web app in the CircleCI config). It would be nice to have all the new features and fixes in the web app as well.

Are there any plans around bringing parity between where the apps on the other platforms are and the web app? If so, I would be happy to help!

**Comment by mirka** [comment]
Great question.

Right now, our new webapp (https://app.simplenote.com/new) is roughly around 1.5.0. In the [commit messages for `webapp`](https://github.com/Automattic/simplenote-electron/commits/webapp), I've been leaving the hashes of the corresponding commit on `master` so we don't lose track.

There are a few reasons why this process is so crude at the moment:

- I don't think this codebase has sufficient test coverage to do continuous deployment.
- Given that we need to rely on some manual testing, we should at least set up a staging environment and a way to manually trigger an automated deployment via CircleCI. However this wasn't an absolute priority, so we haven't had the time to do it yet.

Thanks for offering to help though. We'll try to keep it as up-to-date as possible.
