### ISSUE TITLE
Failure to sync on v 1.5.0 Windows 10

### ISSUE THREAD

**Issue by pieroxy** [Automattic/simplenote-electron#1228]
#### Steps to reproduce
It used to work fine but since a few days, any update I do on the web or on the iOS app are not syncrhonized on my electron version, and changes made in the electron version are not synced to the others. Web and iOS sync fine though.

#### What I expected
Sync to work

#### What happened instead
Sync does not work

#### Simplenote version
1.5.0
#### OS version
Windows 10

#### Screenshot / Video

I restarted the app and still it does not sync. What can I do to help troubleshoot ?

**Comment by pieroxy** [comment]
Just started to work right now.... So I cannot help debugging the issue anymore. Not sure there's anything I can do to help. Let me know if this issue should be closed, I'm not sure it's very actionnable.

**Comment by mirka** [comment]
Yes, it's hard to get a reproducible case for sync issues. If you do encounter a similar problem, our support team can help you troubleshoot 👍 https://simplenote.com/contact-us/
