### ISSUE TITLE
Search: Add Untagged Notes to the sidebar

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#1230]
#### Steps to reproduce
Open the tag list

#### What I expected
Select untagged notes

#### What happened instead
This function is not yet available with simplenote-electron,
but with simplenote-android it is available:
_**Added a sidebar tab to view untagged notes**_
"https://github.com/Automattic/simplenote-android/pull/527"

#### Simplenote version
1.5.0

#### OS version
Windows 10

![39345814-8c681f5a-499f-11e8-99de-464fdff7206a](https://user-images.githubusercontent.com/22197180/54284784-e163aa80-45a0-11e9-877a-6338faa27843.png)

**Comment by eduardozulian** [comment]
Got a user request in 3750787-zen:

> Whilst investigating these issues, I was switching between the Windows and Android applications. I noticed that the Android app has an extra menu item for "Untagged Notes". I found this very useful. Could you please consider adding it to the Windows application.
