### ISSUE TITLE
Notes saved to PDF are just a bitmap of the text

### ISSUE THREAD

**Issue by crankygeologist** [Automattic/simplenote-electron#1232]
#### Steps to reproduce
1. File > Print > Save as PDF

#### What I expected
The text in the resulting PDF to be selectable and searchable with active (clickable) hyperlinked URLs.

#### What happened instead
The PDF is simply a paginated bitmap image of the note.

#### Simplenote version
1.5.0 Electron

#### OS version
macOS 10.14.3

**Comment by crankygeologist** [comment]
I don't think it's an OS issue. By default, File > Print > Save as PDF on macOS, regardless of the text source, saves a PDF with searchable and selectable text. This built-in print to PDF feature respects the textual nature of the data. Simplenote for macOS does not have this problem. I think this issue is related to the lack of feature parity between the Electron and macOS versions. See https://github.com/Automattic/simplenote-electron/projects/2

**Comment by belcherj** [comment]
This appears to be fixed.  I am no longer experiencing this issue. Please open another if you are continuing to experience this.
