### ISSUE TITLE
Add dropdowns feature like github

### ISSUE THREAD

**Issue by biswajitpaul01** [Automattic/simplenote-electron#1233]
#### Steps to reproduce
1. Please write in app
```
<details>
<summary>Heading</summary>

+ markdown list 1
    + nested list 1
    + nested list 2
+ markdown list 2

</details>
```

#### What I expected
<details>
<summary>Heading</summary>

+ markdown list 1
    + nested list 1
    + nested list 2
+ markdown list 2

</details>

#### What happened instead
![SimpleNote Image](https://i.imgur.com/D58S6US.png "SimpleNote Image")

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
