### ISSUE TITLE
Windows laptop: Tapping into a note brings up the On Screen keyboard

### ISSUE THREAD

**Issue by galakhyati** [Automattic/simplenote-electron#1234]
The user is on Windows Dell XPS 12 9Q33 (with touchscreen) and when they tap into a note it brings up the On-Screen keyboard, even if the keyboard is attached. 

The user says the issue is coming up only after updating the application. 

They are on Windows 8.1 (windows is 6.3, build 9600) with all lates updates installed.

#### Steps to reproduce
The user has created a video for us to see how it shows up, it can be found here: https://dl.dropboxusercontent.com/s/ot3uwrov6pi2wmk/V90315-085800.mp4?dl=1

We were unable to replicate the issue on a Windows tablet.

#### What I expected
The on screen keyboard to not open and let edit the note using the attached keyboard.

#### What happened instead
The on-screen keyboard pop-ups whenever the screen is touched in a note.

#### OS version
Windows 8.1

Ticket: #1844405-zd

**Comment by codebykat** [comment]
Closing as stale, we've since replaced the whole editor component. Let's reopen if we get any further reports.
