### ISSUE TITLE
Simplenote blocked

### ISSUE THREAD

**Issue by nettlebay** [Automattic/simplenote-electron#1235]
#### Steps to reproduce
1.
2.
3.
4.

**Comment by nettlebay** [comment]
1. First, I had a problem of sync between Linux / Android
2. When the two device sync after a while, some elements in the list have been reproduced many times which blocks the app. I can't delete this list. Same problem in Android: blocked.
3.I have several backup. But when I delete /home/user/.config/simplenote and uninstall Simplenote then reinstall, my lists re-appear and Simplenote blocks again. How to make a clean sweep? Where are the lists?

**Comment by nettlebay** [comment]
Good news: I have succeeded to unlock Simplenote on Linux and Android. On Linux, the bad list was probably removed without I realizing it (yesterday). However, when I reinstalled SN on my smartphone, this (bad) list reappeared. Fortunately, I succeeded to delete it before the app crashes.

**Comment by mirka** [comment]
Good to hear that you were able to sort it out! Feel free to contact our support team when you have any issues: https://simplenote.com/contact-us/
