### ISSUE TITLE
Add options to Bold, Underscore and Italic selected text 

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1236]
In google docs, when we select any text and  press
	- Ctrl + B = Its become Bold text
	- Ctrl + U = Its become Underline text
	- Ctrl + I = Its become Italic text
It would be great to have these options in Simplenote. Its a must have features. 

I think it has already implemented, just need to create some keyboard shortcuts.
@mirka @roundhill

**Comment by mirka** [comment]
Closing in favor of #1113

**Comment by Donboscow** [comment]
Any Estimated time of arrival? @mirka
