### ISSUE TITLE
Use 4 Spaces For "Tab" Key

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/simplenote-electron#1237]
The Simplenote web app is using 4 spaces when you hit the "Tab" key but not on the Windows app. The user in 1912762-zen is requesting this feature to be added to Windows app as well to make the UI more consistent. 

To quote the user:

`Can you use 4 spaces instead of tab characters? This is the default on the web UI. It makes for a more consistent experience.`

**Comment by mgalbritton** [comment]
Another request to use 4 spaces for tab.

`Please add an option to insert spaces with the tab key, rather than the tab character. The new version uses the tab character, the old version used 4 spaces.`

#2272699-zen

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by samtuke** [comment]
Any updates here? AFAICS tabs work as spaces on Linux but not Mac client 🤔
