### ISSUE TITLE
Adding @text in a note with Markdown formatting creates a link to GitHub

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-electron#1238]
#### Steps to reproduce
1. Create a new note in Simplenote
2. Add text that has @ in it, such as `@text`
3. Ensure note is formatted for Markdown
4. Preview note

#### What I expected
`@text` would be regular text

#### What happened instead
A link was created to `github.com/text`

#### Simplenote version
1.5.0

#### OS version
macOS 10.14.4

#### Screenshot / Video
![Screen Recording](https://cld.wthms.co/ffS72s+)

#### Other
Initially reported in #1914354-zen as an issue in the web app

**Comment by gabe31415** [comment]
Thank you for accepting my issue and creating the bug report!  You all rock!

**Comment by mirka** [comment]
We should disable the `ghMentions` option in Showdown.
https://github.com/showdownjs/showdown#valid-options

**Comment by briangzimmerman** [comment]
If no one has started this, yet, I'd like to give it a go. Thanks.

**Comment by belcherj** [comment]
This was merged in https://github.com/Automattic/simplenote-electron/pull/1256
