### ISSUE TITLE
Cursor jumps to End Of Line when typing

### ISSUE THREAD

**Issue by Bread7** [Automattic/simplenote-electron#1240]
#### What happened
- Typing in the notes will suddenly jump to the end of line and type from that point on. User is still able to click on other lines and continue to type from there but cursor will still jump to end of line rather frequently. This typically happens when I leave Simplenote opened for at least 20 minutes and beyond.

#### Simplenote version
- 1.4.0

#### OS version
- Debian

**Comment by mirka** [comment]
Hi there! Much of the cursor jumping was fixed in 1.4.1, and our latest version is 1.5.0. Could you try that and see if the problem persists? https://github.com/Automattic/simplenote-electron/releases/latest

**Comment by Bread7** [comment]
The problem did not occur during the last few days of usage, thanks for letting me know
