### ISSUE TITLE
Scroll bar doesn't work when window is maximized on Windows app

### ISSUE THREAD

**Issue by IlVecchioMago** [Automattic/simplenote-electron#1245]
Hi,
when using the Windows app there's a bug when the app is maximized.
Even if there are a lot of notes, the scroll bar on the left doesn't scroll.
When the app is in fullscreen mode or is unmaximized the scroll bar works just fine.

#### Simplenote version
Windows app version 1.5.0

#### OS version
Windows 10

#### Screenshot / Video
![Normal window](https://user-images.githubusercontent.com/36239585/55869352-a1371e00-5b86-11e9-9305-32466c0db3e9.PNG)
![Maximized window](https://user-images.githubusercontent.com/36239585/55869351-a1371e00-5b86-11e9-9a5b-4b66ddbcf100.PNG)
![Maximized window 2](https://user-images.githubusercontent.com/36239585/55869350-a09e8780-5b86-11e9-993d-8b1e8bb2c9c7.PNG)

**Comment by PhiLhoSoft** [comment]
FYI, I cannot reproduce this on my Windows 10 Pro laptop, with SN v. 1.5.

**Comment by codebykat** [comment]
Very stale and probably fixed in the intervening time. Please report back if it's still a problem!
