### ISSUE TITLE
Unable to login using "Sign in with Wordpress.com" option

### ISSUE THREAD

**Issue by uncertainquark** [Automattic/simplenote-electron#1247]
#### Steps to reproduce
1. Open Simplenote and choose "Sign in with Wordpress.com"
2. Sign in
3. Click Approve on the permissions screen

#### What I expected
Logging into my account

#### What happened instead
Stuck at the Approve screen

#### Simplenote version
1.5

#### OS version
elementary OS 5.0/Ubuntu 18.04

#### Screenshot / Video
![Screenshot from 2019-04-17 14-44-47](https://user-images.githubusercontent.com/22585732/56276197-bfb98e00-611f-11e9-9ac6-b3f1a98963e2.png)

I rely on Simplenote for a lot of things, hope this issue is fixed soon. :/

**Comment by mirka** [comment]
Thanks for the report! Closing in favor of #1229
