### ISSUE TITLE
Close menu sidebar on esc keypress

### ISSUE THREAD

**Issue by gtsiolis** [Automattic/simplenote-electron#1248]
It would be nice to be able to close the menu sidebar on esc keypress. Also, related to https://github.com/Automattic/simplenote-electron/issues/1249.

**Comment by gtsiolis** [comment]
This has been mentioned in https://github.com/Automattic/simplenote-electron/issues/979. Feel free to close this or keep this open as a smaller tangible change.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by gtsiolis** [comment]
@belcherj see https://github.com/Automattic/simplenote-electron/issues/1249#issuecomment-559462203.

**Comment by belcherj** [comment]
@gtsiolis see https://github.com/Automattic/simplenote-electron/issues/1249#issuecomment-561437985
