### ISSUE TITLE
Close note info sidebar on esc keypress

### ISSUE THREAD

**Issue by gtsiolis** [Automattic/simplenote-electron#1249]
It would be nice to be able to close the not info sidebar on esc keypress. Also, related to https://github.com/Automattic/simplenote-electron/issues/1248.

**Comment by gtsiolis** [comment]
This has been mentioned in https://github.com/Automattic/simplenote-electron/issues/979. Feel free to close this or keep this open as a smaller tangible change.

**Comment by gtsiolis** [comment]
This has been mentioned in https://github.com/Automattic/simplenote-electron/issues/979. Feel free to close this or keep this open as a smaller tangible change.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by gtsiolis** [comment]
Hi @belcherj! Is there a public issue tracking for this feature request?

**Comment by belcherj** [comment]
We do not have public tracking issues for feature requests. When we look into doing this we will link this issue.
