### ISSUE TITLE
Checking parent items should check off it's children

### ISSUE THREAD

**Issue by benclarkk** [Automattic/simplenote-electron#1251]
When I have some nested to-do's, I should be able to check off the parent item to make all it's children also checked.
#### Steps to reproduce
1. Make a checklist with a nested item
2. Try to check off the parent item
#### What I expected
All the nested items should be ticked

#### What happened instead
The nested items aren't ticked and I have to check them off one by one, which is annoying for big lists

#### Simplenote version

v1.5.0
#### OS version
Elementary OS 5.0 (Juno) (Ubuntu 18.04)

#### Screenshot / Video
![yeah it doesn't do it](https://user-images.githubusercontent.com/46399411/56751966-2160a480-677f-11e9-8b7f-f1dfb6604fd2.gif)

**Comment by dmsnell** [comment]
Thanks for the recommendation @benclarkk. This has been added to our feature request list but I wouldn't expect it to come in any time soon, if at all. Checking off all of the children items may be convenient in this use case but it might also surprise people who aren't expecting it, then make it hard to undo the operation.

We'll make it known if we change the behavior!
