### ISSUE TITLE
Please kindly add "Sign up & Sign in with Google Account" option

### ISSUE THREAD

**Issue by romakhan** [Automattic/simplenote-electron#1254]
Please kindly add an option to "**Sign up & Sign in with Google Account**"

**Comment by mirka** [comment]
Duplicate of #1010

**Comment by romakhan** [comment]
Any Estimated time of arrival? @mirka

**Comment by mirka** [comment]
No, not that I'm aware of. A new team is starting to develop a roadmap for the rest of the year, so we'll see 🙂
