### ISSUE TITLE
Add keyboard shortcut to make selected text Bold, Underscore & Italic in insert mode

### ISSUE THREAD

**Issue by romakhan** [Automattic/simplenote-electron#1255]
When we select any text and press
- Ctrl + B = Make it  **Bold**
- Ctrl + U = Make it Underline
- Ctrl + I = Make it _Italic_

**Comment by mirka** [comment]
Thanks for the request! Closing in favor of #1113

**Comment by Donboscow** [comment]
Any Estimated time of arrival? @mirka

**Comment by mirka** [comment]
@Donboscow No ETA for this particular feature, but development on the app will resume soon 🙂
