### ISSUE TITLE
Improvement to Simplenote browser version layout with Vivaldi browser with left sidebar

### ISSUE THREAD

**Issue by pranali333** [Automattic/simplenote-electron#1258]
macOS 10.14

Issue/ Improvement:

Simplenote is working as in widescreen with scrollbar at the bottom to visit content.
User doesn't find it easy to use.

Browser: Vivaldi 

#### Steps to reproduce
1. Use Vivaldi browser and add Simplenote browser version as a left sidebar.
2. Open anything (gmail / other app) on the right hand side.
3. Now, if you need to copy something from the Simplenote, you will see due to wide width you will need to scroll from the bottom to reach to content.
4. Check attached screenshot to match the results.

#### What I expected

The user expects compact screen without scroll to make copy paste easy.

#### What happened instead

Due to the scroll bar, the user needs to go at bottom scroll to right and find content.

#### Simplenote version

1.4.2

#### macOS version

MacOS: 10.14

#### Screenshot / Video

![Simplenote-gmail-scroll](https://user-images.githubusercontent.com/7771963/56491512-6e861180-6506-11e9-9d18-afeda24f4b9f.png)

**Comment by bummytime** [comment]
Thanks for the report @pranali333. Could you attempt to recreate this issue using our beta website in the Vivaldi browser? The URL is https://app.simplenote.com/new

**Comment by pranali333** [comment]
Hi @bummytime,

Sure!

I tried adding the new version with the URL you suggested and I am still able to regenerate the same issue. Please check the attached screenshot:

<img width="1224" alt="Vivaldi-with-new-app-version" src="https://user-images.githubusercontent.com/7771963/57197130-06f9a880-6f81-11e9-9791-1fe26da2f6d5.png">

Thanks!

**Comment by bummytime** [comment]
Thank you for that @pranali333! Our team will investigate this issue.

**Comment by belcherj** [comment]
This is the old app which wasn't responsive.
