### ISSUE TITLE
Windows: Text copied from Simplenote to Notepad has Unix (LF) EOL

### ISSUE THREAD

**Issue by tmo7452** [Automattic/simplenote-electron#1259]
Unknown when this started, I just noticed it.

### Reproduced
![image](https://user-images.githubusercontent.com/9245957/57143399-c89b9800-6d8c-11e9-9490-177c13900b9b.png)

![image](https://user-images.githubusercontent.com/9245957/57143181-4f9c4080-6d8c-11e9-8d7c-03257eafc1d7.png)

### Expected
![image](https://user-images.githubusercontent.com/9245957/57143236-6b9fe200-6d8c-11e9-86c7-3de44ba7771f.png)

### Observed
![image](https://user-images.githubusercontent.com/9245957/57143211-5d51c600-6d8c-11e9-8537-3f8ffcbd6968.png)

If you then save the document and open it with Notepad++, you see it has LF only EOLs
![image](https://user-images.githubusercontent.com/9245957/57143536-0e586080-6d8d-11e9-9d1d-81f90a3dd13c.png)
Most apps seem to correct this automatically at time of paste, but Windows Notepad does not.

Windows 10 x64 1703 | Simplenote 1.5.0

**Comment by codebykat** [comment]
This is already tracked in https://github.com/Automattic/simplenote-electron/issues/512
