### ISSUE TITLE
Add ability to open/edit note in external editor

### ISSUE THREAD

**Issue by henriiquecampos** [Automattic/simplenote-electron#1261]
### What
Add ability to edit note on external editor.

### Why
Since Simplenote doesn't offer the most pleasing markdown edit experience, which is good as it should really focus on its core features: note keeping, sync, organization, etc... It would be good to be able to edit them with a specialized editor, e.g. [Ghost](https://github.com/timsayshey/Ghost-Markdown-Editor). 

### How
Add a simple button that would open the file using the default editor for `.md` files
![image](https://user-images.githubusercontent.com/10171059/57582185-118fd280-7498-11e9-8168-8b98926400ac.png)

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
