### ISSUE TITLE
Number of notes per Tag not visible due to limited width / space 

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#1264]
I cannot see the number of notes per tag due to limited width / space.

The error applies with:
- Firefox
- Chrome

( Currently, the number of notes per tag is not available at all in the Andorid App ).

![Unbenannt](https://user-images.githubusercontent.com/22197180/65600501-81fb4400-dfa0-11e9-896c-1bcce5101fd5.JPG)

PS:
Background: I am migrating form Evernote but have no clue if I was successful so far.

**Comment by belcherj** [comment]
This is the old app. The new web app does not have note counts for tags at the moment.
