### ISSUE TITLE
Notes get erased instantly in New Tab - Chrome on Android

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/simplenote-electron#1266]
This issue was brought up by a user. The steps are a bit weird so I'm not sure how often this would happen but I was able to reproduce it.

In Chrome browser on Android, when you close Simplenote tab and open a new tab and navigate to app.simplenote.com/new when you start typing on the new note everything gets erased instantly.

Now for me, when I go to app.simplenote.com/new in Chrome it takes me to one of my pinned notes, not a new one but even when I open a new note from there and start typing it gets deleted instantly.

2007393-zen

### Expected
I would expect any text or notes would stay on the page not instantly get erased.

### Observed
Text/Notes immediately get erased - **this is in Chrome only. I could not reproduce this on Firefox.**

### Reproduced
1. Open Simplenote in Chrome browser on an Android device.
2. Close Simplenote tab and open a new tab in Chrome and navigate to app.simplenote.com/new
3. When you see the cursor appear, start typing and you will see the text gets deleted instantly

Make|Model|OS Version|App Version
-|-|-|-
Samsung|Galaxy S9 (SM-G960W)|Android 9.0|Simplenote 1.7.0
Moto|G5S Plus|Android 8.1|Simplenote 1.7.0
Samsung|Galaxy S7|?|Simplenote 1.7.0
Samsung|Galaxy S5|?|Simplenote 1.7.0
Huawei|?|?|Simplenote 1.7.0

**Comment by sarahfg** [comment]
Replicated by another user:

#2827725-zen

**Comment by azollafox** [comment]
Issue repeats in for the Chromebook user above in 2.4 and 2.5 of the Android app. Most recent ticket is at #2937827-zen

**Comment by dmsnell** [comment]
@gwensmithx would you mind checking this again at https://app.simplenote.com? It should be resolved now (in #2148).

I'm closing the issue because I believe it's fixed but we can re-open if it's still problematic for you (after clearing browser cache, if necessary).
