### ISSUE TITLE
Mobile Safari: Pulling down on the screen reveals history briefly

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-electron#1267]
### Expected
When pulling down on note screen, the history panel should not be visible.

### Observed
This is more of an UX glitch, but worth mentioning — when viewing https://app.simplenote.com/new on mobile Safari (iOS), the history panel is reveled and then slides back up:

![history_not_accessible 2019-05-20 13_08_21](https://user-images.githubusercontent.com/154014/58042460-623ea580-7b00-11e9-89ac-7b1f57bacf6f.gif)

Not sure if this also affects Android devices as well, but I assume so. Also, worth noting that when tapping the history icon on the toolbar, the history panel works as expected:

<img width="487" alt="Napkin 137 05-20-19, 1 09 28 PM" src="https://user-images.githubusercontent.com/154014/58042616-c82b2d00-7b00-11e9-982a-2f0d9b4ea235.png"><img width="502" alt="Screen Shot 2019-05-20 at 1 11 50 PM" src="https://user-images.githubusercontent.com/154014/58042640-db3dfd00-7b00-11e9-8af8-f665fc91fd74.png">

### Reproduced
1. In mobile safari, go to https://app.simplenote.com/new
2. Pull down on the screen
3. Briefly see the history panel appear
4. Let go of the screen
5. See the history panel spring back up

Make|Model|OS Version|App Version
-|-|-|-
iPhone|Xs|12.3|4.7.0

**Comment by belcherj** [comment]
Should be fixed in: https://github.com/Automattic/simplenote-electron/pull/1741
