### ISSUE TITLE
Mobile Safari: Cannot see/scroll display settings on small screen

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-electron#1268]
### Expected
In mobile Safari, the display settings dialog should be scroll-able.

### Observed
When viewing https://app.simplenote.com/new on mobile Safari (iOS), the display settings dialog bleeds past the edges of the screen and is not scroll-able. This results in many settings becoming inaccessible:

![cannot_scroll_settings 2019-05-20 13_24_07](https://user-images.githubusercontent.com/154014/58043366-9b781500-7b02-11e9-914c-835fba200d90.gif)

(I'm assuming this affects Android devices as well.)

### Reproduced
1. In mobile safari, go to https://app.simplenote.com/new
2. Navigate to the settings dialog
3. Tap the display tab
4. Notice how the dialog takes over the screen and you cannot scroll (the only way to dismiss the dialog is to table on the left/right edge of the screen).

Make|Model|OS Version|App Version
-|-|-|-
iPhone|Xs|12.3|4.7.0

**Comment by belcherj** [comment]
Fixed in: https://github.com/Automattic/simplenote-electron/pull/1767
