### ISSUE TITLE
Segmentation fault on Fedora 29

### ISSUE THREAD

**Issue by samtuke** [Automattic/simplenote-electron#1372]
### Expected
Running sn from terminal or app launcher works

### Observed
sn doesn't start and segfault error given:
`
/opt/Simplenote/simplenote
Segmentation fault (core dumped)
`

### Reproduced
Yes

Fedora 29|Simplenote-linux-1.5.0-i686

**Comment by codebykat** [comment]
We don't have any other (or recent) reports of this so I'm closing for now. @samtuke if you're not able to launch the most recent version of the app on Fedora please let me know!
