### ISSUE TITLE
Ability to sync to GIT automatically

### ISSUE THREAD

**Issue by tvvignesh** [Automattic/simplenote-electron#1384]
First of all thanks for this amazing note taking app.

### What
It would be great to provide an automatic sync option to GIT services like Gitlab/Github so that all the notes are available there whenever we want

### Why
Rather than having to manually export everytime, it is better to have all the repositories, associated todo, etc. all at one place so that its easier to manage. Also, if simplenote server crashes, all data must not go if it is not exported.

### How
An option in settings to enable/disable sync to GIT based services would be great.

**Comment by codebykat** [comment]
Thanks for this suggestion! It's not on our immediate roadmap, but I've added it to our list of feature requests for consideration.
