### ISSUE TITLE
Keyboard shortcut for markdown preview not working for Linux App

### ISSUE THREAD

**Issue by renl** [Automattic/simplenote-electron#1387]
The keyboard shortcut ctrl-shift-p for toggling markdown preview is not working for 64bit linux app

### Expected
***(Required)*** Ctrl-shift-p should toggle preview mode

### Observed
***(Required)*** Ctrl-shift-p should toggle preview mode
### Reproduced
***(Required)*** Press ctrl-shift-p

|OS Version|App Version
|Ubuntu 18.04|1.5.0
SYSTEM_MAKE|SYSTEM_MODEL|OS_VERSION|APP_VERSION

**Comment by qualitymanifest** [comment]
Works for me using Linux Mint 19 (Ubuntu 18.04) with Simplenote-Electron 1.5.0

**Comment by shitpoet** [comment]
I have the same problem with SimpleNote 1.6.0 on Debian 10 Buster

**Comment by dennisez** [comment]
I had the same problem on Ubuntu 18.04. I just disabled and then enabled again markdown formatting. Seems to work fine now.
