### ISSUE TITLE
Linux ability to snap windows into place

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#1393]
### What
Simplenote Linux user on Ubuntu 18.04.2 MATE 1.22.1 cannot use window snapping for Simplenote, and they think it's because the window will not resize to 1/4 of their screen size, even manually, on a 1920 x 1080 display.

On the Electron Mac version, I'm able to reduce the app to much smaller than 1/4 of my screen size, so I can't confirm that it's not possible on Linux. However, when they try to use window snapping with Simplenote, "it causes a fault on the OS."

### Why
This would allow Linux users to "snap" Simplenote to a corner of their screen, which can help keep it there and easily navigate their desktop.

### How
From the user: 

"I believe the problem is the app prevents me from even manually resizing the window to the size of 1/4 screen, so I believe that the inability to do such a resize is causing the fault."

ticket: #2108043-zen

**Comment by thwaller** [comment]
I have also reported this via the report errors within the program.

**Comment by sandymcfadden** [comment]
I've tested this in the latest Ubuntu version and am able to shrink the app size quite small way less than a quarter of my screen when using a wide display. Closing.
