### ISSUE TITLE
Exporting Notes: Save As dialog appears multiple times

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-electron#1394]
When exporting your notes, the save dialog appears multiple times depending on how many times you click the export button:

![export_issue](https://user-images.githubusercontent.com/154014/59936170-fd36e200-9414-11e9-84ea-e0c773e720ea.gif)

To repro:
1. On any OS (mac, Linux, Windows) open the Settings→Tools menu
2. Click the export button multiple times
3. Notice the "Save As" dialog appears multiple times

**Comment by codebykat** [comment]
This seems fine to me... it's typical browser behavior if you click a download link more than once. I suppose we could convert this link to look more like a file download, which is what it is?

**Comment by codebykat** [comment]
@SylvesterWilmott can you weigh in on this? Do we have an icon that would make it more clear that this is a file download link?

**Comment by SylvesterWilmott** [comment]
@codebykat we dont currently have an icon for this but I will create one. I'll keep you posted

**Comment by belcherj** [comment]
Closing as I think this is a non-issue. I would expect that the web would work like this.
