### ISSUE TITLE
Accessibility: Improve contrast of selected note in note list

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1397]
The selected note in the note list has a blue colour that does not have enough contrast with the background. Do not change the colour of the text.  Make the background of the note item in the list a light blue.

### What
The contrast of the note title and excerpt blue colour to the white background does not have enough contrast

### Why
Contrast for accessibility

### How
Make the background a light blue

<img width="336" alt="Screen Shot 2019-06-21 at 2 21 36 PM" src="https://user-images.githubusercontent.com/6817400/59943313-e9e54000-942f-11e9-9a99-659e436d2507.png">

**Comment by kchaplick** [comment]
I would like to work on this

**Comment by belcherj** [comment]
Merged
