### ISSUE TITLE
Web app doesn't start with pinned note

### ISSUE THREAD

**Issue by bakdar** [Automattic/simplenote-electron#1404]
When logging in to Simplenote web app, the screen doesn't start with the pinned note, but the note last modified. The pinned note is on the top of the list, but the app still doesn't start with it.

### Expected
When I log in, I expect to see the first note in the list, which would be the pinned list, if there is any.

### Observed
Web app starts with the note that was last modified, rather than the pinned note.

### Reproduced
Pin a note. Make modification to a note that is down the list. Log out and log back in.

**Comment by belcherj** [comment]
I have not been able to reproduce.  What browser? What OS?
