### ISSUE TITLE
Idea: only show last modified date and word count in Info

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#141]
After doing some quick looking, most note taking apps only provide the last modified date. I think this is probably the most helpful date, especially if you are working on a note together. In my opinion, the last modified date and the word count are the most important bits of info for a note taking app. If Simplenote were more of a writing app, I think there would be a case to add the creation date.

Also, right now I believe that Simplenote only shows the word count and the last modified date in any of the apps.

Can/should we remove the character count and the creation date from the Info panel?

**Comment by Pacerier** [comment]
Hey guys, what about the web version?
