### ISSUE TITLE
Notes get slow for very large note

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1412]
When a note is above ~80,000 words the note editing interface is slow.  Additional the web app is slow to load

### Expected
Note editing should not lag at any size

### Observed
Note editing interface lags

### Reproduced
1. Open up note pad
2. Grab some lorem ipsum
3. Copy and past it so that the word count is above 80,000 words
4. Paste into a new Simplenote note
5. Add some more text and observe the lag

**Comment by belcherj** [comment]
https://github.com/Automattic/simplenote-electron/issues/1457

**Comment by beber666** [comment]
I'm also experience this since multiple versions of Simple notes.
I'm on Mojave 10.14.3, Macbook pro End 2013  I7, 16GO Ram
It's also happens on notes with around 1000 words...
Typing, switching between notes is really slow.

Any workaround ?

**Comment by belcherj** [comment]
@beber666 you can use app.simplenote.com/old but be aware that the old app is no longer support or maintained.

**Comment by beber666** [comment]
It's works with this link
But not with the Mac App from Mac App Store. 
Even after a reinstall I still have the same issue

Thanks for your help

**Comment by belcherj** [comment]
https://github.com/Automattic/simplenote-macos/issues is where the MacOS issues live.  Thank you for your report.  They are aware of the issue.

**Comment by belcherj** [comment]
Duplicate of https://github.com/Automattic/simplenote-electron/issues/501
