### ISSUE TITLE
Overly aggressive markdown formatter 

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/simplenote-electron#1416]
Using v1.5.0, open a new note, enter a `+`, `-`, or `*` and hit enter/return. The char/line is erased.

### Expected
I expect I can have a line with a single character of this type.

### Observed
Seems like an overly aggressive Markdown formatter...if you type one of these characters followed by any character other than a space, it works.

### Reproduced
> 1. Open... New note
> 2. Type... `+`, `-`, or `*` and then hit enter/return
> 3. See error...

FWIW, does not reproduce on the web app.

Make|Model|OS Version|App Version
-|-|-|-

Simplenote-linux-1.5.0-amd64.deb running on Google Chrome (ChromeOS) 75.0.3770.102 (Official Build) beta (64-bit)

**Comment by belcherj** [comment]
This has been resolved. It will only be removed if you have the char and space
