### ISSUE TITLE
Spell check on Linux

### ISSUE THREAD

**Issue by thwaller** [Automattic/simplenote-electron#1435]
The spell check option, when checked, does not appear to work. Testing by intentionally misspelling words results in no user notification.

### Expected
When a spelling error exists, and the check spelling option is checked, the user should in some way be notified of the error, commonly done by a red underline on the word.

### Observed
Spelling errors appear just like every other word.

### Reproduced
This happens on all notes and all text within each note. I use English language if that might change things for others.

Make|Model|OS Version|App Version
Ubuntu 18.04.2 LTS 64-bit - Mate 1.22.1
Kernel 5.0.0-18
Simplenote version 1.6.0

**Comment by belcherj** [comment]
Should be resolve din https://github.com/Automattic/simplenote-electron/pull/2102, which will be in version 1.19

**Comment by mintchaos** [comment]
Can confirm that this is still happening in 2.1.0. Check spelling is checked in the edit menu. The linux flatpack is maybe missing a dependency? or expects it on the system?

![image](https://user-images.githubusercontent.com/1450/99754568-7b316980-2a9d-11eb-9393-efda223c9cd6.png)

**Comment by codebykat** [comment]
The new version currently does not support spellcheck. Sorry for the trouble, we hope to restore it in future. #2410

**Comment by slewis-royal** [comment]
@codebykat , 

Hi! Wondering if there has been any more movement on this front. Would be quite a useful feature. Thank you for your dedication!

Best, 

SL

**Comment by codebykat** [comment]
Thank you for asking so kindly, @slewis-royal! I'm sorry to report that there is nothing to report. It is still something we would like to prioritize in the future but it is unfortunately not straightforward to implement due to technical and cross-platform limitations. It is sadly not likely that it will happen soon. 😞

**Comment by slewis-royal** [comment]
@codebykat , 

I understand. Thank you for your prompt reply! All the best to you and other contributors.
