### ISSUE TITLE
Support tab(shift+tab) to indent(unindent) multiple lines

### ISSUE THREAD

**Issue by thebarbershop** [Automattic/simplenote-electron#1438]
### What

Support tab to indent, and shift+tab to unindent multiple selected lines. At least when markdown is enabled.

### Why

Indents in markdown are used to represent the level of lists. When you want to re-structure your list, you may have to (un)indent multiple lines at once. Selecting multiple lines and pressing tab(shift+tab) is the universal way to do this, being the default behaviour in so many text editors, even as simple as gedit and nano.

However, Simplenote currently doesn't support this. It replaces the selected text with a tab character when you hit tab, or doesn't do anything when you hit shift+tab. The only way to (un)indent multiple lines is to go through each line and edit one by one.

### Version

- Simplenote: <del>1.6.0</del> 1.5.0
- OS: Ubuntu 18.04

(Edit: I thought I updated the app to 1.6.0, but it seems I didn't. I couldn't get the AppImage or tar.gz work on my system for unknown reasons, and the new version doesn't seem to be on snapcraft yet, so I can't test this on 1.6.0. Although the release note doesn't seem to mention this feature, please let me know if this is already handled in the new version.)

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by samtuke** [comment]
I'm also missing this. Any update on the feature request, or where can I track it? Thanks.

**Comment by pachlava** [comment]
@samtuke Thanks for checking in! As for now, the latest available version [2.13.0](https://github.com/Automattic/simplenote-electron/releases/tag/v2.13.0) (as well as the [Web-App](https://app.simplenote.com/)) support multiline `Tab` / `Shift` + `Tab`. Please let us know if this doesn't work for you. Thank you!
