### ISSUE TITLE
Use lighter grey on dark mode for the background highlight

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1449]
https://github.com/Automattic/simplenote-electron/pull/1402#issuecomment-508473656

@SylvesterWilmott Could you clarify which grey you would like lightened up?

https://user-images.githubusercontent.com/31510727/59953395-d943c280-944d-11e9-83c3-26553ba158f6.png

https://user-images.githubusercontent.com/31510727/59953396-dd6fe000-944d-11e9-951f-3e7d0fe6bfd1.png

### What
Make grey lighter on dark mode for the background highlight

### Why
So it looks better

### How
Change the css

**Comment by SylvesterWilmott** [comment]
Hey! Yeah so, you find some information on this in the Design guidelines. For the current palette, we should use 1 shade lighter than the dark background as the highlight.
