### ISSUE TITLE
Enable automatic backup on Linux and Windows clients

### ISSUE THREAD

**Issue by berlinmitteinstitut** [Automattic/simplenote-electron#1454]
### What
Enable automatic backup on Linux and Windows clients to e.g. a specified folder

### Why
I had the case when sync messed up my notes, so I would like to have a daily backup up of my notes to a folder - also for future reference. Manual backups right now ("Export") need to be triggered manually, which is an extra step that someone must think of.

### How
See above.

**Comment by belcherj** [comment]
This feature has been noted but nothing planned in the short/medium term.
