### ISSUE TITLE
Simplenote 1.5 and 1.6 appear to be slow, may be 4K related

### ISSUE THREAD

**Issue by rbreaves** [Automattic/simplenote-electron#1456]
I've read prior bug reports about slowness but have not found a resolution or cause. My OS is KDE Neon 18.04 (based on Ubuntu 18.04, so I have installed the latest amd64 deb release).

### Expected
No real lag when clicking through or using my arrow keys in the interface.

### Observed
Clicking or using the arrow keys inside simplenote results in 3-5 seconds of lag. The lag is not noticeable until the application is fully loaded, after about 20-30 seconds.

### Reproduced
I suspect anyone can reproduce this bug if they're operating in  or above 4K resolution while on Linux, as I did not have this issue until I increased my resolution lately. Other apps do not appear to be hampered, although Kwin effects, like wobbly windows appear to be a little slower on my integrated intel graphics than before. I am certain this is not a compositor issue of the OS though, it'd be system wide and it is not.

To simulate a 4K or 4K+ experience on something lower end you can try something like this below. Personally I do this because font rendering and the general size of things look too massive, or too small, at 2560x1440, but resolve itself when the scale and framebuffer is increased. It also seems like macOS and Windows does something similar at these larger resolutions as well. 

Get the name of your active display device
```
xrandr --query
```

Change HDMI-3 below to your display name and set your native resolution under mode, double h and v resolution under fb and that should hopefully create a 4K or 4K+ experience for you to do tests with.
```
xrandr --output HDMI-3 --pos 0x0 --mode 2560x1440 --scale 2x2 --fb 5120x4680
```

Make|Model|OS Version|App Version
-|-|-|-
Apple|Macbook11,4 (2017 Pro model)|KDE Neon 18.04|Latest Simplenote 1.6

**Comment by belcherj** [comment]
@rbreaves Would you mind taking a look to see if you are still experiencing this issue?

**Comment by rbreaves** [comment]
I'm no longer using that setup, but I don't mind testing inside of a VM with Ubuntu Budgie later and see what happens.

**Comment by belcherj** [comment]
I have tested Ubuntu 20.04 in native 4k and have not experienced this issue.
