### ISSUE TITLE
Cursor Jumping on Windows

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-electron#1477]
I received a report from 2186283-zen where the user has been experiencing a bit of weird cursor jumping. They way they described it is that they will be writing a long and suddenly the cursor jumps to a weird place and a character will move. If you check out this image <img src="https://cdn-std.dprcdn.net/files/acc_593859/VNQzoS" />

The user described this as how this appeared
<blockquote>I re-installed Simplenote 1.6.0 on my Windows 8.1 machine as you advised
and waited to see if the problem would re-occur. It just did. In the
screenshot below I had typed the text "write[space]". As you can see the
"w" became rogue and jumped to the end of the line</blockquote>

I do not have a windows machine these days, so I was unable to replicate.

**Comment by qualitymanifest** [comment]
This happens to me every one in a while on Linux/Electron, in the current version and as far back as I can remember. It's very infrequent and I can't figure out a pattern to it, but it seems like something weird is happening with the selection. Last time it happened I tried highlighting the text and deleting it and I got `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The Node to be removed is not a child of this Node`.
