### ISSUE TITLE
Typing Korean results in almost half of the letters being automatically deleted

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/simplenote-electron#1511]
### Expected
To type Korean text and Simplenote to reflect exactly what the user typed.

### Observed
Typing Korean results in almost half of the letters being automatically deleted as you type.

### Reproduced
Open a new note and type in "나래", you will see that "래" is deleted. In other examples, if you type "홍삼" then it comes out as "홍마" with the "ㅅ" deleted.

Notes:

I figured it is a problem with Simplenote and not the iBus input method, since typing Korean works well in every other app I've tried. Or it could just be the integration of Simplenote with the cinnamon desktop

Here is some of my computer information:

Simplenote Verison: 1.6.0

Operating System: Fedora 30

Desktop Environment: Cinnamon 4.2.3

Input Method: iBus 1.5.20

Keyboard Layout: Korean (Korean lets you input English and Korean letters, only the Korean letters are deleted while you type)

Computer and processor: Acer Laptop with an intel 8th gen core i5

### More information / reported in
 - #2268728-zen
 - #2626282-zen
 - #2963812-zen

**Comment by thebarbershop** [comment]
Experiencing the same issue.

- Simplenote 1.7.0
- Ubuntu 18.04
- Gnome 3.28.2
- fcitx 4.2.9.6

This must be the most destructive bug for a note app.

**Comment by bohyunl** [comment]
i test some korean input method and this is result.
ibus-hangul : same above
fcitx-hangul : same above
uim-byeoru : works fine

**Comment by codebykat** [comment]
Can we re-verify that this one is still happening? It may have been fixed by #1714

**Comment by thehenrybyrd** [comment]
Another possible report in #2626282-zen. Waiting for some more details to determine whether it's the same issue, or https://github.com/Automattic/Simplenote-United/issues/33.

**Comment by belcherj** [comment]
We have internally tested this and are considering it resolved. Please comment if you think it needs to be revisited.
