### ISSUE TITLE
Move Icons to Left

### ISSUE THREAD

**Issue by thehenrybyrd** [Automattic/simplenote-electron#1513]
### What
Move Share, Trash, and other icons from the right side of the notes screen to the left.
As shown in this image provided by a user:

![JPhAJJx](https://user-images.githubusercontent.com/15107387/62928922-18ddb980-bdc2-11e9-87d6-b423d3cae43a.jpg)

### Why
It's a very long way to move the mouse all the way to the right to trash a note.

From a user report: #2269613-zen
It looks like we changed this sometime in 2017.

**Comment by belcherj** [comment]
Correct, this UI has been around since 2017 at `/new` and as of yesterday is the default web app for Simplenote. This UI is consistent with our other Simplenote clients (iOS, Android, etc). We may adjust the design in the future but nothing planned in the short/medium term.
