### ISSUE TITLE
Signup: Terms of Service link does nothing

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1521]
### Expected

On the signup screen, I expect that clicking the "Terms of Service" link will open the terms of service (either in the app or in a browser window).

### Observed

When I click the "Terms of Service" link, nothing happens.

### Reproduced

1. Log out of the app if logged in already.
2. Click the "Sign up" link.
3. Click the "Terms of Service" link.

![Screen Shot 2019-08-15 at 2 26 44 PM](https://user-images.githubusercontent.com/8658164/63097679-ffc33d00-bf68-11e9-8673-52e65cb2ea67.png)

**Comment by aheckler** [comment]
This seems to be back. @rfaile313 and I can both repro after seeing a customer run across this issue in 2370416-zen.

**Comment by rachelmcr** [comment]
@belcherj can confirm, but I believe this fix isn't out yet. Version 1.8.0 was frozen before this issue was reported/fixed, and due to the GM we haven't had a release since then. It should be fixed in the next release.

**Comment by aheckler** [comment]
Ahh, you're right:

https://github.com/Automattic/simplenote-electron/blob/v1.8.0/lib/auth/index.jsx#L149

Looks like the old version. I'll let the user know.
