### ISSUE TITLE
Login: Inconsistent wording (sign in) in login error message

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1523]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected

I expect the app to say "log in" (not "sign in") everywhere.

### Observed

If I try to log in with invalid account details, I get an error message using "sign in" instead:

> Could not sign in with the provided email address and password.

### Reproduced

1. Log out of the app if already logged in.
2. In the login fields, enter an invalid email and/or password.
3. Click the "Log in" button.

![Screen Shot 2019-08-15 at 2 32 44 PM](https://user-images.githubusercontent.com/8658164/63098993-07d0ac00-bf6c-11e9-900e-31677bd1140b.png)

**Comment by belcherj** [comment]
Fixed in: https://github.com/Automattic/simplenote-electron/pull/1534
