### ISSUE TITLE
Toggle Sidebar button non-responsive until dev console is opened

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1525]
### Expected

I expect that clicking the "Toggle Sidebar" button will expand/collapse the sidebar.

### Observed

Clicking the "Toggle Sidebar" button did nothing.

When I opened the dev console, the button suddenly started working and continued working after I closed the console.

### Reproduced

1. Log in to the app if needed.
2. Click the "Toggle Sidebar" button. Note that it is unresponsive.
3. Open the dev console (under Help > Advanced > Debugging Console).
4. Try again to toggle the sidebar.

Reproduced on both Windows 10 VM and macOS 10.14.5, with Simplenote 1.8-beta1

**Comment by codebykat** [comment]
This has happened to me twice now and I can't figure out how to consistently reproduce it. In both cases it did not start working when I opened the dev console, but did start working after I resized the window to be narrow enough that the toggle went away, and then back to full width.

**Comment by codebykat** [comment]
Three times and it seems to always happen when I first load up the dev environment in a browser, so some race condition with the cache possibly? Once I've loaded it in a browser logging out, reloading, and stopping and restarting the dev server fail to produce the bug again.
