### ISSUE TITLE
Flickers between two notes

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#1531]
### Expected
Open Simplenote, select one note and read/edit it

### Observed
The whole app flickers between two (oder more?) notes , see video below
You are not able to do anything.

### Reproduced
Happened on various Windows PC's independently
- on Electron (days before) and 
- on Web Version (today)

### Video:
https://youtu.be/h5OtylKxNwo

### Make|Model|OS Version|App Version
- Electron version before 1.7.0
- Web Version (Firefox)
...both Windows 10

**Comment by bummytime** [comment]
Bump. Seen by a user ~2 weeks ago → Chrome Version 79.0.3945.88 on Windows

**Comment by msilbers** [comment]
"When I use simplenote on the web (chrome) the screen flashes, flipping between notes, i can't select anything. it's usually between one of hte pinned notes & whichever one I am trying to actually read."

both Chrome and Internet Explorer
reported internally #2638774-zen

**Comment by msilbers** [comment]
Windows app and web app, Simplenote, v1.12.0
Flashing between notes while the notes are loading. seems to stop flashing once they are all loading in the browser

"after some experimentation, it seems like the period where this can happen is while notes are loading in."

reported in #2635070-zen

**Comment by msilbers** [comment]
"The browser version isn’t working at all now. It "flashes” and all I can make out is “no notes” and then goes blank. On different browsers it’s the same or at first it appears to be ok - I’m seeing the proper notes - but it’s very slow to switch between notes then will get stuck on a note and redisplay it rapidly and at that point it’s unresponsive."

reported in Safari and Brave, in #2626756-zen

**Comment by belcherj** [comment]
This should have already been resolved and is a different issue from #2085

**Comment by belcherj** [comment]
If you are still experiencing this issue please comment and I will reopen.
