### ISSUE TITLE
Add keyboard shortcut to make selected text Bold, Underscore & Italic in insert mode

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1536]
When we select any text and press

- Ctrl + B = Make it **Bold**
- Ctrl + U = Make it Underline
- Ctrl + I = Make it _Italic_

It would be great to have these options in Simplenote. I think Its a must have features.

@bummytime

**Comment by Donboscow** [comment]
@mirka any ETA?

**Comment by Donboscow** [comment]
@bummytime any ETA?

**Comment by belcherj** [comment]
This is not on our roadmap.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by ChiragKalia** [comment]
@belcherj Was this feature added? I don't see it in the latest version

**Comment by belcherj** [comment]
> @belcherj Was this feature added? I don't see it in the latest version

I am no longer at Automattic.
