### ISSUE TITLE
Create sync status 'text' or 'symbol indicator like rotating spinner' in menu bar

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1537]
Small 'saving' and 'saved' text indicator (it was present in the previous app.simplenote.com web interface) in menu bar will show us the sync status of our current editing note. It will be like Google Docs which shows "Saving.." and " All the changes saved in Drive" indication when we edit any docs.

Isn't it possible to place the animated moving/rotating (like dropbox sync indicator) spinner or [Saving and Saved] sign before the top [History, Share, Trash, Info] logos? I think it will be simpler and natural. Also to check the sync status you have to always leave the main view and go to the [Menu] which is quite distracting and unintuitive. In the previous app.simplenote.com website when you edited any note it showed live [Saving and Saved] status sign in the top right corner which is more natural and intuitive. 

@bummytime

**Comment by Donboscow** [comment]
@bummytime @belcherj any progress or ETA?

**Comment by belcherj** [comment]
This is not currently on our roadmap.

**Comment by Donboscow** [comment]
[is it](https://github.com/dear-github/dear-github/issues/361) in your roadmap? Any ETA? @belcherj

**Comment by belcherj** [comment]
This feature is not on our roadmap so I cannot provide an ETA. I am not sure what that linked issue is and cannot provide an ETA on that. If you are asking if Sign in WIth Google is on our roadmap you created an issue here: https://github.com/Automattic/simplenote-electron/issues/1010 We have no further update to the timeline than what was provided.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
