### ISSUE TITLE
Trash: note does not go away after deleting forever

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#154]
Whenever I delete a note forever, I have to refresh the page in order to see the change.

Alter deleting a note in Trash, the note is visible but I can't click on it.

Steps:
1. Go to Trash
2. Delete a note forever
3. The note is still there and can't click on it
4. Reload the app and go to Trash
5. The note is gone

**Comment by dar5hak** [comment]
Another scenario, which I believe is related to this same bug:

1. Empty your Trash.
2. Go to All Notes.
3. Open one of your non-deleted notes.
4. Go to Trash again.
5. The content of the previously selected note is still there in the contents pane.

Observed on the Linux app.

**Comment by drw158** [comment]
Could not reproduce bug.
