### ISSUE TITLE
Web App Doesn't work in Internet Explorer

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-electron#1544]
The Simplenote web app doesn't work when you try to access it using Internet Explorer. It will allow you to log in but once logged in, it is just a white screen. The old web app does work fine in IE though.

### Expected
Using IE, that when you log in, that you would be able to see your notes in the app.

### Observed
The new web app goes to a white screen when trying to access it via IE. 

### Reproduced
1. Open a new tab in IE.
2. Go to app.simplenote.com and log in
3. Notice it goes to a white screen with no information on it.
4. Go to app.simplenote.com/old and log in. 
5. Notice that the notes do display with the old web app.

Screen recording:
https://cld.wthms.co/GGAd0c

Tested using Browserstack and IE 11.

**Comment by bummytime** [comment]
FYI @belcherj ...

**Comment by belcherj** [comment]
Fixed in: https://github.com/Automattic/simplenote-electron/pull/1547
