### ISSUE TITLE
Show tags for each notes in note list view

### ISSUE THREAD

**Issue by sartrev** [Automattic/simplenote-electron#1552]
### What
***(Required)***  Show tags of notes in note list

### Why
***(Required)*** When I see the note list, I cannot know which tags every note belongs. I need to add tag info at the title as well so that I can know the categories of each note. If tags are shown under the title that would be very convenience.

### How
***(Optional)*** Show tags of notes under the title

**Comment by belcherj** [comment]
@SylvesterWilmott

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
