### ISSUE TITLE
Preview Shortcut Does Not Work in Incognito Browser Tab

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-electron#1553]
When using an incognito browse tab in Chrome, the web app doesn't recognize the keyboard shortcut to preview a note `ctrl+shift+p`

### Expected
When using `ctrl+shift+p` in an incognito browser, that it would show a preview of a markdown note. 

### Observed
When using `ctrl+shift+p` nothing happens. 

### Reproduced
1. Open a new incognito browser tab in Chrome 
2. Go to https://app.simplenote.com
3. Create a note with markdown in it. 
4. `ctrl+shift+p` to preview the note.
5. Notice nothing happens.

Reproduced using Chrome Version 76.0.3809.100 (Official Build) (64-bit) and macOS Mojave 10.14.6

Initially reported in #2288146-zen

Might be related to: https://github.com/Automattic/simplenote-electron/issues/1387

**Comment by Robertght** [comment]
It doesn't work at all for me, regardless of Incognito or not.

**Comment by msilbers** [comment]
A user reported that Ctrl+Shift+P is how to open the OS print dialog and so it is not working as a keyboard shortcut to switch to Markdown Preview for them.

Linux ubuntu 18.04 Chrome 
internal report #2366584-zen

**Comment by belcherj** [comment]
Fixed in https://github.com/Automattic/simplenote-electron/pull/1788
