### ISSUE TITLE
Migrate Workflows to YAML

### ISSUE THREAD

**Issue by mdawaffe** [Automattic/simplenote-electron#1561]
The current HCL syntax for [workflows](https://github.com/Automattic/simplenote-electron/blob/add6b867b455bb6eb05ced2c9fe1600f4e124b0b/.github/main.workflow) will be disabled on 2019/09/30.

There are migration instructions and tools at https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax#converting-workflow-files-in-your-repository-to-yaml-syntax

**Comment by belcherj** [comment]
Done
