### ISSUE TITLE
New WEB version not synced at times

### ISSUE THREAD

**Issue by damamasss** [Automattic/simplenote-electron#1562]
Bug about new Web version of Simplenote. 
Use mainly Google Chrome, but bug also in other browsers. 

### Expected.
That my new added text will be synced

### Observed.
In web mode add my text, all was good, but not find this text in Simplenote on my iPhone and iPad. Tested and understood that web not synced. Refresh page - again, text have in web mode, but not synced. I log out and log in again and see that one of some added sentences (about 100 chars) duplicate about 10 times

### Reproduced
Start reproduce after update Web in August 2019, when new version is main version, and when version which was earlier now is old version. In OLD version today not have this bug. 

-|-|Windows 10 x64|Chrome x64 and other browsers, update August 2019

**Comment by damamasss** [comment]
This is Log from console of Google Chrome x64 76.0.3809.132 (64). This  when try to create a new note, add new text to other bote, but nothing happens. 
After about 1 hour of a normal job

> Active service worker found, no need to register
> serviceworker.js:1 Uncaught (in promise) DOMException
> app.442a6d438e0b78c3d968.js:146 Simperium config: Production
> 9serviceworker.js:1 Uncaught (in promise) DOMException
> app.442a6d438e0b78c3d968.js:128 Uncaught (in promise) Error: Delta length (122135) does not equal source text length (114851).
>     at i.diff_fromDelta (app.442a6d438e0b78c3d968.js:128)
>     at l.apply_object_diff (app.442a6d438e0b78c3d968.js:128)
>     at app.442a6d438e0b78c3d968.js:128
>     at Object.t.apply (app.442a6d438e0b78c3d968.js:128)
>     at app.442a6d438e0b78c3d968.js:20
>     at app.442a6d438e0b78c3d968.js:146
>     at Object.noteUpdatedRemotely (app.442a6d438e0b78c3d968.js:20)
>     at c.<anonymous> (app.442a6d438e0b78c3d968.js:146)
>     at c.s.emit (app.442a6d438e0b78c3d968.js:20)
>     at app.442a6d438e0b78c3d968.js:128
> i.diff_fromDelta @ app.442a6d438e0b78c3d968.js:128
> l.apply_object_diff @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> t.apply @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:146
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:146
> s.emit @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> Promise.then (async)
> c.update @ app.442a6d438e0b78c3d968.js:128
> onChannelUpdate @ app.442a6d438e0b78c3d968.js:128
> s.emit @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> p @ app.442a6d438e0b78c3d968.js:27
> l @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> a.put.onsuccess @ app.442a6d438e0b78c3d968.js:47
> IndexedDB (async)
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> p @ app.442a6d438e0b78c3d968.js:27
> l @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u.onsuccess @ app.442a6d438e0b78c3d968.js:47
> IndexedDB (async)
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> s.then @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> n @ app.442a6d438e0b78c3d968.js:27
> h @ app.442a6d438e0b78c3d968.js:27
> s @ app.442a6d438e0b78c3d968.js:27
> a.get @ app.442a6d438e0b78c3d968.js:47
> c.performChange @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> p.run @ app.442a6d438e0b78c3d968.js:128
> b.<computed> @ app.442a6d438e0b78c3d968.js:52
> w @ app.442a6d438e0b78c3d968.js:52
> E @ app.442a6d438e0b78c3d968.js:52
> serviceworker.js:1 Uncaught (in promise) DOMException
> app.442a6d438e0b78c3d968.js:20 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
>     at app.442a6d438e0b78c3d968.js:20
>     at app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> Promise.then (async)
> u @ app.442a6d438e0b78c3d968.js:128
> c.update @ app.442a6d438e0b78c3d968.js:128
> c.add @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:146
> onNewNote @ app.442a6d438e0b78c3d968.js:146
> onClick @ app.442a6d438e0b78c3d968.js:146
> (anonymous) @ app.442a6d438e0b78c3d968.js:120
> _ @ app.442a6d438e0b78c3d968.js:120
> (anonymous) @ app.442a6d438e0b78c3d968.js:120
> O @ app.442a6d438e0b78c3d968.js:120
> j @ app.442a6d438e0b78c3d968.js:120
> C @ app.442a6d438e0b78c3d968.js:120
> P @ app.442a6d438e0b78c3d968.js:120
> Mn @ app.442a6d438e0b78c3d968.js:120
> Fn @ app.442a6d438e0b78c3d968.js:120
> t.unstable_runWithPriority @ app.442a6d438e0b78c3d968.js:128
> fo @ app.442a6d438e0b78c3d968.js:120
> Du @ app.442a6d438e0b78c3d968.js:120
> (anonymous) @ app.442a6d438e0b78c3d968.js:120
> serviceworker.js:1 Uncaught (in promise) DOMException
> app.442a6d438e0b78c3d968.js:20 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
>     at app.442a6d438e0b78c3d968.js:20
>     at app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> Promise.then (async)
> u @ app.442a6d438e0b78c3d968.js:128
> c.update @ app.442a6d438e0b78c3d968.js:128
> c.add @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:146
> onNewNote @ app.442a6d438e0b78c3d968.js:146
> onClick @ app.442a6d438e0b78c3d968.js:146
> (anonymous) @ app.442a6d438e0b78c3d968.js:120
> _ @ app.442a6d438e0b78c3d968.js:120
> (anonymous) @ app.442a6d438e0b78c3d968.js:120
> O @ app.442a6d438e0b78c3d968.js:120
> j @ app.442a6d438e0b78c3d968.js:120
> C @ app.442a6d438e0b78c3d968.js:120
> P @ app.442a6d438e0b78c3d968.js:120
> Mn @ app.442a6d438e0b78c3d968.js:120
> Fn @ app.442a6d438e0b78c3d968.js:120
> t.unstable_runWithPriority @ app.442a6d438e0b78c3d968.js:128
> fo @ app.442a6d438e0b78c3d968.js:120
> Du @ app.442a6d438e0b78c3d968.js:120
> (anonymous) @ app.442a6d438e0b78c3d968.js:120
> serviceworker.js:1 Uncaught (in promise) DOMException
> app.442a6d438e0b78c3d968.js:128 Uncaught (in promise) Error: Delta length (123349) does not equal source text length (114851).
>     at i.diff_fromDelta (app.442a6d438e0b78c3d968.js:128)
>     at l.apply_object_diff (app.442a6d438e0b78c3d968.js:128)
>     at app.442a6d438e0b78c3d968.js:128
>     at Object.t.apply (app.442a6d438e0b78c3d968.js:128)
>     at app.442a6d438e0b78c3d968.js:20
>     at app.442a6d438e0b78c3d968.js:146
>     at Object.noteUpdatedRemotely (app.442a6d438e0b78c3d968.js:20)
>     at c.<anonymous> (app.442a6d438e0b78c3d968.js:146)
>     at c.s.emit (app.442a6d438e0b78c3d968.js:20)
>     at app.442a6d438e0b78c3d968.js:128
> i.diff_fromDelta @ app.442a6d438e0b78c3d968.js:128
> l.apply_object_diff @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> t.apply @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:146
> (anonymous) @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:146
> s.emit @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> Promise.then (async)
> c.update @ app.442a6d438e0b78c3d968.js:128
> onChannelUpdate @ app.442a6d438e0b78c3d968.js:128
> s.emit @ app.442a6d438e0b78c3d968.js:20
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> p @ app.442a6d438e0b78c3d968.js:27
> l @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> a.put.onsuccess @ app.442a6d438e0b78c3d968.js:47
> IndexedDB (async)
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> s.then @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> n @ app.442a6d438e0b78c3d968.js:27
> h @ app.442a6d438e0b78c3d968.js:27
> s @ app.442a6d438e0b78c3d968.js:27
> a.put @ app.442a6d438e0b78c3d968.js:47
> c.updateObjectVersion @ app.442a6d438e0b78c3d968.js:128
> c.applyChange @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> Promise.then (async)
> c.applyChange @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> p @ app.442a6d438e0b78c3d968.js:27
> l @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u.onsuccess @ app.442a6d438e0b78c3d968.js:47
> IndexedDB (async)
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> p @ app.442a6d438e0b78c3d968.js:27
> l @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> IndexedDB (async)
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> p @ app.442a6d438e0b78c3d968.js:27
> l @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> a.put.onsuccess @ app.442a6d438e0b78c3d968.js:47
> IndexedDB (async)
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> p @ app.442a6d438e0b78c3d968.js:27
> l @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u.onsuccess @ app.442a6d438e0b78c3d968.js:47
> IndexedDB (async)
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> u @ app.442a6d438e0b78c3d968.js:52
> characterData (async)
> r @ app.442a6d438e0b78c3d968.js:52
> n @ app.442a6d438e0b78c3d968.js:52
> (anonymous) @ app.442a6d438e0b78c3d968.js:27
> c @ app.442a6d438e0b78c3d968.js:27
> s.then @ app.442a6d438e0b78c3d968.js:27
> (anonymous) @ app.442a6d438e0b78c3d968.js:47
> n @ app.442a6d438e0b78c3d968.js:27
> h @ app.442a6d438e0b78c3d968.js:27
> s @ app.442a6d438e0b78c3d968.js:27
> a.get @ app.442a6d438e0b78c3d968.js:47
> c.performChange @ app.442a6d438e0b78c3d968.js:128
> (anonymous) @ app.442a6d438e0b78c3d968.js:128
> p.run @ app.442a6d438e0b78c3d968.js:128
> b.<computed> @ app.442a6d438e0b78c3d968.js:52
> w @ app.442a6d438e0b78c3d968.js:52
> E @ app.442a6d438e0b78c3d968.js:52
> serviceworker.js:1 Uncaught (in promise) DOMException

**Comment by msilbers** [comment]
"After clicking to delete a note, every time they almost immediately "reappear" in my main list.
And in general, updates and edits made in my notes in the Web App tend to not be saved (the notes go back to a previous version)."

Chrome: Version 76.0.3809.132 (Official Build) (64-bit) 
Firefox: Version 68.0.2 (64-bit) 

/old works for them
internal reference #2316289-zen

**Comment by msilbers** [comment]
"When using Simplenote with Chrome on my MacBook the notes aren't syncing. I have tried different networks (home and studio)."

reported by a user (internal reference #2323256-zen)

**Comment by vrubzov1957** [comment]
I have same problem. On NEW and on OLD version. Dont sync after some time of using
