### ISSUE TITLE
New notes should open immediately 

### ISSUE THREAD

**Issue by forteller** [Automattic/simplenote-electron#1566]
Thank you for a great product!

### What
When the Linux application is resized so that there is no sidebar but only a list of notes (or a note itself), clicking on the New Note button only creates a new note in the list, and you have to manually click on it to open it and start typing.

### Why
It is very counterintuitive, and not at all usefull, that you have to open the new note after creating it. The thing you expect after clicking the butto is to be able to start typing immediately, which is the case when the application window is sized large enough that there is a sidebar. This throws me a tiny bit off every time it happens.

Thank you!

**Comment by SylvesterWilmott** [comment]
@belcherj this is a great idea.

**Comment by dmsnell** [comment]
Resolved in #1582

**Comment by forteller** [comment]
Thanks for fixing this! But it only works when clicking the New note icon. When using Ctrl+N it still exhibits the old behavior. Hope this can be fixed. Thanks!
