### ISSUE TITLE
Web: Autodetect Dark Mode in Safari

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#1568]
### What
There's apparently now a way for websites to support light and dark themes in Safari via a meta tag. This came up in conversation so I'm not sure I thoroughly grok it but it appears to be this: https://webkit.org/blog/8840/dark-mode-support-in-webkit/

### Why
Feature request from a user :) If you use dark mode I guess this means the webapp would always match your system settings.

**Comment by belcherj** [comment]
Done and done
