### ISSUE TITLE
Can you support Chinese?

### ISSUE THREAD

**Issue by zero-hugo** [Automattic/simplenote-electron#1569]
Can you support Chinese? I like this software very much, but this software does not support Chinese very well, Chinese typesetting is very bad, and the text is too crowded.
In addition, can you achieve instant display of Markdown? Like Typora.

**Comment by codebykat** [comment]
Hi @zero-hugo, would it be possible for you add some screenshots? What do you mean by "typesetting is very bad, and the text is too crowded"? I tested with some sample text in Chinese, Korean and Japanese and the typography looks okay to me, but I am not a native speaker of any of those languages. It would be helpful if you could explain more about why it is bad and what you would expect to see instead.

Also, what browser and OS are you using?

**Comment by caoxuCarlos** [comment]
![Screenshot from 2019-10-27 11-02-22](https://user-images.githubusercontent.com/48681480/67628951-650ca600-f8a9-11e9-9331-21a0f1543593.png)
I may meet the same problem on Chinese character display. 
The left is what shows in simplenote and the right is what it should be.

**Comment by codebykat** [comment]
Ahh thank you! This seems to be the same issue as https://github.com/Automattic/simplenote-electron/issues/788, so I'm closing as a duplicate. Looks like we have a [fix](https://github.com/Automattic/simplenote-electron/pull/1205) in the pipeline.
