### ISSUE TITLE
Monospace font for markdown

### ISSUE THREAD

**Issue by dotwardo** [Automattic/simplenote-electron#1570]
Hey, so I've been using Simplenote for quite a while now. I use the markdown mode on almost all my notes, but one thing that really bugs me is how the font is sans serif instead of a monospace font.

I think it would be great if there was a setting for enabling a mono font whenever a note is in the markdown code editor.

I know there was a PR to add monospace fonts a while ago but someone closed it. It'd be great if you guys can consider this.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by adams141** [comment]
Was this made a feature request and then closed, but not done?

**Comment by codebykat** [comment]
Hi @adams141, we use GitHub issues for tracking bugs and work that's on our immediate roadmap. Our feature requests are logged internally -- so it was tracked, but closed as it's not on our roadmap at the moment. We look at those requests at a high level when planning future work. Hope that clarifies things 😄

**Comment by louwers** [comment]
I'd like to indicate my interest for this. Simplenote is not usable to save code snippets due to lack of Monospace support.

**Comment by kubasejdak** [comment]
Any updates/plans for this in a near future?

**Comment by codebykat** [comment]
@kubasejdak See https://github.com/Automattic/simplenote-electron/issues/274#issuecomment-892934934 for an update, but it may not be "near future" depending on your definition of "near".

**Comment by Emnolope** [comment]
I second this feature.
