### ISSUE TITLE
Add check lists to Mac app

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/simplenote-electron#1575]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
This request comes from Twitter: 
https://twitter.com/DanielGenser/status/1174288070268596224

### Why
Having the ability to add check lists through the Mac App would mirror the abilities of simplenote on other OS.

**Comment by belcherj** [comment]
Both the macOS native and Mac Electron have the ability to add checklists.  By typing `- [ ]` a checklist item is added.

**Comment by dd32** [comment]
On the Mac app, Option + Command + C or Format -> Insert Checklist is also available.
