### ISSUE TITLE
Bold headings in markdown editor mode

### ISSUE THREAD

**Issue by vacocege** [Automattic/simplenote-electron#1578]
### What
The macOS version of Simplenote bolds headings in the editor while writing markdown notes, making it easier to visualize sections of content. Can we add this feature to the electron app?

### How
Simplenote macOS screenshot
Notice the bold text of the ## h2.
![Simplenote macOS screenshot](https://simplenoteblog.files.wordpress.com/2018/02/screen-shot-2018-02-20-at-2-08-15-pm.png?w=1330)
We could add a `data-heading=true` prop to HTML heading elements. Currently there isn't a difference between the HTML of headings and regular text therefore you can't use CSS to change the font weight.
![HTML of a heading element in the markdown editor](https://user-images.githubusercontent.com/55606968/65364615-da5ccb00-dbc7-11e9-9ff8-8d06265e69f4.png)

**Comment by roxihe7880** [comment]
PR #1727 was closed because of performance reasons. A large part of the app may have to be rewritten in order to implement this functionality.

**Comment by dmsnell** [comment]
> PR #1727 was closed because of performance reasons.

Just for clarity sake @roxihe7880 - it wasn't closed for performance reasons. It was closed more because it takes a piecemeal approach to highlighting Markdown syntax which might end up making it harder to do full syntax highlighting/formatting.

**Comment by wolisox428** [comment]
All or nothing.
