### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#16]
The app should support localization, where possible.

**Comment by drw158** [comment]
Latest: publishing individual npm modules has failed

https://github.com/Automattic/wp-calypso/pull/3300#issuecomment-218184051

**Comment by deBhal** [comment]
The good news, though, is that `i18n-calypso` has been pulled out into it's own repo - [gh](https://github.com/Automattic/i18n-calypso), published to [npm](https://www.npmjs.com/package/i18n-calypso) so you can just `npm install --save i18n-calypso`.
There's also [i18n-calypso-localize](https://www.npmjs.com/package/i18n-calypso-localize) to help with live locale switching.

That provides the client side, but we don't have a step-by-step guide on setting up serving the localised strings.

We should have better resources on that, but it's all about internal infrastructure, so let's move that discussion to the the i18n p2.

**Comment by iamgabrielma** [comment]
Request for i18n: 1872258-zen

**Comment by belcherj** [comment]
Added to ideas board.
