### ISSUE TITLE
Introduce Folders and/or Tree Structure

### ISSUE THREAD

**Issue by oicitrapdraz** [Automattic/simplenote-electron#1600]
I'm aware of #432 and  #1019, but do you still have no plans ever to change the tagging system? It's a mess to have notes about any topic in the universe visually together in the left sidebar. Directories and files aren't an alien concept and a lot of desktop users could expect to have something like this in an app like Simplenote, it's intuitive and common.

For example, what can I do if I want to group all my programming tags (Ruby, Python, R, C) together? I can't so I have to tag all the notes I do about programming with another tag (for example I have to tag the notes about Ruby with `Ruby` and `Programming`, tag the notes about `Python` with `Python` and `Programming`, and so on), apart from this extra effort at the end of the day all tags have the same nested level, so it's also unnatural to group notes in a broader topic using other tags...

I understand that there are some benefits using tags instead of directories because a note can have multiple tags meanwhile a file can belong to only one parent folder, but there's no need to delete the tag system to introduce directories, they could both perfectly coexist.

**Comment by martinRibotDeBressac** [comment]
+1, i would love to not be overwhelmed when i am trying to look for a note from 7 monthes ago
