### ISSUE TITLE
Key input is missing/buggy after Japanese IME conversion on Ubuntu18.04

### ISSUE THREAD

**Issue by yamaryoxxxx** [Automattic/simplenote-electron#1619]
### Expected
1. Focus the Editor Area of the app
2. Activate Japanese IME
3. Press `a` => Japanese character `あ` is displayed
4. Press `o` => Japanese character `お` is displayed
5. Press Space bar => characters `あお` is converted to `青`
6. Goto 3. and repeat 3, 4, and 5.
7. You'll get `青青青青青青青青青青...` displayed

### Observed
7. I got something like `青あおあおおあおあおあおおあおおあ` in Simplenote Linux app 1.8.0, Web app with Google Chrome, while it works fine on Web app with Firefox.

* If you press Enter key after each step 5 (after each IME conversion), it works fine. This problem seems to happen when you don't press Enter key after IME conversion and continue input.

#### Web app & FireFox (works fine!)
![simplenote-firefox](https://user-images.githubusercontent.com/34907379/66101279-315f9880-e5e9-11e9-81c0-72577c868c5a.gif)

#### Web app & Google Chrome (not working fine)
![simplenote-chrome](https://user-images.githubusercontent.com/34907379/66101372-90bda880-e5e9-11e9-8e58-3e16b6a5f1b0.gif)

#### Electron App (not working fine)
![simplenote-app](https://user-images.githubusercontent.com/34907379/66101452-dbd7bb80-e5e9-11e9-8a70-b6ff953fb26a.gif)

### Environment
OS: Ubuntu 18.04.3 LTS
App Version: 1.8.0
Google Chrome Version: 77.0.3865.90 (Official Build) (64-bit)
Firefox Version: 69.0.1 (64-bit)
Japanese IME: Mozc (IBUS)
Mozc Version: 2.20.2673.102

Similar problem is not observed with other web apps on chrome or electron apps. (like google keep, boostnote, evernote, vscode, etc...)

**Comment by belcherj** [comment]
Please retest on app.simplenote.com. If it is fixed there it will be fixed in version 1.12.0

**Comment by yamaryoxxxx** [comment]
I retested on app.simplenote.com, but it seems not fixed. (In firefox, it's working fine. It HAD BEEN working fine since when I opened this issue.)

![unfixed-chrome](https://user-images.githubusercontent.com/34907379/69203465-b85fd480-0b87-11ea-80a9-2b05bf6acd23.gif)

![fine-firefox](https://user-images.githubusercontent.com/34907379/69203516-dc231a80-0b87-11ea-8fcf-2d69c2ee3ed9.gif)

**Comment by yamaryoxxxx** [comment]
And.. it seems that I cannot reopen this issue!

**Comment by codebykat** [comment]
Hmm this is a weird one. I can't reproduce it in Electron or on any browser on OSX. Out of curiosity, which IME are you using? I'm using the Google one...

**Comment by yamaryoxxxx** [comment]
I reproduced it in the following environments, both same results.

OS: Ubuntu "18.04.3 LTS" and "19.10"
App: Latest App and Web(Google Chrome)
Japanese IME: Mozc with "IBUS" and "Fcitx" (Mozc is google one for linux, de-facto standard of Japanese input on linux)

**Comment by yamaryoxxxx** [comment]
Finally I found that this is a problem of draft.js's, not simplenote's.
I'll check their repo and try to find solutions. Thanks!

![draftjs](https://user-images.githubusercontent.com/34907379/69944283-3af27780-152a-11ea-8f76-e4c3b58a88c2.gif)

**Comment by mirka** [comment]
Re-tested with 1.21.1 on Ubuntu 18.04.1 with mozc ibus, and can confirm that this is still an issue. (cc @belcherj)

**Comment by dmsnell** [comment]
@mirka we don't have a desktop release for the 2.0 versions. we'll need to test on https://app.simplenote.com or wait for the beta _or_ confirm with a build from a PR, [such as these](https://app.circleci.com/pipelines/github/Automattic/simplenote-electron/1616/workflows/0e664370-a365-4597-a458-cfb1603dd0c1/jobs/17634/artifacts)

**Comment by mirka** [comment]
Ah ok, wasn't aware of that. I re-tested on Ubuntu 20.04.1 with Simplenote Web 2.0.0-rc5 in Chrome, and the issue is gone.
