### ISSUE TITLE
Flatpak version for Linux

### ISSUE THREAD

**Issue by chernyaknikita** [Automattic/simplenote-electron#1622]
I know that Simplenote is avaible via Snap and AppImage but Snap isn't supported by the whole community and AppImage hasn't proper update system. Flatpak version would be really useful since Flatpak doesn't have such issues.
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by belcherj** [comment]
We do not officially create the Snap for Simplenote.  We use Electron builder to generate the builds. When it supports Flatpak we will. https://github.com/electron-userland/electron-builder/issues/512

I will add this to our feature request backlog.
