### ISSUE TITLE
Search: Add "sort by" to search results

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#1625]
## Updated designs:

<img width="328" alt="Screen Shot 2020-12-23 at 10 28 55 PM" src="https://user-images.githubusercontent.com/52152/103066722-4ddd4d00-456e-11eb-9bf6-d89284f1c3ee.png">

https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fd77f1846903987b1b40e75

<img width="327" alt="Screen Shot 2020-12-23 at 10 35 01 PM" src="https://user-images.githubusercontent.com/52152/103067127-1f13a680-456f-11eb-9329-f12d2c54d052.png">

https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fd77f196e43637c2cb2889f

## Old designs below

See designs at p2XJRt-1k0-p2

<img width="332" alt="Screen Shot 2019-10-04 at 1 23 44 PM" src="https://user-images.githubusercontent.com/52152/66237573-36385100-e6aa-11e9-843a-a7a0c7342ef4.png">

  
<img width="361" alt="Screen Shot 2019-10-04 at 1 25 18 PM" src="https://user-images.githubusercontent.com/52152/66237643-70a1ee00-e6aa-11e9-985b-dd7959ea57e8.png">

Options: Relevance, alphabetically, created, modified

**Comment by pachlava** [comment]
[testing] fix/feature verified on Dell Latitude 7400 | Win 10 | Simplenote 2.7.0-beta1
