### ISSUE TITLE
Search: Allow searching for untagged notes with tag: syntax

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#1644]
[Allegedly](https://github.com/Automattic/simplenote-electron/issues/355) you used to be able to search for untagged notes with `tag:untagged`, that no longer seems to work. We should have some way to search for untagged notes.

See also https://github.com/Automattic/simplenote-electron/issues/1230 (untagged notes in sidebar!)

**Comment by dctr** [comment]
Also open for macOS: https://github.com/Automattic/simplenote-macos/issues/120
