### ISSUE TITLE
1.8.0 "Release Notes" Button 404s

### ISSUE THREAD

**Issue by mrwweb** [Automattic/simplenote-electron#1659]
In Windows Simplenote 1.8.0, clicking the "Release Notes" button in the update dialog takes me to a 404ed URL: 

> https://github.com/Automattic/simplenote-electron/blob/master/CHANGELOG.md

I don't know if this issue is resolved in 1.9.0 or not, so I'm filing this as a bug in case this slipped through.

![Focused "Release Notes" button in update dialog for Simplenote 1.8.0](https://user-images.githubusercontent.com/1238696/67231728-c38edb80-f3f4-11e9-8bd1-89ebe69caac7.png)

### Expected
Should go to:

> https://github.com/Automattic/simplenote-electron/blob/master/RELEASE-NOTES.txt

**Comment by belcherj** [comment]
Thank you! This is indeed a bug.  I will get it sorted in the next version.
