### ISSUE TITLE
Duplicated content issue on web app

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#1661]
It's most likely that this is happening when Simplenote is open in more than one place, with the release of Simplenote Electron 1.9.0.

### Observed
When editing a note, it starts to add recently added content (a line, phrase, or word) repeatedly, until you close the browser window.

So far reported for Chrome and Firefox

Internal report references: #2439782-zen, #2440215-zen, #2439988-zen

**Comment by freesonwang** [comment]
I am seeing the same exact behavior as well across all devices - web (I use Chrome), Mac app, and iOS app (I guess I use Simplenote a lot!). For me, this has just started happening last night Wed Oct 23.

**Comment by belcherj** [comment]
This has been resolved in 1.9.1
