### ISSUE TITLE
Allow for tag sidebar / menu to remain open

### ISSUE THREAD

**Issue by dctr** [Automattic/simplenote-electron#1665]
### What

Currently, if you click on the three-bar icon (top left, tooltip "menu") the sidebar with the tags opens. But as soon as you click on a tag, the sidebar closes again.

On the macOS version in place of the three-bar menu button there is a tag icon (tooltip "Show Sidebar") and the sidebar doesn't close when you select a tag.

I would argue to adopt the macOS behaviour in the electron version.

### Why

My personal preference is to keep the sidebar open, of course, or else I wouldn't open this issue, but I also have a few objective reasons: In other note apps like OneNote and Evernote the organising hierarchy sidebar is usually always visible. If you have at lot of notes which you don't know the exact content of and which are sorted by tags, you are likely to use the tags more frequently, not the search function, to find your notes. 

The bar also does not take a lot of horizontal space, especially in an age of wide screens. The default line length setting is "Narrow" which leaves quite a bit of empty screen real estate that would be free to use. And if it is about non-cluttered screen space, there is focus mode already.

### How

Implementation-wise it would probably be about removing the on-click handler for the menu items in the sidebar.

An option would be a toggle under "View" (like Line Length, Order, etc.) so you could set behaviour according to your preference. As non-breaking upgrade path, this option then would not be set when upgrading.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
