### ISSUE TITLE
Login: Log in with WordPress.com logged user out of browser

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1677]
@rfaile313 reported this during beta testing:

> Logging into the Simplenote App via my WordPress.com account logged me out of WordPress.com in my browser and I had to re-log the next time I went to view a WordPress.com link.

### Steps to Reproduce

I wasn't able to reproduce the issue on a Windows 10 VM, logged in to Edge and Chrome with the same account I used to log in to the app. @rfaile313 if you have steps to consistently reproduce this, please feel free to comment or edit this issue with those details!

### Testing details

Simplenote Version: 10.10.0-beta1
Operating System: Windows 10
Version: 1903
OS Build: 18362.418

**Comment by belcherj** [comment]
I think this was a temporary issue.  Closing.  If someone reproduces please reopen.
