### ISSUE TITLE
Login: Loading Notes message does not appear after login

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1678]
When I log in to my account, I only ever see the "No Notes" message (even if my account has notes), not the "Loading Notes" message added in https://github.com/Automattic/simplenote-electron/pull/1650. cc @dmsnell 

### Expected

I expect that if I have an account with notes, while the notes are syncing (e.g. after login or after launching the app while logged in) I'll see a "Loading Notes" message.

### Observed

When I log in to my account in the app, I only ever see the "No Notes" message.

### Reproduced

1. Start logged out of the app.
2. Throttle your network connection (to slow down the notes syncing).
3. Log in to an account with notes.
4. While the notes are syncing, observe what message you see on screen.

![Screenshot 2019-10-29 11 06 39](https://user-images.githubusercontent.com/8658164/67761981-44c12080-fa3c-11e9-9dbd-051a353e8497.png)

Reproduced on Windows 10 VM, Simplenote Electron version 1.10.0-beta1.

**Comment by dmsnell** [comment]
Resolved by #1680
