### ISSUE TITLE
Add an option in settings to let us make/choose/set up the left panel from notes & tags

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1679]
### What

***When we open simplenote it shows us the notes column in left panel by default. Add an option in settings to let us set up the left panel from notes & tags.***

### Why

***When we have lots of notes (more than 40) then it will make the simplenote app more user friendly by setting the left tags first.***

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
