### ISSUE TITLE
Tab keys to indent multiple-lines

### ISSUE THREAD

**Issue by alvhartanto** [Automattic/simplenote-electron#1683]
### Multiple-lines indentation using shortcut
Is it possible to have this multiple-lines indentation in the desktop app version? (Still new to Markdown, which I found a fun way to write notes IMO haha)

### Why
I think this feature will greatly improve the speed of writing notes (Markdown) since it reads indentation for numbering after code blocks (?)

### How
I don't have any experience in developing Electron apps, but as a reference, I think this feature will be similar to add indentation in text editor (Sublime, NP++) / IDE (Atom) (?)

Thank you in advance :)

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

![Nov-18-2019 13-06-20](https://user-images.githubusercontent.com/6817400/69077745-47dc7a80-0a04-11ea-9c3f-eca540d450ed.gif)

**Comment by codebykat** [comment]
Oh neat, this works now in Monaco.
