### ISSUE TITLE
Create a Keyboard shortcut to view & access Menu items

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1685]
### What
**To access menu we need a keyboard shortcut.**

### Why
**For Focus mode we have (Ctrl + Shift + F) keyboard shortcut (which is opposite of Menu icon). To view and access **tag** & **trash** every time we have to go Menu. To access Menu for **tag** & **trash** effectively from keyboard we need a keyboard shortcut like the Focus mode.**

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
