### ISSUE TITLE
Fix simplenote share icon

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1686]
### Expected
**![](https://i.imgur.com/OfKWj3C.jpg)This is the share icon across the web**

### Observed
**Currently simplenote-electron uses this logo ![](https://i.imgur.com/McquTgw.jpg) to indicate share   option which is not intuitive & confusing, because this logo is used to represent upload option across the web, so it's need to be fixed**

**Comment by belcherj** [comment]
This is not a bug and is the expected icon.
