### ISSUE TITLE
Create a keyboard shortcut to share note when we edit or read a particular note

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1687]
### What
***We need a Keyboard shortcut to share note when we read or edit a note*** 

### Why
***Currently we have all important keyboard shortcut like Focus mode, Create new note, Markdown preview etc. To share a note we have to press the share icon. Only we need to implement a keyboard shortcut to share a note. Its missing this feature.***

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
