### ISSUE TITLE
wrong url for changelog

### ISSUE THREAD

**Issue by clach04** [Automattic/simplenote-electron#1695]
Check for update says new release available and offers to show the changelog. THis opens https://github.com/Automattic/simplenote-electron/blob/master/CHANGELOG.md which 404s

### Expected

expect to see changelog :)

I believe correct URL would be https://github.com/Automattic/simplenote-electron/blob/develop/RELEASE-NOTES.txt (or rename in githib so code does not need to change)

Seen in simplenote 1.9.1

### Observed
***(Required)*** Add a concise description of what you observed.

### Reproduced
> 1. check for updates
> 2. Click on show changelog
> 3. See error 404 in web browser

**Comment by clach04** [comment]
Now I've upgraded to 1.10.0 there are no updates available as of today so not sure if this is an issue in current release or not.

**Comment by Jaz-onoff** [comment]
Same here. I believe it's older than this version as I saw this broken link on the last update I made for Simplenote on Windows.

**Comment by dmsnell** [comment]
This should be fixed in 1.10.0 [#1675] which is currently in beta. Please re-open if after the release of 1.10.0 if this is still broken for you. Thanks for reporting!
