### ISSUE TITLE
Option to start Simplenote with active filter for tag

### ISSUE THREAD

**Issue by frkunze** [Automattic/simplenote-electron#1697]
### What
It would be nice if it was possible to start Simplenote with a command line option or preferences setting that will activate the _filter for a tag_ right on startup without user interaction required.

For example, if the application would be started like this `simplenote --tag work`, only notes with the tag "work" would be shown.

Alternatively, this could be a local configuration setting.

### Why
I use Simplenote for both private and business related stuff. When I start it on my private machine, I would only like private notes to show up; when I start it on my work machine, I would like to see only work notes initially. Currently I do it with the mouse after startup.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by mazany** [comment]
Has this been implemented? It would be really useful in my workflow ...
