### ISSUE TITLE
Korean: adding lists issue

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-electron#1698]
The issue is a bit inconsistent on my end, but it's only an issue using the Korean keyboard layout.

1. Try to start the note with a list starting with "-" it might let you add a second item.
2. If it works, add a new line paragraph
3. Try to add a list again.

### Expected
To be able to add a list.

### Observed
After adding the first list item using "-", trying to add the second one might simply remove after trying to move to a new line(hitting enter)

Make|Model|OS Version|App Version
-|-|-|-
Asus|Rog|Win10|1.10.0

**Comment by sarahfg** [comment]
The user added a GIF to show more details 
![](https://cld.wthms.co/xKSAId+)

(Image link: https://cld.wthms.co/xKSAId )

**Comment by belcherj** [comment]
Can you or have the user test with the latest on app.simplenote.com? I think this may be resolved by the Emoji bug fix. https://github.com/Automattic/simplenote-electron/pull/1714

**Comment by Robertght** [comment]
Thank you @belcherj - asking in #2472978-zen

**Comment by Robertght** [comment]
@belcherj The user replied and it doesn't seem to work for them yet :( I won't be able to reach my Windows computer until later today to test this.

**Comment by idpokute** [comment]
If you need a tester, please let me know. I have a korean Keyboard.

**Comment by rezzap** [comment]
We've received a new user report of this in 2816369-zen

They've made some screenshots and provided the following details:

pic. 1. you can see the cursor is *on* the the last letter '트'. When I push enter in that situation, the whole list item "심플노트" will be deleted.
<img width="158" alt="스크린샷 2020-03-26 13 15 18" src="https://user-images.githubusercontent.com/10325627/77744241-3c800800-7011-11ea-98b1-6032e5cf6ae5.png">

pic. 2. now you can see the curser is *after* the last letter '트'. I push return key, and an unordered list will be created. no problem.
<img width="157" alt="스크린샷 2020-03-26 13 15 27" src="https://user-images.githubusercontent.com/10325627/77744268-4a358d80-7011-11ea-84ea-2c3fa0a5d12b.png">

pic. 3. my windows app. look at the top left. You can see a letter '그'. The words are written on the top left side. The letters are inputed one by one, in that manner.
<img width="198" alt="스크린샷 2020-03-26 13 18 37" src="https://user-images.githubusercontent.com/10325627/77744342-66d1c580-7011-11ea-85e8-e09141a9f2ed.png">

For the web browser (pic 1 &2) they are using Firefox (ver. 74.0) 64 bit. pic 1 and 2 are written on simplenote webapp, within my firefox browser.

**Comment by belcherj** [comment]
If there is anyone who can test this at app.simplenote.com it would be very helpful.

**Comment by belcherj** [comment]
We have internally tested this and are considering it resolved. Please comment if you think it needs to be revisited.
