### ISSUE TITLE
Code markdown in dark theme in ubuntu

### ISSUE THREAD

**Issue by mxsadegh** [Automattic/simplenote-electron#1701]
Is it possible to change font color of code markdown?
its hard to see codes in drk theme
please see this picture
![image](https://user-images.githubusercontent.com/32076703/68494954-7f109600-0264-11ea-9208-6c5a22be263e.png)

**Comment by belcherj** [comment]
We use solarized-dark from highlight.js.  Maybe a different theme would be better: https://highlightjs.org/

**Comment by belcherj** [comment]
After looking at the code it is a bug!
