### ISSUE TITLE
Simplenote Completely down

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1706]
### Expected
***From last two days can't log in simplenote with simplenote-electron, app.simplenote.com web version and simplenote android app. Simplenote backend is completely down. When contacting through simplenote.com/contact-us/ they are not responding.***

**Comment by dmsnell** [comment]
Hi @Donboscow. As noted in the Android issue you opened the backend is not completely down. We _have_ been working through some login issues but the vast majority of cases are fine and logging in again a few seconds later should resolve the issue. We need to work through support though to help with individual issues for the sake of others here and for the sake of not sharing your own private information in public. If you are experiencing consistent login problems we can help through the support channel to see if there isn't something particular about your network connection that is causing trouble.
