### ISSUE TITLE
Full text is not stored, instead at some point last couple of words are being repeated

### ISSUE THREAD

**Issue by aitiolog** [Automattic/simplenote-electron#1709]
### Expected
Text typed in a new note (or edit an existing one) will be automatically stored.

### Observed

Using the Simplenote's web app I notice that the text is not being stored correctly. While I can see the whole text in my browser,  the full text is not stored. Instead at some point, the last couple of words are being repeated.

### Reproduced
I haven't noticed this error up to two days ago. I have been using the app a lot recently, therefore the number of notes have increased in number and size. The only solution (I found) is to clear the site's cache storage (refresh or chromium restart do not work). After some time, a similar error happens again.

Chromium, version 78.0.3904.70 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (32-bit)

Inspector mode reports this error: serviceworker.js:1 Uncaught (in promise) DOMException: Quota exceeded.

[app.simplenote.com-1573501306995.log](https://github.com/Automattic/simplenote-electron/files/3832997/app.simplenote.com-1573501306995.log)

**Comment by dmsnell** [comment]
Hi @aitiolog - that sounds quite frustrating. We've already been tracking behaviors like this in #1690 so I'm going to close this on. I'm hoping that this will be fixed up soon.

By any chance did you have multiple tabs or sessions of Simplenote open at the same time in the same browser? For example, did you have two tabs in Firefox, or two in Chrome, or two in Safari? We've been chasing an issue that relates to having multiple copies open in the same program.

**Comment by aitiolog** [comment]
No, I am getting this error even when only one session/tab/browser was open at that time. No browser in any of the other computers was logged in either. It is possible, though, the iPad App might be running in the background (but was not actively used while those errors happened).

**Comment by dmsnell** [comment]
thanks @aitiolog for humoring me with this diagnostic help. we're on task trying to clear this up. in the meantime if you are affected by this and having trouble with your notes please reach out to our support and we can help fix any specific notes that might be problematic.
