### ISSUE TITLE
When pressing menu button its not working & this error message appears

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-electron#1712]
![rsz_screenshot_from_2019-11-12_04-34-22](https://user-images.githubusercontent.com/44976018/68626720-2d873600-0506-11ea-8d07-f9f97a72191a.jpg)

**Comment by dmsnell** [comment]
@Donboscow can you verify if `localStorage` is disabled? The particular crash there should be solved by a patch we're woking on, but the app currently depends on `localStorage` so it won't work even if we stop crashing there.

**Comment by Donboscow** [comment]
No, its enabled. Also can't log in with using simplenote-electron(version 1.10.0). When going to app.simplenote.com and pressing menu button, then this message shows. Also it's causes some abnormal behavior/bug. @dmsnell

**Comment by dmsnell** [comment]
@Donboscow can you confirm that your browser allows for the following on app.simplenote.com?
 - loading and storing of cookies
 - loading and storing of `localStorage` items
 - connecting WebSockets
 - use of `indexedDB`

for `localStorage` can you type this into the developer console when on app.simplenote.com and share the screenshot of the output here?

```js
localStorage.getItem('test');
```

for `indexedDB` can you open app.simplenote.com in a normal tab and run the following code in the developer console, then load it in a private tab and run the same? as above, please share the screenshot of the output. (not that the lower-case `i` and the upper-case `B` in `indexedDB` is important).

```js
indexedDB
```

I'm pretty sure that something is preventing the use of `localStorage` based on the error you pasted as that is the only source in the app that I could find that could cause that error.

**Comment by Donboscow** [comment]
![rsz_1screenshot_from_2019-11-12_05-23-40](https://user-images.githubusercontent.com/44976018/68629274-6971c980-050d-11ea-87c8-07b89220df3b.jpg)

![rsz_screenshot_from_2019-11-12_05-25-44](https://user-images.githubusercontent.com/44976018/68629281-6d055080-050d-11ea-8e95-e3ab96f7934a.jpg)

**Comment by Donboscow** [comment]
![rsz_screenshot_from_2019-11-17_21-36-42](https://user-images.githubusercontent.com/44976018/69009747-a9f49b80-0982-11ea-8592-d94ac261b3d7.jpg)

When trying to log in this messages shows.

**Comment by codebykat** [comment]
I believe that we worked over email to fix this issue, please feel free to re-open if that's not the case.
