### ISSUE TITLE
Windows positioning when closing makes app sit behind taskbar after re-opening

### ISSUE THREAD

**Issue by mzorz** [Automattic/simplenote-electron#1715]
### Expected
With the Windows taskbar moved to the top of the screen, when closing the app and re-opening, the app's menu should show itself completely so it's easy to use.

### Observed
With the Windows taskbar moved to the top of the screen, when closing the app and re-opening, the app's menu sits behind the task bar which is a bit annoying.

### Reproduced
From user:

> Under normal conditions, as I just tested, simplenote does indeed open wherever I close it. But my habit is to move simple note to the upper left of my screen and this happens if I move the left border past the left edge of the screen. (use it and then close it in that position). The default position it opens to if the left border (or right border) was off the edge of the screen appears to be a position that is aligned with the top of the desktop space ignoring the start bar which causes it to be "under" the start bar.

Workaround found by @rfaile313:

> I was able to duplicate the exact same issue on my Windows machine.

> We recommend from here:

> 1) Bringing up the taskbar settings and moving the location if it goes behind. Here's a screenshot: http://prntscr.com/pvz329

> 2) Actively trying to keep simplenote on the screen

> 3) Consider moving your taskbar to the left or bottom.

zen-2472483

**Comment by sandymcfadden** [comment]
Here is a screen recording of this happening

![Screen Capture on 2021-01-14 at 11-20-39](https://user-images.githubusercontent.com/1326294/104610627-ac23ba00-565a-11eb-9615-a659bd6579d3.gif)

**Comment by sandymcfadden** [comment]
From [this issue ](https://github.com/Automattic/simplenote-electron/issues/1976)the same happens with a left taskbar and close Simplenote when it is snapped to the right side.

**Comment by eduardozulian** [comment]
From 4074838-zen:

> One observation: when I pin simplenote to my Windows taskbar, it only stays there until my laptop is on. When I power on my laptop the next day it's no longer there in the taskbar! Rest all apps are there, only simplenote is missing and I have to pin it to the taskbar all over again.

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
