### ISSUE TITLE
Archive feature

### ISSUE THREAD

**Issue by cranders** [Automattic/simplenote-electron#1740]
It would be nice to have a separate archive button, aside from the delete button, which would hide the notes from the left pane or list yet still allow you to locate them using the search. The trash can works much like a recycle bin and I use this feature if I decide I don't need the note any longer. Having the ability to archive notes would really fit my workflow. I hope an archive feature will be added to the project.

I added this comment to another post two days ago but hen realized that the post was closed.

Please consider how this can be implemented so that the notes don't appear unless they match a search query. Perhaps the icon for the button could be a folder or a folder with a down arrow or something else that is intutive. 

Thanks.

**Comment by belcherj** [comment]
Thank you for the feature request. We will add it to our feature request list.

**Comment by 360fun** [comment]
is this going to be added?
