### ISSUE TITLE
Feature to collapse sections in Notes

### ISSUE THREAD

**Issue by oliboss** [Automattic/simplenote-electron#1742]
When writing longer texts the lack of a hierarchical structure leads to a lot of scrolling and makes editing the text really difficult. 

It would be great if a section of the text could be collapsed and expanded.

### What
It should be possible to collapse text on the level of headings so that only the title is visible.

### Why
Simplenote is great for writing blogs and shorter articles. For longer notes (like book chapters or books) navigation in the document is difficult and involves a lot of scrolling.

### How
Ideally a minus sign would be shown in front of each header. If the minus sign is clicked the section is collapsed, i.e. only the header and 3 dots are visible. All content till the next header of the same hierarchy level is hidden. 
The minus sign changes to a plus that makes it possible to show the hidden content. 
Storing the status of collapsed sections between sessions would be a nice to have.

**Comment by dmsnell** [comment]
Thanks for the suggestion @oliboss - I know this is a beloved feature among editors like Atom, Sublime, `vim`, etc… I don't know if we'd ever add it to Simplenote but I will put this on our list of feature-requests.
