### ISSUE TITLE
New version of note has disappeared on all devices

### ISSUE THREAD

**Issue by Pand9** [Automattic/simplenote-electron#1744]
I have had a note that has existed for a long time. I have edited it just recently, to include much more data. Unfortunately, when entering from another device (it was google chrome), old version has overwritten the new version. I've seen the new (long) version for a split second, and then old (short) version appeared.

This happened again on any device I've logged in, including original device that this note was edited on.

The tool has served me greatly, it has amazing architecture. Even so, I hope you understand that it's not acceptable for notes to disappear. There is no way to back them up, AFAIK. Unless there is a way to restore previous version.

**Comment by dmsnell** [comment]
@Pand9 this sounds frustrating. Can you reach out to our support at https://simplenote.com/contact-us/ where we can help you with the specifics on your account?

> The tool has served me greatly, it has amazing architecture.

I'm glad to hear it!

> I hope you understand that it's not acceptable for notes to disappear.

Definitely - we don't always get it perfect, but this is on of our most central and important values.

> There is no way to back them up, AFAIK. Unless there is a way to restore previous version.

There are a couple options for you.

Each note contains a "history" of "revisions" for each change. While the history isn't unlimited, you can revert back to a previous version of the note. This history can come in handy at times when conflicts come in, like when someone takes Simplenote offline on a laptop for a weekend but still updates the same notes on a connected phone.

![RevisionSlider mov](https://user-images.githubusercontent.com/5431237/69587205-4aecf180-1028-11ea-9f76-acfa1c7a6404.gif)

When we restore an earlier revision it doesn't just go back in time, but rather it replaces the contents of the note with the earlier contents and that itself becomes a new revision. Maybe this is harder said than seen.

Unfortunately when making that screenshot I came across a recent bug where the revisions aren't restoring properly. We'll get right on that! (You should be able to use the revision slider in the mobile applications in the meantime).

As a second option the app has an export utility where you can create a zip file containing a plaintext copy of all of your notes and then back up that file.

<img width="507" alt="Screen Shot 2019-11-26 at 8 49 30 AM" src="https://user-images.githubusercontent.com/5431237/69587714-b5eaf800-1029-11ea-9322-0ac3b135e66c.png">

**Comment by Pand9** [comment]
Thank you. I've never noticed "history" button! This is great. I found out that newer entries on the timeline have older timestamps, indicating that there has been old version restored. Could it happen by some elaborate mis-click - hard to say.
