### ISSUE TITLE
One character is missing out in title. (windows only)

### ISSUE THREAD

**Issue by hahatis** [Automattic/simplenote-electron#1746]
![image](https://user-images.githubusercontent.com/46660550/69611311-d8ecca80-1070-11ea-8fc7-79b69bf3d479.png)

version is 1.11.0

It occurs only in my pc (Windows 10 64bit)
My iphone works well.

Thanks.

**Comment by campbellmc** [comment]
It's only lower case "s" that is missing, when it's the first letter of the title.  I haven't noticed any other characters that go AWOL in the note list.
agree - I only see it on Windows 10 64 bit V 1.11.0
Android 1.8.2 is ok.

**Comment by qualitymanifest** [comment]
I can replicate this on Linux / Electron 1.11.0

Only with starting `s`'s though, starting `m`'s do appear. `s`'s elsewhere in the title will appear.
