### ISSUE TITLE
Markdown live preview

### ISSUE THREAD

**Issue by JackCaster** [Automattic/simplenote-electron#1747]
### What
A live preview of markdown formatting right from the editing panel. Ideally, users should be able to toggle this functionality on and off in the settings. 

### Why
Checklists (`- [ ]`) are actually already rendered in real time. I think implementing a real time preview of the whole markdown document would make the typing experience more pleasant and less distracting. Moreover, the automatic rendering of (only) checklists in a markdown document makes the design a bit inconsistent.

### How
[Typora](https://www.typora.io/) has this functionality. This [video](https://www.typora.io/img/beta.mp4) shows how it works

All the best,
JC

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests! This has been requested in the past. This is not on the roadmap but may be in the future.
