### ISSUE TITLE
Revision History is broken

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1750]
When you restore a revision and then click into the note editing section it undoes the restore

Seen in:
 - #2537431-zen

### Expected
When you restore a revision it should stay on that revision

### Observed
It reverts to the most recent revision.

**Comment by michaelwexler** [comment]
I just saw this also, specifically web app.  Works fine in iOS.

**Comment by belcherj** [comment]
This is fixed in the web app, will be fixed in Electronn as soon as we get the next version out.

**Comment by michaelwexler** [comment]
Thanks for the rapid fix!
