### ISSUE TITLE
Chrome Incognito mode updates broken after refresh

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#1752]
Chrome Incognito mode updates broken after refresh

### Expected
Updates are not broken

### Observed
Updates are broken

### Reproduced
1. Goto app in incognito mode in Chrome
2. Make edits and watch the sidebar update
3. Refresh page
4. Observe that syncing and updating is broken

**Comment by dmsnell** [comment]
Since incognito mode doesn't give us the `indexedDB` support we want, isn't this unsupported?

Will need to test after 1.12 goes out where the platform support module should prevent booting in these scenarios.

Granted, we _should_ support incognito mode, but right now that's way too big of an update to fix in a single bug report methinks.

**Comment by belcherj** [comment]
Chrome incognito supports indexedDB. It is Firefox private mode that does not have support.

**Comment by Robertght** [comment]
Got a bit of feedback from the user:

>If the scenario is unsupported (although I am positive I had been using Simplenote in incognito mode before) I would vote to at least display a placard/banner with the readonly mode warning (I hope you can determine the app state on page load).

**Comment by Robertght** [comment]
@belcherj the user was referring to Firefox actually as Chrome worked for them.

**Comment by belcherj** [comment]
Ahh, yes, Firefox is unsupported.  Chrome, however, is broken in incognito mode which has all the features to make it work.

**Comment by michaelwexler** [comment]
So, should folks wanting this (Simplenote working in Incognito Chrome primary, FF secondary (or never)) post a new request as a feature request so it can be tracked?

**Comment by belcherj** [comment]
FF Private window would require substantial effort since IndexedDB is unsupported.  I would not expect that anytime soon. Chrome Incognito is a bug and on the list of things to look at. Feature requests will be added to our internal feature request list and closed.

**Comment by belcherj** [comment]
I have just tested Chrome Incognito and it appears to be working as expected.  Closing this issue.  FF Private Window is unsupported at this time.
