### ISSUE TITLE
Responsive: Resizing with sidebar hidden should start in note focus

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#1760]
A user in #2538788-zen was confused by this, when a note is displayed full-screen (with the sidebar hidden) and you then resize the window to a narrow width, it changes the view to the note list.

In this situation it would be better to change directly to the note view (i.e., the note list is still hidden).

**Comment by qualitymanifest** [comment]
Could I take this one? Pretty sure I know what needs to be changed

**Comment by qualitymanifest** [comment]
Decided to give it a try, it was what I thought it was so I figured I would send it.

If in the future it would be better for me to ignore issues without a "help wanted" label, just let me know
