### ISSUE TITLE
I want to import markdown files

### ISSUE THREAD

**Issue by eallion** [Automattic/simplenote-electron#1764]
I have used many note apps (evernote,wiz,youdao,notion...), but those apps are not easy to use.  The same issure: #1189 

### What
I want to import markdown files (.md)

### Why
I have 4000+ markdown files. I can't do it manually.

### How
Just import markdown files as import json files.

**Comment by eallion** [comment]
thank you very much

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests! This is something that should be doable if we treat it as a text file.

**Comment by eallion** [comment]
Thanks for your reply, and im waiting for it.
