### ISSUE TITLE
Trying to publish an empty note hangs indefinitely

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#1769]
When clicking to publish an empty note, it hangs forever on "Publishing note..."

<img width="673" alt="Screen Shot 2019-12-09 at 3 48 33 PM" src="https://user-images.githubusercontent.com/52152/70482874-a218aa80-1a9b-11ea-88f2-bbf328e194b4.png">

### Expected
Note should successfully publish. OR if we can't publish a blank note (reasonable!) let's show a message to that effect.

### Observed
When you toggle it just says "Publishing note..." but never succeeds.

**Comment by belcherj** [comment]
My notes publish but it reverts to a previous version that wasn't empty.

**Comment by codebykat** [comment]
I can't reproduce this now.
