### ISSUE TITLE
Search: No results when doing a tag search with non-English characters

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1770]
### Expected

I expect to be able to search with the `tag:` syntax for any of my tags.

### Observed

Some of my tags include non-English characters, and those tag searches return no search results. Here are two tags I have that I observed this issue with:

* `سلام`
* `español`

### Reproduced

1. Create a tag with a non-English character, such as `español`, and add it to at least one note.
2. In the tag list, select the tag `español`.
3. Notice that the note list shows the notes with that tag.
4. Go back to the All Notes view.
5. Search for just the tag name `español`.
6. Notice that under "Search by Tag" you see `tag:español`.
7. Select `tag:español`.
8. Notice that the note list says "No Notes" instead of showing the note(s) with that tag.

![simplenote-electron-nonENtags](https://user-images.githubusercontent.com/8658164/70535280-aead0980-1b54-11ea-9824-6af72399581a.gif)

Make|Model|OS Version|App Version
-|-|-|-
Windows|VirtualBox VM|Win10|1.13.0-beta1
Mac|Macbook Pro (2017)|macOS 10.15.1|1.13.0-beta1

cc @codebykat

**Comment by rachelmcr** [comment]
It might be obvious, but this also affects any tags that include emoji.

**Comment by codebykat** [comment]
You can include emoji in tags??? Why did I never think to try this?!

**Comment by codebykat** [comment]
Just to double-check, did it ever work to search **in the text box** for these tags, or only when clicking them from the sidebar? I think this was a pre-existing bug with the text box search. (Of course I'll take a look at it, but if it wasn't introduced by the tag suggestions PR it shouldn't be a blocker for release.)

**Comment by rachelmcr** [comment]
> Just to double-check, did it ever work to search in the text box for these tags, or only when clicking them from the sidebar?

I just tested in prod version 1.12 and confirmed that the same text box search (e.g. `tag:español`) also returns no results there, while other tag searches do work, so this isn't new. Agreed, not a blocker for release.
