### ISSUE TITLE
Cannot 'Add to Dictionary' in Electron app

### ISSUE THREAD

**Issue by mahangu** [Automattic/simplenote-electron#1775]
### Expected
You should be able to add any word to the dictionary in the Electron app, and stop it from being underlined as an error. This is how it works in the web app.

### Observed
You can only add a word to the dictionary when the dictionary can find an alternate suggested spelling for it.

**There is no suggested alternate spelling, and Add to Dictionary doesn't appear.**
<img width="664" alt="Screen Shot 2019-12-12 at 9 49 41 AM" src="https://user-images.githubusercontent.com/10125810/70682705-972a6980-1c97-11ea-8262-dae55155f6f1.png">

**There is a suggested alternate spelling, so Add to Dictionary appears.**
<img width="583" alt="Screen Shot 2019-12-12 at 9 49 53 AM" src="https://user-images.githubusercontent.com/10125810/70682661-75c97d80-1c97-11ea-96a0-37d382456a28.png">

**Even when you add the word to the dictionary, it still appears underlined in red**

<img width="522" alt="Screen Shot 2019-12-12 at 9 59 33 AM" src="https://user-images.githubusercontent.com/10125810/70682828-030cd200-1c98-11ea-9150-491114dfb949.png">

**In the web app, when you add a word to the dictionary, it does not underline it in red anymore:**

<img width="672" alt="Screen Shot 2019-12-12 at 9 59 23 AM" src="https://user-images.githubusercontent.com/10125810/70682850-0f912a80-1c98-11ea-9392-a6ba4b37cbed.png">

### Reproduced
1. Open the Electron app.

2. Type out something like `notarealword` and right click it. `Add to Dictionary` doesn't appear.

3. Type out something like `nott` where the dictionary can suggest an alternate spelling and right click it.

4.`Add to Dictionary` will appear for this word. Click it. 

5. Observe how the word remains underlined in reed.

### Other Info
Tested on macOS 10.14.6 / Simplenote Electron (Mac) 1.8.0

Reported by a user in 2555304-zen who noticed this issue in the Windows app.

**Comment by belcherj** [comment]
https://github.com/electron-userland/electron-spellchecker/pull/101

It looks like a spellchecker issue.

**Comment by belcherj** [comment]
We will be changing how the Spellchecker works in the Electron app. This issue is now invalid.
