### ISSUE TITLE
Editor container

### ISSUE THREAD

**Issue by moniuch** [Automattic/simplenote-electron#1777]
I thought it was a rendering bug within the editor component, but turns out to be a responsive container which on wider screens just gets centered. This in turn produces wide margin where you don't expect it.

![image](https://user-images.githubusercontent.com/681956/70866807-9717bb80-1f6e-11ea-9b43-dca7ddafcfed.png)

One might argue whether it is a bug, but definitely not something natural. Not sure why you decided so, IMO it should be a fluid container with `width: 100%`

**Comment by belcherj** [comment]
There is a setting to make it 100%. Line length: Full

<img width="550" alt="Screen Shot 2019-12-16 at 9 01 54 AM" src="https://user-images.githubusercontent.com/6817400/70912806-bcdea800-1fe2-11ea-83b6-87de9bf3636d.png">
