### ISSUE TITLE
formating issue (spacing) when importing Evernote

### ISSUE THREAD

**Issue by leonard3333** [Automattic/simplenote-electron#1800]
A side by side comparison, Evernote vs Simplenote is shown below. 

![evernote simplenote](https://user-images.githubusercontent.com/56940803/67438860-5cfdfd80-f640-11e9-98b0-e4fc4f345c4e.jpg)

On the left, Evernote. On the right is Simplenote. The issue is LINE SPACING between H E A D I N G S.

Also, the Evernote Shopping Note is generated automatically when Evernote is openned. (Since you can specify an import folder in Evernote.) For Simplenote, I have open Simplenote and slected Import, etc. (However, it is good that Simplenote remembers the location of the Shopping List evenote file). I guess, a dedicted Import folder, would be a good feature request.

Below is the code generated to create the shopping list file as shown above. This is generated from my "program" - LEO RECIPE SYSTEM. (LEO is written almost entirely using Excel formulas, with a small amount of VB code.)

www.leorecipesystem.com

![text](https://user-images.githubusercontent.com/56940803/67439703-c67f0b80-f642-11e9-84ab-0ba95ab5f955.jpg)

**Comment by jleandroperez** [comment]
Transferred over the Electron repository, since the native Mac app doesn't have the Import feature. Thank you!

**Comment by leonard3333** [comment]
Thanks. Actually, this issue has been solved with an update. 

There is one very small new issue. The imported file name (**shopping list**) appears as h**opping list** on the left pane (PC). On my phone (iphone se), it still shows as shopping list.



![shoppinglist](https://user-images.githubusercontent.com/56940803/71601479-b128df00-2ba7-11ea-98e9-42f07bb53e9a.jpg)

**Comment by belcherj** [comment]
The issue with the 's' not showing will be resolved in the next release!

**Comment by jleandroperez** [comment]
Thank you JB!!

**Comment by leonard3333** [comment]
Thanks Jonathan.

Can I make a suggestion in regards to checkbox lists. One of the
frustrations is checking a box and it being interpreted as wanting to edit
the text instead. This is one of the reasons Simplenote is much better than
Evernote IMHO. (Evernote drove me nuts at the supermarket.) However, even
with Simplenote this happens too often, or at least with the ios version I
use on my iphone se. (Perhaps on android or larger screen phones it is less
of an issue.) Perhaps Simplenote could recognize checkbox lines and either
(i) allow text editing only on double-tap (but box-checking on single tap)
OR (ii) recognize any tap in first 1/3rd of a line as intended box checking
rather than text editing.

Leonard

**Comment by belcherj** [comment]
TY Leonard, I'll share your feedback with the team.
