### ISSUE TITLE
first character doesn't show in title if it begins with lowercase 's'

### ISSUE THREAD

**Issue by coldwell** [Automattic/simplenote-electron#1805]
Simplenote v1.12 on Windows

I observed that the title displayed in the list truncates the first letter if it is a lowercase 's'. Uppercase 'S' is ok, as are all the other lowercase letters I tested (which was not exhaustive).

Screenshot:

![image](https://user-images.githubusercontent.com/1333839/71740767-ba71b000-2e22-11ea-9947-d9724d20023c.png)

**Comment by belcherj** [comment]
This will be fixed in the next release.
