### ISSUE TITLE
Lost Note

### ISSUE THREAD

**Issue by mindrunner** [Automattic/simplenote-electron#1815]
Today on my Computer (Linux) was a note missing. I could not find it anymore by searching for it nor was it in the Bin (Never emptied the bin).

I put my phone to flight mode and started simplenote there. Could see the 'missing' note and copied the content to a new note.

When enabling the connection again, the phone synced and the old note disappeared there as well.

What could have happened here?

**Comment by codebykat** [comment]
With apologies for the very late reply. @mindrunner This is very stale and we don't have any similar reports, so unfortunately the best I can say is, it's a mystery. Has it ever happened again? If the note was only missing on the website, it could have been the product of an old bug that sometimes failed to list certain notes. I don't know why it would have also disappeared on the phone; you don't mention if you checked the trash on the phone side.

I'm closing this for the time being as it's not really actionable; please do let us know if you're still having issues. Thanks!

**Comment by mindrunner** [comment]
Hey @codebykat! Never happened again! I am happy with mystery. :)
