### ISSUE TITLE
Can not search with Chinese

### ISSUE THREAD

**Issue by 510846** [Automattic/simplenote-electron#1824]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
***(Required)*** Add a concise description of what you expected.

### Observed
***(Required)*** Add a concise description of what you observed.

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Go to...
> 2. Click on...
> 3. See error...

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, OS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|OS Version|App Version
-|-|-|-
SYSTEM_MAKE|SYSTEM_MODEL|OS_VERSION|APP_VERSION

**Comment by dmsnell** [comment]
Thanks for reporting @510846 - we can't do much with an empty issue report, though we have been working on search improvements and some internal work that we have been doing should make for better results with Chinese and all other searches.
