### ISSUE TITLE
Eliminate `app-state.ts`

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#1836]
Our goal is to move all of the global setters out of `app-state` and into real Redux reducers.

Work on these if you need a break from what you're doing.
Focusing on the thunks first will be more fruitful for eliminating inconsistent app state.

 - [ ] `authChanged`
 - [x] `toggleNavigation` #1907
 - [x] `showAllNotesAndSelectFirst`
 - [x] `showAllNotes`
 - [x] `selectTrash` #1971 
 - [x] `selectTagAndSelectFirstNote` #1920
 - [x] `selectTag` #1920
 - [x] `setEditorMode` https://github.com/Automattic/simplenote-electron/pull/1866
 - [x] `showDialog` #1981 
 - [x] `closeDialog` #1981
 - [x] `editTags` #1899
 - [x] `search` #1881
 - [ ] `newNote`
 - [ ] `loadNotes`
 - [ ] `notesLoaded`
 - [ ] `loadAndSelectNote`
 - [x] `pinNote` #1928
 - [x] `setRevision` #1921
 - [x] `setIsViewingRevisions` #1903
 - [x] `setShouldPrintNote` #1872
 - [x] `setSearchFocus` #1914
 - [x] `markdownNote` #1928
 - [x] `publishNote`#1928
 - [x] `selectNote` #1921
 - [x] `closeNote` #1895
 - [x] `noteUpdatedRemotely` #1851
 - [ ] `onNoteBeforeRemoteUpdate`
 - [ ] `trashNote`
 - [ ] `restoreNote`
 - [ ] `deleteNoteForever`
 - [x] `noteRevisions` #1921
 - [ ] `emptyTrash`
 - [x] `noteRevisionsLoaded` #1921
 - [x] `toggleNoteInfo` #1896
 - [ ] `tagsLoaded`
 - [ ] `loadPreferences`
 - [ ] `preferencesLoaded`
 - [ ] `setPreference`
 - [ ] `toggleShareAnalyticsPreference` #1975
 - [x] `setUnsyncedNoteIds` #1871
 - [x] `setConnectionStatus` #1870

**Comment by codebykat** [comment]
We haven't been keeping this updated and it kind of makes more sense to look at the legacy actions as a todo list, but I updated this with links to the PRs and what's been done so far.
