### ISSUE TITLE
Bug: Leading "s" in note title are not shown in sidebar

### ISSUE THREAD

**Issue by dipnlik** [Automattic/simplenote-electron#1840]
Just updated to 1.12.0 and noticed this.  Searched my notes for "senior" and a note titled "senior engineer checklist" was showing in the sidebar without the first letter.

This is easily reproducible wihout even searching.  With the sidebar open:
- Create a note titled "sample note" and look at the sidebar showing "ample note";
- Replace "s" with "S" and the sidebar will display "Sample note" as expected;
- Now try "sssample note", the sidebar won't show any of the three "s".

<img width="938" alt="Screen Shot 2020-01-16 at 08 44 06" src="https://user-images.githubusercontent.com/223484/72522404-61e7dd00-383c-11ea-849d-8342ade50339.png">

**Comment by codebykat** [comment]
Thanks for the report! This is fixed in #1748.
