### ISSUE TITLE
eliminate copy/cut no word

### ISSUE THREAD

**Issue by Jairjua** [Automattic/simplenote-electron#1843]
### What 
After I copy/cut some word, if I copy (ctrl+c) or cut no word (without select a word/letter), the old one is erased. I can't past the first one. 

### Why
Linux do not works this way. I lost some important informations because I thought simplenote had the same behaviour as Linux.  

### How
Please, make copy/cut no word do not erase the temporary copy/cut memory. 

I use Linux mint 19.2, 8GB RAM, intel i5.

**Comment by dmsnell** [comment]
Thanks for the report @Jairjua - I hadn't noticed this myself until I tried to figure out exactly what was going on. Thankfully it appears like a simpler update to make this work the way you expect it.
