### ISSUE TITLE
Start up slow

### ISSUE THREAD

**Issue by Jairjua** [Automattic/simplenote-electron#1844]
### What
The first time I open simple note takes some seconds. The next times it is faster, but not enough. 

### Why
Apps for simple notes should be very fast. For example, sublime text open very fast. 

### How
Please, make the interface open faster in Linux.
I use Linux mint 19.2, 8GB RAM, intel i5.

**Comment by dmsnell** [comment]
@Jairjua I'm closing this issue because it's not reporting something concretely broken and it's not identifying something we can directly fix. Performance is something we routinely try to address and all want to be better.

The first time Simplenote opens it needs to download the notes from the Simplenote server which is why it's going to load slower. After that it has a copy of the notes and only needs to download the changes/updates.

**Comment by Jairjua** [comment]
Maybe you should make the program open fast, only with the local version, so when the changes are downloaded and detected, a msg appear asking if the user want apply. It's annoying to wait too much for a simple text app.

**Comment by lengockyquang** [comment]
totally agree with @Jairjua , I'm using simplenote with ubuntu 20.04. When i start simple note, it kinda slow to completely open. I think it would be better if dev team can make it load faster with local data and background sync for new notes.

**Comment by codebykat** [comment]
The app does use local storage and background sync. As @dmsnell said, we are always trying to find ways to improve performance. Do either of you have a large number of notes, very long notes, slow network connections, or anything else that might help us narrow down the problem?

**Comment by lengockyquang** [comment]
I have only 2 notes (not to long) at that time. My laptop is kinda old ( dell inspiron 3543 ), but it already use SSD with 8gb ram, so i dont think hardware is the problem. But when i start simplenote, it took me at least 30s to see the application window appear
As you said, maybe the connection between simplenote servers and mine having some issue may cause high latency

**Comment by n-osennij** [comment]
I have pc ryzen 7 1900x, 24 GB RAM, fast ssd, windows 10.

Open ms word and excel 2016 takes ~1.5 seconds, chrome ~1.5 seconds, sublime text v4 less than 1 second, simplenote ~3 seconds. I don't have  many or large notes.

version for m1 macbook (8GB RAM) opens very fast - less than second.
version for android (oneplus ace, 12GB RAM, android 13) takes ~1.5 seconds.


I can record video or do any other measurements. What can I do?

I really like simplenote. But it's too slow on windows when opening. And why it so large? Look at fiinote - less than 10mb, blaze speed.
