### ISSUE TITLE
Debugger console appears when I start the PWA for windows

### ISSUE THREAD

**Issue by Bmartin2013** [Automattic/simplenote-electron#1864]
Hi community! Recently, I downloaded the windows version of simplenote and I noticed that when I start the app, the Debugging console starts too. I thought that it was something from markdown but I disabled the option and the issue still happens. Also, I pinned and unpinned the app from my taskbar but the issue persists. I think that it has something to do with the issue [#291](https://github.com/Automattic/simplenote-electron/issues/291)

![aa](https://user-images.githubusercontent.com/3893598/73106655-ad545800-3eda-11ea-8e05-892015a1bc4d.gif)

### Expected
The app must be opened without the Debugging Console

### Observed
When I close the Debugging Console from the app menu it closes
The console menu shouldn't be in the PWA for windows

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Start the app

Make|Model|OS Version|App Version
-|-|-|-
-|-| Windows 10|Simplenote 1.12.0

**Comment by belcherj** [comment]
Where did you download the app from? I just tested a new download from the Microsoft Store and the dev tools do not open.

**Comment by bummytime** [comment]
Howdy @Bmartin2013 👋 

I tested installs of Simplenote 1.14 on Win10 (from [our site](https://github.com/Automattic/simplenote-electron/releases/download/v1.14.0/Simplenote-win-1.14.0.exe) as well as installing the PWA directly from Chrome when visiting app.simplenote.com) — and was not able to repro this. 

I am going to close this issue, but if you are able to provide more details on how to reproduce we can reopen it. Thank you!

**Comment by Bmartin2013** [comment]
Hi! sorry for the delay! I downloaded the notepad from [your site ](https://github.com/Automattic/simplenote-electron/releases/download/v1.14.0/Simplenote-win-1.14.0.exe) and I'm still having this issue.  Could it have something to do with the dev tools option from the help menu? 

![2020-02-15 11_51_08-Window](https://user-images.githubusercontent.com/3893598/74590058-b2905880-4fe9-11ea-906e-a58bbd3e894a.png)

![2020-02-15 11_53_44-Simplenote](https://user-images.githubusercontent.com/3893598/74590096-1581ef80-4fea-11ea-83a1-d3e240224266.png)

Thanks for taking care of this issue and this is a really nice community!

**Comment by thabotswana** [comment]
Another report: 4372446-zen

>I tried uninstalling (also removed all files from my machine to be sure) and reinstalling the application both from the microsoft store and your website. Also, an update came (2.21.0) and installed it, but the issue still persists.

![image](https://user-images.githubusercontent.com/35628116/138463557-fc4631ea-000c-4f88-b558-42f098bbfcbe.png)

![image (1)](https://user-images.githubusercontent.com/35628116/138463747-d3217995-2f7f-4d77-842e-b712740cfbd5.png)

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
