### ISSUE TITLE
No "preview" button to toggle markdown format

### ISSUE THREAD

**Issue by surfer0627** [Automattic/simplenote-electron#1875]
Hi,
It seems that this case occurs in the site just a while (Commits on Jan 30, 2020 ). When user enable markdown formatting on this note. There is no **preview** button to toggle markdown format.

### Steps to reproduce:
1. Open and login to simplenote.com.
2. Select a note (markdown enable)
3. Try to find "preview" button.

#### Actual behavior:
"Preview" button disappear.

#### Expected behavior:
Find "preview" button to toggle (display markdown format). E.G. headings/ links/ ...

#### Windows version:
6.1.7601 service pack 1

#### Name and version of other software in use when reproducing the issue:

screen reader: [NVDA](https://www.nvaccess.org/) 2019.2.1

### Other information:

Is this a regression? Yesterday, Simplenote site works as expected.

cc: @dmsnell

**Comment by dmsnell** [comment]
Hey @surfer0627 thanks for the report! Indeed we accidentally missed this when we tested #1851 and because of your report were able to fix it 🤞 in #1876. If you reload app.simplenote.com and it's still not there make sure you clear your browser cache and try again.

**Comment by surfer0627** [comment]
Great! It's fixed. Thank you for all of your help.
