### ISSUE TITLE
Whenever I run "npm install" in Windows 10 command prompt, I get this output

### ISSUE THREAD

**Issue by danielh0t** [Automattic/simplenote-electron#1877]
> 
> \> @paulcbetts/spellchecker@4.0.6 install C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker
> 
> \> node-gyp rebuild
> 
> 
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker>if not defined npm_config_node_gyp (node "C:\Users\{user}\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\{user}\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> Warning: Missing input files:
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\..\vendor\hunspell\src\build\build.h
> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
>   md5.cc
>   string_piece.cc
>   bdict_reader.cc
>   bdict.cc
>   affentry.cxx
>   affixmgr.cxx
>   csutil.cxx
>   dictmgr.cxx
>   filemgr.cxx
>   hashmgr.cxx
>   hunspell.cxx
>   hunzip.cxx
>   phonet.cxx
>   replist.cxx
>   suggestmgr.cxx
>   textparser.cxx
>   win_delay_load_hook.cc
>   hunspell.vcxproj -> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellc
>   hecker\build\Release\\hunspell.lib
>   main.cc
>   spellchecker_hunspell.cc
>   spellchecker_win.cc
>   transcoder_win.cc
>   win_delay_load_hook.cc
> 
> 
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\..\vendor\hunspell\src\build\build.h
> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
>   md5.cc
>   string_piece.cc
>   bdict_reader.cc
>   bdict.cc
>   affentry.cxx
>   affixmgr.cxx
>   csutil.cxx
>   dictmgr.cxx
>   filemgr.cxx
>   hashmgr.cxx
>   hunspell.cxx
>   hunzip.cxx
>   phonet.cxx
>   replist.cxx
>   suggestmgr.cxx
>   textparser.cxx
>   win_delay_load_hook.cc
>   hunspell.vcxproj -> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellc
>   hecker\build\Release\\hunspell.lib
>   main.cc
>   spellchecker_hunspell.cc
>   spellchecker_win.cc
>   transcoder_win.cc
>   win_delay_load_hook.cc
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(187
> ,26): error C2061: syntax error: identifier 'Handle' [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron
> \node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(43,
> 1): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Use
> rs\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vc
> xproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(43,
> 1): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\{user}
> ie\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(64,
> 1): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Use
> rs\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vc
> xproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(64,
> 1): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\{user}
> ie\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(75,
> 5): error C2065: 'Handle': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\nod
> e_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(75,
> 12): error C2275: 'v8::String': illegal use of this type as an expression [C:\Users\{user}\Repositories\GitHub\Automatti
> c\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(2702): message : see declaration of 'v8::String'
> [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellche
> cker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(75,
> 20): error C2065: 'string': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\no
> de_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(75,
> 29): error C2065: 'Handle': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\no
> de_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(75,
> 36): error C2275: 'v8::String': illegal use of this type as an expression [C:\Users\{user}\Repositories\GitHub\Automatti
> c\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(2702): message : see declaration of 'v8::String'
> [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellche
> cker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(75,
> 45): error C2039: 'Cast': is not a member of '`global namespace'' [C:\Users\{user}\Repositories\GitHub\Automattic\simple
> note-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(75,
> 1): error C3861: 'Cast': identifier not found [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_m
> odules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(76,
> 10): error C2065: 'string': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\no
> de_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(83,
> 9): error C2065: 'string': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\nod
> e_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(87,
> 32): error C2065: 'string': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\no
> de_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(88,
> 5): error C2065: 'string': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\nod
> e_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(99,
> 1): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote
> -electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(3402): message : see declaration of 'v8::Object::
> Set' [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spe
> llchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(100
> ,1): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\{user}\Repositories\GitHub\Automattic\simplenot
> e-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(3402): message : see declaration of 'v8::Object::
> Set' [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spe
> llchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(101
> ,1): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\{user}\Repositories\GitHub\Automattic\simplenot
> e-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(3411): message : see declaration of 'v8::Object::
> Set' [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spe
> llchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(112
> ,1): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Us
> ers\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.v
> cxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(112
> ,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\da
> nie\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj
> ]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(125
> ,1): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Us
> ers\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.v
> cxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(125
> ,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\da
> nie\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj
> ]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(139
> ,1): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Us
> ers\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.v
> cxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(139
> ,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\da
> nie\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj
> ]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(148
> ,1): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\{user}\Repositories\GitHub\Automattic\simplenot
> e-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(3411): message : see declaration of 'v8::Object::
> Set' [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spe
> llchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(162
> ,1): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Us
> ers\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.v
> cxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(162
> ,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\da
> nie\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj
> ]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(171
> ,1): warning C4996: 'v8::Object::Set': was declared deprecated [C:\Users\{user}\Repositories\GitHub\Automattic\simplenot
> e-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(3411): message : see declaration of 'v8::Object::
> Set' [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spe
> llchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(201
> ,5): error C2065: 'exports': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\n
> ode_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(201
> ,1): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Users\{user}\Repositories\
> GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(5995,46): message : see declaration of 'v8::Funct
> ionTemplate::GetFunction' (compiling source file ..\src\main.cc) [C:\Users\{user}\Repositories\GitHub\Automattic\simplen
> ote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,11): error C2065: 'Handle': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\n
> ode_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,18): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Users\{user}\Repositories\GitHub\Automatt
> ic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(3400): message : see declaration of 'v8::Object'
> [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellche
> cker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,26): error C2065: 'exports': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\
> node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,35): error C2065: 'Handle': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\n
> ode_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,42): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Users\{user}\Repositories\GitHub\Automatt
> ic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\AppData\Local\node-gyp\Cache\12.14.1\include\node\v8.h(3400): message : see declaration of 'v8::Object'
> [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellche
> cker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,50): error C2065: 'module': undeclared identifier [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\n
> ode_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,56): error C2182: 'Init': illegal use of type 'void' [C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electro
> n\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(205
> ,58): error C2448: '`anonymous-namespace'::Init': function-style initializer appears to be a function definition [C:\Us
> ers\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.v
> cxproj]
> C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\src\main.cc(211
> ,1): warning C4312: 'type cast': conversion from 'int' to 'node::addon_register_func' of greater size [C:\Users\{user}\R
> epositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker\build\spellchecker.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\{user}\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> gyp ERR! System Windows_NT 10.0.18362
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\{user}\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\{user}\Repositories\GitHub\Automattic\simplenote-electron\node_modules\@paulcbetts\spellchecker
> gyp ERR! node -v v12.14.1
> gyp ERR! node-gyp -v v5.0.7
> gyp ERR! not ok
> npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN base64-arraybuffer-es6@0.5.0 requires a peer of core-js-bundle@^3.1.3 but none is installed. You must install peer dependencies yourself.
> npm WARN typeson@5.13.0 requires a peer of core-js-bundle@^3.1.3 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\jest-haste-map\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @paulcbetts/spellchecker@4.0.6 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @paulcbetts/spellchecker@4.0.6 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\{user}\AppData\Roaming\npm-cache\_logs\2020-02-02T16_00_19_063Z-debug.log
>

**Comment by qualitymanifest** [comment]
I think this might be related to https://github.com/Automattic/simplenote-electron/issues/1733

**Comment by danielh0t** [comment]
@qualitymanifest That's ubuntu, and it seems like it brought up in 2019. I don't know what the resolution is. Guess I'll go hack something else in the meanwhile. Thanks.

**Comment by qualitymanifest** [comment]
@danielh0t I'm thinking it's the same issue, with electron-spellchecker not building on node v12. Based on your error message I think you're using node 12.14.1.

Switching node versions is easy on mac/linux using `nvm use <version>`, not sure about with windows but it looks like this is probably a good option https://github.com/coreybutler/nvm-windows

Whenever I install this repo I switch to node 10.16.0 but I think anything before v12 would probably work

**Comment by dmsnell** [comment]
We've been going through a lot of work to update Automattic/wp-desktop so that it uses the from-source version of the spell-checker. Previously it was using a prebuilt spell-checker and had similar issues. We'll try and swing around to bring that knowledge here and resolve this with it. As a plus the spell-checking started working better and started working in Windows where it previously hadn't.
