### ISSUE TITLE
Content disappears when previewing markdown-enabled note

### ISSUE THREAD

**Issue by guarani** [Automattic/simplenote-electron#1878]
User reported content disappearing when previewing markdown-enabled note. 

### Expected

On the web app with markdown enabled, previewing a note should display the note contents faithfully with markdown applied.

### Observed
When the preview button is tapped, the latest changes to a note are not displayed in the preview.

### Reproduced

1. Open https://app.simplenote.com on either macOS Safari or macOS Google Chrome.
2. Type a note, eg. "a b c"
3. Tap the preview button
4. Observe part or all of the note missing from the preview
5. Switch back to the editor (by tapping again the preview button)
6. Observe that the original note contents are still not visible
7. Switching to a different note and then back to the original may restore the message content

#### Screen Recording
![demo-preview-bug-2683688](https://user-images.githubusercontent.com/1898325/73688385-abdd1980-46aa-11ea-8f3e-69296ae62312.gif)

### User Reported Errors in Browser Console

I was unable to reproduce these console errors, which the user reported seeing.

1. `Uncaught (in promise) DOM Exception`
2. `Promise.then (async) (anonymous) @ serviceworker.js:17`
3. `Promise.then (async) (anonymous) @ serviceworker.js:18`
4. `Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported at serviceworker.js:41`

### System
Make|Model|OS Version|App Version
-|-|-|-
| Apple | MacBook Pro | macOS 10.15.2 | Google Chrome Version 79.0.3945.130
| Apple | MacBook Pro | macOS 10.15.2 | Safari Version 13.0.4 (15608.4.9.1.3)

**Comment by dmsnell** [comment]
It looks like this is a different exposure of the same bug reported in #1879. Although this one was reported first I identified the bug in #1879 so I'm going to fold this in to that one as a duplicate. Thanks for the report. It should be resolved very soon.

**Comment by guarani** [comment]
I hadn't spotted that issue, and glad it's got a fix on the way 👍.
