### ISSUE TITLE
Update note: user needs to switch to another one, and go back to get the updated result

### ISSUE THREAD

**Issue by surfer0627** [Automattic/simplenote-electron#1879]
### Steps to reproduce:
1. Open and login to simplenote.com.
2. Select note (e.g. name: xxx)
3. Edit note. (add / delete text)
4. Press "preview" button.
#### Actual behavior:
Unable to update note.
#### Expected behavior:
Note updated successfully.

4. Select note (e.g. name: yyy)
5. Select note (e.g. name: xxx again)
(Now, note xxx updated successfully.

#### Windows version:
6.1.7601 service pack 1

#### Name and version of other software in use when reproducing the issue:

screen reader: [NVDA](https://www.nvaccess.org/) 2019.2.1

**Comment by dmsnell** [comment]
Thanks @surfer0627 - it appears that some changes we're making (to stabilize the platform) introduced this without us noticing. Should be fixed soon!

**Comment by surfer0627** [comment]
@dmsnell
Thank you for all of your kindly help.
