### ISSUE TITLE
Adding a tag doesn't add it to the note

### ISSUE THREAD

**Issue by guarani** [Automattic/simplenote-electron#1882]
### Expected
Adding a tag to a note should add the tag to the note in question. The tag should not disappear upon hitting Enter.

### Observed
After typing a new tag name and hitting enter, the tag disappears from the note. The tag will show up in the sidebar tag list, it just don't stay on the note where it was entered.

### Reproduced

1. Open https://app.simplenote.com/ in Google Chrome
2. Click the new note button to create a new note
3. In the "Add a tag..." input at the bottom of the screen, create a tag by entering a name
4. Hit Enter
5. Observe how the newly entered tag disappears from the note
6. If you open the sidebar and look at the list of tags, the newly created tag _is_ there

### Screen Recording

![disappearing_tags](https://user-images.githubusercontent.com/1898325/73875137-83ccf200-4833-11ea-9208-49b51d7e04fb.gif)

Make|Model|OS Version|App Version
-|-|-|-
Apple | iMac 5k | macOS Catalina 10.15.2 | Simplenote 1.14.0

**Comment by guarani** [comment]
This looks similar to [this issue](https://github.com/Automattic/simplenote-electron/issues/87) from a couple of years ago.

**Comment by dmsnell** [comment]
This looks like another realization of the same bug reported in #1879 so I'm going to close it here as a duplicate. Thanks for the report: it helped me update the fix for #1879 to cover other cases I suspected were out there. 👍

**Comment by guarani** [comment]
Good catch – anyhow, I'm glad it helped 🙂.
