### ISSUE TITLE
Renaming a tag removes the tag from the note

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-electron#1887]
### Expected

I would expect that when I rename a tag in the Electron app, the notes that are tagged with this tag would continue to be tagged using the renamed tag. 

### Observed

When the tag is removed, the note is untagged and you need to manually re-add the tag. 

### Reproduced
> 1. Go to tag list
> 2. Click on Edit
> 3. Edit one of the existing tag names
> 4. Click on the tag, to view the tagged post, no posts are tagged anymore. 

![Screen Recording 2020-02-06 at 09 21 am](https://user-images.githubusercontent.com/10325627/73922991-0c926f00-48c2-11ea-944a-a4e533532c2e.gif)

Make|Model|OS Version|App Version
-|-|-|-
MacBook Pro|15-inch, 2017|MacOS 10.15.3|1.11.0 & 1.14.0

Does not reproduce in the MacOS app or web app.

**Comment by codebykat** [comment]
This seems fixed now (at least, I can no longer reproduce in Electron on develop).
