### ISSUE TITLE
Webapp CAPTCHA not working in electron-based messenger

### ISSUE THREAD

**Issue by fungs** [Automattic/simplenote-electron#1890]
Similarly to the issues reported by Chinese users, simplenote stopped working in multi-messenger RamBox (https://github.com/ramboxapp/community-edition) which was working fine before. I thought that the CAPTCHA mechanism was suspended.

**Comment by dmsnell** [comment]
Hi @fungs. We're not planning on removing the CAPTCHA as it's an important element in guarding against bot traffic. Also we're not that familiar with how RamBox is working internally and if Simplenote stopped working there then that's where it will need to be resolved. We're happy to help if you are going to open a PR with RamBox or if you can get someone from that repo to contact us.

**Comment by fungs** [comment]
Sure, it is your decision. I guess what I wanted to say is that embedding your service using electron is not working any more and you should be aware. Maybe you could have given some insight into how it works since your Android app and standalone app seem to be working fine (without CAPTCHA!?).

**Comment by dmsnell** [comment]
Thanks @fungs again. To explain a little more clearly, we're focused on internal needs and on functionality specific to the app we build. We love that people embed Simplenote in other unexpected places but we don't have the time or focus now to go beyond our own product and try to fix other folks' products.

Embedding Simplenote inside another application is not a feature we support or ever really intended. It's cool that it worked. I hope that RamBox gets it working _with_ the security measures.

> Maybe you could have given some insight into how it works since your Android app and standalone app seem to be working fine (without CAPTCHA!?).

We didn't share publicly everything into which we did or did not give insight. I hope you can understand that from time to time we will make decisions to respond to circumstances which threaten the health of our own product. We welcome people sharing their opinions even if they don't agree with us, but arguing about what we did or did not consider won't help anyone or help prioritize the issues you raise.

It's neither our way nor our intention to exclude people from integrating with Simplenote but at the same time we only have limited resources and Simplenote is a free app. We're glad to provide help in integrating our product in someone else's if they reach out with concrete questions or code submissions.

**Comment by fungs** [comment]
Great, thank you for your time to explain you and your company's perspective, which I fully understand.
