### ISSUE TITLE
Context menu (right click) not available in Preview mode

### ISSUE THREAD

**Issue by dplanella** [Automattic/simplenote-electron#1893]
On Linux, given a note with enabled markdown formatting, right-clicking on the note or on selected text brings up the context menu.

Upon switching to Preview mode (Ctrl+Shift+P), text can still be selected, but right-clicking either on the selection or on any area within the note, does not show the context menu.

**Comment by codebykat** [comment]
Reproduced this in the latest app version (pre-Monaco), but not in the browser. Verified I can right-click on other parts of the app and get the menu. I feel like this is probably a bug in the preview component (notably it's adding a listener for click events and I wonder if they're not bubbling up properly on Linux). I'll leave it open for now. Let's re-test after we ship #2148 in the apps.

**Comment by dplanella** [comment]
@codebykat thanks for testing this again. I installed the latest version (1.21.1) and it seems to have been fixed:

1. Open a note in Preview mode
2. Click anywhere or alternatively select a word or section of text
3. Right-click
4. Context menu appears as expected. `Copy` is the only action available in the menu

That said, I would also have expected the `Select All` option to apear along `Copy`. Even if in Preview mode notes cannot be edited, it should be possible to use the `Select All` option as it is under non-preview mode.

Not an issue, as I can just use `Ctrl+A` to select everything as a workaround, I just thought I'd mention it.

**Comment by codebykat** [comment]
This is what I see in the latest (dev) on Electron build:

<img width="358" alt="Screen Shot 2020-10-01 at 9 41 14 AM" src="https://user-images.githubusercontent.com/52152/94838351-4d4b7500-03ca-11eb-9582-26238fc493e4.png">

So I'll close this expecting it will be fixed in the next app release. Thanks @dplanella !

**Comment by dplanella** [comment]
Thanks @codebykat - just one small nitpick - I think you might be showing the edit mode in your screenshot. This bug report is about the Preview mode (where I would not expect to see the `Paste` option in the context menu).

**Comment by codebykat** [comment]
The screenshot actually is in preview mode :) And you're right, it shouldn't have Paste, and yet. That's the default menu so I'm not sure we can fix it, but I'll make a note to look into it.

**Comment by codebykat** [comment]
After investigation, I've opened a new issue for the Paste problem: https://github.com/Automattic/simplenote-electron/issues/2408
