### ISSUE TITLE
Visual checkboxes don't work well with keyboard-only editing

### ISSUE THREAD

**Issue by vicrac** [Automattic/simplenote-electron#1906]
### Expected
I expect markdown checkboxes to be rendered in preview mode, and displayed "as is" in review mode.

### Observed
Checkboxes are rendered in both modes, making it a bit wysiwyg-like editor - one has to use mouse while working in editing mode.

### Reproduced
> 1. Go to any note in edit mode
> 2. Start inserting markdown checkbox:
```md
- [x]
```
> 3. Hit space to finish editing checkbox
> 4. Observe it being rendered to a clickable checkbox

I think it's inconvenient and unpleasantly inconsistent

Environment:
- Ubuntu 16.04
- Simplenote 1.8.0

**Comment by codebykat** [comment]
It's inconsistent, but it is what it is. People really depend on toggle-able checkboxes in plain-text mode; it's one of a few ways we're not a "pure" Markdown editor.

That being said, I agree that we could make the checkboxes more keyboard-friendly, but I'm not sure how that would work.

**Comment by codebykat** [comment]
Oh I just realized we have a prior issue for this - closing in favor of #1265
