### ISSUE TITLE
Could not log in

### ISSUE THREAD

**Issue by lindXdeep** [Automattic/simplenote-electron#1909]
Stopped logging in with the username and password with which I used to log in, after I changed the system from mx-linux to pop!_OS. Username and password are 100% correct.

### Expected
Expected for login

### Observed
Gives an error message
> Could not log in with the provided email address and password.

### Reproduced
> 1. Clicked on start simplenote
> 2. I input login and password
> 3. Clicked log in
> 4. Seeing Error "Could not log in with the provided email address and password."

Make|Model|OS Version|App Version
-|-|-|-|
SYSTEM_MAKE|SYSTEM_MODEL|pop!_OS 19.10 nvidia - amd64 |Simplenote-linux-1.14.0-amd64.deb

**Comment by lindXdeep** [comment]
on Android 8.1 too.

For unknown reasons, this allows to login only the web version. (app.simplenote.com). 

linux and android is: 
> "Could not log in with the provided email address and password."

**Comment by dmsnell** [comment]
Hi @lindXdeep - you might try waiting for a bit and then attempting to login again. If that fails please reach out to support at support@simplenote.com where they can help with your individual account.
