### ISSUE TITLE
Testing changes from week 8, 2020

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#1911]
- [x] Logout
 - [x] Login with wrong password fails
 - [x] Login with correct password
 - [x] Create new note appears in other device
 - [x] Changes to new note sync to other device
 - [x] Changes to new note sync _from_ other device (after debounce delay)
 - [x] New tag immediately syncs to other device
 - [x] New tag immediately syncs _from_ other device
 - [x] Removed tag immediately syncs to other device
 - [x] Removed tag immediately syncs _from_ other device
 - [x] Note publishes with link
 - [ ] Note unpublishes ⭕️ **wiped out changes**<sup>1</sup>
 - [x] Note publish change syncs _from_ other device (visible with dialog open)
 - [x] Markdown setting syncs _from_ other device
 - [x] Preview mode disappears/reappears when receiving remote changes to markdown setting
 - [x] Note pinning syncs immediately from either direction
 - [x] Note pinning works regardless if clicking in list view or from note info
 - [x] Viewing history on one device leaves note unchanged on other device
 - [x] Restoring history immediately syncs note from both directions  ⭕️ **restoring tags fails**<sup>2, 3</sup>
 - [ ] Restoring history revisions updates pinned status ⭕️ (known issue, comes in after successive update to note)
 - [ ] Restoring history revisions updates markdown status ⭕️ (known issue, comes in after successive update to note)
 - [ ] Restoring history revisions updates publish status ⭕️ (known issue, comes in after successive update to note)
 - [x] Can view trashed notes by clicking on `Trash`
 - [x] Can delete note forever from trash screen
 - [x] Can restore note from trash screen ⭕️ **doesn't select restored note**<sup>4</sup>
 - [x] Can trash note
 - [ ] Selects note above recently-trashed note ⭕️ **selects top note in list** <sup>5</sup>
 - [ ] Selects note above recently-restored note in trash view ⭕️ **selects top note in list** <sup>5</sup>
 - [ ] Selects note above recently-deleted-forever note in trash view ⭕️ **selects top note in list** <sup>5</sup>
 - [x] Can preview markdown with 👁 button
 - [x] Can flip to edit mode with 👁 button
 - [x] Markdown rendered in note list when markdown enabled
 - [x] Markdown syntax unrendered in note list when markdown disabled
 - [x] Can filter by tag when clicking on tag in tag drawer
 - [x] Can add tag to note and have it appear in filtered tag view when previously not in filter
 - [x] Can search by keyword with tag selected
 - [x] Searching in the search field highlights matches in note list
 - [x] Searching in the search field highlights matches in the note editor
 - [ ] Searching in the search field highlights matches in the note editor during preview ⭕️ (known issue)
 - [x] Clearing the search field immediately updates filtered notes
 - [x] Clicking on different tags or `All Notes` or `Trash` immediately updates filtered notes
 - [x] Can search by keyword, filtering debounced
 - [x] Tag auto-completes appear when typing in search field
 - [x] Typing `tag:` does not result a list of all tags in the autocompleter
 - [x] Typing `tag:` and something else, like `tag:te` results in autocomplete results starting with that something else, e.g. `test`
 - [x] Tag suggestions suggest tags regardless of case
 - [x] Search field updates with results of `tag:test` format search string
 - [x] Can toggle sidebar
 - [x] Syncs when introducing sequential surrogate pairs sharing the same high surrogate, e.g. `🅰🅱` to `🅰🅰🅱`
 - [x] When disabling network connectivity, changes start counting in unsync'ed changes counter
 - [x] When going back online changes sync and counter resets to `All chagnes synced`
 - [x] Can change analytics sharing setting
 - [x] Changing `Note Display` mode immediately updates and reflects in note list
 - [x] With sidebar disabled, toggling `Line Length` between `Narrow` and `Full` removes and adds border around note content appropriately and immediately.
 - [x] Changing `Sort Type` mode immediately updates and reflects in note list
 - [x] Toggling `Sort Order` immediately updates and reflects in note list for each sort type
 - [x] For each sort type the pinned notes appear first in the note list
 - [x] Changing `Theme` immediately updates app for desired color scheme
 - [x] Using the `Insert checklist` item from the format menu inserts a checklist
 - [x] "Undo" undoes the last edit
 - [x] Typing ` - [x] ` creates a checked checklist item
 - [x] Typing ` - [ ] ` created an unchecked checklist item
 - [x] Typing ` - ` creates a list
 - [x] Typing _tab_ in a list item underneath another list item indents item
 - [x] Typing _shift tab_ in the same spot unindents the list
 - [x] Changing `-` to `+` changes the list item bullet, also for `*` and `•` (`\u2022`)
 - [x] All list bullet types render to markdown lists ⭕️ (known issue, the unicode bullet doesn't render)
 - [ ] Added URL is linkified ❓(in preview mode it does)
 - [ ] When clicking on link it opens in new window ❓(in preview mode it does)
 - [x] <kbd>CmdOrCtrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> toggles preview mode
 - [x] <kbd>CmdOrCtrl</kbd> + <kbd>shift</kbd> + (<kbd>k</kbd> or <kbd>up</kbd>) selects next note above current note, stops at top of list
 - [x] <kbd>CmdOrCtrl</kbd> + <kbd>shift</kbd> + (<kbd>j</kbd> or <kbd>down</kbd>) selects next note below current note, stops at bottom of list
 - [x] <kbd>CmdOrCtrl</kbd> + <kbd>t</kbd> toggles tab list
 - [x] <kbd>CmdOrCtrl</kbd> + <kbd>n</kbd> creates new note
 - [x] <kbd>CmdOrCtrl</kbd> + <kbd>shift</kbd> + <kbd>n</kbd> _when in small screen mode_ navigates to note list

#### Frozen trash view
This is an odd one. I entered a search string into the search field and waited for the list to filter. Then I turned on preview mode. Then I selected the trash view. The app froze in a weird state for a bit before showing the filtered list of trashed notes matching my search. When I cleared the search field the app froze for another bit before showing the full trash view. The Chrome profiler shows nothing but `Rasterizer Thread 1` and `Rasterizer Thread 3` for that time and they take the full CPU. Will have to investigate more as there doesn't appear to be a cyclic loop in the execution code. When I tried to open the sidebar and go back to all notes it froze again and this time spent over a second in the `Event: pointerout` event. Maybe we aren't throttling some handler. I was able to reproduce without the preview step so it appears to be unrelated to that. This was present in the latest web app deployment.

#### Single-use print
I'm only able to print once it seems. There's a funny behavior on the toolbar when I print and once I've printed once, even though I can open the print dialog again, it doesn't print and there are no errors in the console.

![funnyPrintToolbar mov](https://user-images.githubusercontent.com/5431237/74678927-a3d8ab80-5179-11ea-97c7-ed5049d2606c.gif)

Also, the cursor was visible in the non-Markdown-rendered preview

### Notes

 1. When I had the publish dialog open in the web browser and the build from `develop` open in Electron and made changes in the Electron window then those changes were wiped out when I closed the dialog in the web. I reproduced this behavior to confirm. The wiped-out changes were available as the most-recent revision of the note. Probably we're saving the entire note when we unpublish instead of only sync'ing the publish status.
 2. When restoring to a version of the note with different tags the tags reappear locally but don't appear remotely. I tested this by restoring on the Electron app and watching the contents in the web app. If I proceed to make a change to the note locally then the remote app will update and insert the tags as expected. Likely this is because the app is watching for the `update` from Simperium and somewhere we're only looking at note `content` instead of `tags`.
 3. I tested in the opposite direction and repeated the results, though restoring in the web app didn't update the note in the Electron app. After restoring remotely, after making a further change to the restored note, I had to switch to a different note in Electron and swap back to get the updates. This is probably a separate issue from (2) since we're looking at different update flows.
 4. When I restore a note I expect it to open in the note editor and to close the trash view - go back to the normal/all-notes view so that I can edit my recently-restored note. It looks like this behavior hasn't changed though.
 5. In #1851 we inadvertently broke this behavior and then in #1895 removed the mechanism that had previously enabled it.

**Comment by belcherj** [comment]
I was able to print twice.  Anything I'm missing?

<img width="1231" alt="Screen Shot 2020-02-17 at 4 53 59 PM" src="https://user-images.githubusercontent.com/6817400/74688754-9be33080-51a6-11ea-8f5a-26cd4a1896ef.png">

**Comment by dmsnell** [comment]
> I was able to print twice. Anything I'm missing?

I don't know. I was able to reproduce the bug and I tried with a couple different notes. Nothing as complicated as what you have there though.

**Comment by belcherj** [comment]
Looks like this is an Electron bug:  https://github.com/electron/electron/issues/14705

**Comment by belcherj** [comment]
> When I restore a note I expect it to open in the note editor and to close the trash view - go back to the normal/all-notes view so that I can edit my recently-restored note. It looks like this behavior hasn't changed though.

That is not the current functionality in production. @SylvesterWilmott what should it do?

**Comment by SylvesterWilmott** [comment]
>When I restore a note I expect it to open in the note editor and to close the trash view - go back to the normal/all-notes view so that I can edit my recently-restored note. It looks like this behavior hasn't changed though.

I can see why this would be the expected behaviour in a situation where you are restoring a single note. However, by doing this we would be switching from trash to all notes without an explicit user input to do so. And for the user restoring multiple notes it can get frustrating pretty quickly. 

Perhaps what is missing is some feedback that the note has been restored with an action to jump to that note which I think is a broader project to include messaging to the user in the form of snackbars as we do on mobile.

**Comment by dmsnell** [comment]
@belcherj @SylvesterWilmott definitely I didn't intend to trigger design changes here. I noted the behavior because it was unexpected but as we're in the thick of stabilization work I'd be reluctant to introduce destabilizing factors like changing existing behaviors and adding new flows to the app

**Comment by belcherj** [comment]
> When I had the publish dialog open in the web browser and the build from develop open in Electron and made changes in the Electron window then those changes were wiped out when I closed the dialog in the web. I reproduced this behavior to confirm. The wiped-out changes were available as the most-recent revision of the note. Probably we're saving the entire note when we unpublish instead of only sync'ing the publish status.

This bug exists in production.

**Comment by belcherj** [comment]
The two issues that I see as regressions are: 

- Frozen trash view
- Previous note functionailty

And from my testing:
- Revisions slider only contains one revision
