### ISSUE TITLE
Scrollbar Doesn't Move as You Navigate Note List

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/simplenote-electron#1929]
The user in 2715170-zen reported that the scrollbar in the Windows app isn't moving as they navigate through the note list.

In the following screencast, you'll see the user attempting to navigate the list of notes with their keyboard, but the scrollbar isn't moving when the focus changes to notes lower down in the list

![columns](https://user-images.githubusercontent.com/2998162/75252463-a28c2c00-57d4-11ea-9d15-55627f0d1852.gif)

I don't have a Windows device to test this on, but can confirm the Mac app works as expected (with the scrollbar moving along as the focus changes on notes lower down in the list). The user who provided the video is on Simplenote 1.14.0 on Windows 10.

**Comment by codebykat** [comment]
We don't have any other reports of this and this component has been refactored since this version, so I'm closing for now. Let's reopen if anyone else runs into it.
