### ISSUE TITLE
New Web App Doesn't Show Notes in Private Browsing Tab- Firefox

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-electron#1934]
When opening the new web app in a private browsing tab in Firefox, it will show as having no notes. In Chrome, it will show momentarily that you have no notes and then load your notes. 

### Expected
Note would display regardless of using a private browsing window

### Observed
Firefox doesn't display the notes and shows you have none; Chrome briefly shows no notes and then will load your notes. 

### Reproduced
1. Go to a private browser window in Firefox and head to the new web app
2. Log in to your account
3. See no notes or account information displaying

Firefox
<img width="1676" alt="Screen Shot 2019-05-27 at 12 44 12 PM" src="https://user-images.githubusercontent.com/19782997/58433536-624d2100-807d-11e9-87f0-a31fd45e1909.png">

Browser info: Firefox 67

**Comment by codebykat** [comment]
This works now, it detects private browsing mode and offers to redirect you to the old version.
