### ISSUE TITLE
Enable search function in single file

### ISSUE THREAD

**Issue by ouwenkg** [Automattic/simplenote-electron#1937]
Firstlyl, thanks for your excellent work. I really enjoy using your product.

### What

Is there a plan to support the search function in one single file? 

### Why

I only know that there is a global search function. Sometimes, my notes is relatively long, and I want to quickly get the content based on keywords.

**Comment by dmsnell** [comment]
Hi @ouwenkg - right now we don't have any change to the search functionality in this regard. It's a good idea though for long notes with lots of matches in them. Right now we're in the middle of some internal work to improve the stability of the app _and_ the development process so if we end up doing something like this it might take a while - you can check back here for updates.

For now I'm closing this and noting it in our internal feature request list. Thanks!
