### ISSUE TITLE
Restore: History slider shows restored tags but tags are not restored on the note

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1938]
### Expected

I expect that when I view a note's history, anything displayed while using the history slider will be restored when I select "Restore Note."

### Observed

When using the history slider, viewing past revisions shows old tags that were on the note. However, selecting "Restore Note" does not restore those tags.

### Reproduced

1. Add a tag to a note and then remove it.
2. Open the note's history.
3. Use the history slider to go back to a revision with the removed tag.
4. Restore the note at that point in the history.

Result: The note content is restored but the tag is not.

![taghistory](https://user-images.githubusercontent.com/8658164/75449861-aac7a100-5965-11ea-950c-c0b7400c10c4.gif)

Make|Model|OS Version|App Version
-|-|-|-
Windows|VirtualBox VM|Win10|1.15.0-beta.2

**Comment by dmsnell** [comment]
@belcherj I'm guessing this relates to us not updating `note` on the right actions and probably relates to a few other broken things.

@rachelmcr if you restore and then reload the app I'm guessing the tags re-appear

**Comment by rachelmcr** [comment]
>  if you restore and then reload the app I'm guessing the tags re-appear

I tested this and the tags do not reappear, even after reloading the app.

**Comment by belcherj** [comment]
@dmsnell I think it has everything to do with:

 Restoring history revisions updates pinned status
 Restoring history revisions updates markdown status
 Restoring history revisions updates publish status

Im pretty sure we restore the text of the note but not any of the associated tags.
