### ISSUE TITLE
Markdown not stripped from notes list preview when preceding line ends with a space

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#1939]
### Expected

I expect markdown formatting to be stripped from the notes list preview when markdown is enabled on the note.

### Observed

If the preceding line of text ends with a space, the markdown won't be fully stripped in the notes list preview.

Compare this text where the stripping works fully as expected:

```
# New Note

# H1

# Another H1

## Subheading
```

And this text with spaces at the end of each line, where the markdown isn't fully stripped:

```
# New Note 

# H1 

# Another H1 

## Subheading
```

### Reproduced

1. Create a new note with markdown enabled.
2. Paste the first example text into the note. Notice that all markdown formatting is stripped from the notes list preview.
3. Replace the note content with the second example text. Notice that the markdown formatting is stripped from the title and first line of content, but not from the rest of the note preview.

![Screenshot 2020-02-27 14 01 22](https://user-images.githubusercontent.com/8658164/75452168-b321db00-5969-11ea-9377-f843926f4f83.png)

Make|Model|OS Version|App Version
-|-|-|-
Windows|VirtualBox VM|Win10|1.15.0-beta.2

**Comment by dmsnell** [comment]
Not sure if it was in #2148 or elsewhere but I believe this is fixed now.
