### ISSUE TITLE
Open two windows side by side

### ISSUE THREAD

**Issue by benjaminwolkchen** [Automattic/simplenote-electron#1957]
I'm not able to open two Simplenote instances sitde-by-side.

**Comment by dmsnell** [comment]
That's correct, @benjaminwolkchen - unfortunately we don't support this. If that changes in the future we'll definitely announce it. In the meantime if you really want two windows you can open one or more different browsers to https://app.simplenote.com.

We've not intentionally limited the app - it's just that we've got a full list of work keeping us busy. Thanks for writing in!
