### ISSUE TITLE
Won't install in Debian 10

### ISSUE THREAD

**Issue by waywayka** [Automattic/simplenote-electron#1962]
Selecting previously unselected package simplenote.
(Reading database ... 264468 files and directories currently installed.)
Preparing to unpack .../Simplenote-linux-1.15.0-amd64.deb ...
Unpacking simplenote (1.15.0-10394) ...
Details from the install process....

Setting up simplenote (1.15.0-10394) ...
Could not parse file "/usr/share/applications/screensavers/glitchpeg.desktop": Key file contains line ?several times a second.  After a while, finds a new image to corrupt. Written by Jamie Zawinski; 2018.? which is not a key-value pair, group, or comment
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...

**Comment by sandymcfadden** [comment]
Just tried installing the latest version Simplenote-linux-2.4.0-amd64.deb and it installed on Debian 10 without issue. Closing for now.
