### ISSUE TITLE
Text style changes in Electron 1.15

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-electron#1970]
# Expected

A user expected the font in the app to remain the same when updated. 

### Observed

When testing the Electron app version 1.15, the font is a lot heavier than in version 1.14. I'm not sure if this is expected or not, but it feels like the weight of the font has changed a lot, especially in the content area. 

Is this expected behaviour as a new style change? Personally, I appreciate the title being the heavier font but liked the lightweight of the content area. 

### Reproduced

Install both Simplenote 1.14 and 1.15 at the same time, compare the versions. 

<img width="1094" alt="Image 2020-03-17 at 9 26 34 pm" src="https://user-images.githubusercontent.com/10325627/76904505-049df580-6898-11ea-99cf-e75b711c91a6.png">
<img width="1101" alt="Image 2020-03-17 at 9 29 23 pm" src="https://user-images.githubusercontent.com/10325627/76904508-0667b900-6898-11ea-8cd3-9ede25393db9.png">

Make|Model|OS Version|App Version
-|-|-|-
Macbook Pro|13" 2019|10.15.3|Electron 1.14/1.15

Reported by a user in 2793655-zen

**Comment by codebykat** [comment]
Closing as stale
