### ISSUE TITLE
Simplenote web username handle link to share all published notes in a single web page

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#1973]
### What
***Already we can share notes with app.simplenote.com web app's unique url. The problem is for every shared note we get an unique url. Now we need a username/handle web link to share multiple notes/all notes in a single web page.***

### Why
***The simplenote.com/username web page will be our home of all shared note's in a single web page. Then we will be able to share this link in our email/website/blogs etc. It'll be like a homepage of our all personal shared notes. Then we can publish all our shared note in a single web page.***

### How
***You can provide us an unique web page link like http://simplenote.com/username or http://simp.ly/username then it will solve our problem***

@bummytime @belcherj @dmsnell

**Comment by codebykat** [comment]
This is an interesting idea, thank you! I'm closing this for now as it's not on our immediate roadmap, but we'll consider it in the future.
