### ISSUE TITLE
Incorrect opening screen position after closing side docked

### ISSUE THREAD

**Issue by simsrw73** [Automattic/simplenote-electron#1976]
On W10, if I side dock SimpleNote, ie grab the title bar drag to the right edge of the screen to dock it to the right half, and then close the app. Upon opening it displays at the top left of the screen. 

There are two problems with this:
1) Most other apps, including other Electron apps (VS Code, Vortex), do correctly remember being side-docked and open in that same position.
2) This is my biggest issue: it ignores the position of the Windows taskbars. In my case the main Windows taskbar is docked at the top edge of the screen. SimpleNote opens behind the taskbar after having previously been closed when side-docked.

Windows 10. SimpleNote 1.15.0

Thanks,
Randy.

**Comment by sandymcfadden** [comment]
This seems to be related to [this issue](https://github.com/Automattic/simplenote-electron/issues/1715). I'm going to close this in favor of it.
