### ISSUE TITLE
How can i help to translate the app in Portuguese? (Linux App specially)

### ISSUE THREAD

**Issue by Diolinux** [Automattic/simplenote-electron#1977]
Hi! I'm long time user of Simplenote, it's great app. The interface is simple and intuitive, and the inexistent of a Portuguese version don't really border me, but i think other people may not use because of that, so i like to help with the app translation.

How can i do that? :)

I also have some ideas for features, but we can discuss this later.

**Comment by sandymcfadden** [comment]
Thanks so much for the offer. Localization like this is something we are tracking in our internal feature request system and something we plan to look at sometime in the future. For now I'm going to close this issue but I've added to our tracker for this request.
