### ISSUE TITLE
Simplenote-1.15.1 rpm will not install (normally)

### ISSUE THREAD

**Issue by aguador** [Automattic/simplenote-electron#1980]
I downloaded the x86-64 rpm and attempted to install it in my Mageia Cauldron system using rpm.

1. Run 'sudo rpm -ivh Simplenote-linux-1.15.1-x86_64.rpm'
2. Result: Error de dependencias:
	gtk3 is needed for simplenote-1.15.1-10908.x86_64   [Gtk+3.0-3.24.16 installed]
	libXtst is needed for simplenote-1.15.1-10908.x86_64  [lib64xcb-xtest0-1.14.1 installed]
	libnotify is needed for simplenote-1.15.1-10908.x86_64   [lib64notify4-0.7.9 installed]
	libuuid is needed for simplenote-1.15.1-10908.x86_64   [lib64uuid1-2.35.1, 32 & 64 bit installed]

Since I did not believe dependencies were missing, before even looking, I unpacked the rpm and installed in it by hand and, voila!, it runs.

Since there was no SPEC file in the package, I suspect that this was built with from a deb package with Alien or some such thing.

**Comment by dmsnell** [comment]
Thanks for reporting @aguador - we build the app with `electron-builder` and don't get into the details of the `rpm`s or `deb`s much. It's odd that it wants `gtk3`. Do you have any idea why it's requesting those?

**Comment by aguador** [comment]
It does pick up the theme for the menu bar independently of the theme chosen for the app, and for that it would need Gtk3. I am not a programmer and am not familiar with electron, but this would seem to be an upstream problem with electron-builder. At the moment you can simply note that it does install with the --nodeps rpm switch. The deps do not seem at all exotic, but if something is missing, more advanced users will no how to resolve them.

**Comment by dmsnell** [comment]
thanks for the tips. we'll remember to try this if people report the same problem. thanks for taking the time to share your debugging steps!

**Comment by sandymcfadden** [comment]
I tested installing the latest version of Simplnote on Fedora 32 using the same command as above
`sudo rpm -ivh Simplenote-linux-2.4.0-x86_64.rpm`. It installed properly without any errors. 

I'm going to close this for now as it seems like this could be resolved in one of the updates since this was reported. If you are still having issues though please reopen and let us know.
