### ISSUE TITLE
Error when manualy trying to update

### ISSUE THREAD

**Issue by gozzoo** [Automattic/simplenote-electron#1984]
### Expected
When I select Help - Check for updates from the menu I expect if there is a new version the update process to begin

### Observed
Empty box with title 'Update Simplenote' shows up.
![simple-note-update](https://user-images.githubusercontent.com/296970/78229705-03e0a280-74d9-11ea-8269-cac58a2616ad.png)
It closes after few seconds and an error message pops up:

![simple-note-error](https://user-images.githubusercontent.com/296970/78229790-1c50bd00-74d9-11ea-9f9c-587d646c200d.png)

### System info
|Make|Model|OS Version|App Version|
|---|---|---|---|
|Custom built|Intel|Windows 7|1.15.0|

**Comment by rachelmcr** [comment]
I just ran into the same error.

When I am on the latest stable version (1.15.1) or the latest beta version (1.16.0-beta1) it works as expected:

![Screenshot 2020-04-21 12 59 20](https://user-images.githubusercontent.com/8658164/79863659-0ba4b000-83d0-11ea-8060-c56fe487f8ae.png)

But when I try to check for updates on a previous stable release I see the same "Something went wrong!" error noted above.

Reproduced on Macbook Pro macOS 10.15.4 with 1.14.0 and 1.15.0. cc @belcherj

**Comment by codebykat** [comment]
I worked with another user in tickets who was stuck on Windows 1.15 but reported it was fixed when they installed the 1.15.1 executable.

**Comment by gozzoo** [comment]
@codebykat that might be true, but there is no way for me to upgrade to 1.15.1 because:
- if I try to do it trough the app I get the error which is this issue itself
- if I go to https://simplenote.com/ and try to download the windows version from there I can only get 1.15.0. This is the actual link:
https://github.com/Automattic/simplenote-electron/releases/download/v1.15.0/Simplenote-win-1.15.0.exe

**Comment by codebykat** [comment]
Hi @gozzoo,

That note was more for our team to help narrow down the investigation, sorry for any confusion. The 1.15.1 version is still in beta, so for now it's not yet the one listed on simplenote.com, but if you'd like to verify the fix, you can download it directly from here: https://github.com/Automattic/simplenote-electron/releases/download/v1.15.1/Simplenote-win-1.15.1.exe

**Comment by codebykat** [comment]
@belcherj Is this something we can fix in the older versions, or should we just let folks know that they will need to manually upgrade?

**Comment by belcherj** [comment]
TBH, I am not sure. I was unable to get the error message to determine what went wrong.  If we get any more reports I will dig deeper.  I think for now if the number of reports is limited then we can ask users to manually upgrade.

**Comment by gozzoo** [comment]
Just to confirm, the issue is still presnet in 1.15.1. 

I had installed 1.15.1 by downloading it manually and when 1.16 became available exactly the same thing happened again - when checking from the menu for update the error message showed up.

**Comment by belcherj** [comment]
Thank you, I will look into this deeper to determine why this is occurring.

**Comment by rachelmcr** [comment]
@belcherj were you able to find anything more about this one? I confirmed I still see the error when I check for updates (tested on macOS 10.15.4) with these versions:

* Simplenote Electron 1.17.0-beta1
* Simplenote Electron 1.17.0-beta3
* Simplenote Electron 1.16.0

The only time checking for updates worked was to get the "You're up to date!" message when I'm on the latest production/beta version:

* Simplenote Electron 1.17.0
* Simplenote Electron 1.18.0-beta1

But of course that's not so useful for actually getting the updates. :)

**Comment by gozzoo** [comment]
Isn't this supposed to be kind of important providing that people can not upgrade, unless they reinstall the application.

What's the purpose of releasing new versions if most people can not upgrade to them?

**Comment by countfak** [comment]
Still having this issue with 1.20.0.
I will now manually install 1.21.1.

**Comment by rossanafmenezes** [comment]
Another report here:

3600755-zen

Windows 10 Professional versions:

Version 2004 (OS Build 19041.685) and Version 20H2 (OS Build 19042.685)

· The current version of the Simplenote app

installed is Simplenote 2.0.0

· The exact steps you take to update the app

Simplenote 2.0.0 was installed as Administrator

Opened the App with User + Password credentials

Clicked Help > Check for Updates

Simplenote Popup Window is displayed

Window Name: Simplenote

1st text line In blue: Something went wrong!

2nd text line: Please try again later.

OK Button to confirm the message and close the Popup Window

The folder “C:\Users\<UserName>\AppData\Local\simplenote-updater” contains no files, but only an empty sub-folder named “pending”

**Comment by codebykat** [comment]
Let's track any ongoing issues in #2251. Folks who are on 2.0 had a known issue and will need to manually upgrade. It should be fixed from 2.1 onwards.
