### ISSUE TITLE
ARM v8 binaries

### ISSUE THREAD

**Issue by Feakster** [Automattic/simplenote-electron#1986]
Will you be releasing ARM v8 Linux binaries in the future?

**Comment by dmsnell** [comment]
Thanks for the question @Feakster - I don't anticipate us releasing any ARM binaries in the near future. If Electron and `electron-builder` support it then we will too, as we have no native code in the Simplenote part of the app, but that support is still largely missing.

Electron has apparently started supporting Windows ARM64 binaries but I think even that is still in its early stages. We'll announce if it we do start though.

Just out of curiosity, what is this for? A Raspberry Pi?

**Comment by Feakster** [comment]
A Pinebook Pro.

**Comment by dmsnell** [comment]
Very good. I wouldn't hold my breath for this. We mostly focus on the app code and rely on `electron-builder` for building the binaries. You can keep track of what's happening in Electron or in other Electron apps. It looks like there are ways to make it work but I'm pretty confident that, for example, you won't find Simplenote on ARM before VSCode or Slack are officially available on ARM.

Closing the issue for now. Thanks for using Simplenote and sharing!

**Comment by Feakster** [comment]
Thanks for getting back to me. Will use the website interface for now.

**Comment by rschouwenburg** [comment]
Electron and electron-builder support both armv7l and arm64.

I just compiled and ran simplenote-electron on a Pinebook Pro (arm64). No modificatons to the source was necessary except for adding arm64 to the electron-builder.js

Would it be possiblee to see if a release can be made for these two platforms?

Currently Pinebook Pro, Pinephone, Rock Pro, Raspberry Pi and Purism Librem 5 benefit from this and we all love our beloved note app.

**Comment by dmsnell** [comment]
@rschouwenburg would you be willing to submit a patch to our build process? that would definitely help us get to Arm faster.

**Comment by rschouwenburg** [comment]
Sure no problem. Or would you like a pull request?

**Comment by dmsnell** [comment]
@rschouwenburg I meant a pull request, thanks!

**Comment by rschouwenburg** [comment]
Here you go. Let me know if I did not do this correctly.

Happy to beta test on production!

**Comment by Feakster** [comment]
I also wouldn't mind beta-testing this if an arm64 version becomes available.

**Comment by Feakster** [comment]
Thanks for creating the aarch64 and armv7h binaries. just tried the aarch64 one on Manjaro ARM. Works like a charm.

**Comment by dmsnell** [comment]
@Feakster just a mental note: the binaries have been disabled in the beta release we're working on; for some reason they were breaking our builds and at the time I chose to stop making them so I could continue working on the refactor of the app. hopefully we'll be able to add them back in without much ado but it could be shaky again temporarily.
