### ISSUE TITLE
Sync Issues from Chrome on Chromebook to iPhone

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-electron#1994]
### Expected
Note updates made in a browser should show on an iPhone app using the same Simplenote account.

### Observed
 User makes edits on Chrome. They do not appear on the iPhone. To try to get them to sync on the iPhone he has tried:
- Closing the iPhone app and reopening it
- Switched from wifi to cellular data
- Logged out of Simplenote and back in on the iPhone
- Logged out of Simplenote on all devices and cleared browser cache
- Disabling all extensions on Chrome

To further investigate I'm asking the user for a screenshot of the JavaScript console in Chrome and to test a different browser on the Chromebook

Iphone Details: 
iPhone XR
iOS 12.3.1
Simplenote 4.16

Chromebook Details:
Asus Chromebook Model C201P
Simplenote: Chrome 1.14.0
Browser: Chrome 80.0.3987.162 (Official Build) (32-Bit

#2816066-zen

**Comment by dmsnell** [comment]
@sarahfg I think I've seen this before. does this occur only when creating new notes or also when editing existing notes?

**Comment by sarahfg** [comment]
I'll ask and see :-)

**Comment by codebykat** [comment]
Closing as stale, let's open a new issue if we get reproduction steps on the new version.
