### ISSUE TITLE
Firefox populates search field with username

### ISSUE THREAD

**Issue by kristarella** [Automattic/simplenote-electron#2011]
## Issue

When password management is on in Firefox, it fills the web app search field with the username.

## Reported

Over the course of several years:
- https://simplenotep2.wordpress.com/2015/10/26/email-address-appearing-in-search-box-firefox/
- https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2616730
- https://woothemes.zendesk.com/agent/tickets/989626

User has said:
> In any case, I've found that changing the search field's "type" attribute to "search" instead of "text" fixes the issue. Setting the field's "autocomplete" attribute to "off" ought to fix it as well I suppose, but I don't have an easy way to test that.

Changing the type might be a suitable fix?

**Comment by codebykat** [comment]
Closed by #2104
