### ISSUE TITLE
Keyboard shortcuts dialog missing/doesn't always work with Toggle Full Screen shortcut

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2027]
### Expected

I expect the Keyboard Shortcuts dialog (under Help > Keyboard Shortcuts) to document all available keyboard shortcuts.

### Observed

The dialog doesn't include the keyboard shortcut to toggle full screen mode (found under View > Toggle Full Screen). For example, on Windows this is `F11` and on macOS this is `CTRL + CMD + F`.

I also noticed that after using the macOS shortcut `CTRL + CMD + F` I can't bring up the keyboard shortcut dialog with `CMD + /`. I have to click on the app and then use the shortcut.

### Reproduced

1. Go to Help > Keyboard Shortcuts to view the keyboard shortcuts dialog.
2. Notice that there is no shortcut listed to toggle full screen mode.
3. Go to View and notice there is a shortcut listed to toggle full screen mode there.
4. Type the Toggle Full Screen mode shortcut and notice it works as expected.
5. On macOS, type `CMD + /` (the shortcut to bring up the keyboard shortcuts dialog) and notice that nothing happens.
6. On macOS, click anywhere on the app and then type `CMD + /` and notice it works as expected this time.

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.16.0-beta1
Macbook Pro|macOS|10.15.4|1.16.0-beta1

**Comment by dmsnell** [comment]
Small note here

> I expect the Keyboard Shortcuts dialog (under Help > Keyboard Shortcuts) to document all available keyboard shortcuts.

I intentionally left platform-provided shortcuts out of the keyboard map and would probably prefer not to list things like <kbd>F11</kbd> and <kbd>Ctrl</kbd> + <kbd>Cmd</kbd> + <kbd>F</kbd> because that list would be really big and is already documented on the platform (Windows, macOS, Linux) and may be different if people have changed their settings.

I'd prefer we stick to those shortcuts we intentionally add to the app and which are unique to Simplenote.

The other critiques here are valid.

**Comment by dmsnell** [comment]
As per the "click on the app and then use the shortcut" bit how big of an issue would you consider this? It looks like it may have more to do with Electron/macOS at a glance and I'm not sure how easy it will be to fix.

**Comment by rachelmcr** [comment]
I'd consider it a very minor/low priority (nitpicky) issue and probably fine to `wontfix` if there isn't a straightforward fix, as long as this isn't causing reported issues for end users.

**Comment by codebykat** [comment]
The shortcut is working for me after toggling to/from Full Screen and I agree that we don't want to add platform-specific shortcuts into the list.
