### ISSUE TITLE
Can't access note list with narrow app window

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2029]
### Expected

When my app window is narrow, I expect to be able to go back to the note list using the back arrow in the top left or the keyboard shortcut `CTRL/CMD + SHIFT + L`.

### Observed

When my app window is narrow, the note editor takes the full frame and the back arrow appears in the top left. However, clicking on that back arrow or using the keyboard shortcut doesn't do anything. I can't get back to the note list unless I make the app window wider.

### Reproduced

1. With a wide app window, notice you can see both the note list and note editor.
2. Drag to make the app window narrow until the note list disappears.
3. Click the back arrow in the top left and notice that nothing happens.
4. Type `CTRL/CMD + SHIFT + L` (CTRL or CMD depending on your OS) and notice that nothing happens.

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.16.0-beta1
Macbook Pro|macOS|10.15.4|1.16.0-beta1

**Comment by rachelmcr** [comment]
I confirmed this also happens on staging.simplenote.com, making it unusable in Safari on my iPhone XS (iOS 13.4).

**Comment by codebykat** [comment]
Closed by #2037
