### ISSUE TITLE
Note repeats and mangles changes in web app

### ISSUE THREAD

**Issue by evazorro** [Automattic/simplenote-electron#2030]
I've been having issues with Simplenote saving or syncing changes, both in the Android app and in the web app, but this morning one note in particular went bananas.

I created a new note, entered some short text ("DIY voice assistant" as the title, and then a URL as the body text). I clicked into a different tab, and then went back to add another bit of text to my note, and saw that it had already repeated the title three times. (I see this sort of duplication sometimes when there are sync issues, but I hadn't opened Simplenote on any other platform in the meantime).

### Expected
The note stays exactly as I wrote it

### Observed
The text was duplicated within a matter of seconds, and then proceeded to become even longer without my intervention. See the video below where I examine the changes.

### Reproduced

> 1. In Simplenote web app in Firefox, click to add a new note.
> 2. Type some text.
> 3. Wait and see if it goes crazy.

Gif of first problematic note:
![original-note](https://user-images.githubusercontent.com/1493712/79882957-579c2880-83c1-11ea-9190-124ff47ca72d.gif)

Gif of repro:
![repro](https://user-images.githubusercontent.com/1493712/79883173-9631e300-83c1-11ea-8dfb-3b6e6a564a80.gif)

### System info

* I'm using Windows 10
* Simplenote web app accessed in Firefox 75.0

**Comment by evazorro** [comment]
If you want the full text of what the original note ended up as, here it is:

> DIY voicc  abey spstuositiihipuiiiihrmtttttttttttttiiihriiisrirrcsttricsootirciroctmoirrcsrcoirccotoiioicictoiiortrcioorttsrsrtctorsrtoorttictiirrrtstrooistirrocotitrtcmmriiiccotrorscsrrstciotrcoooiricrtsiottotisicoccooiroiocsiosictcotortocioscsoiroscrsicitctcottorocmtctscsrccictriioirosrtroistsscroissortrttrcossrtortrsrcssrtorisctsssirsrsortsccrcicccccctcorsccicciirriirricotrccsicctitssicootcotcorsooisitcicirttssriitrctiotttirrrroccttcisrccscoictcctooitocsrostcocoocirssootcstriotiistsrcocooirosrsccoosioissrstitrictsirrcscisrcscsriticrrrstttrsroocsistrstctttcptssisrsttsotcocooccirssiortitttosoiosrtistsccirrsrcsisiirotrosrtsrrsoircioorcotssrrtirtroroicriccsttctiscsriroostssscccccricciccorcstccsccototsisttrsccoiioititcoiisrrtcsrtisrcrioiotrtirrrtrtrissiiisiccrotrtiittststoootrioscsorctrtrsiortrctcssocccicssosporptpcsoooooirttrsiooctrtsirociortrtscctpsprsssttsrprtocirccrssrscioisistroccsstrcrcsoorssirrtiototircrspssssctsrttscortpirsiooctttscccisrririicicosocsrooooottioiiortiistottciisstcctcocsrsrssrsrrsrppissrstporsrsossorriciorsccttopircrtsocsssrstpitipppopptsrtocstocircorcrrttocirccscssrtsoccrporptrssttrisrssrosicoiisrpttsrrcsoscrtptssiirprptpprooioprstrptcppporrrpiosrrpcotpipsorrstssstiisstprppppotiocscticssocccrcrstcoootsooorosrcicooocosposoriroprstrtticrtrtpspoorprsstrcsitctstptrosttictpcpttsppripsorrstitsstciotptrpossirssritrcticttopcoritpccpopsttcssoorritspociitccpocrriioptsrsiirporporsttsrcprtcppsrproprroocsriiorsstoopciispirtrspsppsopsisrpsrrrsttoococoptrcsippsorpstpippsotttcirrptpprccrtcrtcpopprptspotosposstoocprspoosiitcicitirioirrsttccrocictpcpcpsppopootsioirrotcocsstoppiiccoososrsissrittsstccrstissptcsitrrsssrscscoiitocppociitciioosttcssctiicpicoosssiicoosppipiiioocoioisipstccosipssscpsoostiicoospsssptiopsiiissciooococppisiiscciocissoptcpstpcctoitcrsoocsitorsrcoioiiotittpstippopostpiittscptccsssitcstotpsipsptscsppttppsiiciotcoorscisioitoccstisssopttcoosoosotssittttcicccorpssisstittpsiicsstcsiooossppcscctospocoppooioppcocrssctssitoroosisrrossrrsotciiootiirroocrrotiicciciroioppsstposprcortttopiprtctpitsstocssccpstoittctsctssisiccctpiiistctticoiiciipcoitcocpscrcitciptssrrcrooiroiciipcttoioirsstcoisscstostiitcipscsitoctppsrroticcrtsrsstoroicorcpcpoostocccoriirrrriprospprpocpsprccrsopisicioirrpscosrsrpicrpritpiiitiitstrrtottpsiorircrprprorooocororcosirocripippioosspociiiciorrororpcissioocorriipoicsrcriopiisrrrssrrrorcoposoiipcpriipiosssipcrriiiiiioopsoiiosorcioiocorciisicccoccccipicocccisootctirtocposctirctocpppcpssiccccccocsocicocrrrirtocccposccscrrcirtitootciiscpcpttucrtsrppcmpmmttcmmccrruitrmroitmmmor..i.uiitccctrmrrhrmtmrcmtottirriitcccrtrmchrruucrrrcmcctttccc.ucrmrrcrrrcctttcccrrumrruuucrrrcttucrrcptrrrmcmccpprhhmtmmihmmpprtrmsshhmrmmrhrmmmotmrtmrrormmitmiirirritommmomtirtoriiooimimirrmiimmiiiirmmmiorimmrimrrrmiioiromirmoitmimri.rmitoimooimoooirrttirtmtt.rrrrmoiu.ic.rrrmrirru.mmtimtmrrrrmrmrru.mirrrirrttooiu.ututt.itrrmiiiiu.r.cri.mrmrmiimimutrrmumrttmu.cciiiircu..imiimm..cu.p..ciircmmipm.mpmcm..pmccimcr.cpmitccm.ccm.mc.mmcccccc..ccciccccccrcccc.ircciir.riri.r.c.tppcuirp.t.rccciiicurpm.t.ri.iu.crr..iuc.c.rr..imimii.c.rmroitmrcmtim.mtmp.c..tum.urpuip.pmp.puprrpmp.rrmp.piittirrtrtrttttturtuctcimu.cmmi.pucipimpiiumm..cu.p.imprmmp.imprmrcrcpcpummprmmcicrmpipmi.m.m.iprpicpcicicpipi.i.cimm.pi.cicmpimpcpm.ccm.c..cc.cccccmmc.cp...cruuuurrprummrmrmcm.prprrrmrrttm.puc.icu.crmmummmm.mpipppc.ppcim.cicpmm.ciccrpipm..c.cccc.ircciir.riri.r.c.cp.ucu..cm.ir.urmrr.prpippmi..cr.mpippmi.ircim.irmircmumccirmmurr.tmitmi.mcrtmirrcuumrcr.pm.rm.uprr.um.pr.ppmp.ri.ppcripp.mmmupicir.pr.pmucmcpcppr.pipimppmmupmu.ipr.p.pmi.mirr.cpppmpm..cm.mim.m.imp..cm.uimuiuimmcc.mcripirriiirimmrpii.pci..up.iiimm.rc.ipmrcrii.ipip.cicciiiiipiupuipccumrcmimmiimimprciim.mrr.mc.icirp.im.rcriiiiic.mmim.mc.cc.im.miii.m.mmpmimr.pimrmrpi.irmp..ccmircm.ttmpppc.c.pmmcic.i.mcppppprpmpriri..pcppppm.cuiii.r.irr.rp.cc.iiimi.pimm.uipupiimipcim.pu.cuppp.iipripcmpprppmmmp.mmi.rricimipi.i.pppp.imp.iumciccc.cpcp.p.cppmmmmmmipcmimmpc..pimpiiicmm...i.ccmcc.ic.impmpppmmcccii.ppcc....ii.ic.mmmmm...ir....pimpmmiiumpip.i.c.mmcipiiimimiiiccrummc..pctpicc.rtpppcmimmmmmm..cmptii.pp.c.i.pp.c..pppiicimm.mmii.ip.ippicmiucpicmipt.icmmrm.icrrmiiuimpcmmm.cri.ppp.imim..uic.cumcimmir..mci.ttmpppc.c.pmmmpimrmrmimmmp.pcipmpcpimcmcrtmtrci.iimmmrrprm.uimumccimiuiccitipmum.i.m..pmcpmrr.mmmmmm.ucicirmpmrmrmmummpmpp.m.mip.i.cipiicmpccmpmm.u.m.mip.i.pimic..mcr.iippiicmpccmpmm.u.m.mip.i.p.iic..mcrrmmiumipmimmuuiurmpmimm.srr..ir....m...m.i.rtpirmuirrs.mi..irprripmrttirmuiritururmpcrtrppciuiripccurcrrprrpcmprpccrpcrprppprimpccrcrpcuccrrpmrpmicurrpmucppriripmucitptuppitmcpupiirccrrpruppiupuimcipirputppr.t.umru..u.uiccicmim.cmccmr..cmircs.srccscm..rsrms...crr.rr..r.cirm.prrtuumrcmcmmuuuuuucmuucrcrmpicpmimpmcimppmimrrirmmpmmrrmrrm.mrumpmrmpuuruumpprrp.mmpppmrmuc.mrpm..uuucrmprrpmruumrumucrumcrrucmipppmcuiccmucmupppiiiurprrruuuuiiupupuuuuccmcrrurrcuuiccccuiuicmmuuucuucircucrc.ccuuuuuuuutuiutuurrcrutuctprrcrcmuiurccmppmmuriumruuurirupuuuuucuruuiriprruppuicumuucpcmuurcccucucucuucupiupuupupurrt.utitcrmpt.mcrcrpur.uummm.mmss..u.smsmuuuuccccccccccccmmmrpm.p.cuppm..mphtmttpihcippmttpccmtttuptttuptccmpttmptttuptccmtttcctttuptttupihcipccccccuiuphccuppihcicipccccccciiprrprpihirtprh.pcpuupp.pu.pupr.hrrpppppp.rrhttp.pppp.hppihhhphhphphphiiiirriirrpc.cppppr.iit.mmcppcutcmircmmm.cmm.i.rmh.mh.mmprppmmmmpppttipipiprrm.pirhmmtmmprimhmrsmtutpummm...m.tccu.rr..prsrpsi.rppprp.prrrhr.prrrhrhtrphprhhppppprprthtpr.pphrhpprppprppppprppprppprpppppprpp.r.sss.ssrsprpspismitc...p...ssscismittc......ss.t.tt.sspp.spmricismic....pssrspricismittc.t.pttc.pmmmt.riimiirripr.i.imiirrr.srp..rr.rprimii.i.ii.r..im..i..i.mi.pim.rp.misrr.riii.ii.ii.siiti.i..rrp.tp...r.iimir.iii..rprirriirii.rri.rrprriripimtririiiitiir.t.tsmrr.tt..rmrtr.rtip..iiri...trtmsr..mrrrrrm.rtsmst.srtsrtsrmsrs..tspp.pprrss.rrsiis.pr.rsspspsps.ppps.sssrirrpi..srrii.ppipp.p.ripi.rsppimppiprir.rs...piippp..rt.pmmppt.pmmp.mmcmprsr.psmcumsrsp.mmmpmsrrrs.ii..i.itpp.ts..pmr..mmpmpp.pcmt.icrhmtips.pmrsmc.mtcrsmcm.csc.m..rcccmmctrtctrt.ttttrt.m..ummrtc.rttsmucc.mmutuctrtstturuchtmtsmcccctm.mmttc.tmt.mm.ohmmm.ttmhomooh.ffmttfft...tftf.toprutspo-.stopo.ppttpp-ttrt-r--po:icirttmstmpstthoustrt.t:iprt:rrtiiirc.c.tsrtts:pppmp:pprtsmrttstsooioit.:oospsbffh.hr:uu-.ou-aurgcncccrtcccrtrrgt-mccrth-cry-mmgychogagt-hogscgoyhoascgoayhogtgtgtath-rtrtrcygmnsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiunsiummiucghghcrbocoy-mgycuhogscgoyhoagatt-o-gccrcncrrrrcrrrrrtt-o-gccrcncrrrrcrrrrrtt-o-gccrcncrrrrcrrrrrcch-cccmgymootgncryg-mnsiuucghcrbocoy-mgycugtogccauuo-gao-guhogccatoghcoagcrgtghtogcru/accrgmgysryryg-mnsiuuccrbocoy-mgycugtoscu/aboogogoggoru/chgo///c/h/hrcrrcrcrcrcrgccg//orcrccccc/cccr//grcrrrcrogg/h/ogcccccccrccchcrccchcc//chcg//cc/chcg//rocgo/rrcr//c//gr/cccrch//crogocc/crrrhoc/ccrcchcc/ccco/cccgo/hhrr/cr/rrrcrr/r/rrrcrcrrhcc/c/rhchc/cgg//rcrocoohcohccrccocrcocohcrrhocch/ogroggrggrrhhrhh//rhrorgohrghrhuh//auhrghusniyorg-oyoo-oys-gucortccrthrycrumrmycroo-gffmu/--moi/si/cfcu--oifm/fm/ooeoffmiim/immfc/oitemc/f////cefecieciecieciicecci/teoffcgicigocgccygtyytytyi/--if/sccfuio/uefcuogitgicoiocccccigtiggcotogigucgocucgocoouiuguuciocooccoooctoogggccogcogggoooottgtgutuogootttouttttttttcttttttctttctocctiuocgooggtugocttgcgcccuutccggoggotg-uiiigcgtoigoooccigoguucgtuucgucoiooougoogogtugogococoooooigoguctggcocooiouoccicciuggoioucoicugogoccoiicoiciicocgiit-utcggcccccgicggioggouoggotu-uugoiigogocigoccuugocgoo-otticoticctictoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticoticotiggticogouiouguucctggogtgiggggogtoo-ooiguutututgtguugutuguctcgcgctgcgtugccttuctuctgtgcuuoogcouutgtugcutcoiigutugcuotcoiigutugcuotugucucogcccctoioiuiiuoiuiuoicggoc/cco/gcoooect/g/i/cccigi/iug/goocgociggoguc/ciegugeog-tcccgogoegtigg/ocggccccecgogoegtigg/sgcggcccececgogoegtigg/gccegogoss-tcceocgcoe/i/ciogc/gocgoegtigg/ocigicocccocgeciggstet-gegcioccooooiiiiicicccg-teeeceeeeecceccecceccecececggfrgrcgfge-tgug-tugr/ftm/gggggft/m/meeeeumeeeutttuc/ftymyyyttruefgctrmy-itr-imtiy//mri-mi-tymy/-/-rirmtt-/-r/rm--yymrr/--r/rri-yimmtmm/ym/ty/trr/t/ym-my--r/ymmmt-mm/mrmr-/mrymmmry//rr-mrmr-//-/r-yy-///mrymmm--yy/rimry///yr/ym/my-///-tmmryy-/ym///mm/mryymmmmmyt-myr//m-m/mymmm-rrmr-r-rirr-r--r-rrmmry/r-r--tr//-mm--/rim-ymr/-m//m/mmm-y/rm-r-/-mmry/rmrr//-yrmmr/m-rmr-m-rrm/mmmrm-mrr-mrr-m//m-ryrm-/rmrymmr//ry//r/ymyy-/ym/m//mmmmm-rr-y-/y/mrm/--mry-m/y--m-/m/-/m-r/r-mmm/-rm--/ym/-//--ym-m--my-rmmm/my/m/r//--myrmyrm-ymmm-m-mm/m-m-ymm/yy//-m-r--/m-ym/mr--//m----ymmry-y//r-y-m-/mym/m---rr--/m/r-mr-/m--m/----myym//rr-/m/-yy//try/m-m-ttyryrttr-ttr-/ttr-//r/-/r///tmtiir//mmmmitimmmmimrtrrym/itym/itym/itym/itym/itym/it///-titi/-/-/-i/i/mtmty/mttyytit/-/--m/fgci/tm--yrrrrm/ymmr-m/-/m/---rr/mr/r-/mmym-myyyymmmmyymr---mmr-yyyyyr/rmrr-/mr/-/ym---/-m-mymmy/yy-myryym/my-y-yym/y/m//-y-y/mmmyy-ymr/r-m//y//ym/-ymymr----myyyyyy-//rm-/--y-my//m//r/ymy//yymymmmmyymmm--ri-imy-mymmy/yyy//m-mymy-ymmrmyyr//-yy-y-m/mmy-i-mm/y/m/-r/m-///m-ymmm///ymmyyymm-ym---y/mmy--riyyr--/m/-//r/m-///mym--m/-y//-///y-mmy-/--m//y///-i-m-mmmmm--/mm/-m-i-yr/ym/mmym-/-///y/my/y/m//-r/-m-/-mm//y/-//mmy//-y/m/--m/---/--/y-ym/m/m/ymy/y-myrmyyyy-y-m-ymmyyy-i-yi/mryr----mi/-mm/mryyr-/mym-/--r-rm//-////m-mmyi-my/my/-m///m/yy-yy-/m/mmmmmmmrm/m--mymmryyy/-ymy//y//yy/rr-rm///m/--mrm-ri-iir-yy/yymmyy-rr/rtttrymr/-rrmi/y-//-ritrit-mr-m-imrir--imrir-y-r-iirri-i-i-i-i-ritmmriiitir-/-i--ii----r--ritiiir/r///i/rymyryrrmmrmymmii-mmryr-iyyyti-mmrr-r--rr-ryry-r-r-rirrrryyyy/r/rm--yr-r-r-r-ri-rirrrirtttttttisicsstscosstoticctitrsiocticsioiritcriittcooooosrooisiiosssroitritrtscooitotrimrrccrrrrtttirocisiroicoitoitocstmimorioirrcirmictortirrircsooitctiiorttsrsrtctorrtocsotoirttticiricottsimccrrttsrrcrtoocstrtcomroociiitrroccsitiitorrrcctioioitoctictitrtsotsttstitsococrsirtitosrortotcisscirtoricotrccsicctitssicootcotooorsirrrcrriitrotttcsiosictcotortocioscsoiroscrsicitctcsctsrocmtcciorotcitriotrrostrsistsscroisscctcttcorsooisictittssrrrioitossioorrctiotttirrrroccttricrcsttrrsorttotrirottticctsrocciorcrriioorritscirriscctrttscscsrotroistircicrricitsroosccrocsiotstttriirrioicioocsistrstctttcptssisrsttsotcoccictssrcccsccototsissccorccrsoitstitcrrissrciriitctttcitrtrttirottoicorrrsotstrsciioitssccsrctostsristsirsccorrststtrtttosrcrioiotrtirrrcocrocsirstcttrttrrccstcstrcscsrrtcocrocsirsttottoiirsoiosirrccsoocrrststsoircctrciioioissisitriitriitrorissicisctsicrrrrrirocrrrtrrtsirrccoooirttrisscissrptpcssrsroiorcrrtocctscrircccsrtscsstoccrtrccticcrcstrtsstrstosstcicssscsstoccrsrcoiscrcopiooptopsorsprtcsiisioctotrpsciptriotstiopostroritcrioorsicpoprprritrctroptorotopiptiippoorrpiooscioosscritropiopsrsitsoccocptcrrcsitctssiirprptpprooioprstrptcppporrrpiosrrpcotpipsorrstsscttpssroiooprproroioottioiiortiistottciisstcctcocsrsrssrsrrsrpisspstoorsrspssorricrprsccttopircrtsocsstrisrssrosicoiisrpttsrpppotocscsttpprttocsiirctissocirotirsstorscpcpospotiororsprocioittotppsttptscprcoiotoppissioicpsoocrriitpssroiccciispirtrssptspppotiocscticsipprsccctccrirprrippopcottcpccsipstrrrsrttprstotttotrctictorrprstrsoocciopiccpcrtocorrrsricrccprrrircpcrsptocrsrssoriotstoorcicttosisrrsotosrcoioootoiiriiistprstooopciispirtrspsppsopsisrpsrrrsttoococoptrcsippsorpstpippsotttcirrptpprccrtcrtcpopprptspotosposstoocprspoosiitcicitirioirrsttccrocictpcpcpsppopootsioirrotcocsstoppiiccoososrsissrittsstccrstissptcsitrrsssrscscoiitocppociitciioosttcssctiicpicoosssiicoorocoioiicosipssscpsoostiicoospsssptiopsiiisscoooiriipttosioioirssciitostiitciptsicoosrtsrsrosssscpsostoctppsrrtcistscocioississctcscpsostpiittscptccsssitcstotpsipsptscsppttppsiiciotcoorscisioitoccstisssopttcoosoosotssittttcicccorpssisstittpsiicsstcsiooossppcscctospocoppooioppcocrssctssitoroosisrrossrrsotciiootiirroocrrotiicciciroioppsstposprcortttopiprtctpitsstocssccpstoittctsctssisiccctpiiistcttrrriooiprsicscooiiccoiipoitcocpscrcitciptsrrscroiroiciipcttoioirsstcoisscstostiitcipscsitoctppsrroticcrtsrsstrscrtooiotitpsttocccoriircrrriprospprpocpsprccrsopisicioirrpscosrsrpicrpritpiiitiitstrrtottpsiorircrprprorooocororcosirocripippioosspociiiciorrororpcissioocorriipoicsrcriopiisrrrssrrrorcoposoiipcpriipiosssipcrriiiiiioopsoiiosorcioiocorciisicccoccccipicocccisootctirtocposctirctocpppcpssiccccccocsocicocrrrirtocccposccscrrcirtitootciiscpcpttucrtsrppcmpmmttcmmccrrmmuiom.uiirtoriimmmor..i.uiitccctc.rcmmtrrurcctttcccrutmiruuucrrrcttucrrrcptrrrmcmccpprhhmtmmihmmpprtmsshhmrtmorhrmmmotmrtmrrormmitmiirirritommmomtirtoriiooimimirrmiimmiiiir.mmiorimmrimrrrmiioiromirmoitmimri.rmitoimooimoooirrtimrmrmimrrmoiu.rirrtttmtttu.iiiiirttrctturmumrttutt..itttt.ccuimcitturt.imiircmm.pcm..pp.mimmicppccmmcmm..cmimmm.cpmicmmcc.c....rccccccccrccccccr.rccciiicurpm.t.ri.iu.crr..iuc.c.rr..imimiic.rmroitmrcmtim.mtmp.c..tum.urpuip.pmp.puprrpmp.rrmp.piittirrtrtrttttturtuctcimu.cmmi.pucipimpiiumm..cu.p.imprmmp.imprmrcrcpcpummprmmcicrmpipmi.m.m.iprpicpcicicpipi.i.cimm.pi.cicmpimpcpm.ccm.c..cc.cccccmmc.cp...cruuuurrprummrmrmcm.prprrrmrrttm.picumi.mmm.mpipppc.ppcim.cicpmm.ciccrpipm..c.cccc.ircciir.riri.r.c.cp.ucu..cm.ir.urmrr.prpi.uippcuir..crpippup..r.miu.rrrcrtmirrcuumrurmrcrm.pmpcpc.mmmiipc.pm.m..ppmmpcppmripipipiimupmuprpii.i.mi..imi.mi.imi.imrr.r..pcc.mrr..imcr.i.ium..cpm..c.m.mi.mmppumi.irmcmii.pciimum.ic.i..mrrrmcri.ip.iiiiipppppmimimpimpcimcp.ipi.m.mmpmimmrmripiiuppiupuiirrpipi.icimmcirummc.ipimcrmc.rrii.mrip.cicciiiiipiupuipccumrcmimmiimrpprciippmrr.imprcriiip.cicciiiipmciipccumrcipcmimmpc..pimpii.cciicmm.ppmcuiri.rpr.rp..rcmipcim.pu.cuppp.iipripcmpprppmmmp.mmi.rricimipmccm.i.pppp.imp.icuiim.icccmmpipmmimimrmmi.ccmp.imii.ii.cc.c.iciiipriri.i.rmppmppprprcrcmmcmic.c.r.r.piiiipimimuuumcuccicipm.ipmiim.imimmmu.ppmmpiicm..mpm.mmiirrcmp.cmmcmpi.imiciipiiicc..u.mm..m.mpp.irprmii..pip..ppipmp.uici.cm.ppcii..icppmii.ip.ippicmiucpicmipt.icmmrm.icrrmiiuimpcmmm.cripiciuiippii.uic.cuippmcprirmu.c.mcpi.mittmrrm.prpmmmirmi.mmm.pcpip.mpmrrirmp.pcpcpmi.mrpimci.ttmpppc.c.pmmimimcmmrmmm.mptrimicmimppii.mp.p.pc.pmiiiimm.rc.c.mmi.rpmmicmmpipmicicmptmcm.m.ppmccmip..r.i.cipicipicmiccmimm.u.m.mimipmppp.i.p.iic..mcrrmmmmmmimimitpimipcic.icm.muuiurpmimm..srr..ir....m...m.i.rtpirmuirrs.mii.ipprripmrttirmuiritururmpcrtrppciuirrpmcurcrrprrpcmprpccrpcrprppprimpccrcrpcuccrrpmrpmicurrpmucppriripmucitptuppitmcpupiirccrrpruppiupuimcipirputppr.t.umru..u.uiccicmim.cmccmr..cmircs.srccscm..rsrms...crr.rr..r.cirm.prrtuumcpmimpmcimppmimrrirmmpmmrrmrrm.mrumpmrmpuuruuicrcpirrrrm.ppmmpmmrrpmrpmrmmppmrm.mrumumuumprrp.upuumim.mcrrcuuutuiutuurrcrutuctprriprcupmuipmmupcmuucccucucucuuucpiicmuuccriuuupiuiuurimprrprrumpcucrc.cccuuccuucccpmumprcmcmruiuiricccrcuuiuiuuuurrcrutuctpricccrcuuiururrcuuiccccuiuicmmuuucuucircuc.cmccuuuuuuuicccucuurmccmmmumpmcpcummmuicumpurrmcrrpppumpprupuuucrpmmcmpricmcupucupcmuipppimuurpprmpuuririicmr.iumrcuprcmucrmricrrcmmrtrmmrturrttrtt.uttimumcrcrpic.mmurtutttmi.smsmruuutttupihiihccccccccccccccupccrmmmrpm.p.cuppm..mphtmttpihcippmttpccmtttuptttuptccmpttmptttuptccmtttcctttuptttupihcipccccccuiuphccuppihcicipccccccciiprrprpihirtprh.pcputpp.r.p..ptrtrhrrpppppp.rrhppihhhpiiiirriirrpc.cppppr.iit.mmcppcutcmircmmm.cmm.i.rmh.mh.mmprppmmmmpppttipipiprrm.pirhmmtmmprimhmrsmtutpummm...m.tccu.rr..prsrpsi.rppprp.prrrhr.prrrhrhtrphprhhppppprprthtpr.pphrhpprppprppppprppprppprpppppprpp.r.sss.ssrsprpspismittc..p.r.ssscismit.......ss........st.tt.sspp.sprrss.mricismic....spsmrpisicimittc.t.pttc.pmmmt.riimiirripr.i.imiirrr.srp..rr.rprimii.i.ii.r..im..i..i.mi.pim.rp.misrr.riii.ii.ii.siiti.i..rrp.tp...r.iimir.iii..rprirriirii.rri.rrprriripimtririiiitiir.t.tsmrr.tt..rmrtr.rtip..iiri...trtmsr..mrrrrrm.rtsmst.srtsrtsrmsriis.pr.rsspspsps.ppps.sssrirrpi..srrii.ppipp.p.ripi.rsppimppiprir.rs...piippp..rt.pmmppt.pmmp.mmcmprsr.psmcumsrsp.mmmpmsrrrs.ii..i.itpp.ts..pmr..mmpmpp.pcmt.icrhmtips.pmrsmc.mtcrsmcm.csc.m..rcccmmctrtctrt.ttttrt.m..ummrtc.rttsmucc.mmutuctrtstturuchtmtsmcccctm.mmttc.tmt.mm.ohmmm.ttmhomooh.ffmttfft...tftf.toprutspo-.stopo.ppttpp-ttrt-r--po:icirttmstmpstthoustrt.t:iprt:rrtiiirc.c.tsrtts:pppmp:pprtsmrttstsooioit.:oospsbffh.hr:uu-.ou-aurgcncccrtcccrtrrgt-mccrth-cry-mmgychogagt-hogscgoyhoascgoayhogtgtgtath-rtrtrcygmnsiunsiunsiunsiummiucghghcrbocoy-mgycuhogscgoyhoagatt-o-gccrcncrrrrcrrrrrtt-o-gccrcncrrrrcrrrrrtt-o-gccrcncrrrrcrrrrrcch-cccmgymootgncryg-mnsiuucghcrbocoy-mgycugtogccauuo-gao-guhogccatoghcoagcrgtghtogcru/accrgmgysryryg-mnsiuuccrbocoy-mgycugtoscu/aboogogoggoru/chgo///c/h/hrcrrrh/h/hrcrr/crcrcrcrgccg//orcrccccc/cccr//grcrrcgoc/chrcgcrcccccrccch/cc/chcg//rocgo/rrcr//c//gr/cccrch//crrgocc//chhhcccccc/cgc/ccgo/hhrr//crr/r/rrrcrcrrhhrcccc/ccc/c/crhc/cgcg//rcrocohcgghccrcocohcrrhocch/ogroggrggh/rrhr/hhrrh//rhh//rhrorgohrghrhuh//auhrghusniyorg-oyoo-oys-gucortccrthrycrumrmycroo-gffmu/--moi/si/cfcu--oifm/fm/ooeoffmiim/immfc/oitemc/f////cefecieciecieciicecci/teoffcgicigocgccygtyytytyi/--if/sccfuio/uefcuogitgicoiocccccigtiggcotogigucgocucgocoouiuguuciocooccoooctoogggccogcogggoooottgtgutuogootttouttttttttctttctoccutigooggtugocttgcgcccuutccggoggotg-uiiigcgtoigoooccigoguucgtuucgucoiooougoogogtugogococoooooigoguctggcocooiouoccicciuggoioucoicugogoccoiicoiciicocgiit-utcggcccccgicggioggouoggotu-uugoiigogocigoccuugocgoo-otticoticctictoticoticoticoticotiggticogouiouguucctggogtgiggggogtoo-ooiguutututgtguugutuguctcgcgctgcgtugccttuctuctgtgcuuoogcouutgtugcutcoiigutugcuotcoiigutugcuotugucucogcccctoioiuiiuoiuiuoicggoc/cco/gcoooect/g/i/cccigi/iug/goocgociggoguc/ciegugeog-tcccgogoegtigg/ocggccccecgogoegtigg/sgcggcccececgogoegtigg/gccegogoss-tcceocgcoe/i/ciogc/gocgoegtigg/ocigicocccocgeciggstet-gegcioccooooiiiiicicccg-teeeceeeeecceccecceccecececggfrgrcgfge-tgug-tugr/ftm/gggggft/m/meeeeumeeeutttuc/ftymyyyttruefgctrmy-itr-imtiy//mri-mi-tymy/-/-rirmtt-/-r/rm--yymrr/--r/rri-yimmtmm/ym/ty/trr/t/ym-my--r/ymmmt-mm/y-yy----m-mm/y/m/t/rmrymmmry////y////rmym/rm/-/-yy-/-/rmrrym/-rm/////ry/mm-/my-///-tmmy--m/ym-mm/myymmmmmyt-myr//m-m/mymmm-rrmr-mrr-m//rt---mm/ymy/r-mm-mmmmmmrry/mrmr-m-rrm/mmmrm-mrr-/rmrym/--mrm/ym-ryymr/-m//m///r/ymyy-/ym/m//mmmm/m//-/m/-rmm/m-r/r-y-/y/mrry-m/y-//--mymr-m/ymmm-m--my-rmmm/my/m/r//--myrmyrm-ymmm-m-/m--mr-m-ymmm--y--m-r--/m-ym/mr--//m----y--mmm-y//m-y-m-/mym/m---rr--/m/r-mr-/m--mr/-r/mry/m/m/yrr-/rr-/m-m-yryrtttyryrttr-/tr-ttr-/tr-//r-/r///tmtiir//mmmmitimmmmimrtrrym/itym/itym/itym/itym/itym/it///-titi/-/-/-i/i/mtmty/mttyytit/-/--m/fgci/tm-/rmymmr//yym/mr/r-/mmym--/-/-r---//mmyyy/r/m-r/-r-/m-mr/y/mr-y/--y-mm-mr/-/ym---/-yymy-m/r/m-yy/--/--m-/ymyymmmm/yy-yy-mm---mrmm--mr/r-//y//ym/-ymyr--ry-r-/mrm/-mmymmyyyymmmmyymmm---my-ymymymymmy-ym-/-/--mmymmm//yymyymmmym--yyy/my/my-ymmm///yyymm-ym---y/mmy--riyyr--/m/-//r/m-///myyymy--m-m/-yy-----yyy/mmyyy/r//m//m-iyym-ymmmymmmy-/m-/y/ym/yy//y//ym//-/-mrmr/m/----/-/m///---/--y/r/r-ym/m/m/ymy/y-myrmyy--mm/////yy/mryr----mi/-mmyyr-/mym-/--r-rm//////-m-mmyi-my/my/-m///m/yy-yy-/m/mmmmmmmrm/m--mymmryyy/-ymy//y//yy/rr-rm///m/--mrm-ri-iir-yy/yymmyy-rr/rtttrymr/-rrmi/y-//-mmrritrit-mr-m-imrir--imriit-mr-m-imrir-y-r-iirri-i-i-i-i-ritmmriiitir-/-i--ii----r--ritiiir/r///i/rymyryrrmmrmymmii-mmryr-iyyyti-mmrr-r--rr-ryry-r-r-rirrrryyyyr-r-ri-rirrrir/i--iytmr

**Comment by erricgunawan** [comment]
I got a report on 3317478-zen which looked similar to this.

They're using:

- Firefox Daylight 80.1.3, Moto g5 Plus phone, Android 8.1.0
- Chrome 85.0.4183.81, Moto g5 Plus phone, Android 8.1.0

and they had this problem on Beta: https://staging.simplenote.com/

It works for them on https://app.simplenote.com/

Please let me know if it's the same case or this report should go elsewhere.

Screenshots:

![Screenshot_20200916-054552](https://user-images.githubusercontent.com/1813857/93403763-a38cc400-f8b2-11ea-9794-2fa7c867be0f.png)

![Screenshot_20200916-051326](https://user-images.githubusercontent.com/1813857/93403788-aa1b3b80-f8b2-11ea-9a2a-d2d8f6dfced9.png)

**Comment by dmsnell** [comment]
@erricgunawan this looks like a separate issue; maybe we can create a new issue for it? looks like maybe something on the mobile browser is creating multiple cursors and then edits apply twice.

@belcherj @codebykat I wonder if we can disable multiple cursors

**Comment by erricgunawan** [comment]
Thanks for looking @dmsnell ! I created a new issue here: #2341
