### ISSUE TITLE
Print only works once per session

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2031]
### Expected

I expect to be able to print notes as many times as I want.

### Observed

I can only print once each time I open the app. After that, the print dialog seems to work but nothing happens when I confirm I want to print. (This is the same for both printing and printing to a PDF.) I have to close/reopen the app for print to work again.

This only seems to happen in the packaged apps; the web app prints every time as expected.

### Reproduced

1. Open the app and select a note.
2. Select File > Print or use the keyboard shortcut.
3. When the print dialog comes up, confirm you want to print the note.
4. Notice that the note is printed (or a PDF is created if you print to PDF).
5. Repeat steps 2-3 and notice that nothing happens.

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.16.0-beta1
Macbook Pro|macOS|10.15.4|1.16.0-beta1

**Comment by dmsnell** [comment]
This is a known but unreported issue - thanks for reporting it @rachelmcr 

Sadly this is an issue with Electron, something I found just a couple weeks ago.
https://github.com/electron/electron/issues/14705
https://github.com/electron/electron/issues/21195

Not sure how we're going to work around this.

**Comment by rachelmcr** [comment]
Ah, thanks for sharing those links! I see there's a fix for this in Electron 8.0 but it was also released in [v7.1.11](https://github.com/electron/electron/releases/tag/v7.1.11) (we're on 7.1.7 now) so hopefully we can update Electron to resolve this.
