### ISSUE TITLE
Wrong note in note list is selected after trash/restore/delete forever

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2032]
### Expected

* Selects note above recently-trashed note
* Selects note above recently-restored note in trash view
* Selects note above recently-deleted-forever note in trash view

I confirmed that this behavior works as expected in the 1.15.1 release.

### Observed

In each case, the app selects the note _below_ the recently trashed/restored/deleted note.

### Reproduced

1. In the All Notes list, trash a note and notice that the note below it in the note list is now selected.
2. In the Trash list, restore a note and notice that the note below it in the note list is now selected.
3. In the Trash list, delete a note forever and notice that the note below it in the note list is now selected.

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.16.0-beta1
Macbook Pro|macOS|10.15.4|1.16.0-beta1

**Comment by rachelmcr** [comment]
@codebykat could this be a side effect of the change in https://github.com/Automattic/simplenote-electron/pull/1995 (since the note list behavior is changed)?

**Comment by codebykat** [comment]
Ooh nice find @rachelmcr. This was an intentional change (@dmsnell and I made a judgement call about it). It means keeping the same selected note index which "felt" a little smoother to us. AKA the position of the highlighted note doesn't move. Unless there's a strong reason to prefer the old behavior, can we update the testing checklist to match?

**Comment by rachelmcr** [comment]
Ah, makes sense! The behavior felt fine to me (I agree that keeping the same selected note index feels smooth) and I only noticed it because it didn't match the testing checklist. I opened https://github.com/Automattic/simplenote-electron/pull/2034 to update the checklist. Thanks!
