### ISSUE TITLE
markdown select tooltop thing

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#2033]
Please add this thing:
![image](https://user-images.githubusercontent.com/21956756/80070571-6dd1f200-8543-11ea-866a-32201c37f6c6.png)

just add it please.

How it works: you select some text and this pops up. when you click on one of the buttons, the text changes respectively to markdown: 
![image](https://user-images.githubusercontent.com/21956756/80070481-4c710600-8543-11ea-9a02-13a2b29023b1.png)

Note: this is originally from discord but if you have any questions about it feel free to comment

**Comment by codebykat** [comment]
Thanks, I'm adding this to our feature requests (tracked internally - we only leave issues open here if they are being actively worked on). If we do anything along those lines I think it would be more like this as a first step: https://github.com/Automattic/simplenote-electron/issues/1113
