### ISSUE TITLE
Cursor gets hidden at bottom of window when typing

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2035]
When adding text to a long note, when the cursor first goes to a new line, it is hidden beneath the tag bar at first. It only scrolls when the second character is typed.

### Expected
Editor div should scroll as necessary to keep the cursor visible.

### Observed
![simplenote](https://user-images.githubusercontent.com/52152/80132931-484be500-8551-11ea-96fe-8e6393731a8b.gif)

### Reproduced
Reproduced in Firefox/OSX, Firefox/Linux, Chrome/OSX

**Comment by leogermani** [comment]
Just a comment to say that I tested this on the new Beta and it seems to be fixed! :)
