### ISSUE TITLE
Cpu 100% for many seconds at start. 

### ISSUE THREAD

**Issue by bruno-labs** [Automattic/simplenote-electron#2055]
When starting, the program in linux versions consumes 100% cpu for 1 minute.

**Comment by dmsnell** [comment]
@bruno-labs do you happen to know if that’s account-specific? If you create a new account does it still consume the CPU when opening the app?

**Comment by codebykat** [comment]
Closing as stale - we can reopen if we get any other reports or further details that would help us track it down.
