### ISSUE TITLE
Translate To Persian

### ISSUE THREAD

**Issue by desperanish** [Automattic/simplenote-electron#2056]
hello everyone
How can I Help You Translate This Great App To Persian?

**Comment by dmsnell** [comment]
Hi @desperanish - we don't have translation support yet in the desktop version of the app so unfortunately there's not much to do to help out at this point. It's on our radar but we've been busy fixing some internal issues with the app lately.

Stay in touch though - whenever we do add translation support we'll announce it and then you might be able to contribute if the Persian support is lacking 😄

**Comment by desperanish** [comment]
I meant your Android app

**Comment by desperanish** [comment]
I meant your Android app

**Comment by dmsnell** [comment]
Ah okay - @desperanish we use GlotPress for translations in the Android repository. You can contribute at https://translate.wordpress.com/projects/simplenote%2Fandroid/

The Persian translations (currently none) are at https://translate.wordpress.com/projects/simplenote%2Fandroid/fa/default/
