### ISSUE TITLE
Format markdown text as we write.

### ISSUE THREAD

**Issue by pspatel011** [Automattic/simplenote-electron#2065]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
***(Required)*** What is the feature you are requesting?  Add a concise description of the feature being requested.
I found out this feature on Thomas Frank video https://www.youtube.com/watch?v=ay2GvqVH4SM
This feature is in bear note taking app but it is really useful in formating the text.

### Why
***(Required)*** Why are you requesting this feature?  Add a concise description of the problem this feature solves.
The feature is like this when we write markdown language it is instantly formated. it is really helped in formating and maintaining app without cross clicking the preview button lot of times.
### How
***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate how the feature could be done.
You can watch it here : https://youtu.be/ay2GvqVH4SM?t=267

**Comment by dmsnell** [comment]
Hi @pspatel011. We already have this on our wish list so I'm going to close this issue. It's been something we've explored and hope to someday incorporate into the app, but we don't have a timeline for it. Thanks for the request!
