### ISSUE TITLE
Clear note history

### ISSUE THREAD

**Issue by lucamosca1** [Automattic/simplenote-electron#2069]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
A way to clear note history, not important if clear ALL history or of a specific note

### Why
Could happen that I save a password or personal information. I don't want them to be retrivable by turning back revisions

### How
I have no idea where the history is stored, can't help, sorry

**Comment by dmsnell** [comment]
Hi @lucamosca1. We won't be implementing a _clear history_ button but you can accomplish this by copying the content of one note into a new one - that will "duplicate" the note but without any previous revisions.

Thanks for writing in. If you need further help please don't hesitate to reach out to us at support@simplenote.com
