### ISSUE TITLE
Exported notes in zip password-protected (as option)

### ISSUE THREAD

**Issue by lucamosca1** [Automattic/simplenote-electron#2070]
### What
A way to export my notes in a password protected zip file

### Why
I can retrieve easily user notes, if I have accesso to zip file (e.g. I stole a notebook and user have a backup somewhere)

### How
Flag option for password

**Comment by dmsnell** [comment]
Hello @lucamosca1 - thanks for this request too! I don't know if we'll implement this but I can add the idea to our internal feature request list. It's not likely to come soon even if we do.

In the meantime you might look for resources on how to add a password to a zip file - not sure if you're using Windows, Linux, macOS, or something else, but this kind of security can be added after exporting.

You might also consider saving to an encrypted drive or partition if you are worried about the backup security. For the time being we're allowing the operating system or end-user make the decision on how to secure the exported files.
