### ISSUE TITLE
Asciidoc / Asciidoctor

### ISSUE THREAD

**Issue by jwillikers** [Automattic/simplenote-electron#2071]
### What

The ability to take notes in Markdown is extremely helpful and convenient.
I prefer [AsciiDoc](http://asciidoc.org/) to Markdown as it provides more powerful formatting with a similar syntax.
The  [Asciidoctor](https://asciidoctor.org/) project is a toolchain for AsciiDoc, which is [used on Github](https://asciidoctor.org/news/tag/github/) to render AsciiDoc files such as README's.
I like to write my Github README's in AsciiDoc, too.

### Why

Markdown formatting has several issues which are solved in Asciidoc.
I've copied some points from [a comparison on the Asciidoctor web page](https://asciidoctor.org/docs/asciidoc-vs-markdown/) below.
The italics are my own, to emphasize one of my favorite AsciiDoc features.

You can see that AsciiDoc has the following advantages over Markdown:

- AsciiDoc uses the same number of markup characters or less when compared to Markdown in nearly all cases.
- AsciiDoc uses a consistent formatting scheme (i.e., it has consistent patterns).
- _AsciiDoc can handle all permutations of nested inline (and block) formatting, whereas Markdown often falls down._
- AsciiDoc handles cases that Markdown doesn’t, such as a proper approach to inner-word markup, source code blocks and block-level images.

### How

I would think that it would be done the exact same way as Markdown, with each note having a way to enable AsciiDoc instead of Markdown.

**Comment by dmsnell** [comment]
Hi @jwillikers - it's extremely unlikely that we would switch from Markdown to AsciiDoc, though it won't take much to convince me of Markdown's shortcomings - we deal with that somewhat constantly here especially as it relates to multi-device support.

If you want to play with this you can fork the repo and look in `note-detail/render-to-node.ts` where the preview view is generated. You could replace `showdown` with the AsciiDoc renderer.

**Comment by jwillikers** [comment]
@dmsnell Thanks for the response and the advice! Just to clarify, I don't mean to switch entirely, but as something to consider supporting in tandem with Markdown.  Love the project, by the way 💕

**Comment by dmsnell** [comment]
of course!

> I don't mean to switch entirely, but as something to consider supporting in tandem with Markdown

we try hard to be very cautious about what we introduce since the purpose of Simplenote is to remain as true and simple to plain-text note taking as we can keep it. the addition of Markdown came as a compromise since it became somewhat ubiquitous.

to that end I'm going to close this request and add it to our internal tracker. hope you have a nice weekend!

**Comment by alliter8** [comment]
I literally cannot WAIT for this feature! I use Asciidoc all day every day in all of my projects, and this will be a godsend. I hope we can see it soon. (FYI: Dan Allen (Asciidoctor creator/maintainer/developer) is very approachable and appears extremely open to discussing new integrations/projects. He is easily reached on [GitHub](https://github.com/mojavelinux) or on the [Asciidoctor Discussion forums](https://discuss.asciidoctor.org/).)
