### ISSUE TITLE
Korean Input: Floating input selector and delayed entry

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#2074]
When entering Korean text an IME box appears in the top-left corner of Windows and introduces an odd delay when typing.

This box should appear inline and work like normal IME entry.

Reported as introduced in v1.15.0, confirmed working properly in 1.14.0

## Reported in
 - #2866206-zen

**Comment by gwang-kim** [comment]
This issues are not resolved in v2.21.0. Please fix it :(
