### ISSUE TITLE
Keyboard shortcuts don't respect keyboard layout

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2091]
We had a report from someone using Dvorak that the shortcuts don't work properly.

2937392-zen:

> I'm on a PC running Windows 10. I'm using a Dvorak keyboard layout that I've set in the keyboard settings in the language options in Windows.
> Unfortunately, when I press ctrl-z in order to undo some text edits (just using basic OS/browser-level text field functionality), the keyboard shortcuts info popup shows up, as if I had pressed ctrl-/. I believe this is because of the Dvorak keyboard mapping I'm using - the '/' key on my keyboard is mapped to z because of Dvorak.
> My current workaround is to press the escape key to get rid of the popup after every time I do ctrl-z, which is not a great user experience.

**Comment by mmaluff** [comment]
This is also a problem when using, e.g., a Spanish keyboard. The problem is with using `KeyboardEvent.code`, which doesn't respect keyboard layouts. It might just be a matter of switching to `KeyboardEvent.key`, which does.

**Comment by codebykat** [comment]
We switched from `code` to `key` in #2334. From a brief test with Dvorak this seems to have fixed the issue. Please let us know if there are still any problems with Dvorak or non-English keyboards!

**Comment by CameronBeeler** [comment]
I'm using Evernote with Electron and my DVORAK does not map to most of the function options.
I do get ⌘-B, but most other functions do not work in DVORAK at all.  ⌘-I does not italicize.  ⌘-U does not underline, etc.  Is there a plan to
