### ISSUE TITLE
Can't Sign In with Google Account

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-electron#2094]
### Expected

I should be able to log in through the Electron app using my Google Account when I select the option to log in using my WordPress.com account.

### Observed

I receive a couldn't sign you in error when I try logging in via Google Account due to the in app browser not being secure. 

### Reproduced

> 1. Go to the Electron app (this only reproduces in the app)
> 2. Click on Sign In with WordPress.com
> 3. Select the option to Continue with Google.
> 4. Type in your Gmail address.
> 3. See error, couldn't sign you in. `This browser or app may not be secure. Learn more. Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.`

<img width="599" alt="Image 2020-05-16 at 6 32 02 am" src="https://user-images.githubusercontent.com/10325627/82111757-34099b00-973f-11ea-9ab9-390e7d3d1fb8.png">

Make|Model|OS Version|App Version
-|-|-|-
Apple|Macbook Pro 130inch, 2019|MacOS 10.15.3|1.16.0 Electron app

Reported in 2960957-zen in Ubuntu.

**Comment by codebykat** [comment]
@rezzap We don't have any other reports of this, can you re-open if it's still an issue? Thanks :)

**Comment by codebykat** [comment]
Oh even better, I suspect this would be fixed by the changes to login we did for the Windows app store. #2191
