### ISSUE TITLE
Use bot account to create releases

### ISSUE THREAD

**Issue by mokagio** [Automattic/simplenote-electron#2099]
We generate the releases on GitHub using @belcherj's account.

<img width="862" alt="Screen Shot 2020-05-18 at 3 08 59 pm" src="https://user-images.githubusercontent.com/1218433/82179586-0892d600-9922-11ea-8ea8-e82901ef3fdc.png">

It's not a bit deal, but I find it misleading. I'd prefer to see the release generated by a bot account, like we do for example in [WordPress iOS](https://github.com/wordpress-mobile/WordPress-iOS/releases)

<img width="1110" alt="Screen Shot 2020-05-18 at 4 15 07 pm" src="https://user-images.githubusercontent.com/1218433/82179919-cfa73100-9922-11ea-838e-394e5febd33b.png">

**Comment by belcherj** [comment]
I have an account created to do this. Just need to get it done.

**Comment by mokagio** [comment]
I invited @wpmobilebot to be a collaborator with "Write" access to the repo. 

The next step is to use its API token in CI.

**Comment by mokagio** [comment]
CI now uses @wpmobilebot's token for the uploads 

![image](https://user-images.githubusercontent.com/1218433/110742909-4aaf4e80-828b-11eb-96fc-84509ca9ef5b.png)
