### ISSUE TITLE
Shortcuts: New keyboard shortcut for new note has conflicts / wrong tooltip on icon

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2106]
### Expected

As of https://github.com/Automattic/simplenote-electron/pull/2080 I expect the keyboard shortcut for creating a new note to be `ctrl/cmd + shift + i` (changed from `ctrl/cmd + shift + n`).

### Observed

The keyboard shortcut for the debugging console in Windows (in the packaged app) is also mapped to `ctrl + shift + i`. That leads to unexpected behavior:

1. I can't open the debugging console with the keyboard shortcut (it creates a new note instead).
2. When the debugging console is open, the keyboard shortcut has varying behavior depending on what has focus: if the console has focus, the shortcut closes the console; if the rest of the app has focus, the shortcut creates a new note.

I also noticed that when I hover over the new note icon in the app I still see the old keyboard shortcut on the tooltip (`ctrl + shift + n`).

### Reproduced

1. Open the Windows app.
2. Use the keyboard shortcut `ctrl + shift + i` and notice that a new note is created.
3. Go to Help > Advanced > Debugging Console and notice it has the same keyboard shortcut. Open the console.
4. Click in the app to focus on something other than the console, and type `ctrl + shift + i`. Notice that a new note is created.
5. Click in the console and type `ctrl + shift + i`. Notice that the console closes.

![VirtualBox_MSEdge - Win10_19_05_2020_15_32_44](https://user-images.githubusercontent.com/8658164/82339734-46593280-99e6-11ea-8448-86464d014fd9.png)
![VirtualBox_MSEdge - Win10_19_05_2020_15_32_09](https://user-images.githubusercontent.com/8658164/82339737-478a5f80-99e6-11ea-9094-edc16be6e103.png)

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.17.0-beta1

cc @belcherj

**Comment by belcherj** [comment]
I think I am okay with this.  Most people should not be using the console anyways. The number of hotkeys available to us is quite small. Closing as won't fix unless we have massive user reports that this is more of an issue than I'm aware of.

**Comment by rachelmcr** [comment]
What do you think of removing the console shortcut from the menu, in that case (since it doesn't work to open the console)?

And would you like me to open a separate issue about the new note icon tooltip? That does need a fix but I know I combined it in this report and it's a different thing.

**Comment by rachelmcr** [comment]
Ah, I see that the console shortcut is built into Electron, so I can understand just leaving it as-is since it's not commonly used anyway.

I'll open a PR to update the shortcut tooltips.

**Comment by belcherj** [comment]
Thank you!
