### ISSUE TITLE
Audit use of draft-js and incorporate API updates

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#2117]
Some small things I noticed which _might_ be problematic need some work. A full audit of our API usage for draft-js is probably warranted since we've performed multiple updates without changing any code.

 - `onTab` and `onReturn` type handlers - there's some deprecation warning about them
 - are we adding two paste handlers? check the [Race Conditions docs](https://draftjs.org/docs/advanced-topics-editorstate-race-conditions)
 - need to prepare and merge #1205 and get rid of the funky `this.key++` business

**Comment by belcherj** [comment]
https://github.com/Automattic/simplenote-electron/issues/501

**Comment by codebykat** [comment]
Closing this because #2148
