### ISSUE TITLE
CTRL+DELETE deletes the note, instead of the word following the cursor

### ISSUE THREAD

**Issue by frkunze** [Automattic/simplenote-electron#2118]
### Expected
When pressing CTRL+DELETE inside the note editor, I would expect the word following the cursor to be deleted. (Analog behavior of CTRL-BACKSPACE, which deletes the word before the preceding the cursor.)

### Observed
The note is deleted.

### Additional Note
Maybe this was intended as a feature. But it causes me frustration, as I use CTRL+DELETE quite often automatically when typing/correcting a text. The I always need to go to the trash and restore the note.

### Reproduced
Make|Model|OS Version|App Version
-|-|-|-
SYSTEM_MAKE|ThinkPad 13 2nd Gen|Ubuntu 16.04.6 LTS|1.16.0

**Comment by belcherj** [comment]
This is changed in the version that will hopefully be released soon!
