### ISSUE TITLE
Remember the Preview mode of notes?

### ISSUE THREAD

**Issue by s1-en** [Automattic/simplenote-electron#2124]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
***(Required)*** What is the feature you are requesting?  Add a concise description of the feature being requested.
Make it so that SImplenote remember the last mode I set on a markdown-enabled note (Either Editing or Preview mode)

### Why
***(Required)*** Why are you requesting this feature?  Add a concise description of the problem this feature solves.
I have pinned notes that I use for reference that I always have to change to Preview mode whenever I start up Simplenote.

**Comment by sandymcfadden** [comment]
Thanks so much for the suggestion. I've added this request to our internal feature request tracker to keep in mind for future possibilities.
