### ISSUE TITLE
V1.70.0 would not start after updating from 1.16.0 to 1.17.0 on CentOS 7

### ISSUE THREAD

**Issue by jadupl2** [Automattic/simplenote-electron#2129]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
***(Required)*** Add a concise description of what you expected.
will not start after installing 1.17.0 (1.16.0 was working before updating)
### Observed
***(Required)*** Add a concise description of what you observed.
Receive a message while updating, may help you to find problem (see below)
# rpm -Uvh Simplenote-linux-1.17.0-x86_64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:simplenote-1.17.0-13236          ################################# [ 50%]
Unknown media type in type 'all/all'
Unknown media type in type 'all/allfiles'

Cleaning up / removing...
   2:simplenote-1.15.1-10908          ################################# [100%]

date
Tue Jun  2 09:36:47 EDT 2020

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Just update and try to run it.
> 2. Won't start - Seem to do something (Disk light blink) but then stop and nothing happen.

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem. See Above scree output

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, OS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|OS Version|App Version
# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core
#

**Comment by belcherj** [comment]
This fixes the issue: https://github.com/Automattic/simplenote-electron/pull/2102
