### ISSUE TITLE
Tags - Pull-down list instead of auto-fill

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2130]
### Expected
Starting to type the name of an existing tag, I want to:
a) see a possible selection appearing and 
b) click on the desired one.

As designed with the Android version 2.5.1 of Simplenote.

### Observed
- Just the first tag appears
- I have to type the full text of the tag to have the note tagged

### Reproduced
Example of existing tags:
Garden_100
Garden_110
Garden_120
Garden_200
House_100
House_110
House_200

I type G...
a) I see only " Garden_100 "
b) I have to type " Garden_120 " to have the note tagged for this one.

### Version

Simplenote Electron 1.16.0 | Windows 10

**Comment by belcherj** [comment]
I’ve added this to our feature requests tracker. Thank you for the suggestion.
