### ISSUE TITLE
When logged out most menu items don't work (About, theme, etc)

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2137]
### Expected
I expect that when the Simplenote > About Simplenote menu item is enabled, selecting it will open an about window like this (the about window that opens while logged in):

![Screenshot 2020-06-05 14 28 19](https://user-images.githubusercontent.com/8658164/83881946-50469980-a739-11ea-98fc-246377f7636b.png)

### Observed
Even though that menu item is enabled when I'm logged out, selecting it does nothing. No information about the app is available. (This is a little annoying when I am logged out and want to check what version of the app I'm using, since I have to log in first.)

### Reproduced

1. Log out of the app.
2. Go to the Simplenote system menu.
3. Select "About Simplenote."

Result: Nothing happens.

Make|Model|OS Version|App Version
-|-|-|-
Mac|Macbook Pro|macOS 10.15.4|1.18.0-beta1

**Comment by codebykat** [comment]
Oh yeesh. Yeah actually none of the menu items work while logged out (including changing the theme to dark mode). Stuff like "Insert Checklist" is still there. Sort options. They also seem to get cleared once you log in.

**Comment by belcherj** [comment]
I think they should all be greyed out while logged out. This would require a large refactor to allow for dark mode switches while logged out.

I do think the about page should be accessible while logged out.

**Comment by codebykat** [comment]
Closed in #2228, #2231, #2232
