### ISSUE TITLE
Signup: Password validation error message (for email address) doesn't match validation rules

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2138]
### Expected
When I sign up for a new account, I expect that I can use a password unless it is less than 8 characters or it **matches** my email address. I expect the error message to explain that clearly if I try to use an unacceptable password.

### Observed
The behavior works as expected, but the error message says that the password may not **include** my email address:

![Screenshot 2020-06-05 15 36 08](https://user-images.githubusercontent.com/8658164/83889598-3b6f0380-a743-11ea-80b2-d6cc5f5ef145.png)

### Reproduced

1. Start logged out of the app.
2. Select "Sign up."
3. Enter an email address not linked to an existing Simplenote account.
4. In the password field, enter exactly the same email address.
5. Select the "Sign up" button, and notice the error message.
6. Edit the password field to add extra characters before/after your email address (still including the email address within the password).
7. Select the "Sign up" button, and notice you are signed up and logged in to your new account.

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.18.0-beta1

**Comment by codebykat** [comment]
Thank you @rachelmcr! Fix up in #2139, but Phoenix is AFK today so we'll get that in next week ❤️
