### ISSUE TITLE
Checklist first displays as bracket - requires switching note and returning

### ISSUE THREAD

**Issue by kewlfft** [Automattic/simplenote-electron#2141]
### Expected
checklist to be displayed with bullet points instead of `-[]` in display mode

### Observed
checklist is displayed with `- []` at startup, after moving to another note and coming back to the previous note the checklist is properly displayed.
This is true for the Arch Linux 1.17.0 Simplenote and accessing Simplenote on Firefox as well.

Arch Linux
1.17.0

**Comment by belcherj** [comment]
Fixed in #2170
