### ISSUE TITLE
Published notes: Side-by-side images show up on separate lines

### ISSUE THREAD

**Issue by s1-en** [Automattic/simplenote-electron#2143]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
***(Required)*** Add a concise description of what you expected.
I expected the shared notes with Markdown enabled to show up the same way it does on the app's preview mode.

### Observed
***(Required)*** Add a concise description of what you observed.
It looks different. For example, I can put small enough images sideby side in the app but on the version that can be seen on the share link, they are delimited by a newline.

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
1. Create a new note
2. Enable Markdown
3. Add images by using the format `![image_name](https://image.host/link.png)`
4. Add another image beside it.
5. Share the note
6. Open the share link on a browser

**Comment by codebykat** [comment]
Thanks for this report, @s1-en! I know there are several ways published notes are different (e.g. #537), I changed the title to reflect the specific example you gave here. Please open other issues if there are other specific differences you've noted.

**Comment by s1-en** [comment]
Alright

**Comment by s1-en** [comment]
Is this fixed now?

**Comment by codebykat** [comment]
Should be fixed @s1-en! I just deployed it. Let me know if not.

**Comment by s1-en** [comment]
Sweet, I just checked it out and it works like a charm. Thanks a lot!
