### ISSUE TITLE
Published notes: New line quotes with space between each other gets merged in the published version

### ISSUE THREAD

**Issue by s1-en** [Automattic/simplenote-electron#2144]
As instructed on #2143, I'm opening a separate issue for this other discrepancy

Instead of the quoted text being separated, it combines into one block in the published version.

### Expected
***(Required)*** Add a concise description of what you expected.
![image](https://user-images.githubusercontent.com/63731521/84073616-bc5c2280-aa03-11ea-8bd1-861f3cab8774.png) ![image](https://user-images.githubusercontent.com/63731521/84073675-d138b600-aa03-11ea-8492-ab9b30be06d5.png)

### Observed
***(Required)*** Add a concise description of what you observed.
![image](https://user-images.githubusercontent.com/63731521/84073728-ef9eb180-aa03-11ea-8b0f-685d69297432.png)

**Comment by codebykat** [comment]
Interesting thanks!

**Comment by codebykat** [comment]
Ah this is an upstream issue with the Markdown parser: https://github.com/trentm/python-markdown2/issues/332

I will see if I can figure out a patch.

**Comment by codebykat** [comment]
This was fixed upstream here: https://github.com/trentm/python-markdown2/pull/356

Won't be fixed for us until the new version of the parser is released and we upgrade, so I'll keep this open for now.

**Comment by codebykat** [comment]
Finally fixed!

<img width="286" alt="Screen Shot 2020-10-22 at 3 47 26 PM" src="https://user-images.githubusercontent.com/52152/96939169-1e806600-1481-11eb-95dd-4d062375856f.png">
