### ISSUE TITLE
Import notes using drag and drop

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2154]
I want to import notes using drag and drop.

![image](https://user-images.githubusercontent.com/23485114/84720763-2cceea80-af94-11ea-9ec1-33a20d22d4d2.png)

Please add this feature.

Thanks.

**Comment by dmsnell** [comment]
Hi @xmha97 - thanks for the great idea. I've added it to our internal feature-request tracker. Not sure when we might be able to get this but it seems like a good suggestion. 👍
