### ISSUE TITLE
Support .md format on 'Import Notes...' Dialog

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2155]
Hello,

![image](https://user-images.githubusercontent.com/23485114/84721312-a3201c80-af95-11ea-841e-ceadb91b1d15.png)

There are only the `.txt` format.
Please add `.md` format.

Thanks.

**Comment by dmsnell** [comment]
Labelling as a bug because we probably should have opened up the `.md` file extension when we added the import dialog.
