### ISSUE TITLE
Yellow color theme

### ISSUE THREAD

**Issue by starpause** [Automattic/simplenote-electron#2157]
### What
I would like a Yellow color theme. It would be extra awesome if we had configurable color themes, but I understand that's a whole level of complexity more than adding a single color theme. 

### Why
On OSX it's very useful to have stickies a different color than my other windows. I wish I could set Simplenote color to something like "post-it" yellow so that it stands out from my other windows when context switching.

**Comment by codebykat** [comment]
Thanks for this suggestion! Closing this as we're not working on it in the near future, but I've added it to our list of ideas for potential future work.

**Comment by starpause** [comment]
Glad it's under consideration for future work. I understand there are lots of open issues and would still find an additional color theme very useful!
