### ISSUE TITLE
Windows S Mode prevents app opening

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#2161]
A user has reported that Simplenote does not open in Windows S mode. S mode should mean that only apps downloaded from the Windows store can run, so theoretically it should work, but does not.

I am unable to test this, but got a bit of insight into S mode. It doesn't seem to be incredibly popular, and maybe something schools and businesses are using. It's hard to go back to S mode once you deactivate it.

This particular user is able to open it, log in, and use the app without S mode, on the same device.

### Expected
1. Simplenote 1.5.0 was downloaded from the Windows store
2. Click to open
3. You can then log in

### Observed
1. Simplenote 1.5.0 was downloaded from the Windows store
2. Clicked to open
3. "After installing Simplenote from the store, it never launches. I see that the exe is running in task manager, but I never see it appear."

### Reproduced
I cannot reproduce this behavior. S mode is available on Windows tablets.

Surface Go | Windows 10 | S Mode | Simplenote 1.5.0

ticket reference: #2075287-zen

**Comment by sandymcfadden** [comment]
@belcherj is this something you'd be able to test sometime? From what I can gather it requires a device that supports S Mode and I believe you said you had one.

**Comment by belcherj** [comment]
I do not have an S Mode device or a way to test this. I will inquire about finding an S Mode device.

**Comment by belcherj** [comment]
I was unable to find anyone with a S Mode device. When time permits I will see if it is possible to get S Mode running in parallels.

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
