### ISSUE TITLE
Windows 10 App - Password

### ISSUE THREAD

**Issue by milendimo** [Automattic/simplenote-electron#2163]
Password ending with = ( aka equals sign) on Windows Electron App does not allow users to login. Although it is all fine in the web version. 

### Expected
Able to login with any password on any platform

### Reproduced
Change password on account via web UI and make sure it ends with =

Log Out and Login on Web UI is all fine.
Unsuccessful login via Simplenote Electron App for Windows 10.
Changing password to something else via Web UI enables successful login on both platforms.

**Comment by belcherj** [comment]
Just tested 1.21.1 and this no longer seems to be an issue. Thank you for the report.
