### ISSUE TITLE
Changing password more than once in a single session

### ISSUE THREAD

**Issue by milendimo** [Automattic/simplenote-electron#2164]
Error occurs if an user changes their password at least twice while being logged in. 

### Expected
Able to change passwords indefinitely.

### Reproduced
Changed password to some value via Web UI. 
Attempted login via Windows 10 App. Unsuccessful due to a separate issue. 
In the same session via Web UI, change the password to a new value. Error occurs during password change.
Able to login and set all back to normal after a request for a password reset.

**Comment by codebykat** [comment]
I've tested this and can't reproduce it @milendimo. It's not possible to change the password twice without reloading the page, as it hides the form after a successful submission. My best guess at what may have happened here is that you accidentally typed a different password than the one you thought you submitted. Please let us know if there are different steps to reproduce this bug and we can investigate further.
