### ISSUE TITLE
Smoother typing experience on the desktop app?

### ISSUE THREAD

**Issue by s1-en** [Automattic/simplenote-electron#2172]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What ***(Required)***
Make the typing experience on the desktop application (Windows) feel smoother. See the following comparisons: between Simplenote and VS code. Both are Electron-based.

VS Code: https://i.imgur.com/0NHBfEQ.mp4  
Simplenote https://i.imgur.com/u4UrN9o.mp4

In addition to the visual sluggish feel, there's a small delay between keypress and it appearing on the app which adds to the whole unresponsive feel.

### Why ***(Required)***
Right now, it feels slow to respond while typing.

### How ***(Optional)***
I'm not sure what's causing the slowdown, could it be the network checking? (In the case of collaborations) If that's the case then may I suggest having a check first if the note is being edited simultaneously by different people before turning it on? If it's a wholly unrelated issue then please disregard my ignorant statement.

**Comment by codebykat** [comment]
Hi @s1-en, does this relate to the length of the note at all? We're already looking at some performance improvements under the hood. The issues I'm aware of are mostly related to longer notes.

**Comment by s1-en** [comment]
Hi @codebykat, it seems to affect new blank notes as well (as I tested above) but it gets way more apparent as the note gets longer

**Comment by mmaluff** [comment]
I noticed this too. Looking at the network tab on my browser dev tools, I noticed it's making a request for a 1px gif _every single time_ I enter a character, presumably for analytics. That seems like overkill. Disabling analytics increases performance by a lot, though it's still not perfect.

This is what it looks like with analytics enabled:
![analyticsenabled](https://user-images.githubusercontent.com/916197/89092192-3a3e0980-d375-11ea-8f89-ed9bbf2927ed.gif)

And this is what it looks like with analytics disabled:
![analyticsdisabled](https://user-images.githubusercontent.com/916197/89092193-41651780-d375-11ea-95f6-554b3c42ca1d.gif)

Notice how it stutters a lot less when analytics is disabled.

**Comment by s1-en** [comment]
So then how did you disable the analytics image? @mmaluff

**Comment by mmaluff** [comment]
For testing I was just setting `window.analyticsEnabled = false`, but there should be an option in your settings:

![image](https://user-images.githubusercontent.com/916197/89105859-837c7080-d3ea-11ea-83ef-876f0ae602aa.png)

**Comment by codebykat** [comment]
Can folks on this thread test out the beta app at https://staging.simplenote.com and report back if performance seems better? Thanks 😄

**Comment by mmaluff** [comment]
With analytics turned off, the performance is actually perfect, exactly as I'd hope (and much better than on the current app).

With analytics turned on, it's still just as bad as today (and still seems to do the thing where it gets the 1px gif for every character I enter).

**Comment by codebykat** [comment]
That's good to know, thanks! I'll investigate the analytics. It should be queueing up note edits which I would expect to also debounce the analytics tracking, but obviously not.

**Comment by codebykat** [comment]
@mmaluff We were unable to reproduce the lag from analytics over here (which doesn't necessarily mean anything). Anyhow we just pushed an update to staging.simplenote.com that limits how frequently those analytics calls get made on a note edit. Can you let me know if you can re-enable analytics now without degraded performance?

**Comment by mmaluff** [comment]
It looks fantastic! No noticeable difference between analytics on or off
now. Thank you!!
