### ISSUE TITLE
Mouse cursor & checklist items

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#2185]
While hovering checked / un-checked checklist item, mouse cursor appears as text cursor.

I expected pointer cursor, like the one which appears when hovering or selecting notes.

It also applies for Preview mode.

### Expected
![Screenshot from 2020-07-03 17-43-41(1)](https://user-images.githubusercontent.com/8862464/86484771-407d9d80-bd57-11ea-92b3-0e07015b3697.jpg)

### Observed
![Screenshot from 2020-07-03 17-43-41](https://user-images.githubusercontent.com/8862464/86484829-63a84d00-bd57-11ea-9e27-620d2485fe44.jpg)

|OS Version|App Version|
|-|-|
|Ubuntu 18.04 LTS|Simplenote 1.19.0|

**Comment by arpitbatra123** [comment]
Created a PR for this here - https://github.com/Automattic/simplenote-electron/pull/2189, if any maintainer can please have a look!
