### ISSUE TITLE
Uncaught Exception: ERR_CONNECTION_RESET at browser_init.js:2536:21

### ISSUE THREAD

**Issue by zhangxiaoxing** [Automattic/simplenote-electron#2188]
I keep  a simplenote window open all the time. Sometime around June 2020, random error dialog began to pop up with an Uncaught Exception: ERR_CONNECTION_RESET at browser_init.js:2536:21. This happened with both version 1.15.xx and 1.17.0. The internet connection here is indeed unstable at times, so the exception is likely reasonable, just need to be caught is all.

### Expected
(internet connection breaks at times), but simplenote remains stable.

### Observed
An error dialog with Uncaught Exception: ERR_CONNECTION_RESET at browser_init.js:2536:21.

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
1. Keep  a simplenote window open.
2. Dialog randomly pops up.

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

![Annotation 2020-07-06 144342](https://user-images.githubusercontent.com/58493968/86563561-2d591080-bf97-11ea-96be-6aff2346ff16.png)

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, OS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|OS Version|App Version
-|-|-|-
|||Windows 10| Simplenote 1.17.0

**Comment by codebykat** [comment]
@zhangxiaoxing can you please refresh any open browser tabs and let me know if this is still an issue?

**Comment by zhangxiaoxing** [comment]
@codebykat I ... don't really know how to refresh an open browser tab in simplenote.  But I haven't seen the Error dialog in a few weeks (while still using the 1.17.0 version. Magic?). Thanks a lot!

**Comment by belcherj** [comment]
This appears to be the fix: https://github.com/electron-userland/electron-builder/issues/2398#issuecomment-413117520
