### ISSUE TITLE
Inconsistent note selection with trash/delete/restore actions and switching between note views

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#2190]
### Expected

When I trash, delete, or restore a note, I expect the app to select the note below it in the note list.

I also expect the note selection behavior to be consistent when switching between note views All Notes or Trash.

### Observed

The note selection behavior is different depending on the position of the note in the note list:

1. If you select the first note in the list, and then switch between All Notes and Trash views, no note is open in the note editor. However, if you select any other note in the list, and then switch between All Notes and Trash views, that note remains open in the note editor.
2. If you view the All Notes list, select the first note in the list, and trash it, the next note in the note list is highlighted but it is not opened in the note editor. If you select any other note in the list and trash it, the next note in the note list is highlighted **and** opened in the note editor.
3. If you view the Trash list, select a note in the list, and delete it forever, the next note in the note list is highlighted but it is not opened in the note editor. (This is the only case where it is consistent regardless of which note it is.)
4. If you view the Trash list, select the first note in the list, and restore it, the next note in the note list is highlighted but it is not opened in the note editor. If you select any other note in the list and restore it, the next note in the note list is highlighted **and** opened in the note editor.

**1. Switching between All Notes and Trash**

![sn-electron-selection-alltrash](https://user-images.githubusercontent.com/8658164/86792487-71fdae00-c062-11ea-8803-8a08f587c620.gif)

**2. Trashing notes in All Notes**

![sn-electron-selection-trashnote](https://user-images.githubusercontent.com/8658164/86792497-74f89e80-c062-11ea-8b81-757513272467.gif)

**3/4. Deleting and restoring notes in Trash**

![sn-electron-selection-deleterestore](https://user-images.githubusercontent.com/8658164/86792505-77f38f00-c062-11ea-8cda-0e68cd305666.gif)

Make|Model|OS Version|App Version
-|-|-|-
VirtualBox VM|Windows|10|1.20.0-beta2

This doesn't seem to be new in 1.20-beta2; I also tested in the 1.19.0 release and see the same behavior there.

**Comment by codebykat** [comment]
I reported the first thing as a separate bug #2342
