### ISSUE TITLE
Auto logging out at first start. Solution: use only lower case on email field

### ISSUE THREAD

**Issue by AvatarMod** [Automattic/simplenote-electron#2193]
### Expected
After first start and log in normal work of application with viewing,editing tasks,etc...

### Observed
I'm download latest AppImage version and starting application.Them I'm log in but after 1-2 seconds this app automated logging out and wish to log in again

***(Optional)***
Before log in
![изображение](https://user-images.githubusercontent.com/37958026/86905226-6ff72600-c11a-11ea-952a-cf5449059c10.png)
Apps is logging in
![изображение](https://user-images.githubusercontent.com/37958026/86905382-aa60c300-c11a-11ea-8cae-05e23e6ab796.png)
Apps log out
![изображение](https://user-images.githubusercontent.com/37958026/86905460-bfd5ed00-c11a-11ea-80e2-f63646b2749d.png)

***(Optional)*** 
Make|Model|OS Version|App Version
-|-|-|-
AppImage|Dell Inspiron 5000 Series|Linux Mint 20 Cinnamon|1.19.0

**Comment by CJFxTiKiMoN** [comment]
I'm also experiencing this issue. Here's some of the info I've gathered from the debugging console. Let me know if I can provide any additional information to assist with this issue.

| Make | Model | OS Version | App Version | Installation Type |
| :------ | :------- | :--------------- | :---------------- | :-------------------- |
| Gigabyte | Aero 15 | Pop OS 20.04 | 1.19.0 | Simplenote-linux-1.19.0-amd64.deb |

![image](https://user-images.githubusercontent.com/52645623/87253619-b7e3b900-c44a-11ea-83ef-2945f950d8a7.png)

![image](https://user-images.githubusercontent.com/52645623/87253812-0b0a3b80-c44c-11ea-9903-e4c1e69cda6f.png)

**Comment by CJFxTiKiMoN** [comment]
Just logged in using all lower case in my email (force of habit to capitalize) and it worked. Hope that helps @AVAtarMod

**Comment by EdoardoLopez** [comment]
> Just logged in using all lower case in my email (force of habit to capitalize) and it worked. Hope that helps @AVAtarMod

thanks, it worked for me. I had the issue in "Simplenote-linux-1.20.0-amd64.deb" version.

**Comment by BPService** [comment]
I have the same issue with version 1.20.0 of the Simplenote app under Windows 10. Auto logging out happens after entering an email address with upper case characters on the log in screen.

**Comment by AvatarMod** [comment]
> 
> 
> Just logged in using all lower case in my email (force of habit to capitalize) and it worked. Hope that helps @AVAtarMod

Thanks very very much! I now trying install&launch app for Windows (I use 10 version and 64bit), and me helped your suggest.

**Comment by codebykat** [comment]
Well that's fascinating. Thanks for the report and the detective work! I've made a note to fix this on the backend. (I'm leaving this issue closed because it's almost certainly an issue with the backend and not the app itself.)

**Comment by codebykat** [comment]
Hah - I take it back, it was totally an app-only issue. Fix will be in the next version.

**Comment by imambs** [comment]
I am getting a logging out issue immediately after the login. The email address I entered is in lowercase though.
Using web address https://app.simplenote.com/login/ and OS is Ubuntu 20.04

**Comment by codebykat** [comment]
Hi @imambs, can you please try resetting your password? If that doesn't work, drop us a line at support@simplenote.com so we can investigate further. Thanks!

**Comment by imambs** [comment]
> Hi @imambs, can you please try resetting your password? If that doesn't work, drop us a line at [support@simplenote.com](mailto:support@simplenote.com) so we can investigate further. Thanks!

Resetting the password worked back to login into the app. Before I had a capital letter in the password but this time used small letters in the new password, not sure if it was the issue. Anyway, thanks a lot!

**Comment by alexbottoni** [comment]
I'm having the same problem with the web-based version of Simplenote. It kicks me out just after log in. So, it looks like it is NOT a problem related to the Electron-based desktop application. I'm using lowercase email address. I did not try to reset password. My password contains mixed-case letters, numbers and other characters. BTW: the Electron-based desktop app does not work at all on my Linux Mint 21 Cinnamon. (It worked fine on the Linux Mint 20.1 I used until August).

EDIT: Trying to reset my password from the web interface returned me a 500 Internal Server Error. BUT, strangely enough, now I was able to enter my account with the OLD password.

EDIT 2: Now it is working (only) with the NEW password (all lowercase, special characters and numbers).

**Comment by ffimnsr** [comment]
Also experiencing same problems as the commentor above.

**Comment by codebykat** [comment]
Hi folks - we have fixed this on the backend but some accounts may need further investigation. We can't investigate account-related issues on the public GitHub (and please! Stop sharing details about your passwords here!!)

If you're still unable to log in and the problem is not resolved by a password reset, please email support@simplenote.com for help so we can take a closer look on a case-by-case basis. Thanks!
