### ISSUE TITLE
Last synched does not show correct status | Notes are not synched

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2195]
# Expected
- I write a new note or change an existing note
- I want simplenote-electron to synch my notes **right away**
- I want simplenote-electron to show the actual status **without moving the mouse over "Last synched"** 

### Observed
- Simplenote-electron does not synch my notes immediately
- I need to move the mouse over "Last synched" to see the actual status 
![Last synched](https://user-images.githubusercontent.com/22197180/86950203-2aede680-c150-11ea-92d6-c7e2061cd229.JPG)
...so far I had believed that simplenote-electron has synched immediately - but it did / does not 

### Reproduced
- I write a new note or change a note
- I need to move the mouse over "Last synched" to see the actual status (11 minutes ago):
![Last synched top](https://user-images.githubusercontent.com/22197180/86950249-39d49900-c150-11ea-9979-229a70a16b8f.JPG)
- Simplenote-electron does not synch my notes immediately (16 minutes ago):
![Last synched top 2](https://user-images.githubusercontent.com/22197180/86950322-52dd4a00-c150-11ea-835e-bdb974c1362b.JPG)

### Make|Model|OS Version|App Version
Windows 10 | simplenote-electron 1.15.0

**Comment by codebykat** [comment]
Likely fixed by #2148, this hasn't shipped to apps yet but the component has been completely rewritten. Please open a new issue if problems persist on https://app.simplenote.com
