### ISSUE TITLE
Tags: Can't edit by placing cursor as it always jumps to the end

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#2199]
I'm adding this as an enhancement as it doesn't seem quite like a bug.

### What
A Simplenote user reported strange behavior when trying to add tags. Upon a closer look, I believe it's just a way we didn't expect them to be added.

## Observe

1. Copy a few words with spaces between (like a sentence with no punctuation)
2. Paste into the tag area
3. Try to click into a word to edit it
4. The cursor will jump to the end and it's not possible to edit the words without just deleting from the right side, so any edits end up at the end and look like a bug

User reported this for Windows 10 desktop app and the web.
I can reproduce in Mac Electron 1.19 and on the web in Chrome

**Comment by sandymcfadden** [comment]
This seems to happen as well if you type in a list of tags separated by spaces.
Once you get to the end you can press enter or return and it will turn them to individual tags and then you can remove individual ones.

![Screen Capture on 2021-01-15 at 10-15-44](https://user-images.githubusercontent.com/1326294/104737593-d76dde00-571a-11eb-86d0-6e460f53e9cd.gif)
