### ISSUE TITLE
Simplenote 1.20.0 unusable after trying to import notes

### ISSUE THREAD

**Issue by algent-al** [Automattic/simplenote-electron#2200]
Simplenote unusable after trying to import notes. As you can see in the animation below the whole window goes white.

![import-notes-broken](https://user-images.githubusercontent.com/46356616/87341741-67ec1b80-c54a-11ea-85f7-ea7f85dd3989.gif)

### Reproduced
This happens every time when trying to import notes.
> 1. Go to "File"
> 2. Click on "Import Notes"
> 3. Select one of the import options.
> 4. See error...

OS: Solus Budgie 4.1
Make: Re-packaged the .deb file to .eopkg using Solus build tools.
App Version: Simplenote 1.20.0

**Comment by belcherj** [comment]
Thank you for the report, I have a fix in the works now and hope to have a fix soon.
