### ISSUE TITLE
Feature Request: Default tags.

### ISSUE THREAD

**Issue by mrdrozdov** [Automattic/simplenote-electron#2216]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What

A setting to turn on a default tag assigned to every new note.

### Why

I'd like to be able to change the default tag every few months so that I can easily search notes later. It's also useful for creating notes when I'm attending conferences, etc.

### How

Two ideas.

**(1) Use the existing tag text box.**

- When the tag is set, have an option to delete it (this is equivalent to turning off the default tag).
- Otherwise, can add a "Add default tag..." in the tag text box which is next to the existing "Add tag..." prompt.

**(2) Use a config menu.**

In a settings menu, or one of the drop-downs like "Note", have an option to add/change/delete the default tag. This has the benefit that it is simple to delete the default tag from an existing or in progress note.

**Comment by codebykat** [comment]
This is an interesting idea! It's not on our immediate roadmap, so I'm closing this issue, but I've added it to our list of ideas for possible consideration in the future.
