### ISSUE TITLE
Feature Request: "refresh" button

### ISSUE THREAD

**Issue by Davido264** [Automattic/simplenote-electron#2217]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
Please add a Refresh button, Other apps that automatically sync when a change is made to a note have the ability to refresh the app, so if any changes made that didn't sync the right way, we can try again

### Why
This is not just on Electron version, I recently had some sync issues in all app versions of Simple Note, More frequently when I do something offline, like deleting a note, and connect to internet to sync. In the Electron version, it shows me that I have Unsynchronized  changes, and the only way I could solve this, is by deleting all data on my app (I tried the solutions that the app gave me and nothing happened)
Most apps have issues like that, that's the reason why they include a way to refresh the app. And that's the reason why I'm requesting this features

**Comment by codebykat** [comment]
In the new version if you log out with unsynced data it will offer you an ability to export unsynced notes. I don't anticipate offering a way to "force" sync per se. If the app is connected, making any change to a note would force it to re-try syncing. We handle connectivity issues as robustly as possible, so in situations like this we're probably already trying to force a refresh under the hood.

Anyhow lots of this functionality has been rewritten in #2148 so please open a new issue if you're still having trouble! (The new version has not yet been shipped to apps but you can test on https://app.simplenote.com .) Thanks!
