### ISSUE TITLE
Use shift key to select more than one note

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#224]
This is helpful for:
- Trashing notes
- Pinning notes
- Deleting/Restoring notes

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by codebykat** [comment]
Got a request for this in 3730325-zen; it should really be on our roadmap I think.

**Comment by dragonattack** [comment]
Didn't think that not implemented. I think this is really needed.
I have about 100-200 notes to remove. How you do that?

I think people will vote for this feature if you in doubts.
