### ISSUE TITLE
Pasting text separated by line breaks into a list should create a new list item for each

### ISSUE THREAD

**Issue by mmaluff** [Automattic/simplenote-electron#2253]
### What

I find myself copying a list from elsewhere into simplenote surprisingly often. For example, from a spreadsheet, or from a different set of notes, or from a plain text editor. Currently, when I do this, the first item is part of the list, but everything else is just on a new line outside the list. It would be cool if the app just added a new list item for each line instead of me.

### Why

It would save a lot of time, and it's a surprisingly common workflow (for me, anyway).

### How

Suppose I have text like this in my clipboard:

```
Item 1
Item 2
Item 3
```
If I start a list in Simplenote, like this:

```
- 
```

And paste my text on it, the current result is this:

```
- Item 1
Item 2
Item 3
```

The result should be this:
```
- Item 1
- Item 2
- Item 3
```

**Comment by sandymcfadden** [comment]
Thanks so much. We've had a couple of requests for this before and are tracking it in our internal feature request tracker. I've added your request there as well and am closing this for now.
