### ISSUE TITLE
Lost Note Data

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-electron#2254]
Note created on computer a
Note edited on computer b
Edits from B were not available on A the next day and did not show in the history. 

Computer A
Windows 10 Pro 1909
Chrome Version 84.0.4147.89

Computer B
Windows 10 Enterprise 2004
Chrome Version 84.0.4147.89

They are on the same network and have both been and continue to be online the entire time.

#3181373-zen

**Comment by azollafox** [comment]
The user updated us on this generously. 

Here's what they are doing:
1. writing the time in a note in an incognito window
2. closing the window
3. waiting one minute and logging back in, in another incognito window. 

Result:
some text is lost during that process as they repeat it a few times

The issue only happens in Chrome, not other browsers. Chrome is up to date. They've shared with us screenshots of their browser console:

![](https://d.pr/i/cUehku+)
(Image link: https://d.pr/i/cUehku )

There are extensive videos of the issue in action including one uploaded to YouTube here https://youtu.be/PND7VsGbjp4

@anaemnesis  tried to help us reproduce this but wasn't able to do so

**Comment by andirsun** [comment]
Hi, im facing the same error between my 2 linux devices and android

**Comment by sandymcfadden** [comment]
This is the same report as here https://github.com/Automattic/simplenote-electron/issues/2245
I've reached out to see if this is still happening. Closing this one.
