### ISSUE TITLE
Markdown In Published Note Broken

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-electron#2257]
### Expected
When markdown is used in a note the note preview should reflect accurately what the note will look like when published

### Observed
There is a mismatch in what markdown actually shows in the published version. H1 and unordered lists do not show in the published note. From the user report there may be other markdown similarly affected

### Reproduced

What I put in the note
![](https://d.pr/i/EaiIVo+)
(Image link: https://d.pr/i/EaiIVo )

What preview shows me
https://d.pr/i/4FB4VW

What the published note looks like https://d.pr/i/vIOnV1

### Where did you see the bug

Tested both on Electron for MacOS and Electron in my browser. Preview looks the same on both spots

- System Make:Mac
- System Model: Macbook Pro
- OS: Catalina
- OS version: 10.15.5
- Browser: 79.0 
- Browser version : 79.0 
- Simplenote app version: 1.19.0

Reported: #3189583-zen

**Comment by codebykat** [comment]
Needing to put a space before a list in order for it to get rendered is a known issue on multiple platforms (https://github.com/Automattic/Simplenote-United/issues/30). I can't reproduce the H1 issue - 

<img width="341" alt="Screen Shot 2020-08-04 at 12 56 12 PM" src="https://user-images.githubusercontent.com/52152/89338753-e6237580-d651-11ea-8dfb-81ccbd6e4cdc.png">

Published:

<img width="790" alt="Screen Shot 2020-08-04 at 12 56 05 PM" src="https://user-images.githubusercontent.com/52152/89338760-e885cf80-d651-11ea-9704-38ef0932cc23.png">

I'll connect with this user directly to try to get a link to the affected note.

**Comment by codebykat** [comment]
Actually the ticket linked doesn't seem to contain this report, @sarahfg is it possible it was a different ticket? All I see there is the text before bulleted list one.

**Comment by azollafox** [comment]
Yeah, the screenshots are from my own test. It looks like it's working now. Publishing notes was taking forever while I was trying to test. I would guess the published note wasn't showing my H1 markdown was the slow-to-update published note situation. The addition of the h1 marking on the title was a change I made to the note after initially publishing while testing the user's report that markdown wasn't showing correctly. They only provided one example, so I was trying to see what else they meant.
