### ISSUE TITLE
Unable to login to simplenote version 1.17.0 +

### ISSUE THREAD

**Issue by sreejithpunnapuzha** [Automattic/simplenote-electron#2258]
After upgrading to 1.20.0 from 1.16.0 on my ubuntu 18.04, if i logout of the session, i cant log back in to simplenote. Even on fresh installation of simplenote 1.20.0 on ubuntu 18.04, i am not able to login

### Expected
Sign-in should work as expected on any version of simplenote

### Reproduced
1. Install/upgrade simplenote 1.20.0
2. if new installation Login to simplenote using email and password
3.if upgrade, logout of simplenote and login back in using email and password

- OS: Ubuntu
- OS version: 18.04, 20.04
- Simplenote app version: 1.20.0

I downloaded the old version of simplenote debs. i am seeing the same issue on v1.17.0, v1.18.0, v1.19.0 and v1.20.0.

v1.16.0 works as expected.

**Comment by codebykat** [comment]
Hi @sreejithpunnapuzha, for issues like this it's usually better to reach out to our [support email](https://simplenote.com/contact/) so we can provide individualized support (GitHub issues are public). Are you able to log in on the web (https://app.simplenote.com)?

Is there any kind of error displayed or what happens exactly?

**Comment by sreejithpunnapuzha** [comment]
I am able to login on web. it doesn't provide any kind of error. it tries to login and then logout automatically. since i am getting same experience for login on v1.17.0 +, i thought it might be a bug.  i tested the same on windows as well. 1.16.0 is working well but after updating simplenote via windows store, same issue there as well. i will try reaching out to support via email

**Comment by msilbers** [comment]
This was reported in 3200973-zen for the Windows app

brand new Simplenote account

I've asked for more details

**Comment by msilbers** [comment]
reported in 3202290-zen

Unable to log into Simplenote Windows app
Windows 10

also a brand new Simplenote account

**Comment by sreejithpunnapuzha** [comment]
@msilbers my account is no a brand new one. i was using this for some time. Also login and logout works fine on my mac(v1.12.0). issue is on windows/ubuntu on simplenote 1.17.0 and above. if i downgrade to v1.16.0 i can login without any issues. also login on web is working fine.

**Comment by codebykat** [comment]
User in #3202290-zen wrote to let us know that this was due to mixed case characters in their login. That particular bug is fixed in #2226 which is part of the upcoming version 1.21. @sreejithpunnapuzha is it possible you are using uppercase letters in your email?

**Comment by algent-al** [comment]
Apparently there are some login issues. I logged out and then tried to login, but I couldn't. No issues with web browser. 
But then after a while, about 30 mins later I logged in successfully. 

OS: Solus
Simplenote version 1.21.0

**Comment by sreejithpunnapuzha** [comment]
@codebykat yes. i was using uppercase letters in my email address. I tested the latest release v1.21.0 and its working well. i can login without any issues now. when i tried to on v1.20.0 with lowercase letters it worked.

As you mentioned since this issue is already fixed, I think we can go ahead and close this issue. thanks for the support.
