### ISSUE TITLE
History slider not showing all previous versions in V 1.20.0

### ISSUE THREAD

**Issue by tetrahedon7** [Automattic/simplenote-electron#2259]
### Expected

The history slider should show all previous versions of a note, starting from the earliest version.

### Observed

It's only showing two versions, the current one, and the immediately previous one. This problem is absent from the android app.

### System info

- OS: Windows 10
- Simplenote app version: 1.20.0

**Comment by sandymcfadden** [comment]
Is this still happening if you update to the latest version of Simplenote? We have version 2.4.0 available currently. In my testing the note history is showing the versions properly.

I'm going to close this for now but if you are still having the issue in the newest version please let us know.
