### ISSUE TITLE
Published Notes List

### ISSUE THREAD

**Issue by mklg1982** [Automattic/simplenote-electron#2268]
### What
I am requesting for a button (as "All Notes" or "Trash") in the left menu of the app: to list all the published notes as a web. And then to show a kind of table, with the preview of the note and the link to the published note (copy-pasteable link).

### Why
It is the easiest way to check what you have published and what not.

Thanks So much.

**Comment by codebykat** [comment]
Thanks, this is an interesting idea! I'm closing this issue for now because it's not on our immediate roadmap, but we'll consider it in the future.
