### ISSUE TITLE
Lack of release notes

### ISSUE THREAD

**Issue by ekohilas** [Automattic/simplenote-electron#2269]
Hi,

I've noticed that some releases (such as 1.20) are lacking release notes.
Is there a reason for this?
Or perhaps am I looking in the wrong place?

I really appreciate being able to know what's changed about the new versions without having to read commit messages (which other users who aren't as technical would not be able to do).

Cheers!

**Comment by codebykat** [comment]
Hi @ekohilas, sometimes they don't get copy-pasted into the release itself. I'll follow up on that. You can always view the release notes by checking RELEASE-NOTES.md for the release tag you're interested in, for example here is 1.20: https://github.com/Automattic/simplenote-electron/blob/v1.20.0/RELEASE-NOTES.md

You can get there by going to RELEASE-NOTES.md and toggling the dropdown on the upper left:

<img width="622" alt="Screen Shot 2020-08-09 at 8 36 07 PM" src="https://user-images.githubusercontent.com/52152/89750256-0a32ec80-da80-11ea-88e8-2dd2702ae686.png">

**Comment by codebykat** [comment]
I went back and made sure there are release notes for all the major release tags! Thanks for pointing this out.
