### ISSUE TITLE
Add icon to note list item if it is shared/published

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#227]
We don't do this in any of our apps, but it would be nice to add an icon to a note in the list view if the note is "shared". Shared, meaning that you have added an email to the note's tags, or you have added an email via the collaborate UI.

**Comment by erichiller** [comment]
Duplicated of #220  - but I totally agree

**Comment by bummytime** [comment]
The (old) web app had the published icon for any individual note:

<img width="728" alt="sharing_icon" src="https://user-images.githubusercontent.com/154014/58282571-c022f580-7d6b-11e9-90df-c9b0f0f335df.png">

Ref: https://github.com/Automattic/simplenote-macos/issues/4
Ref: https://github.com/Automattic/simplenote-ios/issues/312

**Comment by bummytime** [comment]
Closing. I just noticed this:

<img width="327" alt="Screen Shot 2019-05-23 at 3 46 56 PM" src="https://user-images.githubusercontent.com/154014/58285273-1004bb00-7d72-11e9-9778-fbc5476fc71a.png">

🤷‍♂ 😄
