### ISSUE TITLE
Grammarly Pop-up erases the whole note

### ISSUE THREAD

**Issue by rossanafmenezes** [Automattic/simplenote-electron#2273]
Fixing grammar errors using the Grammarly extension on the Simplenote Web app completely deletes the note after you close Grammarly pop-up.

### Expected

The corrections made on the pop-up would be applied to the actual note. 

### Observed

The whole note is deleted. Once you close the Pop-up you return to a completely blank note, including the note title

### Reproduced

1.created a new note using the Web app & add content.

2. Grammarly has some suggestions, that are underlined to improve the text (since it is an activated extension) symbol pops on the bottom right of the page to make corrections.

3. The note opens in a Grammarly pop up, to change the mistakes. The 1st draft, simple note page is on the back.

4. Made changes on the Grammarly pop up note.

5.clicked on the close icon on the right top corner.

![Screenshot 2020-08-11 at 10 52 37 AM](https://user-images.githubusercontent.com/30724184/89913028-3efa8d00-dbc1-11ea-97db-11e048218410.png)
![Screenshot 2020-08-11 at 10 52 48 AM](https://user-images.githubusercontent.com/30724184/89913045-4326aa80-dbc1-11ea-9fb5-30eeb3bab590.png)
![Screenshot 2020-08-11 at 10 53 19 AM](https://user-images.githubusercontent.com/30724184/89913071-4ae64f00-dbc1-11ea-8ced-9da3b6996e2f.png)
![Screenshot 2020-08-11 at 10 53 29 AM](https://user-images.githubusercontent.com/30724184/89913077-4de13f80-dbc1-11ea-8526-cacb5929b6fe.png)

### Where did you see the bug

The user only said they are using the Edge Browser and I'm asking for more information, but I was able to replicate the issue on my computer too, so:

- System Make: Chromebook
- OS: Google Chrome OS
- OS version: Version 84.0.4147.110 (Official Build) (64-bit)
- Browser (if applicable): Chrome
- Browser version (if applicable): Chrome 84 on Chrome OS 13099
- Simplenote app version: 1.20.0 (Web App)

Ticket: 3203148-zen

**Comment by erricgunawan** [comment]
Reported also on 3263656-zen

FWIW, I once had this issue myself. The note was disappearing on the web app.

But I managed to find them when I checked Simplenote on my other devices (both Android and iOS).

I suggested checking the same for this particular user and see if that would also work for them.

**Comment by belcherj** [comment]
This should no longer be an issue as the Grammarly extension is incompatible with the new web app. If you would like to use Grammarly I recommend app.simplenote.com/old.
