### ISSUE TITLE
Keyboard shortcut conflicts for beta

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-electron#2279]
### Expected

In Firefox, clicking command + L should focus the address bar. 

### Observed
Even with the option for keyboard shortcuts disabled, in Simplenote with the cursor active in the editor, the current line is selected instead of the address bar being focused on.

I'm not sure if this is just expected behaviour when in an editor mode though or a bug. I also replicated this in Chrome, but it's not an issue in the non-beta version (app.simplenote.com).

### Reproduced

1. Go to staging.simplenote.com in a Firefox browser
2. Disable the keyboard shortcuts option
3. Go to a note and activate the cursor in the editor
4. Click command + L to focus on the address bar.
5. The current line is selected.

![Screen Recording 2020-08-18 at 10 50 am](https://user-images.githubusercontent.com/10325627/90498924-cf484d00-e140-11ea-8b75-6220d8641ac2.gif)

### Where did you see the bug

- System Make: Apple
- System Model: Macbook Pro 13" 2019
- OS: MacOS 
- OS version: Catalina 15.5.5
- Browser (if applicable): Firefox
- Browser version (if applicable): 78.0.2 (64-bit)
- Simplenote app version: https://staging.simplenote.com/
- Reported in 3231675-zen

**Comment by dmsnell** [comment]
Folding into the existing item in #2148
