### ISSUE TITLE
Deletion confirmation

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [Automattic/simplenote-electron#2300]
### What
Hello! It would be great to have confirmation on note and tag deletion not to remove them accidentally.

### Why
It is not very convenient you can remove notes and tags accidentally.

**Comment by djordjeandrejevic** [comment]
There is a _**Trash**_ icon below _All Notes_ icon, where you could restore accidentally deleted notes.

However, I do agree that confirmation dialog would be useful to show up prior to deleting tag.

**Comment by codebykat** [comment]
Closing this for now but we'll take it into consideration in the future. Thanks!
