### ISSUE TITLE
EOL Characters on a list Caused App to Crash

### ISSUE THREAD

**Issue by erricgunawan** [Automattic/simplenote-electron#2309]
Creating a list with markdown, the EOL characters at the end of each line will cause the app to crash when it's opened there.

### Expected
It should not cause the app to crash.

### Observed
The app is crashed.

### Reproduced
1. Create a note on the web version on https://staging.simplenote.com/
2. Use markdown. At the end of each line, use "Enter" key and begin the next bulleted line.
3. Open the note in Simplenote iOS. 
4. Place the cursor near the end of a line, the app would then crash.

User added:

> I can eliminate the offending character at the end of a line by hovering way past the end of the line, and touch. The cursor is not visible, but I know it is at the end of the line. I then type a backspace and the cursor now appears at the end of the line and the app no longer crashes when I try to place the cursor at the end of the line

Reported on 3267142-zen with a sample note given there.

### Where did you see the bug
- System Make: -
- System Model: -
- OS: Windows
- OS version: 10
- Browser (if applicable): Firefox
- Browser version (if applicable): Firefox 77.0.1 64-bit 
- Simplenote device version: iOS 13.6.1 on iPhone Xs

**Comment by codebykat** [comment]
We got a review from an Android user that might be related: "Everything is fine and no brakes[sic]. Here are just paragraphs stick together in the browser version."

**Comment by codebykat** [comment]
After fixing #2548 I had a hunch this one might have been related, but I can't reproduce it. I tested on several notes, including on a note created on Windows (which would have `\r\n` line endings instead of `\n`). It's possible these line endings are properly handled in the iOS app now. Let's reopen if we get any further reports.
