### ISSUE TITLE
Facing some issues with Preview mode

### ISSUE THREAD

**Issue by KaikeWesleyReis** [Automattic/simplenote-electron#2310]
Hi, I'm using SimpleNote since 2019. My account was created in *Ubuntu 18.04*. There my **Preview mode** works fine: if I create a note there, my **preview** will appears just fine. But in *Windows 10* the preview mode just appears for old notes (created in Ubuntu) and not for the new ones.

### Expected
Discover why this is happen! I think that is a minor issue, but a trick one.

### Observed

Here is what I see when I use my account in *Windows 10*:
- Note created in *Ubuntu 18.04*:
![image](https://user-images.githubusercontent.com/32513366/91719364-8f835b80-eb6b-11ea-9b0b-78fdc017eb21.png)
- New note created in *Windows 10* (preview icon is just missing):
![image](https://user-images.githubusercontent.com/32513366/91719399-a629b280-eb6b-11ea-85fa-bbd2011e4706.png)

And if I use preview shortcut `Ctrl + Shift + P` nothing happens.

### Reproduced

1. Basically, have an account in *Ubuntu* and try to use it in Windows.
2. Try to use preview in a new note

### Where did you see the bug

- System Make: ---
- System Model: ---
- OS: Windows
- OS version:  10
- Browser (if applicable): Brave / Chrome
- Browser version (if applicable): ---
- Simplenote app version: 1.21

**Comment by dmsnell** [comment]
Hi @KaikeWesleyReis - thanks for writing in. It looks like the new notes need to have Markdown formatting enabled. Try opening the note info panel (the ⓘ icon in the top right) and look for the Markdown toggle. If this doesn't fix your issue please reach out to our support at support@simplenote.com

**Comment by KaikeWesleyReis** [comment]
@dmsnell Thanks for the answer! Now seeing the solution, I feel that I was some kind dumb hahaha

Again, thanks!
