### ISSUE TITLE
Web App Unresponsive Due to "Quota Exceeded" Error

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/simplenote-electron#2311]
I spent 30 minutes working on a note in the web app last night before noticing that the **New Note** button wasn't responsive. I did a hard refresh on the page, which led to the 30 minutes of work on the note I'd done disappearing. 

The work wasn't accessible from the note's **History** and it couldn't be found anywhere else, such as another device I use Simplenote on or the **Trash**. The **New Note** button remained unresponsive, as did the **Trash** button, and edits I made to _any_ note simply weren't saving. 

### Expected

I expected the work I'd done to be correctly synced, as I've never had any issues when working directly from the web app before. There was no warning or indication that anything was wrong, so I was taken by surprise. If I didn't have a form recovery extension in my browser, 30 minutes of work would have been lost.

### Observed

Chrome's Console showed a `DOMException: Quota Exceeded` error:

<img width="1438" alt="Screenshot 2019-11-15 at 09 05 28" src="https://user-images.githubusercontent.com/2998162/68931267-16f01180-0788-11ea-9bc4-220b76945f9c.png">

Expanded details of the `TypeError: Cannot read property 'id' of undefined` error from the screenshot:

<img width="1436" alt="Screenshot 2019-11-15 at 09 06 46" src="https://user-images.githubusercontent.com/2998162/68931271-19eb0200-0788-11ea-895c-80bff1677f7b.png">

### Reproduced

Simplenote was only unresponsive in Chrome, it worked as expected in Firefox and Safari. The web app started working as expected again in Chrome after clearing the cache, though the work I'd done was still gone from the app. 

I'm not sure if this is known issue that just falls under "things that happen every so often". I still wanted to report it though, as losing work with no warning or indication can be jarring. Is there any way to avoid this happening or, if not, provide warnings when users are close to running out of disk space?

Make|Model|OS Version|App Version
-|-|-|-
Apple|MacBook Air|macOS 10.14.5 / Chrome 78.0.3904.97 | app.simplenote.com / web app

**Comment by codebykat** [comment]
Closing for lack of recent reports, if someone runs into this again we can troubleshoot it.
