### ISSUE TITLE
[rewrite branch] issues with printing

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2317]
Printing this test note: http://simp.ly/p/Sr5Wc8 in Firefox/OSX results in this odd behavior for the last two pages:

<img width="845" alt="Screen Shot 2020-09-01 at 10 47 41 PM" src="https://user-images.githubusercontent.com/52152/91936743-53541600-eca5-11ea-91cd-b221dd7fabe6.png">

<img width="672" alt="Screen Shot 2020-09-01 at 10 47 35 PM" src="https://user-images.githubusercontent.com/52152/91936760-5949f700-eca5-11ea-8f12-c91be1d03e27.png">

The first 22 pages look normal! Here's what the note looks like in the editor:

<img width="956" alt="Screen Shot 2020-09-01 at 10 49 57 PM" src="https://user-images.githubusercontent.com/52152/91936831-81395a80-eca5-11ea-8e20-830df4b029f8.png">

I have also seen printing cut text off at the end like this, I can't reproduce it at the moment but it's something else to watch out for:

<img width="948" alt="Screen Shot 2020-08-27 at 12 46 27 AM" src="https://user-images.githubusercontent.com/52152/91937031-eee58680-eca5-11ea-9297-673c18464acb.png">

### Expected
Should print the entire note as laid out in the editor.

### Observed
Last two pages have a very narrow width and print with one word per line.

**Comment by codebykat** [comment]
Adding to this that Markdown preview only prints the first page.

**Comment by codebykat** [comment]
Just re-tested this and it's better! But there's a stray "0" at the very end.

Edit: Only in Firefox, not in Chrome :/

Edit again: Now I can't reproduce it anywhere 🤷‍♀️ 

<img width="1093" alt="Screen Shot 2020-09-03 at 12 44 50 PM" src="https://user-images.githubusercontent.com/52152/92160055-463d4100-ede3-11ea-9f29-e6a11bf99814.png">

**Comment by dmsnell** [comment]
>But there's a stray "0" at the very end.

This is probably from some JSX check like `{ someArray.length && …` or `count && …` as the `0` value becomes falsey and JSX renders the `0`

**Comment by codebykat** [comment]
Haven't seen this in awhile, assuming fixed.
