### ISSUE TITLE
Export and Pring Dialogues do not show Text Correctly

### ISSUE THREAD

**Issue by rafaelhlima** [Automattic/simplenote-electron#2325]
I have been using SimpleNote for my work as a professor, taking notes for lectures and student supervising. However I haven't been able to export or print them because the dialogues are somewhat broken. In truth I think it is some kind of character encoding issue.

I am using the Snap version of Simplenote on Ubuntu 20.04.1. My system language is English, but the dialog appears as in the image below:

![Simplenote_Bug](https://user-images.githubusercontent.com/65458584/92271231-d0f26e80-eebd-11ea-80f0-3661efe625d9.png)

### Expected

The dialogues should appear in English, instead of these square characters.

### Observed

Both the Print and Export dialogues show this issue. However, the Import and Preferences dialogues do not show the same bug.

### Reproduced

1. Write a note
2. Go to File -> Print
3. See the broken dialog

### Where did you see the bug

- System Make: Ryzen 7 3700X 8 core / 16 threads; 16Gb or RAM; Nvidia graphics
- OS: Ubuntu
- OS version: 20.04.1
- Browser (if applicable): Not applicable
- Simplenote app version: 1.21.1
- Packaging format: Snap

**Comment by dmsnell** [comment]
Hi @rafaelhlima - thanks for writing in. We don't build or support the Snap distribution of Simplenote so we may be limited in what we can do here. It looks like that's the native system print dialog and yeah, I think you're right about the encoding issue.

We produce [a `.deb` package](https://github.com/Automattic/simplenote-electron/releases/latest) you might be able to use and try out. Another thing that could try is running `locale` in a console/terminal and see if anything looks out of place. If your system language is English I'm not sure what encoding issue could be behind that issue.

Maybe there's a font problem with the Snap distribution. I found a few issues in the Snap forums related to this very problem - you may have more luck reporting the bug there.

 - https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/17
 - https://forum.snapcraft.io/t/missing-fonts/4639
 - https://forum.snapcraft.io/t/trouble-running-remmina-with-connection-to-gnome/7736/6

**Comment by rafaelhlima** [comment]
I think I'll try the deb version instead.
Thanks for your prompt reply!
