### ISSUE TITLE
Web app: Strange cursor behavior with lists

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#2336]
### Expected
When hitting enter after a list item where list items follow, the cursor jumps 2 lines down, only on the web app. This does not happen on the desktop Electron apps or the native Mac app.
On the other apps, hitting enter twice after a list item removes the hyphen and the cursor doesn't move to a new spot.

### Observed
I included video below. If you hit enter twice after the end of one bulleted list item, the cursor jumps down unexpectedly. I can reproduce this consistently.

![listt](https://user-images.githubusercontent.com/31680407/93369993-27e13780-f81e-11ea-8c08-4e9498616fc8.gif)]

### To Reproduce

1. log into the web app (new version)
2. set up a bulleted list with at least 3 items
3. Place cursor at the end of item 1 and hit enter twice
4. The cursor will now be in front of the last item

### Where did you see the bug

I replicated this using: 

- MacOS 10.14.6
- Browser: Chrome Version 84.0.4147.105
- Simplenote 2.0.0-rc3

reported in 3314070-zen:

- Windows 10 home
- Firefox v79.0

**Comment by dmsnell** [comment]
Thanks for the report @msilbers.

Notes:
Check on the list continuation. If I remember properly it checks if we had two newlines in a row but doesn't check if the next line has content in it or is a list. Hopefully we need to do little more than go to that condition and verify its behavior.

**Comment by codebykat** [comment]
Verified this is still an issue
