### ISSUE TITLE
Note selection is not reset when switching to Trash

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2342]
When switching to Trash with a note open, the note selection isn't reset.

Reported in 3306162-zen:

> many times when I go to "Trash," it displays the contents of the last regular note viewed, giving the FALSE and momentarily disturbing IMPRESSION that the note had been sent to -- and is sitting in -- Trash.

### Expected
* Select the first note in the Trash, to mirror the behavior when switching back to All Notes with a trashed note open

### Observed
* Note selection is not changed

**Comment by belcherj** [comment]
Is this still an issue after https://github.com/Automattic/simplenote-electron/pull/2349

**Comment by codebykat** [comment]
Fixed now 👍
