### ISSUE TITLE
Should it be possible to edit tags on a note in preview mode?

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2343]
@SylvesterWilmott ?

My instinct is it seems strange because a note in preview mode isn't "editable" but I guess it is kind of a feature?

**Comment by SylvesterWilmott** [comment]
I think we should either allow tags to be editable or simply hide tags altogether when in preview mode. Since this "feature" already exists both on Electron and macOS, I'd be hesitant to remove it.
