### ISSUE TITLE
Note display: number of lines vary for Expanded display 

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#235]
Is Expanded 4 lines? I forgot what we decided.

It seem strange that some notes don't have 4 lines even though there is more text.

![screen shot 2016-03-18 at 10 15 30 am](https://cloud.githubusercontent.com/assets/618551/13882219/93be01ea-ecf2-11e5-826b-78a8d58c324c.png)

**Comment by drw158** [comment]
Another example 

![screen shot 2016-03-18 at 10 18 58 am](https://cloud.githubusercontent.com/assets/618551/13882297/e34fe9e4-ecf2-11e5-9be6-5b7a2090f869.png)
