### ISSUE TITLE
Update to 1.21.1 halts

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2364]
### Expected
I want to Update from 1.14.0 to 1.21.1

### Observed
Installation 1.21.1 halts. Nothing moves for minutes/hours.
I cannot restart Simplenote at all.

### Reproduced

**1) Installation of  1.21.1 halts. Nothing moves for minutes/hours:**
![simplenote 1 21 halt](https://user-images.githubusercontent.com/22197180/94462056-3e42a800-01bb-11eb-9a93-fbce4885aa13.JPG)

**2) I try to de-install te existing installation(s).**

I see that in "Apps" ther are two available (why?):

![simplenote zh_1 14](https://user-images.githubusercontent.com/22197180/94462191-6df1b000-01bb-11eb-9ab6-04f6a7c377b9.JPG)

None of them can be de-installed:

![simplenote zh_deinst](https://user-images.githubusercontent.com/22197180/94462237-7ea22600-01bb-11eb-90d4-84bcd0d7dcb3.JPG)

![simplenote zh_deinst_1 14](https://user-images.githubusercontent.com/22197180/94462250-84980700-01bb-11eb-807e-fc6b9ef6f6e8.JPG)

**3) I cannot re-start Simplenote at all. Dead-lock.**

### Where did you see the bug
Windows 10

**Comment by dmsnell** [comment]
I wonder if this has to do with the space in the filename. `Uninstall Simplenote.exe`

**Comment by gubrist** [comment]
Both pathes are gone:

C;\Program Files (x86)\Simplenote\....

and 

C;\Program Files\Simplenote\....

**Comment by gubrist** [comment]
Where can I get (and try) the installer of the previous Windwos Version?

**Comment by gubrist** [comment]
I got the reply from Simplenote Support:

I have downloaded the Simplenote App (1.21.1) for the first time from Windows store
and it has worked out 👍

PS:
You can find the (previous) Simplenote Windows releases here: 

https://github.com/Automattic/simplenote-electron/releases

**Comment by gubrist** [comment]
I have seen that Simplenote App 2.0 is available 😊
- This dowloaded update file does not work either on my PC.

What has to be done that 2.0 will be available on Windows store as well?
- currently only 1.21.1 is availbale
