### ISSUE TITLE
Electron Todo

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#2367]
- [ ] Spellcheck
- [x] Unsync'd notes close dialog #2277 
- [x] Find in note from menu doesn't work #2370

**Comment by codebykat** [comment]
> Find in note from menu doesn't work

lol whoops.

Here's the fix for that, and some other things: https://github.com/Automattic/simplenote-electron/pull/2370

**Comment by belcherj** [comment]
closing since we have: https://github.com/Automattic/simplenote-electron/issues/2410
