### ISSUE TITLE
Revisions Issues

### ISSUE THREAD

**Issue by belcherj** [Automattic/simplenote-electron#2368]
When I create a new note I have seen revisions shows history as unavailable. Additionally you cannot dismiss the tooltip
<img width="171" alt="Screen Shot 2020-09-29 at 12 41 14 PM" src="https://user-images.githubusercontent.com/6817400/94589824-c5435f00-0253-11eb-9daf-e5a0021721f8.png">

I have also seen the revisions slider only have the current and one other revision when in another browser I see more revisions.

**Comment by codebykat** [comment]
Ooh I saw the very sticky tooltip too.

**Comment by belcherj** [comment]
History unvail occurs when you have a new note. After a refresh, you have the history.

**Comment by codebykat** [comment]
<img width="613" alt="Screen Shot 2020-10-23 at 1 25 14 PM" src="https://user-images.githubusercontent.com/52152/97053261-7083c300-1537-11eb-92fe-4aefb45955c7.png">

Don't know if this is related but I saw another undismissable tooltip for New Note just now.

**Comment by codebykat** [comment]
Closing in favor of #2464
