### ISSUE TITLE
Settings: eliminate need for the modal

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#237]
I don't know why I just noticed this, but it seems strange that you can edit display settings in the Settings modal and in the View menu. You have to first go to Simplenote > Preferences, and then click on the Display tab.

Because the display settings are in the menu, the Settings modal isn't really needed. We can:
- Put a `Log Out` menu item under Simplenote > Account (or something)
- Put an `Edit Account` menu item under Simplenote > Account
- Put the Enable Markdown option in Simplenote > Enable Markdown

This would eliminate the need for the Setting modal entirely for the packaged apps.

![screen shot 2016-03-18 at 10 33 28 am](https://cloud.githubusercontent.com/assets/618551/13883138/257a848e-ecf6-11e5-8469-f523656650b2.png)

**Comment by drw158** [comment]
Ideas for the menu:

![screen shot 2016-03-18 at 11 16 44 am](https://cloud.githubusercontent.com/assets/618551/13884315/84351cf0-ecfb-11e5-8f45-547a4d2df374.png)
![screen shot 2016-03-18 at 11 14 23 am](https://cloud.githubusercontent.com/assets/618551/13884343/8a2643a0-ecfb-11e5-9404-02f0fc759bef.png)

**Comment by dmsnell** [comment]
@drw158 what would appear on the `Edit Account` action? the Account modal?

I'm all for this although it does break functionality when running in the browser instead of Electron (may not matter too much). If we wanted we could keep it there but still add the menu options.

How do we want to differentiate when running in Electron vs in the browser?

**Comment by drw158** [comment]
Edit Account would be the same as it is now. It would open up a browser window, take you to https://app.simplenote.com/settings

Ideally we could keep the code in there, and display when we need it if/when we release it for the web.

Looking at this now, I would probably create a new menu for Markdown, maybe Format > Enable Markdown.

Another idea, which I don't think we'd need unless we add a lot more settings:

![screen shot 2016-11-07 at 2 10 22 pm](https://cloud.githubusercontent.com/assets/618551/20074050/53ffcc86-a4f4-11e6-9ed3-3515f856090d.png)
(a separate native window)

**Comment by dmsnell** [comment]
Showing a web view would mean people couldn't adjust their settings offline. Did you intend on implying this?

**Comment by drw158** [comment]
Nope, edit account is just for changing account info. They'd still be able to edit settings in the electron app via the menu bar. 

By "keep it in there" I meant keep the modal code in the repo and enable it once we need it for a web release.

**Comment by bummytime** [comment]
Ref: #1268

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
