### ISSUE TITLE
Can't log into production

### ISSUE THREAD

**Issue by moniuch** [Automattic/simplenote-electron#2377]
### Expected

Should be able to log in to app.simplenote.com

### Observed

Can't log into app.simplenote.com. Cleared all cookies. Did not clear Application > IndexedDB. Timeout errors

![image](https://user-images.githubusercontent.com/681956/94717719-f9e91080-0350-11eb-9d85-3a39b8660c80.png)

Page loading infinitely. Stuck at waiting for "www.google.com"
Need to use staging.*

### Reproduced

1.
2.
3.

### Where did you see the bug

- System Make:
- System Model:
- OS: Win
- OS version: 8.1
- Browser (if applicable): Chrome
- Browser version (if applicable): Chrome 85 64bit
- Simplenote app version:

**Comment by belcherj** [comment]
Interesting. The login code is exactly the same for app and staging. Can you try clearing the app entirely? 

Chrome Dev Tools > Application > Clear storage > Clear site data

We will try to debug further on our side.

**Comment by codebykat** [comment]
Thanks for the report, @moniuch. The only thing we use google.com for is the reCaptcha verification that prevents bots from submitting the form, and if it's waiting on www.google.com, that would indicate that your system is not able to make a connection to Google's servers for some reason. Additionally staging.* and app.* are currently the exact same code so it's bizarre that staging works!

I'm wondering if it could have been a temporary internet glitch or an outage with the reCaptcha servers. Are you still unable to log in now? Are you behind any kind of firewall, or using any browser extensions that might be blocking traffic to google.com (something along the lines of an ad-blocker or VPN)? Can you test it on another browser or internet connection and let me know if you see the same behavior?

You could also try clearing the app entirely, with `Chrome Dev Tools > Application > Clear storage > Clear site data`.

**Comment by moniuch** [comment]
Must have been a temporary glitch, sorry for bumping up your blood pressure!
Simperium config: Production

**Comment by codebykat** [comment]
No worries, I can skip that second cup of coffee today 😁
