### ISSUE TITLE
Word-wrapping crashes in Chrome (advanced wrapping) on very long lines

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#2382]
Reported in #3371757-zen

App failed to open, showing duplicated text and crashing with this error:

```
DOMException: Failed to execute 'setStart' on 'Range': The offset 370952 is larger than the node's length (65536).
```

This did not occur in Safari or Firefox and the line was extremely long. After cleaning up the line so it wasn't super long the app loaded fine in Chrome. I'm guessing this is a bug in the `advanced` word-wrapping strategy.

**Comment by codebykat** [comment]
I can't reproduce this, four years later.
