### ISSUE TITLE
Markdown Checkboxes are non interactive

### ISSUE THREAD

**Issue by SephReed** [Automattic/simplenote-electron#2390]
### Expected
When making a markdown checkbox and clicking it, the checkbox should be toggled.  An "x" character should be added to the document.  Like this:

- [ ] click me

### Observed
Nothing happens

### Reproduced

1.  add some markdown `- [ ] Click me`
2. switch to markdown preview mode
3. click the checkbox

### Where did you see the bug

- System Make:
- System Model:
- OS: MacOS
- OS version: 
- Browser (if applicable): Brave
- Browser version (if applicable): Updated recently ~month
- Simplenote app version:

**Comment by rossanafmenezes** [comment]
Also reported here 3430664-zen 
Simplenote app on Ubuntu 18.04.5
Asking for confirmation on Simplenote version

Edit: User confirmed version 2.0.0 on a Dell Latitude 7300.
