### ISSUE TITLE
Add "Sign in with Apple" ID & "Sign in with Google" Account Option

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#2393]
### What
***Add "Sign in with Apple" ID & "Sign in with Google" Account Option***

### Why
***Without friction, cross platform, easy & password less sign in for Simplicity***

**Comment by theck13** [comment]
I've added **_Sign In with Apple_** to our feature requests.  **_Sign In with Google_** is already being tracked as a feature request.
