### ISSUE TITLE
Emojis duplicated when inserted via macOS character palette

### ISSUE THREAD

**Issue by guarani** [Automattic/simplenote-electron#2394]
### Expected
On the web, when I add an emoji/character via macOS character palette (by invoking `＾⌘ + Space`), the item I select is duplicated.

### Observed

On the web, when I add an emoji/character via macOS character palette (by invoking `＾⌘ + Space`), the item I select is duplicated.

Backspacing to delete certain emojis such as 🙅‍♂️ changed their skin tone before another backspace deleted them.

<img width="500" alt="gif showing emojis duplicated upon insertion" src="https://user-images.githubusercontent.com/1898325/95881030-8383df80-0d4e-11eb-85b1-a73f5e621949.gif">

### Reproduced

1. Open a note
2. Add an emoji/character via macOS character palette (by invoking `＾⌘ + Space`)
3. Notice the selected item is added to the note but is duplicated 

### Where did you see the bug

- System Make: Apple
- System Model: MacBook Pro 2019
- OS: macOS
- OS version: 10.15.6 Catalina
- Browser (if applicable): Firefox
- Browser version (if applicable): 81.0.1
- Simplenote app version: Version 2.0.0-beta1

Found while testing https://github.com/Automattic/simplenote-ios/pull/906

**Comment by dmsnell** [comment]
This is a known issue we're working on upstream in #2327 - it should only exist in Firefox and Firefox-based browsers.
