### ISSUE TITLE
Copy note Internal Link not working on Firefox

### ISSUE THREAD

**Issue by guarani** [Automattic/simplenote-electron#2395]
### Expected
The Copy button next in the Info pane next to Internal link should copy the link to my clipboard on Firefox.

### Observed
The Copy button next in the Info pane next to Internal link does not copy to my clipboard on Firefox.

Note: This works on Safari (and possibly other browsers)

### Reproduced

1. Open https://app.simplenote.com/ on Firefox
2. On a note, open the Info pane
3. Click the Copy button next to the Internal Link
4. Pasting the clipboard contents doesn't work

### Where did you see the bug

- System Make: Apple
- System Model: MacBook Pro 2019
- OS: macOS
- OS version: 10.15.6 Catalina
- Browser (if applicable): Firefox
- Browser version (if applicable): 81.0.1
- Simplenote app version: Version 2.0.0-beta1
Discovered while testing https://github.com/Automattic/simplenote-ios/pull/906

**Comment by codebykat** [comment]
I'm seeing this in Firefox as well.

**Comment by codebykat** [comment]
It's still working for me on Electron, so not urgent to get the fix in for 2.0. I will take a look at it next week.
