### ISSUE TITLE
Development: Can't log in to local development server

### ISSUE THREAD

**Issue by tbourrely** [Automattic/simplenote-electron#2396]
Hi, I have difficulties to run the app so I can contribute.

### Expected
To be connected after entering username and password

### Observed
After entering my credentials, I can briefly see the home screen, but after less than a second the app is refreshed and I am disconnected from it.

### Reproduced
1. Enter credentials
2. Click "Log in"

I tried it with an instance started with `npm run dev` and a build created with `make package-osx`

![gif](https://user-images.githubusercontent.com/16355046/95984508-99170900-0e23-11eb-809b-4297b03ca5d1.gif)

### Where did you see the bug

- System Make: GNU Make 3.81
- System Model:
- OS: MacOS
- OS version: 10.15.7 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: develop branch
- Node version : v14.13.1
- NPM version : 6.14.8

**Comment by dmsnell** [comment]
@tbourrely can you check if this is also happening to you on the web at https://app.simplenote.com?

it looks like there might be another issue going on and if you have the same thing happen in a browser I'd recommend that you contact our support in order to clear it up - support@simplenote.com

**Comment by tbourrely** [comment]
@dmsnell I can not replicate the problem on the production webapp. (But I can in local when I try to connect to localhost:4000).

**Comment by tbourrely** [comment]
I tried to run (with `run dev`) the project from different tags : 
- v2.0.0-beta1 : not working 🚫 
- v2.0.0 : not working 🚫 
- v1.21.1 : working ✅ 

After running `git bisect`, the first commit to fail on my env seems to be : [fc8921291b6b702db35b076d65e4632203ff4574](https://github.com/Automattic/simplenote-electron/commit/fc8921291b6b702db35b076d65e4632203ff4574)

**Comment by dmsnell** [comment]
we have #2389 open already but it's usually an issue where you have to login twice - it doesn't repeatedly kick you out, which is how I interpreted this issue. can you also confirm that you are unable to login even after multiple tries?

thanks for checking with the web; this is a bug with the app.

> After running git bisect, the first commit to fail on my env seems to be : fc8921291b6b702db35b076d65e4632203ff4574

that was a giant change that rewrote a large part of the app. unfortunately it's also 13k lines of code and unlikely to be too helpful in debugging this. we might start looking though around `boot-with-auth`, `boot-without-auth`, and `boot` to see what's going on. Could be a cookie issue since Electron and the browsers handle cookies differently.

If you can login after a second or third attempt we'll close this as a duplicate report of #2389

**Comment by tbourrely** [comment]
I can confirm you that even after multiple attempts, I still can't login. Your interpretation is correct, I am repeatedly kicked out after correctly submitting the login form 😆 

I'll try to get my head around the `boot-*` parts, thanks for the tips

**Comment by tbourrely** [comment]
I have been able to investigate a little bit more. I found out that I am logged out because of the line https://github.com/Automattic/simplenote-electron/blob/1d70830641ec07754593818625a775a77b1410f6/lib/state/simperium/middleware.ts#L54

Another thing I noticed is that in the app localStorage, the accountName value (in the simpleNote key) is : `{"msg": "Token Invalid", "code": 401}`

May have I missed something when creating my test account from the app ?

**Comment by dmsnell** [comment]
that `Token Invalid` message is clearly wrong there and a good find @tbourrely.

We can also try to investigate this but I don't have any way to estimate if we can do it right away.

> May have I missed something when creating my test account from the app ?

The app should have registered this and prevented you from logging in. I don't understand (from my memory) how that error could have been persisted in `localStorage` but we're probably missing some check that the returned token is valid.

the public test app works just like the normal app except you can't publish or share notes. if you think something was corrupted with that account try wiping your browser cache and creating a new account. Electron occasionally persists its cache - you can double-check in the browser when running the dev server at http://localhost:4000

**Comment by lulupointu** [comment]
I have the same issue. I tried clearing the cache, logging in in the app or the browser, creating a new dev account, logging in multiple times, I get logged out every time.
For what's it's worth my friend tried too and he has the same issue.
My config: Ubuntu 20.04, simplenote v2.1.0-beta2
His config: Manjaro, simplenote v2.1.0-beta2

**Comment by zemariagp** [comment]
exact same issue here, simplenote 2.4.0-beta2 on mac os X catalina

**Comment by dmsnell** [comment]
found the issue: it was my mistake back a few months ago, sorry about that.

when we are initializing Simperium we're using the wrong app name, regardless of what's in the local config. fixing this involves going back to using the config value, which I have proposed in #2536

**Comment by codebykat** [comment]
There was a similar report in 3588107-zen, I asked them to try the fix in #2536
