### ISSUE TITLE
Host deb file online for easy update in linux

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#2401]
### What
***Every time when we update simplenote we have to manually download simplenote's deb file and re install it. We can't update the package automatically from command line.  Which is a lengthy process, make it simple***

### Why
***Host simplenote's deb file online like Google Chrome or Typora's deb file. So that we can easily update simplenote with `sudo apt update && sudo apt upgrade` command***

**Comment by dmsnell** [comment]
Hi @rahul8548 - this is something not entirely within our control. If you are running Debian or Ubuntu you might try filing an issue with their repositories. We don't have the resources to make sure Simplenote is in each of the many many Linux distributions' own repositories and system, but we're happy to help any maintainer who wants to include us.

**Comment by ghost** [comment]
You can create your own apt repository over HTTP @dmsnell @belcherj 

Basically you can put your deb files in http root, create a Release file (that contains package information of all the debs) and that's it.

These links might help you.

https://help.ubuntu.com/community/Repositories/Personal
https://www.percona.com/blog/2020/01/02/how-to-create-your-own-repositories-for-packages/
