### ISSUE TITLE
Github.com style image upload with markdown link feature

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#2411]
### What
***Github.com style image upload with markdown link feature in simplenote***

### Why
***Simplenote already support markdown. Now it will be great to have github's markdown link style image upload in simplenote***

**Comment by codebykat** [comment]
Hi @rahul8548, thanks for this suggestion! I've noted it for future consideration. Image uploads are a frequent request and one that we're thinking about, but it's not on our immediate roadmap. I'm closing this issue as we only use GitHub to track bugs and active projects.
