### ISSUE TITLE
Conflict with Ctrl+G Keyboard Shortcut in Windows 10 Desktop Version

### ISSUE THREAD

**Issue by illusaen** [Automattic/simplenote-electron#2413]
Ctrl+G works when focused in search sidebar to "Jump to next match in note". However, when focused on the editor part, it opens the "Goto Line" dialog.

This means that when searching, jumping to next match in note only works once as it focuses the editor once it goes to the first match when in Windows 10 Desktop V2.0.0.

Inspired from 3424483-zen.

### Expected
Consistent behaviour with the Ctrl+G shortcut -- either it always brings up "Goto line" or always "Jump(s) to next match in note".

This happens *correctly* on the browser version but *not* in the W10 version.

### Observed
Jumping to next match in note only works once as it focuses the editor once it goes to the first match.

### Reproduced
1. Open Simplenote on Windows 10, specifically v2.0.0.
2. Type text into a note.
3. Search for word.
4. Press Ctrl+G.
5. Press Ctrl+G again.

### GIF
![Simplenote-W10-Desktop-CtrlG](https://user-images.githubusercontent.com/13263478/96914447-a444e700-146a-11eb-8cba-fda6c70eafda.gif)

### Where did you see the bug
- System Make: VMWare Fusion
- OS: Windows 10 x64
- Simplenote app version: 2.0.0

**Comment by belcherj** [comment]
This was resolved by https://github.com/Automattic/simplenote-electron/pull/2402 and will be in the next version.
