### ISSUE TITLE
Windows 10 IME offset position

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-electron#2416]
### Expected

Opening the IME dropdown options should display the available selections bellow where the cursor is.

### Observed

Two users have reported that the line conversion doesn't align with the cursor on Windows 10 using the built in IME. 

### Reproduced

I was not able to reproduce this myself, but one user mentioned the following steps:

1. Stat Simplenote for the first time. 
2. Can't input Japanese IME inline.
3. Move to another window and then return to Simplenote.
4. Now you're able to input Japanese.

Screenshots available in ticket 3424483-zen

### Where did you see the bug

Windows 10, Desktop app downloaded directly from GitHub, version 2.0.0. 

Additional details reported in 3424136-zen: 
This wasn't working on 1.15.0 when you originally reported the issue.
When you updated to 1.20.0 the issue was fixed and it worked correctly.
When you updated to 2.0.0, the issue returned.

**Comment by codebykat** [comment]
Pasting from the ticket:

> Immediately after starting Simplenote, I think the language environment ignores the value of the OS system, Isn't it because it is forcibly fixed in the English environment?
> Therefore, if you first try to enter Japanese characters in the search box, you may end up with system line conversion  instead of inline conversion

We are not forcibly setting the language to English via a `DOCTYPE` or `lang` declaration, so it isn't that.

I don't really understand the screenshots provided, I'm still experimenting. It does all seem okay on OSX:

<img width="242" alt="Screen Shot 2020-10-23 at 12 23 00 PM" src="https://user-images.githubusercontent.com/52152/97045546-c3a34900-152a-11eb-8454-8d99ec3e192e.png">

**Comment by reginabally** [comment]
Another report related to Windows IME input for the Japanese (and Chinese) characters in 3473496-zen. 

The environment is:
Windows 10 Pro 1909 Build 18363.1198
Windows App, v. 2.0.0

Same issue on the web app with
Microsoft Edge x64 86.0.622.63

> I use the standard Microsoft IME, and it (at least the Japanese one) does not provide a discrete version number. Apparently, it depends on the version of OS, and different versions of Windows provide slightly different versions of Japanese IME.

> As far as I tried, I encountered the same issue with Chinese IME. I guess that's because both languages have Chinese characters, and typing them involves a conversion process I explain below.

> Perhaps you need to know how the Japanese IME works. It has two modes: half-width mode to input alphabet, and full-width mode to input characters proper to Japanese and Chinese. The problem occurs only in full-width mode. Similarly, Chinese IME has two modes to type alphabet and Chinese characters, and the problem occurs in the latter mode.

> When your IME is set to the Japanese one, the indicator to show the mode appears in the right side of the status bar. The indicator generally shows three state: "あ" "A" "x". When it shows "x", you need to click any textbox so that you are ready for typing. Then it will show "あ" or "A", and you can click it to toggle two modes of IME, which you need to set to "あ" (or right-click to select from five modes, which you should choose "Hiragana/ひらがな").

> In this mode, the text you are typing is in an unconfirmed state at first. For example, when you type "kyou", "きょう" will appear in the text field, but in an unconfirmed state with an underline. You can hit a space key to convert it to the text with Chinese characters. In our example, "きょう" can be converted into some homophone words such as "今日", "京", etc. When you choose the correct one, you hit the enter key to confirm it.

> Apparently, the new Simplenote fails to handle this unconfirmed state. After the inputting text (unconfirmed state) reaches the end of line and you continue typing, the text goes through the invisible border instead of going to the next line. Simultaneously, the overflowing part of text is duplicated in the next line. When the text reaches the border of the window, the entire text field begins to go to the left. And when you hit the enter key to confirm the text, the entire phenomenon disappears and everything goes back to normal.

> I think I do not use any unusual options for IME.

![2020-11-09](https://user-images.githubusercontent.com/40906847/99025431-c8946f00-25a3-11eb-8b2d-2c5ce44927fe.png)

**Comment by azollafox** [comment]
Also reported on Windows 10 Pro 64bit Ver.1909, Firefox 83.0.
https://d.pr/v/IYQNC4 3508026-zen

**Comment by tarunvijwani** [comment]
The issue exists in  Simplenote 2.1.0 as well.

3523744-zen

**Comment by codebykat** [comment]
Tracking all of these in #2522
