### ISSUE TITLE
slider button size too small when there are many notes

### ISSUE THREAD

**Issue by alusiani** [Automattic/simplenote-electron#2417]
### What

Please do not reduce the size of the slider button to less than about 1 times the size of a character, or more, when there are many notes.

### Why

When there are many notes, the slider button in the main view becomes too smal (about 1/4 of a character height), scarcely visible and difficult to click with the mouse.

### How

The slider button size apparently scales as the ratio between the number of note titles inside the current view over the total number of notes. Just stop decreasing the slider button size below a reasonable value.

**Comment by codebykat** [comment]
Good catch, thanks @alusiani. We'll have a fix in the next version.
