### ISSUE TITLE
Search highlight isn't working with Ctrl + G (Find Next/Again)

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-electron#2420]
Before updating the app to version 2.0.0, pressing Ctrl + G after performing a search on the app will highlight the search keyword in a darker color (e.g. brown), but this isn't working now.

### Expected
I would expect the highlighted keyword will show a distinct color from the other search keywords.

### Observed
The highlighted keyword shows the same color with the other search keywords.

### Reproduced

**Note:** The issue was originally reported in 3424483-zen but I was able to replicate this on the Simplenote web app.

1. Go to https://app.simplenote.com
2. Type a keyword to search the notes on the search box
3. Open up a note under the search result
4. Press Ctrl + G to highlight the search keyword
5. See that the color of the highlighted search keyword is the same with the other keywords

**Screen recording**

![Screen Capture on 2020-10-26 at 13-48-58](https://user-images.githubusercontent.com/40906847/97137978-1af72280-1792-11eb-82dc-eee82a50d306.gif)

**Screenshot shared in 3424483-zen**

![hhcbbpndidnnncln](https://user-images.githubusercontent.com/40906847/97137868-d1a6d300-1791-11eb-8951-a2a08f738f8b.jpg)

### Where did you see the bug

**Information shared in 3424483-zen**
- OS: Windows
- OS version: Windows 10
- Simplenote app version: 2.0.0

**Information for the test on Simplenote web app**
- OS: macOS
- OS version: 10.15.7
- Browser version: Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by reginabally** [comment]
Notice this should be fixed as mentioned in https://github.com/Automattic/simplenote-electron/issues/2413 so closing this.

**Comment by rezzap** [comment]
A user in 3775609-zen is reporting that this is an issue again since version 2.2.0 on Windows. Is it expected that this would be working now? 

Re-opening it for testing. 

Simplenote v2.7.0 Windows desktop ver.
Windows10 Pro x64 v20H2

**Comment by pachlava** [comment]
@rezzap I confirm that this is not working on Windows. (Simplenote 2.7.0 | Win10).

'Ctrl+G' shortcut is not working, however the menu item (Edit ~> Find Again) does.

@codebykat since current issue was reopened, but already had some history and milestone etc... does it make sense to open a new one?

**Comment by codebykat** [comment]
I think I have a fix.
