### ISSUE TITLE
Windows App Unresponsive to Clicks to Exit

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-electron#2421]
### Expected
When I click on the X button or go to Simplenote>File>Exit I should be able to close the application. 

### Observed
I can only close the new Simplenote by killing the window, all other options, including clicking File > Exit, have no effect

![](https://d.pr/i/UDjPqx+)
(Image link: https://d.pr/i/UDjPqx )

### Where did you see the bug

- OS: Windows
- OS version: Windows 10 Pro 19041.572
- Simplenote app version: 2.0.0
- 3432279-zen

**Comment by codebykat** [comment]
Hi @sarahfg! We've unfortunately been unable to reproduce this on our end. Does it happen every time for you? Are there any errors shown?

**Comment by reginabally** [comment]
Another report on the same ticket (3432279-zen) that the app was unresponsive after trying to export notes. 

> I have attached a screenshot of the debugging console after clicking export and exit several times. 

Attaching the errors in the console:

![Simpenote-2-Console](https://user-images.githubusercontent.com/40906847/97260367-c61ddf80-1857-11eb-88ee-2988350ac5bc.jpg)


Could this be related?

**Comment by azollafox** [comment]
@codebykat I can't reproduce it but the user seems to be able to reproduce it very reliably. It happens both when they try to exit the app and when they try to export notes from the menu of the app

**Comment by rossanafmenezes** [comment]
Another report here:

3436347-zen

![win10_version](https://user-images.githubusercontent.com/30724184/97312067-72050200-183b-11eb-96b5-86891495e4e5.png)

Their screenshot of the debugging console is empty. 

![debugging_console_when_logged_out](https://user-images.githubusercontent.com/30724184/97312296-b4c6da00-183b-11eb-91c4-03787bc09576.png)

**Comment by reginabally** [comment]
Additional details shared in 3436347-zen

> I've just opened the app now and made the console visible before entering my email & password. The attached is what it shows after I click the blue "log in" button. Once I go File > Preferences > Log out the console clears to a blank pane again. When I'm back on the app's login screen it doesn't matter what menu I select, the console remains blank and I have to kill the app in the Windows task manager to close it.

**Comment by rossanafmenezes** [comment]
another report  here: 3618534-zen

The Console prints this when they try to exit.

```
VM68 C:\Program File…sktop\preload.js:51 Uncaught Error: Uncaught TypeError: Cannot read property 'length' of undefined at EventEmitter.newCallback (VM68 C:\Program File…sktop\preload.js:51) at EventEmitter.emit (VM10 events.js:223) at Object.onMessage (VM55 renderer_init.js:114)
newCallback
@
VM68 C:\Program File…sktop\preload.js:51
emit
@
VM10 events.js:223
onMessage
@
VM55 renderer_init.js:114
```

This is on:

Simplenote 2.3.0
Win 10 Pro 2004

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
