### ISSUE TITLE
Tag isn't added automatically when a tag is selected from the menu

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-electron#2423]
When a tag is selected from the hamburger menu to view the list of notes assigned to the tag, the tag wasn't assigned to the new note created under this view. This feature is available in previous version (v 1.5.x, according to 3432482-zen).

### Expected
I would expect the chosen tag will automatically be added to the note when I create a new note after selecting a tag from the hamburger menu.

### Observed
The new note was created without a tag.

### Reproduced

**Note:** The issue was originally reported in 3432482-zen on Windows 10, Simplenote app version 2.0.0. I was able to replicate this on https://app.simplenote.com.

1. Open up the hamburger menu of the app
2. Choose a tag
3. Create a new note
4. See that no tag was added to the note

**Screen recording**

![Screenshot](https://d.pr/i/oeZqVK/raUWKgYlKC+)
Direct link to the GIF: https://d.pr/i/oeZqVK/raUWKgYlKC

### Where did you see the bug

**Information shared in 3432482-zen**

- OS: Windows
- OS version: 10 v1909
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.0.0

**Information on this test**

- OS: macOS
- OS version: 10.15.7 (19H2)
- Browser (if applicable): Google Chrome
- Browser version (if applicable): Version 86.0.4240.111 (Official Build) (x86_64)
- Simplenote app version: 2.0.0

**Comment by codebykat** [comment]
Huh, I didn't know it used to do this. This feature is probably going away rather than being reimplemented (I think the idea is to get rid of the selected tag entirely and make all searches global) but I'll leave this open for now.

**Comment by reginabally** [comment]
> Huh, I didn't know it used to do this. This feature is probably going away rather than being reimplemented (I think the idea is to get rid of the selected tag entirely and make all searches global) but I'll leave this open for now.

I'm not sure if the feature used to be available in the older version of the Electron app but I'm able to achieve this on MacOS version 2.3.

**Comment by ericamQA** [comment]
Another instance in 3642690-zen

**Comment by gubrist** [comment]
The problem is back with Version 2.9.0

**Comment by pachlava** [comment]
@gubrist the issue is fixed in 2.10.0 which will start rolling out on May 3.
