### ISSUE TITLE
Electron: CTRL + Click (follow link) doesn't work

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#2425]
Follow link feature isn't working as expected in Simplenote 2.0.0 (outside Preview mode).

**Ubuntu** - nothing happens after clicking on a URL. After few clicks it only underlines some part of the URL, as seen on the screenshot below.

![2020-10-27_19-59](https://user-images.githubusercontent.com/8862464/97353841-d56f4e00-1894-11eb-9576-7d5141b185d6.png)

**Windows** - also wasn't able to open any browser. Instead, the dialog on the screenshot below was shown. Even after selecting _Look for an app in the Microsoft Store_ I wasn't able to select any of the installed browsers (or at least install a new one).

![Screenshot_62](https://user-images.githubusercontent.com/8862464/97354451-b1f8d300-1895-11eb-8575-5dff4dc8c713.png)

|OS Version|App Version|
|-|-|
|Ubuntu 18.04 LTS|Simplenote 2.0.0|
|Windows 10 (build 2004)|Simplenote 2.0.0|

**Comment by codebykat** [comment]
Hi @djordjeandrejevic, thanks for reporting these issues. Do you see the "Follow Link" popup when you hover over a link? Does clicking on that work?

<img width="227" alt="Screen Shot 2020-10-27 at 12 59 06 PM" src="https://user-images.githubusercontent.com/52152/97355499-36c2fd00-1854-11eb-9213-a06ae8440fe7.png">

**Comment by djordjeandrejevic** [comment]
Hi @codebykat, yes I see it, but the behavior is the same in both Ubuntu and Windows.

**Comment by reginabally** [comment]
I'm able to replicate this on macOS 10.15.7 (19H2) with Simplenote 2.0.0.

I see the "Follow Link" popup when I hover over a link + pressing Cmd key. Clicking the link with Cmd key pressed does nothing.

Also, I think it's worth mentioning that Cmd + Click works on the web app.

**Comment by mokagio** [comment]
Bumping this to 2.2.0 because it's time to code freeze 2.1.0.

**Comment by reginabally** [comment]
Another report in 3442967-zen. Windows 10 with Simplenote 2.0.0.

**Comment by reginabally** [comment]
Another report in 3476569-zen. Windows 10 with Simplenote 2.0.0.

**Comment by codebykat** [comment]
Will be fixed in 2.2.0
