### ISSUE TITLE
Ubuntu/Windows: CTRL + Z (keyboard) doesn't work or works sporadically

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#2426]
Undo feature on a keyboard doesn't work as expected in Simplenote 2.0.0.

In Windows it works after certain number of <kbd>CTRL</kbd> + <kbd>Z</kbd> clicks (say after 5~6 clicks), while in Ubuntu it doesn't work at all, no matter how many times I press the keys.

By using right mouse click and then selecting Undo - it works properly, though.

|OS Version|App Version|
|-|-|
|Ubuntu 18.04 LTS|Simplenote 2.0.0|
|Windows 10 (build 2004)|Simplenote 2.0.0|

**Comment by cubismod** [comment]
Encountering this issue with Simplenote 2.0.0 and openSUSE Leap 15.2 using the latest AppImage package as well.

**Comment by arkniazi** [comment]
facing the same issue on ubuntu

**Comment by mokagio** [comment]
Bumping this to 2.2.0 because it's time to code freeze 2.1.0.

**Comment by rezzap** [comment]
Reported again in 3457052-zen 

> Currently I'm using Simplenote app that installed on windows. I'm using the latest updated app that I downloaded on Simplenote website. I didn't find any trouble like this before. Sometimes the undo button works, but after you hold ctrl+Z for about 5-10 second, and it undo things repeatedly. But it not happened all the time, just sometimes.

**Comment by reginabally** [comment]
Another report in 3475633-zen. Simplenote 2.0 on Windows 10 Home version 2004.

**Comment by chromer030** [comment]
same here on Arch Linux.

**Comment by JavonDavis** [comment]
> Thanks @JavonDavis, I think this is a duplicate of #2426. Good additional info on the Markdown switch. I'm looking into it 😅
> 
> Can you tell me if you're able to undo edits after making changes using the file menu (File -> Undo)? What about the right click menu?

@codebykat yep I can undo changes with those options just not the keyboard shortcuts

**Comment by dcmlx** [comment]
I'm having the same problem on Windows. CTRL-Z keyboard shortcut not working. File->Undo is working though.

**Comment by codebykat** [comment]
Will be fixed in 2.2 #2490
