### ISSUE TITLE
WebM and WebP

### ISSUE THREAD

**Issue by Thorny-Twig** [Automattic/simplenote-electron#2430]
### What

Is there plans to bring WebM/WebP compression video/image formats into the Simplenote eco system. I have been linking in gifs/jpg/png and noticed that there was a WebM/WebP formats to help lighten the downloading file size/calls.
### Why

To have the option to use WebM / WebP instead of gifs/jpg/png to load public accessible simple note pages faster.

**Comment by codebykat** [comment]
Hi @Thorny-Twig, which images are you referring to? If you're uploading images to another service and linking them in Simplenote, you should be able to link to any file format. Can you provide some examples of formats that aren't working?

**Comment by Thorny-Twig** [comment]
Hi @codebykat, oh I see the .webp works as expected, great.  
![webp_image](https://www.gstatic.com/webp/gallery/1.webp)  
***
Video like files in .webm format don't appear to display. 
![webm video 1](https://upload.wikimedia.org/wikipedia/commons/8/87/Schlossbergbahn.webm)
![webm video 2](https://s1.webmshare.com/qdqB7.webm)
***
Gifs work perfect, so I was trying to use .webm instead of .gif 
![gif file](https://i.imgur.com/qR77BXg.gif)

**Comment by belcherj** [comment]
I think this is a browser implementation detail. I can take a look but I do not know that this will be possible. Notice how the WebM video is also broken in this GitHub issue.

**Comment by belcherj** [comment]
Wait, this is not a WebM problem but that we do not support video embeds in markdown. If you want to embed videos you can do something like: http://sviridovserg.com/2017/05/22/embed-youtube-to-markdown/

Video embeds is something we can look at but is not currently on our timeline.
