### ISSUE TITLE
Windows: Ctrl + Shift + I assigned to both New Note and Debugging Console

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-electron#2436]
Reported in 3429951-zen.

> It looks like Ctrl+Shift+I now is assigned to both "File -> New Note" as well as "Help -> Advanced -> Debugging Console"
And it opens the debugging console and does not create a new note.

### Expected
I would expect the Ctrl + Shift + I hotkey opens up a new note instead of showing the Debugging Console.

### Observed
Using the Ctrl + Shift + I hotkey opens up the Debugging Console.

### Reproduced

1. On the Simplenote app, press Ctrl + Shift + I
2. The app opens up the Debugging Console

### Where did you see the bug

- OS: Windows
- OS version: 10
- Simplenote app version: 2.0.0

I don't have Windows to check this but on Simplenote Elecron 2.0.0 on MacOS, the hotkey for "File > New Note" is ⇧ + ⌘ + I, whereas "Help -> Advanced -> Debugging Console" is ⌥ + ⌘ + I.

I'm asking for some screenshots and will add to this report when we have it.

**Comment by adyomin** [comment]
Updated: Same issue on Ubuntu 20.10 + Simplenote 2.1.0

**Comment by JavonDavis** [comment]
Issue still exists on 2.1-beta-2

**Comment by codebykat** [comment]
Will be fixed in 2.2 #2490

**Comment by codebykat** [comment]
Followed up to remove the label from the menu item in https://github.com/Automattic/simplenote-electron/pull/2493
