### ISSUE TITLE
Sorting: Note list is updated when a note is published

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#244]
It seems that if you sort your notes by date modified, and publish a note, that note is moved to the top. Is that something that is expected? I was surprised. I expect the order to only change if I edit the content of the note (direct editing, revision select, editing tags?).

**Comment by roundhill** [comment]
Sounds like a :bug: to me

**Comment by dmsnell** [comment]
This is still present on the `indexdb`-only sort, right? I know that in the code I put out there for a JS sort, it was specifically looking at the `modificationDate` field, so if it's sorting on publish, we are probably updating that field. Maybe we don't want this, and that could be changed.

**Comment by drw158** [comment]
Just tested again on master. I can confirm that when I publish/unpublish a note it is moved to the top on the Last Modified setting. I don't think we should update the modificationDate on publish/unpublish.

**Comment by mirka** [comment]
Closing as fixed. The [current implementation](https://github.com/Automattic/simplenote-electron/blob/master/lib/flux/app-state.js#L447) doesn't alter the modificationDate on publish/unpublish.
