### ISSUE TITLE
Merge Title and Menu Bar

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2441]
### What

Merge Title and Menu Bar

### Why

Merging Menu Bar with Title Bar will free some room which can be very handy on small screen systems like laptops.

### How

Like Visual Studio Code:
![Simplenote](https://user-images.githubusercontent.com/23485114/97768882-9dd5ff80-1b3b-11eb-8e22-b6ebdd7d89a1.png)

**Comment by belcherj** [comment]
@SylvesterWilmott

**Comment by KraXen72** [comment]
+1

**Comment by sandymcfadden** [comment]
Some changes to the search and menu bar are happening here https://github.com/Automattic/simplenote-electron/issues/2561

**Comment by codebykat** [comment]
Yeah, I think fully merging these two bars would be very difficult from a cross-platform perspective, but the new update will recover some real estate. I'll close this for now and we can revisit sometime in the future.

**Comment by codebykat** [comment]
In case anyone wants to work on this and submit a PR, it looks like we could use Electron's "frameless window" API and then add styles for all platforms, but I haven't tried it. It would need to look and work properly on Linux, Windows and OSX builds.

https://www.electronjs.org/docs/api/frameless-window
https://github.com/binaryfunt/electron-seamless-titlebar-tutorial
