### ISSUE TITLE
Web App: Missing Evernote import tool

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-electron#2444]
According to the [Simplenote Help page](https://simplenote.com/help/), I should be able to import Evernote notes using the web app at https://app.simplenote.com

### Expected
I would expect to be able to import Evernote notes using the Simplenote web app.

### Observed
The "Evernote" import option is missing on the Simplenote web app.

### Reproduced

1. Log in to Simplenote web app at https://app.simplenote.com
2. Click on the menu on the top left corner of the screen and select Settings 
3. Click on Tools
4. Choose Import Notes
5. The only options available are Simplenote and Plain text files.

The Evernote import option is available on Electron version 2.0.0 on macOS.

### Where did you see the bug
- OS: macOS
- OS version: 10.15.7 (19H2) 
- Browser (if applicable): Google Chrome and Firefox
- Browser version (if applicable): Version 86.0.4240.111 (Official Build) (x86_64) for Chrome, and 82.0.2 (64-bit) for Firefox
- Simplenote app version: https://app.simplenote.com

**Comment by codebykat** [comment]
I think it was only ever available on the app and I thought the docs used to reflect that, have they changed? 🤔

**Comment by belcherj** [comment]
It was only ever available in the app due to the complexity of parsing the evernote file. Given that we do not support the macOS Electron app we should look at adding the Evernote implementation to the web app.

We should update the docs.

**Comment by codebykat** [comment]
I updated the docs, also added the Markdown file extension added in #2351 
  
<img width="629" alt="Screen Shot 2020-11-03 at 12 41 09 PM" src="https://user-images.githubusercontent.com/52152/98038365-e0b10500-1dd1-11eb-87ea-5560cf9567e4.png">
