### ISSUE TITLE
Double Quit Needed to Close App

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-electron#2445]
### Expected
When I go to Simplenote > Quit Simplenote and click the app should be completely closed.

### Observed
One the first try of this action the currently open note closes, but the application is still open. I need to go to Simplenote> Quit Simplenote once more to close the applicaiton 

### Reproduced

User reported and I reproduced on the same OS and Simplenote versions

### Where did you see the bug

- System Make: MacBook Pro
- OS: Catalina 10.15.7
- Simplenote app version: 2.0.0

3456210-zen

**Comment by belcherj** [comment]
This is fixed by: https://github.com/Automattic/simplenote-electron/pull/2439 and will be in version 2.1.0
