### ISSUE TITLE
New note blocked when created in the tag sidebar (left)

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2447]
### Expected
- I create a new note using the tag sidebar (left) and:
a) want the tag being set 
b) write text right now
- Behaviour as in previous Simplenote electron versions 1.xx

### Observed
- I create a new note using the tag sidebar (left).
a) The note is being created, without a tag (not visible at the lower buttom) and
b) I cannot enter any text in the note.
- The note remains as "New note..." in the  the tag sidebar (left)
- I have to click into another existing note and then click back to the new note in order to into edit mode

### Reproduced
see above

### Where did you see the bug
- OS: Windows 10
- Simplenote app version: 2.0.0 electron

**Comment by codebykat** [comment]
Heya @gubrist! The selected tag part is being tracked in #2423. I can't reproduce the issue with typing in the new note being blocked; is this still happening for you?

**Comment by gubrist** [comment]
Hi @codebykat
 
Thanks, the issue with typing in the new note being blocked has been solved with the latest upddate(s)
