### ISSUE TITLE
Tag not displayed using the search field

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2448]
### Expected

- I search a note with a key word and want to see the tag of the note (lower buttom)

- Behaviour as in previous Simplenote electron versions 1.xx

### Observed
- I search a note with a key word and do not see the tag of the note (lower buttom)

### Reproduced
see above

### Where did you see the bug

- OS: Windows 10
- Simplenote app version: 2.0.0 electron

**Comment by codebykat** [comment]
Thanks, this is tracked in #2331. We'll get it restored soon.
