### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2451]
### What

Add proxy settings (Socks5)

### Why

When you connect to the Internet, you may sometimes need to go through a proxy server.
Proxies are commonplace in schools, colleges, and workplaces.
Also, proxy help to bypass internet censorship.

### How

Like CintaNotes (a client for Simplenote)
![CintaNotes](https://user-images.githubusercontent.com/23485114/98187159-888b1780-1f25-11eb-965a-6031384db1bc.png)
or Spotify (a electron app) 
![Spotify](https://user-images.githubusercontent.com/23485114/98187396-1535d580-1f26-11eb-85eb-a9b35a4efe9c.png)

**Comment by codebykat** [comment]
Hi @xmha97, the app should use any system proxy you have configured. Is that not working for you?

**Comment by xmha97** [comment]
> 
> 
> Hi @xmha97, the app should use any system proxy you have configured. Is that not working for you?

Yes, the Simplenote app uses the system proxy.
But I prefer to apply proxy only in the Simplenote app.

**Comment by dmsnell** [comment]
Looks like we can do this with the browser session object in Electron, though it will take UI work and isn't on our roadmap right now.

In the meantime @xmha97 you might try setting some ENV vars when starting Simplenote if your setup allows that or look into an app that forces proxy access. I used to use one for some CLI apps that didn't support proxy settings.

**Comment by codebykat** [comment]
What @dmsnell said! I'm closing this for now since it's not on our immediate roadmap. We'll take it into consideration in the future but it's not a common request and I think there are viable workarounds, so unfortunately it is not a high priority at this time.

**Comment by chromer030** [comment]
@codebykat , Hi thank you for improving and developing this lovely app.
Any plan to add support in-app proxy ?
As i mentioned here : https://github.com/Automattic/simplenote-android/issues/1329, proxy support is vital for some users, and using system-wide proxy is not always possible.
Thanks again.

**Comment by codebykat** [comment]
It's not on our immediate roadmap, @chromer030, though we'll consider it for the future if we hear from many people that it's a need. As I said above, it seems there are viable workarounds and it's an uncommon usage. Specifically for the Electron app I think this is more hackable than with Android (e.g. you can use the command line to pass options).
