### ISSUE TITLE
Ctrl + A does not mark all text

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2458]
Expected
- while creating, editing or reading a note
- Ctrl + A does mark all text of a note
- as worked in previous versions 1.xx

Observed
- Ctrl + A does not mark all text

Reproduced
- see above

Where did you see the bug
    OS: Windows 10
    Simplenote app version: 2.0.0 electron

**Comment by codebykat** [comment]
Hi @gubrist, I think this is a duplicate of #2432. Can you confirm that you are able to select all text with the menu option (Edit -> Select All)?

**Comment by gubrist** [comment]
Thanks.
Yes I can confirm that I am able to select all text with the menu option (Edit -> Select All)

**Comment by codebykat** [comment]
Great, thanks. Hoping to have a fix for the keyboard shortcut in the next version.
