### ISSUE TITLE
Right to left languages issues

### ISSUE THREAD

**Issue by chromer030** [Automattic/simplenote-electron#2466]
Hi , when typing in right to left languages like Hebrew, Arabic or Persian , if we use markdown , markdown characters behaves as Left to Right language and make whole note disordered and hard to type , this issue currently is on both Android and Desktop clients.

example :

![Screenshot_2020-11-11_19-26-54](https://user-images.githubusercontent.com/13361552/98834536-91fc0e80-2454-11eb-8be7-3dd463392c71.png)
![Screenshot_2020-11-11_19-27-12](https://user-images.githubusercontent.com/13361552/98834555-96c0c280-2454-11eb-844b-062753b7a335.png)
![Screenshot_2020-11-11_19-25-35](https://user-images.githubusercontent.com/13361552/98834586-9fb19400-2454-11eb-9ff6-7d5744aaa877.png)
![Screenshot_2020-11-11_19-25-48](https://user-images.githubusercontent.com/13361552/98834599-a3451b00-2454-11eb-92e9-243de29001a6.png)

**Comment by codebykat** [comment]
Thanks, already tracked in #2457
