### ISSUE TITLE
Unable to create nested list with the Tab key

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-electron#2468]
Reported in 3477730-zen.

> When I use "-" in Markdown, "-" do not move when I press the tab key after pressing enter key. 

### Expected

When I create a list with the `-` or `*` markdown, I would expect to be able to create a nested list item with the Tab key.

### Observed

When I pressed the Tab key, 2 spaces were added without indenting the list item. This happens on notes with and without markdown enabled.

### Reproduced

1. Create a new note on the app
2. Type `-` and some text
3. Press the Enter key and see another `-` character created on the second line, which is expected.
4. Press the Tab key and see that two spaces were created, instead of indenting the list item to create a nested list.

**Screen recording on the Electron app**

![Screen Capture on 2020-11-12 at 11-40-31](https://user-images.githubusercontent.com/40906847/98893310-29a53f80-24dd-11eb-8b69-8e5da9fe89db.gif)

**Screen recording on the macOS app version 2.3, which is the expected result**

![Screen Capture on 2020-11-12 at 11-42-04](https://user-images.githubusercontent.com/40906847/98893366-3fb30000-24dd-11eb-8af2-e24897e5fa36.gif)

### Where did you see the bug

**Information shared in 3477730-zen**

- System Make: Lenovo 
- System Model: ThinkPad E490 
- OS: Windows
- OS version: 10 Pro
- Simplenote app version: 2.0.0

**Replicated with the following device**

- System Make: Apple 
- System Model: iMac 27-inch
- OS: macOS
- OS version: 10.15.7 (19H2)
- Simplenote app version: 2.0.0

**Comment by albertobalsalm** [comment]
I'm experiencing the same issue on windows, version 2.1.0
