### ISSUE TITLE
Checkbox Icon 

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2479]
### What
Checkbox Icon in text entry surface

![checkbox](https://user-images.githubusercontent.com/22197180/99377759-e1b05f00-28c6-11eb-97d4-8af8e65cd1fd.JPG)

### Why
- Faster entry with mouse
- Exists in Android App

### How
- linke in Android App

**Comment by sandymcfadden** [comment]
We're looking at this here. Going to close this issue in favor of it. https://github.com/Automattic/simplenote-electron/issues/2563
