### ISSUE TITLE
Searching for an exact match takes into account only text inside quotes and ignores other keywords

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-electron#2481]
Let's say we have a note: `Tap the arrow button at the top left or swipe across your note list to view your tags.`
Searching for:
* `"the arrow"` correctly finds this note and highlights only `the arrow`.
* `"the arrow" blabla` still finds the same note. Note doesn't have `blabla` though
* `the arrow blabla` works as expected and doesn't show any notes

### Expected
Keywords outside exact match are also included in the search

### Observed
Keywords outside exact match are ignored

### Reproduced
1. Create a note with text `Tap the arrow button at the top left or swipe across your note list to view your tags. `
2. Search for `"the arrow" blabla`

### Where did you see the bug
- System Make: Apple
- System Model: Macbook
- OS: Catalina
- OS version: 10.15.7
- Browser (if applicable): Safari
- Browser version (if applicable): 
- Simplenote app version:

**Comment by pachlava** [comment]
Verified on Windows with Electron 2.5.0-beta1
