### ISSUE TITLE
reduce amount of white space at the top of the note window

### ISSUE THREAD

**Issue by alusiani** [Automattic/simplenote-electron#2484]
### What

Reduce the empty vertical space at the top of the window than contains the note.

### Why

One more line of text could be accomodated using white space that is not currently used at the top of the note window, in SImplenote v2.1.0 on Linux.

**Comment by djordjeandrejevic** [comment]
I've mentioned this also (along with few other things) in #2504.

**Comment by sandymcfadden** [comment]
Thanks so much for the suggestion.
We're working on this area as mentioned [in comment](https://github.com/Automattic/simplenote-electron/issues/2504#issuecomment-764613768) on the issue mentioned above. 
I'm going to close this based on that work.
