### ISSUE TITLE
Em dashes and typographical quotation marks

### ISSUE THREAD

**Issue by frafor** [Automattic/simplenote-electron#2485]
### Typographical dashes:

em dash

---Three simple dashes should become one em dash. Not happening.

for long em dashes

--This is a not so long a dash

for not so long dashes

*typographical quotation marks:*

When a word is within "quotes", it should make them “this kind” of typographical quotes

MarkDown libraries do exist, 100% open source, capable of such MarkDown to HTML transformations.

**Comment by sandymcfadden** [comment]
Thanks so much for the request! We track feature requests in an internal tracker. I'm going to move this there to keep in mind for future consideration.
