### ISSUE TITLE
Light theme checked but dark should be by default

### ISSUE THREAD

**Issue by vmasseron** [Automattic/simplenote-electron#2486]
On W10 in dark mode, the Simplenote app is by default in dark mode (and that's good !) but in View->Theme, Light is checked. Not a big deal but it keeps a bug.

### Expected
If Windows is in dark mode, "dark" should be checked in View->Theme by default.

### Observed
The dark mode of the app is enabled but View->Theme show that light is checked

### Reproduced
1. Enable dark mode in Windows Preferences
2. Go to View->Theme

### Where did you see the bug
- OS: Windows 10 Pro x64
- OS version: Windows 10 2004
- Simplenote app version: 2.1.0

**Comment by sandymcfadden** [comment]
This seems to go along with the issue here https://github.com/Automattic/simplenote-electron/issues/2134 where there is no System theme showing on Windows even though that is what is being used by default. Closing this one for now.
