### ISSUE TITLE
App is Missing a Few Keyboard Shortcuts

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#249]
Let's add:
* File->New Note (cmd or ctrl + N)
* Focus search field (cmd or ctrl + L)

**Comment by drw158** [comment]
Using L seems kinda weird, not sure why the Mac app uses it. I think it's because cmd F brings up a native search and replace.

How about `cmd F` or `shift cmd F` for search.

Ulysses for ideas: http://ulyssesapp.com/blog/2014/08/ulysses-tips-shortcuts-2/

also #37

**Comment by roundhill** [comment]
> How about cmd F or shift cmd F for search.

Makes sense!
