### ISSUE TITLE
Windows Notifications Are Mis-Labeled

### ISSUE THREAD

**Issue by nsakaimbo** [Automattic/simplenote-electron#2492]
Windows notifications are labeled with the app bundle name and not the application name.

<p align="center">
<img width="388" alt="simplenote-windows-notification" src="https://user-images.githubusercontent.com/8979548/100265795-c5dc3700-2f1e-11eb-8152-a895b2da6f29.png">
</p>

### Expected

The notification should be labeled "Simplenote".

### Observed

The notification is labeled `electron.app.Simplenote`.

### Reproduced

1. Run the application on Windows with notifications enabled
2. Perform an action on another platform (such as a browser) that will trigger a notification (such editing an existing note or creating a new one)
3. Observe the label used when the notification is presented

### Where did you see the bug

- OS: Windows 10

**Comment by codebykat** [comment]
I believe this is fixed in 2.3 by #2483 but let me know if not!
