### ISSUE TITLE
Select All (Ctrl+A) does not work in Edit mode

### ISSUE THREAD

**Issue by dplanella** [Automattic/simplenote-electron#2494]
### Expected
1. Switch to Edit mode on a note
1. With the note on focus, press the `Ctrl+A` keyboard shortcut
1. The complete note contents are selected (and highlighted as a selection)

### Observed
1. Switch to Edit mode on a note
1. With the note on focus, press the `Ctrl+A` keyboard shortcut
1. Nothing happens, the keyboard shortcut seems to 

### Additional notes

- In Preview mode, the `Ctrl+A` shortcut works as expected and selects the full contents of the note
- In Edit mode, using the context menu (right-click) and selecting the `Select all` menu option also selects the full contents of the note as expected.  

### Where did you see the bug

- OS: Ubuntu 20.04.1 LTS
- Simplenote app version: 2.1.0

**Comment by codebykat** [comment]
Thanks for the report, @dplanella. The fix for this is in the upcoming release! (#2490)
