### ISSUE TITLE
Ctrl+Shift+I Keybinding conflict in Linux, Ubuntu

### ISSUE THREAD

**Issue by eldenpark** [Automattic/simplenote-electron#2495]
### Expected

Type Ctrl+Shift+I to create a new note.

### Observed

Ctrl+Shift+I is presumably the keybinding for a chromium-based browser to open a developer tool. And it opens a developer tool showing the markup (HTML), not allowing to create a new note.

### Reproduced

1. Type Ctrl+Shift+I when the app is focused.
2.
3.

### Where did you see the bug

- System Make:
- System Model:
- OS: Ubuntu
- OS version: 20.04
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.1.0

**Comment by codebykat** [comment]
Thanks for this report, @eldeni. This is fixed in the upcoming version (#2490).
