### ISSUE TITLE
Add reminder notifications

### ISSUE THREAD

**Issue by stpoa** [Automattic/simplenote-electron#2498]
### What
Ability to remind me of some specific line of text / todo entry

### Why
One missing feature for simplenote is that I cannot use it to remind me to do things, so for that I have to use Apple reminders.

### How
You could add something like `- [ ] Buy milk @remind-me-at 2020-11-12 09:20` which would remind me at that time.

**Comment by codebykat** [comment]
Thanks, @stpoa. I've added this to our list of feature requests for possible consideration in the future. Since we use GitHub to track only our immediate roadmap and bugs, I'm closing this issue.
