### ISSUE TITLE
Problems inputting Japanese characters on Windows Pro

### ISSUE THREAD

**Issue by rossanafmenezes** [Automattic/simplenote-electron#2501]
I came across two different tickets today where users reported issues inputting characters on Simplenote 2.2 and both cases users are on Windows Pro and both users mention version 2.1 works fine. 

### Expected

Users to be able to type and delete text in any language. 

### Observed

Simplenote 2.2.0 will not allow character input and character deletion (Backspace) in Windows.
You will not be able to enter characters.
Can no longer backspace characters.

### Reproduced
I was not able to reproduce the issue since I don't have a Windows Pro nor I have a Japanese keyboard. But copying and pasting Japanese text on Windows10 Home does not trigger the issue. 

1 - Create a new note
2 - Type Text in Japanese or try to delete (backspace) some characters. 

### Where did you see the bug

3533475-zen

Windows10 Pro v20H2 19042.630
Desktop ver2.2.0

3532984-zen 
Using Windows 10Pro 64bit.
Simplenote 2.2.0

This user did not confirm yet if the issue is only with Japanese or if they are having issues in other languages.

**Comment by codebykat** [comment]
Closing to track in #2522
