### ISSUE TITLE
What happened to the arm64 deb & rpm files in version 2.2.0?

### ISSUE THREAD

**Issue by Feakster** [Automattic/simplenote-electron#2503]
In the latest release (2.2.0) the arm builds are back (yay!) but some are missing (boo!). Namely, Simplenote-linux-2.2.0-arm64.deb & Simplenote-linux-2.2.0-arm64.rpm

**Comment by codebykat** [comment]
Hmm. Previously: #2456 

From the comments there, maybe they didn't work for deb and rpm?

https://github.com/Automattic/simplenote-electron/blob/develop/electron-builder.json#L66

Can you use the .tar.gz and/or the arm71 builds?

<img width="362" alt="Screen Shot 2020-12-02 at 2 29 11 PM" src="https://user-images.githubusercontent.com/52152/100939238-d0f90f00-34aa-11eb-8406-660509ef7462.png">

**Comment by Feakster** [comment]
Unfortunately not. Needs to be the aarch64 (arm64) build.

Could the builds have been omitted from the electron-builder script by accident?

**Comment by SpacingBat3** [comment]
See this issue: [#5422](https://github.com/electron-userland/electron-builder/issues/5422#issuecomment-742105240).

Also consider moving from the `electron-builder` to `electron-forge` – one of advantages of that would be the ARM `*.deb` and `*.rpm` support (tested the build on the `AArch64` host and target).

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
