### ISSUE TITLE
To show the creation time of each note in the Info button

### ISSUE THREAD

**Issue by wlos** [Automattic/simplenote-electron#2506]
### What

Showing the creation data of each note

There is a function that note can be sorted by data created. But we cannot see the creation data of each note. So I hope that each note can easily show its creation data in its INFO.
### How

![image](https://user-images.githubusercontent.com/3961883/101271370-09eff700-37bd-11eb-96ef-8a988a612cb5.png)
The note INFO shows its modification time and  synchronization time. The creation time can be displayed above the modification time.

**Comment by sandymcfadden** [comment]
Thanks so much. We've had this requested a few times in the past and are tracking it in our feature request tracker internally. I will add your request to it and close this for now.
