### ISSUE TITLE
macOS restart is interrupted by the app

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-electron#2507]
When I tried to restart my computer I got the following message:

> Your Mac hasn't restarted because Simplenote failed to quit. To continue restarting, quit Simplenote

I tried it the second time with the same result. I didn't see any pending sync operations happening in the app.
Manually quitting the app works perfectly, the app closes immediately.

Possible solution: https://stackoverflow.com/questions/51804259/how-to-prevent-electron-app-from-interrupting-macos-system-shutdown

<img width="592" alt="Screenshot 2020-12-03 at 20 44 25" src="https://user-images.githubusercontent.com/54751/101327622-382e0f00-386f-11eb-944f-b1a5739b1ba4.png">

### Expected
macOS restarts

### Observed
macOS restart is interrupted

### Reproduced
1. Open the app
2. Restart the Mac
3. See system alert that restart was interrupted

### Where did you see the bug
- System Make: Apple
- System Model: Macbook
- OS: Catalina
- OS version: 10.15.7
- Simplenote app version: 2.3.0-beta1

**Comment by codebykat** [comment]
Seems likely fixed by the latest update, pls re-open if this still happens on 2.22.1!
