### ISSUE TITLE
New Note Shortcut opens Chrome Inspector on Pop OS / Ubuntu

### ISSUE THREAD

**Issue by peterbwf** [Automattic/simplenote-electron#2508]
Pressing Ctrl + shift + I on Ubuntu and Pop OS causes the chrome inspector to open instead of creating a New Note. Is there a workaround for now to modify the shortcut back to Ctrl + N like it used to be in the old version?

**Comment by codebykat** [comment]
Hi @peterbwf, can you let me know what version of the app you're using? This should have been fixed in the most recent (see #2490). We unfortunately had to change the shortcut away from Ctrl + N because it conflicted with "new window" in the browser.

**Comment by peterbwf** [comment]
You're right, @codebykat. It looks like I caught an update today and it upgraded to 2.2.0. I can confirm it's fixed. Thanks!
