### ISSUE TITLE
2.2.0 Windows Input Text Err

### ISSUE THREAD

**Issue by 793383996** [Automattic/simplenote-electron#2509]
Sometimes the first letter disappears when the text cannot be typed properly on the Windows platform.
Reopen it's ok.

**Comment by codebykat** [comment]
@793383996 I'm not sure what this means, can you provide some screenshots to illustrate the problem? Thanks 😄

**Comment by codebykat** [comment]
I think this is a probable duplicate of #2522

**Comment by 793383996** [comment]
2.0 is ok
