### ISSUE TITLE
Note content lingers when switching accounts

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#251]
This has happened to me a few times.
1. Log in to account A
2. Log out
3. Log in to account B
4. The note content in the editor from account A is still there, even though I'm logged into B

![screen shot 2016-03-24 at 3 40 18 pm](https://cloud.githubusercontent.com/assets/618551/14030694/041cc91a-f1d7-11e5-81e8-b38de511ef0a.png)

The note content you see in the editor is from the demo account, but you can see that I just logged into my personal account.

**Comment by dmsnell** [comment]
Should be resolved by #653
