### ISSUE TITLE
New note not assigned with tag

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2525]
### Expected
- A new note shall be assigned with the tag of the tag list
- As in pervious versions (1.x.x) and as in Android version

### Observed
- The new note has no tag.

### Reproduced

- I select a tag on the tag bar (left)
- I see the notes of this tag.
- I create a note.
- The new note has no tag.

### Where did you see the bug
- Windows 10
- Simplenote app version: 2.3.0

**Comment by codebykat** [comment]
Thanks @gubrist, this is a duplicate of #2423.
