### ISSUE TITLE
Sync is broken again while typing

### ISSUE THREAD

**Issue by elecalion** [Automattic/simplenote-electron#2527]
### Expected

Sync operation should not overwrite what I have typed in editor window.

### Observed

Sync operation overwrite what I have typed.
Text will be deleted OR the same text will be appended somewhere.

### Reproduced

1. Type in
2. Sync is triggered, and the sync icon is rolling
3. Continue typing

ex.

```
This is header

1. this is one
2. this is two
// sync is triggered, and continue typing
3. this is three
```
I got:
```
This is header

1. this is one
2. this is two
This is header

1. this is one
2. this is two
3. this is three
```

### Where did you see the bug

- System Make: NA
- System Model: Core i5-3470
- OS: Windows 10
- OS version: 19042.630
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: simplenote-electron 2.2.0 / 2.3.0

**Comment by dmsnell** [comment]
thanks for reporting @elecalion. this is surprising. are you able to reliably reproduce it? I'm following your steps but it's not acting up. is there anything odd about your setup? weird network issues? running inside a virtual machine? you have Simplenote open to the same account editing the same note on multiple devices (such as this one plus a phone)?

**Comment by codebykat** [comment]
Closing for lack of information and no other reports, please comment or open a new issue if you're still having trouble!
