### ISSUE TITLE
Spell check no longer works since 2.0

### ISSUE THREAD

**Issue by A-blette** [Automattic/simplenote-electron#2532]
Hello, 
Since update 2.0 the spell check no longer works (in french).

### Expected
So when I write a word that doesn't exist I would like it to be underlined in red.

### Observed
Spelling errors are not underlined in red...

### Reproduced
I don't know how to reproduce this bug, but I tried this :
- I only updated the software on a French Wondows 10 pc.
- When I uninstall and reinstall the problem persists.
- I have tried all versions from 2.0 to 2.4.0-beta1 without success.
- When I reinstall version 1.21.1 everything works fine.

### Where did you see the bug

- System Make: Desktop computer assembled myself.
- OS: Windows 10 Home
- OS version: 19042.685 (20H2)
- Simplenote app version: from 2.0 to 2.4.0-beta1

Thank you.

**Comment by codebykat** [comment]
Thanks @jeandesentommeures. We unfortunately had to remove this functionality as of 2.0 for technical reasons, but we're hoping to bring it back in future. We do know many people rely on it! Closing in favor of #2410.
