### ISSUE TITLE
auto detect subject / tag

### ISSUE THREAD

**Issue by zemariagp** [Automattic/simplenote-electron#2535]
### What
Simplenote could go through each note and (with a little bit of NLP) figure out what it is about and add (if the user so wishes) it to a tag. this wouldn't be perfect but i'd prefer it over having most of my notes uncategorized (i'm a chaotic person). 
### Why
the problem with taking lot's of notes is that they get spread all over.
### How
a feature called "auto organize" could be turn on or off. if on, the app would parse all the notes and give them a tag (could have a different colour) according to the what the NLP service recognized as the topic. The NLP service could be some open source library, althought I'm not an expert there seem to exist a few that could do exactly this.

Does anyone else think this could be useful?

**Comment by codebykat** [comment]
Hi @zemariagp, thanks for this interesting idea! It do have to say it's probably pretty far out of scope for a simple note-taking app. 😄  I'll add it to our feature requests (and others should still feel free to chime in here), but I'm closing this issue for now, as we only use GitHub to track bugs and our immediate roadmap.
