### ISSUE TITLE
app.simplenote.com - Search broken in Safari

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-electron#2537]
### To reproduce:

1) Log into app.simplenote.com in Safari
2) Open the developer console
3) Type anything in the Search field above the notes list.

### Expected

To see notes matching my search term, with the search term highlighted in the notes.

### Observed

The screen goes completely blank, with a syntax error appearing multiple times in the browser console:

<img width="1082" alt="Simplenote" src="https://user-images.githubusercontent.com/11873759/102735290-ab914f80-434a-11eb-9281-c4d8bb1a61be.png">

### Where did you see the bug

- System Make: Apple
- System Model: Macbook Pro 16"
- OS: Mac OS
- OS version: 11.1
- Browser (if applicable): Safari
- Browser version (if applicable): 14.0.2

Reported via Twitter: https://twitter.com/avernet/status/1340836170914091008

**Comment by pachlava** [comment]
Verified on mac with Safari 14.0.1 + Simplenote 2.5.0-beta1

**Comment by codebykat** [comment]
@pachlava ~Does this mean you verified the fix or that you are still seeing a crash?~ Nevermind I see you were going through and verifying fixes, thanks! ❤️

**Comment by pachlava** [comment]
@codebykat Here and everywhere else: verified the fix. Will write more unequivocally for next cases, sorry for confusion.
