### ISSUE TITLE
We need Chinese！

### ISSUE THREAD

**Issue by jialiangZ** [Automattic/simplenote-electron#2540]
### What

As I said, I am a user from China, I like this software, and I hope more people will like it, so I hope you can add a new language
### Why

For better promotion
### How

Thank you💖💖💖💖💖

**Comment by codebykat** [comment]
Thanks @jialiangZ! Localization is on our roadmap, please stay tuned :)

**Comment by sandymcfadden** [comment]
I've added this for our internal feature request tracker and will close for now.
