### ISSUE TITLE
Web App: Menu hightlight is not placed correctly on Safari

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/simplenote-electron#2541]
### Expected
The highlighted menu should correctly be placed on the currently selected menu item

### Observed
On app.simplenote.com on Safari 14.0.2, the highlighted menu placement overlaps parts of the previous menu as well.

### Reproduced
1. Go to https://app.simplenote.com on Safari browser
2. Click on menu
3. This is how I see it:
<img width="1501" alt="Screenshot on 2020-12-22 at 16-33-18" src="https://user-images.githubusercontent.com/44837596/102889316-e0e58c80-4473-11eb-908a-ffe027587e29.png">

This issue is consistent on both light and dark modes.

On Chrome, this is how I see it:
<img width="1364" alt="Screenshot on 2020-12-22 at 16-37-02" src="https://user-images.githubusercontent.com/44837596/102889365-f3f85c80-4473-11eb-9a6a-40b793eff0df.png">

### Where did you see the bug

- System Make: Macbook Pro 15-inch
- OS:macOS 
- OS version: Big Sur 11.1
- Browser (if applicable): Safari 14.0.2
- 3591521-zen

**Comment by codebykat** [comment]
Thanks @poojashetty18, working on a fix for this now.

**Comment by pachlava** [comment]
Verified on mac with Safari 14.0.1 + Simplenote 2.5.0-beta1
