### ISSUE TITLE
Tags does not respect keyboard layout

### ISSUE THREAD

**Issue by shved** [Automattic/simplenote-electron#2543]
### Observed
Sorry for ignoring "expected-observed" template, its just much easyer to explain it as is. I'm russian and I use Simplenote mostly with my native language. I can't create a tag that is includes the `б` letter. This character simply does not printed out because in the tags input all commas `,` are ignored and russian `б` character is on the comma button of english layout. So it should be reproducible with any other non english layout.

### Reproduced
1. Change the system layout to russian
2. Try to add some russian tag, like `блокнот` (notepad)
3. б will not be printed, so the tag will be just `локнот` (missing first letter)

### Where did you see the bug
- OS: Ubuntu 20.04
- Simplenote app version: 2.3.0

**Comment by codebykat** [comment]
Thanks @shved, this is a duplicate of #2040. I really do intend to fix it sometime! 😓
