### ISSUE TITLE
UI spring cleaning: notes list

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2560]
https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc5d768735855a07651d9
https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc5e81bc37159baf42a47

- [x] Verify all colors
- [ ] There's a timestamp shown?
- [x] Three lines instead of four for Expanded mode
- [x] Blue highlight on selected note [dark mode]
- [x] Text is lighter on selected note [dark mode]
- [x] Add mouseover state

<img width="1049" alt="Screen Shot 2021-01-10 at 10 33 42 PM" src="https://user-images.githubusercontent.com/52152/104152283-f3c4f000-5393-11eb-9cd9-ae12642ba5a2.png">

<img width="1037" alt="Screen Shot 2021-01-10 at 10 36 15 PM" src="https://user-images.githubusercontent.com/52152/104152398-456d7a80-5394-11eb-885b-cfe8045c4916.png">

**Comment by codebykat** [comment]
~@SylvesterWilmott pointed out that the blue color is currently wrong for the pinned icon as well. Should be `blue30` not `blue20`.~ This has been fixed

**Comment by codebykat** [comment]
Another note from Slack:

> We have updated the selection colour in the notes lost in dark mode on macOS from blue50 to blue50 at 40% opacity.

Edit: Included this in #2631

**Comment by sandymcfadden** [comment]
From slack. The idea of a timestamp being displayed was going to be conditional based on what sorting option was selected. If notes were sorted by created date, or modified date we would display the timestamp.
More thought is going to go into this before making any changes to add the timestamp.

**Comment by codebykat** [comment]
Cool - let's close this parent issue for now, then.
