### ISSUE TITLE
UI spring cleaning: menu bar and search

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2561]
https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc589cc874a566eec63cf
https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbc5305a7be757d21b6cc1

* Move search bar below navigation
* Add All Notes (section) title

<img width="975" alt="Screen Shot 2021-01-10 at 10 39 39 PM" src="https://user-images.githubusercontent.com/52152/104152555-c298ef80-5394-11eb-8b9c-5a66ccfa649e.png">

<img width="856" alt="Screen Shot 2021-01-10 at 10 40 09 PM" src="https://user-images.githubusercontent.com/52152/104152583-cfb5de80-5394-11eb-97f8-46d928e2f6c6.png">

**Comment by KraXen72** [comment]
looks clean!
