### ISSUE TITLE
Add delete tag confirmation

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2568]
https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbdd884623ca5a8c957125
https://app.zeplin.io/project/5d795a3d8ed5261aa146e057/screen/5fbbdd887d9c865c6d783840

<img width="374" alt="Screen Shot 2021-01-10 at 10 57 31 PM" src="https://user-images.githubusercontent.com/52152/104153457-3fc56400-5397-11eb-8f45-980b04dc5305.png">

<img width="372" alt="Screen Shot 2021-01-10 at 10 57 35 PM" src="https://user-images.githubusercontent.com/52152/104153469-43f18180-5397-11eb-9b5a-4d177fc3b204.png">

**Comment by dmsnell** [comment]
would be nice to not only ask for confirmation but explain why we want confirmation

> Deleting this tag will also remove it from all of the 34 notes that have it.
