### ISSUE TITLE
Strange bug with quotation marks/colons in international keyboard or Chinese input

### ISSUE THREAD

**Issue by athletik** [Automattic/simplenote-electron#2573]
This problem is recreated under Simplenote v2.2.0 ~ 2.5.0 beta1.
- OS: Linux Mint 19.1
- Chinese input: rime v1.2.9

https://user-images.githubusercontent.com/75654739/104196969-66e76880-545f-11eb-8098-19850ed39fe2.mp4

https://user-images.githubusercontent.com/75654739/104196993-6e0e7680-545f-11eb-8a95-db82a920c395.mp4

**Comment by codebykat** [comment]
Thanks @athletik. This seems similar to #2522. For now I will close it as such but if we find a fix to #2522 and this still persists, we can re-open.
