### ISSUE TITLE
Make adding list items more intuitive when using Markdown formatting

### ISSUE THREAD

**Issue by svenfinger** [Automattic/simplenote-electron#2578]
### What
When adding list items with the asterisk sign * and hitting the enter key, I would expect that a new line is added, and the new line also starts with an asterisk sign in front. If I hit enter an additional time, the line will return to a normal line (without an asterisk) and no new line is created (staying on the current line). This is also how it usually works in text formatting software (also in this issue reporting editor!).

### Why
It makes it much easier and faster to continuously add list items. You don't always have to type an asterisk.

### How
```
* My first bullet // *hits enter*
* | // < Cursor (hitting enter again will just produce a new empty line instead)
```

**Comment by sandymcfadden** [comment]
Hi @svenfinger thanks for the report. This is the way things are meant to work and in my testing the lists do work with or without Markdown formatting enabled on a note.

Are you able to provide some more details about which app you are using where this doesn't happen for you? 
If it is the web app information about the browser you are using would be helpful as well.

**Comment by svenfinger** [comment]
Hey @sandymcfadden, that's great to hear! Then this might be bug and not a feature request. 🙂

I'm using the desktop app (v2.2.0) on Windows and when I hit enter in a list it's just a new blank line and not a new list item.

**Comment by sandymcfadden** [comment]
Thanks @svenfinger I've tested again now on the latest Windows app and it is working for me there as expected as well. I'm going to close this issue for now. Could you contact us through support so we could do some troubleshooting there? You can reach it at support@simplenote.com.

As a couple of first steps, you may want to try uninstalling and reinstalling the app and see if it works in the web version at https://app.simplenote.com

**Comment by codebykat** [comment]
This fix was in 2.4.0 so @svenfinger no need to contact support, just update to the latest version!

**Comment by svenfinger** [comment]
Thank you for the hint, @codebykat. In the Windows Store I only get offered v2.2.0, even if I search for updates manually.

So, I updated to the latest version by manually downloading the .exe on v2.4.0 from the GitHub Releases and I tried it in the web app (which is for me at v2.4.0-beta2). But in both ways, it's not working for me.

I now tried v2.5.0-beta1 and there it's working for me again. 😉

**Comment by codebykat** [comment]
Thanks for the reminder, @svenfinger, we need to update web to 2.5.0-beta today 😅  I'll double-check on the Windows store updates, it's odd that it's not offering an update to the latest version over there.
