### ISSUE TITLE
Mac dictation results in duplicated text using Firefox in web app

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/simplenote-electron#2579]
When looking at https://github.com/Automattic/simplenote-electron/issues/1567 I tried to test to see if it was something with voice to text in general. I tried to use the built in Mac dictation option.

### Expected

I expected as I spoke the text would appear in the note.

### Observed

The text did appear. As I finished with the text I wanted to input the text would suddenly duplicate. 

### Reproduced

1. Using a Mac start a new note
2. Press the FN key twice to start dication
3. When finished click done on the dictation control or return/enter on the keyboard.
4. Notice the text which had appeared in the note is duplicated.

![Screen Capture on 2021-01-14 at 10-44-48](https://user-images.githubusercontent.com/1326294/104606068-ad9eb380-5655-11eb-9be3-385520dfee62.gif)

### Where did you see the bug
- System Make: Mac
- System Model: MacBook Pro
- OS: MacOS Catalina
- OS version: 10.15.7
- Browser (if applicable): Firefox
- Browser version (if applicable):  84.0.2
- Simplenote app version: Web

**Comment by codebykat** [comment]
I suspect this to be the same issue as our old friend #2394, I guess we'll see if they ever release that upstream fix.
