### ISSUE TITLE
Ambiguous icons

### ISSUE THREAD

**Issue by philipjohn** [Automattic/simplenote-electron#258]
While it's pretty obvious what most of the icons are for, some aren't and hovering on them gives no indication as you might expect.

It'd be good to add tooltips to icons at least to help add context.

**Comment by philipjohn** [comment]
Specifically, the "revisions" and "share" icons.

Related: the "share" icon looks like an upload icon, but then the dialog that opens says "share" which seems inconsistent to me as well.

**Comment by Sushubh** [comment]
Yes. You expect tooltips to be available by nature! I had to click on all of them to see what they did!

**Comment by rikai** [comment]
One of the very first things i did when installing this app was to hover over the icons to see what they were for and when they annoyingly gave me no tooltips, to click them to find out, so i can very much agree with this suggestion.

**Comment by soren121** [comment]
Using the `cursor: pointer;` style on the buttons would also help!
