### ISSUE TITLE
Make it so you can edit the text while you are in preview mode

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#2582]
Make it so you can edit the text while you are in preview mode. great example of this is vivaldi notes:  
(gif:)
![gif](https://cdn.discordapp.com/attachments/704792091955429426/800025088287178772/Rec_2021_01.16_1632.gif)

**Comment by codebykat** [comment]
Thanks @KraXen72, we have a number of previous requests for something like this (live preview or side-by-side editing). It's something we'll consider in the future but it's not on our immediate roadmap so I'm closing this for now.
