### ISSUE TITLE
[Tags] Make space a tag submit key, as done in iOS and Native

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2588]
### What
Tags with spaces are not allowed. This is very straightforward in iOS and Native: user hits space, all text before space is submitted.

Now, in Electron, when user enters a string with spaces as a tag, and submits it with Enter or comma, multiple tags will be created. This can be confusing.

### Why
For the sake of consistency.

### How
Once user hits space, text before space is submitted.

Same as https://github.com/Automattic/simplenote-electron/pull/1798, but for space.

**Comment by pachlava** [comment]
Just noticed it's mentioned in more extended https://github.com/Automattic/simplenote-electron/issues/2207. Let me know if I should drop current one, or it can be used as a container for a separate fix.

**Comment by sandymcfadden** [comment]
I am going to close this one in favor of #2207 I'm working on all the issues listed in that one now.
