### ISSUE TITLE
Tag input not cleared when switching notes

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2589]
### Expected
The root cause is that tag is not submitted in Electron as soon as tag editor looses focus (clicked out).

### Observed
See video (make sure to have player controls hidden - they cover the area where fun takes place). It's possible to enter a text as a tag, not submit it, switch between notes, and have this text shown instead of 'Add a tag...'

### Reproduced

1. In any note, start adding a new tag
2. Don't submit a tag
3. Open / create other note ~> the not submitted text will be shown in all notes instead of 'Add a tag...'

https://user-images.githubusercontent.com/73365754/105096505-d8eb2d80-5aaf-11eb-8a2c-d85edd99b1bf.mov

### Where did you see the bug
- System Make: PC | Mac
- System Model: Some DELL laptop | MBP 15"
- OS: Win | macOS
- OS version: Win10 | macOS 10.15.7
- Browser (if applicable): X
- Browser version (if applicable): X
- Simplenote app version: Electron app 2.5.0-beta1

**Comment by codebykat** [comment]
Huh, interesting find. I'm not sure if this is a bug or not. If you've entered something in that text input, it isn't cleared on switching notes. I guess we should probably clear it.

**Comment by codebykat** [comment]
I definitely don't think that we should **submit** any unfinished tag as a tag when you switch notes, that seems a bit unexpected to me.

**Comment by pachlava** [comment]
I agree it's hard to consider this a bug, I'd say this just looks a bit weird. In native and iOS the tag is submitted in this case though...

**Comment by sandymcfadden** [comment]
I was taking a look at this and agree it feels weird the way it is. Working as native and iOS do makes sense to me. If I have typed a tag on a note, but not submitted, and then click out of the tag field it seems like that tag should be submitted. To me clicking away means I'm done inputting now.

**Comment by codebykat** [comment]
When in doubt, making it consistent with the other platforms is usually a good bet.

**Comment by pachlava** [comment]
[testing] fix/feature verified on Dell Latitude 7400 | Win 10 | Simplenote 2.7.0-beta1
