### ISSUE TITLE
[No Network] 'Close window' button text in unsynced notes alert can be misleading

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2590]
### What
Once user has no connection, and closes the desktop app, they will see this:
<img width="366" alt="Screenshot 2021-01-20 at 10 53 26" src="https://user-images.githubusercontent.com/73365754/105151080-32824500-5b0e-11eb-9b6f-2ac5c53351e9.png">

It's not really clear what is meant under 'window': the app itself or the alert.
Having it renamed to 'Close anyway' or 'Close Simplenote' will help in clarifying.

### Why
User might click 'Close window' thinking it will only close the alert.

**Comment by codebykat** [comment]
Thanks! @SylvesterWilmott Opinions on this?

**Comment by SylvesterWilmott** [comment]
"Close anyway" sounds like a clearer label for this button.

**Comment by codebykat** [comment]
Great, will update this in the next version.
