### ISSUE TITLE
[All Notes] Trashed note content and controls can be visible in 'All Notes' screen

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2593]
### Expected
When in 'All Notes' section, the preview for the note should show only the preview of notes from 'All Notes'

### Observed
When trashing all notes on another device, and creating new notes there, user will see the content of trashed note in Electron/Web once they open the app, and app shows 'All Notes'

### Reproduced
Reproducible on Web, and desktop macOS. Should not be reproducible on desktop Windows. Not sure about desktop Linux.

1. Electron: create some notes. close the app either by closing the browser tab, or by clicking the (x) button in semaphore (this will not kill the process).
2. Other device (I used native app): Trash **all** notes and create some new
3. Electron: open the tab again, or launch the window again (for macOS electron desktop)
4. See this (trashed note preview while in 'All Notes'):

<img width="953" alt="Screenshot 2021-01-22 at 13 52 49" src="https://user-images.githubusercontent.com/73365754/105488745-cb55c380-5cba-11eb-90b7-216d1adcabbe.png">

### Where did you see the bug

- System Make: Mac
- System Model: MBP 15
- OS: macOS
- OS version: 10.15.7
- Browser (if applicable): Chrome | Desktop Electron
- Browser version (if applicable): Chrome 87.0.4280.141
- Simplenote app version: 2.5.0-beta1

**Comment by codebykat** [comment]
Hi @pachlava, I think this is working as intended - you still have the trashed note selected/open. You can see that the note is trashed because you now have a Delete Forever and Restore Note action. The app remembers which note you last had open and does its best to restore that view on re-open, even if the note's status has changed.

**Comment by pachlava** [comment]
@codebykat got it, thanks!
