### ISSUE TITLE
Electron: All menu items are visible when signed out

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#261]
When you are signed out of the electron app, all menu items are visible. It doesn't seem to cause anything terrible to happen when you select them, but it does still update the state so settings do get changed.

It'd be nice if we could hide the items that we don't want to show when the user is signed out.

**Comment by dmsnell** [comment]
@roundhill it doesn't look like many menu options are relevant when logged out…

 - About Simplenote
 - View > Toggle Full Screen
 - Window (full menu)
 - Help (full menu)

@drw158 can you review that list.

What do we want to show in this case (logged out)?

**Comment by drw158** [comment]
It looks like that list of items are the only relevant ones for logged out 👍

**Comment by codebykat** [comment]
I'm closing this, it doesn't look like there's anything we need to do. @roundhill feel free to re-open if there's still a concern!
