### ISSUE TITLE
Disallow adding new note when in trash.

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/simplenote-electron#2612]
Currently if you enter the trash adding a new note is confusing.

### Expected
When in trash you shouldn't be able to add a new note. 

### Observed
The button in the toolbar is more faded, but still changes to a pointer when you hover and gives the keyboard shortcut to add a new note. If you click the button nothing happens.

If you use the keyboard shortcut it creates a new note. Changes the heading from Trash to All Notes, but still shows the notes which are in the trash.

If the trash is empty you get a create new note link which behaves the same as above.

### Reproduced

1. Open Simplenote
2. Click to enter the Trash
3. Empty trash and click add new note link or use keyboard shortcut `Ctrl + Shift + i` to insert a new note
4. Notice the heading change
5. Notice the new note doesn't appear

https://user-images.githubusercontent.com/1326294/106280264-10767a00-6214-11eb-980d-300128683e68.mov

### Where did you see the bug
This really applies everywhere for Web/Electron

- MacBook Pro 16-inch 2019
- OS: MacOS Catalina
- OS version: 10.15.7
- Simplenote app version: 2.5.0

**Comment by dmsnell** [comment]
is disabling creating new notes the most appropriate way to resolve this confusion? when I look at this it seems like we should _always_ be able to quickly create a new note. if that's confusing in the trash, maybe we could make sure the app properly flips to the *All Notes* view and that the search list updates accordingly.

**Comment by sandymcfadden** [comment]
@dmsnell I think disabling it makes sense. If I'm in the trash I'm thinking about restoring a note that is there, not create a new note. This also follows what seemed to be the desired approach the app wanted to take as well. When in the trash the button shows as disabled, but there are still other ways to create a new note. This seems to be how Mac Native and iOS work as well, giving no way to start a new note when in trash.

I'm happy to look at this approach instead though. @belcherj what do you think as you proposed not giving the new note option when in trash?

**Comment by sandymcfadden** [comment]
@SylvesterWilmott your thoughts on this would also be much appreciated.

**Comment by SylvesterWilmott** [comment]
There's two separate issues here. It looks like the wrong empty state is being used in the trash. I will add the full list of empty states into the Zeplin project so those can be aligned.

The issue of whether you should be able to create a new note from the trash is something that should be added to our list of UX inconsistencies since currently, on Android, you **can** create a new note from the trash using the FAB. cc: @pachlava

**Comment by dmsnell** [comment]
maybe on a mobile device it makes more sense to not allow creating notes from the trash view, given that the normative view for those are _either_ the note list _or_ a note editor.

on bigger screens, especially the desktop/web app but also on tablets with keyboards and other mobile screens, the use-case feels very different to me. really, I feel stronger about this than most UI things that I find myself at odds with. specifically disabling the keyboard shortcut seems to be the sticker: disabling the icon to better communicate that you're in the trash seems understandable, but we're somewhat arbitrarily disabling shortcuts people use and I'd be surprised if many people don't normally look in the trash for something but then change contexts and want to create a new note, or interrupt what they were doing to create a new note.

**Comment by sandymcfadden** [comment]
Thank you @SylvesterWilmott and @dmsnell!
I'll create a new issue for updating the Empty states to match. 

I don't feel strongly about fully disabling new notes when in trash, so let me rework the PR to allow the keyboard shortcut at least and reset things to the all note view when a new note is created when in trash.

**Comment by sandymcfadden** [comment]
New issue opened for the empty note states https://github.com/Automattic/simplenote-electron/issues/2627

**Comment by codebykat** [comment]
Just to leave my $.02 on this one, I think it makes more sense to switch to All Notes when a new note is created from the Trash rather than disallow it. That resolves the confusion where the new note wouldn't show up immediately upon creation.

**Comment by sandymcfadden** [comment]
I believe the recent changes I made to https://github.com/Automattic/simplenote-electron/pull/2618 addresses this but I could use maybe some pair time with you @codebykat when you have some time on the way I did it.
