### ISSUE TITLE
1st typed letter is missing when second letter is typed in Japanese Kana mode.

### ISSUE THREAD

**Issue by junsan99** [Automattic/simplenote-electron#2615]
### Expected

Japanease typed letter is disappeared.

### Observed

Sometimes 1st letter is missing when 2nd letter is typed.
In this case  I want to input "テスト", but end of the movie, 1st "テ" is accepted, but when second "ス" is input, 1st "テ" is disappeared.
In Kana mode, "テ"and "ス" are showed in one key type.
It seems some wrong signal is inserted before 2nd letter is typed. So sometimes disappeared, sometimes remail storange word.

### Reproduced

1. In japanease Kana mode.
2. Type "テスト" and Enter is itterated.
3. In some case, 1st letter is disappeared. or insert indention.

In my test, this behavior is happen in Japanease letter. 
And it seems that behavior are appear between letter line. not in new line.

In simplenote-electron Ver.2.1, it doesn't happen.

https://user-images.githubusercontent.com/23394784/106446059-28bff080-64c3-11eb-87be-2b014c02edeb.mp4

### Where did you see the bug

- System Make: PC
- System Model: Thinkpad X1
- OS: Windows 
- OS version: 10 home 64bit
- Simplenote app version:  2.5 and 2.6-beta2

**Comment by codebykat** [comment]
Thanks for the report, @junsan99. This is being investigated already and we hope to have a fix soon. In the meantime you might be able to use the website successfully instead of the app (https://app.simplenote.com). #2522

**Comment by junsan99** [comment]
Thanks! 
I misunderstood #2522 is closed. 2.6-beta2 is not fixed that, so report it.
