### ISSUE TITLE
when input chinese punctuation symbol (：；), it will auto repeat copy many content.

### ISSUE THREAD

**Issue by boycuijg** [Automattic/simplenote-electron#2628]
hello

hello

hello

hello

hello

hello

你好：：：；

**Comment by codebykat** [comment]
Leaving this open for now, but possibly related to #2522 

@cSingleboy What version of Simplenote are you using, and what OS? Are you using the desktop app or web browser?

**Comment by boycuijg** [comment]
OS：Win10
Simplenote-Version：lastest version（try many version）
desktop app

**Comment by codebykat** [comment]
Thanks for that information - We're investigating this under #2522 and hope to have a fix soon, so closing this as a duplicate. As a workaround, you should be able to access app.simplenote.com in a web browser other than Firefox (Firefox fix will be in the next version), where it should work -- please let me know if that is not the case.
