### ISSUE TITLE
Linux: app crashes when Markdown is enabled on a note with long Python and/or JS snippets

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/simplenote-electron#2629]
We got a report from a user in Ubuntu whose app crashes whenever you enable Markdown on a note that is full of Python and JS.
 
### Expected
To be able to see the snippets/note without any issues.

### Observed
When you enable Markdown, it causes the app to crash. A note with less python or JS does not crash the app, but the desktop app is still slower than the web app. 

### Reproduced
1. Open Simplenote on Linux
2. Create a new note
3. Copy and paste the contents of this snippet, for example: https://jeromeetienne.github.io/virtualjoystick.js/virtualjoystick.js

### Where did you see the bug
- OS: Ubuntu
- OS version: 20.04.2 LTS
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.5.0

Report: 3672704-zen

**Comment by codebykat** [comment]
I'm assuming this was fixed at some point, maybe in #3183 if not before. I noticed that Monaco has changed their tokenization to run async. Let's reopen if we get any more reports.
