### ISSUE TITLE
Can't copy text in markdown preview mode on Windows app

### ISSUE THREAD

**Issue by Sushubh** [Automattic/simplenote-electron#263]
It works in the web app so I assume it should work in the Windows app as well? Using editor to copy notes is kind of annoying because of all the markdown elements.

**Comment by drw158** [comment]
Noting here that we'd just need to add `user-select: all; ` on the preview element.

**Comment by roundhill** [comment]
> Noting here that we'd just need to add user-select: all; on the preview element.

Easy PR then :) Let's do it!

**Comment by Sushubh** [comment]
Just curious... The app would update by itself (assuming it is kind of a wrapper around a web app) or we would need to download updates? There is no option in the app to check if there is an update? Thanks.

**Comment by roundhill** [comment]
> The app would update by itself

It will prompt you when there is an update available!
