### ISSUE TITLE
Implement TOC (Table Of Content) in simplenote markdown

### ISSUE THREAD

**Issue by vtgdias** [Automattic/simplenote-electron#2636]
### What

A TOC (Table Of Content) in markdown implementation of Simplenote

### Why
Better organization of big notes

### How
As any ordinary TOC markdown feature (github as example)

**Comment by pachlava** [comment]
Added a vote to existing feature request: p7rJFO-dV-p2

**Comment by adyomin** [comment]
> Added a vote to existing feature request: p7rJFO-dV-p2

Is this some public document and/or tracker? I would like to cast a vote in favor of this feature as well.

**Comment by pachlava** [comment]
@adyomin this is our internal tracker. Your vote has been just added 🙂

**Comment by shon** [comment]
+1

**Comment by fcic** [comment]
+1
