### ISSUE TITLE
Custom stylesheet and monaco config in electron app?

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#2637]
### What
Please add an option for us to select a custom stylesheet and monaco config for the electron app.

### Why
Custom stylesheet: There are ways to inject css into electron apps but many of them are sketchy and break on updates, it would be great if we could import our own css stylesheet, for example custom dark theme etc.

Monaco config: To allow more precise control over the monaco features like smooth caret, etc. alternatively you could add the smooth caret option to settings.

### How
Custom stylesheet: make a electron.openDialog to select a custom css file. it would write this path to localStorage and load it on startup

Monaco config: either the same way as a custom stylesheet or make it a settings (for the smooth caret)

**Comment by codebykat** [comment]
Thanks! Themes are on the roadmap. Exposing Monaco config is an interesting idea, though it seems like it might cause more trouble than it's worth (would be quite easy to break things). We did have at least one other person request a setting for smooth caret. Is there another Monaco setting you would want to adjust?

**Comment by KraXen72** [comment]
honestly i only want the smooth caret, but please add the options for custom stylesheet

**Comment by codebykat** [comment]
Oh, the [prior request](https://github.com/Automattic/simplenote-electron/issues/2512) for smooth caret was also from you, I see now 😄  Okay closing this since these requests are tracked elsewhere. Themes are definitely on the roadmap already. No promises about smooth typing setting as it's not something a lot of people have asked for, but your request has been noted.

**Comment by KraXen72** [comment]
i know this is closed, but i've made a custom stylesheet/theme for simplenote (currently only works in browser), so you guys can see the benefit of a custom css stylesheet i guess.
this is how it looks:
![Capture_2021_m02 d10_16;34](https://user-images.githubusercontent.com/21956756/107626176-b509aa80-6c5d-11eb-9d62-11c37f3cc1fe.png)

this is originally for my personal use only, but if you guys are planning some theme store or something (you said themes were on the roadmap so i don't know if you mean like a set of themes or just ability to add a custom stylesheet), i would be glad to provide this css in the set.
