### ISSUE TITLE
markdown preview in separate window

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#2638]
### What
refer to this screenshot from vs code:
![Capture_2021_m02 d08_10;51](https://user-images.githubusercontent.com/21956756/107203374-a623bd80-69fb-11eb-9df7-3f21a9b8c3f9.png)
every time you change the markdown on the left it would update the render on the right.

### Why
No need to toggle visual mode + better utilization of screen real estate if you have a big screen

**Comment by codebykat** [comment]
Hi @KraXen72, we've had a number of previous requests for this. See #460

It's something we'll consider in the future but it's not on our immediate roadmap so I'm closing this for now. Thanks!
