### ISSUE TITLE
Open links in default browser

### ISSUE THREAD

**Issue by hindsholm** [Automattic/simplenote-electron#264]
When clicking on a link in a note, the page opens in a new window with a simple webview (or similar).
It would be very nice to have the option of opening links in the default browser instead.

**Comment by drw158** [comment]
Interesting, that is unexpected. I'll file as a bug. Thanks!

**Comment by hindsholm** [comment]
I didn't know that it was a bug, I thought it was intentional :)
But glad to hear that it will be fixed...

**Comment by drw158** [comment]
Documentation for the solution to this: https://github.com/atom/electron/blob/master/docs/api/shell.md#shellopenexternalurl

**Comment by roundhill** [comment]
Closed via #283
