### ISSUE TITLE
Extra line breaks on exported notes

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-electron#2646]
It was reported in 3706246-zen that extra line breaks can be seen on Notepad for notes that were exported from the Electron app on Windows. However, the line breaks are not rendered on WordPad.

### Expected

The user expects that the exported notes are showing the same line-breaks as the notes on the Simplenote app.

### Observed

Extra line breaks are observed when the exported notes are opened on Notepad. However, if the same note is opened on WordPad, no line break is seen.

The user also noticed that on Notepad, the line break type is `Macintosh (CR)`.

### Reproduced

1. Create a note with the single line break and double line breaks on the Electron app
2. Export the note through File > Export Notes...
3. Extract the note and open up the .txt file with Notepad
4. Extra line breaks can be seen on Notepad
5. Open up the same .txt file with WordPad, see that no line break show up on the note
6. Open the same .txt file with Notepad++ (or a text editor that shows hidden characters), we can see that apart from the `CR` characters, we see some additional `LF` characters that cause the additional line breaks.

![Markup on 2021-02-09 at 12:30:25](https://user-images.githubusercontent.com/40906847/107325466-bebbd280-6ae4-11eb-9b9b-1d399a8b1cdb.png)

### Reproduced on

- OS: Windows
- OS version: Windows 10 Pro
- Simplenote app version: 2.6.0

**Comment by mdrockwell** [comment]
Possibly another related instance here: 3805837-zen

> If create a new note and input line feed codes "CR+LF" in the web app opened in Chrome for Windows, the line feed codes are regarded as line feed codes "CR" & "CR+LF" in the iOS app.
> This bug has occurred since v4.30

They also included a video of the issue in the ticket — bug 3.

**Comment by pachlava** [comment]
Same happens in json:

```
{
  "activeNotes": [
    {
      "id": "dec4c464-8281-411f-8eb4-4597cf8dfa3c",
      "content": "Internally linked note\r\n\r\nSome content goes here...",
      "creationDate": "2021-03-15T09:33:23.002Z",
      "lastModified": "2021-03-15T09:33:43.210Z"
    }
  ],
  "trashedNotes": []
}
```

**Comment by pachlava** [comment]
Removed the 'Windows' ending from the title since it's the same on macOS and Ubuntu
