### ISSUE TITLE
Simplenote app still asks me to verify email after i've done it

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#2647]
### Expected
once the email is verified, it shouldn't ask me to.

### Observed
it wants me to verify my email even after i've done it.

### Reproduced
example: 
1. start simplenote app
2. click verify
3. verify it
4. click X on the dialog to verify
5. relaunch app and it still wants to verify

### Where did you see the bug
- OS: Windows
- OS version: 10
- Simplenote app version: 2.6.0

**Comment by codebykat** [comment]
Hi @KraXen72, this is very odd, I can't reproduce it. Does it also give you the prompt to verify if you log in to app.simplenote.com in the browser?

**Comment by KraXen72** [comment]
yes, and i also sends an email. after i click it it then redirects back, says email verified but when i close and open simplenote it still asks me to verify

**Comment by codebykat** [comment]
@KraXen72 Can you please email support@simplenote.com and let us know what email you're registered with, so we can troubleshoot further? Thanks :)

**Comment by KraXen72** [comment]
alright, thanks.

**Comment by gfedun321** [comment]
It still bugs me with this message.

**Comment by atocyo** [comment]
Same, still not solved. Maybe it is supposed to work that way? I checked may emails I verified 4 times in last 30 days.
