### ISSUE TITLE
New revision slider should not cover tags area

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2654]
### What
Since changes in tags is a part of a note history, it makes sense to have tags area visible while browsing the revisions.

### Why
When the tags area is covered by history overlay, it's impossible to see the changes in tags.

### How
Make tags area appear above revisions panel

**Comment by belcherj** [comment]
Check with @SylvesterWilmott on this one.

**Comment by fluiddot** [comment]
When the note history is opened, the content of the note is previewed but it doesn't include the tags. One way to solve this would be to render the tags of the revision in a new component at the bottom of the content, similar to what is displayed when editing.

**Comment by SylvesterWilmott** [comment]
@fluiddot From the point of view of the user, the history panel would push up all of the editor content including the tags input field?

**Comment by fluiddot** [comment]
> @fluiddot From the point of view of the user, the history panel would push up all of the editor content including the tags input field?

Yeah, although the tags won't be interactive. I created a [PR](https://github.com/Automattic/simplenote-electron/pull/2817) with a potential solution and here you can see how it looks like:

https://user-images.githubusercontent.com/14905380/113137113-65d70380-9224-11eb-9684-17e9e05655c5.mp4

Let me know @SylvesterWilmott what you think about this option, thanks 🙇 !
