### ISSUE TITLE
New revision slider should always allow to see whole note content

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2655]
### Expected
It should be possible to see the note content completely while checking the revisions.

### Observed
If the note is big enough, its final part will be covered by the revision panel.

### Reproduced
1. Have a note of decent length (see picture)
2. Open History
3. Scroll to the bottom

![Screenshot_2021-02-11 00 41 51_5p6w8U](https://user-images.githubusercontent.com/73365754/107582372-0edc8700-6c02-11eb-9ae2-2f3954df56c5.png)

- System Make: Mac
- System Model: MBP 16"
- OS: macOS 
- OS version: 11.2
- Browser (if applicable): X
- Browser version (if applicable): X
- Simplenote app version: Electron 2.7.0-beta1

**Comment by sandymcfadden** [comment]
I didn't think about this or #2654 when making these changes. 

What do you think of these two issues @SylvesterWilmott?

**Comment by SylvesterWilmott** [comment]
Agree, the history UI should resize the editor area as opposed to covering it.
