### ISSUE TITLE
Synchronize preview scroll position with monaco scroll position

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#2656]
### Expected
When i scroll to the bottom in monaco and hit preview (Ctrl + shift + P) it should instantly scroll the preview to the bottom

### Observed
When i scroll to the bottom in monaco and hit preview (Ctrl + shift + P) i am on the top of the document

### Reproduced
1. Go to a note
2. Scroll down
3. Click preview
4. you are at the top

### Where did you see the bug
- OS: Windows
- OS version: 10
- Browser (if applicable): Vivaldi and also in simplenote electron
- Browser version (if applicable): latest stable
- Simplenote app version: 2.6.0

**Comment by codebykat** [comment]
Interesting, we can think about this as part of #2599.
