### ISSUE TITLE
VS code simplenote sync extension?

### ISSUE THREAD

**Issue by KraXen72** [Automattic/simplenote-electron#2657]
### What
Make a simple extension so we can use vs code to edit .md files and upload them to the simplenote for easy access.

### Why
Vs code has better customisability, syntax highlighting for markdown, custom themes and smooth caret, and even though simplenote uses monaco which is the same editor, i miss a lot of features form vs code when writing markdown

### How
after installing the extension you would pick a folder, it would download there all the .md files of notes you have. then you can edit them with vs code and the extension would then sync them back to simplenote

**Comment by codebykat** [comment]
🤔  I'll log it on our feature requests. It sounds like it falls under the idea of two-way file system sync generally... in other words you wouldn't need to use VSCode, you could use any Markdown editor you like.

Closing now, not on our immediate roadmap, but will be considered in the future. (There are some annoying technical problems with file-system sync such as filenames and revision history, so it's non-trivial to figure out how Simplenote data would map to text files.)

#1261, #271

**Comment by tonyjly** [comment]
+1 for this. Would love an extension for vscode specifically. Would add value to Simplenote to use vscode features/extensions and automatic sync.
