### ISSUE TITLE
32 bit build for Linux

### ISSUE THREAD

**Issue by habi** [Automattic/simplenote-electron#266]
It would be nice if you could provide a 32 build for Linux.

**Comment by Yanpas** [comment]
I don't expirience this issue. I just wanted to say thanks for linux version! :smiley:

**Comment by progkix** [comment]
Adding my support for a 32 bit build for Linux as well. Doesn't necessarily need to be distribution specific - a gzipped archive would work just fine.

**Comment by drw158** [comment]
There are no plans to offer a 32 bit Linux build at the moment. We are currently adhering to the standards of https://github.com/Automattic/wp-calypso

**Comment by mirka** [comment]
We now offer several 32-bit builds (ia32, i386, i686) for Linux 🎉
https://github.com/Automattic/simplenote-electron/releases
