### ISSUE TITLE
Review Your Account

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2663]
### Observed
At start the pop-up message "Review Your Account" appears every time

### Reproduced
1. At start the pop-up message "Review Your Account" appears 
2. I press on confirm
3. I open the email I have received and klick on the link
4. It is confirmed with "Email Verified"
5. I close Simplenote app version 2.6.0
6. I restart Simplenote app version:2.6.0
7. The the pop-up message "Review Your Account" appears again (and again)

This does not happen with Simplenote app version 2.5.0 
on my business PC (also Windows 10)

### Where did you see the bug
- Windows 10 
- Simplenote app version: 2.6.0

**Comment by codebykat** [comment]
Hi @gubrist, sorry for the trouble. Can you try logging out of the app and back in again and see if that gets it to refresh your account info?

**Comment by gubrist** [comment]
Thanks, this has worked out.

**Comment by gubrist** [comment]
Thanks, this has worked out.

**Comment by marty331** [comment]
![Uploading Screen Shot 2021-03-03 at 8.19.38 AM.png…]()
This is still happening for me, I'm on Mac version 2.8

**Comment by codebykat** [comment]
Hi @marty331, if logging out and logging back into the app doesn't fix the issue, can you please email us at support@simplenote.com so we can debug further? We can't debug account problems on the public GitHub. 😅 Thanks!
