### ISSUE TITLE
Unpinning note via history leaves unpinned note above pinned ones

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2664]
### Expected
Unpinned note should not mix with pinned ones.

### Observed
If a note in unpinned via history, its position in the note list will not change:
![Screenshot_2021-02-11 20 12 24_SW8YnN](https://user-images.githubusercontent.com/73365754/107679714-929b7f80-6ca5-11eb-9b08-50cfcf13860e.png)

### Reproduced
1. Make sure you have an unpinned note
2. Have 'Sort by Modified: Newest' enabled for better display
3. Pin the note ~> It should appear at the very top of notes list
4. Open history for the note and revert to previous revision ~> note is no longer pinned, but still is placed at the very top (see pic above)

### Where did you see the bug
- OS version: both Win10 and macOS 11.2
- Browser (if applicable): Chrome and also Electron
- Simplenote app version: 2.7.0-beta1

**Comment by FedeCuci** [comment]
I am using Simplenote on Google Chrome (web version). Where do you see the setting 'Sort by Modified: Newest'. Or is that why you said: 'Browser (if applicable): Chrome and also Electron'?

**Comment by codebykat** [comment]
Hi @FedeCuci, there is an option to change the sort order at the bottom of the notes list. You can see it in the bottom left of the screenshot above. It should appear in any browser. If you've had the app open in a tab for a few days without closing it, you might need to refresh the page.

**Comment by FedeCuci** [comment]
Hi @codebykat, thanks for the answer. I didn't notice before now. I was able to replicate the issue.
