### ISSUE TITLE
MacOS Download link directs to obsolete (1.0.8) application version.

### ISSUE THREAD

**Issue by krzysztofzygmunt** [Automattic/simplenote-electron#2665]
As a potential new user of Simplenote for MacOS I read a https://simplenote.com/tag/electron/ page.
I click "Continue reading" link.
I'm redirected to https://simplenote.com/2017/02/14/try-the-new-macos-beta/ page.
I'm reading about new Electron version.
There is a link at the bottom "Ready to try it out? Download now!" which directs to old version https://github.com/Automattic/simplenote-electron/releases/download/v1.0.8/Simplenote-macOS-1.0.8.zip which does not work as expected on new MacOS system.

### Expected
a link which directs to a newset application release 

### Observed
a link which directs to an OLD application release 

### Reproduced
Already described above.

I hope, no need.

### Where did you see the bug

Not related to browser, OS or application version. Just wrong link.

**Comment by codebykat** [comment]
Hmm I'm not sure what to do with this one. That's a blog post from 2017, and the correct download links are also on simplenote.com. We also have a native app for Mac users these days, and consider Electron primarily for Windows/Linux. I guess I can add an update banner to it.

**Comment by codebykat** [comment]
Alright, after some discussion we've added a banner to this page. I also updated the download link to point to the latest releases in this repository.

<img width="724" alt="Screen Shot 2021-02-11 at 12 48 21 PM" src="https://user-images.githubusercontent.com/52152/107697007-82fd4600-6c67-11eb-9597-fee5c66135b9.png">

Thanks for the report, @krzysztofzygmunt!
