### ISSUE TITLE
MacOS desktop app: Not working "Find in Note" (Cmd+F)

### ISSUE THREAD

**Issue by krzysztofzygmunt** [Automattic/simplenote-electron#2666]
When I press Cmd+F (Find in Note) I end up Searching Notes, not Finding in Note.

Pressing Cmd+F (Find in Note) or Cmd+Shift+S (Search Notes...) does the same.

There is no way to "Find in Note".

### Expected
When I press Cmd+F application is finding in note.

### Observed
Pressing Cmd+F (Find in Note) or Cmd+Shift+S (Search Notes...) does the same.

### Reproduced
Just press Cmd+F and It's not Finding in Note, It's Searching Notes.

### Where did you see the bug
- System Make: Apple
- System Model: MacBook Pro (late 2013)
- OS: macOS Big Sur
- OS version: 11.1
- Browser (if applicable): NA
- Browser version (if applicable): NA
- Simplenote app version: 2.6.0

**Comment by codebykat** [comment]
Hi @krzysztofzygmunt, the search also highlights matches within each note, and allows you to move through them with the search results bar at the bottom of the note. Is that not working for you?

**Comment by krzysztofzygmunt** [comment]
Hi @codebykat , yes it works as you just wrote. I just thought there would be a difference by using Cmd+F or Cmd+Shift+S.
If that's by design, than ok.

**Comment by codebykat** [comment]
Thanks for the feedback!
