### ISSUE TITLE
Resize divider between list and notes

### ISSUE THREAD

**Issue by rodalpho** [Automattic/simplenote-electron#267]
Please allow the user to resize the divider between the list on the left and notes on the right. It’s a terrible waste of space.

**Comment by drw158** [comment]
We hope to do this in the future at some point.

**Comment by dnv** [comment]
Really really hoping this makes it into the next version

**Comment by jtoy** [comment]
+1

**Comment by mirka** [comment]
Looks feasible with something like [React Split Pane](http://react-split-pane.surge.sh/basic-vertical). I'm not immediately sure what the effects will be on note list rendering performance though.

**Comment by belcherj** [comment]
I think this is already complete:
<img width="421" alt="Screen Shot 2019-10-31 at 11 15 22 AM" src="https://user-images.githubusercontent.com/6817400/67960022-0bb9b500-fbd0-11e9-8366-d2d63c987512.png">
