### ISSUE TITLE
Import from Evernote won't import images

### ISSUE THREAD

**Issue by adam-jones-net** [Automattic/simplenote-electron#2670]
What I want:  I'm leaving Evernote after their disastrous recent rebuild.  I had high hopes that simplenote would be the answer but it can't import images from Enex files.  

Why:   Surely this can't be that complex, other competitor software can do this.    Some rich media embeds ok I understand if they can't be imported, but images?   I know this is simplenote and images via markdown is only supported but if you want to take a load of the people leaving Evernote right now I'd seriously reconsider some of these choices.

**Comment by codebykat** [comment]
Image support has been requested in the past and we may consider it someday, but for now, not planned.
