### ISSUE TITLE
Description for tags

### ISSUE THREAD

**Issue by FedeCuci** [Automattic/simplenote-electron#2673]
### What

Allow the user to add a description to the tags explaining how the tag should be used and when. 

### Why

Some tags might be used as subtags of a tag to categorize a certain note more thoroughly. If many tags are created a user might forget the difference between 2 tags that are very similar. A brief description of the tags would allow the user to recall the specific purpose of a tag and how it should be used.

**Comment by eduardozulian** [comment]
Hi there, 

Thanks for your patience and for this suggestion. Since Feature Requests are organized internally, I will move your request to our ideas board so we can monitor it.

Thanks again!
