### ISSUE TITLE
Double ⌘Q needed to quit the application

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2676]
I saw the same report here: #2445, which is said to be fixed with #2439, but it looks like it isn't. Correct me if I'm wrong.

### Expected
First ⌘Q should close the Simplenote process.

### Observed
On Mac, the first ⌘Q closes the window (similar to ⌘W), and only the second ⌘Q closes the process.

### Reproduced
1. Have the app window shown and be logged in
2. Hit ⌘Q ~> the window is closed, but the process is not closed.

### Where did you see the bug
- System Make: Mac
- System Model: MBP 16"
- OS: macOS
- OS version: 11.2 
- Simplenote app version: 2.7.0-beta1

**Comment by cappadona** [comment]
Also still experiencing this bug.

```
System Make: Mac
System Model: MBP 13" (2017)
OS: macOS
OS version: 10.15.7
Simplenote app version: 2.7.1
```

**Comment by fluiddot** [comment]
I saw that we're explicitly [forcing this behaviour on MacOS platform](https://github.com/Automattic/simplenote-electron/blob/a682de65213b38de0ea8796d688934d1d29bc60e/desktop/app.js#L186-L188). I'm not sure about the implications of removing it so I'd appreciate if someone with more context could provide some insights.

cc @belcherj as the author of the [PR](https://github.com/Automattic/simplenote-electron/pull/2277/files#diff-767c5388b7d5fbdb5dd8340716fa0eed5fccfdf1a33007f1fa091bc622aa5aaaR168-R170) that introduced the changes

**Comment by belcherj** [comment]
@sandymcfadden this would be a good one to look at when you get a chance.
