### ISSUE TITLE
Primary buffer does not work when selecting text

### ISSUE THREAD

**Issue by KOT040188** [Automattic/simplenote-electron#2677]
Я обновился на версию 2.6.0 и у меня перестал работать primary buffer в Simplenote. Теперь когда я выделяю текст в Simplenote он не попадает в primary buffer. Во всех других приложениях текст при выделении попадает в primary buffer. Это крайне неудобно. Kubuntu 20.04.
I upgraded to 2.6.0 and my primary buffer stopped working in Simplenote. Now when I select text in Simplenote, it doesn't go to the primary buffer. In all other applications, the text goes into the primary buffer when selected. This is extremely inconvenient. Kubuntu 20.04.

**Comment by codebykat** [comment]
Thanks for the report, @KOT040188. I think this is a duplicate of #2361.
