### ISSUE TITLE
Graph view for Simplenote

### ISSUE THREAD

**Issue by FedeCuci** [Automattic/simplenote-electron#2679]
### What

Add an option to view the notes in the form of a [graph](https://publish.obsidian.md/help/Plugins/Graph+view). This idea is from Obsidian, which is another note provider. 

### Why

A graph view is an awesome way to view your notes in a structured way. The tag system in Simplenote is excellent and stays true to the core of Simplenote's main principle, which is to stay simple. I believe that a graph offers the user another way to visualize his/her notes and adds very little complexity. That is because a graph view is not another way to sort notes, but rather another way to view them. In other words, it improves functionality without sacrificing ease of use. On top of that, Simplenote has the already-existing logic of [Internal links](https://simplenote.com/2020/11/03/introducing-internal-links/#:~:text=You%20can%20swipe%20left%20on,tap%20on%20the%20link%20icon.&text=As%20of%20the%20upcoming%20release,list%20and%20choose%20Copy%20Link.) which can be used as a basis to develop the graph view.

### How

Just like obsidian, "Notes with more notes referencing it appear as bigger nodes on the graph." This could be achieved with the Internal link logic already present in Simplenote.

**Comment by codebykat** [comment]
Thanks @FedeCuci! I've added this to our feature requests.

I'm closing this issue for now since we only use GitHub for tracking bugs and our immediate roadmap, but it's something we will consider in the future.
