### ISSUE TITLE
"Super condensed" view

### ISSUE THREAD

**Issue by rodalpho** [Automattic/simplenote-electron#268]
Please offer a “super condensed” view that shrinks all the spaces between each entry in the notes list on the left. Again, the white space here is a huge waste of space. Eyeballing, looks like we could fit at least 50% more notes in the list if the white space was shrunk down.

**Comment by drw158** [comment]
Currently, we don't have any plans for another note display option, but I do think the vertical whitespace in-between each note could be decreased.
