### ISSUE TITLE
Warning Repeatedly

### ISSUE THREAD

**Issue by khanrahan** [Automattic/simplenote-electron#2690]
MacbookAir9,1 (intel)
10.15.7
Simplenote Electron 2.6.0
Homebrew 3.0.1

Greetings!

Each time I load the electron app, it gives the warning to verify the email.  I have verified several times to be sure.  I do not receive this warning when using the web app on Safari 14.0.3 on the same machine.  I do not receive this warning when using the 2.7 version of the OSX app.   I installed the electron app using homebrew. 

<img width="389" alt="Screen Shot 2021-02-21 at 11 31 13 AM" src="https://user-images.githubusercontent.com/5342211/108887048-ba5ce280-75d7-11eb-997e-30b6782eedb7.png">

**Comment by belcherj** [comment]
Can you trying logging out and back in? If that doesn't work contact support at support@simplenote.com. They can sort you out from there.

**Comment by khanrahan** [comment]
That did it.  Sorry to waste your time.
