### ISSUE TITLE
Handle "unusual line terminators"

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-electron#2698]
A user in 3768648-zen got the following message from Monaco:

```
	Detected unusual line terminators

This file contains one or more unusual line terminator characters, like Line Separator (LS) or Paragraph Separator (PS).

It is recommended to remove them from the file. This can be configured via `editor.unusualLineTerminators`.
```

Looks like we can set that option to `auto` instead of the default of `prompt`: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html#unusuallineterminators

**Comment by abhideveloper9753** [comment]
Solution...
