### ISSUE TITLE
v2.7.0 can't login Windows app

### ISSUE THREAD

**Issue by nr1995** [Automattic/simplenote-electron#2699]
Recently I haven't been able to log into the Windows app (Windows 10).
This happened around the time I started using a NordVPN UK server.
I usually use US or Japanese servers.
I don't know if that's the cause, but it could be.

In every other way my internet+VPN is working fine.
Sorry I can't give you much more info than that.

**Comment by codebykat** [comment]
Hi @nr1995, can you please contact us at support@simplenote.com so we can investigate this? We can't debug account-related issues on the public GitHub. Cheers :)

**Comment by nr1995** [comment]
> Hi @nr1995, can you please contact us at [support@simplenote.com](mailto:support@simplenote.com) so we can investigate this? We can't debug account-related issues on the public GitHub. Cheers :)

No problem.
I can confirm that it _**was**_ in fact because I was connected to the UK server, btw.
