### ISSUE TITLE
Markdown Highlight options

### ISSUE THREAD

**Issue by rahuldahal-zz** [Automattic/simplenote-electron#2700]
### What
Markdown syntax highlight options, or themes. Like,
- Github Flavoured Markdown
- Maruku
- StackOverflow Flavoured Markdown
- [more list here](https://github.com/commonmark/commonmark-spec/wiki/Markdown-Flavors)

### Why
While previewing the note written using markdown, it's difficult to "see" the styles being applied. 
Specially, the inline styles like *italics* **bold** `inline code` are indistinguisable from the normal text.

### Example
Below is the screenshot of a markdown syntax that uses `inline-code`.
![markdown with inline-code](https://user-images.githubusercontent.com/44515005/109383293-c1ecf600-790d-11eb-963c-995d51c2928c.png)

And here is the rendered highlight of that snippit
![Poor highlight on inline-code](https://user-images.githubusercontent.com/44515005/109383345-16907100-790e-11eb-9759-e20df5cd7f90.png)

Here, the `inline-code` is indistinguisable from the normal text.

**Comment by wisehackermonkey** [comment]
good idea!

**Comment by codebykat** [comment]
Thanks! More themes are already on our radar. Additionally I think this specific issue was reported in #1891 and will hopefully get some love soon.
