### ISSUE TITLE
Review Your Account dialog close button cut off in macOS Safari

### ISSUE THREAD

**Issue by dcalhoun** [Automattic/simplenote-electron#2704]
### Expected
The close button displays an entire "X" character.

### Observed
The close button displays only the top half of an "X" character.

### Reproduced

1. Visit Simplenote in macOS Safari.
2. Sign up for a new account.
3. Arrive on Simplenote landing screen with "Review Your Account" modal displayed.

| Safari | Chrome |
| --- | --- |
| ![simplenote-safari-close-button](https://user-images.githubusercontent.com/438664/109564001-1f1baf80-7aa6-11eb-8b72-63284b00d40d.png) | ![simplenote-chrome-close-button](https://user-images.githubusercontent.com/438664/109564021-2347cd00-7aa6-11eb-9329-fa4b3f6f7cec.png) |

### Where did you see the bug
- System Make: Apple
- System Model: MacBook Pro
- OS: macOS
- OS version: 11.2.2
- Browser (if applicable): Safari
- Browser version (if applicable): 14.0.3
- Simplenote app version: 2.7.0-beta1

**Comment by codebykat** [comment]
~~LOL. Thanks @dcalhoun 🤦‍♀️  Wanna fix it? 😉~~ Edited to clarify, this snark was at my own expense and not yours, let me try this again:

Whoops, I don't know if we even tested that feature on Safari. 🤦‍♀️ Good find! Let's add it to the good first issue tag, that might be an easy win if you feel like tackling it. Thanks @dcalhoun ❤️

**Comment by dcalhoun** [comment]
@codebykat would be happy to.
