### ISSUE TITLE
Back-up notes to local textfiles

### ISSUE THREAD

**Issue by rodalpho** [Automattic/simplenote-electron#271]
Resophnotes allows all notes to be backed-up to text files on a locally attached disk. I back mine up to Dropbox. Would like this same option in the official Simplenotes app.

**Comment by roundhill** [comment]
Do you know that you can download a .zip archive from the web app at https://app.simplenote.com?

**Comment by marianoju** [comment]
I support the feature request. A plain-text backup would have enabled me to recover [lost data after client failed to synchroniz](https://github.com/Automattic/simplenote-electron/issues/332) (#332). 

Downloading a .zip archive from the web app at https://app.simplenote.com is *not* an option for me, for two reasons: 
1. since client failed to synchronize data was not accessible trough the web app; 
2. since web app fails to execute request (possibly due to large amount of notes?), see [#346](https://github.com/Automattic/simplenote-electron/issues/346).

An automatic periodic plain-text (zipped) backup copy of my notes would be very much appreciated.

**Comment by dmsnell** [comment]
we wish you didn't have that problem with the lost data, @marianoju. can you give some rough estimate of how many notes you have or how big your notes are? _re: "possibly due to large amount of notes?"_

**Comment by marianoju** [comment]
@dmsnell I would estimate I had about 900 notes at the time, totaling 1.8 MB (says Nautilus, the GNOME file manager; listing of the directory with `ls -lh` states 4.4M), of which 

- 531 items smaller than 1 kB; 
- 167 items equal or larger than 1 kB and smaller than 2 kB; 
- 108 items equal or larger than 2 kB and smaller than 4 kB; 
- 54 items equal or larger than 4 kB and smaller than 8 kB; 
- 22 items equal or larger than 8 kB and smaller than 16 kB; 
- 7 items equal or larger than 16 kB and smaller than 32 kB; 
- 4 items equal or larger than 32 kB and smaller than 64 kB; 
- 2 items equal or larger than 64 kB and smaller than 128 kB.

**Comment by dmsnell** [comment]
thanks @marianoju! is that a dump from the zipped download off of the web?

these numbers will help us to understand if there's a link between note size and count and the sync issues

**Comment by marianoju** [comment]
You're welcome @dmsnell! Yes, that is “a dump from the zipped download off of the web”

**Comment by dmsnell** [comment]
Hopefully this has been resolved by the introduction of export functionality in #448. Please feel free to comment on that process; we hope it meets your needs!

**Comment by marianoju** [comment]
Wow, that is great! I had not realised the function had been introduced. It pretty much fits my needs. The only flaw I can think of is the missing timestamp of last modification, which is not preserved in the exported file(s). Nonetheless very useful as it is. I especially like that the text files' names correspond to the first line of text.

**Comment by dmsnell** [comment]
thanks @marianoju for the feedback. we're glad it meets your needs

> missing timestamp of last modification

good point! this doesn't seem like something we couldn't add in. my guess is that it will likely show up in the JSON export eventually if not directly in the one-file-per-note part of the export.

**Comment by rodalpho** [comment]
This does not satisfy my use case, as the backup is not automatic and it's in the form of a compressed archive rather than individual text files that can be read in any other editor.

**Comment by dmsnell** [comment]
@rodalpho I don't believe that we have any plans for building an auto-export or exporting the notes outside of a zip archive. the export is mainly there as a tool to get notes out of Simplenote and not as a backup.

I'm not sure what it is that you are wanting to do but many editors do actually allow one to open a compressed zip archive transparently: [Atom](https://github.com/atom/archive-view), [Sublime](https://packagecontrol.io/packages/Zip%20Browser), [vim (example for gzip but similar)](http://stackoverflow.com/questions/5396363/how-to-open-gzip-text-files-in-gvim-without-unzipping) to name a few.

This isn't a suggestion at a workflow, just a suggestion that this workflow isn't Simperium's goal while it may still be possible for you to accomplish your goals with existing tools.

**Comment by marianoju** [comment]
The [the missing timestamp of last modification](https://github.com/Automattic/simplenote-electron/issues/271#issuecomment-285973406) have been added (see #826), and I am grateful for that! Regrettably text files' names as of now do *not* correspond to the first line of text *anymore* but I can live with that.
