### ISSUE TITLE
Update not updating

### ISSUE THREAD

**Issue by KshDi13** [Automattic/simplenote-electron#2717]
Upon opening Simplenote on Windows 10 x64 i'm prompted that '_A new version of Simplenote is available!_' and that i have 2.5.0 and that 2.7.0 is now available.
I click on on _Update & Restart_ and it appears to download and install 2.7.0 and indeed when i check _Help > About Simplenote_ it says 2.7.0 however when i exit the app and go back in it appears i'm reverted back to 2.5.0. If i manually update _Help >Check for Updates_ again the app updates fine for that session and if i check _Help > About Simplenote_ it does correctly say 2.7.0 but if i exit and go back in it says i'm 2.5.0 and do i want to update. 
 
### Expected
After clicking Update & Restart either after opening the app or manually via _Help > Check for Updates_ then the app should update.

### Observed
Despite the app downloading and installing something and even showing the correct updated version in _Help > About Simplenote_ upon reopening the app a message is displayed telling me the app is version 2.5.0 and that an update is available and indeed checking _Help > About Simplenote_ it does show that the app has reverted back to version 2.5.0.

### Reproduced
Everytime. Simply open the app.

### Where did you see the bug
- System Make: MSI
- System Model: GS40 Phantom
- OS: Windows 10 x64
- OS version: 1909 (OS Build 18363.1379)
- Simplenote app version: 2.5.0/2.7.0

**Comment by pachlava** [comment]
@KshDi13 thank you for the report! Could you please check if #2251 looks similar to your issue (especially, the latest comments)?

**Comment by codebykat** [comment]
Closing as a duplicate
