### ISSUE TITLE
Copy button doesn't work in Safari

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#272]
Button works in Chrome, but not Safari. Text is not copied to clipboard.

9.0.2

![screen shot 2016-03-30 at 3 24 42 pm](https://cloud.githubusercontent.com/assets/618551/14156353/99df1fc6-f68b-11e5-9821-aaf104ed5742.png)

**Comment by dmsnell** [comment]
Closing @drw158 because our target is Electron and not Safari. It's handy to be able to test it in Safari, but the build is all Chrome. 

You may try again because Safari had broken copy/paste support which was supposedly fixed in the v10 release a few days ago.
