### ISSUE TITLE
Light Mode for Editor Panel

### ISSUE THREAD

**Issue by cxmeel** [Automattic/simplenote-electron#2727]
### What

I'd like to see an option added that allows the editor panel to have a separate theme setting to the app itself.

### Why

I personally find it easier to see/read the contents of the editor/preview in light mode while editing, but don't necessarily want the entire app to be in light mode.

### How

![Preview](https://user-images.githubusercontent.com/21029087/110483529-b2299a80-80e1-11eb-9e90-33ded9de66c5.png)
![Settings](https://user-images.githubusercontent.com/21029087/110483534-b35ac780-80e1-11eb-82c3-105d61c58269.png)

**Comment by codebykat** [comment]
Hi @ClockworkSquirrel, this is an interesting idea, and one that we'll keep in mind when considering themes for the app. I'm going to close this for now as we have that tracked elsewhere, but thanks for the idea!
