### ISSUE TITLE
`support@simplenote.com` link is not working as `mailto:` link

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2749]
### Expected
Clicking the `support@simplenote.com` link should result in 'email sending activity' (whatever user has set up):

<img width="251" alt="Screenshot 2021-03-11 at 14 50 13" src="https://user-images.githubusercontent.com/73365754/110809043-3c623200-828d-11eb-9a57-f8bc401cccbf.png">

### Observed
Nothing happens on click

### Reproduced
1. Start new user signup
2. Submit the email ~> you will see the dialog with mentioned link
3. Click the link

### Where did you see the bug
- OS: Windows 10 | Ubuntu 20.04 | macOS 11.2
- Simplenote app version: 2.8.0-beta2 desktop

**Comment by belcherj** [comment]
https://github.com/Automattic/simplenote-electron/blob/da1bee231da1f91987f8b624d9f4bca88f4226ba/lib/email-verification/index.tsx#L101

https://github.com/Automattic/simplenote-electron/blob/6871f8a95dacb0fc79689ae978892dd2111f134b/lib/auth/index.tsx#L98

**Comment by codebykat** [comment]
Weirdly, we wrapped this link in a `viewExternalUrl` call (which I would expect to work) but the link in the verification is just a `mailto:` (which I would expect to fail).

I will look at this today...
