### ISSUE TITLE
Modals become obscured in short windows or with zoomed UI

### ISSUE THREAD

**Issue by dcalhoun** [Automattic/simplenote-electron#2750]
If a user has a short window height or is leveraging a zoomed UI (i.e. <kbd>Cmd</kbd>+<kbd>+</kbd> to increase size of text), several modals become obscured and do not provide scrolling to see the entirety of their content.

Obviously the impact of this issue is dependent upon _how much_ zooming is applied. So, it may not occur for the majority of users, but could negatively impact users who have smaller screens or require larger type for reading.

### Expected
If a modal overflows the height of the window, one can scroll to reveal the rest of its content.

### Observed
If a modal overflows the height of the window, there is not a way to view the entirety of the modal content.

### Reproduced
1. Shorten the browser window height to less than ~600px.
2. Increase the zoom of the browser window (e.g. <kbd>Cmd</kbd>+<kbd>+</kbd> a couple of times).
3. Click the Menu button in the top-right.
4. Click the About link in the bottom of the sidebar.

This issue occurs on each modal I encountered. There may be more occurrences than the following.

<details>
<summary>About Modal</summary>
<img width="1818" alt="modal-about" src="https://user-images.githubusercontent.com/438664/110812757-80cddd80-824d-11eb-897b-5a61318910dc.png">
</details>

<details>
<summary>Review Your Account Modal</summary>
<img width="1818" alt="modal-review-account" src="https://user-images.githubusercontent.com/438664/110812801-875c5500-824d-11eb-9a37-d0348df4af64.png">
</details>

<details>
<summary>Keyboard Shortcuts Modal</summary>
<img width="1818" alt="modal-keyboard-shortcuts" src="https://user-images.githubusercontent.com/438664/110812851-9216ea00-824d-11eb-83b7-9af32c73afe3.png">
</details>

### Where did you see the bug
- System Make: Apple
- System Model: MacBook Pro
- OS: macOS
- OS version: 11.2.2
- Browser (if applicable): Safari
- Browser version (if applicable): 14.0.3
- Simplenote app version: 2.7.0-beta1

**Comment by codebykat** [comment]
See also #2716
