### ISSUE TITLE
Focus Mode/Toggle Sidebar naming is inconsistent

### ISSUE THREAD

**Issue by dplanella** [Automattic/simplenote-electron#2764]
### Expected

The `View` > `Focus Mode` action on the menu and the `Toggle Sidebar` icon on the toolbar do the same thing: they should be named identically, unless they are expected to do different things.

### Observed

Both `View` > `Focus Mode` and `Toggle Sidebar` toggle the sidebar's visibility, but have different names, which sets an expectation that they do different things, confusing users.

### Reproduced

1. Start the app
2. Go to `View` > `Focus Mode` => sidebar's visibility is toggled
3. Click on the `Toggle Sidebar` toolbar icon => sidebar's visibility is toggled

### Where did you see the bug

- System Make: N/A
- System Model: N/A
- OS: Ubuntu
- OS version: 20.04 
- Browser (if applicable): N/A
- Browser version (if applicable): N/A
- Simplenote app version: 2.7.1

**Comment by sandymcfadden** [comment]
Thanks for catching this!
@SylvesterWilmott which option do you think that we should go with to stay consistent?

**Comment by SylvesterWilmott** [comment]
For context, we have both "Toggle Sidebar" and "Focus Mode" on macOS since both the notes list and tags list can be visible at the same time. On macOS "Toggle Sidebar" refers to showing/hiding the **tags** list, so in this case I think the label should be "Focus Mode" in both spots on Electron.

**Comment by codebykat** [comment]
We actually intended to change this in the other direction, as per #2599.

**Comment by codebykat** [comment]
> Merge “Toggle Focus Mode” and “Toggle Notes List” into one shortcut.

Actually I'm now unsure, and I've confused myself. @SylvesterWilmott do we want this one to be "Toggle Focus Mode" (only) or "Toggle Notes List" (only)?

**Comment by SylvesterWilmott** [comment]
>Actually I'm now unsure, and I've confused myself.

No, you're right. We do still plan to remove the current "focus mode" shortcut since it does the same thing as the "toggle notes list" shortcut. However, simply regarding the label or what we call it in the app, I think it should be "Toggle Focus Mode" so we can remain consistent in what we call things across the desktop clients.
