### ISSUE TITLE
Tags are not submitted with space in Web App.

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2765]
### Expected
Space submits a tag

### Observed
While #2607 was tested with a Desktop app (2.7.0-beta1), it looks like the web-app that is currently live, the same version, does not submit a tag with space.

### Reproduced
1. Use the web app in Safari, FF or Chrome
2. Start adding a new tag to a note
3. Hit space → tag is not submitted

### Where did you see the bug
- System Make: MBP 16"
- OS: Windows 10 Home | macOS Big Sur 11.2.3
- Browser: Chrome 88.0.4324.192 (Official Build) (x86_64). Also, FF (macOS) and Safari (macOS)
- Simplenote app version: 2.7.0-beta1

**Comment by sandymcfadden** [comment]
There was an issue where this change was overridden but then added back in PR #2661. It looks like we haven't deployed to production since this was added back though. Next time we deploy this will be working again. 
@codebykat do we know when our next deploy will be?

**Comment by codebykat** [comment]
Let's remember to deploy web on Monday. I've been trying to make sure we do it every sprint but it's on a "someone remembers to deploy it" cadence.

**Comment by pachlava** [comment]
Closing since 2.9.0-beat1 was deployed
