### ISSUE TITLE
Review your account pops up at every launch

### ISSUE THREAD

**Issue by taprobane99** [Automattic/simplenote-electron#2766]
Hi,

For several versions now the "Review your account" window pops up when I launch the application on Linux (AUR version). Even if I press confirm, get the email, and complete a successful verification, I still get the message. It can be ignored by pressing the x button, but is a bit annoying.

Can this be fixed.

thanks

**Comment by codebykat** [comment]
Hi @taprobane99, there's a fix for this in the upcoming new version (2.7.1 / 2.8.0). In the meantime you should be able to clear the message by logging out of the app and logging in again. Thanks for the report!

**Comment by jefferyto** [comment]
I am using 2.8.0 (and 2.7.1 before) and this is not fixed. Logging out and back in is not an obvious workaround, and users should not have to work around an issue with your Linux client.

**Comment by atocyo** [comment]
Same on windows. 2.9v.
