### ISSUE TITLE
Move Sorting Options to Settings

### ISSUE THREAD

**Issue by SylvesterWilmott** [Automattic/simplenote-electron#2769]
Based on low usage, let's remove the sort bar from both the search results and notes list.

Sorting should now appear in settings in full:

Name: A-Z
Name: Z-A
Created: Newest
Created: Oldest
Modified: Newest
Modified: Oldest

**Comment by michaeldurland** [comment]
So what was 2 clicks to change the sort order now becomes 5 clicks. :(
