### ISSUE TITLE
After registration, the webview window does not close

### ISSUE THREAD

**Issue by soren121** [Automattic/simplenote-electron#277]
After you register for a new account within Simplenote-electron, the registration WebView window seems to load the Simplenote web interface inside that window. 

I would expect the window to close and return focus to the main window.

**Comment by roundhill** [comment]
I think we should probably just add support for registering an account directly in the app. The mobile apps currently support that.

**Comment by dmsnell** [comment]
Closing here since we started allowing registration from within the app itself.

Please reopen if you feel the problem remains after `v1.1.0` is released. Thanks as always for your help!
