### ISSUE TITLE
Login screen on startup

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2779]
Please add below feature:
- Support multi accounts feature and show login screen on startup. (like Google Chrome)
![Google Chrome](https://user-images.githubusercontent.com/23485114/109156916-ab686280-7786-11eb-8c0c-77c0a6d634b3.png)

**Comment by codebykat** [comment]
Thanks @xmha97, we will consider this for the future. As a workaround, you can effectively achieve this by using different browser profiles, as in your screenshot. Different Chrome users will have different Simplenote sessions.
