### ISSUE TITLE
Add password protection for the entire app

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#278]
We got a request for password protection, similar to iOS. I think it could work very similarly (maybe just like 1password).

This would require a 4 character/digit password to gain access to the app each time you open the app. Helpful if you have sensitive info.

Things to consider:
- If the user reopens the app right after entering the password, do we require them to enter the password again? At what point to we reset the password entry?
- What if they forget the password?
- How many characters?

**Comment by dmsnell** [comment]
@drw158 could you be a bit clearer and more specific? issues like these are very difficult to make sense of.

**Comment by drw158** [comment]
No problem, updated the issue.

**Comment by roundhill** [comment]
I'm not sure if we should add this. Do other desktop apps have such a feature? Seems like most people these days add passwords to their desktops/laptops.

**Comment by drw158** [comment]
Apple just added password support to their both of their note apps, and it got a really positive strong reaction. I think that is probably a lot more useful than locking the entire app.

**Comment by drw158** [comment]
Also, not having password protection means you can't have any sort of sensitive data in simplenote - imagine working in a coffee shop, and opening the app and the first note is selected automatically. Or, you start writing and realize that you can't m hide that sensitive note in the note list, unless you add some dummy content to the top.

**Comment by KokkieH** [comment]
Just had another request for this in 2674052-t, specifically for the Windows and Linux apps. This has also been requested on the (old) feature request page of the P2 for the Mac app: 2445663-t.

**Comment by drw158** [comment]
Thinking more about this, I think it makes much more sense to lock specific notes, not the entire app. Rarely do you need to lock more than 1 or 2 notes. It would be worth it to go through the Notes.app locking flow and see what we can learn.

Unfortunately, this might be something we have to do across all apps. I don't know if we should do it on just one app and not the others.

**Comment by manu-chroma** [comment]
Me and @ggyanez have also requested this feature [in this duplicate issue](https://github.com/Automattic/simplenote-electron/issues/366). Having a lock on the app would be really useful and also makes sense. 

It can be passively added in the settings  like on android app and user can manually activate if he/she wants to.

**Comment by gracie** [comment]
Being able to lock the app was also requested in #2983176-t

**Comment by kriskarkoski** [comment]
Also requested in #726598-zen

**Comment by suyogyashukla** [comment]
Also requested in #767892-zen

**Comment by huangdawei** [comment]
Actually, the only reason I still using Simplenote not Notes.app on iOS is the entire app locks automatically. Same reason that nvALT is my fav on macOS to access Simplenote, I'm longing for the password protection for the entire app added to our own apps on macOS.

**Comment by BandonRandon** [comment]
While not a "note" app, Telegram allows a _local passcode_ to be set per device allowing local locking of the app. If one forgets the passcode they will need to log out and log back in.

![screenshot_07-08-2018-16 07 59](https://user-images.githubusercontent.com/150348/43807256-7b3df7dc-9a5c-11e8-91e8-4ac96eb46c79.png)
![screenshot_07-08-2018-16 09 19](https://user-images.githubusercontent.com/150348/43807258-7d4c1d88-9a5c-11e8-91d1-981d50dc818c.png)
![screenshot_07-08-2018-16 09 44](https://user-images.githubusercontent.com/150348/43807263-7fa5ff36-9a5c-11e8-91f1-99a9d80fd692.png)

**Comment by BandonRandon** [comment]
Requested on Twitter https://twitter.com/stevengayrogers/status/1026925805098754048

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by lizkarkoski** [comment]
There's another request for passcodes from Twitter. Specifically for the Windows desktop app.
https://twitter.com/CoodDoBettr/status/1230444134814638081
