### ISSUE TITLE
[Win] Simplenote shortcut is broken after `only for me` install

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2796]
### Expected
All shortcuts that are created during app installation should be working

### Observed
The shortcut that is created during `only for me` install in Windows creates a desktop shortcut with no properties:

<img width="916" alt="Screenshot 2021-03-22 at 15 27 25" src="https://user-images.githubusercontent.com/73365754/111997723-fd9d6900-8b23-11eb-919b-e4b8be163aa0.png">

`Install for everyone` produces a correct icon.

### Reproduced
1. Have no Simplenote installed
2. Install [2.9.0-beta1](https://github.com/Automattic/simplenote-electron/releases/tag/v2.9.0-beta1)
3. Select `only for me` installation

### Where did you see the bug
- System Make: Parallels Desktop on MBP 16"
- OS: Windows
- OS version: 10 Home 20H2 build 19042.508
- Simplenote app version: 2.9.0-beta1 desktop
- Simplenote app version:

**Comment by sandymcfadden** [comment]
This looks to be an issue with using Parallels and installing from a shared Mac folder. 
I don't think there is anything we can do to fix this besides copying the installer to the Windows VM directly and then installing.
[More context here](https://github.com/electron-userland/electron-builder/issues/865#issuecomment-258105498).

**Comment by pachlava** [comment]
@sandymcfadden thank you! Looks like this is the case. I think it's ok then, knowing that it's Parallels-specific issue
