### ISSUE TITLE
Only the imported files list should be scrollable, not the whole dialog

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2801]
### What
When enough files are imported, the import dialog will have a scrollbar. However, it might be better to have only the files list scrollable, but the bottom of the dialog always visible (also, take into account the vertical expansion of dialog after import is done):

https://user-images.githubusercontent.com/73365754/112161507-e62db100-8bf3-11eb-97d4-2115c334801f.mov

### Why
UI elements will always be available to the user. Better accessibility

**Comment by pachlava** [comment]
I guess it's the same as #2777? If so, please close 🙇

**Comment by sandymcfadden** [comment]
Thanks @pachlava! You're right, this is one of the places #2777 will fix as well when I work on it.
