### ISSUE TITLE
Teach importer to handle 'alien' json files

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2806]
### What
It would be nice to have the importer handle the cases of valid, but 'alien' `.json` files

### Why
When importing a  syntactically correct `.json` [file](https://support.oneskyapp.com/hc/en-us/articles/208047697-JSON-sample-files), but not the one using the Simplenote format, the app will freeze. It's more critical when using the desktop version, where there's no reload button.

**Comment by codebykat** [comment]
This is already tracked as #2517 😄
