### ISSUE TITLE
[Mobile Browser] Don't show keyboard when note is opened

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2810]
This is about using the Web app on iPhone (in Chrome, in this case).

### What
There are two things causing some discomfort:

1. Once the note is opened, the keyboard is always shown (this does not happen in iOS or Android apps)
2. When search matches are highlighted, the match navigator is hidden by the keyboard, and the keyboard is always opened after jump to the next match:

https://user-images.githubusercontent.com/73365754/112465686-ad194c00-8d6d-11eb-874a-0a76c199aa3a.MP4

### Why
Consistency. Also, the user might firstly want to see the note, or explore the search matches, before editing it. Keyboard covers almost half of the editor.

**Comment by codebykat** [comment]
Same comment as https://github.com/Automattic/simplenote-electron/issues/2811#issuecomment-807107550, mobile browser is considered unsupported.

I'm closing this one since it's a Monaco behavior.
