### ISSUE TITLE
[Mobile browser] End of the note is not visible during edit

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2811]
### Expected
When a part of the note is edited, this part should be visible.

### Observed
If the note is long enough, the edited part will be covered by the keyboard. There might be cases when it will be scrolled to view, but it's not always consistent:

https://user-images.githubusercontent.com/73365754/112467017-2feed680-8d6f-11eb-9b3f-25bb314a04d6.MP4

### Reproduced
1. Have a note that takes almost all screen space on your device
2. Tap a portion of text that is at the bottom part of a note ~> keyboard will be shown
3. Start typing ~> in some cases you will not be able to see what you are typing.

### Where did you see the bug
- System: iPhone XR
- OS version: iOS 14.4.1
- Browser (if applicable): Safari (I guess it's 14.4.1) 
- Simplenote app version: 2.9.0-beta1

**Comment by codebykat** [comment]
@pachlava Monaco doesn't support mobile editing, so we basically don't either. Users on mobile devices are understood to have a fairly buggy experience unless they install one of the apps.

https://github.com/microsoft/monaco-editor/issues/246

This particular issue may not be Monaco specific, so I'll leave it open for now, but it's not a high priority to address.
