### ISSUE TITLE
Linux AppImage has no icon in the dock

### ISSUE THREAD

**Issue by retrosmarc** [Automattic/simplenote-electron#2824]
Hello,

I just started using Simplenote for Linux. Thanks for creating it.
When the app is open, I just noticed there is no icon in the Ubuntu dock. Is it normal?

### Expected
I thought I would see the Simplenote logo in the dock, with other open apps (like Firefox in the example) and shortcuts.

### Observed
The placeholder for Simplenote instance is empty.
![Capture d’écran du 2021-04-06 12-33-32](https://user-images.githubusercontent.com/81690481/113698356-ad520980-96d4-11eb-8532-b5915accf1ca.png)

### Where did you see the bug
- OS: Ubuntu 20.10
- Simplenote app version: Simplenote-linux-2.9.0-x86_64.AppImage

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
