### ISSUE TITLE
Server connection fault in PC app and site

### ISSUE THREAD

**Issue by gabri25ele** [Automattic/simplenote-electron#2825]
on iphone, Simplenote works well.
on PC (app desktop and url)

![sshot-1](https://user-images.githubusercontent.com/33927879/113730460-34fd3f80-96f8-11eb-8c62-9f3a5e586799.png)

the only thing that syncs me is the **tags**

I tried also to create a test account and it works on PC, so where is the problem with my real account? it works on iphone and not on PC (does not synchronize).

what can I do?

**Comment by pachlava** [comment]
@gabri25ele I'm sorry to hear this is happening. I would suggest contacting the Simplenote support team by writing an email to support@simplenote.com, which is a faster way to troubleshoot the issue you describe. It would also be very helpful if you could provide additional information in the email:
- The email address used to register the account with sync issue (in case if it will be different from the mailbox you will use to contact support)
- Simplenote version and OS version
- Does the issue persist if you change the network (e.g. connecting your PC to LTE)
- Does your PC/router use VPN and/or firewall

**Comment by codebykat** [comment]
Yes, closing as we cannot debug account-related issues on the public GitHub :)
