### ISSUE TITLE
Review pop everytime I open App

### ISSUE THREAD

**Issue by vijayhardaha** [Automattic/simplenote-electron#2830]
![image](https://user-images.githubusercontent.com/25227317/114056434-49d00380-98af-11eb-8a9e-8de52da38923.png)

Simplenote version 2.8.0
OS- Windows 10

Popup is coming every time I open the APP. I confirmed my email so many times but the popup still coming each time opening App.

**Comment by codebykat** [comment]
Hi @vijayhardaha, thanks for the report. Can you please log out of the app and log back in? That should sync up your account data. Otherwise we believe this bug to be fixed in the latest version.
