### ISSUE TITLE
Simplenote is not syncing data nor allowing login

### ISSUE THREAD

**Issue by abdul-foomotion** [Automattic/simplenote-electron#2845]
My Simplenote app on ubuntu was not syncing notes anymore. I had checked the logs and there were some connection issues with the remote server. I decided to  uninstall and reinstall the app. But now it's not even allowing me to login, 

I'm attaching the screenshots of the error.
![Screenshot from 2021-04-15 11-39-40](https://user-images.githubusercontent.com/73174756/114825513-c39c4b80-9ddf-11eb-8f6a-2b298d8c04a8.png)
![Screenshot from 2021-04-15 11-39-52](https://user-images.githubusercontent.com/73174756/114825526-c5fea580-9ddf-11eb-87b4-69bbf9f01c74.png)

- OS: Ubuntu
- OS version: 20.4
- Simplenote app version: 2.9.0

**Comment by codebykat** [comment]
Hi @abdul-foomotion, this sounds like an issue specific to your account or network. I'm wondering if you can try it from a different IP address and see if that works?

We can't really debug account-related issues on the public GitHub, so if that doesn't help, can you please drop us a line at support@simplenote.com? Thanks :)

**Comment by abdul-foomotion** [comment]
Thanks @codebykat for the response. I was facing this issue for more than two days I guess. But it's suddenly resolved. Don't know the reason behind this issue.

**Comment by johnmorenoGL** [comment]
I have the same issue. I can confirm that I can login and sync properly when using my cellphone's hotspot, but not when using my router Wi-Fi. I tried, with the same results, on
* Mac OS Catalina ---installed through HomeBrew
* Debian Testing ---installed from the *.deb package provided at this repository.

Also, in regards to accessing the account through https://app.simplenote.com
* Login when using the hotspot works properly and I can see all my notes.
* Login when using the Wi-Fi works, but there are no notes displayed. Only a button to add my first note.
