### ISSUE TITLE
While typing, characters start to disappear as if hitting control-Z

### ISSUE THREAD

**Issue by weisisheng** [Automattic/simplenote-electron#2855]
### Expected

Type a phrase and it remains rendered and visible

### Observed

While typing, with some delay, characters start to disappear, going back 3-6 inputs (keystroke or pastes into the app).  Been using the app for over 12 months and never saw this behavior before.

### Reproduced

1.
2.
3.

### Where did you see the bug

- System Make: Ubuntu
- System Model:
- OS: 20.04
- OS version: 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: Version 2.90

**Comment by codebykat** [comment]
Hi @weisisheng, thanks for this report. This is a new one to us and I can't reproduce it so far... can you possibly share a screen recording to illustrate what's going on?

Do you have the same thing happen if you log into the web app on https://app.simplenote.com? Does it happen on all notes, or only on long notes / after you've been writing for awhile / some other situation? Does it progressively get worse or start happening all at once?

Thanks for any additional information you can think of to help us track this down!

**Comment by weisisheng** [comment]
Hello, I will try the web app in the next 2-3 days and come back.  Thank you for your time.

**Comment by weisisheng** [comment]
Hmm, after a few days, I haven't seen this phenomena.  Will close for now.
