### ISSUE TITLE
Multiple dialogs have decreased in height

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2859]
### Observed
<img width="1480" alt="Screenshot 2021-04-20 at 14 22 32" src="https://user-images.githubusercontent.com/73365754/115388039-18770200-a1e4-11eb-8243-2009a70098c6.png">
<img width="1480" alt="Screenshot 2021-04-20 at 14 23 02" src="https://user-images.githubusercontent.com/73365754/115387998-09904f80-a1e4-11eb-80a7-643ec2217f8e.png">
<img width="1480" alt="Screenshot 2021-04-20 at 14 22 46" src="https://user-images.githubusercontent.com/73365754/115388008-0c8b4000-a1e4-11eb-9052-b8039593f61a.png">

### Where did you see the bug
- System Make: Parallels Desktop on MBP 16”
- OS: Windows 10 Home 20H2
- Simplenote app version: 2.10.0-beta1

**Comment by pachlava** [comment]
In one place more:

<img width="1480" alt="Screenshot 2021-04-20 at 16 32 49" src="https://user-images.githubusercontent.com/73365754/115404523-13bb4980-a1f6-11eb-8549-e9571493e93c.png">

**Comment by sandymcfadden** [comment]
Fixed in #2863
