### ISSUE TITLE
Installation on Windows 7 fails

### ISSUE THREAD

**Issue by abhishekpc** [Automattic/simplenote-electron#286]
Hello,

I tried to install Simplenote on Windows 7 Enterprise edition but the installation failed. I tried twice.

Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/3172915/14274962/aefded3c-fb14-11e5-86df-af5434229666.png)

**Comment by roundhill** [comment]
What if you right-click the installer and `run as administrator`?

**Comment by abhishekpc** [comment]
@roundhill Indeed it worked with Admin privileges. Maybe this could be either fixed or mentioned in the download page? 

Thanks :)
