### ISSUE TITLE
Searchbar now contains the `X` button even when empty

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2860]
### Expected
Search bar should contain the `X` button only if there's an entered text

### Observed
The search bar has the `X` button in all cases:
<img width="379" alt="Screenshot 2021-04-20 at 16 18 37" src="https://user-images.githubusercontent.com/73365754/115404920-6c8ae200-a1f6-11eb-817f-83c4e4c7cde5.png">

### Reproduced
1. Remove the text from searchbar, if it had any ~> the `X` button is still shown

### Where did you see the bug
- System Make: Parallels Desktop on MBP 16”
- OS: Windows 10 Home 20H2
- Simplenote app version: 2.10.0-beta1

**Comment by sandymcfadden** [comment]
Fixed in #2862
