### ISSUE TITLE
`Account` dialog scroll position is reset when `Share Analytics` is toggled

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2861]
### Expected
Changes in switches states should not affect the scroll position of the dialog.

### Observed
When `Share Analytics` switch is clicked, the scroll position is set to 0. Also, I've noticed that switch animation is instant for `Share Analytics`, but slow for the other switches:

https://user-images.githubusercontent.com/73365754/115406414-d0fa7100-a1f7-11eb-9ba3-188873f4f303.mov

### Reproduced
1. Open `Settings` ~> `Account`
2. Scroll down
3. Click `Share Analytics` switch

### Where did you see the bug
- System Make: Parallels Desktop on MBP 16”
- OS: Windows 10 Home 20H2
- Simplenote app version: 2.10.0-beta1

**Comment by sandymcfadden** [comment]
Fixed in #2863

**Comment by pachlava** [comment]
@sandymcfadden #2863 made the issue harder to notice for `Settings` dialog, but using the `Share Analytics` switch still results in scroll position reset to zero for other parts of UI (note list, note editor). In the video it shows the case for note editor:


https://user-images.githubusercontent.com/73365754/119113516-d7b21900-ba2d-11eb-94f9-a490a4b5c010.mp4


Please let me know if I should reopen the issue.

**Comment by sandymcfadden** [comment]
Ah, yes I didn't realize it was affecting the note in the background as well. I've reopened the issue now.

**Comment by pachlava** [comment]
> Ah, yes I didn't realize it was affecting the note in the background as well

To be honest, I did not realize this too at the time when I created the issue 😄. Just noticed recently. Thanks for reopening!
