### ISSUE TITLE
Note preview contains extra in-line space / line breaks compared to 2.9.0-beta1

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2866]
### Expected
When it comes to line breaks, preview should look close to what's seen in the editor.

### Observed
2.9.0-beta1 on the left, 2.10.0-beta1 on the right:

https://user-images.githubusercontent.com/73365754/115565883-724df980-a2c2-11eb-818f-9ca66160db34.mov

### Reproduced
1. Have a note with this content:

```
Bulleted List:
- one
- to
- three

Checkoxes:
- [ ] box1
- [x] box2

The text.

Linebreak is above.
New line.
```

2. Open preview ~> the in-line spaces are much bigger than in 2.9.0-beta1

### Where did you see the bug
Video shot in Chrome on Mac, but same in:
- System Make: Parallels Desktop on MBP 16”
- OS: Windows 10 Home 20H2
- Simplenote app version: 2.10.0-beta1

**Comment by sandymcfadden** [comment]
Fixed in #2867
