### ISSUE TITLE
Please provide another address to download the deb package

### ISSUE THREAD

**Issue by EdwardYuan** [Automattic/simplenote-electron#287]
It is hard to download the deb package from AWS platform in mianland China. So, could you provide another address to download it or an PPA for Ubuntu Linux. Thank.

**Comment by dmsnell** [comment]
I'm not sure what you mean @EdwardYuan - we provide download links at simplenote.com from GitHub

https://github.com/Automattic/simplenote-electron/releases

We're note specifying any AWS servers or anything in China. I'm going to close this but if you can provide more detail an the official links aren't working for your please reopen with the additional information. Thanks!
