### ISSUE TITLE
Support Fixed Width Font

### ISSUE THREAD

**Issue by lousyd** [Automattic/simplenote-electron#2875]
### What
I would like to be able to set the font of the text in my notes to fixed width.

### Why
I like to indent with whitespace but the alignment is never quite right due to it being non-fixed width font. Also, I can't tab to specific columns to line up text in columns. I would like to be able to.

**Comment by sandymcfadden** [comment]
Thanks so much for the request. This is something that has been requested previously as well and we are tracking it in our internal issue tracker. I've added your request there as well for future considerations.
