### ISSUE TITLE
Notes organized in folders or tree

### ISSUE THREAD

**Issue by Nebrit** [Automattic/simplenote-electron#288]
It would be very interesting and I would give a great leap to get more users to organize notes in a folder structure or tree. We could have notes father and son.

Could add it as a new feature? What do you think?

**Comment by drw158** [comment]
Hey @Nebrit, thanks for the suggestion. We have thought about this, but we explicitly chose to keep Simplenote's organizing functionality simple with tags only.

**Comment by fernandocalazans** [comment]
I agree with Nebrit
