### ISSUE TITLE
[macOS] Window top corners look both rounded and sharp under dark theme

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2886]
### Expected
Window corners should either be rounded or square. Also, all corners (top/bottom) should have the same shape. 

### Observed
Desktop app top corners under dark theme are shown as primarily rounded, but also with a sharp outline that gives a feeling of a bounding box:

<img width="827" alt="Screenshot 2021-05-04 at 12 11 27" src="https://user-images.githubusercontent.com/73365754/116983198-79b5cf80-acd2-11eb-8d5a-0c8ec1c0b525.png">

### Reproduced
1. Activate `Dark` theme
2. Take a look on the top corners of the app window

### Where did you see the bug
- System Model: MBP 16"
- OS: Big Sur 11.2.3
- Simplenote app version: 2.11.0-beta1 desktop

**Comment by pachlava** [comment]
UPD: it's also visible in light scheme if there's a modal shown:

<img width="799" alt="Screenshot 2021-05-04 at 12 26 30" src="https://user-images.githubusercontent.com/73365754/116984602-19c02880-acd4-11eb-8b66-6e426193b35b.png">

**Comment by pachlava** [comment]
At this point I'm not sure if top corners are expected to be round or sharp 🤔

**Comment by sandymcfadden** [comment]
This I believe is an issue with the version of our Electron dependency we're currently using. It should be resolved with this PR https://github.com/Automattic/simplenote-electron/pull/2871 which updates Electron.
