### ISSUE TITLE
JavaScript error on logout

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2888]
### Expected
Logging out should not cause a JavaScript error.

### Observed
It does:
<img width="566" alt="Screenshot 2021-05-04 at 12 44 18" src="https://user-images.githubusercontent.com/73365754/116986517-8b997180-acd6-11eb-8895-28aac2020663.png">
<img width="277" alt="Screenshot 2021-05-04 at 12 44 55" src="https://user-images.githubusercontent.com/73365754/116986527-8f2cf880-acd6-11eb-988f-44e360348552.png">

### Reproduced
1. Be logged in
2. Log out

### Where did you see the bug
- System Make: MBP 16"
- OS: Win10 (Parallels) | Big Sur 11.2.3
- Simplenote app version: desktop 2.11.0-beta1

**Comment by sandymcfadden** [comment]
Fixed in #2890
