### ISSUE TITLE
Tags are restored regardless of `Restore deleted tags` state

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#2889]
### Expected
If `Restore deleted tags` is disabled, the tags should not be restored

### Observed
Tags are restored regardless:
https://user-images.githubusercontent.com/73365754/116990681-1fba0780-acdc-11eb-9f4e-bcf436c0cee6.mov

### Reproduced
1. Have a note with a tag and history available
2. Delete the tag
3. Open history for the note
4. Disable `Restore deleted tags`
5. Roll back to the state when deleted tag was still present, and click `Restore` ~> tag is restored

### Where did you see the bug
System Make: MBP 16"
OS: Win10 on Parallels Desktop
Simplenote app version: desktop 2.11.0-beta1

**Comment by sandymcfadden** [comment]
Ah, this does seem to be behaving as expected, but maybe we need to make more clear what the checkbox does.
Tags that have only been removed from a note but still exist within your tag list itself will always be restored. 
The checkbox is meant for tags that have been deleted from your tag list directly. If a note has a tag that has been removed from the tag list it won't be restored unless that checkbox is selected.

I'm trying to think of how to make that more clear, but I'm not thinking of anything concise. @SylvesterWilmott do you have any ideas?

**Comment by SylvesterWilmott** [comment]
I can see how this label can be misunderstood. Some possible alternatives:

- Restore trashed tags
- Recover deleted tags

@pachlava do you think this would be an improvement? If not we can include some expanded description in a tooltip on mouseover.

**Comment by pachlava** [comment]
To be honest, both options still might be understood ambiguously, imo. I think a tooltip would help. Maybe it's just me.

**Comment by SylvesterWilmott** [comment]
Here's an example using the popover component along with a "help" icon target (icon would need to be created for this purpose). Thoughts @pachlava ?

<img width="431" alt="Screenshot 2021-05-04 at 12 56 16" src="https://user-images.githubusercontent.com/36532468/116999843-1f1f7200-acd8-11eb-89c6-ef50686d4eda.png">

**Comment by pachlava** [comment]
@SylvesterWilmott I like the copy, maybe adding a `general` word, like `...and re-added to the general tags list.` will make it even more clear.

**Comment by mokagio** [comment]
Moving to keep track of this 2.12.0. It's time to finalize 2.11.0.
