### ISSUE TITLE
32 bit version

### ISSUE THREAD

**Issue by mDfRg** [Automattic/simplenote-electron#289]
Do you plan to compile 32-bit version for older linux machines?  Here is my uname -a output:

`3.16.0-67-generic #87~14.04.1-Ubuntu SMP Fri Mar 11 00:26:36 UTC 2016 i686 athlon i686 GNU/Linux`

Regards,
mDfRg

**Comment by drw158** [comment]
Duplicate of #266

**Comment by mDfRg** [comment]
Sorry!

**Comment by drw158** [comment]
No problem!
