### ISSUE TITLE
Scroll Bar Highlights disappear on search if Ctrl+G or > is used to go to next result

### ISSUE THREAD

**Issue by michaelwexler** [Automattic/simplenote-electron#2903]
### Expected
When searching, blue highlights appear on the scroll bar to show where in the doc the search results are located (and the words are highlighted in blue.  When Ctrl-G or > from bottom of screen is used to go to next result, expected the blue highlights to remain. 

### Observed
Instead, scroll bar highlights disappear.  Blue highlighted hits (words) do remain highlighted on the screen, however, so it's just the scroll bar.

### Reproduced
1. Open any note, pref one with a repeated word and multiple screens.
2. Ctrl-F or click on the search box, type a word you know is present multiple times
3. Observe the highlights in the scroll bar and in the hits (words in the doc that match your search string).
4. Using either ctrl-G or the > (greater than) at the bottom of the note, go to the next hit.  Notice the highlights disappear from the scroll bar.

### Where did you see the bug
- System Make: Dell
- System Model: 8920 
- OS: Windows 10, 64-bit
- OS version: 2004(.19041.928)
- Browser (if applicable): Chrome, Firefox
- Browser version (if applicable): Chrome Version 90.0.4430.93 (Official Build) (64-bit), FF 88.0.1 64 bit 
- Simplenote app version: https://app.simplenote.com/   2.11.0-beta1

**Comment by michaelwexler** [comment]
Thank you, @sandymcfadden, I appreciate getting this fixed so quickly.  Is using Monaco as part of preview rendering on the roadmap somewhere?

**Comment by sandymcfadden** [comment]
Hi @michaelwexler, thanks for opening the issue so it could get fixed!
I did see your other issue #2822 for the highlights not appearing in preview. That is something that I'd like to add at some point but it isn't a high priority currently. 
I haven't looked into it fully but I don't believe the Monaco editor would work well to provide the preview for notes and so we'd need to come up with a custom highlight bar to use instead.

**Comment by michaelwexler** [comment]
Thank you, at least it's on a radar somewhere.  Appreciate all the help in making Simplenote ever more amazing!
