### ISSUE TITLE
Linux client is not loading

### ISSUE THREAD

**Issue by BroBan** [Automattic/simplenote-electron#2904]
When starting the simplenote client on linux, the past couple of days it fails to load any notes and just displays a white screen. 
### Expected
When opening the simplenote client to display the notes, rather than a white screen.
### Observed
Upon going to the debugging console i see two errors present -
`boot-with-auth.42179af05dc5c0fdf677.js:1 Uncaught (in promise) TypeError: Cannot read property 'content' of undefined
    at m (boot-with-auth.42179af05dc5c0fdf677.js:1)
    at boot-with-auth.42179af05dc5c0fdf677.js:1
    at Map.forEach (<anonymous>)
    at g (boot-with-auth.42179af05dc5c0fdf677.js:1)
    at app.36423e27942961645bec.js:29
    at Array.map (<anonymous>)
    at app.36423e27942961645bec.js:29
    at vendors~boot-with-auth.4aa8772bfed63abbc6cc.js:33
    at u (app.36423e27942961645bec.js:29)
    at boot-with-auth.42179af05dc5c0fdf677.js:1`
and
`Uncaught Error: Dispatching while constructing your middleware is not allowed. Other middleware would not be applied to this dispatch.
    at r (app.36423e27942961645bec.js:29)
    at dispatch (app.36423e27942961645bec.js:29)
    at boot-with-auth.42179af05dc5c0fdf677.js:1
r @ app.36423e27942961645bec.js:29
dispatch @ app.36423e27942961645bec.js:29
(anonymous) @ boot-with-auth.42179af05dc5c0fdf677.js:1`

### Reproduced
I can't remember if this happened after i did an update, but it has been like this for a couple of days now and restarting the machine does not help either.

![image](https://user-images.githubusercontent.com/9061102/117656640-44612400-b1a1-11eb-9a86-fa3dfab9c270.png)

### Where did you see the bug
- OS: Linux Kubuntu
- OS version: 20.04
- Simplenote app version: 2.10.0

**Comment by sandymcfadden** [comment]
Hi @BroBan I've tested out the 2.10.0 release on Ubuntu to far and haven't had the same issues you're seeing.
We've just released version 2.11.0 though, are you able to install it and see if you have the same issue?
You can get the file from here https://github.com/Automattic/simplenote-electron/releases/tag/v2.11.0

**Comment by rj-xy** [comment]
@BroBan what was your installation method? i.e apt-get, pacman, yay, manual (please explain how you did this)

**Comment by sandymcfadden** [comment]
Going to close this one for now, please feel free to reopen if needed.

**Comment by jimschmit** [comment]
Hello, I have the same issue (on Linux Mint), I'll check later which version I'm on.

**Comment by thabotswana** [comment]
Another report in 5453806-zen

>on firefox all works, and on my tablet and android phone too, just
the linux deb app is not workink... just a balnk page.

![Screenshot from 2022-08-08 11-56-42](https://user-images.githubusercontent.com/35628116/184909518-33be3b57-116e-4b74-bbe9-d6584ff79fb5.png)

OS: Linux Mint 20.3 Cinnamon
OS version: 5.2.7
Simplenote version: 2.21.0

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
