### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by goduck777** [Automattic/simplenote-electron#2905]
Please reopen #1051

Electron 12 now has been released and has native wayland support. I have tried to change package.json to use electron 12, and simplenote can successfully run in wayland.

However, with the development build I cannot use my own account. I hope you can have electron 12 in your next release, or just relax this limitation so I can build a production version myself.

**Comment by sandymcfadden** [comment]
Hi @goduck777 we are in the process of testing things out with Electron 12. Things do look good so far so we plan to include it in an upcoming release.

**Comment by goduck777** [comment]
I tested the new version with full wayland support and it works well.

Thank you!

**Comment by taprobane99** [comment]
any progress on this?

**Comment by ralyodio** [comment]
It still won't open for me on arch/kde. I have to use a command line argument.
