### ISSUE TITLE
WYSIWYG Editor

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#2909]
Markdown support is great; however, WYSIWYG (what you see is what you get) editor would have been much more suitable for most users. Or, at least give the ability to choose opening the md notes always in preview mode.

### Faster, clutter free note taking

WYSISWYG editor makes life much easier and gives the user a clutter-free space.

### How

This is an example editor.

![0F4173FE-BFBE-467A-948B-A299EC940473](https://user-images.githubusercontent.com/83839684/118598810-5a7d6e80-b7b7-11eb-8123-9094010d3c62.png)

**Comment by sandymcfadden** [comment]
Thanks so much for the request. This is something that has been requested a number of times. We track feature requests like this in an internal tracker. I've added your request there. We don't have plans currently to add this, but we track it so we can consider it for the future.
