### ISSUE TITLE
Start menu shortcut opens a second, broken copy of the app.

### ISSUE THREAD

**Issue by rikai** [Automattic/simplenote-electron#291]
If you open simplenote on windows via the start menu (or, i presume a desktop icon as well), it opens the app a second time, the second copy being in a broken state where none of the UI appears.

This isn't the functionality i expected. Most apps, when opened from an icon/menu entry, pull up the existing copy of the app.

**Comment by rikai** [comment]
Just curious if there's a reason this hasn't been marked as a bug yet. :)

**Comment by dmsnell** [comment]
Thanks for the follow-up @rikai. It's not that we don't consider it a bug - we just hadn't gotten to this yet. Right now we don't have enough resources to work through the full list of issues. We appreciate your help in finding and writing them up!

**Comment by roundhill** [comment]
This was fixed somewhere along the way ;)
