### ISSUE TITLE
[macOS] App Still Open After Quitting

### ISSUE THREAD

**Issue by kaelri** [Automattic/simplenote-electron#2912]
### Expected
While the Simplenote application is open on macOS, the “quit” command should fully close the application.

### Observed
When quitting Simplenote, the window disappears, but the application does not fully close. The dock icon indicates that the app is still open, and the Activity Monitor shows that the Simplenote process is still running and consuming a small amount of memory and CPU cycles.

If a second “quit” command is sent—e.g. by Cmd-Tabbing to the Simplenote application and then quitting with Cmd-Q—the app does close completely.

Interestingly, the same behavior occurs if I terminate the process from the Terminal via `killall Simplenote`. However, using “force quit” from the dock or Activity Monitor does close the app with one attempt. This could be related to one of the various helper processes that load alongside the primary application process.

If I try to reopen Simplenote after the first quit attempt, the window has to load as if for the first time, i.e. with an expected amount of delay/lag. So it seems like the document is certainly ”closed” from Electron’s point of view, but the OS isn’t getting the message.

### Reproduced

1. Open Simplenote so that the main window is visible.
2. Quit the application via the menu bar, dock, keyboard shortcut, or `killall` Terminal command.
    - The window should now be closed, but the Dock icon still appears with an "open" indicator light, and Activity Monitor still shows an active “Simplenote” process.
3. Quit the application again.
    - Simplenote should now be completely closed.

### Where did you see the bug
- System Make: MacBook Pro
- System Model: 13-inch, 2020, Four Thunderbolt 3 ports
- OS: macOS
- OS version: 11.3.1 
- Simplenote app version: 2.11.0

**Comment by pachlava** [comment]
@kaelri thank you for the report! The issue is already [fixed](https://github.com/Automattic/simplenote-electron/pull/2901) and will be shipped with the next Simplenote 2.12, which is expected to be available on 1st of June.
