### ISSUE TITLE
Linux Client not syncing notes

### ISSUE THREAD

**Issue by davidromero** [Automattic/simplenote-electron#2915]
Hello I had been using simple note linux client app for 8 months everything was smooth and nice. Until last week, when i tried to login with another linux machine but failed. The login button just keeps showing the loading animation then it fails. 

I went to my main machine and edit some notes, but they cant sync, i dont know if theres a problem with my account or the client, i tried recovering my password but doesnt work.

### Expected
To login in with multiple clients, and sync notes all across.

### Observed
Linux Client 
### Reproduced
1. Linux client version 2.10.0, ubuntu 20.04
2. Login in 
3. Error

I tried with the web client but my notes are gone there.

**Comment by pachlava** [comment]
Hello @davidromero ! Thank you the report. In cases like this, when there's a chance that the root cause is in the account, I would suggest you contacting our dedicated support team by  sending the email to support@simplenote.com. Any additional information you can provide would help.

**Comment by davidromero** [comment]
thanks i will!.
