### ISSUE TITLE
Multiple Checkbox on a line

### ISSUE THREAD

**Issue by chromer030** [Automattic/simplenote-electron#2917]
### What

Please add support for multiple checkbox on a single line.
### Why

Currently checkbox is limited to new lines and sometimes we need to have multi checkbox on a line.

**Comment by sandymcfadden** [comment]
Hi @chromer030 Thanks so much for the suggestion.

I've added this request to our internal feature request tracking system for future consideration. We keep feature requests there so I'll close this issue in favor of tracking there.
