### ISSUE TITLE
Server not connecting

### ISSUE THREAD

**Issue by piskunow** [Automattic/simplenote-electron#2918]
The app in my mobile phone is not loading, nor the desktop app, and in the web app I see no server connection.

![image](https://user-images.githubusercontent.com/22959851/119881544-b1a8df00-bf2d-11eb-95ac-d15548fc0ed7.png)

**Comment by dmsnell** [comment]
Hi @piskunow - it appears like there is an issue preventing your devices from connecting with our servers. Can you reach out to support@simplenote.com where we can discuss specific details and resolve the problem?

**Comment by forteller** [comment]
Hi. I've had this same problem for a good while now, and sent an e-mail to support@simplenote.com about it on Feb 22, with no reply yet. Hope to hear from you soon. Thanks!
