### ISSUE TITLE
Cursor jumps to bottom of the note while editing

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-electron#292]
I am experiencing an issue while editing an existing note. Every time I try to edit the note (e.g. add text in the middle of the note), after a few seconds of typing the cursor jumps to the bottom of the note as I type. I then have to cut and paste the text I typed to put it where I want it in the note.

This doesn't seem to happen for all notes, so here are a few things about the note I have trouble with:
- It is a pinned note
- It is a fairly old note that I edit almost daily (I use it as a to-do list)
- Markdown is not enabled on the note (and I noticed this issue before enabling markdown in Simplenote)
- The note currently has 496 words with 3543 characters

(It's possible that this isn't a note-specific issue and I only notice it with this note because it's the one I edit most often.)

App: Simplenote beta v. 1.0.1
OS: Mac OS X 10.11.4

**Comment by rachelsquirrel** [comment]
A report on Linux (Mint 17.3, Ubuntu 14.04)- #2642910-t

**Comment by rachelmcr** [comment]
I have noticed that if I unpin and re-pin the note, this issue goes away for a while. I'm able to edit the note without any trouble for a while, although eventually the problem comes back and my cursor jumps to the bottom of the note again as I type.

**Comment by cecoates** [comment]
User still having this issue:

864118-zen

Asked for more information.

**Comment by RolfCl** [comment]
I am using Windows 10. The problem has been worse since upgrading to 1.1.2.

**Comment by rexpo** [comment]
Freshly installed Win10 Enterprise (build 1709), freshly installed Simplenote 1.1.2.

Happens randomly, whether in bulleted lists or not.

It's especially fun when the cursor jumps while I'm hitting backspace quickly to delete a few characters. Extra cool that Ctrl-Z doesn't recover the mystery characters that I just deleted at the end of my note.

## ***Almost 2 years and this still isn't fixed????*** You do realise that this bug makes the program ***useless***? It ***damages*** notes!!

*Thank gawd I only need to use this Windows machine for a few days!*

**Comment by ChrissiePollock** [comment]
Issue brought up again in #958281-zen

**Comment by dmsnell** [comment]
This is an important bug to fix. I'm going to fold this thread into #36 where we can centralize a few spread-out and duplicate conversations. I have moved the ticket references over there as well. Please let me know if I missed any.

As we are preparing to overhaul the editor part of the app this should resolve itself as a byproduct of working through the flows which have been broken in the past to make sure we get it right this time. A number of related issues should also resolve.

**Comment by zoltanwerner** [comment]
Still happening under lates release v1.4. Jumps to end of note seemingly randomly.

**Comment by zhartus** [comment]
> Still happening under lates release v1.4. Jumps to end of note seemingly randomly.

The same problem here.

**Comment by nsabouret** [comment]
Still having the same problem
