### ISSUE TITLE
"Review Your Account" dialog appears always when starting the application

### ISSUE THREAD

**Issue by bkosowski** [Automattic/simplenote-electron#2921]
Every time I open the application (current version 2.11.0) on Linux (up-to-date Manjaro), the "Review Your Account" dialog pops up. There doesn't seem to be anything I can do to stop it from appearing. I can only close it. I tried using the "Confirm" option, clicking on the sent e-mail and logging through the browser a dozen times. Still, the issue persists.

### Expected
After confirming the e-mail once, the dialog no longer appears when starting the application.

### Observed
The "Review Your Account" dialog pops up each time I open the Electron application, no matter what I do.

### Additions
The dialog that appears when I open the application:
![review_your_account](https://user-images.githubusercontent.com/4819024/120033908-8a6d1300-bffc-11eb-8ddf-9b4002d76e2b.png)

### Reproduced
1. Open the Electron application.
2. Click on "Confirm".
3. Go to your e-mail account.
4. Click on the sent link in the e-mail.
5. Log in to Simplenote browser version.
6. Start the application again.
7. See the "Review Your Account" dialog.

### Where did you see the bug
- OS: Manjaro Linux
- OS version: 21.0.5-1
- Simplenote app version: 2.11.0

**Comment by codebykat** [comment]
Hi @bkosowski, I'm sorry for the trouble. Can you please try logging out of the app entirely (not just closing the application, but going into Settings and signing out) and logging back in, and let us know if that fixes the issue? That should force it to sync up your account information.

**Comment by bkosowski** [comment]
@codebykat Noice! That did the trick. Thank you! :*

**Comment by bjwest** [comment]
Although the above action by @codebykat works, I don't think this should be closed without fixing the actual problem  One shouldn't have to log out and log back in to sync account information.

**Comment by ghost** [comment]
I had the same issue. Logging out and back in fixed it. But I agree with bjwest, this is bad behavior and needs to be fixed. I shouldn't have to come to GitHub and search through closed issues to find out how to work around it.

**Comment by codebykat** [comment]
Hi @bjwest and @holmesrichards, we have made some updates to both the app and the backend to fix this problem since it was first reported. However in rare cases it does still get stuck, and after a lot of investigation, logging out and logging back in is really the best way to get your account info to sync up. Sorry for the trouble. The good news is, once you've validated your email, you never need to do so again. If you encounter any further issues please feel free to reach out to us at support@simplenote.com.
