### ISSUE TITLE
I can't login in the .deb app

### ISSUE THREAD

**Issue by allanpfreitas** [Automattic/simplenote-electron#2924]
### Expected
Expected to be able to login in the app

### Observed
I noticed that the icon in the Web App is telling the server connection is down 
![image](https://user-images.githubusercontent.com/2490836/120340572-8a0a9b80-c2cc-11eb-874b-7ba03f6bd252.png)

### Reproduced
1 - Download and install the .deb file
2 - Fill the username and password with valid ones
3 - The application stays in the login forever
![image](https://user-images.githubusercontent.com/2490836/120340857-c0e0b180-c2cc-11eb-8b77-902efd20acc4.png)

### Where did you see the bug

- System Make: Asus
- System Model: AMD Ryzen 
- OS: Linux Mint
- OS version:  Linux Mint 20.1 Cinnamon
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: .deb 2.12.0

**Comment by codebykat** [comment]
Hi @allanpfreitas, are you able to log in from app.simplenote.com successfully? What if you try a different network connection (for example, tethering to your phone instead of WiFi)?

**Comment by allanpfreitas** [comment]
Hi @codebykat I'm trying to log in from my desktop computer. I can log in successfully in app.simplenote.com but as I displayed I have this message about network connection.
 ![image](https://user-images.githubusercontent.com/2490836/120495527-2bf4bb80-c393-11eb-8274-b72a48c603fb.png)

**Comment by codebykat** [comment]
Okay, in order to track this down we need to ask you for some info that we can't do on the ~private~ public (sorry, typo) GitHub, as it likely relates to something specific about your account or your network config. Can you please send an email to support@simplenote.com so we can figure it out? Thanks!
