### ISSUE TITLE
Search only in selected tag

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#2929]
**What**
I want to show search results only in/of the selected tag.

**Why**
This feature was available in Simplenote Electron Version 1.xx

Currently, search results are shown of all tags (regardless of the selected tag)
and I loose the oversight.

**How**
- select a tag
- search for a expression
- show search results only in/of the selected tag.

**Version**
Windows 10 electron
Simplenote-Version 2.12.0

**Comment by pachlava** [comment]
Thank you for the report @gubrist! The search has been made global for Electron/Web platform recently to make it consistent with iOS, macOS and Android. You can still search only among notes with a specific tag by including both tag and search keyword into the search field like this:

<img width="1000" alt="Screenshot 2021-06-07 at 13 49 50" src="https://user-images.githubusercontent.com/73365754/121004374-4a91f280-c797-11eb-97fd-210afb66a55a.png">

Please let us know if this helps.

**Comment by gubrist** [comment]
Thanks. 
As I have a lot and long tag names, this manual typing is a bit laborious.

**Comment by gubrist** [comment]
The electron version has evolved, meanwhile:

Entering a second word, Simplenote-elelctron suggests to search in tags beginning with that expression

![search](https://user-images.githubusercontent.com/22197180/136037749-4c243152-8bdd-43b5-9eac-c69fa3ddb50b.JPG)

**Comment by gubrist** [comment]
(When) can an update be expected?

**Comment by gubrist** [comment]
Any update on this?
