### ISSUE TITLE
How To Install

### ISSUE THREAD

**Issue by l4n1skyy** [Automattic/simplenote-electron#2932]
Hi! This might be a dumb question, and I don't know if it's right for me to ask this here, but how do I install this on linux? I'm not really tech savvy, sorry :(
I downloaded the zip file, I extracted it, but there's no .deb file or anything.. 

I just tried doing this part in the readme

```
## Running

1. Clone the repo: `git clone https://github.com/Automattic/simplenote-electron.git`
2. `cd simplenote-electron`
3. `npm install`
4. `npm run dev`
5. The dev server will start on [http://localhost:4000](http://localhost:4000), and the Electron app will launch automatically.
6. For all logging from Electron to be printed to the terminal (e.g. `console.log` statements within `app.js`), you might need to set `env ELECTRON_ENABLE_LOGGING=1`.
7. Sign up for a new account within the app. Use the account for **testing purposes only** as all note data will be periodically cleared out on the server.

_Note: Simplenote API features such as sharing and publishing will not work with development builds. Due to a limitation of `make` installation paths used for build cannot have spaces._
```
and I think its meant for developers.. it says it's meant for testing purposes only, what should I doooo!!?!
I can't login to it with my account too..

**Comment by Lani-Skyy** [comment]
I just tried doing this part in the readme

```
## Running

1. Clone the repo: `git clone https://github.com/Automattic/simplenote-electron.git`
2. `cd simplenote-electron`
3. `npm install`
4. `npm run dev`
5. The dev server will start on [http://localhost:4000](http://localhost:4000), and the Electron app will launch automatically.
6. For all logging from Electron to be printed to the terminal (e.g. `console.log` statements within `app.js`), you might need to set `env ELECTRON_ENABLE_LOGGING=1`.
7. Sign up for a new account within the app. Use the account for **testing purposes only** as all note data will be periodically cleared out on the server.

_Note: Simplenote API features such as sharing and publishing will not work with development builds. Due to a limitation of `make` installation paths used for build cannot have spaces._
```
and I think its meant for developers.. it says it's meant for testing purposes only, what should I doooo!!?!

**Comment by sandymcfadden** [comment]
Hi @Lani-Skyy thanks for reaching out. 
You're right this is more for development, but you can download installation files from the releases section. The latest can be found here https://github.com/Automattic/simplenote-electron/releases/tag/v2.13.0

I hope that helps!

**Comment by l4n1skyy** [comment]
Ah I see, thank you so much! I actually found it on the software store, so I downloaded it from there.. should I delete the thing I downloaded using these commands/ undo the things these commands did? How can I do that?
```
1. Clone the repo: `git clone https://github.com/Automattic/simplenote-electron.git`
2. `cd simplenote-electron`
3. `npm install`
4. `npm run dev`
5. The dev server will start on [http://localhost:4000](http://localhost:4000), and the Electron app will launch automatically.
6. For all logging from Electron to be printed to the terminal (e.g. `console.log` statements within `app.js`), you might need to set `env ELECTRON_ENABLE_LOGGING=1`.
7. Sign up for a new account within the app. Use the account for **testing purposes only** as all note data will be periodically cleared out on the server.
```
Thanks for replying by the way, it's really kind of you! I'm pretty new to all of this :')

**Comment by sandymcfadden** [comment]
Glad you were able to get it installed. You can delete this Github repo from your computer no problem. In the folder you ran the `git clone` command there will a `simplenote-electron` folder. You can delete that folder.

**Comment by l4n1skyy** [comment]
Thank you so much!
