### ISSUE TITLE
Question: how can I store my notes locally without using simplenotes account?

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#2934]
I want to store all my notes on my local machine. For such case I don't need a simplenotes account.
How can I achieve this?

**Comment by pachlava** [comment]
Hello @altwarg! One of the key features of Simplenote is continuous sync of user content across all devices where Simplenote is installed. Having an account is necessary for this, subsequently, the business logic of the app requires an account. There is no way to use Simplenote with no account, unfortunately.
