### ISSUE TITLE
ToDo List Support

### ISSUE THREAD

**Issue by ryanleesipes** [Automattic/simplenote-electron#294]
Now that I find myself using this application every day for notes, I find that I keep making ToDo lists in it. I'm not sure if this issue needs to be integrated at a lower level (simplenote proper). But some kind of checkbox support or a proper ToDo list integration seems like a natural fit.

**Comment by rikai** [comment]
There is [existing markdown syntax](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments) that could be used to support this feature.

**Comment by ryanleesipes** [comment]
Thank you @rikai - nice to see JB folks in here! :smile:

**Comment by ryanleesipes** [comment]
Hold up, that syntax doesn't work for me, @rikai - does it work for you?

**Comment by drw158** [comment]
That's Github flavored MD, I don't think we support that right now.

**Comment by ryanleesipes** [comment]
@drw158 is it on your roadmap? Is there an alternative way to do it that is supported?

**Comment by drw158** [comment]
Proper to do list support is something we want to do, but no plans. Maybe in the meantime we can enable Github flavored MD.

**Comment by ryanleesipes** [comment]
That would be awesome.

**Comment by drw158** [comment]
Closing in favor of #309
