### ISSUE TITLE
Verification prompt keeps appearing in Electron version despite verifying manually from our end.

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#2940]
User on 4074680-zen reported that they keep seeing the verification prompt even though they confirm and verify every time. Generally we see this problem in the web version and is enough if we verify their account manually from our end, after this they don't see the prompt anymore.

In this case, the prompt has disappeared from the web version ( as expected ) but they keep seeing it via the Linux app. From the user:

> I am working on Ubuntu 20.04 and my Simplenote version is 2.13.0.
I installed it with the deb-package from
https://github.com/Automattic/simplenote-electron/releases/tag/v2.13.0
> and now in the Snap-version, there was and is no verification message in the last months

### Expected
That the prompt is not requested after the user verified their account, or we verify it manually from our end.

### Observed
I don't have a machine or setup to replicate this.

**Comment by sandymcfadden** [comment]
There seems to be a few people where this verification screen gets stuck for them. Logging out and back in clears this up.
@iamgabrielma are you able to have them log out and back in?

**Comment by hevanaa** [comment]
I still have this issue on Linux, Fedora 34 flatpak package (version 2.17.0). I have logged out and in (in the desktop app) and verified email again, but it still asks me every time to verify my email when I start the desktop app. It doesn't ask on the web nor in the Android app.

**Comment by iamgabrielma** [comment]
Re-opening this one for the moment, in 4299195-zen restarting the app doesn't seem to fix it.

**Comment by hevanaa** [comment]
Still an issue for me with 2.18.0 on Linux.

**Comment by codebykat** [comment]
Hi @iamgabrielma, note that restarting the app without logging out is not the same as logging out and logging back in. Can you ask the user to log out from Preferences and see if that fixes it?

**Comment by iamgabrielma** [comment]
> Hi @iamgabrielma, note that restarting the app without logging out is not the same as logging out and logging back in. Can you ask the user to log out from Preferences and see if that fixes it?

Yeah! My message was not clear, 4299195-zen claims that they logged out and in, and then restarted the app but this still hasn't fixed it. We're now waiting for more details of their app/OS versions to see if anything is out of date.

**Comment by hevanaa** [comment]
There is something odd going on with the flatpak package I'm using. When I log out from Settings, and don't log in again, next time I start the app it logs in by itself again without asking credentials. So I can't log out from it! I tried uninstalling the flatpak with --delete-data option and installed it again and it logged straight in to my account when starting. I kind of understand that uninstalling shouldn't erase user data, but maybe there is some issues with the credentials, I don't know. So if I could get _really_ logged out from the app, maybe it would help.

**Comment by sbgraphic** [comment]
Hi, I confirm I had this annoying prompt request for a long time and before 2.15. Today I saw this open issue, so just before updating to 2.21 (github electron version), I did the following _(MacOsx 10.13, old MacPro 3,1)_:
1. **signed out** & quit
2. update with the latest app version (2.21)
3. **sign in** back gain.

Tadaaa.… Looks like the "verification prompt" is gone for now... 

I'll check later on my other (more recent) Macs, if the cause was resolved too by just to "sign out" and "in" to fix as I'm still on 2.15

Thanks to @iamgabrielma for the tip above.

**Comment by erricgunawan** [comment]
Another report from 5226842-zen:

> For more than 6 months I see this Review your email prompt every time I launch the Windows Desktop app. I have confirmed my email countless times but it still keeps popping out.

Asked them to log out and back in, after verifying their notes on the web app.

**Comment by CameronMilliken** [comment]
I don't like to complain about something so useful and free, without even adverts, (I've no idea how you do it) but there is one other thing as I'm here.  The app for Windows 10 throws a nag message about verifying e-mail on every single start up, even if you've just done it anyway. It doesn't seem to break anything, but it's very annoying having to dismiss it every time and it feels like it's been going on for ever.

https://woothemes.zendesk.com/agent/tickets/5374043

**Comment by codebykat** [comment]
Closing as stale, I think this issue has been fixed.
