### ISSUE TITLE
Can not login to Simplenote (flatpak version)

### ISSUE THREAD

**Issue by tuananhlai** [Automattic/simplenote-electron#2948]
The flatpak version of Simplenote on Pop OS 20.04 throws CONNECTION_TIME_OUT constantly when I tried to login. I am sure that my email address and password are correct (I double-checked on simple note website).

Also, I would be appreciated if someone could tell me the location of my notes so I could recover them.

### Expected

The app let me login.

### Observed

The app show a CONNECTION_TIME_OUT error in the console and `The provided email address...` error in the app.

### Reproduced

1. Go to login
2. Enter email address and password
3. Click Login

### Where did you see the bug

- System Make: ASUS
- System Model: Zenbook UX430
- OS: Pop OS
- OS version: 20.04 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.13.0

**Comment by Chortowod** [comment]
Same thing happened to me.
At first I wasn't able to sync so I decided to reinstall the program. As the result - now I can't log in after installing from win .exe file.

**Comment by RealYaddie** [comment]
> Same thing happened to me.
> At first I wasn't able to sync so I decided to reinstall the program. As the result - now I can't log in after installing from win .exe file.

The same thing has happened to me and right now I'm still unable to login on my laptop, my phone is still connected but I'm not gonna risk logging out of it there.
I did however manage to log in using through my web browser but none of my notes showed and in the sidebar, it said that 
>"Simplenote hasn't communicated with the server in a while; changes may not be synchronized with the server until the connection improves."

and as a result of that none of my notes show up there.

**Comment by codebykat** [comment]
It sounds like there may be a couple of things going on here.  @RealYaddie If you are having trouble syncing from the web browser, you might try from a different IP address to see if that resolves the problem. Sometimes this issue is caused by use of a VPN or firewall, so you can try turning those off. Otherwise it might be something specific about your account; please email us at support@simplenote.com if none of that helps and we can do some further debugging!

@tuananhlai Can you confirm that you are able to log in on the web at https://app.simplenote.com and that your notes appear there? That would narrow it down to a problem with the Flatpak app version rather than your network or account. As far as the location of your notes, if you're able to log in on the website and view them, you can export them all from Settings so that you have a backup.

**Comment by tuananhlai** [comment]
> @tuananhlai Can you confirm that you are able to log in on the web at https://app.simplenote.com and that your notes appear there? That would narrow it down to a problem with the Flatpak app version rather than your network or account. As far as the location of your notes, if you're able to log in on the website and view them, you can export them all from Settings so that you have a backup.

I am able to log in on the web with my account, but since my notes weren't synching (due to the app, network,...), there's nothing on the web for me to backup. If you could tell me the location of the notes on my local machine, that would be great.

**Comment by karbarkar** [comment]
I just updated Simplenote on Windows and now I have the same problem. I can't log in using windows app. The mobile app works fine (but I did not log out). I can log in to web app but my notes are not there.

**Comment by codebykat** [comment]
@tuananhlai The notes are not stored in any kind of easily-accessible way, unfortunately. What version were you using previously, and was it able to sync? It sounds like it was never actually syncing, if you have no notes showing up on the web?

Can you please try installing the prior version to see if that is still working? Prior versions of the app can be downloaded from here: https://github.com/Automattic/simplenote-electron/releases

@karbarkar If the mobile app is syncing correctly, your notes should also be visible on the web app. Does the web app show that the connection to Simperium is working, or is it showing an error in the sidebar?

**Comment by karbarkar** [comment]
> @karbarkar If the mobile app is syncing correctly, your notes should also be visible on the web app. Does the web app show that the connection to Simperium is working, or is it showing an error in the sidebar?

Web app -> sidebar, there is a wifi-like icon crossed out and when I hover the cursor over it says "Simplenote hasn't communicated with the server in a while; changes may not be synchronized with the server until the connection improves."

My connection is good and stable.

**Comment by codebykat** [comment]
@karbarkar That is good to know - it means the notes aren't showing on the web because of connection difficulties to the backend, not because they aren't there. Can you try it from a different network please? Are you using any kind of VPN or firewall?

**Comment by karbarkar** [comment]
@codebykat 
I tried with VPN and without VPN, turned off my AntiVir, downloaded three prior versions of the windows app and I still can't log in. Now I logged out from the mobile app and can't log in back. Three days ago it worked all fine.

**Comment by reginabally** [comment]
Hi @karbarkar Can you try switching to a different network source (e.g. mobile data) and see if you can log in? If you're on WiFi, you can restart the modem to get a new IP address from your ISP.

If that doesn't help, please write to us at support@simplenote.com, let us know your GitHub username, and share with us the link to this GitHub report so we can cross-reference it. Thanks.

**Comment by karbarkar** [comment]
BINGO! When I turn off WiFi and turn on LTE on my mobile it works, and all of my notes are there :) but it is weird that with VPN it still does not work (I tried five different IPs).

Thank you @codebykat and @reginabally for your time and help.

**Comment by Reyzan** [comment]
Same thing happened to me and the trick above doesn't solve my problem. I get errors like below when open debugging console:
`WebSocket connection to 'wss://api.simperium.com/sock/1/chalk-bump-f49/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT` 
or 
`WebSocket connection to 'wss://api.simperium.com/sock/1/chalk-bump-f49/websocket' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE`

**Comment by reginabally** [comment]
Hi @Reyzan It seems like your device wasn't able to connect to our servers. If you use any VPN/proxy/security software, can you disable them and see if you can connect? You can also try connecting your device to a different network source, or restart the Wi-Fi router to get a new IP address from your ISP to see if it helps.

If this isn't working, please reach out to us at support@simplenote.com and let us know the version of the Simplenote app you're using. Thanks!

**Comment by reginabally** [comment]
If you're reading this and experiencing the same issue, please try these troubleshooting steps.

1) Try logging in to the web app at https://app.simplenote.com on a web browser. If you did this, try with another browser without an extension.

2) Disable any VPN/proxy/security software you're using on your device.

3) Connect your device to a different network source, or restart the Wi-Fi router to get a new IP address from your ISP.

If you've tried all these steps but are still unable to access your account and notes, please email us at support@simplenote.com and let us know. Thanks!
