### ISSUE TITLE
Unable to highlight text on Windows 10

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/simplenote-electron#2952]
Reported in 4061125-zen.

### Expected
To be able to highlight the texts correctly.

### Observed
They are unable to highlight any texts on their Windows web app as well as the Windows app. All their other apps are working. The issue happens across all browsers and updating the Text Cursor Indicator settings also did not work. As a workaround, they are following the steps to "select all" and then copy/paste into another program.

### Reproduced
1. Go to https://app.simplenote.com/
2. Try to highlight a text 
3. Mouse cursor is not visible to highlight.

Screenshot can be found on the ticket. I'm asking for the user's permission to attach them to this report. I wasn't able to replicate this on the web app and the Electron app on macOS. 

### Where did you see the bug
- System Make: HP
- System Model: Envy
- OS: Windows
- OS version: Windows 10
- Browser: Chrome
- Browser version:91.0.4472.106 (Official Build) (64-bit)

**Comment by eduardozulian** [comment]
Their version is 2.13.0.

From the user:

> My only workaround has been to -- while in App -- to use keypad controls: Control A; Control C... then copy the work into another program such as Word. Usually, I just copy it into my email and then send it to myself.
FYI, I can use the cursor with text cut and pasted into these emails.

As for the screenshot, the user mentioned:

> It might be hard to see, but the only "markers" of using the mouse to highlight text are the space markers between words. Otherwise, space markers would not be there.

![image](https://user-images.githubusercontent.com/1136160/126200128-f7075b7c-eb29-4b31-aedd-e9b29f561322.png)

**Comment by codebykat** [comment]
This is deeply odd. I don't see any issues in either the Electron or Monaco repositories that seem at all similar.

I wonder if they are using:
* Any custom zoom levels
* Any OS level accessibility customizations or custom themes
* Any browser plugins

Additionally I'm wondering if they are able to select text invisibly (as in, the selection is succeeding, but the highlight is not being displayed correctly) or if they are simply unable to select text at all? They could test this by attempting to highlight text and then "cutting" it, or typing to see if it is replaced by newly-typed text.

Finally, does it happen on all notes? Or is it possible they have some kind of weird character in some specific note or notes that is breaking Monaco's parsing somehow? We could ask them to try creating a brand new note and find out if the issue exists there.

@poojashetty18

**Comment by sandymcfadden** [comment]
I've tested this a fair amount with different system settings and changing cursor settings but couldn't duplicate this at all. I'm really not sure what is causing this for them, but it seems limited to their system. With that and that there hasn't been any activity for some time I'm going to close this for now.
