### ISSUE TITLE
Does simplenote have native wayland suppoer ?

### ISSUE THREAD

**Issue by parsanoori** [Automattic/simplenote-electron#2953]
I need to live in wayland, since I've got a lodpi and a hidpi display.
Does it have native wayland support or it may get blurry on wayland ?

**Comment by pachlava** [comment]
Hi @parsanoori , thanks for reaching out! You might find [this thread](https://github.com/Automattic/simplenote-electron/issues/2905#issuecomment-864467982) useful. Let us know if this helps, please.

**Comment by codebykat** [comment]
Closing as it seems to be answered by the other thread.
