### ISSUE TITLE
Unable to Publish Note

### ISSUE THREAD

**Issue by NathanDai5287** [Automattic/simplenote-electron#2956]
I clicked the three ellipses and then checked publish. However, the `Copy Link` button loads indefinitely. 

I tried publishing a note in both the Windows desktop app and the web app. Both yield the same result. 

![image](https://user-images.githubusercontent.com/61402904/125183700-9d632d80-e1cd-11eb-826e-3a9c1778d051.png)

I couldn't find any duplicates. Hope this helps! 👍

**Comment by pachlava** [comment]
Thanks for reaching out to us @NathanDai5287! It looks like the issue you describe might be account-specific. Could you please contact our support team at support@simplenote.com? Thank you!

**Comment by NathanDai5287** [comment]
Yeah of course.
