### ISSUE TITLE
Support Table of Contents (TOC)

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2957]
Hello, Please I want to create a table of contents but I do not want to make multiple notes.
~https://simplenote.com/2020/11/03/introducing-internal-links/~

I need this:
```
# Table of Contents
1. [Example](#example)
2. [Example2](#example2)
3. [Third Example](#third-example)
4. [Fourth Example](#fourth-examplehttpwwwfourthexamplecom)


## Example
## Example2
## Third Example
## [Fourth Example](http://www.fourthexample.com) 
```
Learn more: https://stackoverflow.com/questions/11948245/markdown-to-create-pages-and-table-of-contents/33433098
Thanks.

**Comment by pachlava** [comment]
Thank you for reaching out to us @xmha97 ! This is one of the requested features, and I've added one more vote based on your request to our internal tracker. We can't predict when exactly will this be implemented, but it's on our radar. _Thank you!_
