### ISSUE TITLE
The last character is deleted!

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#2959]
Hi, I use Simplenote on Windows 10.
When I use `[` feature, the last character is deleted!
![Simplenote](https://user-images.githubusercontent.com/23485114/125289761-d8cc3c00-e334-11eb-855e-511f7e6077d9.gif)
Please fix it.

**Comment by pachlava** [comment]
Hi @xmha97 ! Thank you for the report! It looks like it duplicates #2771, so I'm closing this issue. Let us know if it's not the case, please.
