### ISSUE TITLE
Select and drag text replaces spaces with %2B - Windows

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#296]
Steps to reproduce:
1. Select a line of text in the Windows app.
2. Drag it to a different location in the note.
3. The spaces are replaced with %2B.

**Comment by dmsnell** [comment]
@rachelmcr I don't think this is an issue anymore. we've gone through considerable changes to the editor. if it is (I couldn't reproduce) please let me know and we'll reopen and get to it.
