### ISSUE TITLE
How is the username obtained from confirmation token?

### ISSUE THREAD

**Issue by aryaniyaps** [Automattic/simplenote-electron#2963]
I was looking into this project to learn React, and more particularly, the authentication process. SimpleNote's authentication workflow is very secure, from what I can see. While trying to learn how it works, I couldn't understand a part though.

While registering,
- user enters email. A call is made to /request-signup
- if the email doesn't exist already, an email is sent with a confirmation link.
- the link looks like this:
   https://app.simplenote.com/account/complete-signup?token=Ze0yv2mQ3jiekY9kKLzg6WIigWwDbp0S
- when the link is opened in the URL, a page like this pops up:
![image](https://user-images.githubusercontent.com/69184573/125820945-6cf11418-3f01-4d1f-83d9-0b0818bed8ee.png)

However, I am curious, how is the email field value obtained?
I checked the network logs and could see that no external request is made to get the email.

It's as though the email is magically popping up.
Could anyone please clarify this? I would love to implement a similar authentication workflow in my projects.

Thanks for this amazing project!

**Comment by codebykat** [comment]
Hi @aryan340, the missing piece here is that the backend is doing some work! When the client sends along the "request-signup", the backend generates a unique token that is associated with the user's email address and stored in the database. Then when the link is clicked from the email, the backend looks at the database to see which email address is associated with that token (and some other stuff like whether the token is still valid). If it's valid, it renders a template with the email address already filled in.

I'm going to close this issue as it's not something we need to address, but I hope this helps! Please feel free to ask more questions if there's still something that doesn't make sense.

**Comment by aryaniyaps** [comment]
Is the complete signup page handled by the backend with some sort of templating engine? I could see that this part isnt handled by the react client.

Thanks for the reply!

**Comment by codebykat** [comment]
Yes, exactly - it's basically a separate site. Actually it's mostly a separate API (Simplenote's backend is a service we run called [Simperium](https://simperium.com/)) with a few webpages that handle some specific things like signup and settings. Those templates are a framework similar to Django. Unfortunately we haven't yet been able to figure out how to open-source that part of the system, as it's tightly-coupled with our specific needs and wasn't written with the ultimate goal of opening up the source in mind, but we do hope to be able to share parts of that system publicly one day.
