### ISSUE TITLE
Failed to sync

### ISSUE THREAD

**Issue by felangga** [Automattic/simplenote-electron#2966]
Mine got this error on Windows 10, so it won't sync with my phone

> WebSocket connection to 'wss://api.simperium.com/sock/1/chalk-bump-f49/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

Does the server is down?

**Comment by codebykat** [comment]
Hi @felangga, the server is not down! Can you perhaps try with a different network connection? If you are using a VPN or firewall, it can also help to turn that off. If that doesn't help, please reach out to us at support@simplenote.com . I'm closing this issue as we can't effectively debug individual account related problems on the public GitHub, but please let us know how it goes!
