### ISSUE TITLE
Option to encrypt notes

### ISSUE THREAD

**Issue by rj-xy** [Automattic/simplenote-electron#2974]
Allow the user to encrypt some or all notes, so that the text in the notes can not be consumed on the server end by either the admins or a malicious attack.

### What
The ability for the user to encrypt notes, or perhaps only selected notes, using either their login password, or another password

### Why
For privacy reasons. Although notes shouldn't have sensitive data in them, that line is blurred the more a user uses the software.

### How
Either the password can be used for encryption (easiest), since the password should be hashed and salted on the server end, the admins would still have a hard time of decrypting.

---

The MVP for this feature would be:
- Use the password for encrypting, since that field has already been collected, no other admin/config field is required
- Rather than tracking which notes to encrypt, encrypt all notes - also reduces the need for new admin/config fields
- A migration step will need to be considered, or a rolling encryption strategy (encrypt as the notes are edited)

**Comment by pachlava** [comment]
Thank you for the request @rj-xy ! In fact, adding encryption for notes (and also, optionally selecting individual notes for encryption) is one of our frequently requested features. I've just added one more vote based on your request to our internal features requests tracker, and will close your issue for that reason. It's on our radar, and our developers check with this list at the beginning of each sprint, however, we can't predict when exactly will it be implemented.
