### ISSUE TITLE
I can't login to my account

### ISSUE THREAD

**Issue by andreyferriyan** [Automattic/simplenote-electron#2975]
Suddenly simplenote cannot sync to multiple device. After logout I cannot login to simplenote Apps in my Windows. Try to uninstall and install got the same login problem. I try to login from app.simplenote.com... I terrified, really. All my notes are gone. 

### Expected

Synchronization should working across devices. Windows and Android phone. 

### Observed

Around two or three days ago, simplenote acting weird such as cannot sync to other device. 

### Reproduced

1. Uninstall and install again
2. Login
3. See error... "Could not log in with the provided email and password"

### Where did you see the bug

- System Make: 
- System Model: 
- OS: Windows
- OS version: 10
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.16

**Comment by codebykat** [comment]
Hi @andreyferriyan, can you please email us at support@simplenote.com so we can get some more details and help debug this issue? It's quite hard to debug account-specific problems on the public GitHub :) Thanks!
