### ISSUE TITLE
Allow tab key to indent

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#299]
In the Windows app the tab key changes focus to the tags fields. It would be better if the tab key let the user add an indentation to the note.

_Tracking Tickets_
- #2642910-t
- #2641835-t
- #2653851-t
- #2654072-t
- #2670773-t
- #2708420-t
- #2711658-t
- #2724788-t
- #2770231-t
  -  #2849381
- https://twitter.com/user/status/749495005866258432

**Comment by rachelsquirrel** [comment]
Another request - #2642910-t

**Comment by rachelsquirrel** [comment]
Another request - #2641835-t

**Comment by rachelsquirrel** [comment]
#2653851-t

**Comment by rachelsquirrel** [comment]
#2654072-t

**Comment by rkwnyc** [comment]
Same behavior in the Linux app, version 1.0.1.  Would be better if tab key worked the same as the web interface (i.e., as a 4-space indentation)

**Comment by kriskarkoski** [comment]
#2670773-t

**Comment by dcoleonline** [comment]
#2708420-t

**Comment by kriskarkoski** [comment]
#2711658-t

**Comment by KokkieH** [comment]
https://twitter.com/user/status/749495005866258432

**Comment by jerrysarcastic** [comment]
#2724788-t

**Comment by dmsnell** [comment]
just curious why are we listing the tickets here? don't we have a way to mark tickets as duplicates?

**Comment by jerrysarcastic** [comment]
@dmsnell great question. I had never seen a list of tickets links in a Github issue before this ticket, so doing what everyone else is doing.  To be fair I usually see this kind of thing happening over here:  https://simplenoteideas.wordpress.com/

**Comment by rachelsquirrel** [comment]
@dmsnell It helps us track how common an issue it is. Like we do here - https://github.com/Automattic/jetpack/issues/2051. 

It's true that most feature requests go to the p2 but this seems more significant.

**Comment by dmsnell** [comment]
@rachelmcr do you think we could use another method, such as adding thumbs'-ups or editing a single comment/the issue itself to indicate popularity?

From my perspective it's not helpful at all to have a bunch of comments because we're already aware of the issue and it's just a matter of being able to find the resources to dedicate to resolve it. Marking tickets as duplicates still tracks back to the original, no? So maybe we could use that when tracking popularity?

Anyway, we have different needs and different purposes for this, so it's just my opinion here. Thanks for all the work y'all do keeping things organized!

**Comment by rachelsquirrel** [comment]
I'm happy to edit the same comment or add a thumbs up, that's fine.

**Comment by catkit** [comment]
Not sure what to do, as I don't know how to marking tickets as duplicates so just pasting yet another request:
https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2770231

**Comment by balaziks** [comment]
Structured Markdown lists (IMHO killer Markdown feature) are impossible to use quickly and comfortably in the desktop apps due to the missing tab indentation.

**Comment by dmsnell** [comment]
to all fellow Automatticians working in this issue, I'd like to suggest that when we add tickets to the issue to track them that we edit a single comment (or the issue description) as I have done above. Feel free to add some thumbs-up as well to indicate priority or need. It will be much more helpful for us not having the huge list of comments.

by the way, I've pushed out a branch to fix this :wink:

**Comment by nfcampos** [comment]
@dmsnell this would be much easier to do once #370 is merged, in fact I've implemented it in another branch on top of that PR (see `NoteContentEditor#onTab` on https://github.com/nfcampos/simplenote-electron/tree/lists)

**Comment by seanzig** [comment]
One thing I do as a clunky work-around is to get a tab character in the clipboard and paste (Ctrl-V) it when I need it.  I use enough tabs in every note, and the autoindent feature from the Mac client keeps the tabs in there, that I have a tab character readily available to copy (Ctrl-C) in any note that I'm using.  The usability pales in comparison to the Mac client, but it's better than no tab at all.

**Comment by drw158** [comment]
This is fixed now right?

**Comment by dmsnell** [comment]
Yes! Thanks to the great work by @nfcampos we have tab and list auto-complete!
