### ISSUE TITLE
Could not log in with the provided email address and password (timeout on desktop app for Windows)

### ISSUE THREAD

**Issue by folmert** [Automattic/simplenote-electron#2996]
I've downloaded Simplenote for Windows at https://github.com/Automattic/simplenote-electron/releases/tag/v2.18.0, provided the same credentials as on web version (they work) and after a while Simplenote returns:

"Could not log in with the provided email address and password"

### Expected
Simplenote for Windows should log me in.
If it runs into timeout error message should be different - it shouldn't suggest incorrect address or password was provided, because they are in fact correct.

### Observed
Simplenote for Windows tries to connect for a long time and eventually times out (after ~30 seconds).

### Reproduced
1. Download latest version from https://github.com/Automattic/simplenote-electron/releases/tag/v2.18.0
2. Open app and log in
3. Logging in doesn't work

### Where did you see the bug

- OS: Windows 10 Pro
- Simplenote app version: v2.18.0 (for Windows)
- blocked port 25 (does it matter?)

Authenticating at web version works but it's not pulling any notes - it can't connect to server.

**Comment by codebykat** [comment]
Hi @folmert, if you're still having issues can you please contact support@simplenote.com? This sounds like you're unable to connect to the backend API for some reason. Closing this issue as we can't debug account issues on the public GitHub.
