### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#3009]
### Expected

***Notes are supposed to sync***

### Observed
***Notes are not synchronizing***

### Reproduced
Just a sync error. No new note is syncing.

### Where did you see the bug

- Simplenote app version: 2.19.0 (desktop and web) WINDOWS

[![Screenshot-000026-092121-085129-PM.jpg](https://i.postimg.cc/1zwH558x/Screenshot-000026-092121-085129-PM.jpg)](https://postimg.cc/zLDWxNwp)

**Comment by pachlava** [comment]
Thank you very much for the early notice @panwanarek! The fix will be available in Microsoft Store as soon as it's approved. Meanwhile, you can use the patch version [2.19.1](https://github.com/Automattic/simplenote-electron/releases/tag/v2.19.1) directly from GihHub.

**Comment by pachlava** [comment]
@panwanarek 2.19.1 with hotfix has also been deployed to the Web and approved in MS Store (might take some time for it to actually become available). The previously unsynced notes (as in your example) will still not sync, but the issue will not appear for the new notes. We’re sorry for the inconvenience. I'll close the issue, but feel free to reopen it if there's a need. 👋
