### ISSUE TITLE
"Review Your Account" Popup Not Going Away After Verification

### ISSUE THREAD

**Issue by fullbuffer** [Automattic/simplenote-electron#3010]
### Expected

After clicking confirm, going through the verification process, and getting the successful verification message from the app.simplenote.com website I expect the dialog to no longer show when I open the app.

### Observed

Every time I open the app, the popup shows as seen here:
![image](https://user-images.githubusercontent.com/18314290/134419595-4e4df5d3-c34b-41bf-97fb-e4ddcfb57bed.png)

### Reproduced

1. Open the app

### Where did you see the bug

- System Make: N/A
- System Model: N/A
- OS:  Ubuntu
- OS version: 21.04
- Browser (if applicable):  N/A
- Browser version (if applicable): N/A
- Simplenote app version: 2.19.1

**Comment by codebykat** [comment]
Hi @fullbuffer, this is one we've tried a few things to fix and we're still hoping to improve on the backend. In the meanwhile can you please try logging out of the app entirely (via Settings -> Logout, NOT simply closing and reopening the app) and let us know if that fixes the problem? It should get the app to sync up your account status. Sorry for the trouble.

**Comment by fullbuffer** [comment]
Hi @codebykat, no problem at all. When I get back to my desk later tonight or tomorrow I’ll give it a shot and post a reply on here with the results.

**Comment by fullbuffer** [comment]
Hi @codebykat, logging out and logging back in seems to have fixed the issue with the popup.  Thanks for you help!

Closing this issue.
