### ISSUE TITLE
Delete all notes

### ISSUE THREAD

**Issue by hoangpx** [Automattic/simplenote-electron#3011]
I accidently imported 2 times all of my notes from Notion (about 300 notes). Is there any quick way to delete all of the notes? Like select all or delete database?

**Comment by pachlava** [comment]
@hoangpx Simplenote for iOS allows selecting all notes and deleting them, as well as Simplenote for native macOS. In Simplenote for Android, it's possible to multiselect, but it has no `Select All` option.
