### ISSUE TITLE
PWA uses so much RAM

### ISSUE THREAD

**Issue by chromer030** [Automattic/simplenote-electron#3016]
### Expected

Normal memory footprint
### Observed

High amount of RAM usage , growing in number and finally when reached at a large number, app will freeze and needs to force close.
### Reproduced

1. Use Simplenote as PWA in chrome
2. after a while look at memory usage
3. When reaches at more than 2 GB app will freeze

### Where did you see the bug

- OS: Linux
- OS version: Arch
- Browser : Google Chrome 
- Browser version : 94
- Simplenote app version: latest web app

![Screenshot_20210926_071629](https://user-images.githubusercontent.com/13361552/134794782-735bacb5-41ef-45d3-bbb0-9a635de15f7a.jpg)

**Comment by chromer030** [comment]
Seems that it's about JavaScript :

![Screenshot_20211005_153331](https://user-images.githubusercontent.com/13361552/136033864-d61d17d2-8f42-46a4-81cb-09a28625e657.jpg)

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
