### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by RickyCox** [Automattic/simplenote-electron#3032]
I’m just a regular user of Simplenote, not a dev.
I love the app, and use it multiple times a day. But I'm frustrated that my work gets interrupted much too often with new update notifications.
Looking at the change logs, updates often appear to consist of minor improvements that would wait till the next significant release. If it ain’t broke . . .  I’d suggest a more disciplined approach, that only offers significant updates on a regular cycle would be more helpful, unless there are serious bugs that need fixing asap. 4 times a year would be about right for me.
anyone else feel like me?

**Comment by codebykat** [comment]
Thanks for the comment. Closing as fixed, I suppose. https://github.com/Automattic/simplenote-electron/issues/3080#issuecomment-1053929475
