### ISSUE TITLE
iHD_drv_video.so init failed

### ISSUE THREAD

**Issue by VitalyYakunin** [Automattic/simplenote-electron#3034]
OS: Kubuntu 21.10
CPU: Intel i3-2370M
GPU: Intel HD 3000

Start in Terminal:

$ /opt/Simplenote/simplenote %U
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[7316:1008/112025.972015:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

**Comment by VitalyYakunin** [comment]
$ ls /usr/lib/x86_64-linux-gnu/dri/
d3d12_dri.so  i965_dri.so        iris_dri.so        nouveau_drv_video.so  r300_dri.so        radeon_dri.so          swrast_dri.so      zink_dri.so
i830_dri.so   i965_drv_video.so  kms_swrast_dri.so  nouveau_vieux_dri.so  r600_dri.so        radeonsi_dri.so        virtio_gpu_dri.so
i915_dri.so   **iHD_drv_video.so**   nouveau_dri.so     r200_dri.so           r600_drv_video.so  radeonsi_drv_video.so  vmwgfx_dri.so

**Comment by VitalyYakunin** [comment]
I removed version 2.20.0 and installed 2.10.0. There are no errors.

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
