### ISSUE TITLE
libva error on fedora 35

### ISSUE THREAD

**Issue by bozkurtovski** [Automattic/simplenote-electron#3039]
hi. i use simplenote for my notes. i se fedora linux 35, but i cant open simplenote. i use simplenote for fedora/ red hat package, rpm. i have a electron problem i think.
its my command line output when i start simplenote:
[bozkurtovski@fedora Simplenote]$ ./simplenote 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2909:1031/232304.944380:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
İzleme/kesme noktası yakalayıcı (core dumped)

i tried to reinstall simplenote but it cant fix it.

### Expected

i wanna fix my problem. but i dont know how to fix.
### Observed

its electron problem, or nvidia problem.
### Reproduced

[bozkurtovski@fedora Simplenote]$ ./simplenote 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2909:1031/232304.944380:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
İzleme/kesme noktası yakalayıcı (core dumped)
1.
2.
3.

### Where did you see the bug

- System Make: AMD FX 6300 65 bit/NVIDIA 560 Ti 448 Cores/ MSI 760GM P23 AM3 Motherboard
- System Model: Desktop PC
- OS: Fedora Linux
- OS version: 35
- Browser (if applicable): Firefox
- Browser version (if applicable): 93
- Simplenote app version: 2.21.0

**Comment by PinkFrosty** [comment]
I'm seeing the GPU error on F35 KDE Plasma spin. I've upgraded my Simplenote to the latest, 2.21.0 via RPM.

Simplenote  $ ./simplenote 
[15450:1107/091026.488475:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
[1]    15450 trace trap (core dumped)  ./simplenote

Where did you see the bug
System Make: MSI Prestige 14 evo A11M - 11th Gen Intel(R) Core(TM) i7-1185G7 - 16G RAM - 1TB nvme - Intel Iris Graphics
System Model: Laptop
OS: Fedora Linux
OS version: 35
Browser (if applicable):  Not applicable since I'm running the rpm version.
Browser version (if applicable): N/A (Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit))
Simplenote app version: 2.21.
[simplenote_strace.txt](https://github.com/Automattic/simplenote-electron/files/7492614/simplenote_strace.txt)
0

**Comment by petrstepanov** [comment]
I am experiencing the same issue

**Comment by martonlente** [comment]
Hello,


I'm having the same issue on my laptop with Fedora 35, on Ryzen 3 3250u with Radeon vega 3 graphics. The interesting thing though, that Simplenote starts the first one/two times, but if I close it, it no longer launches. When it doesn't start, it gives the following error in Terminal:
`[3803:0309/132319.399835:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.`

Do you have any ideas why this happens, or are there any updates to this major issue?


Update: The above applies if I install the app from [Simplenote-linux-2.21.0-x86_64.rpm](https://github.com/Automattic/simplenote-electron/releases/download/v2.21.0/Simplenote-linux-2.21.0-x86_64.rpm) . If I install the app using Flathub (Flatpak), than it perfectly and consistently works. Still it'd be nice to  use the RPM instead.


Thank you in advance,
Márton Lente

**Comment by crsesilva** [comment]
> Hello,
> 
> I'm having the same issue on my laptop with Fedora 35, on Ryzen 3 3250u with Radeon vega 3 graphics. The interesting thing though, that Simplenote starts the first one/two times, but if I close it, it no longer launches. When it doesn't start, it gives the following error in Terminal: `[3803:0309/132319.399835:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.`
> 
> Do you have any ideas why this happens, or are there any updates to this major issue?
> 
> Update: The above applies if I install the app from [Simplenote-linux-2.21.0-x86_64.rpm](https://github.com/Automattic/simplenote-electron/releases/download/v2.21.0/Simplenote-linux-2.21.0-x86_64.rpm) . If I install the app using Flathub (Flatpak), than it perfectly and consistently works. Still it'd be nice to use the RPM instead.
> 
> Thank you in advance, Márton Lente

Just faced the same issue today, here's the "fix"

The "fix" applies if install the app from Simplenote-linux-2.21.0-x86_64.rpm.

Edit the file /usr/share/applications/simplenote.desktop, appending a --no-sandbox into the Exec command

Before Exec=/opt/Simplenote/simplenote %U | After: Exec=/opt/Simplenote/simplenote --no-sandbox %U

Enjoy it :)

**Comment by tuxedotje** [comment]
Same problem  on Fedora 37, same solution

**Comment by Antidote00** [comment]
Same problem on Fedora 38, same solution

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
