### ISSUE TITLE
Enable access to developer tools

### ISSUE THREAD

**Issue by dhry** [Automattic/simplenote-electron#3041]
Would like to know if we can enable access to the Chrome Developer Tools feature.

### What
Could we have the Chrome Developer Tools menu enabled - not by default (per issue #206 I guess), but perhaps specifically with a command line parameter used when starting, or a system environment variable (such as Slack's SLACK_DEVELOPER_MENU=true).

### Why
Would like to enable the tools to fiddle with the layout of Simplenote, change the font, line height, padding between items in the list column, color scheme etc.

### How
For example:
1. Add SIMPLENOTE_DEVELOPER_MENU system environment variable sensing, true enables the feature
2. Start Simplenote.
3. View - Developer - Toggle DevTools option appears.
4. Can also now use the ctrl-alt-I hotkey to pop up devtools window

I know this was enabled before and issue #206 requested it be removed. I'd like to use it but it doesn't need to be enabled by default.

**Comment by codebykat** [comment]
Hi @dhry, you should still be able to access the console under Help -> Advanced -> Debugging Console. There's not a shortcut key or any way to open it by default, but the app might remember and re-open it if you had it open the last time you closed it. Hope this helps!
