### ISSUE TITLE
Broken error message structure on Signup page.

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-electron#3043]
### Expected
It's expected that anchor tags are rendered correctly in error messages.

### Observed
User provided this screenshot via 4438339-zd-woothemes:

![Screenshot_2021-11-09 15 19 08_Uc77r8](https://user-images.githubusercontent.com/73365754/140931301-a4667301-15aa-4e60-bcea-cd05473d46e4.png)

### Reproduced
I'm not entirely sure how it is possible to get to this error. I think it happened after the user clicked the signup link, created a password, but still stayed on the signup form (how?), and tried to log in.

### Where did you see the bug

- Browser: Safari on unspecified iPhone

**Comment by codebykat** [comment]
I believe we fixed this awhile ago as part of the backend upgrade, re-open if I'm wrong please :)
