### ISSUE TITLE
Remove dependency on gconf2

### ISSUE THREAD

**Issue by dimitry-ishenko** [Automattic/simplenote-electron#3048]
### What

Replace gconf2 with dconf.

### Why

gconf2 is deprecated.

From wikipedia:

> GConf was a system used by the GNOME desktop environment for storing configuration settings for the desktop and applications. It is similar to the Windows Registry.
> 
> It was **deprecated** as part of the GNOME 3 transition. Migration to its replacement, GSettings and dconf, is ongoing.

From [https://gitlab.gnome.org/Archive/gconf](https://gitlab.gnome.org/Archive/gconf):

![Screenshot from 2021-11-25 21-54-45](https://user-images.githubusercontent.com/2858291/143519944-0ee7944d-4456-42e7-b49f-288beae83f68.png)

### How

By modifying the code to use dconf instead of gconf2?... Yep.

**Comment by dimitry-ishenko** [comment]
FWIW it seems whatever the thing that `Simplenote` is built on, which used to require `gconf2`, no longer needs it.

In other words, I was able to install both `Simplenote-1.21.1` and `Simplenote-2.21.0` (one at a time) with:
```shell
dpkg -i Simplenote-linux-...-amd64.deb
```
and they both worked fine without `gconf2` being installed on my system.

Not sure if whatever that thing was that needed it (_electron_, or _chromium_, or whichever), has since switched to `dconf` or just altogether doesn't need it anymore.

**Comment by codebykat** [comment]
Thanks, yeah, looks like [Electron has removed the dependency](https://github.com/electron/electron/pull/19498).

**Comment by dimitry-ishenko** [comment]
When was this completed? Latest Linux version (2.21.0) still depends on gconf2.
