### ISSUE TITLE
Remember session settings when app is closed

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#305]
When the app is closed and reopened it would be good if the window size and the note which was previously open are returned by default.

**Comment by rachelsquirrel** [comment]
#2672167

**Comment by KokkieH** [comment]
Another request for this in https://twitter.com/glauer42/status/743086090542800896

**Comment by kriskarkoski** [comment]
#2711658-t

**Comment by ruppalsingh** [comment]
Having the same issue. Electron client on both Windows and Linux acts in the discussed manner. Would love a quick fix.

**Comment by diazbastian** [comment]
I really like to take advantage of Simplenote responsive interface and sometimes becomes annoying to have to adapt the interface again and again. Thank you.
![simplenote](https://cloud.githubusercontent.com/assets/5126124/17846121/077ad914-681d-11e6-9be9-3724f4979593.png)

**Comment by fayad** [comment]
Thanks for the fix. Can you update the deb package.

**Comment by dmsnell** [comment]
@fayad we don't really have a fix quite yet. @arshsingh has put together a pull request to include this functionality, but we are waiting to see if we can make a few changes to that patch before we merge it in. we're all very excited to persist the window size :smile:
