### ISSUE TITLE
since v2.13, cannot work in deepin linux 

### ISSUE THREAD

**Issue by hetian127** [Automattic/simplenote-electron#3050]
my OS is deepin linux, base on debian.

I installed all the version above 2.12, the app cannot work, messages shows:
2021-11-29 16:48:13 xxx-UOS kernel: [ 5064.975911] traps: simplenote[29350] trap int3 ip:559477bd3c68 sp:7fff2cd905c0 error:0 in simplenote[5594779a4000+626b000]

v2.12 works fine.thanks a lot!

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
