### ISSUE TITLE
Verification email never turns up from multiple linux systems

### ISSUE THREAD

**Issue by pnunn** [Automattic/simplenote-electron#3054]
I have two kdeneon systems with simplenote installed. One of them lets me in to simple note but keeps complaining about the verification email being needed (it was set up while I had simplenote on a windows system), the second one is that ex-windows system and I can't get into simplnote at all, either with the app or via the web, because it requiires the verification email, but it never turns up from either system.

### Expected
Verification email arrives

### Observed
It never arrives.

### Reproduced
1. Try to log into simple note
2. Click on 'Send Verification Email'
3. Web page opens to say email has been sent.
4. It never turns up.

### Where did you see the bug

- System Make: Dell laptop (no idea why this is relivant)
- System Model:
- OS: Linux
- OS version: KDE Neon
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.21.0

**Comment by codebykat** [comment]
Hi @pnunn, please send an email to support@simplenote.com so that we can get your account verified! We can't debug account-related issues on the public GitHub :)
