### ISSUE TITLE
Clicking Menu Bar Crashed the Linux app

### ISSUE THREAD

**Issue by erricgunawan** [Automattic/simplenote-electron#3058]
Upon clicking in the menu bar, the following error occurs in the Linux desktop app:

![image](https://user-images.githubusercontent.com/1813857/147088170-a526babf-838b-45f0-a543-35601d374656.png)

User confirmed this is not a network connection issue, since they don't experience the issue on https://app.simplenote.com/ 

Report from 4601941-zen

### Expected

Menu bar should open the menu, like in the web app. 

### Observed

It crashed as in the screenshot above.

### Reproduced

1. Use the Simplenote app on Linux.
2. Click on the menu bar.
3. See the error as in the screenshot above.

### Where did you see the bug
- OS: Linux
- OS version: Pop!_OS 21.04 
- Simplenote app version: 2.21.0

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
