### ISSUE TITLE
Keyboard shortcut for toggling markdown preview

### ISSUE THREAD

**Issue by EJOweb** [Automattic/simplenote-electron#306]
Adding a keyboard shortcut for switching from markdown to preview and vice versa would be nice. Maybe CTRL + M(arkdown) or something?

**Comment by prat0088** [comment]
CTRL+M would be great.

**Comment by sambody** [comment]
In the desktop app, Ctrl+M is already used to minimize the desktop app (Windows 10). 

And in the web version on Firefox, Ctrl+M is used to mute the current page. So it will probably have to be another shortcut.

**Comment by prat0088** [comment]
Ok. As long as it gets a shortcut I'm happy.

**Comment by jcrben** [comment]
Ideally keyboard shortcuts are configurable.

**Comment by guilsa** [comment]
Why not treat Edit/Preview like browser tabs, so switching between them can be Cmd + Shift + [ OR ]

**Comment by dmsnell** [comment]
How do y'all feel about making it a kind of print-preview shortcut like <kbd>CmdOrCtrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>?

Candidates:
 - <kbd>CmdOrCtrl</kbd> + <kbd>M</kbd> already mentioned that it is used
 - <kbd>CmdOrCtrl</kbd> + <kbd>[</kbd> it doesn't really feel like browser tabs, and I don't think we need two keys whereas a toggle feels right. Further, if we decide to open a live preview on wide displays I think the single-key toggle would fit better with "open or close preview."

@drw158 do you like this idea?

**Comment by drw158** [comment]
That idea sounds great to me. `p` as in `preview` or `p` as in `print`. Easy to remember.

**Comment by dmsnell** [comment]
Closing here as a duplicate of #37 - check back soon for an update in v1.0.9!
