### ISSUE TITLE
Fix Windows 10 start menu tile icon

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#3061]
Hi,
Windows 10 start menu small tile icon is too small, please fix it.
![image](https://user-images.githubusercontent.com/23485114/148117790-53c5b17a-80da-4b8f-bb30-951360a4a068.png)

**Comment by codebykat** [comment]
Thanks for the report! Looks like a duplicate of #3057.

**Comment by xmha97** [comment]
> Thanks for the report! Looks like a duplicate of #3057.

#3057 is a taskbar issue but
#3061 is a start menu issue.
They are similar but they are not an issue.
