### ISSUE TITLE
Run Simplenote with different profiles

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#3062]
### What

Run Simplenote with different profiles.

### Why

Because I want to make a portable version of Simplenote.

### How

```
simplenote.exe --profile-directory="X:\SimplenoteProfile"
```
Using this command, I can create a special shortcut to launch Chrome with a different profile.

**Comment by codebykat** [comment]
Thanks for this suggestion! It's not something we are likely to prioritize, as you can run separate instances of Simplenote (e.g. log in on the app and a browser, or two different browsers). But I have noted your suggestion in our feature requests for future consideration.
