### ISSUE TITLE
Release on PortableApps.com

### ISSUE THREAD

**Issue by xmha97** [Automattic/simplenote-electron#3068]
Having portable apps is a huge request from users who hop on different machines regularly. This enables them to install the apps once on an external drive and use it across machines and user accounts and all the app data will be available in the installed location.

This enables:
- Install once and use it everywhere.
- Take your work anywhere you go.
- Better backup of apps and their data.
- Other advantages of portable apps: https://portableapps.com/about/what_is_a_portable_app

Please make a portable version and release it on PortableApps.com
https://github.com/PortableApps/Platform/issues/5

**Comment by xmha97** [comment]
I created a Portable version of the Simplenote app,
You can download SimplenotePortable:
https://github.com/xmha97/PortableApps/releases/tag/Simplenote-v2.21

**Comment by codebykat** [comment]
Thanks for the suggestion, @xmha97. We're unfortunately not able to commit to maintaining packages on the wide variety of package management ecosystems out there. I'm closing this as "won't fix" but it will still turn up in a search of issues in case it is of interest to others.

In particular, I'm not sure what the utility of portable apps is for Simplenote, which is already a packaged (Electron) version of the web app available at https://app.simplenote.com . I believe you could accomplish the same by simply copying the executable to a USB drive. But at any rate, this will be here if anyone else needs it.

**Comment by passionate2023** [comment]
@xmha97 Can you please create one portable version and add the link to download for the latest version?

**Comment by xmha97** [comment]
> @xmha97 Can you please create one portable version and add the link to download for the latest version?

https://github.com/xmha97/PortableApps/releases/download/Simplenote-v2.21/SimplenotePortable_2.21_English.paf.exe
