### ISSUE TITLE
Add an option set new notes as markdown by default

### ISSUE THREAD

**Issue by jrcacd** [Automattic/simplenote-electron#3069]

**Comment by codebykat** [comment]
Hi @jrcacd! The app should automatically use the last setting, so if you have been working with Markdown notes, new notes should in fact default to Markdown. Let us know if that's not working properly for you.

**Comment by jrcacd** [comment]
Okay. didn't know. Therefore, it was implemented in a very intelligent and practical way.
Excellent!
