### ISSUE TITLE
Please, I beg you fix the sync issues. It's been broken for years now. I'm dying inside. Everyone is losing data, nobody wants to resolve merge conflicts with their note app.

### ISSUE THREAD

**Issue by slothentic** [Automattic/simplenote-electron#3075]
Simplenote fails to sync constantly. Like almost daily I see a note that just hangs forever, indefinitely and fails to ever sync. Since the version released a few years ago it has just remained broken. I suspect your logic around window reactivation is faulty and perhaps not idempotent, its reproducible on every platform (Android, iOS, Web and Desktop) for multiple years, multiple networks, numerous devices, multiple accounts, so it's a core issue with your main functionality.

I evaluated every single app on the market, yours is by a wide margin superior except for this single issue. It's unbearable to use with the current problem.

And I know since you're a bunch of developers your instinct will be to assume I'm an idiot and I'm wrong and your app is perfect and there are no bugs. You're wrong. There is nothing exceptional about my use case. I'm a Cordova dev, your app is lovely, but also horrendously broken, just fix it already 🙏

Keep up the great work! ❤️

**Comment by codebykat** [comment]
Hi @slothentic, I'm sorry to hear you're having such trouble syncing! This is not an issue that is widespread or that we are able to personally reproduce, so I'm wondering if there's something specific to your account, the content of your problem notes, or perhaps the location you're using the app from. Could you drop us a line via support@simplenote.com so we can look at your account details and try to get to the bottom of it? If you're able to reproduce this consistently (which it sounds like you are), it would be a huge help to send along the reproduction steps as well. Cheers :)

p.s. I LOLed at the "assume your app is perfect and there are no bugs" line. As a developer I personally assume there are bugs lurking everywhere, in every piece of software, actually. 😂

**Comment by slothentic** [comment]
Well sounds like you're a good developer if you're paranoid and care to
hear about gremlins lurking in your codebase. It's been on numerous
devices, all platforms over many years, syncing in either direction from
web to desktop or vise-versa. Deleted my account out of frustration, tried
every other note app (they're all garbage btw), came back a year and half
later with a brand new account.... STILL has the freaking issue. Has
happened on multiple continents, countries, states, devices, platforms...
it's ubiquitous, but perhaps transient and difficult to isolate, however,
extremely consistent from my perspective, I practically expect it now. As
far as I can tell I really don't do anything exceptional or power-usery in
your app. Sorry mate, I know that is zero help, but it's a real thing, and
I would love to just love your app. Best of luck.

**Comment by codebykat** [comment]
Closing for lack of reproduction steps.
