### ISSUE TITLE
simplenote mobile browser side can not paste the content (ctrl + v)

### ISSUE THREAD

**Issue by sixgodfan** [Automattic/simplenote-electron#3082]
simplenote mobile browser side can not paste the content (ctrl + v)

simplenote 手机浏览器端无法粘贴内容（ctrl+v）

**Comment by codebykat** [comment]
Yes, sorry about that, these shortcuts aren't fully supported within the mobile editor (as are many other things). This is because our underlying text editor, Monaco, doesn't have full mobile support. We recommend installing the native app on mobile, instead.

(Duplicate of #2388)
