### ISSUE TITLE
Sync Issues Part 2 (now with details/maybe smoking gun)

### ISSUE THREAD

**Issue by slothentic** [Automattic/simplenote-electron#3084]
Original gripes here: https://github.com/Automattic/simplenote-electron/issues/3075

I don't have exact repro steps, but I do have an actual lead, and its sort of what I suspected it would be:

![Screen Shot 2022-03-11 at 10 21 22 AM](https://user-images.githubusercontent.com/821287/157896683-dda09ac0-b07d-442a-a8df-a2db7f6d6c66.png)
.

It looks like once the websocket connection dies, it never comes back. I've had a similar kind of issue with Pusher before where it gives up trying once its exhausted some kind of fixed limit of retry attempts (called "lives" on Pusher).

I can confirm once the app enters this state, no new notes will sync, and the app is basically stuck offline until you restart it. My suspicion is that leaving the app open for an extended period of time where your internet goes off and on repeatedly causes it to trigger some kind of fixed internal limit of how many times it's going to connect, and would never been seen in manual testing.

A possible unit test could be doing a connect/disconnect in a loop until it triggers the condition, or more gracefully handling the re-connected status to forcibly reconnect regardless of limits.

Here is approximately where the problem lives:
![Screen Shot 2022-03-11 at 10 31 26 AM](https://user-images.githubusercontent.com/821287/157897956-7d96807a-410c-4ed9-b8c4-69af0c936e45.png)
 
Hope this can help get to the bottom of it, good luck!

**Comment by dougaitken** [comment]
@slothentic Are you using Chrome v100 by any chance? If you have other web browsers installed, can you try Simplenote on them, please? 

If you are using Chrome 100, can you try this? Head to `chrome://flags/#force-major-version-to-minor` and then change this to **Enabled**. Restart your browser and the Simplenote web-app will work. 

Let me know how you get on!

**Comment by slothentic** [comment]
@dougaitken that was on the Mac desktop app (2.21.0), not on browser.

Just checked it out here:

![Screen Shot 2022-03-30 at 4 29 09 PM](https://user-images.githubusercontent.com/821287/160925375-1e7200bb-48ff-4ba7-b574-df5d436934ed.png)

**Comment by dougaitken** [comment]
Ah! Thanks for letting me know @slothentic 

The server team have made a tweak related to the bug I was referring to, I'm wondering if this has fixed this for you. Can I ask you to quit and reopen the Simplenote app to see if this helps?

**Comment by slothentic** [comment]
Awesome thanks for checking. Restarted the app, and synced up on the first try, will open another issue if the problem recurs.
