### ISSUE TITLE
Linux on Wayland/Gnome: Blurry on HiDPI displays or sans window decorations, improved on Electron 17+

### ISSUE THREAD

**Issue by seltzered** [Automattic/simplenote-electron#3088]
### Expected
Simplenote-electron, like many other Electron based apps, appears blurry on HiDPI displays under Linux with Gnome on Wayland, or likely appears without a titlebar when trying to use `--ozone-platform=wayland`

Electron 17 and later addresses this https://github.com/electron/electron/pull/29618 such that at the least one can use `--ozone-platform=wayland --enable-features=WaylandWindowDecorations` to make things work. 

### Observed
On Linux (with Gnome, Wayland) with a HiDPI display, observe after launching Simplenote that display is blurry in appearance.   

### Where did you see the bug
- OS: Ubuntu 
- OS version: 21.10
- Simplenote app version: 2.10.0 , but checked to see electron version in main branch is currently 12.x

**Comment by codebykat** [comment]
Electron has been upgraded in #3183, please re-open if this is not addressed.
