### ISSUE TITLE
Enable Github-flavoured Markdown

### ISSUE THREAD

**Issue by eblade** [Automattic/simplenote-electron#309]
Given how I assume this app is built (not too familiar with Electron, but it looks web-ish to me), would it be possible to use for instance this renderer [marked](https://github.com/chjj/marked) to enable Github-flavoured Markdown (GFM). The main feature for me would be syntax highlighting for a number of languages.

**Comment by roundhill** [comment]
We're already using `marked`, so I think we just need to enable the gfm option 👍

**Comment by MJIO** [comment]
+1 on syntax highlighting support.

Are there plans to also enable Markdown for the OSX application?

**Comment by rnewton** [comment]
According to the readme and the code, marked has gfm enabled by default. https://github.com/chjj/marked/blob/master/lib/marked.js#L1242

To get syntax highlighting, you need to add another library like https://github.com/isagalaev/highlight.js

**Comment by dmsnell** [comment]
Will be resolved when #309 merges.

**Comment by eblade** [comment]
Looking forward to it!

**Comment by geekpete** [comment]
GFM seems to work for me by wrapping code in ``` backticks.

This displays fine in the electron based client preview but breaks in the web version preview.

Can we get the web version to have parity with this feature?

**Comment by rachelsquirrel** [comment]
A request in #3241877-t for Fountain script (https://fountain.io/), which is a markup language for writers.

**Comment by dmsnell** [comment]
This should have been fixed in the rollout of the `showdown` renderer in #577.
