### ISSUE TITLE
Support having multiple accounts

### ISSUE THREAD

**Issue by nsrosenqvist** [Automattic/simplenote-electron#310]
It would be awesome if the Simplenote could support having multiple accounts that can easily be switched between. A simply way to integrate it in the UI would be to just have the user icon in the corner of the toolbar and on click have a drop down appear with all authorized accounts.

**Comment by dmsnell** [comment]
@nsrosenqvist thanks for the suggestion! this is not a priority of ours right now but it would fit into some work @drw158 has proposed working with the account settings in #237 and also with the work in adding native tray support in #362. At this point in time I'm going to close this issue but will continue to keep it in mind when we work on those other PRs. Thanks again!

**Comment by ChrissiePollock** [comment]
This is also requested in #4730759-zen.
