### ISSUE TITLE
Request update on ubuntu app store

### ISSUE THREAD

**Issue by songsammy** [Automattic/simplenote-electron#3100]
### What
I am wondering whether you can update the package hosted on ubuntu app store.  The current version there is 2.10.0, which falls behind.
### Why
When we talk about linux pc, chances are high that (s)he is using ubuntu, PLUS that most if not all linux system supports snap packages.
### How
On https://snapcraft.io/ , stroll down a bit, and you can see the benefits.  
On https://snapcraft.io/docs/electron-apps there's a specific instructions on how to pack an electron project.  
It claims on the homepage that it takes only 30mins.

**Comment by songsammy** [comment]
and why the package maintainer is snapcrafters not automatic?

**Comment by codebykat** [comment]
Unfortunately, we don't currently have the resources to package the app for every different app store. Those "only 30 minutes" tend to add up 😓  You can always download the latest Linux build from the releases on this repository.
