### ISSUE TITLE
Markdown not rendering

### ISSUE THREAD

**Issue by notklaatu** [Automattic/simplenote-electron#3102]
Running 2.21.0, I write in markdown but I see no Markdown preview or render. 

I'm running the Electron client on Linux.

I do have Markdown enabled.

![Screenshot_centos-stream9_2022-07-13_14:42:41](https://user-images.githubusercontent.com/2211671/178639929-0740a514-50f5-4680-9147-9d48b12845b9.png)

**Comment by Erudition** [comment]
hit the eye icon.
