### ISSUE TITLE
Note not syncing to other device after 24 hours

### ISSUE THREAD

**Issue by Bluto39** [Automattic/simplenote-electron#3104]
### Expected
 I created a simple note on a win10 desktop.

### Observed
  It is not found on my android device logged into same simplenote account after 24 hours

### Reproduced

1. create note on win 10 platform with simplenote
2. not  found on android platform running simplenote logged into same simplenote account
3.

### Where did you see the bug

- System Make: Asus
- System Model: k17a
- OS: win 10
- OS version: 21H1 OS build 19043.1645
- Browser (if applicable): n/a
- Browser version (if applicable): 
- Simplenote app version: 2.23 (148)

**Comment by observerobserver** [comment]
mine worked fine until a few days ago, all syncing has stopped

**Comment by Atomk** [comment]
I have the same issue, it looks like the developers are working on a fix for the Android app - https://github.com/Automattic/simplenote-android/issues/1548

**Comment by AdrX003** [comment]
Same issue, thankfully it seems its being worked on. Since i had alot of edits on both devices Ill just export my notes from both and compare.

**Comment by cereby** [comment]
Windows app can soon sync app.simplenote.com, but Android cannot.
Even after I performed a clean installation of Android's app.

-> Working fine now.

**Comment by joashrajin** [comment]
+1 at 5861090-zd-woothemes

Seems to be specifically happening on the Windows 10 app

**Comment by gubrist** [comment]
It happens again (for days).

**Comment by codebykat** [comment]
I think these are temporary issues that got resolved, but if anyone is still having problems with notes not syncing, please contact us [directly](https://simplenote.com/contact/). We can't troubleshoot issues specific to an individual account on the public GitHub.

**Comment by gubrist** [comment]
It happens again (for days).

**Comment by gubrist** [comment]
It happend again (for days).

Nasty is: 
some notes are synchronized normally whereas others are not.

And it happens on different Android devices independently:
- Samsung Galaxy S21 and 
- Samsung Galaxy A55 (brand new)

**Comment by gubrist** [comment]
> I think these are temporary issues that got resolved.

No, it is still happening.
