### ISSUE TITLE
Simplenote fails to start after upgrading from Ubuntu 21.10 to 22.04

### ISSUE THREAD

**Issue by rmappleby** [Automattic/simplenote-electron#3106]
### Expected

I have used Simplenote on my laptop, android phone and iPad for a couple of years. I expected Simplenote to operate as normal after the Ubuntu upgrade on my laptop.

### Observed

After the upgrade of Ubuntu, Simplenote failed to start. I assumed something had gone amiss during the Ubuntu upgrade, so I purged Simplenote, and reinstalled with a fresh download of the latest Simplenote-linux-2.21.0-amd64.deb. Simplenote still failed to start. At this point I tried running the executable directly from the command line (ie, ./opt/Simplenote/simplenote) which resulted in the error:
```
[15270:0724/194952.519449:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```
This same result was observed under both Wayland and X. From some browsing on the internet, this seems to be a problem with Electron. There are various suggestions regarding workarounds to disable hardware acceleration. Adding "--disable-gpu-sandbox" to the Simplenote command line seems to allow Simplenote to start up normally. This can also be added to the relevant stanza in /usr/share/applications/simplenote.desktop

### Reproduced

1. Click on the Simplenote icon, or start from the commandline with ./opt/Simplenote/simplenote

### Where did you see the bug

- System Make: HP
- System Model: Probook 430 G8
- OS: Ubuntu
- OS version: 22.04 with Gnome
- Browser (if applicable): n/a 
- Browser version (if applicable): n/a 
- Simplenote app version: linux-2.21.0-amd64

**Comment by billybhaub** [comment]
Same problem here.
using "--disable-gpu-sandbox" to the launch command solves the problem.

**Comment by ialobanov** [comment]
Same problem. 
> using "--disable-gpu-sandbox"

don't work for me:

#simplenote --disable-gpu-sandbox
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/simplenote_Simplenote.desktop"
(simplenote:35668): Gtk-WARNING **: 23:09:25.818: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name
(simplenote:35668): Gtk-WARNING **: 23:09:25.826: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name
(simplenote:35668): Gtk-WARNING **: 23:09:25.827: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
Trace/breakpoint trap (core dumped)
Ubuntu 22.04.1 LTS.
Simplenote installed from snap.

**Comment by rmappleby** [comment]
> Same problem.

I think you have a different problem. Your error (Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/simplenote_Simplenote.desktop") gives you a place to start looking. I'd start by finding where the snap really has put the desktop file for simplenote and see if it matches the location in the error message. Also check permissions. Maybe a packaging error in the snap version?

**Comment by ialobanov** [comment]
Today I installed successfully Simplenote from Snap on fresh installation of Ubuntu, but before snap-installation I tried to install from deb package with dpkg and apt, however Simplenote failed to start.

**Comment by lapisdecor** [comment]
> > Same problem.
> 
> I think you have a different problem. Your error (Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/simplenote_Simplenote.desktop") gives you a place to start looking. I'd start by finding where the snap really has put the desktop file for simplenote and see if it matches the location in the error message. Also check permissions. Maybe a packaging error in the snap version?

I went to the error location on this one and the desktop file is named with 's' instead of 'S':  'simplenote_simplenote.desktop'.
I changed the filename using sudo to 'simplenote_Simplenote.desktop' and let the snap update the changes. That error is gone but I had to add the program to favorites again.

**Comment by rmappleby** [comment]
> > > Same problem.
> > 
> > 
> > I think you have a different problem. Your error (Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/simplenote_Simplenote.desktop") gives you a place to start looking. I'd start by finding where the snap really has put the desktop file for simplenote and see if it matches the location in the error message. Also check permissions. Maybe a packaging error in the snap version?
> 
> I went to the error location on this one and the desktop file is named with 's' instead of 'S': 'simplenote_simplenote.desktop'. I changed the filename using sudo to 'simplenote_Simplenote.desktop' and let the snap update the changes. That error is gone but I had to add the program to favorites again.

So sounds like a snap packaging error - maybe worth raising with them at https://github.com/snapcrafters/simplenote/issues ?

**Comment by amatus-** [comment]
> Same problem here. using "--disable-gpu-sandbox" to the launch command solves the problem.

Fixes a problem on my laptop.

**Comment by opsaaaaa** [comment]
hay thanks @rmappleby 

`--disable-gpu-sandbox` worked for me.

**Comment by rcrx** [comment]
> Same problem here. using "--disable-gpu-sandbox" to the launch command solves the problem.

This worked on Linux Mint 21

**Comment by bkosowski** [comment]
I have the exact same issue, but on Manjaro Linux (Arch-based). And yes, the `--disable-gpu-sandbox` is a functional workaround.

**Comment by Thorny-Twig** [comment]
Had same problem running my desktop version of Simplenote v2.21.0 (.deb installed package) after upgrade to Ubuntu's "Jammy Jelly" version 22.04.01. I just ran `/opt/Simplenote/simplenote %U --disable-gpu-sandbox` in the default GNOME CLI Terminal and I got it working that way. Hope this helps the Ubuntu 22.04 users that have above issue starting up Simplenote desktop version.

**Comment by cwwees** [comment]
I finally spent the time to get an AppImage to run - from command line I got the same error message. From the command line, I can add the "--disable-gpu-sandbox" and it works. Thanks for the pointer.

**Comment by irfaanz** [comment]
I am having the same issue but --disable-gpu-sandbox it works but I am trying to add this into start up application on Mint Vanessa. Is there any other decisive solution as the application fails to start from the launcher in the panel.

**Comment by rmappleby** [comment]
> I am having the same issue but --disable-gpu-sandbox it works but I am trying to add this into start up application on Mint Vanessa. Is there any other decisive solution as the application fails to start from the launcher in the panel.

I'm not a Mint user, but I assume Cinnamon still follows the OpenDesktop specifications. If so you just need to edit the simplenote.desktop file to add the --disable-gpu-sandbox flag. $XDG_DATA_DIRS should point you to possible locations for one or more "applications" directories, one of which will contain simplenote.desktop.

On Ubuntu $XDG_DATA_DIRS contains /usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
and simplenote.desktop is located in /usr/share/applications/

Edit that file, and add --disable-gpu-sandbox to the Exec stanza.  Mine looks like:

```
[Desktop Entry]
Name=Simplenote
Exec=/opt/Simplenote/simplenote %U --disable-gpu-sandbox
Terminal=false
Type=Application
Icon=simplenote
StartupWMClass=Simplenote
Comment=Simplenote is an easy way to keep notes, lists, ideas and more. Your notes stay in sync with all your devices for free.
GenericName=Note Taking Application
StartupNotify=true
Categories=Utility;
MimeType=x-scheme-handler/simplenote;
```

I can't remember if you need to logout/in before it takes effect.

**Comment by bagustris** [comment]
It also happens for fresh install of Ubuntu 22.04. Need to be fixed in future release. For clicking Simplenote icon in Ubuntu, you need to edit `simplenote.desktop` located in `/usr/share/applications/` (needs sudo) using the the command provided by @rmappleby above (adding `--disable-gpu-sandbox` in `Exec` line). For me, no need to login/logout, just click it twice.

**Comment by SaeedBaig** [comment]
Just saying same thing worked for me on Kubuntu 22.04.1 (added `--no-sandbox` to simplenote.desktop's 'Exec' command)

**Comment by membersound** [comment]
Anybody know how to achieve the same when pinning Simplenote to taskbar?

**Comment by davRX** [comment]
I have the same bug, but only on 1 PC; the bug is present on my Lenovo Thinpad with "i915" video driver, complete log is:
```
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[58459:0228/124401.764354:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trappe pour point d'arrêt et de trace (core dumped)
```
but no bug on my Asus All-in-One PC with "radeon" video driver...
I used the same package on the 2 machines (Simplenote-linux-2.21.0-amd64.deb)

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!

**Comment by irfaanz** [comment]
Hi Codebykat,

On Linux Mint 

![image](https://github.com/user-attachments/assets/28c40f29-b629-4049-9026-ab7712f5d95b)
I am using flatpak version now and I dont have this issue even though I was using LMDE for sometime and on it as well I was using the Simplenote flatpak version and didnt experience the issue any longer.

Thanks for everyones help. 

Irfan

**Comment by rekom** [comment]
`--disable-gpu-sandbox` fixed the problem for me too (Manjaro user). I had the problem for several weeks (month?, but it worked well at the beginning) but didn't bother to fix it as i was using the web version

**Comment by amatus-** [comment]
> `--disable-gpu-sandbox` fixed the problem for me too (Manjaro user). I had the problem for several weeks (month?, but it worked well at the beginning) but didn't bother to fix it as i was using the web version

This issue has been fixed in recent versions.

**Comment by rekom** [comment]
> > `--disable-gpu-sandbox` fixed the problem for me too (Manjaro user). I had the problem for several weeks (month?, but it worked well at the beginning) but didn't bother to fix it as i was using the web version
> 
> This issue has been fixed in recent versions.

Well started it today and it crashed again :(
