### ISSUE TITLE
stop at npm install

### ISSUE THREAD

**Issue by allelimo** [Automattic/simplenote-electron#3107]
### Expected
prepare fro npm run dev

### Observed
the process stops with errors

### Reproduced
fresh install of latest node.js on windows 10
cant go over steps 1 and 2
1. Clone the repo: git clone https://github.com/Automattic/simplenote-electron.git
2. cd simplenote-electron
3. npm install
4. this is the error list:
5.npm ERR! code 1
npm ERR! path C:\users\integra\simplenote-electron\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\users\integra\simplenote-electron\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\users\\integra\\simplenote-electron\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.16.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\users\integra\simplenote-electron\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\users\integra\simplenote-electron\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\users\integra\simplenote-electron\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\users\integra\simplenote-electron\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\users\integra\simplenote-electron\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\users\integra\simplenote-electron\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\users\integra\simplenote-electron\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\users\integra\simplenote-electron\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\users\integra\simplenote-electron\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\users\integra\simplenote-electron\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\users\integra\simplenote-electron\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\users\integra\simplenote-electron\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\users\\integra\\simplenote-electron\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\users\integra\simplenote-electron\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by allelimo** [comment]
I've just noticed that this is almost a duplicate of #3077
I think I can close this one

**Comment by passionate2023** [comment]
I'm also getting the same exception
