### ISSUE TITLE
Note not syncing to other device on today,my simplenote-electron is blank

### ISSUE THREAD

**Issue by singmj** [Automattic/simplenote-electron#3109]
### Expected
today my simplenote-electron not syncing to other device ,it is blank,
windows 11,
pls.fix it thank you
### Reproduced

1.
2.
3.

### Where did you see the bug

- System Make:
- System Model:
- OS:
- OS version: 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version:

**Comment by charliescheer** [comment]
Hi there.  Thanks for this report.  For issues with Simplenote, please contact Simplenote support by emailing support@simplenote.com
