### ISSUE TITLE
Not loading notes on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by rbreaves** [Automattic/simplenote-electron#311]
Installed both v1.0.0 and v1.0.1 and after providing my log in information the app simply does not load my notes at all. I can not really create additional notes either. I tried creating a test note, but it did not upload and sync itself and I could not create more than 1.

![blanksimplenote](https://cloud.githubusercontent.com/assets/10969616/15100472/61235cf8-1538-11e6-9aab-ffb69d092c1f.png)

**Comment by rachelsquirrel** [comment]
Are you able to sign into our web app and see your notes there? If yes, try deleting the app from your computer and installing it again. If this doesn't fix the problem then get in touch with us here - https://simplenote.com/contact-us/

**Comment by rbreaves** [comment]
Actually it is working correctly now... that is sort of odd. I did reinstall it twice that day, but it is working now. I suspect that maybe it was just some sort of DNS issue, although the site and the notes loaded just fine in chrome on that day.

**Comment by rachelsquirrel** [comment]
Ok, great! I'll close this. If you have any other issues then contact us here - https://simplenote.com/contact-us/.
