### ISSUE TITLE
Capitalization of S in the Simplenote install for Linux causes issues

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-electron#3112]
### Expected
chmod should be able to access '/opt/simplenote/chrome-sandbox`

### Observed
The symlink that gets pointed in the /usr/bin folder goes to the /opt/simplenote
The chmod command also goes to /opt/simplenote
chmod: cannot access '/opt/simplenote/chrome-sandbox': No such file or directory

Simplenote is installed in /opt/Simplenote. The capital S means other commands for Simplenote don't work
User reported in 5501115-zen

**Comment by SadParad1se** [comment]
Here's a workaround:
```
cd /usr/bin/
rm simplenote
ln -s /opt/Simplenote/chrome-sandbox simplenote
```

**Comment by davRX** [comment]
The problem is in the DEB package; the "postinst" file contains:
```
#!/bin/bash

# Link to the binary
ln -sf '/opt/simplenote/simplenote' '/usr/bin/simplenote'

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/simplenote/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
```
should be:
`ln -sf '/opt/Simplenote/simplenote' '/usr/bin/simplenote'`
and:
`chmod 4755 '/opt/Simplenote/chrome-sandbox' || true`

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
