### ISSUE TITLE
Core dumped Ubuntu 22.04

### ISSUE THREAD

**Issue by Beeblebrox21** [Automattic/simplenote-electron#3113]
When I try to start Simplenote  I get a core dump at most trys:
8><-----------------------------------------------------------------------------------------------------------------------------
┌──(frank🐧mother)-[~]
└─$ /opt/Simplenote/simplenote
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[3702660:0904/113057.097960:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  /opt/Simplenote/simplenote
-----------------------------------------------------------------------------------------------------------------------------><8
In about one of 10 cases the app starts anyway.

simplenote (2.21.0-25251)

System:
  Host: mother Kernel: 5.15.0-47-generic x86_64 bits: 64 Desktop: GNOME 42.4
    Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Machine:
  Type: Laptop System: LENOVO product: 20AMS2YJ00 v: ThinkPad X240
    serial: <superuser required>
  Mobo: LENOVO model: 20AMS2YJ00 v: SDK0E50510 PRO
    serial: <superuser required> UEFI-[Legacy]: LENOVO v: GIET99WW (2.49 )
    date: 03/17/2020
Battery:
  ID-1: BAT0 charge: 16.5 Wh (98.2%) condition: 16.8/23.2 Wh (72.4%)
  ID-2: BAT1 charge: 57.0 Wh (97.4%) condition: 58.5/71.1 Wh (82.3%)
CPU:
  Info: dual core model: Intel Core i5-4300U bits: 64 type: MT MCP cache:
    L2: 512 KiB
  Speed (MHz): avg: 957 min/max: 800/2900 cores: 1: 1040 2: 968 3: 926
    4: 895
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel
  Device-2: Acer SunplusIT Integrated Camera type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 resolution: 1360x768~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 4400 (HSW GT2)
    v: 4.6 Mesa 22.0.5
Audio:
  Device-1: Intel Haswell-ULT HD Audio driver: snd_hda_intel
  Device-2: Intel 8 Series HD Audio driver: snd_hda_intel
  Sound Server-1: ALSA v: k5.15.0-47-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I218-LM driver: e1000e
  IF: enp0s25 state: up speed: 10 Mbps duplex: full mac: 28:d2:44:70:89:24
  Device-2: Intel Wireless 7260 driver: iwlwifi
  IF: wlp3s0 state: up mac: 7c:7a:91:99:a3:54
  IF-ID-1: wwan0 state: down mac: 02:67:cc:e6:88:3f
Bluetooth:
  Device-1: Cambridge Silicon Radio Bluetooth Dongle (HCI mode) type: USB
    driver: btusb
  Report: hciconfig ID: hci0 state: up address: 00:1A:7D:DA:71:15 bt-v: 2.1
Drives:
  Local Storage: total: 238.47 GiB used: 138.87 GiB (58.2%)
  ID-1: /dev/sda vendor: Innovation IT model: N/A size: 238.47 GiB
Partition:
  ID-1: / size: 232.02 GiB used: 138.62 GiB (59.7%) fs: ext4 dev: /dev/dm-1
  ID-2: /boot size: 702.1 MiB used: 254.9 MiB (36.3%) fs: ext4
    dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 8 GiB used: 2.68 GiB (33.6%) file: /swapfile
  ID-2: swap-2 type: partition size: 980 MiB used: 0 KiB (0.0%)
    dev: /dev/dm-2
Sensors:
  System Temperatures: cpu: 58.0 C mobo: N/A
  Fan Speeds (RPM): fan-1: 4497
Info:
  Processes: 317 Uptime: 3d 21h 14m Memory: 7.46 GiB used: 5.83 GiB (78.2%)
  Shell: Zsh inxi: 3.3.13

**Comment by Beeblebrox21** [comment]
OK, https://github.com/Automattic/simplenote-electron/issues/3106#issuecomment-1200248598 solves the Problem for now.

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
