### ISSUE TITLE
Login into website immediately logs out

### ISSUE THREAD

**Issue by JannemanDev** [Automattic/simplenote-electron#3115]
### Expected
After logging in you expect to see your notes and that you stay logged in.

### Observed
After logging in on the simplenote website with correct email and password you immediately get logged out.

### Reproduced
1. Goto https://app.simplenote.com/login/
2. Login with correct email and password combination
3. You will notice you will get logged out

### Where did you see the bug
Tested on Windows 11 under FireFox.

**Comment by githubyouser** [comment]
I'm having the same issue in Firefox and Brave Browser on Windows 11. Kinda frustrating :( I'll gladly provide logs or troubleshooting if need be, to help get this fixed.

**Comment by caladd** [comment]
I'm seeing the same issue, but trying to login via my Wordpress.com account. I authenticate and then it refreshes back to the login screen. I'm seeing this under MacOS, Android, and under Chrome on Linux.

**Comment by eludi** [comment]
same for me. Happens both on Linux Firefox and Chromium.

**Comment by JannemanDev** [comment]
The app on iOS works btw

**Comment by opsaaaaa** [comment]
Same Problem on brave and Firefox Ubuntu

also I am unable to install the desktop app on Ubuntu 22.4.1. The deb package wont run and the AppImage Isn't working either.

**Comment by evazorro** [comment]
Seeing the same on web! I'm still logged in on the Android app, though, and that seems to be working still thankfully

**Comment by codebykat** [comment]
Hi folks, we believe this issue was caused by a short-lived problem that has since been fixed. If you're still seeing this behavior, can you kindly try resetting your password? If that doesn't work, please reach out to support@simplenote.com so that we can investigate further. Thanks!

**Comment by githubyouser** [comment]
Thanks for the quick fix! Seems to be working OK for me now.

**Comment by caladd** [comment]
Logging in with Wordpress.com account is still broken for me.

**Comment by oxycoder** [comment]
Still broken for WP account

**Comment by codebykat** [comment]
Hi, if you're still having problems please reach out by email to support@simplenote.com so we can fix your accounts up. We need to fix something on the backend for affected accounts and we can't collect personal information on the public GitHub. Thanks!
