### ISSUE TITLE
Expecting Features

### ISSUE THREAD

**Issue by davidjeba** [Automattic/simplenote-electron#3121]
- [ ] Missing Formating Toolbar
- [ ] Create different types of notes
      + Create Sticky Note
      + Create Slides
      + Create Meeting Notes (Whiteboard Canvas)
- [ ] Create Tasks [as simple as kanbanflow.com]

http://tauri.app/ better than electron

**Comment by CanadaHonk** [comment]
Tauri isn't better than Electron, it's an alternative with advantages and disadvantages.

**Comment by codebykat** [comment]
Thanks for these suggestions. You can "pin" notes to make them sticky, and the app does support basic checklists for tasks. The others are not planned at this time. As you noted, there are many note-taking apps out there, some of which support other kinds of workflows such as slide decks! Simplenote's mandate is to keep note-taking as simple as possible.
