### ISSUE TITLE
Unable to run the app in windows local machine

### ISSUE THREAD

**Issue by passionate2023** [Automattic/simplenote-electron#3122]
I'm unable to run the app in windows local machine neither build it

C:\Users\admin\Downloads\simplenote-electron-trunk-test\simplenote-electron-trunk>npm run dev
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> simplenote@2.21.0 dev
> make dev

The system cannot find the path specified.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[electron] '.' is not recognized as an internal or external command,
[electron] operable program or batch file.
[electron] ./node_modules/.bin/wait-on http://localhost:4000 && node C:\Users\admin\Downloads\simplenote-electron-trunk-test\simplenote-electron-trunk\node_modules\@adlk\misty\dist\exec.js --name="electron" --watchDir="./desktop" --cmd="make start NODE_ENV=development DEV_SERVER=true"   exited with code 1
[electron] ./node_modules/.bin/wait-on http://localhost:4000 && node C:\Users\admin\Downloads\simplenote-electron-trunk-test\simplenote-electron-trunk\node_modules\@adlk\misty\dist\exec.js --name="electron" --watchDir="./desktop" --cmd="make start NODE_ENV=development DEV_SERVER=true"   restarted
[electron] '.' is not recognized as an internal or external command,
[electron] operable program or batch file.
[electron] ./node_modules/.bin/wait-on http://localhost:4000 && node C:\Users\admin\Downloads\simplenote-electron-trunk-test\simplenote-electron-trunk\node_modules\@adlk\misty\dist\exec.js --name="electron" --watchDir="./desktop" --cmd="make start NODE_ENV=development DEV_SERVER=true"   exited with code 1
--> Sending SIGTERM to other processes..
[simplenote] node C:\Users\admin\Downloads\simplenote-electron-trunk-test\simplenote-electron-trunk\node_modules\@adlk\misty\dist\exec.js --name="simplenote" --watchDir="undefined" --cmd="make dev-server NODE_ENV=development"   exited with code 1
[simplenote] node C:\Users\admin\Downloads\simplenote-electron-trunk-test\simplenote-electron-trunk\node_modules\@adlk\misty\dist\exec.js --name="simplenote" --watchDir="undefined" --cmd="make dev-server NODE_ENV=development"   restarted
[simplenote] node:events:505
[simplenote]       throw er; // Unhandled 'error' event
[simplenote]       ^
[simplenote]
[simplenote] Error: spawn sh ENOENT
[simplenote]     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
[simplenote]     at onErrorNT (node:internal/child_process:478:16)
[simplenote]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[simplenote] Emitted 'error' event on ChildProcess instance at:
[simplenote]     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
[simplenote]     at onErrorNT (node:internal/child_process:478:16)
[simplenote]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[simplenote]   errno: -4058,
[simplenote]   code: 'ENOENT',
[simplenote]   syscall: 'spawn sh',
[simplenote]   path: 'sh',
[simplenote]   spawnargs: [ '-c', 'make dev-server NODE_ENV=development' ]
[simplenote] }
[simplenote] node C:\Users\admin\Downloads\simplenote-electron-trunk-test\simplenote-electron-trunk\node_modules\@adlk\misty\dist\exec.js --name="simplenote" --watchDir="undefined" --cmd="make dev-server NODE_ENV=development"   exited with code 1

**Comment by bunnv2** [comment]
any solutions?

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
