### ISSUE TITLE
Insert images

### ISSUE THREAD

**Issue by ajvcorreia** [Automattic/simplenote-electron#3125]
### What
Adding images to notes would be very helpful for my use case

### Why
I use simplenote to document lots of diferent information, sometimes adding thing like screenshots is much easier than having to type things.

**Comment by codebykat** [comment]
Thanks for posting the request! This is a highly requested feature, and while we have no immediate timeline, it is something we are considering.

Most discussion regarding this is tracked in #1069. Closing this as a duplicate.
