### ISSUE TITLE
Being able to disable IME for an input element

### ISSUE THREAD

**Issue by hhkkyy** [Automattic/simplenote-electron#3126]
In IE browser we have a css property ime-mode to control IME behaviors, especially disable IME. Would it be possible to have some way to disable IME in electron?

For windows machines, Microsoft IME of different versions and some third-party IMEs behave differently, and for some numeric input elements, IME itself causes some problems. Handling all these behaviors manually seems not to be possible. Maybe disabling IME for certain input element is a better way.

Since electron have its unique properties like -webkit-app-region , can it also support some unique css properties to disable IME for an input?

Sorry for poor English

**Comment by codebykat** [comment]
I don't think I understand the issue you're trying to solve by disabling the IME, but I know that people do rely on IMEs to insert characters in the correct language, so I don't think we would want to disable it entirely. It does look like Electron has better IME handling in recent versions. Issues such as this one might be relevant? https://github.com/microsoft/vscode/issues/120084

I'm going to close this as not actionable at the moment. There will be a new release out soon that, among other things, upgrades the bundled versions of Electron and the Monaco editor. Please let us know if you're still having trouble!
