### ISSUE TITLE
Extra lines in web interface

### ISSUE THREAD

**Issue by adamjohndaly** [Automattic/simplenote-electron#3127]
I'm emailing today to let you know that one of my notes somehow got into a bad state, where it looks different on my Android phone than it does on the website. On the website there are lots of extra blank lines, which I did not intentionally make. 

The Android screenshot comes from the Simplenote app on a Pixel 6 phone. The app version is 2.24.1 (150) and the Android version is 13. The Chrome screenshot is from Google Chrome 107.0.5304.121 (Official Build) (64-bit) running on an x64 computer with Windows 10 Pro version 21H2 build 19044.2130.

### Expected

Extra lines not added in the editor on the web. 

### Observed

Extra lines appear in the web version when not appearing in the Android version. 

### Reproduced

1. In a PC web browser, go to app.simplenote.com (I used Google Chrome on Windows 11).
2. Open the Settings screen, go to the Display tab, and set "Note display" to "Comfy", set "Line length" to Narrow, and set "Theme" to "Dark". I'm not sure if this matters or not, but those are my settings.
3. Click the "New Note" icon in the upper left.
2. Type "Test" and press Enter (this will be the title of the note).
3. Type "Apple" and press Enter.
4. Type "Banana" and press Enter.
5. Type "Cookie" and press Enter.
6. Open that note in the Android app. (You can leave the PC web browser open or closed while doing this.)
7. Long press on the word "Banana" to select it and bring up some commands.
8. Tap the "Cut" command. Now there will be a blank line where "Banana" used to be, both on Android and on PC.
10. Tap the backspace character on the Android phone's onscreen keyboard to delete the empty line.
11. Note that the cursor is now slightly to the right of the word "Apple", indicating that there is some kind of invisible space character after "Apple". This is the first indication of a bug, because you never typed a space.
12. Look at the note in your web browser again, and observe there is an empty line between Apple and Cookie which is not present in the Android version. This is the second indication of a bug, because you deleted that line in the Android version.

Playing around with it a little bit more, I suspect that when I press "Enter" on Windows you are recording it as \r\n, and when I try to delete the newline sequence on Android you are only deleting one of the characters and not the other. So it still shows up as a newline on Windows.

![android_fine](https://user-images.githubusercontent.com/18173779/208481291-d1cd4410-303a-4082-8d2d-6fa456cedf9c.png)
![chrome_extra_newlines](https://user-images.githubusercontent.com/18173779/208481312-86aeac98-a87d-42b2-aeb8-012876954437.png)

### Where did you see the bug

- System Make:
- System Model: Windows 10 Pro version 21H2 build 19044.2130.
- OS:
- OS version: 
- Browser (if applicable): Google Chrome 
- Browser version (if applicable): 107.0.5304.121 (Official Build) (64-bit)
- Simplenote app version:  2.24.1 on Android. 

Ticket 5742053

**Comment by codebykat** [comment]
Thanks for this detailed report. I'm closing it as stale but please report it in the [Android repository](https://github.com/Automattic/simplenote-android) if it is still happening on the latest version!
