### ISSUE TITLE
cannot not install from GUI on Ubuntu 16.04

### ISSUE THREAD

**Issue by chiisaihayashi** [Automattic/simplenote-electron#313]
When I click install button at software center,  installation does not start.
Installation from terminal is ok. (dplg -i simplenote-1.0.1.deb)

**Comment by MiteshNinja** [comment]
It's not a Simple Note issue. It's a bug with Gnome centre/Ubuntu. View the bug here: https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1573206

(You can close this now :P)

**Comment by chiisaihayashi** [comment]
That's problem on my desktop environment.
Thanks!!
