### ISSUE TITLE
Edit keyboard shortcuts

### ISSUE THREAD

**Issue by gleb-28** [Automattic/simplenote-electron#3135]
### What
Hi! It would be cool to have a feature allowing user to customize keyboard shortcuts in the settings.

### Why
Now there are preconfigured shortcuts and you can't set them by your own choice. In case the shortcuts are not convenient for a user, it remain unused at all. The feature would help to be more efficient and productive.

### How
There is a switch button for a shortcuts in the settings. The additional link to edit it could be placed below.

![image](https://user-images.githubusercontent.com/104042337/215824325-eb885c8a-f870-4890-8b87-1a3851e1c5b3.png)

**Comment by codebykat** [comment]
Thanks for the suggestion, but we have no plans to implement this currently. It would add a great deal of complexity for something few people use.
