### ISSUE TITLE
Slow start up on windows 10

### ISSUE THREAD

**Issue by n-osennij** [Automattic/simplenote-electron#3137]
#1844

I have pc ryzen 7 1800x, 24 GB RAM, fast ssd, windows 10.
Open ms word and excel 2016 takes ~1.5 seconds, chrome ~1.5 seconds, sublime text v4 less than 1 second, simplenote ~3-4 seconds. I don't have many or large notes.

version for m1 macbook (8GB RAM) opens very fast - less than second.
version for android (oneplus ace, 12GB RAM, android 13) ~1.5 seconds.

I can record video or do any other measurements. What can I do?

I really like simplenote. But it's too slow on windows when opening. And why it so large? Look at fiinote - less than 10mb, blaze speed.

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
