### ISSUE TITLE
Readonly Public Sharing with search optiopn

### ISSUE THREAD

**Issue by passionate2023** [Automattic/simplenote-electron#3138]
Hi,

Need to share the entire notes as public URLs where noone should be able to edit/update/delete any of the content. The public sharing URL will be completely READ-ONLY

Thanks

**Comment by codebykat** [comment]
Hi @passionate2023, we do have the ability to publish a note to a public URL. Published notes are visible to anyone but cannot be modified by viewers. See the following link for more information: https://simplenote.com/help/#publish

**Comment by passionate2023** [comment]
But search option is missing when notes are published.

**Comment by passionate2023** [comment]
It is about publishing all the notes and entire collection and not only one single note

**Comment by passionate2023** [comment]
@codebykat Can you please help me on how to publish all the notes and entire collection with search and not single note?
