### ISSUE TITLE
Add Task List (checkbox) Markdown support

### ISSUE THREAD

**Issue by valdotdev** [Automattic/simplenote-electron#314]

**Comment by Trollwut** [comment]
This would make my household (4 persons) gladly switch to simplenote. :>

Any word on considering this request?

**Comment by rafaelpimpa** [comment]
Would love to see this too!

**Comment by dmsnell** [comment]
This is something we definitely plan on implementing at some point but haven't yet and probably won't be able to get in for a couple of releases. I think that somehow it should already be working with the Markdown rendering but that obviously isn't. We would absolutely welcome some help on this! :smile:

**Comment by johnkjoseph** [comment]
In the meantime is it somehow possible according to #309 using GFM? Couldn't get it to work though.

**Comment by dmsnell** [comment]
@johnkjoseph this is on my own personal backlog to try and track down. I'm simply not sure why it's not working is all.

**Comment by rik-shaw** [comment]
Yes, checklists would be great.  Unfortunately, the `[` and `]` are hard to get to on Android if it follows this syntax.  But I suppose a hard to use standard is better than no standard at all.  Maybe I need to find a markdown friendly Android keyboard? :-)

**Comment by Topy44** [comment]
I agree that checklists would be great. Especially if they can be activated/deactivated by clicking on the box.

**Comment by pedrojuk** [comment]
+1 for Markdown checkbox support. Would be very useful

**Comment by greatkithain** [comment]
Yeah, checkbox in Simplenote would be awesome!

**Comment by giannissc** [comment]
I was under the impression that this was already submited in the repository and would be inlcuded in the 1.1.0 update yet when i try to show a checkbox i only get this 
![screenshot from 2017-11-21 12-13-01](https://user-images.githubusercontent.com/20277283/33071918-57f38a94-ceb5-11e7-8d50-c065a86e91a9.png)

**Comment by MorgothSauron** [comment]
+1 for checkbox support in Simplenote :-)

**Comment by giosoft** [comment]
This is a must, pls

**Comment by toast018** [comment]
+1 for checkbox support in Simplenote. Made a Github account just to come here and +1 this.

**Comment by Laurent001** [comment]
+1 for checkbox support

**Comment by Robertght** [comment]
+1 #1236175-zen

**Comment by sinisavukovic** [comment]
+1 for checkbox support

**Comment by virtadpt** [comment]
+1 for checkbox support, also.

**Comment by BandonRandon** [comment]
Twitter request https://twitter.com/TEDxOdessa/status/1029813699949867009

**Comment by weems74** [comment]
+1 I'm really wanting to switch from Evernote, but this is a big impediment.

**Comment by mirka** [comment]
Thanks everyone! Since we do support markdown checklists now (kind of), I'm closing this in favor of more specific enhancements: #874 #875 #876
