### ISSUE TITLE
500 Error when attempting Simplenote web app login

### ISSUE THREAD

**Issue by sylvre** [Automattic/simplenote-electron#3140]
### Expected
Log into Simplenote web app

### Observed
Typed email and password into https://app.simplenote.com/login on browser behind enterprise firewall
Checked "Remember me"
Clicked "Log in"
"500 Internal Server Error" displayed at https://app.simplenote.com/user
Clicked "Go back one page" button
The above reproduced as is multiple times.

### Where did you see the bug
- System Make: Dell
- System Model: Latitude 2420
- OS: Windows 10 Education
- OS version: 22H2
- Browser (if applicable): Firefox
- Browser version (if applicable): 110.0.1 (32-bit)
- Simplenote app version: app.simplenote.com

**Comment by codebykat** [comment]
Hi @sylvre, if you are behind a firewall you need to make sure you are able to access the host api.simperium.com.

If you're still unable to log in, please drop us a line at support@simplenote.com so we can get more details. We're not able to troubleshoot account-related problems on the public GitHub. Thanks!
