### ISSUE TITLE
simplenote (snap) only starting up with sudo

### ISSUE THREAD

**Issue by frankmuc** [Automattic/simplenote-electron#3143]
### Expected

simplenote can be started as a regular user without sudo

### Observed

The app does not launch despite some warnings:

(simplenote:194088): Gtk-WARNING **: 23:55:53.275: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(simplenote:194088): Gtk-WARNING **: 23:55:53.285: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(simplenote:194088): Gtk-WARNING **: 23:55:53.287: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
frank@HOST:~$ simplenote --no-sandbox

(simplenote:194285): Gtk-WARNING **: 23:56:10.623: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(simplenote:194285): Gtk-WARNING **: 23:56:10.632: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(simplenote:194285): Gtk-WARNING **: 23:56:10.634: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

### Reproduced

running 'simplenote' as user leads to the warnings mentioned above

running 'sudo simplenote' works and shows:

Failed to open connection to "session" message bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

(simplenote:194678): Gtk-WARNING **: 23:59:37.903: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(simplenote:194678): Gtk-WARNING **: 23:59:37.912: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(simplenote:194678): Gtk-WARNING **: 23:59:37.915: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

Note: X11 is being used via X11 forwarding / Xming on Windows (export DISPLAY=...)

### Where did you see the bug
- System Make:
- System Model:
- OS: Ubuntu
- OS version:  Linux HOST 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.10.0 (snap)

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
