### ISSUE TITLE
We need a DEB installer file (and maybe others) for arm64

### ISSUE THREAD

**Issue by mbrennwa** [Automattic/simplenote-electron#3146]
Raspberry Pi. PineBooks. Chromebooks. Lenovo high-end ARM laptop. Apple M1/M2 computers running on Linux (Asahi). They all want an ARM/Linux version! Please tell your compiler to make an ARM binary in addition to the x86 and package this into a DEB (and other installer files). This would be great!

**Comment by 510846** [comment]
Apple Chip Support?

**Comment by codebykat** [comment]
This should be working in the latest version (2.22.1), please let us know if not!
