### ISSUE TITLE
Build fails (due to Python 2 dependency?)

### ISSUE THREAD

**Issue by mbrennwa** [Automattic/simplenote-electron#3147]
I followed the instructions to build the code. The process failed at step 3 (`npm install`) with the following error(s):
```
npm ERR! code 1
npm ERR! path /home/mbrennwa/Ablage/simplenote-electron/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /home/mbrennwa/Ablage/simplenote-electron/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/mbrennwa/Ablage/simplenote-electron/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.13.0 | linux | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/home/mbrennwa/Ablage/simplenote-electron/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/mbrennwa/Ablage/simplenote-electron/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/mbrennwa/Ablage/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp ERR! System Linux 6.3.0-asahi-00538-g3965d153b13f
npm ERR! gyp ERR! command "/usr/bin/node" "/home/mbrennwa/Ablage/simplenote-electron/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/mbrennwa/Ablage/simplenote-electron/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mbrennwa/.npm/_logs/2023-05-23T18_27_58_140Z-debug-0.log
```

**Comment by mattdimicelli** [comment]
The same thing happened for me:

npm ERR! code 1
npm ERR! path /home/matthew/Documents/simplenote-electron/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /home/matthew/Documents/simplenote-electron/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/matthew/Documents/simplenote-electron/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.13.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/home/matthew/Documents/simplenote-electron/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/matthew/Documents/simplenote-electron/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/home/matthew/Documents/simplenote-electron/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /home/matthew/Documents/simplenote-electron/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /home/matthew/Documents/simplenote-electron/node_modules/isexe/index.js:42:5
npm ERR! gyp Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matthew/.npm/_logs/2023-06-04T17_56_10_831Z-debug-0.log

**Comment by passionate2023** [comment]
This happens to me as well. What is the fix?

**Comment by billsliu** [comment]
**I failed too, it looks like this project is an abandoned project.**

**Comment by codebykat** [comment]
Hi folks, it's not abandoned but it was deprioritized for awhile. We are in the process of updating all the apps to make sure they still build and should have an update out soon. Thanks for the reports!

**Comment by codebykat** [comment]
#3183
