### ISSUE TITLE
Simplenote in Debian 12 Bookworm

### ISSUE THREAD

**Issue by bonushenricus** [Automattic/simplenote-electron#3149]
### Expected
resolve a run problem in debian 12 amd64
### Observed
the Simplenote desktop software had a problem

### Reproduced
/opt/Simplenote/simplenote
in terminal done this
[24795:0628/193716.000734:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

### Where did you see the bug
- System Make:
- System Model:
- OS: DEBIAN
- OS version: 12
- Simplenote app version: 2.21.0

**Comment by 1majom** [comment]
For anyone else having this problem adding the --in-process-gpu switch helped. Got the idea from [this](https://stackoverflow.com/a/74342187/14621947) Stackoverflow answer.

**Comment by rcentros** [comment]
That fixed it for me in the terminal. Couldn't get it to work when adding --in-process-gpu to the Menu entry however -- so I couldn't move it to my Panel. But I found a workaround. I just made a small bash script named "simple"...
**#!/bash/bin
/opt/Simplenote/simplenote --in-process-gpu &
exit**
Make the shell script executable then run it from the terminal as "**source simple**" or "**. ./simple**" and it will close the terminal once Simplenote is up and running.
You can also use the shell script to create a Launcher on the Desktop or in the Menu. I'm using Cinnamon and built mine in the Menu. Just added this to the Launcer's command line... **/home/my _myusername_/simple**. Add the Simplenote icon and copy to the Cinnamon Panel by pressing the Control+Alt keys and dragging it there.
So far working without issue.

**Comment by philipjohn** [comment]
@rcentros ' suggestion worked for me on Pop!_OS with one small change to the hashbang:

```
#!/bin/bash
/opt/Simplenote/simplenote --in-process-gpu &
exit
```

**Comment by victe** [comment]
In gnome-destop you can edit `/usr/share/applications/simplenote.desktop` by adding `--in-process-gpu` or `--disable-gpu-sandbox` to the `Exec` entry before `%U`.

    [Desktop Entry]
    Name=Simplenote
    Exec=/opt/Simplenote/simplenote --in-process-gpu %U
    Terminal=false
    Type=Application
    Icon=simplenote

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
