### ISSUE TITLE
Lost ability to search inside a note on Mac

### ISSUE THREAD

**Issue by nikitar** [Automattic/simplenote-electron#3150]
In Simplenote 2.18, pressing cmd+F opens the standard search-in-a-document window. (See the screenshot) I also have Simplenote 2.21.0 on a different mac and there pressing cmd+F focuses the "Search all notes and tags" input box instead. I assume it's a regression.

<img width="633" alt="Capture d’écran 2023-06-29 à 11 28 09 AM" src="https://github.com/Automattic/simplenote-electron/assets/396798/10eb2506-71d6-4291-bddd-7b6a7ffac288">

### Expected
Pressing cmd+F allows one to search inside the current note. (Previous behaviour)

### Observed
Pressing cmd+F activates the "Search all notes and tags" flow

### Reproduced
1. Focus a note
2. Press cmd+f

### Where did you see the bug
- System Make: MacBook pro
- System Model: MacBook pro 14-inch, 2023
- OS: Mac
- OS version: MacOS 13.4
- Simplenote app version: 2.21.0

**Comment by nikitar** [comment]
Looking more into this, it _seems_ that version 2.21 is built with Electron and 2.18 is a native app. That might explain the regression.

**Comment by codebykat** [comment]
Hi @nikitar, they are in fact two different apps. You can (re)download the native app from the Mac app store: https://itunes.apple.com/us/app/simplenote/id692867256?ls=1&mt=12
