### ISSUE TITLE
Self-hosted server

### ISSUE THREAD

**Issue by webysther** [Automattic/simplenote-electron#3152]
### What

Self-hosted of server used by simplenote

### Why

Privacy

### How

Like mostly projects that support self-host, expose a docker or open the project that is used to build the server.

**Comment by webysther** [comment]
Based on https://github.com/Automattic/Simplenote-United/issues/75

**Comment by jleandroperez** [comment]
I'm sorry to say that, for the time being, there are no news on the self-hosted server request.

Closing this one since this repository is just for the Electron client.

Thank you for reaching out!
