### ISSUE TITLE
Some edited notes get stuck in sync state

### ISSUE THREAD

**Issue by Arrow7000** [Automattic/simplenote-electron#3154]
### Expected

For notes to sync as usual.

### Observed

Edited notes get stuck with the spinner forever, and this error appears in the console:

```
serviceworker.js:42 Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
    at serviceworker.js:42:18
```

However this only seems to happen for *some* notes, not all of them, but I can't figure out what the difference is between those notes that work and those that don't. But those that don't seem stubbornly stuck, even when I close and reopen the app/webpage.

![image](https://github.com/Automattic/simplenote-electron/assets/13225609/7dc1c14a-2f9e-4feb-859b-cf1f0249a222)

### Where did you see the bug

- System Make: Dell
- System Model: XPS 13
- OS: Windows
- OS version: 10
- Browser (if applicable): Chrome - both on the app.simplenote.com webpage and the PWA app.
- Browser version (if applicable): 115.0.5790.111 
- Simplenote app version: N/A

**Comment by Atomk** [comment]
Can also reproduce on Windows 10 with the Simplenote Electron app, version: 2.21.0.

I tried to look at app logs but there is nothing recent in there.

I noticed that actually sometimes some changes are synced, for example if I write a phrase, after a few minutes only a word is synced, and then nothing else happens (but the spinner stays there). I tested this with the desktop app and the Android app, and it happens both ways, so I'm pretty sure it's a server issue, something similar happened last year.

EDIT: three weeks later, it happened again. This is very frustrating.

**Comment by rjsalvadorr** [comment]
Also seeing this issue on two separate Windows 10 machines (both using Simplenote v2.21.0)  
Not seeing any errors or warnings on the debugging console though :(  

Even worse, I've also noticed that it will sometimes sync notes eventually, but then repeat some of the more recent changes. Like `## header example` becoming `## ## header example`. Or entire lines being repeated.

**Comment by madhur** [comment]
Happens to me too on Linux

**Comment by shawnk-23** [comment]
same here on Linux. :(

**Comment by gubrist** [comment]
Same with electron 2.21.0

- Windows 11 (at home) and 
- Windows 10 (at work)

Furthermore, I have observed that new notes get "scrumbled" interacting with Android Phone / Tablet.

**Comment by Atamasy** [comment]
I have also observed this under Windows 11 and Windows 10. Sync times seem to vary between half a minute (30 sec.) to a few minutes. Seems to work relatively fine through the web interface.

**Comment by sharknoise** [comment]
For me, the same happens in the web interface and the Android app, probably a server issue https://forums.simplenote.com/forums/topic/simplenote-servers-performance-issues-august-2023/

**Comment by rizqikazukun** [comment]
I think i got same problem using flatpak build on fedora 38

**Comment by rickswe** [comment]
Same thing happened to me on Linux. I'm using the app image that was released in 2021 https://github.com/Automattic/simplenote-electron/releases/tag/v2.21.0  Seems to work fine on Mac. Having second thoughts about using it on  Linux or at all. :(

**Comment by codebykat** [comment]
I'm closing this as it probably captured several different issues, which may be related to a backend problem, firewall/VPN settings, the outdated Linux build or issues specific to a particular account. Please open a new issue if you're still unable to sync after the new version of the app is packaged and released.
