### ISSUE TITLE
Can't run on Debian 12 with Amd cpu.

### ISSUE THREAD

**Issue by earthmoon** [Automattic/simplenote-electron#3155]
Hello,

I try to install Simplenote on Debian 12 with Appimage and deb file from [the link](https://github.com/Automattic/simplenote-electron/releases/tag/v2.21.0), but all fail.

From the deb file, the result is:
```
Selecting previously unselected package simplenote.
(Reading database ... 256778 files and directories currently installed.)
Preparing to unpack Simplenote-linux-2.21.0-amd64.deb ...
Unpacking simplenote (2.21.0-25251) ...
Setting up simplenote (2.21.0-25251) ...
chmod: cannot access '/opt/simplenote/chrome-sandbox': No such file or directory
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
```

I can search the Simplenote and click it, but it doesn't start successfully.

From the Appimge file, after having been given the access by `chmod` command, it can't be started by double clicking.
How should I install it?

Thanks.

**Comment by philipjohn** [comment]
I saw the same thing when attempting to install on Pop! OS. I decided to create the directory manually and re-run install, which seemed to work:

```
$ sudo mkdir -p /opt/simplenote/chrome-sandbox

$ sudo dpkg -i /tmp/Simplenote-linux-2.21.0-amd64.deb 
(Reading database ... 210221 files and directories currently installed.)
Preparing to unpack .../Simplenote-linux-2.21.0-amd64.deb ...
Unpacking simplenote (2.21.0-25251) over (2.21.0-25251) ...
Setting up simplenote (2.21.0-25251) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
```

However, I also see nothing happening when opening the application. I also purged (`sudo apt-get remove --purge simplenote`) and tried to install by opening the .deb package with Eddy, the package manager that comes with Pop! OS but had the same result.

I'm using [Simplenote-linux-2.21.0-amd64.deb](https://github.com/Automattic/simplenote-electron/releases/download/v2.21.0/Simplenote-linux-2.21.0-amd64.deb).

My system:

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Pop
> Description:	Pop!_OS 22.04 LTS
> Release:	22.04
> Codename:	jammy

Edit: If it matters, my Chrome version is "115.0.5790.102 (Official Build) unknown (64-bit)"

**Comment by worldwalker2000** [comment]
You need to run the app with --disable-gpu-sandbox as #3149 states.

**Comment by codebykat** [comment]
This should be working in the latest version (2.22.1), please let us know if not!
