### ISSUE TITLE
Padding Between the Top Panel and the Editor

### ISSUE THREAD

**Issue by iseos** [Automattic/simplenote-electron#3156]
Hi.
Could you please tell me if the padding between the top panel and the editor is intentional or is it a bug?
![1](https://github.com/Automattic/simplenote-electron/assets/16374845/efe183b1-6064-4557-99bc-ec3b4804b4ab)
![2](https://github.com/Automattic/simplenote-electron/assets/16374845/8fdf1f4b-ccaf-49fb-a02a-344389812609)
In my opinion, it's a bit inconvenient. Ideally, there shouldn't be any padding at all.
![3](https://github.com/Automattic/simplenote-electron/assets/16374845/b66b3007-d4b6-4256-9c54-39f277fecc33)
There's also a small padding in the history mode.
This applies only to the Electron version, both desktop and web.

**Comment by codebykat** [comment]
Thanks for the report! The whitespace is intentional, and I don't think we'll revisit it without a larger design overhaul.
