### ISSUE TITLE
Simplenote icon missing in GNOME dock

### ISSUE THREAD

**Issue by joshcjohns** [Automattic/simplenote-electron#316]
When launched, the Simplenote entry that appears in GNOME dock is a generic, grey icon, not the blue Simplenote icon. Using Fedora 23, GNOME 3.18.2, Simplenote 1.0.1 for Linux 64-bit.
![screenshot from 2016-05-21 20-56-57](https://cloud.githubusercontent.com/assets/11774978/15451551/193f815a-1f97-11e6-9ed0-1d62fd7d6da2.png)

**Comment by RobbieFM** [comment]
On Ubuntu 16.04 Gnome 3.20 there is a icon
![simplenote icon dash](https://cloud.githubusercontent.com/assets/19664209/15669582/5ab14f24-2721-11e6-97e1-bcdc2a7f72cc.png)

**Comment by diazbastian** [comment]
I think that depends on the installation process. In the case of @RobbieFM there is a *.deb package for Ubuntu that includes everything needed for the application to work correctly. For other distributions that we must perform a manual installation.

@joshcjohns I recommend after installing Simplenote, for example in /opt directory, create a [desktop entry](https://specifications.freedesktop.org/desktop-entry-spec/latest/) with the necessary information. You can do this with a text editor or an application like [MenuLibre](https://launchpad.net/menulibre).

Cheers

**Comment by amenk** [comment]
I installed it using the .deb in Xubuntu and in the taskbar, there is no icon.

**Comment by owcz** [comment]
![](https://i.imgur.com/McTluNn.png)

A similar situation (note that Xfce's Whisker Menu uses the right icons but that the panel's Window Buttons plugin uses the generic white window icon)

An [Xfce forum mod](https://forum.xfce.org/viewtopic.php?id=11537) said that the app likely doesn't follow the [Extended Window Manager Hints (EWMH) spec](https://specifications.freedesktop.org/wm-spec/1.3/) and recommended [a hack](https://forum.xfce.org/viewtopic.php?id=10845) (`xseticon`) for getting around it on my individual install, though it would be better to fix it in the repo.

**Comment by owcz** [comment]
As fixed:

![](https://i.imgur.com/mfI04hD.png)
