### ISSUE TITLE
Simplenote Bulk Edit feature needed

### ISSUE THREAD

**Issue by khuongduy354** [Automattic/simplenote-electron#3160]
This feature request #2680 is in 2021 and probably ignored, I want to request it again, since this is such a crucial feature.

**Comment by codebykat** [comment]
Hi @khuongduy354,

While I appreciate your enthusiasm, opening duplicate issues is a bit counterproductive. If there's an issue for it, the request has been noted, and you are welcome to subscribe to existing issues to see any updates. We do take everyone's feedback into consideration when deciding on our roadmap for future work, but there's currently no timeline for when we might be able to work on this.

If you are working with a lot of notes, the best course of action might be to export your data, edit it with a different tool, delete all notes from your account and then re-import them. I realize that's a bit drastic as a workaround, but depending on what you're doing it might be faster than editing them one-by-one.
