### ISSUE TITLE
Wrong symlink

### ISSUE THREAD

**Issue by pavroo** [Automattic/simplenote-electron#3163]
### Where did you see the bug

- System Make:
- System Model:
- OS: Debian
- OS version: 12 & testing (13)  amd64, armhf, i386
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.21.0

The postinst script makes symlink from /opt/simplenote which doesn't exist.
There is /opt/Simplenote dir instead, so the app can not be launched from Menu or a terminal.
The postrm script removes broken symlink, should be changed to the right one too.

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
