### ISSUE TITLE
iHD drv video failed

### ISSUE THREAD

**Issue by pavroo** [Automattic/simplenote-electron#3164]
### Reproduced

Can not launch the simplenote app from  Menu and the /opt/Simplenote/simplenote file:
 `libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[23226:0924/124617.458524:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Pułapka debuggera/breakpoint`

The driver is installed:
`apt policy intel-media-va-driver
  Installed: 23.3.2+dfsg1-1
  Candidate:   23.3.2+dfsg1-1
  Version:
 *** 23.3.2+dfsg1-1 500
        500 http://deb.debian.org/debian trixie/main amd64 Packages
        100 /var/lib/dpkg/status
`

### Where did you see the bug

- System Make:
- System Model:
- OS: Debian
- OS version: 12 & testing (13) amd64
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.21.0

**Comment by codebykat** [comment]
The latest version (2.22.1) upgraded a ton of dependencies and should have fixed issues such as this one. Please let us know if this is still a problem after updating!
