### ISSUE TITLE
highlight text with dragging

### ISSUE THREAD

**Issue by randomstuff69** [Automattic/simplenote-electron#3170]
### What
 highlight text with dragging on phone app

### Why
 making copy pasting one piece of text instead of the whole note

**Comment by codebykat** [comment]
Unfortunately the editor component we use, Monaco, does not support mobile browsers. See https://github.com/Microsoft/monaco-editor/issues/246

Using Simplenote web from a mobile browser is "at your own risk" -- we recommend installing a native app for the best experience.
