### ISSUE TITLE
Can I request an update in 2024 from 2021 for all apps including windows?

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#3173]
### Reproduced

1.
2.
3.

### Where did you see the bug

- System Make:
- System Model:
- OS:
- OS version: 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version:

**Comment by codebykat** [comment]
Hi @Varniit-pro-90s! Thanks for getting in touch. We are working to get the apps on all platforms updated and should have new versions out soon.
