### ISSUE TITLE
Is this project abandoned ? 

### ISSUE THREAD

**Issue by andirsun** [Automattic/simplenote-electron#3174]
two years without any update. why is that ? 

### Reproduced

1.
2.
3.

### Where did you see the bug

- System Make:
- System Model:
- OS:
- OS version: 
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version:

**Comment by codebykat** [comment]
Hi @andirsun, occasionally we have to put Simplenote on the backburner and spend some time working on other projects within the company. (As you might know, Simplenote is run by the folks at Automattic, who also run WordPress.com, Tumblr, Day One, PocketCasts and a number of other services.) The good news is we're planning some updates to the apps and the infrastructure soon. Simplenote is sometimes dormant but never abandoned - last year was not the first time we had to set it aside for a bit, and probably won't be the last. Thanks for getting in touch!
