### ISSUE TITLE
Support multi-tab

### ISSUE THREAD

**Issue by bagustris** [Automattic/simplenote-electron#3198]
It is a common feature that a (note) editor should have a multi-tab feature, i.e., to edit multiple notes simultaneously.

### What
Support multi-tab for Simplenote

### Why
Editing multiple notes is a common workflow (e.g., for linking or remembering other topics when editing another). Considering the following work flow:
- edit note A
- edit note B, leaving note A
- back to note A

### How
Open each note in each tab, provide close (x) symbol in each tab to close that tab.

**Comment by codebykat** [comment]
I understand that you're asking for tabs within the app, but I think if we added distinct URLs for notes, that would largely address this use-case. #1635

**Comment by codebykat** [comment]
Closing for now, with the suggestion that you use https://app.simplenote.com in a browser, which should allow you to use browser tabs to simultaneously edit multiple notes to your heart's content.

**Comment by bagustris** [comment]
@codebykat 
I really want this feature. I think that, with the rise of AI agents, implementing this feature is not difficult.
Simplenote keeps me focused.
A browser doesn't.
