### ISSUE TITLE
Inserting Email Address Into Note Causes Markdown Preview to be Blank

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/simplenote-electron#3200]
### Expected
A note that includes an email address in the text should display the full note's text in the markdown preview.

### Observed
The preview is completely blank.

### Reproduced
1. Create a new note
2. Type an email address into the note — "email@domain.com", for example.
3. Click on the markdown preview button.

<img width="1004" alt="CleanShot 2024-05-22 at 09 22 43" src="https://github.com/Automattic/simplenote-electron/assets/42454301/4b4f8c59-7a2c-415e-af90-a25c2abe7622">
<img width="1005" alt="CleanShot 2024-05-22 at 09 22 37" src="https://github.com/Automattic/simplenote-electron/assets/42454301/983d3ee9-f071-48a7-ac9f-20a999c778da">

### Where did you see the bug
- OS: macOS
- OS version: 13.6.6
- Browser (if applicable): Brave
- Browser version (if applicable): 1.66.110

[Reported by user in the forums](https://forums.simplenote.com/forums/topic/adding-markdown-sometimes-renders-a-blank-markdown-screen/?view=all#post-2567).

**Comment by mdrockwell** [comment]
One workaround is to wrap the email address in ` to create a code block.

**Comment by codebykat** [comment]
Fascinating. You're right. I guess one of our recent dependency upgrades changed something about the preview sanitization behavior...

**Comment by codebykat** [comment]
This is now fixed on app.simplenote.com and will be included in the upcoming 2.22 release.
