### ISSUE TITLE
Fails to launch on Kubuntu 24.04 (Maybe other ubuntu flavors)

### ISSUE THREAD

**Issue by sgerner** [Automattic/simplenote-electron#3203]
### Expected
Application launches

### Observed
Apparmor error message because application does not have a name

### Reproduced
Try to open app

### Where did you see the bug
Kubuntu 24.04

### Solution
Modified from [https://github.com/OrangeDrangon/android-messages-desktop/issues/448](https://github.com/OrangeDrangon/android-messages-desktop/issues/448
)

1. Create a new apparmor profile:
`sudo touch /etc/apparmor.d/simplenote`

2. Edit the file:
`sudo nano /etc/apparmor.d/simplenote`

3. Insert the following content into the new file:
```
# This profile allows everything and only exists to give the
# application a name instead of having the label "unconfined"

abi <abi/4.0>,
include <tunables/global>

profile simplenote "/opt/Simplenote/simplenote" flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/simplenote>
}
```

4. Reload apparmor
`sudo systemctl reload apparmor`

**Comment by codebykat** [comment]
Hi @sgerner, thanks for the report. Which version of the app is this occurring on, and where did you install it from? I'm not sure if this is fixed in the upcoming release candidate or not...

**Comment by sgerner** [comment]
I apologize for not being more complete and appreciate you following up!

App version is 2.21.0, AMD64. I installed it from the GitHub .deb package [found here](https://github.com/Automattic/simplenote-electron/releases/tag/v2.21.0).

**Comment by codebykat** [comment]
Thanks! Can you try the [upcoming 2.22 version](https://github.com/Automattic/simplenote-electron/releases/tag/v2.22.0-beta1) and let me know if the issue exists there too?

**Comment by sgerner** [comment]
Everything appears to be working with the new beta and update dependencies. Thanks!
