### ISSUE TITLE
Upgraded to 2.22.0 and just shows white blank page and nothing else

### ISSUE THREAD

**Issue by jhedlund** [Automattic/simplenote-electron#3228]
### Expected

Expected SimpleNote to launch normally.

### Observed

Just a white blank screen:
![image](https://github.com/Automattic/simplenote-electron/assets/7224943/e61d164b-f574-481a-9b54-c0e5dcc2946a)

I saved application logs as well but they are empty (0 bytes).

### Reproduced

I've tried quitting and relaunching, same thing happens.

### Where did you see the bug

- System Make: AMD
- System Model: Ryzen 7
- OS: Windows
- OS version: 11
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: 2.22.0

**Comment by paulobrabo** [comment]
Same here

**Comment by codebykat** [comment]
Hmm, that's concerning, thanks for the report. Can you view the development console and let me know what errors are shown, if any? It's under Help -> Advanced -> Debugging Console, and it should stay open through a restart of the app, which would let us see if there are any errors on startup.

**Comment by jhedlund** [comment]
Didn't think to look at the errors:

![image](https://github.com/Automattic/simplenote-electron/assets/7224943/30e49edc-f9bd-4f11-b744-94ae0c0c8021)

So am I missing a .config-local file?

**Comment by roundhill** [comment]
If you try downloading an alternate windows build from here does it work? https://github.com/Automattic/simplenote-electron/releases/tag/v2.22.0

**Comment by roundhill** [comment]
We've set it back to pre-release while we figure out what's going on! The older release is still available here: https://github.com/Automattic/simplenote-electron/releases/tag/v2.21.0

**Comment by jhedlund** [comment]
I tried Simplenote-win-2.22.0 and Simplenote-win-2.22.0-x64 from the release link and both exhibited same problem.

Downloaded and installed 2.21 and I'm back in business.

**Comment by roundhill** [comment]
> I tried Simplenote-win-2.22.0 and Simplenote-win-2.22.0-x64 from the release link and both exhibited same problem.

Thanks for the info! We tested those builds, something went awry 🤔

**Comment by codebykat** [comment]
The bug behind the missing config has been fixed and this release should be available as a new 2.22.1 version soon. Anyone who did upgrade to the broken 2.22.0 version while it was available will need to download the previous version manually (or the upcoming 2.22.1 version once it is out). Very sorry for the trouble! Our release process is quite rusty since this is the first new version in quite some time 😬

**Comment by jhedlund** [comment]
Thanks for the quick fix!

**Comment by jhedlund** [comment]
Probably don't need this confirmation, but I installed 2.22.1-beta1 and it worked fine (there is a close to 1-second pause of a white blank page but then loads).

Thanks again!

**Comment by codebykat** [comment]
Actually I appreciate the confirmation @jhedlund! Not sure about the pause... was that just the first time or on every load? We had to upgrade a LOT of things under the hood for this version, so it may or may not be an indication something is broken, per se, but just a difference in what loads in which order, etc. But if it's unduly slow or showing any other errors we might be able to dig into it.

I'm going to close this issue but please do let us know if you notice anything else weird with the beta 😬

**Comment by jhedlund** [comment]
The white blank page shows on every load, 1-2s delay.   Certainly not a big deal for me
