### ISSUE TITLE
[macOS] 2.22.0 is ARM-only and requires macOS 11

### ISSUE THREAD

**Issue by core-code** [Automattic/simplenote-electron#3229]
2.22.0 is ARM-only and requires macOS 11. there is no mention about those changes in the release-notes. is this on-purpose?

<img width="253" alt="Screenshot 2024-07-10 at 18 31 12" src="https://github.com/Automattic/simplenote-electron/assets/1261954/0a731712-cb96-416e-bf77-096c4a66ee5b">

**Comment by codebykat** [comment]
Thanks for the report @core-code, I don't believe we tested on Intel Macs. We upgraded all the dependencies to fix the build for Silicon Macs and I thought it was a universal build 🤔 

We've set this release back to prerelease status for unrelated reasons, but I will investigate.

**Comment by codebykat** [comment]
Oh, I should note that we have a [native Mac app](https://itunes.apple.com/us/app/simplenote/id692867256?ls=1&mt=12) available, which should work on Intel-based infrastructures as well. We generally recommend folks install that one if they're on the Mac, as this (Electron-based) version exists primarily to support Linux and Windows desktop users. So this is something we'll fix if we have the time, but it may not be the highest priority. If the native app doesn't work for you, please let me know why :)
