### ISSUE TITLE
Export individual notes

### ISSUE THREAD

**Issue by prat0088** [Automattic/simplenote-electron#323]
I wanted to save a specific note as a text file.  I clicked the share arrow expecting to see an export option.  No luck.  Such a feature would be useful.

**Comment by dmsnell** [comment]
@prat0088 can you help me understand the value of this here? I thought about individual note exports, but since the notes are plain text a quick copy-all gets the note content ready to paste anywhere. I find that more useful than exporting a single note because in most cases I can imagine, exporting to a file would precede opening that file and copying and pasting the content elsewhere.

**Comment by dmsnell** [comment]
@prat0088 I'm going to close this issue as I don't see us adding an option to export individual notes. in the app (since #448) you can export the entire account and each note will appear in the generated ZIP file, however. I hope that meets your need!

**Comment by davidwolfpaw** [comment]
An example of where this would be useful: If I want to write something and share it with someone else in Markdown format. The version that can be shared through the app has HTML as opposed to the Markdown. To get the Markdown file I need to copypaste the content into a text editor and save it as a new file. As the alternative is downloading every note, unzipping the archive, and discarding all other notes after finding the one that I need, if incorporating an individual export feature isn't too onerous, I think that it would be useful.

**Comment by dmsnell** [comment]
@davidwolfpaw I wonder if we're crossing terms with `export` and `publish`. We can publish notes and they will render the markdown source of the note if Markdown is enabled for that note. If it's disabled for that note then you can publish the markdown source. You could copy a note's contents into a new note and publish both versions if you wanted to.

Exporting will always save the unformatted source of the note which sounds like what you want. If you copy all of the text content from the note when you are in the Simplenote app though, that too should be the unformatted source.

Sorry I'm not understanding your case here - please do show me where I'm not getting it.
