### ISSUE TITLE
Inconsistent first line style between `simplenote-electron` & `simplenote-macos` & `simplenote-android`

### ISSUE THREAD

**Issue by wenfangdu** [Automattic/simplenote-electron#3238]
`simplenote-electron`
<img width="680" alt="image" src="https://github.com/user-attachments/assets/388dddcb-f848-42c5-a87e-a6029370707c">
`simplenote-macos`
<img width="595" alt="image" src="https://github.com/user-attachments/assets/387ceb68-efe9-41ce-a2f8-5ef243e281b8">
`simplenote-android`

![image](https://github.com/user-attachments/assets/87a95e96-39e5-469a-8825-d676759f3c56)

Only `simplenote-electron`'s first line is not bold, is it intentional?

**Comment by wenfangdu** [comment]
Personally, I like the `simplenote-electron` way, since it's simpler, less info to digest.

**Comment by codebykat** [comment]
This is #3158 I believe, and sorry that you prefer it this way, because technically it _is_ supposed to match the other platforms. But thank you for the feedback 😅

**Comment by wenfangdu** [comment]
@codebykat Thank you for the pointer.
