### ISSUE TITLE
Global hotkeys

### ISSUE THREAD

**Issue by prat0088** [Automattic/simplenote-electron#324]
A global hotkey to bring the application to the front would be useful, perhaps with the focus on the search field so you could simply type in the note you're after.

**Comment by erichiller** [comment]
Hotkey to minimize to and restore from the TSA would be _perfect_.

**Comment by drw158** [comment]
Not sure this is really feasible. If you are not focused on the app, then we cannot guarantee than this shortcut would not interfere with the app you are focused on.

**Comment by mirka** [comment]
This can be achieved with the [globalShortcut](https://electronjs.org/docs/api/global-shortcut) module in Electron. We would need a new tab in the Settings dialog so the shortcuts can be set by the user. A global `New Note` and `Search Notes` shortcut might be useful.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
