### ISSUE TITLE
Version 2.22.1 not installing on Linux Mint 22

### ISSUE THREAD

**Issue by jannotti-glaucio** [Automattic/simplenote-electron#3241]
### Expected
Install simplenote version 2.22.1 on a linux minnt 22 distribution, using the .deb installation

### Observed
When I try to install it I receive the following error:
![image](https://github.com/user-attachments/assets/e4b349eb-d89c-434a-a6bb-364344bd52e2)

### Where did you see the bug
- System Make: Dell
- System Model: Latitude 5510
- OS: Linux Mint
- OS version:  22
- Simplenote app version:  2.22.1

**Comment by DanielNoga** [comment]
Same for Kubuntu 24.04 and latest beta 2.22.2 beta2

**Comment by fishinnabarrel** [comment]
Same problem on Debian Trixie ...
![Screenshot_20240804_142211](https://github.com/user-attachments/assets/ba77fe6f-854a-4304-90e7-b6e18e9ee321)

**Comment by codebykat** [comment]
Hm. @mokagio do you happen to know if this dependency is still necessary? Some prior discussions [here](https://github.com/Automattic/wp-calypso/issues/75452) and [here](https://github.com/Automattic/simplenote-electron/issues/3048).

**Comment by codebykat** [comment]
Thanks, this dependency has been removed in the upcoming 2.22.2 version. If you'd like to test this ahead of the release, you can download the beta from here: https://github.com/Automattic/simplenote-electron/releases/tag/v2.22.2-beta.4
