### ISSUE TITLE
Complete Collaborator Access 

### ISSUE THREAD

**Issue by mangoose20026** [Automattic/simplenote-electron#3242]
Hi,

Complete Collaborator Access is needed 

a) assign few users read-only 
b) assign few users write-only
c) assign few users delete-only
d) all access
e) access to any public as read-only without any credentials

Thanks

**Comment by codebykat** [comment]
Hi @mangoose20026, it sounds like your use case is probably too complicated for Simplenote. At the moment you can share a note with another person (granting full edit access), and you can share a note to a public URL (read-only without credentials). We are unlikely to ever add granular permissions such as write-only and delete-only; this would be very, very difficult to implement across different platforms in a way that wasn't easy to circumvent.

Collaboration is designed to allow two (or more) people to work on a note together and this does assume a level of trust. You could always make a copy of a note before sharing, and the history function allows you to revert any unwanted changes, but a better workaround would probably be to share the text of the note with your intended recipient(s) by copying it and pasting it into a different program (email, for example). If the content isn't particularly sensitive, you could always rely on security via obscurity, and share the link to a published note directly with someone else, never posting it publicly online, and unpublishing it as soon as it is no longer needed.

Sorry I don't have a different response to share, but our mandate for Simplenote is to keep it, well, simple, and this means we can't accommodate every feature request. If you do find another app that meets your needs, I'd love to hear what it is, as I can't think of one offhand that has granular sharing controls like the ones you're suggesting.

**Comment by mangoose20026** [comment]
@codebykat Sorry the collobaration is not both people working on the same thing on the same time. I meant providing read-only or public URL for anyone to have access to all except delete or edit. My entire collection should be readable with search, higlight option as me for any user.
