### ISSUE TITLE
Up/down navigation of note list after search

### ISSUE THREAD

**Issue by prat0088** [Automattic/simplenote-electron#325]
I'd like to navigate to another note without using the mouse:
1. CTRL+F to jump to the "All Notes" search box. (this exists)
2. Type part of the note name to filter the note list
3. Press up/down to change the selected note
4. Press enter to move the focus to the note text in the right-hand pane.

This request is for the behavior in 3 and 4.

**Comment by drw158** [comment]
will be done in #37
