### ISSUE TITLE
Monaco Sticky Scroll: Disable?

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#3250]
A user reported that they see a `<div class="sticky-widget">` tag in the Simplenote editor. Looks like this may be the "Sticky scroll" feature in Monaco that we should disable. We're unable to reproduce with the content the user provided.

This should do it, in the Monaco settings. We should see if it's disabled by default though, maybe we have another bug somewhere...

```
stickyScroll: {
    enabled: false,
},
```

**Comment by codebykat** [comment]
Done [here](https://github.com/Automattic/simplenote-electron/pull/3254) and seems okay, though I don't think this option should be causing a div to appear within the editor area, so I'm concerned there's another bug at large. Where was this reported?

**Comment by yoshi-sheep** [comment]
Is current version of https://app.simplenote.com 2.22.2, which includes this fix?
If so, this fix is not a cause of the problem.
I'm the one who reported this issue. I checked this and still see the problem.
As a workaround, I use a Chrome extention to manipulate CSS ( .sticky-widget { display: none !important; } ) so I don't see the widget.

![Image](https://github.com/user-attachments/assets/673bdbe3-d08c-4f1f-8096-7c235e5444bc)
