### ISSUE TITLE
Escape should remove the note list filter

### ISSUE THREAD

**Issue by prat0088** [Automattic/simplenote-electron#326]
#### Steps to reproduce
1. Type in any text in the "All Notes" note list filter on the left.
2. Press escape 
#### What I expected

Search box is cleared and all notes show in the list.
#### What happened instead

Nothing

**Comment by drw158** [comment]
#481

**Comment by gtsiolis** [comment]
#481 implemented a different workflow. This is still relevant a would be nice to have!

@drw158 do you think it's worth reopening? /cc @roundhill

**Comment by gtsiolis** [comment]
Oh no, that's already included in #481. It was actually performing quite to notice. Ignore this! 😅
