### ISSUE TITLE
Follow The FreeDesktop Dark Style Preference

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-electron#3264]
### What

GNOME, Cinnamon, KDE Plasma, and Elementary OS include a way for apps to switch between light and dark themes by following this key (Freedesktop Dark Style Preference) e.g. when GNOME is set to Dark style and then the apps that foilow this preference also use a Dark style/ theme.
### Why

It would be a good idea for Simplenote to follow this implementation to have better consistency between different desktop environments and to be able to automatically set a light or dark theme in the whole notetaking interface depending on what style of GTK theme being used i.e. a light style or a dark one - that is if it supports the FreeDesktop Dark Style Preference which most modern themes do since this preference has been out for almost three years now.
### How

Here's the [documentation](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html) for this preference. Remember to add a "System Theme" entry in the "Theme" submenu under "View" in the menubar so the system's theme preference can be overridden for this app. I'd recommend it be set to "System Theme" so has the same style so the app's is in the dark mode when the system is in dark mode and the light mode when the system is in it too.

**Comment by codebykat** [comment]
Hi @amethystgosling163, Simplenote is built on Electron and this is something that would need to be supported in Electron for us to be able to implement it. I found a couple related issues over there: https://github.com/electron/electron/pull/38977 and https://github.com/electron/electron/issues/33635

I'm not sure if those are referencing the same FreeDesktop preference, but I'd recommend adding a note to those discussions to see if Electron would be able to add support for it.
