### ISSUE TITLE
Preview: Keep same styles for desktop as for web version

### ISSUE THREAD

**Issue by sambody** [Automattic/simplenote-electron#327]
I would expect to see the same (or similar) styles for desktop and web version, for consistency.

Some differences that stand out for me (especially the first one):
1. Heading 1 is left aligned in desktop, centered in web version. I would suggest keep it left aligned.
2. Heading 2 and 3 are bold in desktop, unlike the web version.
3. A code block has a padding and a border in the deskop version, unlike the web version.

![simplenote-content](https://cloud.githubusercontent.com/assets/37572/16055847/2913545a-3273-11e6-8e97-5934dbef8833.png)

**Comment by mambusskruj** [comment]
It would be really nice. First of wall, web app should highlight `inline code` and  
    code block.

**Comment by dmsnell** [comment]
Thanks for reporting this! We definitely have ways we can improve the preview styles. Also we have some open issues dealing with our Markdown parser (#309, #450).

We'd love to provide guidance and any help we can if if anyone wants to lend a hand!

**Comment by roundhill** [comment]
The stylesheets for this app and the web have been synced up 👍
