### ISSUE TITLE
Copy Link (After Publish) Loads Indefinitely

### ISSUE THREAD

**Issue by GGussi** [Automattic/simplenote-electron#3271]
### Expected

Click publish, be able to copy a link.

### Observed

Clicked publish, copy link loads indefinitely, can't copy link.

### Reproduced

1.  Go to a note
2. Click publish
3. Try to click copy link

Saw another issue that was closed that listed the same problem back in 2021, someone in the comments said to email support as it was account specific, I emailed them and haven't gotten a response back.  Asking here as well.

### Where did you see the bug

- System Make: ASUSTeK COMPUTER INC.
- System Model: ROG Zephyrus G14 GA401IV_GA401IV 
- OS: Windows
- OS version: 10.0.19045 Build 19045
- Browser (if applicable): 
- Browser version (if applicable): 
- Simplenote app version: Does the same thing as the windows application Simplenote

**Comment by GGussi** [comment]
I'm using the latest version v2.22.2

**Comment by codebykat** [comment]
Hi @GGussi, we actually had an issue with the backend that was causing publishing to be pretty lagged, can you check and see if this is fixed now?
