### ISSUE TITLE
Add markdown support for Mac OS

### ISSUE THREAD

**Issue by titoesteves** [Automattic/simplenote-electron#329]
#### Steps to reproduce
1. Simplenote app for Mac OS does not currently have markdown support yet markdown is supported in the windows and linux apps. 

#### What I expected
Simplenote app for Mac OS to have markdown support

#### OS version
El Capitan

**Comment by daveismyname** [comment]
+1

**Comment by TwisterMc** [comment]
I'd love to see this too.

**Comment by bopinto** [comment]
Since there is already Markdown for linux and windows, what's stopping from having it to Mac?

**Comment by titoesteves** [comment]
In looking at a previous blog post by simplenote(https://simplenote.com/2016/03/29/simplenote-for-windows-and-linux/), it states the windows and linux versions were open sourced. Since they did not mention the mac version, I assume they did not use the same code the mac and linux versions use for markdown support. Again this is only an assumption given that the mac source code is not readily available. Which brings up another point. The mac source code should be open source especially since the windows and linux versions are. I will create another issue to open source mac source code

**Comment by roundhill** [comment]
We have an issue open for the mac app to add markdown, so closing here.

**Comment by titoesteves** [comment]
@roundhill I created this issue because I was unable to find a previously created issue. Can you provide a link to the open issue?

**Comment by roundhill** [comment]
@titoesteves the mac app is currently in a private repo, sorry.

**Comment by titoesteves** [comment]
@roundhill, thanks for the reply. Is there an ETA on when markdown support will be added to the mac app? Also is there an ETA when the mac app will be open sourced?

**Comment by frenchbread** [comment]
@titoesteves It's here: https://github.com/Automattic/simplenote-macos

**Comment by randallagordon** [comment]
Any plans for an official OSX build of this Electron app?

**Comment by titoesteves** [comment]
@frenchbread Glad to see it is now open source. Does this include markdown support?

**Comment by roundhill** [comment]
> Any plans for an official OSX build of this Electron app?

We're trying to decide on that. Replace the native app? Offer two apps? The electron app actually has more features that the native one.

What do y'all think?

**Comment by randallagordon** [comment]
@roundhill I imagine it'd be easier to support a single Electron app targeting all platforms versus multiple apps, but that could easily be assuming more than I should about what y'all are up to! I'm partial to Electron since I'm a JS dev, but I mostly would like to get my hands on some tasty, tasty Markdown support. 😄

**Comment by roundhill** [comment]
@randallagordon Try downloading the source, and run `make package-osx`. Should work...

**Comment by frenchbread** [comment]
@titoesteves No, it does not.

**Comment by frenchbread** [comment]
+1 for electron build for OSX. (@randallagordon has a point)

**Comment by marcphilipp** [comment]
+1 for an electron build for os x, too.

**Comment by oravla1972** [comment]
Hi, sorry but I do not understand, Is there a way to use Markdown in simplnote for MAC?

thanks
Alvaro

**Comment by zky829** [comment]
Any ETA on markdown support for the macOS app? Trying to use Simplenote instead of Evernote. Thanks!

**Comment by damiensawyer** [comment]
+1 for OSX electron build to bring the three platforms into parity.

**Comment by roundhill** [comment]
You might be interested in this 😄  https://simplenote.com/2017/02/14/try-the-new-macos-beta/

**Comment by damiensawyer** [comment]
Awesome!! Thanks!!



------------------------------------------------------------------------
I welcome VSRE emails. Learn more at vsre.info
------------------------------------------------------------------------

**Comment by stevegray** [comment]
@roundhill The beta works great but its version number is now lower than the most recent number.  Did the "beta" feature get dropped?

**Comment by roundhill** [comment]
@stevegray it's a different version number based on the Electron app. Sorry for any confusion there.

**Comment by stevegray** [comment]
@roundhill Thanks for the reply.  So will the beta be extended and maintained?  Or is it a "one off" demo of features?  Just trying to understand what the strategy is to incorporate Markdown into the OSX version.

**Comment by seaneking** [comment]
Bit late to the party but just wanted to voice a strong -1 for replacing the native MacOS app with this Electron one. Electron wrappers are much slower than native counterparts, and having both the native app and electron beta side by side the difference is very noticeable. For a note taking app, whose only real job is to process text, performance is a key feature. And it's a pretty fundamental problem with Electron's weight (c.f. Atom vs. Sublime). Electron apps also have a tendency to be huge memory hogs, another thing that a simple note taking app definitely shouldn't be.

Can understand the benefits of a single cross-platform codebase for desktop, and if you _need_ to replace the MacOS app with an Electron distro, from a maintainability/viability standpoint, then okay. But I wouldn't see it as a goal to aim for from the user's perspective.

**Comment by ericsoco** [comment]
No clear place to +1 on this thread, and it's been 9 months since the last comment, so...
What's the plan for Markdown on OSX? I see the > 1-year-old Electron beta, but...not clear what the actual plan for OSX support is here.

**Comment by roundhill** [comment]
@ericsoco we added Markdown to the native Mac app last a few months ago:

https://simplenote.com/2018/02/20/markdown-support-added-in-latest-macos-app-update/
