### ISSUE TITLE
Note title (first row) isn't stylized as heading in the editor like in the other apps

### ISSUE THREAD

**Issue by nsrosenqvist** [Automattic/simplenote-electron#330]
In the other SimpleNote apps the first row of the note in the editor is stylized as a heading, increased font-size, but isn't in the electron app. Can this be added for the electron app too?

**Comment by AntonioIT** [comment]
I do agree. This will avoid markdown tags to be displayed in the list of the notes (in the left panel).

**Comment by roundhill** [comment]
This is pretty challenging because we are using a `<textarea>` element in the electron app. Open to suggestions :)

**Comment by nsrosenqvist** [comment]
Electron is built on Chromium's Blink rendering engine right? The CSS ::first-line pseudo-selector works on textareas for Blink (and WebKit, I assume). I don't think it works for Firefox but that wouldn't be an issue since no code is shared with the official web app, right?

Here's an example: http://codepen.io/anon/pen/NAwkAV

**Comment by dmsnell** [comment]
Looks great @nsrosenqvist - are you interested in putting together a PR for this?

**Comment by nsrosenqvist** [comment]
Unfortunately I don't have the time to do that right now. I assume that it would only apply for when markdown is not used as well, right? If you're familiar with the code base, which I am not, it should be pretty straight forward to implement this though.

**Comment by dmsnell** [comment]
Thanks, we'll try and see when and if we can get this in.

**Comment by roundhill** [comment]
It works! I'm pretty sure I tried this before, maybe an update to WebKit between then and now added support:

<img width="492" alt="screen shot 2016-07-13 at 3 48 55 pm" src="https://cloud.githubusercontent.com/assets/789137/16822699/2d45a846-4913-11e6-8913-c1577fc931a8.png">

I'll create a PR for this at the end of the week.

**Comment by nsrosenqvist** [comment]
Great! Thanks @roundhill, much appreciated!
