### ISSUE TITLE
Note editor: No focus when when toggled back to edit mode

### ISSUE THREAD

**Issue by sean185** [Automattic/simplenote-electron#331]
#### Steps to reproduce
1. Create note
2. Enter preview mode
3. Enter edit mode
4. Attempt to scroll/type
#### What I expected

The app should focus on the editing pane and I should be able to begin typing or scrolling immediately.
#### What happened instead

The focus remains on the edit toggle button. I determined that because pressing tab shifts focus to the preview toggle button.
#### OS version

Windows Desktop app v 1.0.2

**Comment by drw158** [comment]
It would be nice if when you go back to the editor pane, then it would remember where your cursor was.

**Comment by mirka** [comment]
Related: #102

**Comment by codebykat** [comment]
Confirmed still an issue after #2148

**Comment by belcherj** [comment]
Fixed in: https://github.com/Automattic/simplenote-electron/pull/2434
