### ISSUE TITLE
Search uses exact phrase search rather than keywords

### ISSUE THREAD

**Issue by shawnajean** [Automattic/simplenote-electron#333]
#### Steps to reproduce

1.Create a new note with the words "Rachel loves bikes"
2. Search for the words "Rachel bikes"

The app can't find the note because it's searching for the exact phrase rather than notes which contain both Rachel and bikes. It doesn't work this way in the iOS app. In iOS searching for "Rachel bikes" will return the note with "Rachel loves bikes".

Reported by user on Windows: 2722409-t

Confirmed by @ashercantrell

**Comment by dmsnell** [comment]
Closed by #604
