### ISSUE TITLE
Source code for Mac app is not available

### ISSUE THREAD

**Issue by titoesteves** [Automattic/simplenote-electron#336]
#### Steps to reproduce
In looking at a previous blog post by simplenote(https://simplenote.com/2016/03/29/simplenote-for-windows-and-linux/), it states the windows and linux versions were open sourced. However, the mac version is not
#### What I expected
App for mac source code to be available on github

#### What happened instead
It is not currently available on github

#### OS version
Mac OS

**Comment by roundhill** [comment]
We are planning to open source the other apps, once we get them cleaned up and ready for OSS.
