### ISSUE TITLE
Word count displays as zero for Russian

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#337]
**Steps to reproduce**
1. Create a new note.
2. Add some text in Russian.
3. View the word count.

**What I expected**
The word count to display the number of words.

**What happened instead**
The word count displayed zero words.

**Screenshot / Video**

![words](https://cloud.githubusercontent.com/assets/7946521/16683058/c268f9ea-44f5-11e6-946d-10067177202d.png)

Reproduced by @KokkieH. Thank you!

**Comment by dmsnell** [comment]
@rachelmcr awesome spotting! I have submitted an update to the word counter, but it will not completely fix the counts, as some languages (Japanese, for example) are much more difficult than finding spaces between words.

**Comment by rachelmcr** [comment]
I think you meant @rachelsquirrel :)

**Comment by dmsnell** [comment]
oops, thanks @rachelmcr - I hit enter after the first autocomplete on `r` having seen it was `rachel`
