### ISSUE TITLE
Pencil icon is to add new notes, not for editing

### ISSUE THREAD

**Issue by AntonioIT** [Automattic/simplenote-electron#339]
The pencil icon button is generally used to edit notes.
To add a new note I expect a more standard "plus" icon button.
Thank you.

**Comment by roundhill** [comment]
It is a `+` icon in the app, unless I'm missing something:

<img width="35" alt="screen shot 2016-07-13 at 8 45 36 am" src="https://cloud.githubusercontent.com/assets/789137/16809743/3da51baa-48d6-11e6-8c29-506300d8411b.png">

**Comment by AntonioIT** [comment]
I do not see the + icon. Instead I see the attached screenshot of my tablet.
Thank you!

-- Antonio

Il 13/lug/2016 17:46, "Dan Roundhill" <notifications@github.com> ha scritto:

**Comment by roundhill** [comment]
Screenshot didn't come through, is it an android tablet? This repo is for the electron app (windows and Linux). The android app will get the + icon in an update soon.

**Comment by roundhill** [comment]
Closing since I'm pretty sure you were referring to the Android app, which now has the same icon.
