### ISSUE TITLE
Tags duplicates

### ISSUE THREAD

**Issue by AntonioIT** [Automattic/simplenote-electron#340]
SimpleNote allows duplicated tags (no difference in case neither in right spaces). This must be avoided.
As soon as the user types the first letters, SimpleNote should suggest the possible existing tags.
Thank you.

**Comment by dmsnell** [comment]
@AntonioIT thanks for the report! I'm having trouble reproducing this locally. could you help me understand how to create a duplicate tag?

here's what I tried:
 - found a tag I had used already "work"
 - found an existing note without that tag
 - added the tag, but only the one "work" tag was found in the list of tags and both the old notes and this newly-tagged note appeared when I searched for "work"
 - tried adding that tag again in the "Add tags…" input, but when I entered "work" the second time, it simply disappeared while the existing "work" tag remained

also, can you help me understand how to know if I have a duplicate tag? are you seeing two tags of the same name in the list of tags? in the list of tags on a given note?

thanks again!
