### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by catkit** [Automattic/simplenote-electron#341]
From a user:

> I have one problem though, most of the notes I write are in Arabic, and I was wondering about any possibility to see a future version of simplenote that support right to left text, or at least support adding HTML code, that would be really useful, since the service becomes almost unusable when writing Arabic text inline with English text.

**Comment by rezzap** [comment]
We have another user requesting this in #1322140-zen

>I want to ask you to fix the layout problem in published notes for middle-eastern languages like Persian and Arabic. 
When I publish my notes in Persian and check the public link in my browser (Chrome), they are not in "Right to left" layout and it really bothers any one who reads my notes. 
Currently they are being presented like English Text, but in languages like Persian and Arabic, It should be right aligned some how.
Could you plz solve that issue? 
I'm working with simple note alot and it's becoming really annoying. 
I would be glad to help if you needed extra informations about the issue.

**Comment by mirka** [comment]
Thanks for the requests! Closing in favor of #562.
