### ISSUE TITLE
Automatic hyperlink formatting in Simplenote for Windows & Web

### ISSUE THREAD

**Issue by jgadsby** [Automattic/simplenote-electron#342]
Simplenote on Mac and Android automatically highlights URLs, even if the note is not Markdown formatted. This does not happen on Simplenote for Windows, in the desktop or web apps. I have to add markdown formatting and switch the view to Markdown to be able to click on the links. It'd be really great if this feature was brought to Windows.

**Comment by axil** [comment]
I second that. It would be a great step forward in usability.

**Comment by drw158** [comment]
Dupe of #368
