### ISSUE TITLE
Download .zip unsuccessful, browser freezes

### ISSUE THREAD

**Issue by marianoju** [Automattic/simplenote-electron#346]
#### Steps to reproduce
1. Login to Simplenote web app (https://app.simplenote.com/signin). 
2. Select $userid (in upper right corner) > Download .zip

#### What I expected
After some server-side compressing a .zip file to be downloaded by browser. 

#### What happened instead
Browser freezes after selecting “Download .zip”. Tried with Firefox 47.0 and Chromium 51.0.2704.79
- Firefox asks to stop script or continue (neither produces the expected outcome). 
- Chromium reports “Server trouble. (Will retry.)”. 

#### My Configuration 
- Ubuntu 16.04.1 LTS (Xenial Xerus) 32-bit
- Kernel Linux 4.4.0-31-generic i686
- MATE 1.12.1
- Memory: 3.7 GiB
- Processor: Intel® Core™ i3 CPU U 380 @ 1.33GHz × 4

**Comment by roundhill** [comment]
Can you please reach out to support at https://simplenote.com/contact-us? They can help with your .zip issue.
