### ISSUE TITLE
Feature Request: Make individual notes searchable in spotlight

### ISSUE THREAD

**Issue by 3vivekb** [Automattic/simplenote-electron#347]
Make simplenote notes searchable from macOS spotlight.

Spotlight is a very useful mac feature to search for things.  When I use spotlight I can find text inside individual notes and documents that are stored in other applications.  

Unfortunately, I cannot currently search inside my simplenote notes from macOS spotlight.  When I want to use simplenote, my current process is to open simplenote and then use search to find specific notes.  A two step process when maybe it can be reduced by one step!

Edited: Because what I wrote before was unreadable 😝

**Comment by dmsnell** [comment]
Hi @3vivekb - thanks for filing the issue! Can you help me understand what you are asking for?

When you speak about Spotlight, are you referring to the built-in Spotlight search in macOS?

Can you clarify the process you refer to when writing, "Instead I must open spotlight and then search again?" I'm not sure I follow what you are describing.

**Comment by 3vivekb** [comment]
I rewrote my issue to improve readability!

**Comment by gatestone** [comment]
Yes indeed! I would really love to swipe down on iPhone to search for a simplenote! Spotlight supports dozens of my applications but not Simplenote app. It can't be that hard?

**Comment by hmijail** [comment]
The Simplenote blog post at https://simplenote.com/2017/01/16/ios-and-macos-update-now-available/ mentions that Spotlight is supported in iOS since January 2017. No mention of Spotlight in macOS, and this bug report and the lack of news makes me think that it's still not supported - is that right?

Any plans to support it?

**Comment by KodeNationFR** [comment]
Hello, I would like the same functionality as the one described in this application, but for linux, thanks to the application "Albert", which do the same thing as spotlight on Mac. thanks!

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by mal567** [comment]
Request for this feature too in 2026
