### ISSUE TITLE
Fails to remember window size on Linux

### ISSUE THREAD

**Issue by fayad** [Automattic/simplenote-electron#350]
I'm running 1.0.2 build on Debian Sid with Gnome 3.20.2.
#### Steps to reproduce
1. Open up Simplenote
2. Reduce the window to smaller size or maximize to full screen
3. Close the app and reopen
4. Fails to open from the last resized position of window
#### What I expected

Expected the application to remember last size of window. Open again from the last window size.
#### What happened instead

Always opens with the default window size.
#### OS version

Debian Sid. Desktop environment is Gnome 3.20.2.

**Comment by ruppalsingh** [comment]
Same as #305

**Comment by natanielcz** [comment]
This one should be closed. Bug was fixed in #305 :)
