### ISSUE TITLE
Markdown enabled should not split the main view in to two modes

### ISSUE THREAD

**Issue by DoTheEvo** [Automattic/simplenote-electron#352]
I would like all the nice stuff that markdown provides, but not in the way its working now.
I rather just have simple notes than to be at the mercy of that indecision, which view I should use.

Should I have nice markdown or should I have easy editing whenever I want to?

It might seem little silly maybe, you just do extra click/swipe when you want to edit but its kinda ruining my experience.

Consider that the two major note taking players OneNote and EverNote decided to have single view of the notes, and you edit it in with all the glory within that main view, and at the same time have all the bells and whistles.

This is to be simplenote, and idea of switching between viewing and editing goes against my imagined idea of simple. But thats just one random guy opinion...

First solution that comes to mind is going in to Edit mode on clicking in to the note, assuming markdown is enabled.

**Comment by drw158** [comment]
Can you clarify what you mean exactly? Do you mean that you do not like having both the Edit and Preview modes when you have MD enabled? Do you want editing and preview of MD all in the same view?

> First solution that comes to mind is going in to Edit mode on clicking in to the note, assuming markdown is enabled.

Currently, once you click on a note you should go straight to Edit mode unless you previously selected Preview.

**Comment by DoTheEvo** [comment]
>Do you mean that you do not like having both the Edit and Preview modes when you have MD enabled? Do you want editing and preview of MD all in the same view?

pretty much, yeah

>Currently, once you click on a note you should go straight to Edit mode **unless you previously selected Preview**.

well, that just means I need to be in edit mode already so I am in edit mode when I click

I am probably too demanding, these are simple notes afterall...
but what I would prefer instead of having "markdown view", I would just have toolbar where I could make text bold, or make unsorted lists, various highlight text, make url... all of this in the same view as the one I am always in. The same way onenote, evernote, or zim have.. just less, simpler

its just floating idea...   it would be probably too rough change to go from plaintext with some markup options to something that I described, where the note could not be just displayed - "as is" on a smartphone

**Comment by dmsnell** [comment]
I would like to see us style the markdown text in the edit mode. @DoTheEvo I don't think it would be aligned with Simplenote to have a WYSIWYG editor, which it sounds like you are describing, though I think we could improve the appearance in the editor view.

With the work that @nfcampos is doing in #370 we should be able to experiment with styling and decorators in the edit mode. [Zeit.co's blog](https://zeit.co/blog/now-cli-oss) and some Markdown editors I have used inspire me this way. It's simple, it's minimal, it's plain-text, but it's still semantically emphasized.

cc: @drw158 @roundhill
