### ISSUE TITLE
Dependency deprecated

### ISSUE THREAD

**Issue by space-curiosity** [Automattic/simplenote-electron#357]
#### Steps to reproduce

On npm install got warnings for Dependency deprecated
#### What happened instead

Got warning on npm install. here are the list of warnings:

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated electron-packager@5.2.1: Critical security bug fixed in v7.0.0 - read more at https://github.com/electron-userland/electron-packager/issues/333
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
#### OS version

windows 10

**Comment by dmsnell** [comment]
Thanks @space-curiosity. Some of these are probably legitimate while others are probably stuck this way due to being dependencies of dependencies.

Are you looking to start contributing? This would make for some great first PRs. You can use a convenient tool [npm check updates](https://www.npmjs.com/package/npm-check-updates) to see which dependencies are out of date. Then, probably one or a few at a time, submit a PR to update the versions. We only need to make sure that we test functionality for regressions on version bumps. Before testing, it's good to `rm -rf node_modules` to clear out lingering state.

**Comment by owcz** [comment]
Here's the state of the current dependency warnings:
```sh
$ npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.6.0 should be installed with -g
```

1. Latest Simperium is in use. Blocked by Simperium/node-simperium/pull/44.
```sh
$ npm ls node-uuid
simplenote@1.0.8
└─┬ simperium@0.2.5
  └── node-uuid@1.4.8 
```

2. Update `electron-builder@16.7.1`. Creates new dependency discussed here: electron-userland/electron-builder/issues/1344.
```sh
$ npm ls minimatch
simplenote@1.0.8 
├─┬ babel-core@6.21.0
│ └── minimatch@3.0.3 
└─┬ electron-builder@2.8.4
  └─┬ electron-winstaller-temp-fork@2.0.5-beta.3
    └─┬ fs-jetpack@0.7.3
      └── minimatch@2.0.10 
```

3. Tried to add `"preinstall": "npm install -g node-gyp",` which failed. Blocked by sass/node-sass/issues/1740.
```sh
$ npm ls node-gyp
simplenote@1.0.8
└─┬ node-sass@4.1.1
  └── node-gyp@3.6.0 
```
