### ISSUE TITLE
Build error when I followed steps `npm run build`

### ISSUE THREAD

**Issue by artivilla** [Automattic/simplenote-electron#359]
#### Steps to reproduce
1. Running on mac 10.11.6 with node v4.4.7 and npm v2.15.8.
2. `npm run build` won't work if your parent folder has a space it's in name.
#### What I expected

Expected electron to start running locally.
#### What happened instead

npm thew and error and said it can't find the file or folder.
#### What happened instead

10.11.6
#### How did I fix this error

I just changed my projects parent folder name to a single word.

**Comment by dmsnell** [comment]
Thanks for the report @artivilla! We will try and address this soon so that it won't cause any more headaches

**Comment by roundhill** [comment]
I revisited this and tried renaming the parent folder to have a space in it, and it built just fine 👍
