### ISSUE TITLE
Search: Notes not in results despite containing search term

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-electron#360]
#### Steps to reproduce
1. Create several notes (4 or more) of varying length. Make sure that all notes contain at least one instance of the same word. Word must be 6 characters or longer. Capitalization doesn't matter.
2. Start typing the word in the search box. 

#### What I expected
For all notes containing the search term to be listed

#### What happened instead
At the first letter of the search term, one of the notes already does not appear in search results.

As I type more letters of the search term, up to half the notes containing the term don't appear at all in the final results.

There does not appear to be any pattern in which notes are not included, at least not what I can see.

#### OS version
version 1.0.2 in Windows 7. The user who reported the issue (2779459-t) also found the same on Linux. They didn't specify which version.

#### Screenshot / Video

![capture](https://cloud.githubusercontent.com/assets/11873759/17743078/d0bdd836-64a2-11e6-84bf-1d05d6946980.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11873759/17743079/d1055288-64a2-11e6-954a-f6d5fadf48c8.PNG)
![capture3](https://cloud.githubusercontent.com/assets/11873759/17743082/d1cec62c-64a2-11e6-8054-65aa69c96ccb.PNG)
![capture4](https://cloud.githubusercontent.com/assets/11873759/17743083/d1d5305c-64a2-11e6-82c9-532c7541aedc.PNG)

**Comment by dmsnell** [comment]
Thanks for the report @KokkieH. I couldn't reproduce this error but we did recently update the search mechanism. Would you be willing to try again with the latest build/version and let me know if you are still seeing this bug?

**Comment by KokkieH** [comment]
@dmsnell Confirmed in version 1.0.5 I can no longer reproduce this, so it appears to be fixed. I'll also follow up with the user who made the original report.

**Comment by KokkieH** [comment]
User also confirms the issue is fixed. Closing.
