### ISSUE TITLE
Add Ubuntu tray support

### ISSUE THREAD

**Issue by october21** [Automattic/simplenote-electron#362]
Hello! Please add support of minimize to Ubuntu tray.

**Comment by roundhill** [comment]
What's this mean exactly?

**Comment by october21** [comment]
![tray](https://cloud.githubusercontent.com/assets/5104118/17988859/127c9cc4-6b3a-11e6-8b79-d4728726e9fd.png)

To there

**Comment by sercba** [comment]
Please!

**Comment by lekseven** [comment]
+1

**Comment by drw158** [comment]
Looks like this would be the equivalent of adding SN to the Mac menu bar, which we haven't done for the Mac app. Not sure what functionality we would put there.

**Comment by dmsnell** [comment]
For anyone wanting this in Ubuntu or Gnome, have you tried [AllTray](https://apps.ubuntu.com/cat/applications/oneiric/alltray/)?

I'm not sure how much we would end up doing to meet specific distribution needs so maybe a third-party solution like that could work.

It looks like we might be able to provide some level of support through [Electron](https://github.com/electron/electron/blob/31b4f61815cc25bef7804be304136a0074ea9b0c/docs/api/tray.md) but we haven't tried this yet.

❓what would we put in the tray? I can think of an option to start a new note and maybe one to exit out of the app. Any others?

**Comment by october21** [comment]
>I'm not sure how much we would end up doing to meet specific distribution

Do it for Unity and Gnome because these desktop environments on most popular distributions.

>have you tried AllTray?

Third-party not cool. This is a task that should do the application

> what would we put in the tray? I can think of an option to start a new note and maybe one to exit out of the app. Any others?

I think create note, open main window of application and exit.

**Comment by drw158** [comment]
![screen shot 2016-11-04 at 11 35 08 am](https://cloud.githubusercontent.com/assets/618551/20013873/c976107a-a282-11e6-930d-b13022038434.png)

**Comment by dmsnell** [comment]
Note: although I didn't push anything up I was able to experiment and get a working prototype working in Mac. The code wasn't too complicated but I think this is the list of steps we need to complete before we can resolve this:

 - [ ] A good design of the task bar item: what icon to use and which actions/items to provide in the menu
 - [ ] IPC between the main process and the renderer which can invoke actions such as "Add a new note." We currently have some simple IPC established for handling changes to the display settings from the menu bar.

**Comment by natanielcz** [comment]
Ubuntu with Unity is no longer developed and Gnome shell has no tray. 
Should we still consider this feature?

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests! Added to a more general tray support feature request.
