### ISSUE TITLE
Translate app linux to Spanish

### ISSUE THREAD

**Issue by jgjimenez** [Automattic/simplenote-electron#363]
I installed the version of android and this to Spanish, but not linux. as I can help translate them into Spanish for this app

**Comment by roundhill** [comment]
We'd love help with translations, but unfortunately the app isn't currently set up to support other languages. We'll get back to you ;)

**Comment by dmsnell** [comment]
I'm going to close this issue since we both won't be addressing it soon _and_ translations will remain 100% on our radar without needing the issue to remind us :wink: 🌐

**Comment by drw158** [comment]
cross linking the main issue: #16
