### ISSUE TITLE
Error processing argument at index 0

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/simplenote-electron#364]
A user submitted this error message via email. They report they're using Windows 10.

![12c76e685d4217891095b8d9dd4c7020](https://cloud.githubusercontent.com/assets/8002138/17867045/abcd1bf4-685d-11e6-8b57-5d6d979a3e8b.png)

**Comment by roundhill** [comment]
Is this meant for https://github.com/automattic/wp-desktop?

**Comment by chrisfromthelc** [comment]
Derp. Yes. I'll repost there.
