### ISSUE TITLE
Ability to import text notes (from Evernote)

### ISSUE THREAD

**Issue by valasek** [Automattic/simplenote-electron#365]
Add the feature to import notes. Source can be plain text or maybe other formats - markdown.
Actually return it back as I can read here - "Ever2simple was initially created as a way to import Evernote files into Simplenote, but Simplenote no longer supports importing TXT files, so it’s useless for that"- http://lifehacker.com/how-to-jump-ship-from-evernote-and-take-your-data-with-1782841075).

**Comment by dougmorin** [comment]
I'm surprised this hasn't gained more traction.  This is going to be the best way to get users to migrate away from either evernote or icloud.

**Comment by hmijail** [comment]
I was a long-term Simplenote user. I switched to macOS Notes about 3 months ago because it offered some features over Simplenote (like Spotlight integration). But Notes has its own share of bugs and problems, and Simplenote has grown enough of those missing features to give it another try. Alas, there is no way to import notes into Simplenote, so I can't migrate back.

(Exporting the notes from Notes is not trivial in itself, and I already opened a bug with Apple about that, but still might be doable through AppleScript. But without a way to import into Simplenote there's no point... please don't make me script the GUI ;P)

**Comment by dmsnell** [comment]
Thanks for posting here all. Making it easier to get notes into Simplenote from other applications is something we certainly want to accomplish. We recently added the ability to export notes out of Simplenote from this version of the application, but this was the easier of the two sides of integration.

At this point we have other priorities for the next couples releases focused on some pain points in the user interface and with the process of logging in and out of accounts. At or around that time I think we might be able to more realistically focus on adding in some kind of import feature.

That being said we can certainly discuss what we would want or need from imports, what kind of file structure we would require (I could imagine having external tools to convert exports from various apps into a unified format for import into Simplenote), and what kind of effects an import would have (would we create a tag on all the imported notes, for example?).

Thanks again for your input! We're always happy to support any help offered here and can work with PRs submitted outside of our own development timelines and flows.

**Comment by dougmorin** [comment]
Where I agree with what you say @dmsnell, unless you provide an import utility you're not going to see the normal influx in users who might be willing to try the app with their existing notes.  Especially someone like me who has a ton of notes.

**Comment by seanmmasters** [comment]
Random new user here: I'll cutover to Simplenote and keep Evernote as an archive. See how far I get before going insane. For reference I have about 5,000 notes in Evernote, but anything actionable I'll just make new notes/lists for and then the rest is just reference material.

**Comment by gerv** [comment]
Here's my hacky desktop script to move notes one at a time from Tomboy to Simplenote. Could be adapted for other systems, no doubt.
https://gist.github.com/gerv/f7a9fbf64a9a259593321ae6d9d32e9e

**Comment by gerv** [comment]
Also, with a little massaging of the data, you can use sncli for this:
https://github.com/insanum/sncli

**Comment by ChrissiePollock** [comment]
Requested again in #1118368-zen

**Comment by iamgabrielma** [comment]
Requested in #1141390-zen

**Comment by nebososo** [comment]
Requested in #1162186-zen

**Comment by DrSpaldo** [comment]
I would also like to see this. I would have hoped this would take priority over exporting (losing your users) and other features. Importing notes means you can get more/new users. I would like to try your note product, but, without the import function there is no way I can try it. I can only suggest this feature be given priority so you can gain new users.

**Comment by Robertght** [comment]
+1 on this. Ref: #1428501-zen

**Comment by mirka** [comment]
Finally! We can start building this importer!

Closing in favor of #916
