### ISSUE TITLE
Enhancement : Adding support for pin code similar to what is present in the android app

### ISSUE THREAD

**Issue by manu-chroma** [Automattic/simplenote-electron#366]
I find the PIN lock feature present in the android app very useful. 
Would love to see it in the desktop client as well.

**Comment by ggyanez** [comment]
+1 to this request please!

This is a must.

**Comment by ggyanez** [comment]
+ 1 to this request please!

This is a must. Specially for those of us that want to use Simplenote as a private/protected daily journal.

Btw, after trying Evernote, Google Keep and others, Simplenote is the best. Keep up with then great work!

**Comment by drw158** [comment]
Dupe of #278
