### ISSUE TITLE
is this also the web app at app.simplenote.com?

### ISSUE THREAD

**Issue by nfcampos** [Automattic/simplenote-electron#367]
Sorry to open an issue just for asking this but is the react app in this repo the one at https://app.simplenote.com or is this only used for the electron app and the web app is a separate code base? the web app doesn't appear to be rendered with react from a quick inspection. do you have plans to open source the web app as well? or maybe replace it with this react version?

**Comment by roundhill** [comment]
We don't have any plans to open source the current web app, as we'd like to replace it eventually with this app.

Here's a version running on our app engine host. You can try it out at your own risk! https://electron-dot-simple-note-hrd.appspot.com/

**Comment by nfcampos** [comment]
I see. The version running at that url looks pretty cool! Curious, anything in particular stopping you from replacing the web app with this?

**Comment by roundhill** [comment]
> anything in particular stopping you from replacing the web app with this?

I think just lots of testing! A lot of the users rely on the web app every day, so we'll want to make sure it's rock solid, or offer both web apps in a non-confusing way.

**Comment by nfcampos** [comment]
this is already supposed to work in a browser, right?
i cloned this repo, ran `npm i`, ran `npm start` and when i go to the app on the browser it redirects to `app.simplenote.com`... any idea why?

**Comment by roundhill** [comment]
You probably haven't added a simperium app key to `config.js`: https://github.com/Automattic/simplenote-electron/blob/master/README.md

**Comment by nfcampos** [comment]
Thanks, sorry about that, should have paid more attention to the readme
