### ISSUE TITLE
Link detection like in iOS or Mac app

### ISSUE THREAD

**Issue by nfcampos** [Automattic/simplenote-electron#368]
Hi,

This looks great!
I'd like to see link detection (like in the mac and ios apps) added. Is that something you'd want?

From a cursory look at the code for the `NodeDetail` component it seems that doing this would require replacing the `textarea` element with a `<div contenteditable />` (maybe using https://github.com/facebook/draft-js) because text inside a `textarea` is not style-able in any way (as  far as i know). Is this something you'd be ok with? If so I can take a stab at this

Nuno

Also Reported in:
 - #985556-zen
 - #1118368-zen
 - #1194082-zen

**Comment by roundhill** [comment]
Yes, please! I think I tried `contenteditable` for a while but it gave me problems which of course I don't recall. Go for it!

**Comment by nfcampos** [comment]
Cool, I'll open a PR when I have something!
In the meantime, would you accept a PR updating this to use babel 6? the version you're using currently doesn't work with node 6

**Comment by roundhill** [comment]
Maybe, I think we'd need to test our desktop app packager to see if it works with node 6. cc @rodrigoi

**Comment by nfcampos** [comment]
you could keep using node 5, updating babel would simply allow me (and everyone else) to develop using node 6, but it'd still be totally compatible with node 5, unless I misunderstood what you wrote?

**Comment by nfcampos** [comment]
but honestly I can just use node 5 for this, it doesnt realy matter to me

**Comment by dmsnell** [comment]
@nfcampos it's probably best to work within node 5 for this PR. an update would be an entire PR by itself is my guess, and probably also something that wouldn't happen quickly enough to be in there before this work gets merged

**Comment by nfcampos** [comment]
ok, no problem

**Comment by nfcampos** [comment]
opened PR replacing textarea with draft.js editor :) the link detection, styling will follow

**Comment by memeplex** [comment]
The web app neither shows urls as links.

**Comment by tmchartrand** [comment]
this would be great on Linux too!

**Comment by katinthehatsite** [comment]
A user in 985556-zen also asked for the feature to be added on Windows and reported links not being detected.

**Comment by ChrissiePollock** [comment]
Requested again in #1118368-zen.

**Comment by serabi** [comment]
Requested . again in #1194082-zen

**Comment by laoyuan** [comment]
need this!

**Comment by crankygeologist** [comment]
I would likely switch from the native Mac version to the web app or Electron flavor if they had if link detection.

**Comment by roman-yagodin** [comment]
Vote for it!

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
