### ISSUE TITLE
Keyboard bindings/shortcuts

### ISSUE THREAD

**Issue by beaucollins** [Automattic/simplenote-electron#37]
Make the UI keyboard navigation enabled:
- [x] Navigate and select a note - <kbd>CmdOrCtrl</kbd> + <kbd>Shift</kbd> + <kbd>Up</kbd>/<kbd>Down</kbd>/<kbd>j</kbd>/<kbd>k</kbd>
- [x] Open and navigate tag menu - <kbd>CmdOrCtrl</kbd> + <kbd>Shift</kbd> + <kbd>t</kbd>
- [x] Global binding to focus search field - <kbd>CmdOrCtrl</kbd> + <kbd>Shift</kbd> + <kbd>f</kbd>
- [x] Toggle markdown preview - <kbd>CmdOrCtrl</kbd> + <kbd>Shift</kbd> + <kbd>p</kbd>
- [x] Open/focus list view - <kbd>CmdOrCtrl</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd>
- [ ] ~Trash current note~

The app should be fully usable without a mouse.

**Comment by drw158** [comment]
I think we should also add keyboard shortcuts for basic MD formatting, maybe only available if they have MD on?

- bold
- italic
- link
etc.

**Comment by gerv** [comment]
Even better, automatically turn MD on if someone presses Ctrl-B, Ctrl-I etc. with selected text.

**Comment by dorianbrown** [comment]
Has this issue been solved, or just closed? I can't find any infomation about what the shortcut is if it was.

**Comment by drw158** [comment]
Looks like the issue was solved by #603
