### ISSUE TITLE
Tab not working ubuntu 16.04

### ISSUE THREAD

**Issue by tkuraku** [Automattic/simplenote-electron#372]
App Version 1.0.3

#### Steps to reproduce
1. download .deb package and install using software center ubuntu 16.04
2. Create new note
3. Press tab

#### What I expected
The standard indentation to happen.

#### What happened instead
Instead my cursor jumped to the "Add tags" field at the bottom of the window

#### OS version
ubuntu 16.04

**Comment by lekseven** [comment]
Same issue. The bug makes almost impossible formatting code sections in the markdown mode.

**Comment by dmsnell** [comment]
I'm closing this issue because it's a duplicate of #299 and we will resolve it there. Thanks for reporting it!
