### ISSUE TITLE
DEVELOPMENT: Failed at the react-popover@1.0.1 postinstall script 'npm run build'. 

### ISSUE THREAD

**Issue by deadstar1** [Automattic/simplenote-electron#375]
hi I have tried install simple-electron via git, This error occurs, `npm ERR! Failed at the react-popover@1.0.1 postinstall script 'npm run build'.
npm ERR! This is most likely a problem with the react-popover package,
npm ERR! not with npm itself.`.

#### OS version
I have tried to install simplenote-electron in ubuntu and windows 8, The same error is occur after `npm install` where issued.

#### Screenshot / Video

![image](https://cloud.githubusercontent.com/assets/6646675/18195782/24ca64a6-7120-11e6-86e3-ea562254093b.png)

[npm-debug.TXT](https://github.com/Automattic/simplenote-electron/files/451338/npm-debug.TXT)

**Comment by dmsnell** [comment]
thanks for reporting @deadstar1! I'm closing this out after the merge of #348. Please open it back up if it continues to be a problem (after fetching the updates to **master**)
