### ISSUE TITLE
missing dependencies in deb package v1.0.3

### ISSUE THREAD

**Issue by kaepuo** [Automattic/simplenote-electron#377]
#### Steps to reproduce
1. download deb package v1.0.3
2. install `dpkg -i simplenote-1.0.3.deb`
3. install dependencies `apt-get install -f`  (=> NOTHING!)
4. run `./simplenote` (==> missing packages, e.g. `libgconf-2-4` and `libnss3`
#### What I expected

i expected `apt-get install -f` to install missing dependencies
#### What happened instead

nothing, i.e. i had to execute `./simplenote`, read the error message, install the depencies, over and over again.
#### OS version
- Ubuntu 16.04.1 LTS
- Linux 4.7.1-040701-generic

**Comment by naxsooley** [comment]
@kaepuo I'm using Simplenote v1.0.3 and it works well under Ubuntu 16.04.1 LTS.

**Comment by roundhill** [comment]
Haven't seen any recent reports of .deb issues, closing this one.

**Comment by asamats** [comment]
I downloaded Simplenote-linux-1.5.0-amd64.deb, installed and I'm trying to run but it isn't opening.
After that I tried to run from cmd and got this message "simplenote: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory"

OS version: Ubuntu 18.04.2 LTS

**Comment by Saavestro** [comment]
I have the same problem

**Comment by Saavestro** [comment]
Still not working in Ubuntu 18.04.2

**Comment by arpol** [comment]
Getting this when trying to install Simplenote 1.8.0-5718 on Ubuntu 16.04.1:
> simplenote: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
