### ISSUE TITLE
Awesome app but need some improvement

### ISSUE THREAD

**Issue by himaanshu24** [Automattic/simplenote-electron#380]
1. In list view of all the notes, it should show preview text by default.
2. Same thing with note panel, instead of default edit mode show preview mode. (Same for mobile)
3. Color highlight of word/statement
4. background control of note (color/image)
5. Shortcut key binding (with custom) for formatting things

**Comment by roundhill** [comment]
Thanks for the feedback! Please use search to see if issues have already been filed. If it hasn't been filed yet, feel free to file one separately. 

Since a lot of these are duplicates I'm going to close this.
