### ISSUE TITLE
Preview mode in defaults

### ISSUE THREAD

**Issue by october21** [Automattic/simplenote-electron#381]
When I open a note it opens in Edit mode, but but it would be nice to specify the default mode in the settings
#### Steps to reproduce
1. Just click to created note
#### What I expected

Setting for open note in preview by default
#### What happened instead

Note opens in Edit mode
#### OS version

Ubuntu 16.04

**Comment by drw158** [comment]
Unfortunately there are no plans to implement a feature like this.

**Comment by fregs7** [comment]
I achieved that in a rather hacky way by modifying the `resources/app/dist/app.js` file.
You have to look for the following part:

    namespace: 'App',
    initialState: {
        editorMode: 'edit',

And change `edit` to `markdown`.

Of course, this is totally a hack, but I want this behavior and this is the only way to have it, as there will be no support for this apparently. I wonder why.

**Comment by drw158** [comment]
An elegant way to implement this in Simplenote, is for the app to remember the last view mode you were in. Right now, if you restart the app, it reverts back to the editor as the default view.

**Comment by mirka** [comment]
I'm concerned that persisting the Preview mode state across app relaunches would cause usability issues. For notes that don't contain a lot of Markdown syntax, the Edit/Preview modes aren't that different visually. It may be disorienting to launch into a mode where you expect to start editing a note, but can't, and take some time to discover why.

**Comment by rob-maidment** [comment]
So, we fixing this? I think edit should be the default, principle of least surprise in a note-taking app

on ios mobile it's not (and cannot be) the default, don't know about droid but I'd guess also a swipe-left only

**Comment by mirka** [comment]
Yeah, I guess the current behavior is ideal then. The mode will be preserved when selecting another note, but the app will always launch in Edit mode.
