### ISSUE TITLE
Mathematics support

### ISSUE THREAD

**Issue by TileHalo** [Automattic/simplenote-electron#383]
Hi!
Thanks for the great software! I'd like to ask if it is possible to add mathematics support to markdown? Sorry if this is in wrong place.

**Comment by drw158** [comment]
If it's supported by Markdown, it should be available, or easily added. What kind of math support did you need?

**Comment by TileHalo** [comment]
I was thinking LaTeX or AsciiMath style. And it is not supported by markdown.

**Comment by dmsnell** [comment]
@TileHalo I don't think that we would be incorporating any math typesetting soon if ever. It definitely would have advantages in certain use cases, but we're very hesitant to add new functionality into <em>Simple</em>note. Thanks for the suggestion - we'll keep it in our pool of ideas. In the meantime, we would absolutely review a fork PR if you wanted to build it. Thanks for using Simplenote too!

**Comment by nmabhinandan** [comment]
Whyyy? You only need to render it. No backend changes are required!!  😥

**Comment by cossio** [comment]
Please bring math support!

**Comment by honghuzi** [comment]
We really need math support in Simplenotes.
