### ISSUE TITLE
Out of sync. 

### ISSUE THREAD

**Issue by neelkadia** [Automattic/simplenote-electron#384]
#### Steps to reproduce
1. Open the Simplenote on Windows, write something on existing note 
2. Simultaneously open the http://app.simplenote.com
#### What I expected

It will sync as it used to sync among Android n iOS and Web.
#### What happened instead

but Syncing is not happening in this electron version 
#### OS version

Windows 8.1

**Comment by rustykeyctrl** [comment]
I too have the sync issue with Windows 10.
Finally had to copy and paste from web ver to desktop ver. Thanks for the info going to try it on my computer see if it's working.

**Comment by dmsnell** [comment]
@neelkadia and @rustykeyctrl I'm going to close this issue as a duplicate and move the discussion into #385 in order to be able to better organize it. thanks for the reports.
