### ISSUE TITLE
Search highlighting in Windows app

### ISSUE THREAD

**Issue by madhattermattic** [Automattic/simplenote-electron#395]
According to Kayako ticket #2850777:

"I think it would be great idea for the Windows app to highlight the word I am searching for inside the note (similar to what's being done in browsers).

It's especially useful for long list notes."

OS Version: Windows

**Comment by dmsnell** [comment]
Thanks for reporting @madhattermattic - we are currently planning on pushing this out at some point but it's not at the top of the list.

**Comment by suaracahaya** [comment]
It has been requested since last year: https://github.com/Automattic/simplenote-electron/issues/52

**Comment by dmsnell** [comment]
Should be resolved with the merge of #424
