### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#40]
Ensure that whatever Electron integrations we are using for menus, sharing, etc work well on Linux. I'm guessing we'll probably distribute this through for gnome and kde desktop environments?

**Comment by user501254** [comment]
Hi, any plans of providing rpm packages?

**Comment by jeremeylduvall** [comment]
@roundhill related to the user above, the user in #2794476-t was also wondering about an rpm package. Is this something we're looking at in the future or not on the radar right now?

**Comment by arturtr** [comment]
I also need RPM because of using Fedora.
