### ISSUE TITLE
How do I disable Developer Telemetry?

### ISSUE THREAD

**Issue by linickx** [Automattic/simplenote-electron#404]
It appears to me that every time I search, on top of the API call, there is an additional query to pixel.wp.com. I understand that developer telemetry is normal practice, but most applications allow users to opt out.
1. Can anyone verify the same behaviour _(i.e. to confirm my install is not broken or something)_
2. Is there a privacy setting somewhere that I've missed?
#### Steps to reproduce
1. Install Simplenote and log-in, then exit
2. Open Fiddler or Wireshark, start network capture
3. Open Simplenote
4. Search for something
5. Observe/Capture requests to pixel.wp.com
#### OS version
- Windows 10 (Enterprise) - 64bit - Build 14393.2222 
- Simplenote 1.0.3
#### Fiddler Screenshot

![simple_note_telemetry](https://cloud.githubusercontent.com/assets/649661/19382661/29859b24-91f9-11e6-9080-8c9cecffa972.PNG)

**Comment by roundhill** [comment]
The app captures some anonymous statistics to help us improve the app. We don't currently have an option to turn it off, so I agree that an adding opt-out is a good idea.

**Comment by dmsnell** [comment]
@roundhill here is a perfect scenario for the analytics middleware like we started using in Calypso. If we have a toggle then all we need to do is toggle the middleware on and off with the setting. We can continue to program as though it were enabled, but those actions will simply fall to the bit bucket.
