### ISSUE TITLE
Add an option to lock a note

### ISSUE THREAD

**Issue by popod** [Automattic/simplenote-electron#405]
Add an option to lock a note (to prevent delete the note). When this option is enabled, the note cannot be deleted !

**Comment by dmsnell** [comment]
Hi @popod. Although we don't currently have any note locking mechanism, did you know that when you delete a note it's still available if you list the trashed notes? We can restore accidentally (or intentionally) deleted notes from the trash view.

**Comment by popod** [comment]
Yes, I know that. But it will better if you could add a "lock" option to each note (same as pin to top option) and if this option is set juste disabled the "delete" or "move to trash" item in menu ;)

I think it is easy to implement ? What do you think about this new function ?

**Comment by roundhill** [comment]
I don't think we need to clutter up the UI with something like this, when you can just restore the note from the trash if you accidentally delete it, like @dmsnell described.

**Comment by danvilar** [comment]
Although, a locking mechanism to avoid the note being edited until you unlock it again would be useful.
