### ISSUE TITLE
Pressing PageUp/PageDown Keys Causes Layout Bug

### ISSUE THREAD

**Issue by laskin82** [Automattic/simplenote-electron#408]
#### Steps to reproduce
1. create new note (or open existing)
2. write some text
3. push PgUp or PgDown
4. got a bug

#### What happened instead
app is open side bar and you cant close it. the left side bar is blocked.

#### OS version
Windows 7 x64

#### Screenshot / Video
![default](https://cloud.githubusercontent.com/assets/16285422/19547817/4377f7e4-96a3-11e6-9828-913e87bb8764.png)

**Comment by roundhill** [comment]
Did those keys previously scroll to the top/bottom of the editor?

cc @nfcampos

**Comment by laskin82** [comment]
yep. i check it.

**Comment by arshsingh** [comment]
Not sure how to reproduce this, but I encountered this bug on Ubuntu 16.04 (Simplenote 1.0.5) as well

**Comment by nfcampos** [comment]
hmm, I don't gave PgUp / PgDown keys on my keyboard (i'm on a mac) so I'm not sure how to reproduce this. The equivalent keys on the mac (cmd+upArrow / cmd+downArrow) do work for me to scroll to the top/bottom of the editor.

**Comment by roundhill** [comment]
> I don't have PgUp / PgDown keys on my keyboard (i'm on a mac)

I'll have a look, I have a keyboard with these keys.

**Comment by drw158** [comment]
I think I encountered this same bug (info sidebar open and stuck) while testing the new tab PR.
