### ISSUE TITLE
Request: Select edit tab when adding a new note

### ISSUE THREAD

**Issue by arshsingh** [Automattic/simplenote-electron#410]
#### Steps to reproduce
1. Select preview tab in any note
2. Add a new note
#### What I expected

When adding a new note, I expect the editor to be in edit mode, so that I can start typing
#### What happened instead

New note opens in preview mode which is not useful since there is no content
#### OS version

Ubuntu 16.04

**Comment by dmsnell** [comment]
Thanks for the report @arshsingh. This behavior doesn't make sense and we will put it on the queue for updating!
