### ISSUE TITLE
X to clear search (feature request)

### ISSUE THREAD

**Issue by owcz** [Automattic/simplenote-electron#411]
The feature I miss most from other versions of SN is the one-click ability to clear the search field. Perhaps it's just the spoils of Mac but the white X in a gray circle in the right corner of the search box was a really easy way to clear it out while refocusing the app. Now it takes several clicks to select all text and begin to type.

**Comment by dmsnell** [comment]
@owcz this sounds like a great idea - thanks for reporting! I'm sure this wasn't a decision we made to not include the `x` - more like it was something we weren't able to polish in time for the earlier releases. I'll take a look and see how much work it will take to get in. If not much, we can probably sneak it in soon :smile:

**Comment by drw158** [comment]
#481
