### ISSUE TITLE
Pg Down/Up opens sidebar after update to version 1.0.5

### ISSUE THREAD

**Issue by marianoju** [Automattic/simplenote-electron#421]
#### Steps to reproduce
1. Update to Simplenote version 1.0.5 
2. Open note and press Pg Down or Pg Up. 
3. Observe Info sidebar on the right (shows: Modified Date, word count, character count, Pin-to-top toggle, Markdown toggle). 
4. Click X in upper right corner. 
5. Click (i) symbol (next to History, Share and Trash symbols on the top). 
6. Click X in upper right corner again. 

#### What I expected
1. I expect Pg Down and Pg Up to scroll up or down in documents as is customary, and used to work up to Simplenote version 1.0.5. 
2. I expect a click on the X in the upper right corner always to close the Info sidebar. 

#### What happened instead
1. Pressing Pg Down or Pg Up opens Info sidebar 
2. Closing Info sidebar is only possible after first clicking (i) symbol. 

#### My Configuration
- Ubuntu 16.04.1 LTS (Xenial Xerus) 64-bit
- Kernel Linux 4.4.0-45-generic
- GNOME 3.18.3
- Memory: 7.5 GiB
- Processor: Intel® Core™ i5-3320M CPU @ 2.60GHz × 4

#### Screenshot / Video
![screenshot from 2016-10-28 09-40-43](https://cloud.githubusercontent.com/assets/6254428/19800149/b60cea64-9cfa-11e6-8f43-b0795f79e93e.png)
![screenshot from 2016-10-28 09-41-19](https://cloud.githubusercontent.com/assets/6254428/19800156/bded8126-9cfa-11e6-8da8-5db50f50ab2c.png)
![screenshot from 2016-10-28 09-41-29](https://cloud.githubusercontent.com/assets/6254428/19800159/c0b4ff06-9cfa-11e6-9060-4599a1094a9b.png)

**Comment by dmsnell** [comment]
Thanks for reporting this @marianoju! We actually already discovered this and @roundhill patched it up in #419. We'll be shipping an update very soon with the fixed behavior.
