### ISSUE TITLE
Login: Is it possible to use Simplenote without signing in. (offline mode)

### ISSUE THREAD

**Issue by zhangzhishan** [Automattic/simplenote-electron#423]
#### Steps to reproduce
1. My computer cannot access to the internet, but the app needs to signing in.

#### What I expected
Is it possible to make it can use without an account

#### OS version

Windows 10

**Comment by dmsnell** [comment]
Thanks for filing the issue @zhangzhishan. Right now it's not possible to start using the app without having a login. It _is_ possible on the mobile apps, or at least on Android, but not on the desktop. it's important to know, however, that using Simplenote without an account means that the notes won't be synchronizing anywhere.

If you can create an account when you _do_ have internet, then you should be able to sign in to the app and it will keep you logged-in even after you lose internet access. That is to say, after logging in once you should be safe.

@roundhill or @drw158 is there a reason for the inconsistency between the platforms on this? is being able to use the app without an account the ideal? is the risk of losing data/confusion of not syncing when not having an account too much of an obstacle to consider making this available on all the apps?

**Comment by drw158** [comment]
It would be great to have offline. I guess the native Mac app does this too?

**Comment by dmsnell** [comment]
> we'd need to visually indicate that the app is offline I think

That doesn't sound very Simplenote-y. Indicating that the app isn't linked to an account and therefore _not syncing_ seems very reasonable though. Would some kind of banner/bar across the top of the note view be reasonable?

**Comment by drw158** [comment]
I think so, yep. Android probably does something like that.

**Comment by zhangzhishan** [comment]
One of my computers cannot access to the Internet in some reasons, but I use Simplenote in my other computers. I only want a easy to use note app for my offline computer.

**Comment by roundhill** [comment]
The Android app's accountless UI was an experiment to see how valuable it was to users. I think it has proved to be useful by a very small minority.

**Comment by roundhill** [comment]
And I'll add that there were quite a few bugs related to that feature, I'd have to try and remember what those gotchas were before we attempt something like this.

**Comment by zhangzhishan** [comment]
Thank you so much.

**Comment by dmsnell** [comment]
I'm closing this issue because I believe we will not implement logged-out use of the app.

**Comment by gsbhasin123** [comment]
Any update on this? I want to have my notes synced offline, I don't care for online storage

**Comment by dmsnell** [comment]
Hi @gsbhasin123 - if we were to decide to open up using the app without an account we'd be announcing it on our blog.

It's very possible and normal to use Simplenote offline but when there's no account it ended up causing a variety of confusing and troublesome issues. We have discussed this feature over and over again but right now nothing has changed.

If anyone else is wondering if anything has changed then it probably hasn't, as something this big we would announce 😀

We're glad you like Simplenote. If you want to talk about the limits of online storage you can reach out to us at support@simplenote.com.

**Comment by gsbhasin123** [comment]
Thanks! I took a look at your Faq and apparently you provide unlimited notes, so that's great :D 

Unfortunately since Simplenote does not provide any sort of formatting (for example, a Markdown mode would be nice, you only have a checklist :( ) it's currently not a viable solution for me

**Comment by dmsnell** [comment]
> a Markdown mode

@gsbhasin123 You can check out Simplenote's Markdown support and see if it suits you. The one thing we don't have is syntax-highlighted Markdown when editing it, but if you write in Markdown you can view the rendered copy of the note and also publish it online in its rendered form.

**Comment by gsbhasin123** [comment]
Wait, simplenote has markdown? I just realized, that's great! :D 
Two things would be really useful:
- syntax highlighting
- allow docking the preview pane to the right of the editor

Are these on the roadmap?

**Comment by dmsnell** [comment]
> Are these on the roadmap?

Not really @gsbhasin123. Of course, we'd like them too, but right now we are occupied with other work and those aren't likely to come soon.

**Comment by gsbhasin123** [comment]
Ah okay - I understand. Thank you!

**Comment by zdxsector** [comment]
@codic12 I made my own offline version of this simple note called "Recall" https://github.com/zdxsector/recall-electron/
