### ISSUE TITLE
Get accent color on Windows

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#426]
Would be cool to use this to change the SN blue to whatever the user sets as their accent color on Windows. Hopefully doesn't conflict with dark theme?

![screen shot 2016-11-04 at 11 52 40 am](https://cloud.githubusercontent.com/assets/618551/20014537/6e1986fa-a285-11e6-9b15-cd9f50adb160.png)

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
