### ISSUE TITLE
Why not use Electron for OS X, too?

### ISSUE THREAD

**Issue by amontalenti** [Automattic/simplenote-electron#429]
I love SimpleNote and use it everywhere, but I really wonder why this project doesn't make OS X builds alongside the Windows/Linux builds? The "native" OS X app lacks proper Markdown support.

**Comment by dmsnell** [comment]
@amontalenti thanks for the inquiry! stay tuned, this might happen in the future!

**Comment by zeke** [comment]
See also https://github.com/Automattic/simplenote-macos/search?q=electron&type=Issues&utf8=%E2%9C%93

@dmsnell let me know if you need help making it happen.

**Comment by dmsnell** [comment]
@zeke I'm not sure if we are ready to replace the macOS app yet based on the performance of the app and the list of bugs/features.

personally I run the electron app in macOS while I'm developing. we would definitely welcome feedback from people testing it out; other than that I'm not sure what our timeline will be. we need to figure out and resolve this nasty [sync bug](https://github.com/Automattic/simplenote-electron/projects/1) before we move more over to Electron.

**Comment by zeke** [comment]
Which issue specifically? That link is to the repo's project view.

**Comment by dmsnell** [comment]
@zeke it should link to Project 1, which is the sync bug. We've had great difficulty reproducing the behavior, but sometimes the app isn't syncing data. There are several open issues related to that right now.

**Comment by zeke** [comment]
Got it! Will look into it.

**Comment by zeke** [comment]
So I just read through #354, #384, and #385. From what I can tell, it appears that these syncing problems are only affecting the Linux and Windows desktop clients (Electron), whereas no one is mentioning the Mac client (Native).

I'd going to try to reproduce it on macOS.

**Comment by amontalenti** [comment]
Adding a link here for [simplenot-electron release 1.0.8](https://github.com/Automattic/simplenote-electron/releases/tag/v1.0.8), which includes a Mac OS build. Just in case people are searching for it and come across this ticket. Thank you, SimpleNote devs.
