### ISSUE TITLE
Published note does not sync & I can't generate public URL for note

### ISSUE THREAD

**Issue by marianoju** [Automattic/simplenote-electron#430]
#### What I did 
1. Checking on a previously published note I realized it is not synchronized with current note edited with Simplenote app 
2. Tried to generate a public URL for the current note and failed (“Publishing note“ does not produce an URL, and mouse-click on “Copy” in sidebar does not copy a public link to clipboard, see screenshots). 

#### What I expected
1. I expected published notes to reflect edits after the publication. 
2. I expected to be able to generate public URL within the Simplenote client. 

#### What happened instead
None of my expectations was met, see above. 

#### My Configuration
- Ubuntu 16.04.1 LTS (Xenial Xerus) 64-bit
- Kernel Linux 4.4.0-45-generic
- GNOME 3.18.3
- Memory: 7.5 GiB
- Processor: Intel® Core™ i5-3320M CPU @ 2.60GHz × 4
- Simplenote v1.0.6

#### Screenshots

![screenshot from 2016-11-07 14-13-29](https://cloud.githubusercontent.com/assets/6254428/20059337/11a74632-a4f6-11e6-8692-0ae5d4a6bb25.png)

![screenshot from 2016-11-07 14-13-49](https://cloud.githubusercontent.com/assets/6254428/20059339/15de2c16-a4f6-11e6-90c2-96cac0693df3.png)

**Comment by roundhill** [comment]
Sometimes it can take a while for the note to publish. If you return to this note now is it published?

**Comment by dmsnell** [comment]
@roundhill I just [noticed](https://github.com/Automattic/simplenote-electron/pull/228#issuecomment-258653775) this issue when addressing #228. I'm not sure when it creeped in or why.

**Comment by roundhill** [comment]
> @roundhill I just noticed this issue when addressing #228. I'm not sure when it creeped in or why.

oh, I see. Thanks for the additional info!

**Comment by marianoju** [comment]
@roundhill Checking 19 hours later on my note it is *still* public, but
the content is garbled (mixing old and new edits, including text that
has been deleted).

Republishing of the note i.e. creating a (new?) public URL is still not
possible.

I have toggled “Make public link” but note remains public when it should
not be, and resetting note to public does not help republishing.

I have created a new note with the content of the latest version, and it
publishes within seconds. I have made edits and they are visible on
reloading the public URL.

**Comment by chaitanyamsv** [comment]
Reported by the user in #947090-zen.

**Comment by marianoju** [comment]
This bug has been unassigned for too long. I'm out.

**Comment by goryny4** [comment]
same thing for me
![82qw34cwww0qrd 1](https://user-images.githubusercontent.com/1492085/40627614-a81699e2-62c8-11e8-94fb-b198d63ba341.png)

**Comment by damiannep** [comment]
Another report in 1.1.6 in 1219109-t.

**Comment by roundhill** [comment]
This was fixed via https://github.com/Automattic/simplenote-electron/pull/749
