### ISSUE TITLE
Add scroll to bottom button for traversing long notes

### ISSUE THREAD

**Issue by dartiss** [Automattic/simplenote-electron#431]
A user has requested an enhancement to allow quick scrolling to the bottom of long notes...

> My note often accumulate quite long. Every time i want to add some more text to this note, i have to scroll for some time until reaching the bottom. It's quite annoying for me and other user who also keep a long note.
> 
> I suggest to add a little button, one pressed, it scroll to the end instantly.
> 
> To still keep it simple. I suggest this button only show up in long note we opened and it disappear if untouch in first command to keep the simplicity we love.
> 
> It's especially useful in mobile app.

As the user says, I think this is more a mobile app improvement but it's certainly worth considering with all platforms (I'm cross-posting this for all platforms).

Ticket is #2909376-t.

**Comment by drw158** [comment]
My suggestion is to record the last position of the user's cursor. Alternatively, placing the cursor at the end of the note could be the default, instead of the top of the note.

**Comment by dmsnell** [comment]
@drw158 am I missing something big? positioning the cursor at the end seems very counterintuitive to me. I may use notes differently, but I think an overwhelming majority of the time I spend in notes is reading old ones and I usually start at the top.

remembering the cursor spot is something I could imagine getting pretty complicated technically. do we have any examples in other apps that do this? I would like to play around with it and feel how it is.

**Comment by drw158** [comment]
I could be wrong, but think Microsoft Word does this. I haven't been able to test. Ulysses for Mac seems to save the cursor state, which is nice (not sure if that is cross-platform).

It's good to remember the use case of our app, which unfortunately is a wide range for us. I think it's safe to say that most people use SN for short-form notes, so keeping the cursor at the  top makes sense. Based on the conversation on Slack, I don't think it's feasible to come up with a good solution for this.
