### ISSUE TITLE
Introduce Folders and/or Tree Structure

### ISSUE THREAD

**Issue by dartiss** [Automattic/simplenote-electron#432]
A user would like to request the introduction of a more advanced note structure - a tree and/or folders.

> Your app Simplenote is really great! I use it everyday.
> 
> However, I usually transfer the notes Simplenote in a document on Google Drive because GD has a tree of files and folders. Although the tags are very convenient but if you had a tree of files and folders I would use only your solution.

As this applies to all the platforms, I'm cross posting this on all the issue logs.

Ticket is #2909181-t.

**Comment by drw158** [comment]
We get this one a lot, but we have no plans to ever change the tagging system.
