### ISSUE TITLE
Tag list sidebar should be a toggle

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#433]
Sounds easy, but actually quite hard to design for. I sketched a lot of different ideas, and researched a lot of apps. Here is what I've found for us.

First, the current design is great for mobile, and aligns the design with iOS/Android. Having a responsive layout for Simplenote Electron actually has nice benefits, one being the ability to set a very small width and still be functional. Most native apps have a large minimum window size because they are not responsive. 

I think whatever kind of layout changes we do to solve this tag sidebar issue will need to stay on desktop only. At small widths, the design stays the same as it is now.

![screen shot 2016-11-07 at 4 00 00 pm](https://cloud.githubusercontent.com/assets/618551/20077748/422cef3e-a503-11e6-84a1-62c8caf48bb4.png)

---

Proposal:

Red box is the OS chrome

![screen shot 2016-11-07 at 4 02 23 pm](https://cloud.githubusercontent.com/assets/618551/20077817/9ba82eac-a503-11e6-87e2-737c0ec4bc71.png)

Instead of a tag sidebar icon, it's now a 3 state layout toggle. 3 pane, 2 pane, and editor only. Clicking this button just cycles through each of the 3 layouts.

![screen shot 2016-11-07 at 3 41 32 pm](https://cloud.githubusercontent.com/assets/618551/20077886/d7d0e9be-a503-11e6-8cd3-efa16dd68599.png)

By moving the search bar to inside the notes list, the layout is free to change, and the top icon bar is static. When you have a layout toggle button, you don't want it jumping around.

Doing this will also allow us to do things like:

![screen shot 2016-11-07 at 4 06 56 pm](https://cloud.githubusercontent.com/assets/618551/20077972/4061f9d2-a504-11e6-8e84-172ad33bce80.png)

**Comment by drw158** [comment]
The Info button and sidebar also become a toggle, but that has no effect on what I mocked up.

**Comment by drw158** [comment]
Also, you might notice there is a lot of space in the top bar, enough for the search bar. We could do this, but having the search bar in editor only mode would be counterintuitive. Maybe it's just hidden in that mode?

**Comment by roundhill** [comment]
Interesting idea! Should be fairly easy to build this and try it out.

**Comment by belcherj** [comment]
@SylvesterWilmott Take a look at this. Closing as the design has diverged since this request.
