### ISSUE TITLE
v1.0.6: Preferences Tab doesn't List Writing on Linnux Ubunto 64 bit

### ISSUE THREAD

**Issue by gracie** [Automattic/simplenote-electron#435]
#### Steps to reproduce
1. Navigate to File --> Preferences

#### OS version
Linnux Ubunto 64 bit

#### Screenshot / Video
https://cloudup.com/ch_DXBulAJf

Reported in #2898462-t

**Comment by roundhill** [comment]
We removed this setting in the latest release. The markdown switch is in the info panel of each note.
