### ISSUE TITLE
Linux version broken - does not display notes or allow editing

### ISSUE THREAD

**Issue by alexforencich** [Automattic/simplenote-electron#438]
Linux version is totally broken (1.0.6).  No notes are displayed.  Note list side bar is blank.  New note button does nothing.  Logging out and logging back in does not change anything.  

#### Steps to reproduce
1. Start program
2. Log in (if not already logged in)

#### What I expected
Note list in sidebar populated with notes in account, notes can be edited, notes can be added

#### What happened instead
Note list in sidebar empty, text can be added in initial blank note, but add note button does nothing and note title does not appear in note list

#### OS version
Linux

#### Screenshot / Video
![simplenote bug](https://cloud.githubusercontent.com/assets/508807/20453016/6c73e54a-adcd-11e6-9ec5-7e4753aa43bd.png)

**Comment by alexforencich** [comment]
Alright, after leaving it open for a couple of hours, it suddenly started working.  Maybe some sort of progress indication is required for initial sync on start?

**Comment by dmsnell** [comment]
@alexforencich thanks for reporting this. that's definitely not a good feeling opening up an empty app. that behavior does seem a bit atypical though. do you think there could have been any abnormal issues with the Internet connection when the app opened up? disconnection? high latency? very slow speed? proxies? etc…

**Comment by alexforencich** [comment]
No, as far as I could tell, the internet connection was fine.  And it's a decently performing connection as well - speedtest.net shows ping time of 25 ms, download of 35 Mbps, upload of 10 Mbps.  No proxies or VPNs, just wifi (5 GHz 802.11n) to router to cable modem.  My computer does sometimes fall off the university wifi, but I have never had an issue with my home wifi (where this problem occurred).

**Comment by alexforencich** [comment]
I just tried closing and re-opening the simplenote program, and there is only about a half second delay before it displays the notes.  So it seems to be working at the moment.  Perhaps it is some sort of a migration issue from a previous version?  I can't recall what version I was running before, but every time I tried to start it since upgrading, I ran in to this issue (no notes displayed, etc.) - until last night, when I left it open instead of closing it after a couple of minutes.

**Comment by dmsnell** [comment]
@alexforencich I have personally seen some delays when opening the app while developing on it, but I have never seen it draw the UI and show no notes.

I'll keep a watch out for this, but I don't think there's much in the way of clues as to what could have caused this.

I don't think it's "totally broken" though, thankfully. The only thing that seems like a lead at this point is either the Simperium client had some issue connecting to Simperium the server or perhaps something was wonky with IndexedDB in the browser.

Although I'm going to close this for now, we can reopen it at any point. If we get more reports that are related I'll make sure to reopen and bring this to the top.

**Comment by alexforencich** [comment]
Yeah, agreed that it's not totally broken.  That's just the way it appeared to me after trying to start the app multiple times over several days and running in to this issue, but now it seems to be working fine, so whatever happened must have been some sort of a transient issue.

**Comment by ca19972001** [comment]
I this exact issue in windows. I can reproduce it at will. If I open the app with no internet connection, the notes show up. If there is a good connection in place, the notes will not show. If I open with a good connection and remove the internet connection, the notes will appear, if I reapply the internet connection the notes will again disappear.

My suspicion is that that there's a sync conflict on one of my notes and the program is hanging when it encounters the conflict.

I use simplenote all the time, I'd love to get this fixed. let me know how I may help.

**Comment by dmsnell** [comment]
@ca19972001 that sounds like a big problem! it sounds unrelated to what @alexforencich reported here though if you ask me. if you logout and login again do you experience this issue? are your notes available in any other apps or on Simplenote.com?

**Comment by ca19972001** [comment]
The logout/login did in fact make it work again. I thought I had tried that before but it's been a while so maybe I didn't. 

My iphone app works fine.

I'll see if the issue comes back...

**Comment by mariosant** [comment]
I can confirm this issue with the latest release, using deb release.

**Comment by roundhill** [comment]
Let's wrap this one into https://github.com/Automattic/simplenote-electron/issues/734, sounds similar.
