### ISSUE TITLE
Drag to select multiple notes

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#44]
When you click and drag in the note list, you should be able to select multiple notes for deleting them all at once. Could also implement `shift` + `click (#224).

See Mac app for example.

**Comment by mirka** [comment]
We also received a suggestion to add other bulk actions, such as toggle markdown and export selection.

Related: #928

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
