### ISSUE TITLE
broken markdown in android app 1.5.2 (russian)

### ISSUE THREAD

**Issue by laskin82** [Automattic/simplenote-electron#444]
#### Steps to reproduce
1. update to mobile ver 1.5.2
2. create note, write some text in russian
3. enable markdown in note
4. change to preview mode

#### What I expected
Text in russian

#### What happened instead
Text in not russsian :)

#### OS version
android 6.0.1

#### Screenshot / Video
![screenshot_20161129-123842](https://cloud.githubusercontent.com/assets/16285422/20704582/ef785f00-b630-11e6-85f0-172ce250b8ee.png)
![screenshot_20161129-123845](https://cloud.githubusercontent.com/assets/16285422/20704583/ef7a27a4-b630-11e6-8de4-10e3f28c1c59.png)

**Comment by laskin82** [comment]
wrong codepage in markdown on mobile

**Comment by roundhill** [comment]
Thanks for the report! We're investigating now.

**Comment by roundhill** [comment]
Closing here, will link to it from a new issue over at https://github.com/automattic/simplenote-android
