### ISSUE TITLE
suppress update dialog 

### ISSUE THREAD

**Issue by gregzuro** [Automattic/simplenote-electron#446]
Add the ability to suppress the update dialog, since it can become annoying.

#### What I expected

To not be bothered to update several times each day. :)

#### What happened instead

...

#### OS version

linux

**Comment by roundhill** [comment]
You could, you know, update the app ;)

**Comment by gregzuro** [comment]
I'm not on the latest verison and don't want to update the app.

**Comment by roundhill** [comment]
The latest update only prompts you to update when you launch the app, so in a way we've fixed this, but you would need to update the app...

**Comment by gregzuro** [comment]
I see.  That works.  Thanks!
