### ISSUE TITLE
Markdown Code Block Does Not Parse Properly

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-electron#450]
### Note:
I'm moving [this macOS Issue](https://github.com/Automattic/simplenote-macos/issues/95) over to the Electron repository, since it's an electron app bug actually.

Thanks!

--

I noticed in one of my notes that the code blocks are not properly parsing out in the Preview.

The three back ticks before and after the block are still shown in the preview and any headers or other markdown characters are parsed as actual markdown and not as a part of the code.

**Example**

Editor:

<img width="778" alt="screenshot 2016-11-15 10 14 01" src="https://cloud.githubusercontent.com/assets/481776/20311127/98a9ec8a-ab1c-11e6-86c3-c149c6edfb4e.png">

Preview:

<img width="773" alt="screenshot 2016-11-15 10 14 20" src="https://cloud.githubusercontent.com/assets/481776/20311137/a67ce6c8-ab1c-11e6-9f0e-fdfa62b025cc.png">

**Comment by davewhitley** [comment]
Time to move again, since this is actually the web app!

**Comment by jleandroperez** [comment]
There we go... filed an issue in the web app repository. Thanks for the heads up @drw158!!
