### ISSUE TITLE
Unwanted text appears when Printing Notes

### ISSUE THREAD

**Issue by chris-budd** [Automattic/simplenote-electron#457]
#### Steps to reproduce
1. Print any note and save it as a PDF

#### What I expected
To see the note displayed

#### What happened instead
The note displayed but with icons slightly visible over part of it.

#### Further Information
The icons appear to be from the Restore Note function in the note editor as the 4 visible items are: 'Latest' , a Slider Icon, a Cancel button and a Restore Note button.

 I suspect hiding the ```RevisionSelector``` element [found here](https://github.com/Automattic/simplenote-electron/blob/903d468fc80f04395877aab32db55040aaa11a7c/lib/note-editor.jsx#L115-L119) in the [print.scss](https://github.com/Automattic/simplenote-electron/blob/fdf0b85d0a9d373e1e8c2281e1cd2eb5ccf546b7/scss/print.scss) might solve it.

#### OS version
Windows 10

#### Screenshot / Video
[Simplenote.pdf](https://github.com/Automattic/simplenote-electron/files/642077/Simplenote.pdf)
[Simplenote1.pdf](https://github.com/Automattic/simplenote-electron/files/642078/Simplenote1.pdf)

**Comment by dmsnell** [comment]
Thanks for the report @chris-budd. You're probably onto something here. We'll add this to our list. Feel free to submit a PR yourself if you want to clone and try to get this working. We'll be here to answer any questions that might come up.

**Comment by roundhill** [comment]
I wonder if we could do the print stylesheet better, currently we have to remember to add new things to hide to the styles as we add them. We've forgotten a lot :)

**Comment by gubrist** [comment]
No the same error but same "construction site".

In the produced PDF (e.g. Adobe Reader):
- you cannot find any text string (CTRL + F)
- you cannot mark text and copy it

**Comment by Essayoh** [comment]
This is still an issue, here's a Printout from the Windows App (via @ashercantrell )

[test.pdf](https://github.com/Automattic/simplenote-electron/files/700018/test.pdf)

**Comment by beaucollins** [comment]
Maybe we should make the print stylesheet explicit. Like:
```css
* { display: none }
.printable, .printable * { display: unset }
```

**Comment by roundhill** [comment]
Pretty sure this is fixed, but we haven't released the update with the fix yet.

**Comment by dmsnell** [comment]
@beaucollins or also maybe we could be explicit about the media query and make web CSS media-query-specific

**Comment by drw158** [comment]
Can we do this in the JS?

http://electron.atom.io/docs/api/web-contents/#methods

```webContents.fromId(id)
id Integer
Returns WebContents - A WebContents instance with the given ID.```

**Comment by mirka** [comment]
Closing this as the original issue has been resolved.

The printing styles have been simplified somewhat (#1013), but we'll be on the lookout for ways to prevent regressions.
