### ISSUE TITLE
Add text to an existing note - cursor jumps to the end

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#461]
#### Steps to reproduce
1. open an existing text note, a rather long one
2. add text e.g. in the upper part
3. type fluently 
4. and suddenly the cursor jumps to the end of the note, in the middle of a word

#### What I expected
That it responds smoothly like Windows Notepad, Editor etc.

#### What happened instead
4. and suddenly the cursor jumps to the end of the note, in the middle of a word

#### OS version
Windows 10 / Simplenote 1.0.7 Electron

#### Screenshot / Video
https://www.youtube.com/watch?v=XftjrUdy-QY

**Comment by roundhill** [comment]
Strange! Do you have the app open on any other devices?

**Comment by gubrist** [comment]
Most probably yes: on my Andorid tablet and Android phone.
- I check with closing the apps.

**Comment by gubrist** [comment]
It happens also when all other apps are close.

**Comment by dmsnell** [comment]
thanks for the report @gubrist - I may have seen this personally at one point before and we have definitely discussed other issues related to the cursor positioning. I'll try and update here with what I find but we might just need to wait until we can figure out the proper cursor solution in which case this problem might disappear as a result.

**Comment by roundhill** [comment]
@gubrist Is the note shared with another Simplenote user? Just trying to see if we can nail down what's causing that.

**Comment by dmsnell** [comment]
@roundhill I think I have seen this with `draft-js` where we initialize the cursor at the end of the content. Although it looks like this was reported before `draft-js` in #292.

The related issues I was referring to are #36 and #42 and maybe some others.

I'm not confident on the way we handle updates _from_ Simperium and I think that could be causing us issues.

**Comment by gubrist** [comment]
@roundhill 
No, I do not share my notes at all.

**Comment by gubrist** [comment]
With Electron 1.0.8 the overall performance of the GUI has notably improved  👍 

But **fluent** text typing when you are at the bottom of the note adding more and more text has become creepy - like if a ghost hand would type and erase text at his own will.

**Comment by druesome** [comment]
I got a similar report about this as well.  A user writes:

> Whenever I'm editing a note (say I have a long block of text, and I'm editing a sentence somewhere around the middle of it), the cursor will randomly jump do the bottom of the page, and whatever I type onwards from then ends up at the bottom of the text that was already there. It's really disruptive for my workflow, and really annoying. Couldn't find anyone else with a similar problem so far. 
> 
> I have the latest version of the program installed on Windows7.

**Comment by ngarside** [comment]
I've had the same problem, although it's very intermittent.

> Windows 10 x64 (Creators Update)
Simplenote v1.0.8
Markdown enabled
Note not shared
Note open (but not being worked on) on another device

(Haven't had a chance to test if it still happens without the note being open on another device).

**Comment by jamiepalatnik** [comment]
Another report: 757894-zen

User is reporting that the cursor is jumping to bottom of the note on Simplenote Linux app, v. 1.0.8, seems to happen randomly, but user notices it more after using CTRL+V.

**Comment by beatskipt** [comment]
I have the issue too. Either it occurs in a session or it doesn't and if it does occur it keeps happening. 

    Windows 8.1 Pro 
    Simplenote 1.0.8
    Markdown not enabled
    Pinned to top 
    Note not shared
    Note not open on another device 

Definitely a workflow killer. I hope you're successful in fixing it. Thanks.

**Comment by rachelsquirrel** [comment]
I've also got a report of this in #808817-zen

**Comment by pothi** [comment]
"Cursor jump" also happens on SimpleNote version 1.1.0 on an Ubuntu 16.04 based distro (elementary OS) and on Macbook Air with macOS latest version and with all latest patches installed (I am not on my mac right now to provide specific version).

I can't find a reliable way to reproduce it, either. But, wanted to let everyone know here, though.

It's not too annoying. But, would love to see it works as a normal note taking app. The app is still great to work with and to sync across devices. Thanks.

**Comment by dmsnell** [comment]
This is an important bug to fix. I'm going to fold this thread into #36 where we can centralize a few spread-out and duplicate conversations. I have moved the ticket references over there as well. Please let me know if I missed any.

As we are preparing to overhaul the editor part of the app this should resolve itself as a byproduct of working through the flows which have been broken in the past to make sure we get it right this time. A number of related issues should also resolve.
