### ISSUE TITLE
Display issues with long tags overlapping number count, web app

### ISSUE THREAD

**Issue by Enils7** [Automattic/simplenote-electron#462]
#### Steps to reproduce
1. Open tags list
2.
3.
4.

#### What I expected
To see the number of notes associated with a certain tag

#### What happened instead
Some numbers are obscured by the name of the tag 

#### OS version
Wep App. Per user it happens on Firefox, Chrome, IE, Edge and on Mac

#### Screenshot / Video

![image](https://cloud.githubusercontent.com/assets/13973728/21252929/9f28feba-c30f-11e6-9da7-308ccf7ec094.png)

**Comment by drw158** [comment]
Thanks for the bug report, but because this issue is not from the electron app, this will need to be moved to the web app GitHub repo.

**Comment by gubrist** [comment]
Thanks, which is the new location of this bug report?
