### ISSUE TITLE
Copying and pasting a note carries dark mode background to pasted text.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/simplenote-electron#469]
Reported by a user via email.

When using Simplenote in dark mode, copying text from Simplenote and pasting into other applications (in this instance, web-based Gmail message windows) results in the pasted text carrying over the dark background from Simplenote.

#### Steps to reproduce
1. Switch to the dark theme.
2. Compose some text.
3. Copy from Simplenote and paste in Gmail

#### What I expected
Pasting should only paste the text, not formatting.

#### OS version
Windows 10, Chrome/Firefox

#### Screenshot / Video
![simplenote copy paste](https://cloud.githubusercontent.com/assets/8002138/21434351/2ff9203e-c831-11e6-848d-dfec9241dae8.PNG)

**Comment by dmsnell** [comment]
Yowsers! This is a bad thing. Thanks for reporting it here @chrisfromthelc

**Comment by j2xl** [comment]
This is still an issue with Simplenote v. 1.3.4 on Windows 10. Pasting into a rich text box in Chrome applies the dark-mode background.

**Comment by mirka** [comment]
@j2xl This should be fixed in 1.4.0. Could you try the latest version?

**Comment by j2xl** [comment]
Yes, this is fixed in 1.4.0. Thanks for the clarification. I had been concerned because I just downloaded 1.3.4 a week ago and this bug had been fixed about 2 years ago. All's well. :)
