### ISSUE TITLE
.deb installation error: "architecture 'amd64' wrong"

### ISSUE THREAD

**Issue by CorentinLemaitre** [Automattic/simplenote-electron#484]
I have a laptop with X86 processor. 
I want to install simplenote on it 
I download deb file and i try to install it
I get an error message : architecture "amd64" wrong 
I try deb file from github and other debfile manager
I download targz and it is for x64 also
No solution are working

Is there any version build for x86 ?
Or a possibility to build a version for x86 ?

I use ubuntu 16.04

**Comment by dmsnell** [comment]
@CorentinLemaitre thanks for the question! we might need to make sure we're all talking about the same things. the `amd64` builds are also technically `x86` so something else might be going on here.

would you be willing to send us the output from running the following command in a terminal on your laptop? the terminal is available from the main Ubuntu icon/launcher but you may need to type in "Terminal" to find it.

```bash
cat /proc/cpuinfo
```

feel free to paste it in here or drop it in a [gist](gist.github.com) and share the link

**Comment by CorentinLemaitre** [comment]
Here is the result : 

`
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU N455   @ 1.66GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1333.000
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3324.83
clflush size	: 64
cache_alignment	: 64
address sizes	: 32 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU N455   @ 1.66GHz
stepping	: 10
microcode	: 0x107
cpu MHz		: 1666.000
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
bugs		:
bogomips	: 3324.83
clflush size	: 64
cache_alignment	: 64
address sizes	: 32 bits physical, 48 bits virtual
power management:
``
```

**Comment by dmsnell** [comment]
@CorentinLemaitre thanks for sending that over. I can almost guarantee that the reason for this trouble is that it appears like you are running on a computer with an Intel Atom processor, which has a few small differences from the standard line of x86 processors.

I'm not sure what the implications of that are or if it should be running, but I will try and check in during the next several days to see if we can't figure it out and hopefully get it working for you.

Here's to hoping it works out!

(P.S. If anyone has any good knowledge about Electron running on an Atom we would welcome the help!)

**Comment by CorentinLemaitre** [comment]
OK, I understand that my situation is not a classic one.... for the moment I use simplenote online and it's fine. It is an old laptop so I think not so much people have my problem... If any other information can help ask me.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         De: Dennis SnellEnvoyé: mercredi 11 janvier 2017 20:25À: Automattic/simplenote-electronRépondre à: Automattic/simplenote-electronCc: CorentinLemaitre; MentionObjet: Re: [Automattic/simplenote-electron] .deb installation error: "architecture 'amd64' wrong" (#484)@CorentinLemaitre thanks for sending that over. I can almost guarantee that the reason for this trouble is that it appears like you are running on a computer with an Intel Atom processor, which has a few small differences from the standard line of x86 processors.
I'm not sure what the implications of that are or if it should be running, but I will try and check in during the next several days to see if we can't figure it out and hopefully get it working for you.
Here's to hoping it works out!
(P.S. If anyone has any good knowledge about Electron running on an Atom we would welcome the help!)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Automattic/simplenote-electron","title":"Automattic/simplenote-electron","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Automattic/simplenote-electron"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dmsnell in #484: @CorentinLemaitre thanks for sending that over. I can almost guarantee that the reason for this trouble is that it appears like you are running on a computer with an Intel Atom processor, which has a few small differences from the standard line of x86 processors.\r\n\r\nI'm not sure what the implications of that are or if it should be running, but I will try and check in during the next several days to see if we can't figure it out and hopefully get it working for you.\r\n\r\nHere's to hoping it works out!\r\n\r\n(P.S. If anyone has any good knowledge about Electron running on an Atom we would welcome the help!)"}],"action":{"name":"View Issue","url":"https://github.com/Automattic/simplenote-electron/issues/484#issuecomment-271968353"}}}

**Comment by mirka** [comment]
Let us know if this persists with our current builds, available on our release page:
https://github.com/Automattic/simplenote-electron/releases
