### ISSUE TITLE
XSS vulnarability in Markdown Mode

### ISSUE THREAD

**Issue by k-miras** [Automattic/simplenote-electron#487]
#### Steps to reproduce
1.Enable "Markdown Mode"
2.Create new note with XSS. In my case `<input type=text value=a onfocus=alert(JSON.stringify(document)) AUTOFOCUS>` - XSS from  [Wikipedia](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2%D1%8B%D0%B9_%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B8%D0%BD%D0%B3#.D0.9F.D0.BE_.D1.81.D0.BF.D0.BE.D1.81.D0.BE.D0.B1.D1.83_.D0.B2.D0.BE.D0.B7.D0.B4.D0.B5.D0.B9.D1.81.D1.82.D0.B2.D0.B8.D1.8F.5B26.5D)
3.Switch to "Preview"
4. On click to the input there will be created new modal window that prints "document" object. After press OK it appears again infinetely. The only way to exit - hold ENTER button and click "Edit"

#### What happened instead

JavaScript code injection

#### OS version
 Windows 7

#### Screenshot / Video

![default](https://cloud.githubusercontent.com/assets/22428831/21906699/80f4a86c-d936-11e6-85eb-11af6babaeb1.png)

Sorry for frequent updates, that my first time creating an issue

**Comment by dmsnell** [comment]
Thanks for reporting this @k-miras. We'll have to examine this.

It's probably safe to assume that allowing JavaScript inside a note is not what we want. It's also probably safe to assume that we don't want to be `eval`ing JavaScript anywhere from the note contents.

It appears like it's fully within the rendered HTML output in the viewer.

**Comment by pacharanero** [comment]
This bug confirmed replicable in Simplenote Linux (mint18.1) following the above steps to reproduce.
