### ISSUE TITLE
Editor: no padding at the bottom

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#492]
There use to be padding at the bottom of the editor, but a recent change has caused the editor to ignore the CSS style. The padding created a space above the tag list and below the last line of the note. Test by looking at a long note that scrolls.

Here is the padding that is being ignored:

![screen shot 2017-01-18 at 12 41 00 pm](https://cloud.githubusercontent.com/assets/618551/22083963/cb520b96-dd93-11e6-8989-568c8908b5f2.png)

**Comment by dmsnell** [comment]
I think this could be related to draft-js. Need some more investigation. My suspicion comes from the fact that I can't fix this with the CSS in the Chrome inspector and it's odd how a newline alone doesn't scroll but once a character is typed it works.
