### ISSUE TITLE
Can't access Settings

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#495]
Noticed on latest master, running in Electron.

#### Steps to reproduce
1. Click on Trash
2. Click on All Notes
3. Click on the Prefs menu item
4. Notice that nothing happens

#### OS version

MacOS 10.12.2

**Comment by dmsnell** [comment]
@drw158 please pull from **master** and try again. this should be fixed with the merge of #493. I tested comparing before and after that merge and was able to reproduce what you found and it was fixed in **master** after the merge. Please reopen if this still fails for you after the update.
