### ISSUE TITLE
Data loss when editing on iOS app and Electron at same time

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#502]
Edits made on iOS are continually deleted when the Electron app is open

Video of the issue:

https://youtu.be/LFxbP4OGrHA

Windows 10 is being used in the video.

**Comment by roundhill** [comment]
I've tested this out a bit, and was able to reproduce on 1.0.7, but I'm not certain how I got it in that state. A build of `master` has yet to show this behavior for me. So maybe it's already fixed, or is quite rare?

**Comment by will-hart** [comment]
I'm not sure if this is the same issue, but I seem to have a variant of this issue with Android and 1.0.7 on Windows 10. My steps:

- When I opened the desktop app it no longer shows any notes or lets me create new ones. 
- The web and Android interfaces correctly show my notes. 
- Logging in and logging out of the electron app doesn't fix it. 
- When I tried to rename the `C:/Users/MyUserName/AppData/Roaming/SimpleNote` directory to "clear the cache", it refuses and says the folder is in use. 
- SimpleNote is not visible in the task bar.
- When I look at Task Manager it is still running. 
- If I end the task and reopen SimpleNote it seems to fix it.

I've actually noticed this "failing to exit" in other electron apps such as Ghost

**Comment by es20490446e** [comment]
Same issue than on https://github.com/Automattic/simplenote-electron/issues/1075

**Comment by es20490446e** [comment]
[My case](https://youtu.be/cDJ3KHDLA44).

**Comment by es20490446e** [comment]
This issue happens quite often to me, with a reliable always connected Internet.

**Comment by es20490446e** [comment]
https://youtu.be/tSHbLdqy6FU

**Comment by es20490446e** [comment]
I started using Google Keep instead, as it showed to have high resistance to this kind of issue.
