### ISSUE TITLE
Published icon alignment

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#504]
As you can see, the icon is touching the right border of the note list which is not ideal. Seems to be related to the scrollbar. Looks fine when there is a scrollbar.

![screen shot 2017-01-27 at 5 49 23 pm](https://cloud.githubusercontent.com/assets/618551/22391804/1a75db2c-e4b9-11e6-8d9b-dad249bf5075.png)
![screen shot 2017-01-27 at 5 49 13 pm](https://cloud.githubusercontent.com/assets/618551/22391810/1c6ffa0c-e4b9-11e6-8212-e3c867e25e39.png)

**Comment by rakhi2104** [comment]
how can we test on the Dev platform where Publishing is restricted? :thinking:

**Comment by rakhi2104** [comment]
My bad, we could manually add a Published flag to all the notes, right ? :sweat_smile:

**Comment by vadimnicolai** [comment]
@mirka I tried to reproduce it on macOS 10.14.1 and simplenote v1.2.1 and it's not showing publish icon. Although doing the same on web app it's showing publish icon.

**Comment by mirka** [comment]
> it's not showing publish icon

@vadimnicolai Yes, this is actually because publishing is disabled on development builds. In dev, you're going to need to make the icon visible by altering the code in the `NoteList` component, or by adding the CSS class in devtools.

**Comment by vadimnicolai** [comment]
Understood, @mirka. Adjustments are here:
https://github.com/Automattic/simplenote-electron/pull/997
