### ISSUE TITLE
Disable/Hide the tags' Edit button when there are no tags

### ISSUE THREAD

**Issue by hoverduck** [Automattic/simplenote-electron#508]
#### Steps to reproduce
1. Open Simplenote
2. Click the Tags icon at the upper left
3. Ensure there are no existing tags

#### What I expected
To either be unable to see or click the Edit button, or otherwise have some indication that it's not going to work without any existing tags

#### What happened instead
Clicking the button cycles the label between Edit and Done with no visual indication of what that means

#### OS version
Tested on Simplenote v1.0.8 on Windows 10 and Linux Mint 18

**Comment by natanielcz** [comment]
I've created PR for this feature. #652

**Comment by natanielcz** [comment]
We should probably close this one. Fixed in #652
