### ISSUE TITLE
Preview mode selects all after update

### ISSUE THREAD

**Issue by djordjeandrejevic** [Automattic/simplenote-electron#511]
Hi Simplenote team, nice job for adding highlight support, but I have a problem with new Simplenote 1.0.8.

Before update (version 1.0.7 and lower) I could select particular line of text from the preview/markdown mode and copy it.

Now it selects all the text from the note (as if I pressed <kbd>CTRL</kbd> + <kbd>A</kbd> in edit mode) or selects none. For example, if I wanted to select `test3` part from the note below, I wouldn't be able to do it, unless I switch back to edit mode.

Fix would be highly appreciated.

#### OS version
Tested on two Ubuntu 16.04 LTS x64 machines and one Windows 10 x64 machine.

#### Screenshot
![simplenote](https://cloud.githubusercontent.com/assets/8862464/22545967/4085d408-e93b-11e6-90bb-3ac678b7e632.png)

**Comment by dmsnell** [comment]
Thanks for reporting this @djordjeandrejevic. I was able to reproduce the behavior and we'll make sure we fix this; it wasn't intentionally changed to this behavior.

**Comment by djordjeandrejevic** [comment]
Okay, one more also related to selecting (although this time it's the edit mode). I wasn't sure whether I should open a new issue, so I'll post it here.

The issue happens when I try to select long text (usually some long URL) starting from the last character and by using a keyboard (<kbd>CTRL</kbd> + <kbd>↑</kbd> to be precise). This long text I'm trying to select has to break into a new line and and has to have `-` character somewhere in the middle. Like the one on the screenshot below.

#### Screenshot

![select bug simplenote](https://cloud.githubusercontent.com/assets/8862464/23503579/993dcd00-ff3c-11e6-9407-abf63ee6a7a8.png)

(you can copy/paste this placeholder text to test it yourself: `bbbbbbbbbbbbbbbb-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb`)

To reproduce this bug, place your cursor at the end of the text (after last `b` character) and try to select whole text by using <kbd>CTRL</kbd> + <kbd>↑</kbd> on keyboard. The selection will stop as soon as it reaches the `-` character. Selecting from top to bottom (<kbd>CTRL</kbd> + <kbd>↓</kbd>) works fine though.

**Comment by taimaiduc** [comment]
Can you fix on window version ?

I can not copy in preview markdown :(

![2017_07_05_19_01_39_](https://user-images.githubusercontent.com/10907980/27863481-7e28d570-61b4-11e7-885d-9b05e37904f4.png)

**Comment by dmsnell** [comment]
Thanks @taimaiduc - the bug is already reported and should be fixed with #579. If you would like to confirm that you also see a reported bug please leave a :+1: on the opening issue description via the GitHub sticker button

<img width="803" alt="screen shot 2017-07-05 at 2 14 33 pm" src="https://user-images.githubusercontent.com/5431237/27863870-5cc53928-618c-11e7-956e-e651768f8057.png">

**Comment by dmsnell** [comment]
Closing as this should have been resolved in #579. Please reopen if it remains after the v1.1.0 release coming up.
