### ISSUE TITLE
Save or export a note as file (TXT, HTML etc.) directly form Electron

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#514]
#### Steps to reproduce
Referring to  #512
[https://github.com/Automattic/simplenote-electron/issues/512](url)

#### What I expected
An (even **simple**r and faster) alternative to:
1. copy  a complete note 
2. paste into e.g. Windows Text Editor and 
3. save the note as file there.

#### What happened instead
This feature is not yet availble.

#### OS version
Windows 10

**Comment by drw158** [comment]
As of 1.0.8, you can export all of your notes as .txt files. File > Export Notes

 You can't export single notes, but this should be able to cover your needs.

**Comment by gubrist** [comment]
The overall backup (zip) function as of 1.0.8 is **great** 
- thank you 🥇 

The exported TXT notes have the same appereance without line breaks as reportet with 
[https://github.com/Automattic/simplenote-electron/issues/512](url)

- Will the fix of #512 fix this too, automatically?


PS 1:
an export of a **single note** as file would be a simplificatoin of my daily tasks:
- each time a '**_task_**'  (~ 1 note)  has ended, I export the note to the file system.

PS 2:
an export a **all notes of a tag** would be a simplificatoin of my daily tasks.
- each time a '**_project_**'  (~ all notes of a tag)  has ended, I export the note to the file system.

**Comment by Copons** [comment]
Hi @gubrist!
The fix for #512 will also add proper Windows line breaks on the exports, for both text and JSON formats.
