### ISSUE TITLE
Printed PDF Note - no Find-function , no Copy-Paste (Electron 1.0.8)

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#515]
#### Steps to reproduce
1. Print a Note e.g. with [Microsoft Print to PDF]
2. Open the created PDF File [e.g.  Adobe Reader]
- Try  to find any text string (CTRL + F)
- Mark text and copy it

#### What I expected
- you find any text string
- you can mark text and copy it

#### What happened instead
- you cannot find any text string (CTRL + F)
- you cannot mark text and copy it

**Comment by dmsnell** [comment]
Thanks for reporting @gubrist! I'm afraid this is going to be an issue far more related to the _Print to PDF_ utility than it is with Simplenote.

We don't have any way of forcing other software to do specific things. I was able to "print" a PDF and use search and other tools as expected.

**Comment by gubrist** [comment]
@dmsnell 

a) How were/are you  able to print/create a PDF from Simplenote meeting the  expected results
- which PDF  printer / PDF creating app did/do you use?

b) I can print from **any** known text processing application under Windows 10 (Standard Text editor, Evernote, Open Office, Notepad, Word, Notepad+, PowerPoint) and I get the expected results. 
- Simplenote is currently the **only** one, which does not work.

Therefore, I invite you to re-open #515
