### ISSUE TITLE
Search: different results on different Linux (same SN version) and clients version (Android)

### ISSUE THREAD

**Issue by keypey** [Automattic/simplenote-electron#516]
Hi! 

#### Steps to reproduce
1. Insert four note:
titlte1:testClus1
body1:testClus1
titel2:test Clus2
body2:test Clus2
title3:test eClus3
body3:test eClus3
title4:testeClus4
body:testeClus4

2. Insert in search "All Notes" text:
clus

#### What I expected
- at least:show all inserted (four) notes, from 1 to 4
- (I have some another notes with words:cluster, exclusive, etc.,)

#### What happened instead
- on Linux [Debian GNU/Linux 9.0 (stretch)] (SN-1.0.8): notes: 1,2,3 
- on Linux [LMDE 2 Betsy](Linux Mint Debian Edition) (SN-1.0.8): notes: 1,3,4 
- on Android (ver. 6.0.1)(SN:1.5.5): note: 2
- What should occur when searching for the word "clus"?

#### OS version
- Linux Debian GNU/Linux 9.0 (stretch)
- Linux LMDE 2 Betsy] (Linux Mint Debian Edition)
- on Android (ver. 6.0.1)

#### Screenshot / Video
Android:
![photo_2017-02-09_13-37-20](https://cloud.githubusercontent.com/assets/3405185/22783663/13ae5076-eecd-11e6-9813-909db84a5726.jpg)
LMDE2 betsy
![photo_2017-02-09_13-37-24](https://cloud.githubusercontent.com/assets/3405185/22783745/6c973ffe-eecd-11e6-8610-da217f26213a.jpg)

Debian Stretch
![sn-1 0 8-debian9](https://cloud.githubusercontent.com/assets/3405185/22783786/98fbcede-eecd-11e6-81b6-2f72c63f4438.png)

**Comment by keypey** [comment]
1. I removed all the notes, and all tags.
2. Cleaned: Empty trash.
3. Add only four notes (see above).
LMDE2:
![111](https://cloud.githubusercontent.com/assets/3405185/22785654/833fec1c-eed5-11e6-933f-e531f8b3dcad.jpg)


4. Insert search word: clus - result ()1,3,4:
![111-s](https://cloud.githubusercontent.com/assets/3405185/22785667/8af6809c-eed5-11e6-8b80-e9bfe1488c26.jpg)

5. Open client on: Debian & Android:
DEBIAN:
![222](https://cloud.githubusercontent.com/assets/3405185/22785713/bcf0f5d2-eed5-11e6-89b2-415ab2d167a3.jpg)

ANDROID:
![333](https://cloud.githubusercontent.com/assets/3405185/22785722/c8d9c87e-eed5-11e6-89e5-4af9935b4ede.jpg)

...so I suppose Simple Note Data/index corruption. On botch platform I saw new 4 items...and "old 4 items" and all "deleted" notes.

**Comment by codebykat** [comment]
I can't tell if there's a bug here and either way things have changed a lot with search since last year. Please let us know if something still doesn't seem right.
