### ISSUE TITLE
Add Spell Check

### ISSUE THREAD

**Issue by TwisterMc** [Automattic/simplenote-electron#517]
Please add spell check. 

#### Steps to reproduce
1. Open the app.
2. Type: I can't not spel well.

#### What I expected
spel is underlined as being incorrect.

#### What happened instead
Nothing

#### OS version
Mac 1.0.8

**Comment by KokkieH** [comment]
Another request for this via [Twitter](https://twitter.com/user/status/832101454731149312).

**Comment by TwisterMc** [comment]
This was shared with me. Maybe it helps?

https://github.com/electron-userland/electron-spellchecker
electron-spellchecker is a library to help you implement spellchecking in your Electron applications, as well as handle default right-click Context Menus (since spell checking shows up in them). This library intends to solve the problem of spellchecking in a production-ready, international-friendly way.

**Comment by drw158** [comment]
dupe of #312

**Comment by dmsnell** [comment]
I'm going to close since this is a duplicate. We can track in #312
