### ISSUE TITLE
Windows: Cannot return to the list of notes from single pane

### ISSUE THREAD

**Issue by kevmarsden** [Automattic/simplenote-electron#518]
When using Simplenote 1.0.8 in the single pane view, the list of notes is not accessible after reopening the application.  

#### Steps to reproduce
1. Reduce the width of the Simplenote window until the list of notes collapses and only one note is viewable
2. Close Simplenote
3. Open Simplenote
4. Click the back arrow in an attempt to view the list of notes

#### What I expected
To view the list of notes

#### What happened instead
Unable to return to the list of notes until the window is resized.  

#### OS version
Simplenote 1.0.8
Reported on Windows 10 Pro.  I was able to reproduce on Windows 10 Enterprise.  

#### Screenshot / Video

http://d.pr/v/y0sc

Reports:
 - #3059958-t
 - #3118705-t (reproduced in Electron on macOS) [@rachelsquirrel]
 - #3153199-t (Windows) [@Hywan]

**Comment by rachelsquirrel** [comment]
Another report in #3118705-t

I can also reproduce this in the electron app for Mac.

**Comment by Hywan** [comment]
Another report in #3153199-t (on Windows).

**Comment by ForgottenUmbrella** [comment]
Can confirm that this occurs on Linux OSes too.

**Comment by LondonAppDev** [comment]
I can confirm this occurs using Simplenote v1.0.8 on Ubuntu 16.04.

**Comment by dmsnell** [comment]
Closing as this should have been resolved in #578. Please reopen if the issue remains after the v1.1.0 release.
