### ISSUE TITLE
Add highlighting to search

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#52]
While typing, matching strings should be highlighted. Here is a design:

![searching](https://cloud.githubusercontent.com/assets/618551/10983477/431ade26-83d8-11e5-9d32-88de9c753cac.png)

**Comment by BobTB** [comment]
Very important thing to do, hard to see where the searched text is without this!

**Comment by rbreaves** [comment]
I would agree that search highlighting needs to be added and was about to add a request if one had not been made. There are 3rd party clients for Windows, Linux and OSX that support this feature and as much as I love the official Simplenote app this is the single reason why I am no longer able to use the official app. My notes in the application are beginning to get long and detailed enough that search highlighting is critical.

**Comment by BobTB** [comment]
I just have to say that I stopped using the official Simplenote app just because this does not exists. It is actually quite useless when the notes are more than a few lines without search highlighting.

**Comment by KokkieH** [comment]
Another request for this in https://twitter.com/user/status/749116726701281280

**Comment by systemocracy** [comment]
there is highlighting in the android client. Puzzles me how this is not included in the windows version, I have not made the switch to the official windows client for this reason alone. Hope its included soon.

**Comment by susingha** [comment]
Still not added in Version 1.0.3. I am not able to move to SimpleNote because of the absence of this feature alone

**Comment by suaracahaya** [comment]
Please implement this soon... I like Simplenote App but it's so hard to search for notes because of no highlighting :(

**Comment by suaracahaya** [comment]
Please implement this soon, hundreds of notes are not easy to navigate through without a search highlighting...

**Comment by mnmami** [comment]
In two days from now, this request turns one year old, pity that it is still dragging. I'm speaking for the Linux version. I'm wondering what makes the task difficult if the full-text search across the notes itself is working?! Anyway, casting a vote for this being so important.
