### ISSUE TITLE
Keyboard shortcut & gesture to go "back"

### ISSUE THREAD

**Issue by samhashemi** [Automattic/simplenote-electron#522]
I use the app in a small window, in it's mobile mode.

It's terrific, but hard to go "back" to the list view. It would help if:

1. There was a keyboard shortcut to go back. `⌘[` would be a good option.

2. I could two finger swipe horizontally to go back. Many multiple-pane apps do this, especially note apps. See Ulysses or IA Writer for example.

<img width="441" alt="screenshot 2017-02-18 13 31 36" src="https://cloud.githubusercontent.com/assets/1435836/23097033/99d52a72-f5de-11e6-8ab2-a516fea19784.png">

**Comment by drw158** [comment]
This possible might help https://github.com/electron/electron/pull/4181

**Comment by drw158** [comment]
Electron does not support this currently. We could do a keyboard shortcut.

**Comment by dmsnell** [comment]
Closing here and folding into #37
