### ISSUE TITLE
Visual indicator of sync

### ISSUE THREAD

**Issue by owcz** [Automattic/simplenote-electron#527]
Transferring between 1.0.7 and 1.0.8 installs at least appears to have cleared my notes cache (online version is intact and fine), but even after logging out and logging back in, I don't have a visual feedback that a sync is in progress

**Comment by dmsnell** [comment]
Thanks for the comments @owcz! I'm going to close this since it appears to be a duplicate request to #459; feel free to follow along in that issue.
