### ISSUE TITLE
Request: Official RPM for Fedora

### ISSUE THREAD

**Issue by eduardohki** [Automattic/simplenote-electron#530]
I would love to have an Official RPM package for Fedora, just like the DEB package.

Thanks!

**Comment by natanielcz** [comment]
@eduardohki: I did it in #422 because it was just one additional line. After merging my pull request we may close this request.

**Comment by yoyoyojomo** [comment]
FYI #422 has been merged

**Comment by dmsnell** [comment]
Thanks @yoyoyojomo

**Comment by yoyoyojomo** [comment]
It looks like something still needs to be tweaked so the rpm shows up at https://github.com/Automattic/simplenote-electron/releases
