### ISSUE TITLE
Request: Numbered List Autofilling in Markdown

### ISSUE THREAD

**Issue by druesome** [Automattic/simplenote-electron#531]
With Markdown enabled, it would be great to have the ability to easily create numbered lists by autofilling succeeding numbers when pressing the Enter key.

To illustrate: when I type 1. and hit Enter, 2. automatically appears, then 3., so on and so forth. At the moment, the autofilling only works for unordered lists.

**Comment by mizejewski** [comment]
The same goes for bulleted lists

**Comment by dmsnell** [comment]
@mizejewski it should work for bulleted lists when typing `-` or `*` or `+` on new lines if you have some spacing before them.

@druesome we can check into numbered lists. we'd probably want to make sure that the mobile apps also do this. one unintuitive aspect is that Markdown numbered lists ignore the value of the number and restart the numbering at render time from the beginning. it could be unexpected to try and auto-generate the number.

 - what should happen if we have 1/2/3 and we hit enter after 2? should we get a second 2? a second 3? should we rewrite the whole list? write another 1?

**Comment by sdixon194** [comment]
This featured was also requested in 969927-zen

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by chromer030** [comment]
No any progress or plan ?

**Comment by belcherj** [comment]
Not at the moment.

**Comment by shahamit** [comment]
This is a great feature. I am finding it hard to use simplenote without this as I use numbered list a lot. 
Is this planned or already done?
