### ISSUE TITLE
Printed PDF Note - no Find-function , no Copy-Paste 

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#532]
#### Steps to reproduce
Electron 1.0.8

-     Print a Note e.g. with [Microsoft Print to PDF]
-     Open the created PDF File [e.g. Adobe Reader]
-     Try to find any text string (CTRL + F)
-     Mark text and copy it

#### What I expected
-     you find any text string
-     you can mark text and copy it

#### What happened instead
-     you cannot find any text string (CTRL + F)
-     you cannot mark text and copy it
-     I can print from **any** known text processing application under Windows 10 (Standard Text editor, Evernote, Open Office, Notepad, Word, Notepad+, PowerPoint) and  I get the expected results.  Simplenote is currently the **only** one, which does not work.

####  OS version
Windows 10

**Comment by dmsnell** [comment]
@gubrist I'm going to close this because I think this probably has more to do with the PDF printer than with Simplenote. We're not doing anything custom here and when printing the notes.

If you want, could you print out a basic note and share it with us so we can try and see what you are seeing?

**Comment by gubrist** [comment]
Here you go:

![print to pdf a](https://user-images.githubusercontent.com/22197180/29680073-c87c49c4-8903-11e7-8417-89a9044f38b8.JPG)
![print to pdf b](https://user-images.githubusercontent.com/22197180/29680075-ca29aece-8903-11e7-9089-1c94063a267c.JPG)
![print to pdf c](https://user-images.githubusercontent.com/22197180/29680078-cb9f0736-8903-11e7-88d6-b28802d660eb.JPG)

**Comment by dmsnell** [comment]
Oops @gubrist - we'd need the PDF documents to check.

Do you get the same results with the other PDF virtual printers?

**Comment by gubrist** [comment]
I have just made another test with:
- Microsoft XPS Document Wirter
- FreePDF Printer

With both the same problem remains.
