### ISSUE TITLE
No Tag "Autofill" when assigning a (new) note

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#533]
#### Steps to reproduce
Electron 1.0.8
1. Write a new note or change an existing one
2. Try to assign a new / change an exsting tag 
   (You do not want to create a new tag  but choose it from the existing tags.)

#### What I expected
As in the Android Version, when you start to type the desired tag, corresponding **existing** tags apprear.

#### What happened instead
When you start to type the tag, no **existing** tags apprear. 
You have to type the tag completly again.

This might aslo result into:
- typo errors,  wrong tags and 
- duplicate tags. 

See also as cross-reference:
https://github.com/Automattic/simplenote-ios/issues/99
https://github.com/Automattic/simplenote-macos/issues/70

#### OS version
Windows 10

**Comment by dmsnell** [comment]
Thanks for the report and cross-links @gubrist.

@roundhill and @jleandroperez I think this probably results from the awkward data model we have for tags, especially since this appears to affect all apps?

tags have a `name` and an `id` that are often the same thing but the `id` can also apparently be assigned as some kind of UUID. I've seen this for a long time but haven't had the chance to figure out why or fix it (requires cross-app coordination). worse, in some places we seem to use the two fields interchangeably instead of settling on one.

it would be good to somehow audit our use of the tag data and maybe formalize in a document somewhere the normative ways to use and set it

**Comment by jleandroperez** [comment]
@dmsnell I'm afraid that tags, in Mac / iOS, have three fields:
- Index (refers to the "visual position")
- Name
- Share

The data model is definitely up for a cross platform refactor. I'm not sure, though, if the lack of an actual UUID is the root of this specific issue.

**Comment by gubrist** [comment]
Here a picture of how this is implemented on the Android Version 1.5.6:
(and similar with the iOS Version):

![tag list android](https://user-images.githubusercontent.com/22197180/34305279-af4ae9fe-e73d-11e7-80fc-37257853fc64.png)

You start to type the name of the tag e.g. v - and the whole list appears.

This avoids creating wrong and double tags.

**Comment by roundhill** [comment]
I _think_ this should be fixed via #682, but it requires that you delete any tags you created in this app previously.

I was able to auto-complete a tag:
 * Create a new tag on a note.
 * Switch to another note and start to type the name of the tag, then press the tab key. It added the tag and saved.

**Comment by gubrist** [comment]
Using  Electron 1.1.1:

I do not create new tags currently (I have plenty of the)

1. I create a new note in the "All Notes" selctions:
2. I start to tpe the first letter(s) V and suggestion(s) appear(s)
- but **I have to type in manually the complete tag** to activate it:

![no autofill 23 12 2017](https://user-images.githubusercontent.com/22197180/34320297-3afd5040-e7f7-11e7-8068-5b30b7783e8b.JPG)

**Comment by dmsnell** [comment]
@roundhill I wonder if we could go through and try to run cleanup on existing tags - do you think we could safely do that automatically?

**Comment by mirka** [comment]
Since auto-complete is working for normal cases, closing in favor of #1124 #1128.

I also posted the awkward data model issue at https://github.com/Automattic/Simplenote-United/issues/21
