### ISSUE TITLE
Feature request: Regex search capabilities.

### ISSUE THREAD

**Issue by zohozer** [Automattic/simplenote-electron#534]
Hi. I'm a "Heavy user" Simplenote user and the most important feature I'm missing from this wonderful app is the ability to search in notes using Regular Expressions. For example if I need to find all notes with the text "Hello World" but I'm searching using the pattern "World Hello" I can't find any result.

Some good documentation can be found here: https://www.codeproject.com/Articles/2456/Adding-Regular-Expressions-to-Your-App-with-Regex

**Comment by dmsnell** [comment]
thanks for the request @zohozer! by happenstance and not by choice we used to actually have RegExp-based searching in the app but we took it out in favor of plain-text searching. for one, the search results were unexpected for most people, for two, searches from different places around the app were harder to make consistent.

one thing that we want to make happen when we are able is to make searching for multiple words work better just as you bring up with `World Hello` as well as add in support for searching for multiple tags on a note.

if you'd like to get started helping out we'd be happy to lend a hand in any way we can! I don't think it's likely, however, that we'll intentionally be pulling in RegExp-based searches into the app at any point in the future. Simplenote is, after all, supposed to be _simple_ for most people.

if there are specific needs you have for some kind of complex RegExp you can always export your notes and get it done. I'm not suggesting this as a normal workflow but as an exception. there's a `notes.json` file in the export that contains all of the notes and tags and meta information in one file.

**Comment by dmsnell** [comment]
Closing because of other search enhancements. From what I understand of your described problem this will be resolved by #604 because "Hello World" will also match a note with "Hello world"
