### ISSUE TITLE
Unable to login to desktop app on Win 10

### ISSUE THREAD

**Issue by duttakapil** [Automattic/simplenote-electron#536]
#### Steps to reproduce
1. Logout from desktop app on Windows 10
2. Login with id and pass

#### What I expected
To login with my email id and password on my desktop app

#### What happened instead
My desktop app was not syncing with my phone/web app, so I logged out to login again and check. But now I'm unable to login as well. 
Says, "Login failed. Please try again"
Forgot password also doesn't help, it shows a blank page in a new window.  
I'm able to login on the website with the same id and password

#### OS version
Windows 10 
Simplenote version : 1.0.8

#### Screenshot / Video
![Unable to login](https://cloud.githubusercontent.com/assets/6577624/24567778/c7873a00-167c-11e7-9582-c4f51821cac0.png)

**Comment by duttakapil** [comment]
I believe I've also lost the all content I had in the desktop version, but which did not sync with the mobile/web version :|

**Comment by kwonye** [comment]
Experiencing this on macOS as well

**Comment by raevilman** [comment]
First time user. Installed on windows 7. Signed up. Not able to login. Same creds working on web app.

**Comment by a9works** [comment]
This is still an issue! Cannot log in on macOS or Windows 10.

**Comment by lwx5924** [comment]
I still cannot login in mac, do you solve this issue?


First time, I cannot with the dev version, I think this is the development environment.
Then ,   I try build the app for Mac build. But still cannot login. 
Cannot Sign accout too,
Display:"The credentials you entered don't match"

**Comment by mirka** [comment]
For login issues, our support team might be able to assist you better 👍 https://simplenote.com/contact-us/
