### ISSUE TITLE
MacOS: Note display width constricted when maximized or full-screen

### ISSUE THREAD

**Issue by dogear42** [Automattic/simplenote-electron#538]
#### Steps to reproduce
1. Run Simplenote Electron on MacOS
2. Create a note with lots of flowing text (as opposed to, for example, short bullet lists)
3. Switch to full-screen mode.

#### What I expected
I expect it to look like the web version, which expands to fill the space:
![image](https://cloud.githubusercontent.com/assets/9095611/24583658/557ee9a0-1706-11e7-8158-e7d4ce8f56e6.png)

#### What happened instead
Wide margins are visible, which is a huge waste of space and requires more scrolling:
![image](https://cloud.githubusercontent.com/assets/9095611/24583661/5f6815c2-1706-11e7-97a8-50653f7b9f2b.png)

#### OS version
OS X El Capitan

#### Screenshot / Video
See attached screenshots, above.

**Comment by drw158** [comment]
#349
