### ISSUE TITLE
None of the SimpleNote display works on Ubuntu 16.10 on VirtualBox 5.1.18 running on Windows 10 (1607)

### ISSUE THREAD

**Issue by figueroadavid** [Automattic/simplenote-electron#539]
Running:
Guest VM is Ubuntu 16.10
VirtualBox Version 5.1.18 r114002 (Qt5.6.2)

Host is Windows 10, build 1607

Issue:
Nothing really displays other than a page with a black center and white borders.. there is literally nothing else on the screen.. 

#### Steps to reproduce
1. Try to open the application

#### What I expected
1. To see the regular application front end (same as Windows) with the option to login

#### What happened instead
1. Large unusable blank screen; the screen cannot be moved (graphically), and the only option is to kill the process 

#### OS version
Ubuntu 16.10

#### Screenshot / Video
![simplenote_error](https://cloud.githubusercontent.com/assets/2041839/24584036/ac8a9a14-1724-11e7-8b9c-cc4ac522d8bf.png)

The SimpleNote version is 1.0.8 (downloaded today)..
I have rebooted the guest VM multiple times, and this problem always happens.. I am unable to opne SimpleNote on this guest VM successfully at all.  I am able to open it on the WIndows host, and on iOS, and the features work perfectly on iOS & Windows.  

I installed it with sudo apt install ./simplenote-1.0.8.deb
I reinstalled it with gdebi, logged out and back in, and had the same issue with one exception.  This time, simplenote had a frame around it, and I was able to close it clicking on the X without having to kill the process.  It still had the white border area with a black center that couldn't be used.

**Comment by owcz** [comment]
This could be a VirtualBox issue. Have you tried other Electron apps or asking on their forums?

**Comment by figueroadavid** [comment]
Didn't occur to me that an application issue would be tied to the virtual host.. I have since blown all that away and haven't come back to this..

Thank you though, 

David F.
