### ISSUE TITLE
Tag autocomplete in the search field

### ISSUE THREAD

**Issue by davewhitley** [Automattic/simplenote-electron#54]
Currently in the web app you can type `tag:tagname` in the search field, and it displays all notes tagged `tagname`.

A nice improvement would be an autocomplete feature, similar to Slack.

Process:
- Start typing `tag`.
- Once you type `:`, then a background color kicks in with new placeholder text:

![screen shot 2015-11-05 at 4 49 59 pm](https://cloud.githubusercontent.com/assets/618551/10984173/56bdfe9a-83dd-11e5-91f0-76b88a266de0.png)
- Then, start typing one of your tags, and it autocompletes. Press tab to complete the tag.

![screen shot 2015-11-05 at 4 52 19 pm](https://cloud.githubusercontent.com/assets/618551/10984232/b6c6f6c0-83dd-11e5-8cfc-0132ce069563.png)

Finished typing: 

![screen shot 2015-11-05 at 4 29 57 pm](https://cloud.githubusercontent.com/assets/618551/10983859/e7b84c8c-83da-11e5-8d52-5ce60612bd3f.png)

**Comment by dmsnell** [comment]
@drw158 and @rachelmcr suppose we want to add in support to search for notes without a tag and so we choose `tag:untagged` as the search string. It sounds silly, but how would we search for a note with the tag `untagged`?

**Comment by drw158** [comment]
Oh so you are saying what if the user adds a tag named 'untagged' to a note? Hopefully an edge case, but it's important to think about.

- We could show the notes that are only tagged `untagged`, alongside the notes that have no tags.
- We could ignore it and just make it impossible to search for notes with the tag `untagged`.
- We could restrict the use of the `untagged` tag

GtiHub has some advanced search patterns like this. Maybe they have a similar problem?

I like option number 1 best. Not sure what the user would expect.

**Comment by dmsnell** [comment]
the first option seems reasonable. I would hope that it's a rare case but I'm going to try and see what all the other apps already do in this case before moving forward. it would be great to unify all the behaviors

**Comment by rachelsquirrel** [comment]
You can already search for untagged notes in the web app by typing tag:untagged and I just tested to see what would happen if I made "untagged" a tag for one note. It wasn't returned in the search results. 

I like the first option too - where both untagged notes and notes with the tag "untagged" are returned but this is not how it works in the web app. Right now it's not possible to search for notes with the tag "untagged". If we make it possible to do this in the Electron app can we also implement it for the web app?

**Comment by dmsnell** [comment]
This won't make it in for v1.1.0 but we can hopefully get it in later.

**Comment by dokker** [comment]
Would you consider please that the keyword for searching tags would be **t:**. So I could search with less typing.  
Or It could be an alias for **tag:**.

**Comment by rachelsquirrel** [comment]
A user has reported that the tag search is case sensitive. For example, if the tag is _BobDylan_, searching for _bobdylan_ will not find any results. It also doesn't find partial matches. Is it worth changing this to support partial matches and also removing the case requirement?

#964763-zen

**Comment by charlesinc3** [comment]
This is not available in 1.1.7 yet. Will it land ?

**Comment by mirka** [comment]
@charlesinc3 Unfortunately no, we haven't implemented this yet. I'm hoping we can work on improving the search features sometime next year.

**Comment by msilbers** [comment]
Searching for untagged notes specifically requested in #1430868-zen
as well as an easier way to search for multiple tags

**Comment by fhellwig** [comment]
I also wanted to add my vote to #716 (folded into #54 here). It would be great to have an "Untagged" button. Doesn't even need to be a search feature - just an "Untagged" item at the end of the list of tags would be fantastic!

**Comment by lancewillett** [comment]
Adding another vote for the `tag:untagged` search. Used to work only in the web version — which now doesn't seem to work any more, sadly.

Context: I use this for a weekly review of any new notes that I haven't tagged yet. A bit like an "inbox" and then sort by anything not yet "processed" with a tag.

**Comment by belcherj** [comment]
The ability to select untagged notes is something we are working on. Closing this as tag autocompletion is currently in the app.

**Comment by codebykat** [comment]
@belcherj There's a somewhat different idea buried in here, which is autocomplete in the text field (different than suggestions). Maybe an open issue isn't the right place to make sure it doesn't get lost.
