### ISSUE TITLE
When remove all tags from a note, it is not possible to add a new one

### ISSUE THREAD

**Issue by gie3d** [Automattic/simplenote-electron#550]
#### Steps to reproduce
1. Create a note
2. Add some tags
3. Remove all of tags from the note
4. Press delete (mac) or backspace (windows)
5. Add a new tag

#### What I expected
The new tag added in step 4 should be able to add into a note

#### What happened instead
The new tag cannot be added. Looking at console and see an error 

#### OS version
macOS 10.12.4
Simplenote 1.0.8

#### Screenshot / Video
![issue](https://cloud.githubusercontent.com/assets/1977772/25883706/f69520c8-3576-11e7-9a78-c79d15e69eec.gif)

**Comment by woneob** [comment]
same issue in 1.0.8 Windows

**Comment by gie3d** [comment]
This should be fixed by this PR #549

**Comment by gie3d** [comment]
Tested with the merged PR and the issue has been resolved.
