### ISSUE TITLE
Mac beta: Can't view note list without resizing window

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#552]
When using the beta Mac app on minimum width, closing and opening the app will display the first pinned note in editing mode. The arrow to return to the note list doesn't work. You have to resize the window to return to the list of notes.

#### Steps to reproduce
1. Resize window on the beta Mac app to the smallest width.
2. Click the x to close the window and then open the app again.
3. The app presents the first pinned note in editing mode. 
4. Try to click the arrow at the top left to return to the note list.

#### What I expected
I expected the app to open at the note list which is what I was viewing before closing it. I also expected the arrow icon to return me to the note list.

#### What happened instead
I had to resize my window to get the arrow to work.

#### OS version
Mac 10.11.6

#3208987-t

**Comment by dmsnell** [comment]
Closing as this should have been resolved in #578 - please reopen if you continue to see this problem after the 1.1.0 release.
