### ISSUE TITLE
Inter-note links

### ISSUE THREAD

**Issue by gerv** [Automattic/simplenote-electron#554]
I'm really surprised this isn't filed already... did I miss it?

It would be great to be able to link one note to another, using syntax like [[Note Name]] (already supported by one Simplenote-compatible client) or something else. I'm considering a move from Tomboy, and this is a feature I would really miss.

An alternative workaround which might be almost as good would be to add a "Search For..." item to the selection menu, so I could just select the note name where I've written it in my other note, and search for it.

**Comment by rosszurowski** [comment]
Other possible solutions:
* Provide web-based permalinks for notes, so we could open them on app.simplenote.com
* Add a URL scheme (à la [Notational Velocity's URL scheme](https://github.com/scrod/nv/wiki/nv%3A---URL-Specification)) to the apps to allow linking directly within the application

Regardless of how it's implemented, being able to connect related notes would be really helpful.

**Comment by souljedi** [comment]
I also appreciated this feature with nvAlt and would be happy to see it supported in simplenote natively.

**Comment by Crazor** [comment]
This would be a great feature! I suggest combining the suggestions of @gerv and @rosszurowski.

Parsing links like [[Note Name]] is convenient to the user, especially if there would be some kind of auto completion while typing the link. NVs usage of unique IDs allows renaming notes without breaking links.

I've never used NV, but it seems it already supports Simplenote, so it would be nice to follow it's URL style, I guess.

**Comment by iamgabrielma** [comment]
Also requested on 2127897-zen

**Comment by reizen703** [comment]
Me too - really want this

**Comment by belcherj** [comment]
We hope to work on direct linking to notes later this year. Thanks!  I’ve added this to our feature requests!

**Comment by brettz9** [comment]
If the feature request document an internal list? I didn't see it with a quick search. It'd be nice to be able to get notified when implemented.

**Comment by belcherj** [comment]
We have an internal feature request list that has this issue attached to it.  I am the one doing the work so I'll be sure to mention this issue on the user story when I start work which should, in turn, send you a notification.

**Comment by dokker** [comment]
It could make Simplenote the perfect note taking app.
Please bring us the last peace of perfectness.

**Comment by dokker** [comment]
I know it doesn't help much but I mention this just for the record:
https://github.com/Automattic/Simplenote-United/issues/20

**Comment by ohthehugemanatee** [comment]
Also interested in this feature!

It could be as simple as markdown `[title of destination note]`. 
* Since note titles aren't enforced as unique at the moment, when there are multiple notes with the same title it takes you to a generated disambiguation page. 
* If there is no note with that title, it takes you to a new note with the title pre-filled.

**Comment by wooohoooo** [comment]
That would be amazing indeed!

**Comment by louisabraham** [comment]
Hi, any update on this? It would be sooo awesome

**Comment by belcherj** [comment]
No update at this time but it is on our radar.

**Comment by WRoestorf** [comment]
My support for this request. Have used Simplenote for 10 years I think, and this would be my most wanted feature. Please have a look at https://roamresearch.com/ for a great implementation (I think) of this functionality, or this video to see it in action https://www.youtube.com/watch?v=vxOffM_tVHI

**Comment by alanlaird** [comment]
Another person eager to move away from Evernote but needing note linking.

**Comment by alanlaird** [comment]
> No update at this time but it is on our radar.

When the issue is closed and the feature list is not visible, it's hard to track progress or priority.  The popularity of mind mapping and other GTD related note systems puts a lot of value on clean note linking.  Even Github is putting effort against it and has improved their markdown linking recently.   Thanks!

**Comment by belcherj** [comment]
I would love to be able to give you a timeline but at this point, any prioritization or progress could be misleading.  I would not expect this in 2020.

**Comment by codebykat** [comment]
https://simplenote.com/2020/11/03/introducing-internal-links/ 😄
