### ISSUE TITLE
Title in Markdown rendering is no larger than standard text

### ISSUE THREAD

**Issue by gerv** [Automattic/simplenote-electron#555]
In the "Edit" screen, the note title on the first line is several points bigger than the standard text. If I switch to "Preview", it's the same size as everything else. Adding "##" before and after the title fixed it, but means all my titles in the title list have hashes in and are really ugly. Adding "----" underneath it also fixed it, but that's also ugly because you don't offer a monospace font option, and because it then takes space in the preview :-)

What I think we need is an implicit "#" before and after the title when rendering a note as Markdown.

**Comment by jakobdkp** [comment]
Or have the # in the note title automatically removed from the notes list.

**Comment by gerv** [comment]
Well, maybe. That would require adding similar hash-removal code to every client. But the title is already semantically distinct; making it so that it's styled to match seems like a cleaner solution.

**Comment by blukas** [comment]
I agree that it would be great to remove the # from the title in the note list. I have all my notes in markdown, so the first line always has a #. This makes for a lot of visible clutter and hurts scannability of the note title list.
![example of visual clutter when not masking the # in title](https://user-images.githubusercontent.com/1406519/29850305-cb7f24c2-8ce9-11e7-95ca-670a27c174ee.png)

**Comment by natanielcz** [comment]
I've fixed issue with # tags on the left sidebar but couldn't figure out how to modify font size for the first row of the editor. Looks like it's hidden somewhere in draft-js editor.
![image](https://user-images.githubusercontent.com/1231703/32113624-227fb68a-bb41-11e7-80c1-07ba37b5d3bc.png)
