### ISSUE TITLE
new osx versions needs option y/n for auto-listmaking (keep simpler!)

### ISSUE THREAD

**Issue by kirkjerk** [Automattic/simplenote-electron#556]
#### Steps to reproduce
1. start a line with a dash and a space
2. type some words and press return

#### What I expected

The cursor to move down

#### What happened instead

Dash appeared at start of next line 

But the behavior is inconsistent, because you can
1. start a line with a dash but NO space
2. Press return

and people expecting it to auto insert a dash on the next line will be disappointed

It's hard to remember which one autolists and which one doesn't.
I know you guys like to think things simple and convenient, but sometimes the two conflict.
For me, I say- how much are you helping people by making the next "bullet" for them vs how much are you annoying people who want a dash for some other reason, or don't realize you're gonna autoinsert so they type the dash anyway? 

If *I* was in control of my bullet lists, I could also easily handled nested items, but your support for that breaks down inconsistently.

Here I think you should choose simplicity and predictability over the convenience of not having to type a dash and a space. Or you could make it a preference, though I know you are trying to minimize number of preferences

#### OS version

MacOS 10.11.6, the new Electron Beta

**Comment by drw158** [comment]
I believe we try to keep this behavior consistent with all of the apps, but here we deviate from the Mac app from the App Store. We decided to **not** create a list if there is **no** space between the dash and the next character. This is more standard in web editors and markdown. We don't have any plans on changing this in the near future.
