### ISSUE TITLE
Opening notes in external windows?

### ISSUE THREAD

**Issue by LondonAppDev** [Automattic/simplenote-electron#558]
I am using Simplenote 1.0.8 on Ubuntu 16.04.

Is there a way to open notes in a separate window or run multiple instances of Simplenote?

This would be really useful feature as it means you could reference other notes within simplenote while writing a new note.

Being able to pop the note out into a separate window would give the added benefit of removing distractions of the notes preview on the left when creating or updating notes.

**Comment by drw158** [comment]
Not possible right now, but a good idea.

**Comment by leehblue** [comment]
I'd really like this feature too. Right now, if I want to see multiple notes at the same time, I have to fire up a web browser and use the web version of Simplenote while composing in the desktop version.

**Comment by codebykat** [comment]
Just noting I have heard a couple requests for this informally too and I am also in favor.

**Comment by codebykat** [comment]
Thinking about how to actually accomplish this, I think https://github.com/Automattic/simplenote-electron/issues/1635 is a prerequisite.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by inteist** [comment]
+1 for this feature. It really is a deal breaker for some users.

**Comment by jlovellgmail** [comment]
I can't use Simplenote without this feature

**Comment by dmgeurts** [comment]
Any news on this feature request? Having to switch between notes when using multiple at the same time is getting very tedious.

**Comment by codebykat** [comment]
Hi @dmgeurts, any updates would be posted here. This is something I personally would like to have, but it's not on our immediate roadmap.

As a workaround, you can use the web app at https://app.simplenote.com in multiple browser windows. There is no restriction that prevents you from editing different notes simultaneously in different browser windows (or tabs).
