### ISSUE TITLE
Korean input: cursor wouldn't detach even after completing character

### ISSUE THREAD

**Issue by Canorus** [Automattic/simplenote-electron#560]
#### Steps to reproduce
1. Install both old and new version of SimpleNote
2. Setup Korean input(macOS 10.12.5)
3. Compare their behavior

#### What I expected

cursor should detach after finishing a character

#### What happened instead

It didn't which causes me to press keys twice(return, arrow, backspace etc.)

#### OS version

macOS 10.12.5

#### Screenshot / Video

Comparison video between older version and newer version.
http://d.pr/v/eK9kj

**Comment by dmsnell** [comment]
Thanks for the report @canorus. Can you also let us know which versions are the "old" and "new" ones?

**Comment by Canorus** [comment]
"old" 1.1.8(1182) and "new" 1.0.8
![2017-05-25 23 41 27](https://cloud.githubusercontent.com/assets/7209435/26455033/dbf63854-41a3-11e7-8b0a-0cc5ddfa7910.png)
![2017-05-25 23 41 29](https://cloud.githubusercontent.com/assets/7209435/26455034/dc066fda-41a3-11e7-973a-4865189352cb.png)

Thank you :)

**Comment by dmsnell** [comment]
Thanks @Canorus - the "old" version is a native macOS app and won't be going away while the "new" version is what we've put out there for Windows and Linux users (it happens to run in macOS as well).

**Comment by mirka** [comment]
This doesn't seem to be happening in the latest version, v1.2.1. Let us know if you are still encountering this issue.
