### ISSUE TITLE
Linux: Non-Latin Characters do not display correctly. (installed via Snap)

### ISSUE THREAD

**Issue by nemonein** [Automattic/simplenote-electron#561]
#### Steps to reproduce
1. Install the latest version using Snap on Ubuntu (16.04~17.04)
2. Run Simplenote, and the documents (which I made before in Korean chracters, with others OS's simplenote) with Korean letters are displayed with squares.
3. When trying to type(input) Koreans, also and only squares are visible.

#### What I expected
Korean characters!

#### What happened instead
Squares!

#### OS version
Ubuntu/Kubuntu 17.04 (Snap version)

I asked this in https://github.com/Automattic/simplenote-electron/issues/274#issuecomment-304034716, but @drw158 suggest to open a new issue.

As I describe above, no Korean characters are displayed.
![simplenote_001](https://cloud.githubusercontent.com/assets/5688288/26485827/78ad56d4-4233-11e7-8614-19d75e42c882.png)

It's related with font settings.
https://github.com/Automattic/simplenote-electron/blob/master/scss/variables.scss#L30
In Simplenote in Ubuntu, the font 'Ubuntu' is loaded by default, which has ONLY Latin glyphs.
However, Ubuntu is matched with Korean fonts(for my case, it is matched with NanumBarumGothic - a Korean fonts) but Simplenote(or Electron) seems not to accept the matching.
```
$ fc-match ubuntu -a | head
Ubuntu-R.ttf: "Ubuntu" "Regular"
Ubuntu-M.ttf: "Ubuntu" "Medium"
Ubuntu-L.ttf: "Ubuntu" "Light"
Ubuntu-B.ttf: "Ubuntu" "Bold"
Ubuntu-RI.ttf: "Ubuntu" "Italic"
Ubuntu-MI.ttf: "Ubuntu" "Medium Italic"
Ubuntu-LI.ttf: "Ubuntu" "Light Italic"
Ubuntu-BI.ttf: "Ubuntu" "Bold Italic"
NanumBarunGothic.ttf: "나눔바른고딕" "Regular"
NanumBarunGothic.ttf: "나눔바른고딕" "Regular"
```

**Comment by drw158** [comment]
cc @gerv in case you are interested.

> Simplenote will try to load the fonts in a sequence from left to right. For example, it will try to find the first font, "-apple-system", and if it doesn't find it, it will look for the next font in the list, "BlinkMacSystemFont". Since your computer has the "Ubuntu" font, it loads that one.

> But does electron do font substitution if a glyph isn't found, like a browser does? If not, then this could be a problem, because the first font found will be used, and if it doesn't have the right glyphs, you are outta luck.

I'm not sure. Electron should behave the same as Chrome or any browser in this case. We can narrow the issue down by testing the web only version of the Electron app. It could be a problem with Electron, or just the font stack that we are using in the CSS.

**Comment by nemonein** [comment]
In Atom, which is also based on Electron, even though I set the defualt font as 'Ubuntu', I can read and type Korean.

**Comment by nemonein** [comment]
I have found something important.
This only occurs on snap version of Simplenote.
I've download and installed the Deb package(1.0.8), which works just fine. No Korean related problem at all.
Atom(Snap version), which is also based on Electron, has similar problem. In snapped version of Atom, it does not seem to support the language input system, which means I cannot change into Korean input system.

I guess this is mainly related to the Snap system.

**Comment by drw158** [comment]
Wow, great detective work. I've update the issue title so that it includes the Snap aspect. Thank you for this report! We will need to dig deeper into how Snap works.

**Comment by mirka** [comment]
Let us know if you are still encountering this issue in the latest versions.
