### ISSUE TITLE
Preview mode doesn't support RTL

### ISSUE THREAD

**Issue by tareefdev** [Automattic/simplenote-electron#562]
Hi there.. Thanks a lot to adding RTL support to Simplenote but there is one issues related with that.

When the "Markdown" option was activated for one note, the Preview mode didn't support RTL so text aligned to left and the direction become from Left-to-Right.

Other thing, the font for Headers (h1, h2 etc) changed also in Preview mode

Edit mode: 
![edit mode](https://cloud.githubusercontent.com/assets/17391433/26487961/4848a7ce-420a-11e7-82e1-f09050901af6.png)

Preview mode:
![privew mode](https://cloud.githubusercontent.com/assets/17391433/26487967/4cfd33f2-420a-11e7-812d-747dd23b9494.png)

**Comment by drw158** [comment]
Font styes changing in Preview mode is expected, but it should not change from RTL to LTR. Thanks for reporting, we will look into as soon as we can.

**Comment by tareefq** [comment]
Thanks a lot.. one something I didn’t mention it: the problem appear in Linux and Android apps

**Comment by itaysk** [comment]
@drw158 Are you planning to fix this?

**Comment by dmsnell** [comment]
@itaysk we intend on fixing every bug we're made aware of, but we don't have any hard timelines on the updates. in the meantime, we're always glad to help anyone who might want to help contribute!

**Comment by msilbers** [comment]
noted and requested a fix in #1577424-zen for Hebrew

**Comment by amirography** [comment]
+1 for this problem!

**Comment by mohamedelhosseiny** [comment]
+1
love the app, and using it almost on a daily basis.
would be great to see this feature supported

**Comment by rezzap** [comment]
Reported again in 2981058-zen

Samsung Galaxy Fan Edition and sync. it with Win10 64bit. Simplenote version 1.16.0

**Comment by azollafox** [comment]
Reported again at #3212102-zen
Simplenote version 1.20.0 on Windows 8.1
Web app on Chrome v84.0.04 on Windows 8.1
