### ISSUE TITLE
search box loses focus after every character if blank note open

### ISSUE THREAD

**Issue by kirkjerk** [Automattic/simplenote-electron#564]
#### Steps to reproduce
1. create a new note
2. click on search field and type a character
[3. focus switches to note and subsequent characters are put in note]

(Steps for control case
1. open an existing note
2. click on search field and type a character
[3. Focus stays in search field and normal highlighting occurs]

#### What I expected
for focus to stay in input field

#### What happened instead
focus jumped to new note

#### OS version
MacOS 10.11.6

**Comment by owcz** [comment]
Confirmed in latest Linux release

**Comment by dmsnell** [comment]
Should be resolved in #605 

I believe that this was introduced in another PR which fixed a different bug 🙃 

If you find that this is still broken after the 1.1.0 release can you reopen the issue? Thanks!
