### ISSUE TITLE
If Simplenote can't connect to the server, it should say so in its title bar

### ISSUE THREAD

**Issue by unforgettableid** [Automattic/simplenote-electron#565]
#459 isn't done yet, and I presume it may be very difficult to do. Here's a proposed temporary workaround which might be easier to implement.

-  If you start Simplenote, and it can't connect to the server:
    -  It should say "Simplenote — No Internet connection" in the title bar.

-  If server connectivity later becomes available:
    -  The client should retrieve as many updates as possible from the server.
    -  Once the client believes that it's probably up to date, it should change its title to just "Simplenote".
    -  Finally, it should also show an [infobar](https://en.wikipedia.org/wiki/Infobar). This bar should say "Your Internet connection has been restored". It should have an "OK" button.

**Comment by dmsnell** [comment]
@unforgettableid thanks for writing up this related issue. I think it's a great idea to indicate total loss of network connectivity (though we're still probably looking at a while before being able to get it in).

It should be possible to indicate if we have a known successful connection to the server and indicate uncertainty if it's lost. On startup we should also be able to indicate until we get such a connection that the app is in "standalone mode."
