### ISSUE TITLE
Pictures?

### ISSUE THREAD

**Issue by maanemann** [Automattic/simplenote-electron#570]
I'm very puzzled right now. Both the iOS and the Mac app store screenshots for Simplenote have been updated to now show an example of a nice, big picture, which is what I've been hoping to see, so I'm excited about this. However, there is no option to actually do so in the app, or if there is it's really well hidden. What's going on? If I'm missing something obvious I apologise.

Kindly, Hans

**Comment by maanemann** [comment]
Alright, I found my answer in the Twitter comments. You have to write the image source in markdown like so: ![title](source). Gotta be honest, that's not simple enough for me, especially not the times when using a touch keyboard. Also the image has to be online, so I'd have to upload my photos before being able to attach them. I'll wait for the friendly button before considering Simplenote again. Sorry...

**Comment by dmsnell** [comment]
Thanks for your feedback @maanemann!

There is no way in Simplenote to upload images as you discovered. The format you found for pulling in an image is standard in the Markdown family of formats and that's why this is the way we do it there in Simplenote.

It has been discussed and debated how best to incorporate something like image uploads but we just don't have a clear path forward for that in the app. We hope you are able to find it useful anyway!

**Comment by Krzychek** [comment]
Sorry for "reopen", but how about adding some external service for this (gdrive or imgur like)?
Or maybe adding ability to write simple plugins, that would allow anybody interested to add this feature (without getting deep into app code).

**Comment by dmsnell** [comment]
@Krzychek we have explored this idea but haven't been able to get it all together as quickly as everyone wants and hopes. I'm not sure what exactly you are proposing that would allow for people to add this feature without getting deep into the app code.

Are you offering to write some plugins?

**Comment by Krzychek** [comment]
In near feature (like 2 months) I could write plugins, unfortunately for now I don't have much free time.
But without a simple plugin hook I would need much more free time to spend on it.
I imagine simple API like

```typescript
interface Plugin {
    addActionButton(opts: {
        name: string | ActionEnum,
        icon: string | BaseIconEnum,
        type?: string | ActionEnum,
        onClick: Function
    }): void | Promise
}
```

**Comment by dmsnell** [comment]
@Krzychek I don't see us having any kind of plugin API available anytime soon. We would need to make sure it's available in all of the five different platforms (Android, Electron, iOS, macOS, and web) and also keeps to the mission of being simple.

I don't think that `addActionButton` would be the hard part either: more difficult would be the `onClick` action.

**Comment by sevku** [comment]
Having to switch to another program because of this issue. Maybe it'll get fixed in the future. Simplenote would e awesome.

**Comment by cryarchy** [comment]
*A means to get images from a folder on your local machine to Simplenote without having to use some external service (besides a localtunnel server, that is. ;-)). I am leaving it here for those who do not mind the hassle. I also do not think it is practical for mobile users.*

#### Prerequisites
- [Node.js](https://nodejs.org/en/download/)
- [npm](https://www.npmjs.com/get-npm)
- [localtunnel](https://www.npmjs.com/package/localtunnel)
- [static-server](https://www.npmjs.com/package/static-server)

#### Procedure
[Open a command prompt or terminal in the folder containing your image](https://www.groovypost.com/howto/open-command-window-terminal-window-specific-folder-windows-mac-linux/). Start a local static files server by typing in the command `static-server .` into the terminal and pressing enter. Make the server available on the internet by typing in the command `lt -p SERVER_PORT` into the terminal and pressing enter. `SERVER_PORT` is the port on which the local static files server is running. You can then insert your images using the ` ![title](source)` markdown syntax where `source` is your localtunnel url e.g. https://average-goat-85.localtunnel.me and the path to your image from your local folder.
