### ISSUE TITLE
Add a confirmation prompt when emptying the trash

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#571]
To match up with the other apps, we should show an `Are you sure?` type prompt when emptying the trash, because the action permanently deletes notes.

**Comment by abhimanyughoshal** [comment]
any way I can bump this up? I have some important notes that I need across devices, would hate to lose them because of a hasty click.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

Unfortunately, no way to bump at the moment.
