### ISSUE TITLE
Feature Request: Auto-enable Markdown on all notes

### ISSUE THREAD

**Issue by remarks** [Automattic/simplenote-electron#573]
Hello,

I write down all my notes in Markdown but I have to toggle each of my notes to switch it on. Is there any way to have them automatically toggle Markdown enabled?

**Comment by viewergit** [comment]
Yes, that's what I want to say

**Comment by dmsnell** [comment]
@remarks the intended behavior is that any new note follows the setting of the previous note. are you saying that when you have a note with markdown enabled and create a new note that it's not enabled in that new note too? I just tested on my copy and it's working as I expect…

 1. Create a new note, enabled markdown
 2. Create another new note, markdown is already enabled
 3. Create a third new note, but disable markdown on this one
 4. Create a fourth new note, now markdown is disabled (follows the previous note)

**Comment by giannissc** [comment]
The error can be reproduced if the first posts are pinned posts then the first non-pinned post will not inherit from them and instead it will inherit the default behaviour of non-markdown post

**Comment by natanielcz** [comment]
Maybe it would be better to set options like this in application settings instead of using unclear for user inheritance?

**Comment by davealexis** [comment]
I agree.  It would be much clearer and a better experience to just explicitly set markdown on for everything in settings.  Always-enabled markdown is something I've wanted in the app since I first started using it.

**Comment by natanielcz** [comment]
It could be useful to add settings to default mode when markdown is enabled (edit/preview) so it could be used after opening a note.

**Comment by BackSeat** [comment]
Just Googled "simplenote enable markdown by default" which brought me here, which I guess is just another way of saying, "me too".

**Comment by video99** [comment]
Always-enabled markdown feature is nice.
A Toggle option markdown for all notes at once (for all notes) also recommend

**Comment by Robertght** [comment]
To keep this topic alive, I can also say that it would be a very consistent experience across platforms to have it all enabled for all the notes. #1211522-zen

**Comment by Itrofnoc** [comment]
Please add as well some way to markdown-enable old notes. I have more than 2'000 of them, and every time I need to click an URL in an old note I must manually enable markdown (only 3 clicks, but rather annoying).

**Comment by SeanKilleen** [comment]
I don't mind the behavior of defaulting to the behavior of the last note, which works correctly for me upon creating new notes.

I have 1,000+ notes that I need to change to markdown format, and I'd like to save 3,000+ clicks and maybe save others that as well.

If I was able to submit a PR for this as a kind of utility / extension from the menu, would the Simplenote team consider it?

**Comment by mirka** [comment]
This thread is diverging into three separate issues:

1. The markdown setting on a new note is not the same as the previously created note (Bug)
2. There should be a way to toggle markdown on all notes (New feature)
3. There should be a visible, intuitive way to see what the default markdown setting will be for new notes (Usability enhancement, however may be unnecessary if number 1 is fixed)

> I have 1,000+ notes that I need to change to markdown format, and I'd like to save 3,000+ clicks and maybe save others that as well.
>
>If I was able to submit a PR for this as a kind of utility / extension from the menu, would the Simplenote team consider it?

@SeanKilleen I can't say yet, but I'm interested to see how many people have this problem. Could you post a separate issue for this so we can gauge interest and consider solutions?

**Comment by SeanKilleen** [comment]
@mirka will do! Incoming shortly.

**Comment by aseemgautam** [comment]
👍if the app would just remember the preview markdown setting. Its a pain to toggle it everytime opening a new note.

**Comment by mbjarland** [comment]
+1 for this feature request.

**Comment by thawkins** [comment]
+1, to be honest i was unaware if the following the last item edited, however if i do manage to get it into the creating markdown versions mode, and then go and edit a non-markdown  note. 
I love simplenote, i use it across 8 different devices,  i try to only use it in markdown mode. 

While we are on good stuff to add, 

1. A simple list making mode with done checkboxs on each item, timestamps etc
2. A "share to simplenote" handler that adds the shared content on mobike to either an existing note or a new note. 
3. A graphics insertion mode simular to https://github.com/blackhole89/notekit/

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by divakaivan** [comment]
Has this feature been implemented today?

**Comment by alex-kovalchuk** [comment]
I got tired of constant problems with such a simple application, so I switched to Joplin.

**Comment by ThomasDNguyen** [comment]
it's 2021 and I'm still waiting for this feature :/
