### ISSUE TITLE
Can not copy selection note in markdown preview ?

### ISSUE THREAD

**Issue by taimaiduc** [Automattic/simplenote-electron#580]
I can not copy selection note in markdown preview ? Please support it ty.

**Comment by djordjeandrejevic** [comment]
Duplicate: https://github.com/Automattic/simplenote-electron/issues/511

**Comment by dmsnell** [comment]
Thanks for finding the duplicate ticket @djordjeandrejevic - I'll close this one. Should be fixed anyway soon with #579
