### ISSUE TITLE
Revisions icon arrow points in wrong direction

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#584]
The icon for navigating a note's revisions is turning in the forward direction but revisions indicate history and the arrow should point in the backward direction. See the `gridicons-history` icon for reference.

We should update the icon to fix this. The iOS app already points in the proper direction.

@see https://ctrl.blog/entry/review-simplenote

@drw158 would it be much work to update this?

**Comment by drw158** [comment]
I think someone mentioned this to me a long time ago, or I thought about it while first making the icon. Wasn't a big deal to me at the time. According to the review we will also need to update Android (I don't have my device with me atm).

Wouldn't be a big deal to fix. We can just flip the icon horizontally.

**Comment by drw158** [comment]
Here is the path for the updated icon. Should be an easy replacement:

```<path d="M8.7,14.7l3.3-3.3V6h-2v4.6l-2.7,2.7L8.7,14.7z M11,2c5,0,9,4,9,9h-2c0-3.9-3.1-7-7-7s-7,3.1-7,7s3.1,7,7,7
		c2.4,0,4.5-1.2,5.7-3H13v-2h7v7h-2v-3.3c-1.6,2-4.2,3.3-7,3.3c-5,0-9-4-9-9S6,2,11,2z"/>```

**Comment by dmsnell** [comment]
Thanks @drw158! I've updated it. It feels a bit different to me though for sure.
