### ISSUE TITLE
List not displaying correctly on Android and Web app

### ISSUE THREAD

**Issue by diego-betto** [Automattic/simplenote-electron#588]
#### Steps to reproduce
1. create note with a list in desktop app
2. open the note in the android app or web app

#### What I expected
from this markdown
```
**title**
- item 1
- item 2
- item 3
```

this output
# title
- item 1
- item 2
- item 3

#### What happened instead
**title** `- item 1 - item 2 - item 3`
(I'm using code tag to avoid dot before first item)
#### OS version
Android 7, Samsung S7

If I add a new line after the title it works correctly on desktop, web and app. I there is no new line it works only on desktop.

**Comment by drw158** [comment]
Ok, sounds like the issue is with the web app and the Android app, not this app (Simplenote Electron). This is the repo for the Simplenote app for Windows and Linux.

Please file you issue [here](https://github.com/Automattic/simplenote-android)! Thanks!
