### ISSUE TITLE
Improve performance with multiple monitors

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#592]
When using Simplenote with several monitors it's not possible to easily move the app into view without switching back to single monitor mode before undocking. It's a problem because Simplenote will open on whichever monitor it was last used with and sometimes the monitor is no longer connected. 

Note from the user:

> Other Windows applications you can right click and select move to move the window into view. Simplenote has no ability to move the window once it opens off screen. 

Reported in #3328895-t and tested with Lenovo W530 running win 7.

**Comment by rachelsquirrel** [comment]
Another report in #3338910-t

**Comment by msilbers** [comment]
reported in #1383937-zen

**Comment by msilbers** [comment]
reported in #1389692-zen
from the user: 


In the following case:

- The external display monitor is connected with the PC. 
- The simplenote window is shown on the external monitor and then closed. 
- When I open simplenote next time without connecting the external monitor.

The following simptom happens:

- Simplenote is not shown on the display of the PC. 
- If I connect the external display monitor in this case, I can find the simplenote window. 
- If there is no external monitor, I have no way to find the simplenote window, even restarting the PC.

**Comment by mirka** [comment]
Looks like this may be fixed by updating [`electron-window-state`](https://github.com/mawie81/electron-window-state/releases/tag/v5.0.3) to 5.0.3.
https://github.com/mawie81/electron-window-state/pull/45
