### ISSUE TITLE
Inline markdown preview

### ISSUE THREAD

**Issue by seaneking** [Automattic/simplenote-electron#594]
Are there any plans to add support for inline preview of markdown formatting in notes (eg: show `**text**` as bold in editor, without stripping markdown signifiers)? 

This is a common pattern in most markdown note apps (iAWriter, Bear, etc) and would make authoring notes in markdown much more pleasant. Then the preview tab is just for a 'published' view, but markdown is still useful while in the edit view as well.

**Comment by dmsnell** [comment]
Thanks for the question @seaneking! We have explored the idea (notably in #418) but haven't yet made plans to add this. It's going to require simultaneous development across the different Simplenote apps and that will take time and coordination. We like the idea though and hope that at some point we will get it in and make it mesh well with the Simplenote paradigms!

For now I'm going to close this issue but please feel free to check in as we update the app 😄
