### ISSUE TITLE
+ button flickering and does not work

### ISSUE THREAD

**Issue by lindsaymacvean** [Automattic/simplenote-electron#595]
#### Steps to reproduce
1. Go to https://app.simplenote.com/
2. The + button to add a new note is visible
3. Move the cursor over the button
4. The icon flickers between visible and not visible 
5. if clicked there is no response and the button remains not visible

#### What I expected
The button should open a new blank note

#### What happened instead
The button just disappeared until I move the cursor away from the icon
There are no JS errors in the console, either before or after being clicked. 
I also tried with a separate session of chrome with no plugins and the bug still happened.

#### OS version
Fedora 26
Chrome Version 60.0.3112.90 (Official Build) (64-bit) 
I checked on Firefox 54.0.1 (64-bit) on same system and it works fine. 

#### Screenshot / Video
https://www.youtube.com/watch?v=t1p12N6Z7Kw

**Comment by dmsnell** [comment]
thanks @lindsaymacvean for reporting this. we're aware of the bug and are working on it already in another repository (this is for the Electron-based app), so I'm going to close the issue here.

the issue definitely started appearing in Chrome 60 and we're trying to investigate what changed there that is now breaking the app.

**Comment by lindsaymacvean** [comment]
@dmsnell Where is the other repository bug so I can keep an eye on it?

**Comment by dmsnell** [comment]
@lindsaymacvean sorry I didn't answer that already. we have a form at simplenote.com to contact us with issues for the web app. when I answered yesterday unfortunately the web app wasn't in the list of selectable apps 🙃 but later in the day we added it back in :smile:

https://simplenote.com/contact-us/
