### ISSUE TITLE
Keyboard shortcuts for switching between notes

### ISSUE THREAD

**Issue by Topy44** [Automattic/simplenote-electron#597]
New user, liking it so far. Unfortunately the Windows application's keyboard support is lacking.
I would love to see shortcuts to switch between notes. Suggestions would be Alt+Up/Alt+Down or, more standard but much less convenient, CTRL+Tab/CTRL+Shift+Tab for selecting the previous/next note in the list.

**Comment by dmsnell** [comment]
Closing here as a duplicate of #37 - check back soon for updates in v1.0.9!
