### ISSUE TITLE
Keyboard shortcut for deleting note

### ISSUE THREAD

**Issue by Topy44** [Automattic/simplenote-electron#598]
I would like to see a keyboard shortcut for deleting the current note.

**Comment by dmsnell** [comment]
Thanks for the suggestion @Topy44 - I'm going to close this here and fold it into #37.

**Comment by dmsnell** [comment]
Actually I'm going to leave this open because I'm not sure if we will have a hotkey for trashing a note. We'll keep this tracking for a while…

**Comment by roundhill** [comment]
I'd like this as well. The native macOS app will let you press the `delete` key to trash the note (when the editor is not active)

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
