### ISSUE TITLE
Allow to archive notes

### ISSUE THREAD

**Issue by neufena** [Automattic/simplenote-electron#601]
This is a feature request.  The ability to archive or soft-delete old notes would be very useful.

**Comment by dmsnell** [comment]
Hi @neufena - great news! If you trash a note they will be "soft-deleted" automatically. You should be able to find the trashed notes from the same place where you can list notes by tag.

![restoreanote](https://user-images.githubusercontent.com/5431237/29268094-b3124932-80eb-11e7-9898-4e5153911a6f.gif)

We may occasionally delete notes which have been trashed for a long time though. If we want the notes to stick around forever they will need to be out of the trash; if we want to have them available in case we change our mind within a month or two of trashing then the normal procedure should work fine.

**Comment by shubham9411** [comment]
OMG, please can we make it look like its a soft delete, because from a long time I was thinking it will hard delete my notes. Today i was here for making a feature request for same and got this. :disappointed:

**Comment by cranders** [comment]
It would be nice to have a separate archive button, aside from the delete button, which would hide the notes from the left pane or list yet still allow you to locate them using the search. The trash can works much like a recycle bin and I use this feature if I decide I don't need the note any longer. Having the ability to archive notes would really fit my workflow. I hope an archive feature will be added to the project.

**Comment by asor12** [comment]
I would appreciate an archive function too. I don't want to see notes from many years ago whenever I open the app.

**Comment by derion1** [comment]
I can see this feature has been requested for more than three years now. I don't think it is too much to ask for an archive feature. It is quite essential when taking notes. 
It is too cluttered to have all the notes in the left pane, and it is not a solid solution to keep archived stuff in the trash bin, as it might/will eventually get deleted. Besides, there should be a clear distinction between "non-pertinent" and "not needed" material. 
Please make an Archive button, just as there is a Trash button. 

Thanks.

**Comment by havinhphu188** [comment]
I really want to see this feature on simplenote. This is the reason why I still stick with google keep
