### ISSUE TITLE
Info: App fatals when clicking the Info icon with no notes

### ISSUE THREAD

**Issue by kwight** [Automattic/simplenote-electron#613]
Clicking the Info icon with no notes in the app results in an error. `note-info.jsx` [relies](https://github.com/Automattic/simplenote-electron/blob/d761694daa326df1f73f63a0d5541464ec489ce5/lib/note-info.jsx#L168) on an undefined `data` property.
![screen shot 2017-08-23 at 10 01 28 am](https://user-images.githubusercontent.com/349751/29628508-87528bbc-87ea-11e7-9f49-38fd3b8e95bc.png)

**Comment by natanielcz** [comment]
This is no longer an issue. If a note isn't selected then info button is hidden.

**Comment by kwight** [comment]
Yep, confirmed – thanks @natanielcz 👍
