### ISSUE TITLE
Number of notes per tag (notes count)

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#616]
#### What I expected
1. Open the  tag list 
2. See the number of notes per tag 
    - This feature is not yet available.

#### OS version
Windows 10

#### Screenshot / Video
Example of the Simplenote Web-Version, where this feature is available:

![number of notes per tag example web](https://user-images.githubusercontent.com/22197180/29680844-255eb4d6-8906-11e7-80d6-c21e811775a4.JPG)

The  Simplenote Web-Version is not a work-around for me, as it does currently not work propperly, showing just a few of all my notes:
https://github.com/Automattic/simplenote-macos/issues/83

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
