### ISSUE TITLE
Search within single note

### ISSUE THREAD

**Issue by owcz** [Automattic/simplenote-electron#624]
Mentioned in #301 but I don't see an open ticket

The global/main search (between notes) already exists, so the gist is to search within a single, perhaps long note. Right now, the global search will find a relevant note, but it's hard for the user to locate the result within the actual note without a finer, single intra-note search. A similar "search within note" feature is implemented in the native Mac app (#445). For discussion on the proper keyboard shortcut, see #301.

**Comment by virtadpt** [comment]
This, please.

**Comment by nateshmbhat** [comment]
ya please add this

**Comment by DanyGee** [comment]
Looking for this feature too.
Once the search term is found, the note's text (right pane) should scroll to the result. After hitting Ctrl+F it should jump to the next result, and so forth.

**Comment by melsophos** [comment]
This is a vital feature, otherwise it becomes very hard to use the app with very long notes.

**Comment by laoyuan** [comment]
search in current note, and with ˆ | ˇ  buttons like Chrome. It's very important for me

**Comment by iamgabrielma** [comment]
Requested on 1882108-zen

**Comment by gabri25ele** [comment]
search inside the note is the most important feature.
is incredibile that no one has thought about this.
Unfortunately I can't use this software if there is no such possibility

**Comment by tscizzle** [comment]
Putting in my vote on this feature as well, if that's helpful for you. I often am wanting to search within the single note I'm editing or reading.

**Comment by ehremington** [comment]
Yes this really needs to be added.

As a quick work around in a pinch: publish to web and copy and paste the link to your browser and ctrl-f in the browser.

**Comment by iamgabrielma** [comment]
Requested by 2128552-zen as well

**Comment by JSoet** [comment]
Another +1 for search within a note in the Android app in particular for me

**Comment by robderon** [comment]
nothing more true here : automatic focusing and highlighting of the searched keyword within a note would be VERY helpful.

**Comment by tscizzle** [comment]
> As a quick work around in a pinch: publish to web and copy and paste the link to your browser and ctrl-f in the browser.

@ehremington Creative! Similar and perhaps easier (and works offline), would be just select all (ctrl-A) and copy-paste into a text editor and ctrl-F in there.

**Comment by JSoet** [comment]
> Similar and perhaps easier (and works offline), would be just select all (ctrl-A) and copy-paste into a text editor and ctrl-F in there.

The thing is I want to use Simplenote as the note taking app on my phone. If I have to use another app to find the text in the note then I might as well just use that app instead. (Not to say that your solution isn't possible on desktop, but just wanted to point out the that it's not always really a possibility)

**Comment by belcherj** [comment]
We have search improvements coming soon. I’ve added this to our feature requests!

**Comment by pabloacera** [comment]
please, Is this feature implemented already? thanks

**Comment by AdnanHodzic** [comment]
> We have search improvements coming soon. I’ve added this to our feature requests!

Sorry, but why was this issue closed when almost 5 months later this feature is still not available?

**Comment by codebykat** [comment]
This was part of the 2.0 rewrite.
