### ISSUE TITLE
App icon is not visible on Xfce Desktop on Linux

### ISSUE THREAD

**Issue by ajyotirmay** [Automattic/simplenote-electron#626]
There is no application icon visible, either in the panel, the title bar, or the application switcher (alt+tab)

#### OS version
Xubuntu 16.04.3

#### Screenshot
![image](https://user-images.githubusercontent.com/8706789/30177436-627afbb4-93f5-11e7-8d41-6f18e87a7af9.png)

![image](https://user-images.githubusercontent.com/8706789/30177485-84a7ac6e-93f5-11e7-91cc-d42605db5e9a.png)

**Comment by sujaataarya** [comment]
It's great if you can turn the panel into the system tray!

**Comment by kungpaogao** [comment]
How did you fix this? I am also running Xubuntu, and this happens for multiple Electron-based programs, including Simplenote.

**Comment by nichcz** [comment]
+1

**Comment by ajyotirmay** [comment]
@kungpaogao my bad, I was using KDE and it was working just fine there, so I thought this issue was fixed. When I installed the latest build on my Xubuntu Xenial, this issue was still existing.

I'm reopening this issue, as it seems like this one still exists on Xubuntu/Xfce-Desktop.

**Comment by ajyotirmay** [comment]
The following code snippet is from a Facebook Messenger application that I was creating for my desktop. I'm able to display a proper icon for my application, even on Xfce desktop.

`window = new BrowserWindow({
        width: 1000,
        height: 600,
        icon: '/home/apurv/.applications/fb-messenger/app/images/96x96.png',
        webPreferences: {
          nodeIntegration: false
        }
    });
`

From what I think, the following code will be able to display an icon for Simplenote:
`icon: '/home/apurv/.applications/fb-messenger/app/images/96x96.png'
`

But this needs to be adapted according to this project's needs. If any one can help with this, it will be great. :)

**Comment by facosta0787** [comment]
Is there any solution for this issue ?

**Comment by sandymcfadden** [comment]
This is an old issue. After testing in the most recent LTS version of Xubuntu 20.04 the icon shows in the appropriate places including the panel at the top and application switcher. Closing.
