### ISSUE TITLE
Markdown options / flavors

### ISSUE THREAD

**Issue by PhiLhoSoft** [Automattic/simplenote-electron#627]
Feature request

I am a big fan of Markdown, but one thing annoys me a lot is the collapsing of newlines. In an era where we have auto-wrapping at textarea border, this is rather useless (might be useful in doc comments in code too, but that's outside the scope of this app).

So when I type a text, when I hit Enter, I mean to start a new line.
GitHub-flavored Markdown (the variant used in this very section, it doesn't work in Readme files) supports this.

It would be nice to have an option to support that for all notes (not sure if a per-note override would be needed / useful).

Also I would appreciate three backticks ``` code delimiters, for those like me often writing technical notes.

**Comment by dmsnell** [comment]
@PhiLhoSoft we're not implementing a custom Markdown parser so we won't be diverging from any standard implementation soon. Nominally we have chosen to render GitHub Flavored Markdown. That being said, in the upcoming `1.1.0` release we have replaced the older parser and the newer one is performing much more closely to the GFM standard.

It supports tables, code fences (with the language hints for highlighting), and many more features that the existing `marked`-approach has lacked.
