### ISSUE TITLE
Note created night before has disappeared.

### ISSUE THREAD

**Issue by ekohilas** [Automattic/simplenote-electron#628]
I made a new note with some small comments last night.

#### Steps to reproduce
Currently unknown

#### What I expected
I expected the new note to stay in my collection

#### What happened instead
The following day, the note had disappeared from everywhere, and couldn't be found in any note's version history.

#### OS version
Linux mint 4.4.0-87

**Comment by roundhill** [comment]
Hi @ekohilas! If you are still curious about the lost note feel free to reach out to our support team here: https://simplenote.com/contact. If they do indeed find a bug we will open another issue here.
