### ISSUE TITLE
Back button doesn't work

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#629]
#### Steps to reproduce
1. Open the app and open a note.
2. Resize the window to a smaller view until only the note is visible and the back arrow appears at the top left.
3. Close Simplenote and then reopen it.
4. Try clicking the back arrow at the top left.

#### What I expected
I expected to see the full list of notes again.

#### What happened instead
The back arrow is unresponsive.

I can reproduce this in the Mac app. Reported in 647156-zen.

**Comment by dmsnell** [comment]
Probably related to #578 - we can dig in and report back later

**Comment by supernovia** [comment]
Reported in ticket 707395, too.

**Comment by dmsnell** [comment]
Oops, I just realize this may be different than #578. Sorry. Let's investigate.

**Comment by dmsnell** [comment]
@rachelsquirrel I tried reproducing this but every time I open the app it comes back to the list view (not the note detail view with the back button).

Could you test with the latest macOS beta and see if you can reproduce?

**Comment by rachelsquirrel** [comment]
It works with version 1.1.0-rc1. I'll close this.
