### ISSUE TITLE
Improve Edit/Preview buttons

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#631]
The Edit/Preview buttons are large and take up space in the content area of a note. 

![preview](https://user-images.githubusercontent.com/7946521/30691145-b05fa28e-9ebe-11e7-875d-d2fbbbfe3bcb.png)

All the other icons are small and neatly tucked at the top right. Could we move these buttons or change the design to make them less obtrusive? Maybe we could have tabs at the top rather than buttons? Or even a toggle? I'm not a designer so perhaps someone else has some better ideas.

**Comment by rakhi2104** [comment]
Hope the :eye: preview icon resolved this.
@roundhill @mirka can close this issue.

**Comment by mirka** [comment]
Yes, thank you!
