### ISSUE TITLE
New Account: UI messed up with no notes available

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#633]
When I created a new account from within the app and there were no notes the UI was incomplete.
We need to make sure that it either appears properly or pre-fills an empty note.

<img width="780" alt="screen shot 2017-10-01 at 1 33 34 pm" src="https://user-images.githubusercontent.com/5431237/31057219-27ae7b8a-a6ad-11e7-8bc9-19dcd7960264.png">

This apparently appeared in #603 when I added keyboard shortcuts and conditionally rendered the note editor. This leaves the question: what _should_ happen when we have no notes?

Maybe it's not a problem: if we add the welcome note then the likelihood of having no notes is low so the problem is effectively mitigated?

**Comment by roundhill** [comment]
Resolved by #640

**Comment by dmsnell** [comment]
Kind of, but people can delete that note and get back to an empty list...
