### ISSUE TITLE
Text infinitely repeating in note

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#635]
When I created a new account and opened the app and started typing I found the text I inserted to start repeating and it continued without end until I executed some other edit action such as deleting or entering different text.

Nothing should loop like this at all.

I'm sure I've experienced this bug before and seen it reported somewhere but I couldn't find the mention. It's probably a blocker for the release.

**Comment by rachelsquirrel** [comment]
A similar issue has been reported in the Android app: 
https://github.com/Automattic/simplenote-android/issues/443

**Comment by roundhill** [comment]
@hoverduck found a way to reproduce this one:

> And as a more fun version of that bug, if you have an empty note selected, type a character in the search, then type it in the title field…then click on the body of the note, it will get caught in a loop pasting that search in repeatedly

![simplenote-110rc2-tag-search-char-repeat](https://user-images.githubusercontent.com/789137/32561686-bc6574fa-c461-11e7-9dd6-d1eb92b8b824.gif)

**Comment by roundhill** [comment]
This was fixed in 1.1.0
