### ISSUE TITLE
Edit/Preview Behavior

### ISSUE THREAD

**Issue by kodburn** [Automattic/simplenote-electron#637]
I would suggest using the same behavior for enable/preview buttons as in a browser app.
So, all markdown notes are opened in the preview mode by default and switch to edit mode by double click. I think it's far more usable experience than what you have in electron app. 

   Secondly, the edit/preview buttons should be moved up, to the options bar like in the web app:
![image](https://user-images.githubusercontent.com/10180759/30860459-73a44d56-a2c7-11e7-9b6c-0e5fc19d3cf4.png)
This way, it doesn't waste horizontal space.

**Comment by taigi100** [comment]
Are there serious considerations for choosing to go with edit/preview buttons? Can we have something like edit in the preview too? What I'm talking about it would be nice to write in markdown and see it automatically as it is, for example, what Bear does on mac.

**Comment by kodburn** [comment]
That'd be perfect and I'd love to help with the implementation.

**Comment by taigi100** [comment]
I also want to implement it myself but it will take a bit of time till I understand this project. Yet, let's see if they want it in the official project or we'll have just a separate copy of it.

I'll also research a bit how to do it and based on the workload I'll try to let you know @kodburn :)
Or you can just go ahead and beat me to it :P

**Comment by dmsnell** [comment]
@taigi100 live-previewing of the editor is something that will be further out on the radar though we're big fans of it too!

@kodburn would be very happy to help in any way we can to make it easier for you to contribute. you can get started and play around with this repository - it connects to a test backend service so you won't risk destroying any legitimate note data :wink:

**Comment by Robar666** [comment]
+1 for the live preview

**Comment by mirka** [comment]
Closing in favor of #381 #460 #944
