### ISSUE TITLE
Feature Request: Is it possible to support Mathjax?

### ISSUE THREAD

**Issue by dai-pch** [Automattic/simplenote-electron#638]
I'm wondering if it possible to enable <script> tag in Markdown mode. It make it possible to include MathJax script in a note and write math formula easily. Since html support is part of the markdown syntax, it might be easy to implement. 

Common usage of MathJax in Markdown is to add html scripts as follows:
```html
<script type="text/javascript"
 src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```
And then type type formula in the article. It's really convience for me to record formula in notes.

I've tried to add this in my note. It seems doesn't work in preview mode and the script sentences a
re not displaied. While in shared links on web explorer, all the html tags are showed as common text.

Is it possible to do that? Or is there something difficulty? 

#### OS version
I'm using simplenote in windows platform and website.

**Comment by dmsnell** [comment]
Thanks for the request @dai-pch. Sadly we're not going to try and make it easier to run JavaScript over Simplenote notes. Unfortunately if we were to do so it would be inviting an array of security issues we are constantly trying to prevent - a shortcoming of the way the web works today.

Although I see great value in being able to quickly write math inside of the notes themselves I don't see it coming to Simplenote any time soon. As an alternative you might explore tools for forming MathML markup which you could paste into your notes and that should render, though MathML isn't without its own issues.
