### ISSUE TITLE
Logout/Login: Notes don't load until other app action

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#641]
When logging out of the app and then logging in again I'm noticing that the notes don't load. Once I try to create a new note then all of the other notes load as they should have when I first logged in.

This is an issue that only happens when logging out and logging in during the same app session.

It appears related to #634 and I believe that what is happening is that for some reason we're not reestablishing a proper connection with Simperium. I'm actually seeing a valid `notesLoaded` Redux action fly by after switching accounts, but (unlike the `tagsLoaded` message) contains `notes: []` regardless of the account.

Once I create a new note then I see another `notesLoaded` message dispatch with the actual `notes` in its payload. Maybe this is a timing issue? Maybe the code flows aren't clear. I'm not sure and I wasn't able to trace the flow to resolve this problem.

**Comment by roundhill** [comment]
I dug into this a bit, it appears that `isIndexing` is always `true` after signing in with the new account here: https://github.com/Automattic/simplenote-electron/blob/36263d094927f2fcdcffc32897aa5d717b8cdbd8/lib/flux/app-state.js#L439

So something isn't getting reset properly in the Simperium library, or it's getting confused. Maybe we need to recreate the bucket objects after we sign in again?

A band-aid solution for this would be to remove the throttling when we are indexing, that would fix the issue but may cause performance problems if a user signs in and has a ton of notes.

cc @beaucollins for any ideas :)

**Comment by dmsnell** [comment]
can't we reset the throttling on login?
