### ISSUE TITLE
Editor: Updates go through wonky state

### ISSUE THREAD

**Issue by dmsnell** [Automattic/simplenote-electron#642]
Right now edits are a bit awkward in the editor. Changes are debounced (to around 3s I think) before updating to Simperium but this can present an unexpected feedback loop in the app:

  1. Make a change in the editor
  2. Change synchronizes
  3. Change comes back and edits editor content

This may be behind the occasional runaway infinite loop in #635 and some glitchy editing behavior in #568.

cc: @roundhill

**Comment by mirka** [comment]
I think this is fixed in #1193.
