### ISSUE TITLE
Korean input : completed in Hangul, but the cursor is before the letter

### ISSUE THREAD

**Issue by itwoodi** [Automattic/simplenote-electron#643]
#### Steps to reproduce
1.Install 1.0.8
2.Setup Korean input(Windows 10)

#### What I expected
cursor should detach after finishing a character
#560  same issue but different OS system.

#### What happened instead
The last letter is completed in Hangul, but the cursor is before the letter. To enter a newline, press Enter twice.

It didn't which causes me to press keys twice(return, arrow, backspace etc.)

#### OS version
Windows10 pro 1703

**Comment by dmsnell** [comment]
I'm going to mark this as a duplicate of #560 because the operating system shouldn't be playing a role here. Thanks for the report!
