### ISSUE TITLE
Delay showing window until app is ready (reduce flicker)

### ISSUE THREAD

**Issue by secretfork** [Automattic/simplenote-electron#645]
#### Steps to reproduce
1. launch app
2. observe empty window loading
3. observe content loading (causing flicker)

#### OS version
Windows 7, SP1 / simplenote 1.0.8

#### Suggestion
```javascript
mainWindow.once( 'ready-to-show', function() {
		mainWindow.show()
} );
```
Added to app.js  in function `activateWindow` will make window stay hidden until presentable.
Read more about `'ready-to-show'` in the electron documentation [here](https://electron.atom.io/docs/all/#using-ready-to-show-event)

**Comment by dmsnell** [comment]
nice suggestion @secretfork - we'll have to try this out if you don't beat us to it with a pull request :smile:

makes me wonder why it's taking so long to get ready, also if we should toss up an indicator that it's loading at least
