### ISSUE TITLE
Markdown list resets to 1 if text is nested inside.

### ISSUE THREAD

**Issue by taigi100** [Automattic/simplenote-electron#647]
While doing some research and writing some notes I've come across some unexpected behaviour. The lists aren't working properly. I'll try to look for a fix but it will take some time till I learn the project :)
#### Steps to reproduce
```
1. John
	- Doe


2. Test
	- Yep


3. What
4. Done
```

#### What I expected
1. John
	- Doe

2. Test
	- Yep

3. What
4. Done
#### What happened instead
```
1. John
	- Doe


1. Test
	- Yep


1. What
2. Done
```
#### OS version
Windows 10

#### Screenshots
![image](https://user-images.githubusercontent.com/10900362/31930804-ad7722c2-b8a9-11e7-9ffd-11d80aea9438.png)

![image](https://user-images.githubusercontent.com/10900362/31930789-a7238f96-b8a9-11e7-86dd-9ffc29aca6b8.png)

#### Notes
It works properly if I only leave one empty line between the notes, but then you get a weird space between the list and before the nested content instead of after.

**Comment by dmsnell** [comment]
Thanks for bringing this up @taigi100 - I verified with the Common Mark spec that these lists should continue as you expected.

However, we don't have our own Markdown parser in the application and so we won't be making changes to bits of how it processes Markdown. Instead, we are aware of issues with the wholesale system.

In #577 I replaced the existing parser with a more updated and modern parser. It's in the next release - `1.1.0` but I'm not entirely sure when that will be available - hopefully very soon. Can you check back after the update and see if it's still broken?

Pending that we have a number of issues centered around Markdown parsing and this will be rolled up in those changes. Thanks!
