### ISSUE TITLE
Cursor jump between search field and empty note

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#657]
Typing in the tag search field while an empty note is open is causing the cursor to jump back to the start of the current note. I reproduced this on both Windows and Linux and didn’t see any problems.

![simplenote-110rc2-tag-search-cursor-jump](https://user-images.githubusercontent.com/789137/32561765-ee3fc2c8-c461-11e7-8bf2-333e6cdf1fe2.gif)

Reported by @hoverduck

**Comment by dmsnell** [comment]
Not at my computer here, but that looks suspicious like it could be interacting with my keyboard shortcut to focus the search field
