### ISSUE TITLE
copy and paste for images

### ISSUE THREAD

**Issue by dschneiderch** [Automattic/simplenote-electron#669]
#### Steps to reproduce
1. copy an image to the clipboard
2. attempt to paste into a note yields no result

There is no paste support for images. 

#### Use Case
Sometimes if i'm taking notes from a webinar I would like to quickly copy an image or take a screenshot of part of a slide to include in my notes. Currently the only support for images is the standard markdown syntax `![alt](https://path_to_image.png)` but this means I have to have the file locally somewhere or I have to rely on a url (which may not persist). A local file on my computer does not currently get synced to my phone so the note on my phone just displays "alt" in the above case.

#### Possible Solution
I like Boostnote's solution. They keep settings, notes, user files etc in a directory. If you paste an image it automatically gets added as a file to an image folder in your Boostnote's directory, and the markdown syntax is used to refer to this location.  Simplenote has a more comprehensive syncing solution so I suppose you'd have to store this image on a server long enough to sync to all devices. storage space on a mobile device my limit the utility of this approach.

I really like the app but this is the biggest thing missing for me!

#### OS version
MacOS 10.12.6, with mac electron beta app

**Comment by dmsnell** [comment]
Thanks for providing the feedback @dschneiderch. We'd love to be able to paste in images and media, but that's not something that will be here any time soon. We have had discussions on how best to do this but it's going to involve a lot of work and coordination between the various apps and backend. I'm going to close the issue for now.

**Comment by grand-lotus-iroh** [comment]
Just uninstalled software. Simplnote is lovely but this is a big "must have feature". Keep up the great work and hope to see this feature integrated soon.

**Comment by qiuwch** [comment]
One simple idea is automatically upgrade images to a third-party service, such as imgur, then paste links to simpleone. The website <hackmd.io> handles their images this way and it seems work very well.
