### ISSUE TITLE
Default table formatting

### ISSUE THREAD

**Issue by e-volusian** [Automattic/simplenote-electron#672]
Hi, thanks to the developers for finally implementing GFM-style tables. Is it possible that the default formatting of those tables can be changed? Right now, the tables provide little value the way they are currently formatted.

Example, this Markdown:

<pre>
# testing

this | is | a
--|--|--
test | of | tables
a|second|line

```js
alert('hi');
```
</pre>

Produces these results in SimpleNote & its competition:

![image](https://user-images.githubusercontent.com/7467373/33098318-9d6a8632-ced2-11e7-8d0c-3a99cb14be72.png)

I think SimpleNote is unquestionably the most difficult of the three to read.

Simplenote-windows-1.1.0.exe

**Comment by roundhill** [comment]
Fixed in 1.1.1!
