### ISSUE TITLE
Simplenote v1.1.0 broken on HiDPI display

### ISSUE THREAD

**Issue by alexdevero** [Automattic/simplenote-electron#673]
#### Steps to reproduce
1. Donwload Simplenote v1.1.0
2. Run it

#### What I expected
App, text and its UI elements are scaled properly.

#### What happened instead
Scaling of the app is not proper. The text and UI elements are are much larger. Compare the text in app navbar (File, Edit, etc.) with the rest of the text.

#### OS version
Windows 10 (1709)

#### Screenshot / Video
v1.1.0:
![simple-note-png](https://user-images.githubusercontent.com/4237724/33114909-3eb88462-cf5f-11e7-88f1-0dcd352ece70.PNG)

v1.0.8:
![simple-note-2-png](https://user-images.githubusercontent.com/4237724/33114912-4220bda4-cf5f-11e7-991a-7075f3b7c876.PNG)

**Comment by alexdevero** [comment]
It is caused by issue in electron: https://github.com/electron/electron/issues/10862.

**Comment by justinkterry** [comment]
The current version works perfectly fine on all my high dpi displays, I recommend closing this issue

@mirka

**Comment by mirka** [comment]
@justinkterry Thanks for confirming!
