### ISSUE TITLE
Linux update always picks .deb regardless distribution

### ISSUE THREAD

**Issue by jotak** [Automattic/simplenote-electron#674]
Hi,

I'm using the tar/gz distribution (running on Fedora), and when a new version is available SimpleNote opens the .deb download link instead of the .tar.gz.

I dug a little and found this URL is called: `https://app.simplenote.com/desktop/linux/version?compare=1.0.8` and provides the link `https://github.com/Automattic/simplenote-electron/releases/download/v1.1.0/Simplenote-linux-1.1.0.deb` in its response.

Could you have something like a user-agent check server-side to distinguish between debian-based distro and others? As far as I know there's mostly ubuntu, debian and mint that use `.deb` (if you keep just focus on the biggest). Most other won't, and the tar.gz distribution would work anyway on any linux.

PS: If you need the user-agent I have:
`User-Agent | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0`

**Comment by roundhill** [comment]
You're right, it's only designed to serve the .deb. Cool idea to do a user agent check, might be possible.

**Comment by swalladge** [comment]
How about `https://app.simplenote.com/desktop/linux/version?compare=1.0.8&distro=ubuntu` instead of checking useragents?

**Comment by mirka** [comment]
Our revamped updater (#869) for Linux will have a button that opens the GitHub [latest release page](https://github.com/Automattic/simplenote-electron/releases/latest), so Linux users can download their package of choice.
