### ISSUE TITLE
It's great if you can turn the panel into the system tray!

### ISSUE THREAD

**Issue by sujaataarya** [Automattic/simplenote-electron#675]
It's great if you can turn the panel into the system tray!
Archlinux, XFCE4

**Comment by dmsnell** [comment]
Thanks @sujaataarya for the idea! We've had a submission in #710 to do what I think you are asking for. Please let me know if this _isn't_ a duplicate and if I have misunderstood! :Smile:

**Comment by sujaataarya** [comment]
Hi @dmsnell Yes, I looked at topic 710, in general, about the same speech.
I just wondered whether it was possible to come to some decision, or a patch for the program.
Thank you!

**Comment by dmsnell** [comment]
@sujaataarya you can follow the development there - I think that there are just some bugs in the patch that need to be fixed before we can merge it in.
