### ISSUE TITLE
Sync conflicts

### ISSUE THREAD

**Issue by OkazakiNagisa** [Automattic/simplenote-electron#678]
#### Steps to reproduce
1.Create a new note in an app instance and type 123
2.Open a new app instance in another machine, shutdown the network, delete '3' and type '4'
3.Delete '3' and type '5' in the origin app instance
4.Reconnect the other machine's network

#### What I expected
Show the conflicts or create a new copy of this note which includes both 124 and 125

#### What happened instead
Note 125 was lost, overwrited with 124

#### OS version
Windows 10 1703 pro, x64
Android 6.0.1

**Comment by liviopv** [comment]
Similar report on #832278-zen

**OS and app version**
Windows 10 Version 1709 (OS Build 16299.64) 
Simplenote electron-windows v1.1.0

**User's description**

> I use Simplenote on Windows (the newer Electron app), and I generally just leave it open all the time on my work and home computers. However, it seems like if one of the computers is asleep while I update the other instance, they tend to get out-of-sync. The app doesn't seem to handle this scenario well.
> 
> When I re-awake the computer, my notes are out of date and don't have any of the latest changes. Restarting the app doesn't always force a refresh, and whenever I try to use the History button it will show me the latest changes from the server, but I don't have the option to get it (since the app believes that it has the latest version, the only option I have is to hit cancel). Upon doing that, the note *disappears* from just that app. So far, the only I've found to retrieve it is to log into the website and use the History tool to set the correct version, and then restart the Electron app.

**Comment by swoolz** [comment]
Similar report on #928637-zen
App installed in 5 devices. PC 1, PC 2, netbook, iPad and Samsung phone.

**User's Description**
Example: I open a new note in any device. "Master" PC is off. 
Everything goes well all the time. 
Now I open the master. All my notes are there. 
So far so good. 
Now I change one thing on the master PC. 
It is reflected on all other devices. 
So far so good. 
I leave the master PC on with Simplenote running. 
I try and change any note on any of the other devices. 
The change is visible for about 1 or 2 seconds then reverts to the previous version. 
The only way to avert that is by shutting down the app on the master PC.

**Comment by dmsnell** [comment]
I believe that this is directly related to the bug causing the issues in #602 and so I'm going to close this ticket as a duplicate. it's not because it isn't important but rather for our own organization and to try to keep the related issues together. I spend shamefully too much time this weekend auditing these failures and have gained some insight into the problem - thanks again for everyone who has taken the time to report and interact here. you are invited to join the part in #602 unless you believe strongly that these two are separate.
