### ISSUE TITLE
Notes disppear when you change your password while logged in

### ISSUE THREAD

**Issue by ryanburnette** [Automattic/simplenote-electron#679]
#### Steps to reproduce

1. Log in with some existing notes
2. Change your password on the website
3. See all your notes disappear

#### What I expected

For the app to verify my authentication status

#### What happened instead

All my notes disappeared and I had to log out and back in

#### OS version

macOS 10.13.1

**Comment by mirka** [comment]
Fixed in #1022. The fix will not make it into v1.3.0, but we'll get it out soon 👍
