### ISSUE TITLE
Checkboxes support

### ISSUE THREAD

**Issue by giannissc** [Automattic/simplenote-electron#681]
I was under the impression that this was already submitted in the repository and would be included in the 1.1.0 update yet when i try to show a check box i only get this (image attached)
#### Steps to reproduce
1. Create a check box list
2. Press preview

#### What I expected
When writing check box list when pressing preview to render them properly

#### What happened instead
The check boxes were rendered as the equivalent HTML text for check boxes (see picture) 

#### OS version
Ubuntu 17.10

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/20277283/33660651-7efa3ade-da7c-11e7-9a65-cd73e0abe10d.png)

**Comment by laskin82** [comment]
same bug on windows 7

**Comment by giosoft** [comment]
how can you create checkboxes? I'm typing [_] but it doesn't work

**Comment by laskin82** [comment]
new note
- [] test1
- [] test1
- [] test1
- [] test1

**Comment by giosoft** [comment]
thanks, but it doesn't work. shows me this in preview: `<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1
<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1
<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1
<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1`

**Comment by giosoft** [comment]
`<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1
<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1
<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1
<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"> test1
`

**Comment by giannissc** [comment]
It actually does work but it has a bug. Let me elaborate:
1. You create a checkbox in markdown like this:
- [ ] Blah blah
- [x] Blah blah
2. The markdown texted is parsed into the equivalent html
3. The html text is parsed and rendered into the checkbox

Somehow step 3 does not happen and instead you only see the html text and not the checkbox that you are supposed to

**Comment by colinhowells** [comment]
One thing that'd be cool is if the 'preview' tab was interactive, so you could check the checkbox and when you went back to the 'edit' tab the checkbox'd be checked

**Comment by dmsnell** [comment]
Moving this into #314 where the feature request has been being tracked.

For the benefit of those in this thread I'll try and summarize why this isn't in yet:

 - Something is wrong on the render of the checkbox HTML as a result of some security sanitization going on. This is a bug and we just need to find and fix it.
 - Getting the checkbox to work from the preview is much harder than getting it to preview a checkbox.  We had a working prototype in #576 but that was only for the Electron app where the data flow is a bit simpler. We need to be able to get this out to the iOS, Android, macOS, and web versions too which sadly takes much more time.
