### ISSUE TITLE
Markdown Reference-style links break if the URL has letter - Z - uppercase,  in it 

### ISSUE THREAD

**Issue by nagpai** [Automattic/simplenote-electron#683]
#### Steps to reproduce
1. Login to Simplenote web - app.simplenote.com
2. Create a note with Markdown enabled and toggle to edit mode
3. Add this sample 
```
What a way to start the day with [Example 1] [Example1]
[Example1]:http://www.ABCXYZ123.com
```
4.   The output renders as 

What a way to start the day with Example 1  
(Example link is linked to http://www.ABCXYZ - clipped after Z)

Tested on Chromium based browser: - 
Vivaldi | 1.13.1008.34 (Stable channel) (64-bit)
on MacOSX High Sierra.

#### What I expected
Example 1 linked to complete  link :http://www.ABCXYZ123.com

#### What happened instead

Example 1 linked to clipped  link address :http://www.ABCXYZ

#830137-zd

**Comment by roundhill** [comment]
Hmm it works ok for me using that syntax @nagpai. The entire url links correctly. Any other examples?

**Comment by mirka** [comment]
Closing as this cannot be reproduced in neither the current web app (app.simplenote.com) nor the Electron app.
