### ISSUE TITLE
Tag management enhancement

### ISSUE THREAD

**Issue by crystalFljzw** [Automattic/simplenote-electron#684]
#### What I expected
It's good to add a filter that shows notes with no tags.
That will greatly help manage large amont of notes.
🥇

**Comment by dmsnell** [comment]
Thanks for the suggestion @crystalFljzw! We're planning on adding an `untagged` menu item in the tag list in order to find these notes. I'm going to close this issue then since it's a duplicate of work being tracked in #54 :smile:
