### ISSUE TITLE
Notes are not shown on startup

### ISSUE THREAD

**Issue by fedeest** [Automattic/simplenote-electron#691]
#### Steps to reproduce
1. From source, open program with `electron .`

#### What I expected
To show my notes

#### What happened instead
The notes were shown for maybe 1 second, afterwards they were hidden. If I create a new note all previous notes are shown.

#### OS version
Ubuntu 16.04

#### Screenshot / Video
[simplenote.ogv.zip](https://github.com/Automattic/simplenote-electron/files/1620366/simplenote.ogv.zip)

**Comment by roundhill** [comment]
Did you create a new test account for the dev version? When you build the app yourself you are using a different app id than the production version, so it will do weird things if you are using a production Simplenote account.
