### ISSUE TITLE
Issues with Chinese input when adding Tags

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-electron#696]
An issue that was reported for the iOS app is also being reported in the Electron app so I thought it best to create an issue for it here too.

iOS app report is at https://github.com/Automattic/simplenote-ios/issues/58

Reported in:
#900523-zen
#808832-zen
#867235-zen
#934135-zen
#974387-zen

**Comment by aizhimou** [comment]
This bug has affected the normal use of this app，hopping it can be resolved as soon as possible

**Comment by sdixon194** [comment]
Also reported in #934135-zen, Chinese and Japanese characters

**Comment by FelixGuess** [comment]
Same problem, can not input Chinese.

**Comment by AtrumGeost** [comment]
Same problem here: 

> It can’t directly enter the Chinese characters but with garbled when creating a new tag.

**Comment by AtrumGeost** [comment]
Same problem here:
>Better Chinese support for PC client. E.g. It can’t directly enter the Chinese characters but with garbled when creating a new tag.

**Comment by melines** [comment]
Another user reported an issue with Japanese input; ticket #1508255-zen
