### ISSUE TITLE
"Close to status bar" ability

### ISSUE THREAD

**Issue by hyayh** [Automattic/simplenote-electron#701]
#### What I expected
A "minimize to the status bar" or the default "close" action will minimize the app to the status bar instead of exiting it is preferred.
#### OS version
Windows

**Comment by roundhill** [comment]
The minimize button works fine for me after a quick test. And the close button is usually expected to quit an app, isn't it?

**Comment by dmsnell** [comment]
@roundhill I knot other note apps don't always quit. for instance, the Tomboy app lives in the dock and normally you'd close it from the dock icon.

**Comment by dmsnell** [comment]
Wonderfully being worked on in #710 by a community member!

**Comment by hyayh** [comment]
@roundhill As noted by dmsnell other note apps don't always quit, but it may have a 'setting' which could change the default action of close —— minimize to the dock or quit the apps. The

**Comment by hyayh** [comment]
@roundhill As noted by dmsnell other note apps don't always quit, but it may have a 'setting' which could change the default action of close —— **minimize to the notification area** or **quit the app**.

**Comment by roman-yagodin** [comment]
Vote for it! Could be nice to have for any desktop OS version.

**Comment by mgalbritton** [comment]
another vote for this in #2114823-zen

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
