### ISSUE TITLE
[Feature Request] Desktop widgets

### ISSUE THREAD

**Issue by Igetin** [Automattic/simplenote-electron#704]
I'm looking for a feature similar to Sticky Notes on Windows and Xpad on Linux. There should be an option in the desktop application to pin/stick a note to the user's desktop. 

Here's an example of Xpad:

![Xpad notes on desktop](https://user-images.githubusercontent.com/14016863/35644033-9d1b809c-06d0-11e8-878b-1ecab23ea68b.png)

The notes stay in the desktop along the shorcut icons, and they can be freely dragged around there.

Ideally it should be possible to edit the notes there, but an option to lock the notes should also be included, so that the user won't accidentally edit them. When the system is rebooted, the notes should appear right where you left them.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by Igetin** [comment]
> Thanks! I’ve added this to our feature requests!

Where can I follow the status of this feature request? Is there a new issue?

**Comment by belcherj** [comment]
We have an internal feature request tracker. This feature is not currently on our roadmap. If or when we start working on it we will reference this issue which should notify you.
