### ISSUE TITLE
Markdown preview tab empty

### ISSUE THREAD

**Issue by sivering** [Automattic/simplenote-electron#705]
#### Steps to reproduce
1. Reduce the windows/linux app window size until you reach single tab view (no split view between list/notes)
2. Go to Preview tab of a markdown note
3. Press back to come back to the note list
4. Go back into the same note

#### What I expected
See the markdown preview of the note

#### What happened instead
The note is empty, I have to click back on edit and preview to see it again

#### OS version
Archlinux 64bit
Windows 7 64bit

#### Screenshot / Video
![1markdown](https://user-images.githubusercontent.com/16690730/35661031-e864aace-0752-11e8-9d83-974c1ba1f06a.PNG)
![2markdown](https://user-images.githubusercontent.com/16690730/35661036-ec8c1632-0752-11e8-92ce-61f8678ebd83.PNG)
![3markdown](https://user-images.githubusercontent.com/16690730/35661038-edcf7854-0752-11e8-99f7-c8267bcc9446.PNG)

**Comment by AFortune** [comment]
Are you on master or another branch?

**Comment by sivering** [comment]
Yes, I am on the master branch. Thanks

**Comment by AFortune** [comment]
I submitted a fix for this. Are you still having issues @sivering ?

**Comment by sivering** [comment]
I just tested the current master branch and the issue is revolved.
Thank you very much!
