### ISSUE TITLE
Toggle for startup update checker in Linux

### ISSUE THREAD

**Issue by hfel** [Automattic/simplenote-electron#707]
Hi!

It would be nice if there was an option to turn the automatic update check on the app startup off for those who've installed Simplenote from a repo and would prefer to wait until it's updated there.

**Comment by dmsnell** [comment]
@hfel from which repository did you install Simplenote? Usually these kinds of things are performed by the repository maintainers. Maybe we could make it easier for them to perform this behavior.

**Comment by hfel** [comment]
The stable branch (shannon) of Solus.

**Comment by mirka** [comment]
It would be nice to have a toggle to disable update checking, regardless of this specific use case here. A "Check for updates" checkbox is pretty much standard (on Mac apps, at least).

I'm going to close this in favor of the more generic #842
