### ISSUE TITLE
Tags Sidebar pinnable toggle

### ISSUE THREAD

**Issue by YeshYyyK** [Automattic/simplenote-electron#713]
Hey, could you make a toggle for permanently showing/pinning the tags sidebar to the Simplenote Window?

P.S. Label as feature request.

**Comment by mgalbritton** [comment]
Another request for this feature: 1248483-zen

**Comment by jenlynnemc** [comment]
Another request for this to be added to Windows app here:
1429656-zen

**Comment by msilbers** [comment]
another request for this in #1432115-zen

**Comment by msilbers** [comment]
requested for Linux in #1434322-zen

**Comment by mirka** [comment]
Closing in favor of #433
