### ISSUE TITLE
[Feature Request] Add support for bookmarks

### ISSUE THREAD

**Issue by cgomezsilva** [Automattic/simplenote-electron#715]
Hi,

Thank you for developing and maintaining such a great app!.

I think it would be nice to have a bookmark function for notes, this might be very helpful while browsing a large note archive as well as scrolling through a long note.

## User Stories (Rough)

1. As an authenticated user I need to be able to place a bookmark on a particular line of a note
2. As an authenticated user I need to be able to see a drop-down list of clickable bookmark jump links
2.1 As an authenticated user I need to be able to see the bookmark links as user assigned short length aliases in order to avoid cluttering the UI.
3. As an authenticated user I need to be able to see the actual bookmarks as gutter marks or highlighted lines while displaying and scrolling a note
3.1 As an authenticated user I need to be able to add or remove a bookmark by right clicking on a line while displaying or scrolling a note
4. As an authenticated user  I need to be able to set the maximum allowed number of bookmarks in the dropdown menu in order to avoid cluttering the UI. 

Keep the good work :-). 

Kind Regards,

CAGS

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

Also, thank you for all the detail! I have added the user stories to the existing internal post for this feature request.

**Comment by dmittleman** [comment]
Would love to see this feature as well.  Am out on web today searching for whether Simplenote supports bookmarks.  I know some versions of Markdown do support and others do not.  I know Simplenote supports "internal links" from note to note (opening at top of note).  But as best I can tell, this 2018 feature request has not yet bubbled to the top of your work list.
