### ISSUE TITLE
[Feature Request] Button for listing all notes without tags

### ISSUE THREAD

**Issue by IlVecchioMago** [Automattic/simplenote-electron#716]
Hi,

What do you think about adding a button to list all the notes without tags?

It would be useful to view all the random notes.

The button can be placed between "All Notes" and "Trash" or on the side of "All Notes".

**Comment by dmsnell** [comment]
Thanks for the report @IlVecchioMago! I'm going to close this issue because we're already working on this feature request over in #54 and tracking it's progress there.
