### ISSUE TITLE
Markdown links with parentheses not rendering correctly

### ISSUE THREAD

**Issue by alxmjo** [Automattic/simplenote-electron#718]
#### Steps to reproduce
1. Write `Find a minimum-weight [perfect matching](https://en.wikipedia.org/wiki/Matching_(graph_theory)).` in Edit pane.
2. View extra parenthesis in Preview pane.

#### What I expected
The link to not show any extra parenthesis.

#### What happened instead
The link showed an extra parenthesis in the Preview pane.

#### OS version
MacOS Sierra 10.12.6
Simplenote 1.0.8

#### Screenshot / Video
<img width="331" alt="screen shot 2018-03-07 at 6 29 41 am" src="https://user-images.githubusercontent.com/1656106/37097703-f9a10cd6-21d0-11e8-8e5a-520c2ef14f02.png">

**Comment by dmsnell** [comment]
@alxmjo I tried to reproduce and it looks like the link is working for me.

<img width="347" alt="screen shot 2018-03-07 at 12 32 18 pm" src="https://user-images.githubusercontent.com/5431237/37110821-9fbd8194-2203-11e8-81d0-62fafdaca3d2.png">

also I copied this straight for your report. additionally I tested in the native macOS application and found the same behavior.

<img width="405" alt="screen shot 2018-03-07 at 12 33 24 pm" src="https://user-images.githubusercontent.com/5431237/37110904-d7914894-2203-11e8-9da1-2c9d7f6e25e2.png">

I tested in the Electron app (this repo) version 1.1.3 and the native macOS version 1.3.1

**Comment by alxmjo** [comment]
Sorry, didn't realize the repo was separate. You probably want to close this immediately, but if not, I've attached the complete Markdown file (with suffix changed to txt to allow pasting to this issue). 

To be clear, the link works, but it shows that extra parenthesis (which I know that you're not seeing). If I remove the extra parenthesis from the Markdown file (effectively breaking the URL), then the link no longer works.

[bug.txt](https://github.com/Automattic/simplenote-electron/files/1790464/bug.txt)

**Comment by dmsnell** [comment]
@alxmjo can you try with a newer version of the app? I'm not entirely sure still if you running this Electron-based app or the native macOS app (they both run on macOS) but both have been updated since 1.0.8 and the issue may already be resolved.

**Comment by alxmjo** [comment]
Didn't realize I wasn't running the most up to date version. Updated via App Store to 1.3.1 which resolved the issue. Thanks for your help.
