### ISSUE TITLE
Trash view options

### ISSUE THREAD

**Issue by drw158** [Automattic/simplenote-electron#72]
While viewing Trash, the app has a few different actions:

![trash view](https://cloud.githubusercontent.com/assets/618551/11131530/b9073ddc-8950-11e5-8353-55aaf0a26728.png)

- Empty Trash
- Restore Note
- Delete Note forever (this doesn't seem to be an option in any of our apps)

Also:

- New Note button is disabled.
- Search field will have a red focus style to remind users that they are searching in Trash.
- Tags are not editable.
- When selecting multiple notes in Trash, you can either restore them or delete forever.

**Comment by dmsnell** [comment]
@drw158 can you clarify what, if any, tasks remain for this issue?

**Comment by drw158** [comment]
No remaining tasks, just one enhancement. Made a new issue for it: #224
