### ISSUE TITLE
Show the sidebar when doing a global search in a narrow window.

### ISSUE THREAD

**Issue by kawamurakazushi** [Automattic/simplenote-electron#728]
#### Steps to reproduce
1. Open one of the notes with sidebar closed.
2. ⌘ + Shift + F to do an Global Search.
3. Starts searching inside the note preview, which hides all the search results.

#### What I expected
It should move back to the `sidebar` and start searching.

#### What happened instead
It started searching in the notes section.

#### OS version
mac OS 10.13.2
simplenote v1.1.3

**Comment by kakawamura** [comment]
I will try fixing this if it needed.
