### ISSUE TITLE
Publish link dialogue box hangs for Simplenote 1.1.3 on Linux

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-electron#729]
#### Steps to reproduce
1. Add a note.
2. Try to publish the link
3. The publish popup should hang, not publishing the link until the dialogue box is closed and reopened.

#### What I expected
To publish the link right away.

#### What happened instead
The Publish link dialogue hangs until the dialogue box is reopened.

#### OS version
Linux Mint 18.3

User's confirmation:

> the Publish dialogue, upon creating a Publish Link, simply states "Publishing Note....." (tested 
for 3.5+ minutes) without presenting the link to the user. If the Publish dialogue is exited, then reopened, a Publish Link is indeed presented to the user, and is accessible from all platforms. 
This was tested and reproduced on two distinct systems.

> I installed a new version of Linux Mint 18.3 in a VM for testing  purposes, syncing to my own account.* Installed Simplenote-linux-1.1.2.deb - the Publish problem does not exist. Behaviour as expected.* updated to Simplenote-linux-1.1.3.deb - Publish Link problem appears on new notes as described. I also confirmed the problem with 1.1.3 and a brand new Simplenote 

Reported in #1004592-zen

**Comment by breakfast1** [comment]
I can reproduce that except the link is never showed.

**Comment by dmsnell** [comment]
We appear to be having some issues with the publish service but it's not related to the client code in this repository. Thanks for the reports - we're on it!
