### ISSUE TITLE
can't move markdown reference window

### ISSUE THREAD

**Issue by jtoy** [Automattic/simplenote-electron#732]
you can't move the markdown reference window, it is fixed and so you can't actually use it to reference markdown syntax as you are writing your note. 
https://cl.ly/050q13213l3x

#### Steps to reproduce
1. edit a note
2. click info button
3. click "learn more" link for markdown
4. can't move the window

#### What I expected
This is a bug, it should be movable so people can actually use it.

#### What happened instead
you can't move it

#### OS version
Mac OS 10.13.2

#### Screenshot / Video
https://cl.ly/050q13213l3x

**Comment by dmsnell** [comment]
Thanks for reporting this @jtoy. That's frustrating! I think we may have some issues in general with window moving. We'll see what we can do!

**Comment by roundhill** [comment]
In my testing, clicking the link opened up the page in my browser so I think it's working as expected.
