### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by djordjedjukic** [Automattic/simplenote-electron#733]
I would like to have rich text editor with some basic options (bold, italic, underline, color highlight, lists, links).
I know that markdown is very similar to this, but sometimes it's easier to see and edit formatted text without preview.
Is there chance to add this feature?
Thank you

**Comment by dmsnell** [comment]
Thanks for the request, @djordjedjukic! although we probably won't be building much of a rich text editor any time soon we _have_ been exploring ways to integrate Markdown formatting live while editing.

You can see some of the work in #692
