### ISSUE TITLE
Blank Simplenote window - Windows 10 Pro, Simplenote v1.1.3

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/simplenote-electron#734]
2 reports: Windows 10 Pro (Version 1709/Build 16299.309) - Simplenote window opens blank.  The menus at the top are visible (File, Edit, View, etc), but the notes area is blank.  No left pane, no notes, just blank.

Reports: 
1017910-t (ongoing)
1024824-t (resolved itself.  We don't know why)

This is not something I've been able to reproduce on my Windows 7 (Home) setup, and we couldn't reproduce it on a Windows 10 Pro setup (Version 1709/Build 16299.309).  

In both of the two reports mentioned above, Simplenote was uninstalled and reinstalled, no change.
In 1017910-t, no Simplenote errors show up in the Event Viewer.

Screenshot from [1017910-t](http://cld.wthms.co/jqxzRP)
Screenshot from [1024824-t](http://cld.wthms.co/ySIwzO)

The graphics/display drivers were up to date in report 1024824-t, I'm checking if that's also the case in 1017910-t.

**Comment by sophiegyo** [comment]
Update:  Video drivers confirmed up to date for 1017910-t

**Comment by pauljacobson** [comment]
Additional report of this behaviour, on Linux: 1229766-zen.

#### User report

The user's report:

> Sometimes the whole window turns blank, the only thing visible is the menu bar, but no way to turn my notes back. The only cure is restart.
> 
> But after the problem happens once, it happen on and on again after restart.

#### Browser / OS version

OS versions: Ubuntu 16 on Chromebook, and Ubuntu 18.04 on HP EliteBook 850.
App version: TBC

**Comment by pauljacobson** [comment]
Here's another report of this behaviour on Windows from 1223410-zen:

> After upgrading to Version 1.1.5 there is a very odd behaviour.
> 
> When I start the app I see my previous notes briefly and then it changes to an empty user interface as though there were no notes at all.
> 
> On top of that there seems to be no synchronising happening. I have installed the app on my mobile, too, but the content is not identical to the one I had entered in Windows.

The user also pointed out that the web app is in sync with their mobile device so this issue seems to be limited to the Windows app.

**Comment by jaredpgranger** [comment]
@pauljacobson 1229766-zen responded that they're using Simplenote version 1.1.5

**Comment by mgalbritton** [comment]
Another report. User is using 1.1.6 with Windows and getting the same blank notes page. Reported in zen-1248383. Screenshots below.

![screenshot 8](https://user-images.githubusercontent.com/19782997/42288238-84ee167e-7f7f-11e8-82b4-ba565657785c.jpg)
![screenshot 10](https://user-images.githubusercontent.com/19782997/42288210-6d294572-7f7f-11e8-995c-d00c5b859ae6.jpg)
![screenshot 13](https://user-images.githubusercontent.com/19782997/42288220-766b5c4c-7f7f-11e8-9b89-8f8645a8b084.jpg)

**Comment by mgalbritton** [comment]
Another report of this in #1277622-zen. 
Running: Windows 8.1 
Simplenote: 1.1.6

**Comment by rantoncuadrado** [comment]
About the previous one, the user says 

> I have discovered that my blank page problem can be overcome by logging out and then logging back in. This loads the data from scratch. Thereafter it has remained.
> However the problem now is that it doesn't sync properly. It will sync down from entries elsewhere but only after I close and open twice. It will not sync up at all.

**Comment by zdenys** [comment]
Another user reports a similar issue in #1384053-zen. 

> Every time i start SimpleNote on my Ubuntu 18.04 machine with all updates installed, including latest SimpleNote 1.1.7 (including previous releases) then i have to first create a new note to see my notes.

**Comment by mirka** [comment]
This will hopefully be resolved by #1022. The fix won't make it into v1.3.0, but we'll get it out soon. Feel free to reopen if you still encounter this issue on a version > 1.3.0.

**Comment by rasebo** [comment]
I think this should be reopened, I am getting the same issue with Simplenote 1.3.4, which should already contain #1022 . I'm running Windows 10 Pro Version 1803 Build 17134.523.

**Comment by iamgabrielma** [comment]
I'm re-opening this as seems we still have instances of this bug after 1.3 ( 1733481-zen ), in this case with Simplenote 1.3.4 on Windows 10.
