### ISSUE TITLE
Possibility to hide menu bar on linux app

### ISSUE THREAD

**Issue by ramizdemiurge** [Automattic/simplenote-electron#735]
Please, add possibility to hide top menu bar on linux app.

Version: 1.1.3
Os: Ubuntu 14.04.3

I'm using deb package.

![ugly_menubar](https://user-images.githubusercontent.com/16004189/37716925-0eb0ae1a-2d39-11e8-8983-ff3d50761e00.jpeg)

Thanx :+1:

**Comment by mirka** [comment]
Thanks for the request! Closing in favor of #293
