### ISSUE TITLE
When pressing ctrl-shift-p and then going back, curser doesn't return where it was before

### ISSUE THREAD

**Issue by starndust31** [Automattic/simplenote-electron#737]
When you press ctrl-shift-p to look at the preview and then press it again, the cursor is no longer where it was left making you have to click the spot you were on every time you use the shortcut. Could you make it so that the cursor returns to the spot you were on before you go to preview mode?

**Comment by dmsnell** [comment]
Thanks for highlighting this @starndust31. I'm going to fold the issue into #42 because I think they both get resolved from the same update. There are several places the cursor jumps unexpectedly.
