### ISSUE TITLE
Markdown `code` blocks  look different in web and windows desktop

### ISSUE THREAD

**Issue by muphblu** [Automattic/simplenote-electron#738]
#### Steps to reproduce
1. Create note with markdown `code block` and some text before and after code block
2. Share->Publish->Make public link
3. Open link in browser

#### What I expected
**Expected:** looks similar to desktop(at least line breaks near code blocks)

#### What happened instead
**Actual:** each code block occupies whole line

#### OS version
Windows 10 Pro 1709
Testede browsers: Google Chrome 65, Mozilla Firefox 59

#### Screenshot / Video
- **Windows desktop**
![simplenote 2018-03-30 13 42 13](https://user-images.githubusercontent.com/2836641/38135319-371d7c3c-3420-11e8-92c9-4b4f76431d51.png)

- **Web**
![test - google chrome 2018-03-30 13 41 56](https://user-images.githubusercontent.com/2836641/38135321-3a9f680c-3420-11e8-8cb9-c6acd07d47b4.png)

**Comment by roundhill** [comment]
Thanks for the report. We pushed a fix to the published page, is it looking better for you now?

**Comment by muphblu** [comment]
yeah looks perfect)
Thanks
P.S.
Lightning-fast response
