### ISSUE TITLE
Highlight search terms in the note list

### ISSUE THREAD

**Issue by Hywan** [Automattic/simplenote-electron#740]
#### Steps to reproduce

1. Search a term in the search field,
2. See a reduced note list, all containing the term.

#### What I expected

The term is highlighted (in the note list, and maybe in the notes themselves).

#### What happened instead

No highlighting.

This highlighting is present on Android and iOS for instance.

#### OS version

macOS

According to #1053382-zen, highlighting works on Windows, didn't tested. Didn't check on Linux.

**Comment by xta** [comment]
+1 request as this is a key feature that prevents me from using Simplenote 100% of the time. 

I was previously using Notational Velocity & nvALT. I have to sometimes fall back to one of those to get search result text highlighting since Simplenote macOS doesn't have it.

**Comment by mirka** [comment]
Closing as this seems to be a feature request for the native macOS app, not the Electron app (already implemented here).

Related: https://github.com/Automattic/simplenote-macos/issues/18
