### ISSUE TITLE
User Has Issues Adding Pre-Existing Tag

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/simplenote-electron#741]
> I find I have to regenerate (retype) the tag at the end (bottom) of creating each new note, and I end up with multiple identical tags in the all tags view. 

> There may be a tag problem caused by correcting tag spelling mistakes as they are entered. The tag being corrected may not be corrected correctly internally, although the view of the tag is ok at the time the note is loaded. (The spelling correction process is also awkward because with each character corrected, the cursor goes automatically to the end of the tag, and has to be brought back to the remaining characters to be corrected. This awkwardness at the user level may cause internal tag id problems.)

#1045953-zen

**Comment by dmsnell** [comment]
Thanks for reporting @ChrissiePollock. There's a sneaky issue with tags where a tag is identified not by is label but by an internal id. That is, we can end up in situations like this. It's possible to rename tags and end up with duplicate labels.

At some point we held a discussion about merging identically-labeled tags but I don't think it went anywhere. Doing so I think would clear up issues like this.

@drw158 @roundhill what do you think? do you remember us talking about the distinction between tag id and tag label.

**Comment by roundhill** [comment]
Merging identically 'labeled' tags sounds good to me. I think internally what we are calling 'label' here is the 'name' property.

I assume we have this issue on all of the apps?

**Comment by mirka** [comment]
Closing in favor of https://github.com/Automattic/Simplenote-United/issues/21
