### ISSUE TITLE
Share icon uses a confusing symbol

### ISSUE THREAD

**Issue by srravya** [Automattic/simplenote-electron#742]
The share icon at the top right does not intuitively convey 'Share'. The upward arrow symbol could be interpreted as an 'Upload' icon instead of 'Share' or 'Collaborate'. Perhaps the conventional 'Share' symbol could be used? [Ref: https://openclipart.org/detail/180832/share-icon]

**Comment by roundhill** [comment]
It's a very similar icon to what macOS/iOS uses for sharing. Sharing icons are one of those things that changes across platforms 🤷‍♂️

**Comment by eternaltyro** [comment]
For the record, I'm using Simplenote on Linux, Mac and Android N. The icon is same everywhere for me.

**Comment by rakhi2104** [comment]
Why not platform dependant icons ? :thinking:

**Comment by eternaltyro** [comment]
> Why not platform dependant icons ? thinking

Because many times platforms sacrifice intuitiveness for aesthetics. As is apparently the case with MacOS.

**Comment by belcherj** [comment]
This is the intended icon for Electron/Web
