### ISSUE TITLE
Optimise search/highlight as you type to avoid full UI lockup when viewing very large notes

### ISSUE THREAD

**Issue by geekpete** [Automattic/simplenote-electron#747]
#### Steps to reproduce
1. I have 800+ notes, some of them large, so probably needs a certain count of notes to hit the performance issue. I think it's repeatable if you're currently viewing a very large sized note.
2. Type in the search box and it will immediately start a search with the first character and this doesn't appear to perform very well since it will match many notes and need to highlight each occurrance of the char within the large document
3. try to continue typing but find the UI isn't responding since it's too busy going through the large doc.

#### What I expected

For the UI/app not to lock up and for the speed of search and highlight as you type to work/perform the same way on large documents as on small ones.

#### What happened instead

It went slow or locked up the UI so I wasn't able to continue typing or interacting with the app.
Have some circuit breaker or only highlight a subset of the doc to prevent full UI lockup (or do it asynchonously?) if the note is over a certain size. Or maybe use some sort of paging under the hood to only have to deal with the visible text.

#### OS version

OSX 
Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by mirka** [comment]
Closing in favor of #1107.
