### ISSUE TITLE
Support nested tags

### ISSUE THREAD

**Issue by adamshand** [Automattic/simplenote-electron#750]
Hey,

Longtime Simplenote fan, from want back in Notational Velocity days.  Thanks for the ongoing support of a great app.

I use note applications to store my entire brain, so I end up with lots of notes.  The tagging feature is great, but I end up with so many tags that it gets unwieldy.

I love what [Bear did with nested tags](https://blog.bear-writer.com/organize-notes-with-tags-and-infinite-nested-tags-c42b02b2c0d7 ).  So tagging something with year/2018 and year/2012 means that in the tag window you see:

year/
  * 2017
  * 2012

This is also very similar to what Google does with labels in Gmail.

And if you don't care about the sub-tags you can just collapse it so all the sidebar shows is "year/".

Thanks again.
Adam.

**Comment by MorgothSauron** [comment]
+1

**Comment by Lumiras** [comment]
+1 as well. I'm trying to move from Ulysses to Simplenote and this would be really the only feature they offer that Simplenote doesn't. It would be much appreciated!

**Comment by awrog** [comment]
~1

**Comment by dmsnell** [comment]
Hey all, thanks for sharing here! I don't want to sound harsh but please don't leave `+1` comments as they don't help us and don't help you either :wink:

We'd love to be able to hear you when you think a given issue needs higher priority, but adding a 👍 as a reaction to someone else's comment or to the issue description is a much nicer way to manage the intention on Github.

At this point in time I wouldn't expect to see a tree view of the tags on the sidebar. It's already the case that if we add the tag `year` and `2017` to a note then it will show up in a search for either of those, and we can manually order tags if, for example, we wanted `2017` to be at the top of the list. I realize that this doesn't address everything that has been shared here as a want but for the time now we're not sure if we will move this direction at all and even if we _were_ it wouldn't be coming any time soon.

Further, we would happily welcome contribution. This is a community project and the best way to get a feature that you want is to engage with the project and build out a solution that demonstrates it 😄

**Comment by Kristyjnh** [comment]
I too would love this. Even with just a few notes, if you're tagging each note with multiple things the tags bar quickly becomes unwieldy. I'd love to drop Evernote, I'm basically just waiting on this feature.

**Comment by Bajocode** [comment]
First of all, great job on the app guys, I really think you understand what people actually need; cross platform synchronization (as wide as possible, even Linux) and multi format input (markdown & text).

I do think the application is missing out on a crucial part of a note taking apps: organization

A nested tagging feature should be top priority, as in:

- RootTag/SubTag/SubSubTag

Here is an example of how the guys art Bear notes nailed that one: https://bear.app/faq/Tags%20&%20Linking/Nested%20Tags/

Adding this features does not at all conflict with SimpleNote's simple philosophy as it's a very practical and necessary functionality for your product and will make the others truly obsolete.

F

**Comment by darnelldibbles** [comment]
Another request came in via Twitter: https://twitter.com/jplonghi/status/1090351264012124160

**Comment by jplonghi** [comment]
+1

**Comment by EnterpriseBranding** [comment]
Hi!

I found this via search engine when comparing note taking apps.

I just wanted to follow this thread and also state, that I did not know SimpleNote was of Automattic. Because it is I would like to support it, but I would need this feature as well. So adding a +1 👍 for this feature. <3

**Comment by joshm89** [comment]
I've just moved over to Simplenote from Bear because I need something that will work on Windows, Linux and macOS and I'm really missing this functionality. Nested folders allow me to keep things much better organised and keep related notes together.

![Screenshot 2019-04-24 at 11 26 43](https://user-images.githubusercontent.com/48421167/56652681-da41b900-6683-11e9-930a-a30a71f6799f.png)

**Comment by raul-xag** [comment]
Guys, what do you think about this?
![Screenshot_2019-05-12_20-46-16](https://user-images.githubusercontent.com/49216144/57589222-6e6ea580-74f7-11e9-974a-6c7fcb637c05.png)
I just added tree or four spaces + this "↳" character. On Evernote, you can easily tag each notebook with a same-name tag, import them to Simplenote and add "↳" to all the subtags. It's just a visual thing, of course. There is no real hierarchy.

**Comment by EnterpriseBranding** [comment]
Following and hopeful :) 👍

**Comment by iamgabrielma** [comment]
Requested also in 2127685-zen

**Comment by darnelldibbles** [comment]
Another request:

https://twitter.com/shendavidesign/status/1149075385444794368

**Comment by AdamHutchison** [comment]
I completely agree, this is a fantastic app and nested tags would be a great addition.

**Comment by TwisterMc** [comment]
Where as nested tags sounds good, it depends on how it works. In Bear, the parent tag includes all the children's notes. I like a folder structure where the parent folder only shows what's in that folder. It's cleaner and feels more organized to me.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests! We will update when or if this work is imminent. It is not currently on our roadmap.
