### ISSUE TITLE
Web app feature parity: Searching multiple tags returns different results in web vs. app

### ISSUE THREAD

**Issue by cecoates** [Automattic/simplenote-electron#752]
I tested with Android/Linux apps, user in 1089651-zen tested in Android/Windows.

#### Steps to reproduce
1. Create three notes. One with the tag tag1, one with the tag tag2, and one with both tag1 and tag2.
2. Type 'tag:tag1 tag:tag2' into the search box.

The web app will return notes tagged with tag1 or tag2.

The desktop (Linux) app and Android apps only return notes tagged with both tag1 AND tag2.

#### What I expected

To see a list of notes with either tag.

#### What happened instead

Results only listed notes with both tags.

#### OS version

Debian GNU/Linux 9 (stretch) 64-bit, Simplenote version 1.1.3

Pixel XL with Android 8.1.0, Simplenote version 1.5.8

#### Screenshot / Video

Web app:

![screen shot 2018-04-24 at 11 46 27](https://user-images.githubusercontent.com/10121835/39201620-32ca38b6-47b5-11e8-8a27-1634bd112c36.png)

Android app:

![screenshot_20180424-114729](https://user-images.githubusercontent.com/10121835/39201699-69b39e62-47b5-11e8-8c74-188cbdd26a14.png)

Linux app:

![selection_018](https://user-images.githubusercontent.com/10121835/39201669-55355d36-47b5-11e8-9caf-0828e5fa35fb.jpg)

**Comment by codebykat** [comment]
Tag searches are an `AND` now on all platforms.
