### ISSUE TITLE
Allow collaboration for all notes with a particular tag

### ISSUE THREAD

**Issue by adamshand** [Automattic/simplenote-electron#754]
I love the new features which allow me to share notes with my family, friends and colleagues.  Thanks!

However, it would be even better if I could collaborate with somebody with all of the notes with a particular tag (or group of people).

For example:

* any note tagged with my wife's name would automatically have her as a collaborator.
* any note tagged with "family" would automatically have my mum, dad and sister as collaborators.

Many thanks,
Adam.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
