### ISSUE TITLE
Shortcut colors on dark theme

### ISSUE THREAD

**Issue by rianquinn** [Automattic/simplenote-electron#755]
In Linux, using Adwaita-dark (Gnome 3.28), the shortcuts are hard to see

![screenshot from 2018-04-25 16-33-26](https://user-images.githubusercontent.com/5932003/39276537-b141c6b8-48a6-11e8-825e-569d37137df6.png)

**Comment by mirka** [comment]
Unfortunately this is not something we can address on our end, but you can try posting an issue with Electron to see if they can fix it: https://github.com/electron/electron
