### ISSUE TITLE
[Feature Request] Title Font Size / Boldness

### ISSUE THREAD

**Issue by rianquinn** [Automattic/simplenote-electron#757]
Right now, a note's title and it's text are so similar, its hard to see the difference. It would be great if you could change the font size, and boldness of the title so that those of us who have terrible eyes can configure this.

**Comment by mirka** [comment]
We probably won't be making it user-configurable, but I agree that it would be better to have more size contrast by default.

**Comment by bummytime** [comment]
Closing this in favor of #1391
