### ISSUE TITLE
Don't silently modify release files

### ISSUE THREAD

**Issue by swalladge** [Automattic/simplenote-electron#759]
It appears that the latest .deb release file (<https://github.com/Automattic/simplenote-electron/releases/download/v1.1.3/Simplenote-linux-1.1.3.deb>) has been modified at least twice since it was published, resulting in the community Archlinux package for simplenote breaking at times since the checksum changes. See https://aur.archlinux.org/packages/simplenote-electron-bin/ for reference.

Curious to know if this has been intentional - if so, please consider not clobbering published files (it's bad for user experience and trust); if not, perhaps something malicious has been tampering with your releases?

**Comment by kewlfft** [comment]
Same comment here, this is an issue, we generally prefer building from source rather than using the binary. If in addition the package is changing unexpectedly and with no proper log and tracking we may have to stop supporting `simplenote-electron` for security reasons.

**Comment by mirka** [comment]
Thanks for flagging this. We'll keep this in mind!
