### ISSUE TITLE
Linux: text updates added in Simplenote 1.1.3 lost after closing app

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-electron#761]
Reference 1138698-zen

#### Steps to reproduce

Report from user:

Last night I lost some text from a note.
Here is a timeline of what occurred:
1. I finished up taking some notes last night after midnight, and had shutdown my Linux mint 4.4.0-122-generic computer from the menu without closing simplenote v1.1.3, assuming simplenote had synced.
2. Once I had left home the following morning, I was reading the same note from my iPhone5 iOS9 (latest simplenote version) and made a small change.
3. Upon scrolling down I realised that the rest my notes that I wrote after midnight weren't synced.
4. I called up a friend to have them log in to get simplenote to re-sync, but they couldn't log in, and linux was giving the error message "MDM could not write to your authorization file", (I found this strange given that I was sure that my file system wasn't full)
5. I came back home, and attempted to fix the above issue, and did so by running `sudo apt-get clean` through ssh.
6. I opened simplenote after disconnecting the internet and noticed that my text wasn't saved at all.
7. I reconnected the internet and let simplenote sync as normal, all my notes had updated but nothing in regards to the missing text.
8. Nothing was found in the trash, in the history, in the search, or in any other notes.

I'm not sure whether the linux login issue had anything to do with the simplenote problem, but I have had at least one other occasion where a note has disappeared from me.

#### What I expected

1. Edit text in Simplenote app.
2. Close app after giving the app an opportunity to sync.
3. See edited text afterwards.

#### What happened instead

Edits made to note in Linux version of the app were not synced, and subsequently lost.

#### OS version

Linux mint 4.4.0-122-generic
Simplenote 1.1.3

**Comment by pauljacobson** [comment]
Updates from the user:

1. The user doesn't recall any particular connectivity issues on their side;
2. The user also doesn't appear to have closed the app immediately after editing their notes.

**Comment by pauljacobson** [comment]
Another update from the user:

>I think I've located the problem.
>The issue occurs when my disk runs out of memory.
>If the disk is full, simplenote won't open.
>If the disk becomes full while simplenote is open, you can't open a new note when navigating back to the notes page when one is already open.
>I wasn't able to record what happens when you try to edit a note while the disk is full.

**Comment by roundhill** [comment]
> The issue occurs when my disk runs out of memory.
> If the disk is full, simplenote won't open.
> If the disk becomes full while simplenote is open, you can't open a new note when navigating back to the notes page when one is already open.
> I wasn't able to record what happens when you try to edit a note while the disk is full.

We can't do much about that :) Going to close this one.
