### ISSUE TITLE
Feature Request: package Simplenote as a snap/appimage/flatpak

### ISSUE THREAD

**Issue by tavilla61** [Automattic/simplenote-electron#762]
#### Steps to reproduce
1.
2.
3.
4.

#### Screenshot / Video

Request from Simplenote user who says "Your product is fantastic, and packaging as one of these options would make it way more convenient for Linux users!"

**Comment by grvrulz** [comment]
For Flatpak, it should be submitted to Flathub https://flathub.org

Here's a sample packaging recipe for Atom from Flathub https://github.com/flathub/io.atom.Atom/

How to submit ton app
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by mirka** [comment]
AppImage packages are also now available on the [releases page](https://github.com/Automattic/simplenote-electron/releases).

**Comment by okanakinci** [comment]
Simplenote's Snap app is pretty good. But I don't use Snapd Package System. I think Flatpak Package System ise better than Snapd. Can you make a Flatpak package?
