### ISSUE TITLE
Markdown preview: Add styling for <kbd> tag

### ISSUE THREAD

**Issue by grvrulz** [Automattic/simplenote-electron#763]
#### Steps to reproduce
1. Create a note in Markdown.
2. Write some text wrapped in `<kbd>` tags
3. Switch to preview

#### What I expected
Monospace font and some styling for the text in kbd tag

#### What happened instead
Regular text styling.

#### OS version
SImplenote 1.1.3 on Ubuntu 18.04
Also reproduced on the latest version of the Mac OS app.

#### Screenshot / Video

![Gif showing the issue](https://user-images.githubusercontent.com/1659416/40216975-db733a46-5a87-11e8-8ae3-d3b83503476b.gif)

**Comment by rakhi2104** [comment]
I'll work on it.
