### ISSUE TITLE
Toggle markdown shortcut not working (ctrlOrCmd shift p) on mac osx 10.13.3

### ISSUE THREAD

**Issue by liangmicha** [Automattic/simplenote-electron#765]
#### Steps to reproduce
1. Open a note in simplenote (version 1.3.3)
2. press cmd + shift + p

#### What I expected
I expected this to toggle to the markdown preview view.

#### What happened instead
It stays on the edit note view.

#### OS version
Mac OSX (10.13.3 High Sierra)

#### References
Also looks like at the bottom of this PR: https://github.com/Automattic/simplenote-electron/pull/603 someone else is also having the same issue.

**Comment by mirka** [comment]
Thanks! Since your Simplenote version is 1.3.3, I believe you are using the [native Mac app](https://github.com/Automattic/simplenote-macos), not simplenote-electron. There seems to be [a feature request](https://github.com/Automattic/simplenote-macos/issues/131) at the simplenote-macos repository.
