### ISSUE TITLE
Wrong permissions for unzipped files

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#767]
This came up on 1187583-zen:

> Your zip download has the wrong permissions for the zipped files. They all have (I think) 000 permissions so no one can read/write/execute them. It can be fixed by chmoding them so I can still use the feature, but I thought you should know that it's broken!

> The actual zip file permissions are fine; it's the files within the zip (after being unzipped) that have the wrong permissions.

#### Steps to reproduce
1. Go to https://app.simplenote.com/signin and login.
2. Download your notes.
3. Unzip the file and check for its permissions
4. You'll see that permissions are set to `----------` when should be something like `-r--r--r--` or `drwxr-xr-x`

**Comment by roundhill** [comment]
Moved this issue to the web app repo.
