### ISSUE TITLE
Android App missing Hardware Keyboard shortcuts 

### ISSUE THREAD

**Issue by sitaramp** [Automattic/simplenote-electron#769]
Android apps on Chromebooks with hardware keyboard or wireless hardware keyboard must take advantage of Ctrl+ keyboard shortcuts like its desktop counterparts.
#### Steps to reproduce
1.Install android app on chromebook 
2. press Ctrl+F
3. Nothing happens.
4.

#### What I expected
Search field is activated on Ctrl+F

#### What happened instead
Ctrl+ keyboard combinations not recognized 

#### OS version
Android 8.0

**Comment by roundhill** [comment]
Moved to https://github.com/Automattic/simplenote-android/issues/538
