### ISSUE TITLE
Web: Users from China cannot log in because of Google Captcha

### ISSUE THREAD

**Issue by kriskorn** [Automattic/simplenote-electron#775]
#### Steps to reproduce
1. Be a user based in China
2. Go to https://app.simplenote.com/signin
3. Fill the fields and click the sign in button

#### What I expected

To be logged in to the Simplenote app.

#### What happened instead

Saw an error message about "Invalid captcha", but as Google is blocked in China, no captcha is shown to the user in the first place.

User report in #1230039-zen

**Comment by mirka** [comment]
The captcha on the web app is removed for now, since we’ve added a few more protections. We’ll keep an eye on things and hopefully we won’t need it anymore.
