### ISSUE TITLE
Dashes in markdown list multiply upon hitting return

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-electron#776]
#### Steps to reproduce
1. Create a new note
2. Add a dash in front of a note, as if making a list
3. Move the cursor in front of the dash and hit enter
4. You will see another dash prefixed to the note, rendering `--`

#### What I expected
No dash to be added.

#### What happened instead
Dash was added. 

####Gif here:
![screen capture on 2018-06-24 at 06-56-06](https://user-images.githubusercontent.com/19782997/41820102-e5c63cf6-7791-11e8-994b-fdae7be4c597.gif)

####Note: I am using the mac OS app in the screen capture but the same thing happens. This does not happen in the web app. Have not tested on iOS or android.

**Comment by marianoju** [comment]
+1 
Same experience here. 112 days later that bug is still not fixed.
