### ISSUE TITLE
Add code snippets using a button

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-electron#778]
A user contacted us through 1239902-zen with the following feature request:

>If it is possible can you add code snippets features in upcoming updates? Just a button at the top to insert code snippets in preformatted style. That will be great for developers. I know it is possible to add through markdown features but it is a bit time-consuming.

The user also shared some feedback for our awesome developers:

>Simplenote has really changed my work life. I am able to store notes and access it anywhere. I often use it during my projects.
>...
>Finally, kudos to the developers' team for making Simplenote available for all for free.

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!
