### ISSUE TITLE
Typing CJK after a Tab character can crash the app

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-electron#780]
#### Steps to reproduce
1. Open your Simplenote app.
2. Change the keyboard layout into Chinese(Simplified Chinese)
3. Now try to type something in a note an increase your speed.
4. The app will crash most of the times.

#### What I expected
To work in a similar way as when using the ABC alphabet.

#### What happened instead
It crashed the app.

#### OS version
MacOS
The user also reports the following:
>Mac and Linux Manjaro.

#### Screenshot / Video

https://monosnap.com/file/D9Wqx5L9idY7WZRYLvFdjZKRSEH4lb#

More details from the user:

>* The version on Windows is 1.16, installed by Windows Store.
>* The version on Mac is 1.16, installed by homebrew.
>* The version on Manjaro is 1.1.6-1, which is maintained by aur-simplenote-electron-bin (https://aur.archlinux.org/packages/simplenote-electron-bin/)

Please note that this won't break the app if you copy-paste the characters so it is important to change the keyboard layout.

Case: #1233037-zen

**Comment by mirka** [comment]
With information from the original support request, the exact steps I took to reproduce this are:

1. In the note editor, hit <kbd>Tab</kbd> and type any Latin character (like `-`).
1. Set the keyboard layout to Japanese.
1. Type the key sequence `kanji`, hit <kbd>Space</kbd>, and then <kbd>Enter</kbd> to confirm the conversion to `漢字`.
1. Backspace.

The app will crash.

This is likely a bug in `draft-js`, and I'm not sure we can fix it on our end.

**Comment by mgalbritton** [comment]
Another report of this in #1664641-zen.

**Comment by mgalbritton** [comment]
Another report of this in #1697597-zen.

**Comment by mirka** [comment]
For those who are experiencing this issue, a workaround is to use spaces instead of tabs.

**Comment by mirka** [comment]
> This is likely a bug in `draft-js`, and I'm not sure we can fix it on our end.

I looked into this a little, and it may be a bug (or if not, may be worked around) in our [`indentCurrentBlock` function](https://github.com/Automattic/simplenote-electron/blob/master/lib/note-content-editor.jsx#L20). We'll need to investigate further.

**Comment by mgalbritton** [comment]
Another report in #1714515-zen

**Comment by brezocordero** [comment]
Another report in zen-1728879

**Comment by mirka** [comment]
> zen-1720385
> 
> From user:
> "I didn't use tab, only SPACE in the GIF.

From the screenshot in the support request, I can see that the crash is happening on a line that is a nested list item, which has a tab character at the beginning. So I'd say this is the same issue 👍
