### ISSUE TITLE
Simplenote in Brazilian Portuguese

### ISSUE THREAD

**Issue by mv-santos** [Automattic/simplenote-electron#786]
Hello,

Firstly, I'd like to say thanks and congratulate you on the great work you have done. I started using _Simplenote_ few months ago and really loved its plainness, it's so quick and practical!

Yesterday I contacted you through the support form to ask if would you be interested in translating the web and Linux applications into Brazilian Portuguese. So Megan recommended that I contact you through your repo.

Do you plan to translate them into Brazilian Portuguese? It would be great to work on their localization.

Anyway, keep on the beautiful work! Best wishes!

**Comment by mirka** [comment]
Thank you for the kind words, and offering to help with translation! We don't have the infrastructure in place yet, but localization is definitely on our minds.

Closing in favor of #16.
