### ISSUE TITLE
Simplenote not working in openSUSE Leap 15

### ISSUE THREAD

**Issue by cpt1971** [Automattic/simplenote-electron#792]
I've tried the tar version of Simplenote on openSUSE Leap 15. The apps loads but gets no login UI box.

This same issue is true for V1.1.4, V1.1.5 and V1.1.6

The app seemed to work OK with V1.1.3

Any ideas?
Thanks Chris

**Comment by mirka** [comment]
Does this still happen with v1.2.1? If so, could you post a screenshot?

**Comment by cpt1971** [comment]
Hi, the strange thing was that it worked on xfce on leap 15, but not on kde leap 15.

I have not tested it yet for 1.2.1, but I will next week and get back to you.

**Comment by cpt1971** [comment]
I've just tested kde leap 15 with version 1.2.1 and it works well :-)
Many thanks
Chris
