### ISSUE TITLE
Password change won't display the notes in Windows

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-electron#794]
#### Steps to reproduce
1. Log in the Simplenote app on Windows
2. Log into the Simplenote account and change the password
3. Go back on the app, close it (if open) and open it again.
4. The notes won't show up anymore and I can't do anything about it(add notes/etc). It will be pretty blank

#### What I expected
To log me out or to keep me logged in as on MacOS.

#### What happened instead
It showed me the a rather empty app with no action to take.

#### OS version
Windows 10

Temporary workaround:
Log out of the app via File-> Prefferances-> Log out and log back in to see them again.

Possible case:  #1341102-zen

**Comment by mgalbritton** [comment]
Looks like it has been reported in [Issue 679](https://github.com/Automattic/simplenote-electron/issues/679)

**Comment by sashastone** [comment]
No notes displaying after password change on Microsoft Surface running Windows 10, even after uninstalling and reinstalling the app: #1341102-zen

**Comment by Robertght** [comment]
@mgalbritton Thanks! I'm not able to replicate this behavior on MacOS though. Are you able to?

**Comment by mgalbritton** [comment]
@Robertght No I cannot replicate on MacOS. Sorry!

**Comment by jenlynnemc** [comment]
User attached screenshot:
![screenshot 2](https://user-images.githubusercontent.com/26546176/45295248-64158b00-b4d4-11e8-86df-af3d8950bd39.png)

**Comment by mirka** [comment]
Fixed in #1022. The fix will not make it into v1.3.0, but we'll get it out soon 👍
