### ISSUE TITLE
Up/Down keys should navigate the notes list

### ISSUE THREAD

**Issue by uncertainquark** [Automattic/simplenote-electron#799]
The notes list is not navigable using the intuitive Up/Down keys, especially considering that a note is always highlighted on app launch.

#### Steps to reproduce
1. Open Simplenote
2. Try to navigate using Up/Down key

#### What I expected
The notes list will be navigated up/down using the said keys.

#### What happened instead
No other notes get selected.

#### OS version
Ubuntu 18.04

**Comment by uncertainquark** [comment]
As suggested in #798, it maybe better to use `CTRL+PgUp` to go up the list of notes, and `CTRL+PgDn` to go down? That would be in line with Gnome user conventions (such as scrolling through tabs in Nautilus/Terminal/Chrome/etc).

**Comment by belcherj** [comment]
Thanks!  I’ve added this to our feature requests!

**Comment by codebykat** [comment]
#1983
