### ISSUE TITLE
Give an action button to manually initiate a sync

### ISSUE THREAD

**Issue by uncertainquark** [Automattic/simplenote-electron#800]
In case the sync doesn't work automatically (say due to poor connection), forcing a manual sync using a given button would be helpful.

#### OS version
Ubuntu 18.04

**Comment by iamgabrielma** [comment]
1910794-zen

> I have to wait sometimes for update/sync, very odd and confusing due to lack of knowing actual update of info I am seeing,

**Comment by iamgabrielma** [comment]
1983783-zen

> given the VERY high failure rate of my mobile to sync, I'm requesting some sort of sync button or way to force note syncing. It simply does not work right now. It can even be buried in a setting menu until you get it fixed. I just can't go to a meeting without the note syncing.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
