### ISSUE TITLE
Please settle on a naming convention for your releases on github

### ISSUE THREAD

**Issue by el-psycho** [Automattic/simplenote-electron#804]
Currently I build a personal RPM with a SPEC file that references the download link to the deb package, which is extracted and repackaged as an RPM. To build a new simplenote version RPM with this inconsistent naming of the deb package I have to come see how the package was named this time on the github releases page. 

Names I've seen are:
- Simplenote-linux-1.1.3.deb
- Simplenote_1.1.4_amd64.deb
- simplenote_1.1.5_amd64.deb
- Simplenote-1.1.7-amd64.deb

The Source in the SPEC file looks like this:
` Source0:        https://github.com/Automattic/simplenote-electron/releases/download/v%{version}/simplenote_%{version}_amd64.deb`

If the naming was reliable and consistent all that would be needed for a new RPM would be to change the `%{version}` variable. Other release formats on the releases page show similar naming inconsistencies between releases.

**Comment by roundhill** [comment]
We're adding server builds soon which should standardize the naming 👍 

cc @adlk

**Comment by adlk** [comment]
In the works #809

**Comment by mirka** [comment]
Resolved in #809
