### ISSUE TITLE
[Feature Request] Table of Content

### ISSUE THREAD

**Issue by RCDCL5** [Automattic/simplenote-electron#811]
### Table of Content

One command which creates Jumplinks / A table of content of all headings... like in this examplepicture it sums up all headings and if I add a new heading the table of content adds it automatically as a simple jumplink.

It is a very "simple" ;) feature

![unbenannt](https://user-images.githubusercontent.com/42832561/44840655-cbfce380-ac41-11e8-8e0c-4adbf4087355.png)

**Comment by melsophos** [comment]
I agree that this feature would be extremely useful: it would greatly help to navigate very long notes.
The table of content could be displayed on the left or right of the notes, with an option (associated to a shortcut) to hide or display it.

**Comment by michaelwexler** [comment]
Seconded.  I've been hoping for this for a while, and some markdown extensions already have a tag and approach for it.  It would be very nice to see here.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
