### ISSUE TITLE
Labeling and shortcut errors in menus

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#816]
There are some errors in the menus that make the app feel less native.

Most of these can be fixed by adding the correct `role` and/or removing the `label` where unnecessary, as Electron has [a lot of the logic built in](https://github.com/electron/electron/blob/master/lib/browser/api/menu-item-roles.js).

We should probably do some refactoring to allow easier per-platform logic based on composition, since we will be adding more menu items. The current system is quite error-prone and is bloating the app.js file.

### all
- [x] `accelerator` for “Font Size ▸ Bigger” should be `CommandOrControl+Plus` instead of `CommandOrControl+=` ([Quirk](https://github.com/atom/electron/issues/1507) seems to be fixed now) (#863)
- [ ] Multi-step items (“Preferences”, “Export Notes”, “Print”, “Search Notes”) should have an ellipsis `…` appended

### darwin
- [ ] Shortcut for “Hide Others” should be Cmd+Opt+H
- [ ] “Hide” and “Quit” should be suffixed by app name
- [ ] Help menu should include searchable field (can be achieved by adding `role: 'help'`)
- [x] “Bring All to Front” is in the wrong menu (#813)

### linux
- [ ] “Exit” should be “Quit”
- [ ] Window menu should not exist
- [ ] Help / Help & Support is duplicated

### win32
- [ ] Shortcut for “Redo” should be Ctrl+Y
- [ ] Window menu should not exist

**Comment by mirka** [comment]
>> Shortcut for “Redo” should be Ctrl+Y
>
> is it applicable only to Windows ?

Yes, and I think removing the explicit `accelerator` property and using just `role: 'redo'` would work, because the logic is [baked into Electron](https://github.com/electron/electron/blob/176a76217c5f70d92bf21f6782a0c838a1e5058e/lib/browser/api/menu-item-roles.js#L80). We are actually overwriting the platform logic by adding an accelerator ourselves 😅

**Comment by rakhi2104** [comment]
Updating those changes @mirka.
Thanks for reviewing

**Comment by rakhi2104** [comment]
Most of the edit commands already have `role` assigned in the code.
Is `accelerator` overriding them ?

**Comment by mirka** [comment]
> Most of the edit commands already have role assigned in the code.
> Is accelerator overriding them ?

That's correct. So my plan was to look at the [Electron code for menu item roles](https://github.com/electron/electron/blob/176a76217c5f70d92bf21f6782a0c838a1e5058e/lib/browser/api/menu-item-roles.js), and remove any properties from our code that is unnecessary.

We still have to override the `label`s though, because the default labels don't include Windows access keys.  (That's what the [ampersands in the labels](https://github.com/electron/electron/issues/1698) are)
