### ISSUE TITLE
Rethink labels for “Note Display”

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#819]
“Note Display” is a somewhat unintuitive label, and will continue to cause confusion as we add more settings relating to the display of notes.

Gmail has been using the term “density” for this kind of setting, and I think that would be a good choice here.

And of the three options, “Comfy” will probably cause translation woes as we start to localize the menu strings. I think it could safely be renamed “Default”.

So I propose something like this:

```
Note List Density:
Default / Condensed / Expanded
```

Or we could be more descriptive:

```
Note List:
Title Only / Short Excerpt / Long Excerpt
```

**Comment by belcherj** [comment]
@SylvesterWilmott what you think about this? Can you include this in your settings update? Closing for now.
