### ISSUE TITLE
Recaptcha doesn't work on Windows app in China

### ISSUE THREAD

**Issue by zandyring** [Automattic/simplenote-electron#824]
Recaptcha is blocked in China, so users of the Windows app (and possibly any of the desktop apps) get similarly blocked.

This was reported via a ticket 1386059-zen

I can ask for screenshots of the behavior.

**Comment by mirka** [comment]
The captcha on the web app is removed for now, since we’ve added a few more protections. We’ll keep an eye on things and hopefully we won’t need it anymore.
