### ISSUE TITLE
Tracks: Opt Out

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-electron#837]
### Details:
- [ ] Add a new boolean field to the`Settings` entity (Simperium backed) to persist if the user opted out from Tracks
- [ ] Add a new Switch in the Settings UI

Ref. [iOS Issue](https://github.com/Automattic/simplenote-ios/issues/222)

**Comment by roundhill** [comment]
Note: The bucket to use is now `preferences`, with a boolean field named `analytics_enabled`. Correct me if I'm wrong @jleandroperez :)

**Comment by jleandroperez** [comment]
That would be correct Dan!
