### ISSUE TITLE
No way to remove the "Update Available" modal popup?

### ISSUE THREAD

**Issue by pakal** [Automattic/simplenote-electron#842]
I thinks users should be able to disable update checks, like on any app; I found nothing in program preferences or "about" page.
Especially since updating, here, means downloading and installing a new program manually.

**Comment by gemmagarner** [comment]
Requested [on Twitter](https://twitter.com/Li_Guilong/status/1073515186961694720).

**Comment by gemmagarner** [comment]
Request [on Twitter](https://twitter.com/pipe__alvarez/status/1088065985628815361).

**Comment by MyOneTaps** [comment]
This issue drives at the core use case of SimpleNote and is getting too little attention.

The entire point of a note app is to add permanence to potentially ephemeral thoughts. We have something we don't want to forget so we open SimpleNote or an alternative to save it. Every barrier you add to this process increases the likelihood that the thought is lost--potentially forever.

Update modals on start betrays a key misunderstanding between either your CEO and your users, your CEO and Head of Product, or your Head of Product and the developers.

On start is literally the worse possible time to interrupt the user. Besides, unless the update relates to data integrity, most users are maximally inconvenienced for minimal benefit. You're not in a feature race: your motto shouldn't be "Move Fast and Break Things".

**Comment by EmperorEarth** [comment]
This issue drives at the core use case of SimpleNote and is getting too little attention.

The entire point of a note app is to add permanence to potentially ephemeral thoughts. We have something we don't want to forget so we open SimpleNote or an alternative to save it. Every barrier you add to this process increases the likelihood that the thought is lost--potentially forever.

Update modals on start betrays a key misunderstanding between either your CEO and your users, your CEO and Head of Product, or your Head of Product and the developers.

On start is literally the worse possible time to interrupt the user. Besides, unless the update relates to data integrity, most users are maximally inconvenienced for minimal benefit. You're not in a feature race: your motto shouldn't be "Move Fast and Break Things".

**Comment by EmperorEarth** [comment]
This issue drives at the core use case of SimpleNote and is getting too little attention.

The entire point of a note app is to add permanence to potentially ephemeral thoughts. We have something we don't want to forget so we open SimpleNote or an alternative to save it. Every barrier you add to this process increases the likelihood that the thought is lost--potentially forever.

On start is literally the worse possible time to interrupt the user. Besides, unless the update relates to data integrity, most users are maximally inconvenienced for minimal benefit. You're not in a feature race: your motto shouldn't be "Move Fast and Break Things".

**Comment by dmsnell** [comment]
Thanks @EmperorEarth for your feedback. Please know that adding a 👍 is the most effective way to share that this is important to you and usually more comments or energy in a comment won't have much of an impact on the speed with which we are able to address the issue.

I hear that this can be frustrating to you but please do know that we are real people who develop this app and we are real people who give it away for free. "Move Fast and Break Things" is about the diametric opposite of how we develop Simplenote and I'm not sure what led you to the impression that it would represent this app; we have consistently said no to most feature requests for the past five years I've been a part of it. That is, it sounds like an insult and insults rarely help persuade someone 😉

>  unless the update relates to data integrity

Ironically the past couple updates have made important fixes to exactly this and address headaches people were having when their data was lost.

---

When leaving a comment it helps us the most when people are specific and focus on their own needs and pains. If you share that you were frustrated when an update popup interrupted your thought then that's something we can work with.

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by volknerbat** [comment]
Why would you remove this from the Future milestone???????

**Comment by codebykat** [comment]
@volknerbat Sorry for the confusion - it was removed from Future as part of some backlog tidying, as we are no longer using the Future milestone. (In fact we hadn't been using it consistently for quite some time.) This has no bearing whatsoever on whether we plan to address this issue sometime in the future. Any issues that are not in a milestone on GitHub are effectively/implicitly in the Future milestone. 😅
