### ISSUE TITLE
Better interaction for restoring a trashed note

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#845]
Restoring a trashed note should display some kind of feedback, or go to All Notes view with the restored note selected. Probably the latter?

Current interaction:

![restore](https://user-images.githubusercontent.com/555336/45292115-28f47580-b52f-11e8-9ece-5ce516a7bc0f.gif)

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests! @SylvesterWilmott please reopen or create a new issue for the desired interaction.
