### ISSUE TITLE
Show animated loading screen when first loading notes

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#862]
After logging in to an existing account, the app displays a "No Notes" placeholder for a second while first loading all the notes.

It would save the users from a moment of panic if it were a loading screen instead.

**Comment by roundhill** [comment]
The native app shows a little spinner in the toolbar while it is indexing, it usually goes away in a second or two, but it is good to see that it's working on something :)

**Comment by codebykat** [comment]
We do now have a catch to show a "Loading" placeholder instead of "No Notes". #1649
