### ISSUE TITLE
Checkboxes in markdown preview should not be toggleable

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#875]
Users should not be able to toggle a checkbox in a previewed markdown checklist, since the actual note content will not be modified.

![click-checkbox](https://user-images.githubusercontent.com/555336/45916291-6695be80-be9e-11e8-83de-aa7b38af83ac.gif)

The `<input>`s can probably be `disabled` using an [output extension](https://github.com/showdownjs/showdown/wiki/extensions) with `showdown`.

**Comment by rakhi2104** [comment]
Hey @mirka, I tried to setOption 'tasklists' to true but it didn't change the behaviour of Checkboxes.
Any other work around ? (without creating an extension)
