### ISSUE TITLE
Modify note content when checkboxes are toggled in markdown checklists

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#876]
It would be great if we could toggle checkboxes in the markdown preview to modify the actual note content.

Current checkbox behavior (doesn't update note content):
![click-checkbox](https://user-images.githubusercontent.com/555336/45916476-e5402b00-bea1-11e8-95b0-7cf96308e442.gif)

However, I'm not immediately sure if we can easily convert the rendered HTML back to raw markdown without causing unexpected changes to other parts of the note content.

(Usability enhancement to disable checkbox toggling in the meantime: #875)

**Comment by roundhill** [comment]
We should style the checkboxes as well, those look like chrome default?
