### ISSUE TITLE
[Feature Request] Windows 10 for ARM package in Microsoft Store

### ISSUE THREAD

**Issue by Ecnassianer** [Automattic/simplenote-electron#878]
Windows 10 runs on ARM now!
https://docs.microsoft.com/en-us/windows/arm/

I went looking for the SimpleNote app on the Microsoft Store for my ARM device and couldn't find it. There is a package on my PC's Microsoft Store, but the system requirements say it's only for x64.

Would you mind adding an ARM version of SimpleNote to the Microsoft Store?

**Comment by roundhill** [comment]
I'm afraid it doesn't look possible at the moment: https://github.com/electron/electron/issues/9456

**Comment by Ecnassianer** [comment]
Thanks for the update!

**Comment by mirka** [comment]
Closing for now. We can revisit this when it becomes possible.

**Comment by Ecnassianer** [comment]
Electron now supports ARM!

**Comment by codebykat** [comment]
Yes, we're building ARM for Linux now. #2456  @belcherj should we reopen this?

**Comment by belcherj** [comment]
I have a surface X ARM machine that I use the app on. Let's reopen and see if we can get an ARM specific version running.
