### ISSUE TITLE
   Cannot login the normal account & password

### ISSUE THREAD

**Issue by lwx5924** [Automattic/simplenote-electron#882]
#### Steps to reproduce
1.  run command 'make package-osx'. 
2. open build 'Simplenote.app' generate by the last command.  
3.  login the origin account & password. 
4.  login failed and display 'The credentials you entered don't match'

#### What I expected

Login success

#### What happened instead

Login failed.

#### Screenshot / Video
![1](https://user-images.githubusercontent.com/6096406/46053985-b2cf5000-c177-11e8-8655-4b7a3a5836bc.png)

**Comment by mirka** [comment]
> How can I change to production databases if I use the build app( build by myself) ?

I'm afraid we don't support that. In development builds, please use a test account with test data 🙂

**Comment by lwx5924** [comment]
the production app does not support language highlight.

**Comment by mirka** [comment]
I'm not sure what that means, but if you can post an issue for that, we'll be happy to look into it!

**Comment by lwx5924** [comment]
@mirka simplenote production app I install from the app store, it does not support   'syntax highlighting', such as javascript & cplusplus. But the development builds support.

**Comment by mirka** [comment]
@lwx5924 Oh, I see what you're saying. The version in the Mac App Store is a native macOS app, and the repo is https://github.com/Automattic/simplenote-macos.

This repo here is the multi-platform Electron app, and that is why you are seeing slightly different feature support. Sorry for the confusion. You can download production builds of this Electron app from the [release page](https://github.com/Automattic/simplenote-electron/releases). [Here's the link](https://github.com/Automattic/simplenote-electron/releases/download/v1.1.7/Simplenote.app.1.1.7.zip) for the latest Electron release that runs on macOS. You will be able to use accounts in the production database, and you will get syntax highlighting.

**Comment by lwx5924** [comment]
@mirka thanks, that is what's I wanted. thanks for your kindly response.

**Comment by lwx5924** [comment]
@mirka  but I want to know, how can I use the production database if I build the code ( using git clone ...) way?

**Comment by mirka** [comment]
@lwx5924 We only support using the production database in official production builds. Is there still a reason you would want to use the prod database in your own builds?
