### ISSUE TITLE
Restoring a tag change revision doesn't work as expected

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#887]
The tag in the revision preview doesn't stick:

![tag-revision](https://user-images.githubusercontent.com/555336/46102817-2fab0a00-c20a-11e8-8c9d-e2962a290e25.gif)

**Comment by arunsathiya** [comment]
Noting that I am able to reproduce this as well on Simplenote for Electron. 

As a side note, on Simplenote for Mac (Simplenote 1.3.8), I am not able to see the tags in the revision. I have gone ahead and submitted this issue over here https://github.com/Automattic/simplenote-macos/issues/254
