### ISSUE TITLE
Application often crashes when backspace is pressed in windows7

### ISSUE THREAD

**Issue by mkanenobu** [Automattic/simplenote-electron#890]
Application often crashes when backspace is pressed.
And display blank white screen.

I'm always using markdown mode.

#### OS version
Windows 7
simplenote 1.1.7

**Comment by roundhill** [comment]
Do you have a way to reproduce this consistently? It'd really help us isolate the issue!

**Comment by mkanenobu** [comment]
Sorry, I can't reproduce it consistently.
But in most cases japanese IME was enabled.

**Comment by mirka** [comment]
I tried to crash it with some fast typing and backspacing using the Japanese Microsoft IME on Windows 7, but I couldn't get it to crash.

@mkanenobu Can you tell me what IME you are using, just in case? Google IME, ATOK, etc...

**Comment by mkanenobu** [comment]
@mirka I'm using Microsoft IME.

However, after updating to 1.2.1, this problem has not occurred.
Should I close this issue?

**Comment by mirka** [comment]
@mkanenobu Good to hear that! Feel free to add more information if you encounter the issue again 👍
