### ISSUE TITLE
F11 doesn't work in Ubuntu18.04 desktop

### ISSUE THREAD

**Issue by isdanni** [Automattic/simplenote-electron#891]
I entered Full-screen mode in **Simplenote Linux desktop** but cannot quit using `F11` shortcut. Now my only option is to use `Ctrl + Super + D` to enter desktop and quit Simplenote, but this still cannot let me out and every time I open the application I automatically enter the full-screen mode.

Is there a way to quit full-screen mode? Thanks!

**Comment by rakhi2104** [comment]
Which release of Simplenote are you using ?

**Comment by rakhi2104** [comment]
Maybe #904 should resolve, if any

**Comment by isdanni** [comment]
> 
> 
> Which release of Simplenote are you using ?

I'm using Version 1.1.7. However, `Esc` does not work after entering Full Screen Mode. I also tried `End Process` using `System Monitor` but it's still full screen after I restart Simplenote. Any other way to quit app?
