### ISSUE TITLE
"#" character rendered as a header inside blockquote on android

### ISSUE THREAD

**Issue by DanyGee** [Automattic/simplenote-electron#893]
#### Steps to reproduce
1. Run app
2. Make a note with blockquote containg a # sign
3. Compare the blockquote note on the desktop and android

#### What I expected
The same formatting

#### What happened instead
A # inside the blockquote is rendered as Header on android

#### OS version
Android - 8.0.0 @ LGv30
Elementary OS Linux - Juno Beta2 
#### Screenshot / Video
Desktop raw
![screenshot from 2018-10-08 13 41 05 2x](https://user-images.githubusercontent.com/26818551/46607177-469e0600-cb00-11e8-9306-e1ecd7a590e5.png)
Desktop markdown
![screenshot from 2018-10-08 13 40 35 2x](https://user-images.githubusercontent.com/26818551/46607179-4998f680-cb00-11e8-88a5-df044678786f.png)
Android raw
![photo_2018-10-08_13-44-00](https://user-images.githubusercontent.com/26818551/46607207-5f0e2080-cb00-11e8-8211-60a6b4ecbc4b.jpg)
Android markdown
![photo_2018-10-08_13-43-57](https://user-images.githubusercontent.com/26818551/46607209-61707a80-cb00-11e8-8f82-0a345f330217.jpg)

**Comment by mirka** [comment]
Thanks for reporting, @DanyGee !

I'm moving this to an [obscure place](https://github.com/Automattic/Simplenote-United/issues/) where we track cross-platform inconsistencies like this.
