### ISSUE TITLE
Click-dragging the pointer on the history slider moves the window

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/simplenote-electron#898]
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Get the Simplenote Electron app. 
- Create a note. 
- Create another note, for no reason.
- Come back to the first note and modify the note contents.
- Click on the history button at the top and see the slider appear over there.
- Click-drag the pointer on the slider.

#### What I expected

The pointer on the slider moves.

#### What happened instead

The Simplenote Electron app window moves.

**Note:** Clicking at select stages works fine though. 

#### OS version

macOS 10.14 - Mac OS Mojave

#### Screenshot / Video

[Here is a recording of this behavior](https://cloudup.com/cVc_-CFqVSb).

[This is similar to the report here](https://github.com/Automattic/simplenote-electron/issues/454), but that one was for the buttons.

**Comment by roundhill** [comment]
I think this may only happen on macOS, we have some special drag listeners for the way it renders the toolbar.

**Comment by mirka** [comment]
For reference: Electron docs on [draggable regions](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#draggable-region)

**Comment by louisabraham** [comment]
Hi, any update on this? I can confirm the bug still happens.
