### ISSUE TITLE
Add Web app name to Tracks

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#908]
When we start using this on the web, we should use an appropriate Tracks name so we know which requests came from the Web app.

We _could maybe_ just [change this code](https://github.com/Automattic/simplenote-electron/blob/master/lib/analytics/index.js#L20) from returning `unknown_` to `spweb_`?

**Comment by mirka** [comment]
> We could maybe just change this code from returning unknown_ to spweb_?

Probably not, because `navigator.appVersion.indexOf('Win')` would still match people using the web app on Windows. It might be easiest to set a global again like I did with `window.analyticsEnabled` 🤔

**Comment by roundhill** [comment]
> Probably not, because `navigator.appVersion.indexOf('Win')` would still match people using the web app on Windows.

Mmm good point.
