### ISSUE TITLE
Editor: Hiragana conversion display issue (Google IME)

### ISSUE THREAD

**Issue by naokomc** [Automattic/simplenote-electron#909]
#### Steps to reproduce
1. Add [Google IME Japanese](https://www.google.co.jp/ime/) to your Mac
2. Select hiragana = "ひらがな (Google)" as your input method
3. Start typing "kyo" in a Simplnote note and select one of the date formats
4. You get a garbled text as a preview
5. When you actually select a date format, the confirmed text is displayed correctly.

#### OS version
macOS Sierra 10.12.6

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/34067/46842472-c1209b80-ce08-11e8-8acc-083ccdcf51f5.png)

Video: https://cloudup.com/cyndeSf1ZC1

**Comment by mirka** [comment]
Thank you for the report!

I was able to reproduce this on the native Mac version and not on the Electron Mac version, so I'm guessing this is a report for the native one. I moved it to the [other repo](https://github.com/Automattic/simplenote-macos). Sorry for the confusion! (This seems to happen a lot, so I will improve the New Issue template to hopefully make it clearer 😅)
