### ISSUE TITLE
Latex/Math Preview

### ISSUE THREAD

**Issue by csc401** [Automattic/simplenote-electron#910]
Thanks for making the great software.  I am aware  math support has been discussed [two year ago](https://github.com/Automattic/simplenote-electron/issues/383), but would like to revisit this topic.

Math rendering would be the turn-key feature for the engineering/science community. MathJax/Katex has made great progress in recent years. E.g.,  [Atom markdown preview for math rendering](https://atom.io/packages/markdown-preview-plus). ![Example](https://i.github-camo.com/a33e36e8625ddcac07e2949151f9124909ed0e4a/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f61746f6d2d636f6d6d756e6974792f6d61726b646f776e2d707265766965772d706c75732f6d61737465722f696d67732f6d70702d66756c6c2d7265732d696e766572742e706e67)

MathJax/Katex based rendering seems particularly suitable for Electron. Would this be a possible addition to Simplenote ?

**Comment by rakhi2104** [comment]
Since Simplenote uses [Showdown.JS](http://showdownjs.com) to render Markdown.
Showdown doesn't support MathJax as of now.

**Comment by melsophos** [comment]
I strongly support this feature!
Apparently, there is an [extension to use Katex with Showdown](https://obedm503.github.io/showdown-katex/).

**Comment by rogersachan** [comment]
I support this as well!

**Comment by rogersachan** [comment]
Using the katex-showdown extension as mentioned in the showdownjs [tracker](https://github.com/showdownjs/showdown/issues/474) and mentioned above would be a great place to start. Dropbox Paper already uses KaTeX for math according to the katex repo, so this seems to be feasible.

**Comment by mirka** [comment]
Thank you for the extension suggestion!

Due to the nature of being a cross-platform app, one thing we have to consider is whether this is also achievable on the other platform versions (iOS, Android, macOS). It seems like Markdown parity has been [hard to achieve](https://github.com/Automattic/Simplenote-United/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+markdown), even with the relatively standard Markdown features we currently have.

**Comment by rogersachan** [comment]
@mirka Dropbox Paper has this feature implemented on iOS/Android.

**Comment by v-marinkov** [comment]
Math support would be essential for me. Now I use Dynalist which does support math

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by i2** [comment]
Is there a link to this feature request? Any update on this? Thank you!

**Comment by cossio** [comment]
Hi, any update on this feature? Thanks!

**Comment by lgcavalheiro** [comment]
Hi! Is there an update on this feature? Been needing it for statistics studies. Thank you!

**Comment by SamNour** [comment]
Is there any update on the feature still :/ ?
