### ISSUE TITLE
Improve .deb App Name and Description

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-electron#917]
When you install the .deb package in Ubuntu, you get:

<img width="706" alt="screen shot 2018-10-15 at 12 54 33 pm" src="https://user-images.githubusercontent.com/789137/46974683-94bf8600-d079-11e8-8760-2c54631a4719.png">

A few things I noticed:
* `simplenote` needs a capital `S`
* Can we add the app icon somehow?
* The app description seems incorrect, it doesn't match any of our other app descriptions. Missing the `an` word in `Simplenote is modern note...`

**Comment by marianoju** [comment]
“Simplenote is _an_ modern note...”?! How about: 

> Light, clean and free. Simplenote is a modern note taking app available for iOS, Android, macOS, Windows, Linux and via web browser.

**Comment by roundhill** [comment]
Yes, `a` is better there thanks!

Aha I found it: https://github.com/Automattic/simplenote-electron/blob/master/package.json#L3. We should nuke that whole line and put an actual marketing summary there, not sure who wrote that.

**Comment by justinkterry** [comment]
Here's another thing that should be fixed with this: In ubuntu, it lists the software as proprietary in the installer, but the front end here is under GPLv2

**Comment by mirka** [comment]
Closing this for now, since we fixed the description, but there doesn't seem to be a way to set the icon, capitalized app name, or license 😬 (As mentioned in #1030)
