### ISSUE TITLE
sharing notes via tag field in app fails

### ISSUE THREAD

**Issue by marianoju** [Automattic/simplenote-electron#918]
#### Steps to reproduce
1. Open note in Andoid app 
2. Add email address as a tag (bottom) 
3. Wait for anything to happen 

#### What I expected
This used to be an easy and quick possibility to share a note with another person (see #915). I expected an email to be sent to the email address with a link to the note. 

#### What happened instead
Nothing ever happened. Has this functionality has been discontinued? 

Suggestion if so: provide feedback to the user upon insertion of an email address as a tag to a note (“Sharing notes via tag has been discontinued. Press the Share icon in the toolbar to collaborate with another Simplenote user or publish a note.”) 

#### Simplenote version
1.6.5 

#### OS version
Android 8.0 (Oreo) 

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/6254428/46992638-5a062e00-d10b-11e8-8b5a-59f081803825.png)

**Comment by mirka** [comment]
Thank you for this report!

Would you like to post this in the [simplenote-android repo](https://github.com/Automattic/simplenote-android/issues)?
