### ISSUE TITLE
Notes missing in Ubuntu app after update (Simplenote-linux-1.2.1-amd64) / possible data loss?

### ISSUE THREAD

**Issue by marianoju** [Automattic/simplenote-electron#925]
#### Possible steps to reproduce
1. Run Simplenote <= 1.2.0 on Ubuntu 16.04 
2. Close Simplenote and install `Simplenote-linux-1.2.1-amd64.deb`
3. Restart Simplenote. 

#### What I expected
Minor changes, see [Releases](https://github.com/Automattic/simplenote-electron/releases/). 

#### What happened instead
Several notes seem to have disappeared. Some recent notes, some old ones. I have no way to check which. I disconnected all my devices at once. I then proceeded to the [web-interface](https://app.simplenote.com/) and downloaded a ZIP copy of my data. I then compared the content of the ZIP file with the notes on my Android devide (apparently identical). I then restarted  Simplenote 1.2.1 on my Ubuntu device. Still missing notes. I then reinstalled `Simplenote-linux-1.2.1-amd64.deb`. Now some notes have reappeared, but others are (still?) missing. 

#### Simplenote versions 
- [Simplenote-linux-1.2.1-amd64.deb](https://github.com/Automattic/simplenote-electron/releases/download/v1.2.1/Simplenote-linux-1.2.1-amd64.deb) ([see Releases](https://github.com/Automattic/simplenote-electron/releases/tag/v1.2.1))
- [Simplenote 1.6.5 from Google Play](https://play.google.com/store/apps/details?id=com.automattic.simplenote) ([see Releases](https://github.com/Automattic/simplenote-android/releases/tag/v1.6.5))

#### OS version
- Ubuntu 16.04 
- Android 8.0

**Comment by roundhill** [comment]
Is there anything unique about the notes that aren't showing up in Linux? Did you check the trash?

**Comment by roorco** [comment]
I'm having a similar issue. I have updated the software and notes are not showing, but if I create a new note than all notes magically reappear. Quite annoying though. 
I'm using Manjaro 18, Simplenote 1.2.1

**Comment by mirka** [comment]
@roorco Thanks for the report. Your issue is probably https://github.com/Automattic/simplenote-electron/issues/734#issuecomment-418316299 . We will be investigating this 👍

**Comment by marianoju** [comment]
**Summary** 
Some or most notes have reappeared. @roundhill I can not see a pattern here. 

## What I have done 

I have for comparison downloaded a ZIP file from the web application (1,248 files) and I have exported ZIP files from the standalone app after each step described below. 

1. I have closed and relaunched the app. No change. 
2. I have restarted my OS and then relaunched the app. No change. 
3. I have (within the app) logged out of my account, relaunched the app and logged in: 
    - after the 1. relaunch only 238 notes showed up, 
    - after the 2. relaunch only 96 notes showed up, 
    - after the 3. relaunch only 1,092 notes showed up, 
    - after the 4. relaunch only 1,136 notes showed up. 

Obviously this is going in the right direction. Who knows? I might end up with more notes than I originally created! ;-)  Seriously I find this behavior troubling and once again makes me doubt the reliability of the app.

**Comment by roundhill** [comment]
Thanks @marianoju! Are you giving it a bit of time to download all of the notes before you download the export file? A thousand notes might take a while to sync up.

**Comment by marianoju** [comment]
Including the files in the trash today's count seem to be in sync.
