### ISSUE TITLE
Segmentation fault after update to 1.2.1

### ISSUE THREAD

**Issue by segeeslice** [Automattic/simplenote-electron#927]
#### Steps to reproduce
1. Install Simplenote through `snap` on arch linux
    - `snapd` package version 2.34.3-1
2. Attempt to launch Simplenote after installation via `simplenote` command

#### What I expected
Simplenote should launch, as it worked on this computer in previous versions

#### What happened instead
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Segmentation fault (core dumped)
```

App did not launch at all.

It is to my understanding the `canberra-gtk-module` error can be ignored. Confirmed with the snap distribution of Spotify which launches despite these errors.

#### Simplenote version

1.2.1

#### OS version
*(From config files)*
Linux version 4.14.74-1-MANJARO (builduser@development) (gcc version 8.2.1 20180831 (GCC)) #1 SMP PREEMPT Fri Oct 5 14:16:52 UTC 2018

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/32147527/47098944-3b369300-d202-11e8-8907-f16b2903d9ea.png)

**Comment by roundhill** [comment]
Maybe @popey would have some idea on this issue? The snap is managed over at https://github.com/snapcrafters/simplenote

**Comment by segeeslice** [comment]
@roundhill Ahh, confirmed an issue with snap. Installing via AUR works as expected. Will make an issue there. Thanks!
