### ISSUE TITLE
Feature Request: Mass-toggle Markdown on existing notes

### ISSUE THREAD

**Issue by SeanKilleen** [Automattic/simplenote-electron#928]
A follow-up / disambiguation of #573, suggested by @mirka to be split out here.

I have a number of old notes in Simplenote (1,000+), and I would like to convert many of them to markdown rendering within SimpleNote.

Currently, the process to do so would be to click into each note, click the information button, and toggle on Markdown. That's 3,000+ clicks assuming all goes well. 😄 

The feature request is to either:

* Allow for the toggling of markdown on a selection of notes (up to and including all notes), or
* Allow for an action to convert all SimpleNote notes to toggle Markdown on/off.

@mirka has asked to understand how many folks would benefit from this feature; if it is something that could benefit you, please react with a 👍 on this post.

**Comment by SeanKilleen** [comment]
@mirka let me know if I didn't capture something here. Thanks!

**Comment by ianchanning** [comment]
If there needs further examples of why it's useful, I just imported 1400 notes from Evernote, but they weren't tagged with which notebook they were in. I've re-tagged all my Evernote notebooks with mass tagging (it works really well inside Evernote) and I'm going to re-export them. 

But now I have a problem with no good solutions:

1. I could delete all the current Simplenote notes and re-import the notes - this is 1400 clicks (the delete key would be handy here)
2. I could tag the notes one by one - this is click + type tag for 1400 notes

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
