### ISSUE TITLE
On Ubuntu/Linux: Cut with Ctrl-x not working

### ISSUE THREAD

**Issue by luxmile** [Automattic/simplenote-electron#929]
#### Steps to reproduce
1. On Linux, open SimpleNote
2. type some text notes
3. block some parts of the typed text note
4. use Ctrl-x to cut/move text
5. do paste with Ctrl-v to any place inside the editor

#### What I expected
it should paste the cut text on new place

#### What happened instead
but nothing happened, or it paste previously copy/cut text
(it working when use right-click on the selected text, and click cut from context menu item)

#### Simplenote version

Simplenote v1.2.1, installed from downloaded deb package

#### OS version
Ubuntu 18.04

**Comment by rakhi2104** [comment]
It works on my computer though.
Try reinstalling the app. If you still face the same issue, comment here.

**Comment by mirka** [comment]
I can't reproduce this either (Ubuntu 18.04, Simplenote v1.2.1 from downloaded deb package). Is ctrl-x / ctrl-v working in your other apps?

If this issue persists for you, we would need more information to debug it. For example, does it always fail or just under certain conditions?
