### ISSUE TITLE
No note visible behind firewall (Update to Simplenote-electron 1.1.7)

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-electron#930]
#### Steps to reproduce

a) Working at home
- Update to Simplenote-electron 1.1.7 - Windows 10
- Work at home with free internet access as usual and you have access to all your notes
- Shot down your PC (or activate energy safing)

b) Working in your office
- Go to a place behind a firewall which blocks simplenote access (and Evernote etc.), most probably your office place, working in a big company with high web restrictions.
- Start your PC

#### What I expected
- I have access to all my notes, as with the previsous Simplenote-electron versions (last years, months)

#### What happened instead
- There is no note at all visible :-(

#### Simplenote version
- Simplenote-electron 1.1.7

#### OS version
 - Windows 10 (Enterprise)

**Comment by mirka** [comment]
You will need to ask whoever is in charge of the firewall to whitelist these domains:

- `https://api.simperium.com`
- `https://auth.simperium.com`

Related: #789

**Comment by gubrist** [comment]
It did work until today with the previsous Simplenote-electron versions (last years, months).

**Comment by mirka** [comment]
@gubrist Just to make sure that it isn't [a different bug](https://github.com/Automattic/simplenote-electron/issues/734#issuecomment-418316299), can you check if all the notes reappear when you add a new note?

**Comment by gubrist** [comment]
Thanks, mirka

the appereance was indeed the same as with the different bug [Blank Simplenote window - Windows 10 Pro, Simplenote v1.1.3 #734].

Today, I have logged in off-line, established an "open" internet connection with my mobile phone hot spot and it worked.
