### ISSUE TITLE
Menu Bar Colour Change on Update

### ISSUE THREAD

**Issue by ekohilas** [Automattic/simplenote-electron#936]
#### Steps to reproduce
1. Run Simplenote 1.2.1

#### What I expected
Menu bar to be the same colour as the window bar

#### What happened instead
After updating, the menu bar is no longer the same colour as the window bar.

#### Simplenote version
1.2.1

#### OS version
Linux mint 4.4.0-135-generic

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/10705539/47169861-4e577900-d350-11e8-8a37-ecb400477269.png)

**Comment by mirka** [comment]
Thanks for the report! I'm afraid this is an issue between Linux Mint and [Electron itself](https://github.com/electron/electron), since we aren't able to control the menu bar color, as far as I know. (The colors are still matching in Ubuntu, by the way.)
