### ISSUE TITLE
Revisions selector is awkwardly positioned in Focus Mode

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#939]
#### Steps to reproduce
1. Enable Focus Mode
2. Click Revisions button

#### Simplenote version
1.2.1

#### Screenshot

<img width="1087" alt="screen shot 2018-10-20 at 1 17 48" src="https://user-images.githubusercontent.com/555336/47230792-29bdd880-d406-11e8-8e48-a7787304aeb3.png">

#### Proposed fix

A quick fix is to center align it and extend the blue background to the edges.

**Comment by clayreimann** [comment]
Hacktober dibs

**Comment by clayreimann** [comment]
I also tried nesting the revision component in the editor component, but for some reason the DOM of the editor extends beyond the right edge of the window.
