### ISSUE TITLE
Feature request : basic syntax highlighting when editing markdown

### ISSUE THREAD

**Issue by andaag** [Automattic/simplenote-electron#944]
I'd really like to see some basic syntax highlighting of the markdown editor when editing.

When everything is flat white it can be hard to see where the next header begins, compared to the previous one. As it's just a "#" in front of it.

**Comment by alexanderte** [comment]
Totally agree. Formatting headings in bold and showing backticks with monospace would make Markdown preview unnecessary for me.

**Comment by melsophos** [comment]
I also agree with this proposal.

**Comment by leonardonormando** [comment]
I was about to request this feature when found this post. Even simple syntax highlighting  in markdown would be great.

Just to exemplify:
![image](https://user-images.githubusercontent.com/798716/61825347-930bc580-ae36-11e9-8c9a-0c1eaa674d3e.png)

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
