### ISSUE TITLE
Add character count

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#946]
Requested originally on 1491454-zen

At the moment there's already a word count in place, by clicking the "i" icon. Adding a character count too would be great for some users.

> If you think about the various use cases, it is more common to restrict according to the # of characters, rather than words

**Comment by mirka** [comment]
Thanks for bringing this up! I moved this to the [iOS repo](https://github.com/Automattic/simplenote-ios/issues/240) since we already have character counts on the desktop apps.
