### ISSUE TITLE
Simplenote cannot be opened in Windows 10

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-electron#947]
This seems an edge case, as we haven't been able to replicate it (cc: @msilbers ) and we only had one report from an user.

> Windows 10 app will not work. Seems to install and appears on the task bar but will not show up on desktop when I open it.

**They have tried:** 
- Uninstalling it and downloading a new version.
- Uninstalled that and then went to the windows 7/8 version and install that – no difference, same problem.

**Details:**
Windows 10 Pro version 1803
![specs screen shot 2018-10-23](https://user-images.githubusercontent.com/3812076/47334621-b93ae400-d6b1-11e8-9462-eec01ef5ad76.JPG)

Anything we could ask to the user or tell them to try in order to debug this further?

**Comment by mirka** [comment]
We're working on a fix (#1029) to delete the AppData so an uninstall is actually a clean uninstall.

The runaway characters may be related to #642.

**Comment by mirka** [comment]
> We're working on a fix (#1029) to delete the AppData so an uninstall is actually a clean uninstall.

This fix was released in v1.3.2 🎉
