### ISSUE TITLE
Right Click does not work in the Windows Store version

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/simplenote-electron#956]
#### Steps to reproduce

1. Select the text and right click to copy it.

#### What I expected

It should bring up the right click option to copy/cut/paste.

#### What happened instead

It doesn't show any options at all. Right click doesn't bring up any options.

#### Simplenote version
Simplenote Windows app version 1.2.1 

#### OS version

Windows 10 home  and windows 10 pro

#### Screenshot / Video

Ticket: 1513028-zd-woothemes

**Comment by msilbers** [comment]
reported by a Simplenote user in #1519364-zen
on English notes using Windows 10
right click never works, not just in some instances

**Comment by mirka** [comment]
This is likely related to [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker). Since the module must be rebuilt natively, there is a possibility we are not doing this correctly for a particular target.

It might help to know whether the people encountering this issue are on a 32-bit system...?

**Comment by mirka** [comment]
I got a machine that reproduces this issue 👍

**Comment by mirka** [comment]
Seems like this is only happening on the Windows Store version. While we look into this, a temporary workaround would be to use the [non-Windows Store version](https://github.com/Automattic/simplenote-electron/releases/download/v1.2.1/Simplenote-win-1.2.1.exe).

Let me know if this is not the case.

**Comment by damiannep** [comment]
The user confirmed that the non-Windows Store version works.

**Comment by katinthehatsite** [comment]
Another report in #1605568-zen

**Comment by mirka** [comment]
This should now be working in the new v1.3.0 [available in the Windows Store](https://www.microsoft.com/store/productId/9NXQQ40LDW3X). Let us know if you still see issues.
