### ISSUE TITLE
Focus line at bottom page (add extra page)

### ISSUE THREAD

**Issue by fabienbelmonte** [Automattic/simplenote-electron#959]
#### Steps to reproduce
1. Write normal text until the bottom of the page

#### What I expected
I expect the page to add extra space at the bottom to center vertically the focused line.

#### What happened instead
The text goes below the visible window.

#### Simplenote version
v1.2.1

#### OS version
Windows 10

PS: What a wonderfull app! Thanks.

**Comment by ivan-ottinger** [comment]
We have another report. #2140842-zen

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!
