### ISSUE TITLE
No way to move out of Note Editor with a keyboard

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-electron#970]
Once you <kbd>Tab</kbd> into the note editor, subsequent <kbd>Tab</kbd> presses will insert a tab character instead of tabbing out of the editor.

There's an undocumented <kbd>Ctrl+T</kbd> shortcut to go to the Tag Field, but then you get trapped there.

Standard web behavior for <kbd>Tab</kbd>s inside `textarea`s  is to move to the next focusable element. MacOS has a standard <kbd>Ctrl+Opt+Tab</kbd> shortcut that inserts tab chars instead of tabbing out of the textarea. There is also <kbd>Alt+09</kbd> on Windows. I don’t think these are widely known, though.

Reverting to the standard web behavior might be disrupting for some users (#299). 

I think we should keep the current tab-insertion behavior, but add navigational shortcuts that are discoverable in the in-app cheat sheet (#700). This is similar to how [Google Docs](https://support.google.com/docs/answer/179738) does it.

**Comment by belcherj** [comment]
We now have a navigational shortcuts cheat sheet accessible via cmd/ctrl + /. There is also a link to open it from the tab panel.
