### ISSUE TITLE
Community for Issues and Discussions

### ISSUE THREAD

**Issue by rakhi2104** [Automattic/simplenote-electron#972]
- I strongly believe it would be better if there is a Slack or Gitter community so that things can move a bit fast.
- Discussions would be quick and review section doesn't become a chat inbox.

**Comment by roundhill** [comment]
I don't think we really have the resources to support end users via Slack, but a developer community sounds like a good idea. What do you think @mirka?

**Comment by dmsnell** [comment]
As great of an idea as this is it's not on our plan to add. Thanks @rakhi2104!
