### ISSUE TITLE
Add a Next and Previous button to Search facility

### ISSUE THREAD

**Issue by Pyroseza** [Automattic/simplenote-electron#983]
#### What's the scenario
If I have a document with say a 1000 lines, I like to use the search feature to find the exact note I want.

#### What I expected
When I use the search feature I expect it to take me to the first result for the first notebook tab I have, and I would like to see a Next and Previous button to allow me to cycle through the results.

#### What happened instead
Instead what is happening is the search results are being highlighted but I have no quick way to jump to that result, I have to use the scroll bar to find the highlighted piece of text I was looking for, I might as well have just scrolled instead of just searching.

#### Simplenote version
1.2.1

#### OS version
Windows 10

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/8463626/47860011-77174e00-dde7-11e8-96ec-001e633b8cb0.png)

**Comment by Pyroseza** [comment]
I use SimpleNote on my iPhone as well.
The search feature behaves the way I want on iPhone.

**Comment by rakhi2104** [comment]
Or, we could add some key points to the scroll section to quickly jump to that part of the Note.

**Comment by mirka** [comment]
Good suggestion! This should probably be a part of #624.

**Comment by msjasinski** [comment]
The lack of this feature is why I avoid keeping long notes in Simplenote. Two extra buttons or an implemented F3 shortcut would be enough to change it.

**Comment by thehenrybyrd** [comment]
Had a request for this in #2299133-zen

**Comment by belcherj** [comment]
Thanks! I’ve added this to our feature requests!

**Comment by msjasinski** [comment]
not implemented yet - so why is this closed?

**Comment by belcherj** [comment]
We close feature requests on the repo and add them to our internal feature request tracking tool.

**Comment by krzysztofzygmunt** [comment]
I'd also be more than happy if there was a shortcut to jump to another search result within a note.
Thanks.

BTW.
Is there a shortcut to switch to a note content from search box ?

**Comment by codebykat** [comment]
Thanks for these suggestions, @krzysztofzygmunt! We've been making some improvements to search and I'd love to get to them soon.

If you're using Simplenote in the browser, using the browser's built-in search might be a useful workaround for searching long notes. That will allow you to go to next and previous results within a note.

If you're in the search box, you can hit CTRL+T to get to the note content. Hitting it again jumps between the tag input and note.

We definitely do need to revisit keyboard shortcuts though. There's a few open issues already (#1167, #700, etc.)

**Comment by codebykat** [comment]
This has been implemented, along with keyboard shortcuts.
