### ISSUE TITLE
Keyboard shortcut for preview on / off

### ISSUE THREAD

**Issue by rschouwenburg** [Automattic/simplenote-electron#985]
I'd love to see a keyboard shortcut to switch between preview and edit modes.

**Comment by mirka** [comment]
Thanks. We actually have this, but it's undocumented at the moment. It's <kbd>Ctrl+Shift+P</kbd>. I'm hoping to make all the shortcuts discoverable in an in-app shortcut cheat sheet, and perhaps also tooltips. (Related: #700)

**Comment by triangulum** [comment]
It's worth adding that after exiting the preview mode, the cursor should return to the original editing position, so the user can keep on writing. This would be a kind of *write-check-write* methodology.

At the moment, the cursor simple disappears and the document becomes inactive, which means you have to move your hands off the keyboard, and use the mouse to reposition the cursor.

**Comment by mirka** [comment]
@triangulum I agree 100%. We're tracking this enhancement at #331

**Comment by mirka** [comment]
A shortcut hint will be added as a tooltip in #1214.
