### ISSUE TITLE
Simplenote Windows chokes on an email address included in the title for a link.

### ISSUE THREAD

**Issue by billrobbins** [Automattic/simplenote-electron#993]
refer to Markdown syntax - Links (https://daringfireball.net/projects/markdown/syntax#link)

In Simplenote Windows 1.2.1, when an email address is included in the title for a link, it breaks the reference’s formatting. This does not happen on other platforms. It seems the email address is being interpreted as it’s own link even though within quoted text.

Example
```
[Reference link][1]

[1]: http:www.a.sample.reference.com "one two three@four.com five six"

[Inline link](http:www.a.sample.reference.com "one two three@four.com five six") 
i.e. Link text = "Reference link" or "Inline link" URL = " http:www.a.sample.reference.com" Title = "one two three@four.com five six"
```
This should produce

Reference link

Inline link

but on Simplenote Windows 1.2.1, produces
```
three@four.com five sixReference link

three@four.com five sixInline link
```

* The email address presents as the link text. This is followed by the text which followed the email address in the title, then by the intended link text. 
* The text which precedes it in the title is included as the actual title to the link. 
* The original URL remains as the URL, now attached to an email address link text rather than the intended link text.

This issue is from a user reported ticket (ZD-1546141)

**Comment by mirka** [comment]
This seems to be a bug in the Markdown module we are using. I posted a bug report here: https://github.com/showdownjs/showdown/issues/632
