### ISSUE TITLE
Windows app crashes when working in Chinese

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-electron#994]
A user is reporting that Simplenote on Windows crashes when they are deleting characters or making other edits. They are typing latin characters and have something that changes it to Chinese (input method application called Shouxin input method).

This started when they updated to 1.2.1 but going back to 1.1.7 (in a virtual machine) did not resolve the issue
They have tried both the Windows 10 Simplenote version and the Windows 7/8 Simplenote version

This happens with any kind of edit to a note (but not adding or deleting a note) and happens to many notes, but not necessarily all. The user is basically unable to use the Windows app right now.

#### Simplenote version
Both 1.2.1 and 1.1.7

#### OS version
Windows 10 (version 1809)

#### Screenshot / Video
video in #1520291-zen

**Comment by mirka** [comment]
Closing this in favor of #780, since I was able to confirm from the user's video that they were indeed typing after a Tab character.
