### ISSUE TITLE
Email Address Overrides Filter Field In Chrome On Windows

### ISSUE THREAD

**Issue by billrobbins** [Automattic/simplenote-electron#995]
#### Steps to reproduce
1. Open web version of SimpleNote in Chrome on Windows.
2. Email address appears in filter field clearing out list.
3. Click on any note and the filter field will again be filled with email address.

#### What I expected
Nothing appearing in the filter unless directly input there.

#### Simplenote version
Crome 70.0.3538.77/Windows.
The user did report this did not happen Firefox.  
I did not notice this in Chrome  70.0.3538.77 for Mac.

---

From ZD-1552429
The page loads fine, however the filter edit box is immediately populated with my email address. Upon clicking on any note, it is again populated with the email address, resulting in all the notes being cleared from view.

This was not a problem as recent as yesterday (though Chrome had been updated last night). I haven't checked on Mac, yet. Doesn't happen on Firefox.

**Comment by mirka** [comment]
Thanks for the report! I'm going to close this and move it to the web app repo (which is currently private) 👍

**Comment by w3sip** [comment]
A few things I've noticed:
- This doesn't seem to happen in Private Mode (nor on another instance of the browser).
- Attempt to clear local storage and cookies from Inspect panel didn't fix the problem.

Seems like a state issue to me, but not sure what element of local state can be cleared to fix it.
